<a href="https://colab.research.google.com/github/skywalker0803r/CFB/blob/main/%E6%BB%BE%E5%8B%95%E5%BC%8F%E9%A0%90%E6%B8%ACy2_R20929_aa2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# load data

In [18]:
import pandas as pd

df = pd.read_csv('aa2.csv')
df['Time'] = pd.to_datetime(df['Time'])
df.set_index('Time', inplace=True)
for i in df.columns:
    df[i] = pd.to_numeric(df[i], errors='coerce')
df.head()

,DeSOx_2nd,MLUT4_AIA792101A,MLUT4_AIA792101B,MLUT4_AT.232A,MLUT4_AT.237,MLUT4_FIC.231A,MLUT4_FIC.231B,MLUT4_FIC.231C,MLUT4_FIC.233,MLUT4_FIQ.2BTCF,...,MLUT4_TE.953B,MLUT4_TE.954A,MLUT4_TE.954B,MLUT4_FT.956,MLUT4_FT.957,MLUT4_IT.B7926A,MLUT4_IT.B7926B,MLUT4_IT.B7926C,前爐SOx濃度,鈣硫比
Time,,,,,,,,,,,,,,,,,,,,,
2025-05-24 20:10:05,0.998264,0.874767,0.871931,0.903664,0.876600,0.859543,0.871945,0.845141,0.832117,0.876444,...,0.829285,0.832349,0.835281,0.870939,0.871488,0.868410,0.870792,0.871566,0.875007,0.874200
2025-05-24 20:15:05,0.998938,0.874863,0.871931,0.901274,0.873041,0.859832,0.866944,0.837614,0.827172,0.877525,...,0.838669,0.839210,0.842528,0.871118,0.871320,0.869278,0.870798,0.871566,0.885554,0.874429
2025-05-24 20:20:05,0.999351,0.874863,0.871931,0.900675,0.868550,0.860121,0.866244,0.837599,0.829646,0.877644,...,0.847407,0.847462,0.852678,0.870893,0.871001,0.869786,0.870586,0.871566,0.884352,0.874434
2025-05-24 20:25:05,0.999802,0.874863,0.871931,0.898537,0.871577,0.860410,0.867020,0.837585,0.825525,0.877747,...,0.855577,0.855032,0.856321,0.870912,0.871840,0.870371,0.870566,0.871566,0.873928,0.894053
2025-05-24 20:30:05,0.893009,0.874863,0.871917,0.895382,0.871097,0.860699,0.866028,0.837570,0.840381,0.877759,...,0.854596,0.862678,0.865071,0.870999,0.871706,0.869696,0.870432,0.871566,0.880042,0.871179

In [19]:
特徵篩選結果 = pd.read_excel('/content/特徵篩選結果（10s間隔彙整後）.xlsx',sheet_name='Y2')
features = list(特徵篩選結果.head(40)['Feature'])
print(features)
特徵篩選結果.head()

['MLUT4_AT.232A', 'MLUT4_RQ.2BTLS', 'MLUT4_TE.252A', 'MLUT4_SIV.B7921', 'MLUT4_AIA792101B', 'MLUT4_PDT.956', 'MLUT4_TE.252F', 'MLUT4_PT.231', 'MLUT4_FIC.231C', 'MLUT4_FIC.231A', 'MLUT4_FT.232', 'MLUT4_TE.251A', 'MLUT4_FT.951AA', 'MLUT4_FT.951BB', 'MLUT4_TE.251I', 'MLUT4_TE.255A', 'MLUT4_AIA792101A', 'MLUT4_TE.255B', 'MLUT4_FIC.233', 'MLUT4_IT.E7925A', 'MLUT4_TE.254A', 'MLUT4_TE.951A', 'MLUT4_ZT.231', 'MLUT4_TE.236C', 'MLUT4_AT.237', 'MLUT4_FT.792003', 'MLUT4_TE.236A', 'MLUT4_FQ.239', 'MLUT4_TE.252E', 'MLUT4_IT.B7926B', '前爐SOx濃度', 'MLUT4_PDIC.233', 'MLUT4_TE.252G', 'MLUT4_TE.954B', 'MLUT4_IT.B7926C', 'MLUT4_IT.E7925B', 'MLUT4_FT.V004', 'MLUT4_TE.252D', '鈣硫比', 'MLUT4_RT.041']

,Feature,pearson_score,lasso_score,permutation_score,rfe_score,rf_score,total_score,final_rank,Varv,import
0,MLUT4_AT.232A,88,80,88.0,34,85,375.0,1.0,ECO_NOx,NaN
1,MLUT4_RQ.2BTLS,81,78,85.0,41,87,372.0,2.0,石灰石,V
2,MLUT4_TE.252A,69,68,84.0,76,70,367.0,3.0,上層爐溫A,NaN
3,MLUT4_SIV.B7921,65,77,82.0,37,86,347.0,4.0,PAF變頻轉速,NaN
4,MLUT4_AIA792101B,26,87,81.0,65,79,338.0,5.0,ECO_O2_B,NaN

In [20]:
dataall = pd.read_csv('/content/Datall(d)new.csv')
dataall['Time'] = pd.to_datetime(dataall['Time'])
dataall.set_index('Time', inplace=True)
dataall.head()

,MLUT4_AIC.232B,MLUT4_AT.240,MLUT4_FIQ.2BTCF,DeSOx_1st,DeSOx_2nd
Time,,,,,
2025-05-24 20:02:45,37.927130,0.075534,39.117515,0.931564,0.998008
2025-05-24 20:02:55,37.377069,0.075027,39.152805,0.932554,0.997993
2025-05-24 20:03:05,36.840427,0.074521,39.178716,0.933661,0.997977
2025-05-24 20:03:15,36.402475,0.074014,39.201588,0.934563,0.997967
2025-05-24 20:03:25,35.984424,0.073507,39.224352,0.935067,0.997957

In [21]:
df = df.join(dataall[['MLUT4_AIC.232B', 'MLUT4_AT.240']], how='left')
df.head()

,DeSOx_2nd,MLUT4_AIA792101A,MLUT4_AIA792101B,MLUT4_AT.232A,MLUT4_AT.237,MLUT4_FIC.231A,MLUT4_FIC.231B,MLUT4_FIC.231C,MLUT4_FIC.233,MLUT4_FIQ.2BTCF,...,MLUT4_TE.954B,MLUT4_FT.956,MLUT4_FT.957,MLUT4_IT.B7926A,MLUT4_IT.B7926B,MLUT4_IT.B7926C,前爐SOx濃度,鈣硫比,MLUT4_AIC.232B,MLUT4_AT.240
Time,,,,,,,,,,,,,,,,,,,,,
2025-05-24 20:10:05,0.998264,0.874767,0.871931,0.903664,0.876600,0.859543,0.871945,0.845141,0.832117,0.876444,...,0.835281,0.870939,0.871488,0.868410,0.870792,0.871566,0.875007,0.874200,30.672325,0.053241
2025-05-24 20:15:05,0.998938,0.874863,0.871931,0.901274,0.873041,0.859832,0.866944,0.837614,0.827172,0.877525,...,0.842528,0.871118,0.871320,0.869278,0.870798,0.871566,0.885554,0.874429,35.814025,0.038041
2025-05-24 20:20:05,0.999351,0.874863,0.871931,0.900675,0.868550,0.860121,0.866244,0.837599,0.829646,0.877644,...,0.852678,0.870893,0.871001,0.869786,0.870586,0.871566,0.884352,0.874434,35.217820,0.022841
2025-05-24 20:25:05,0.999802,0.874863,0.871931,0.898537,0.871577,0.860410,0.867020,0.837585,0.825525,0.877747,...,0.856321,0.870912,0.871840,0.870371,0.870566,0.871566,0.873928,0.894053,38.660620,0.007641
2025-05-24 20:30:05,0.893009,0.874863,0.871917,0.895382,0.871097,0.860699,0.866028,0.837570,0.840381,0.877759,...,0.865071,0.870999,0.871706,0.869696,0.870432,0.871566,0.880042,0.871179,45.777777,4.897829

# help function

In [22]:
def y2_2_y3(DeSOx_2nd,MLUT4_AIC_232B):
  return MLUT4_AIC_232B * (1 - DeSOx_2nd)

def y2y3_2_MLUT4_AIC_232B(DeSOx_2nd, MLUT4_AT_240):
    if DeSOx_2nd == 1:
        DeSOx_2nd == 0.999
    return MLUT4_AT_240 / (1 - DeSOx_2nd)

def solve_DeSOx_2nd(MLUT4_AT_240, MLUT4_AIC_232B):
    if MLUT4_AIC_232B == 0:
        MLUT4_AIC_232B = 0.001
    return 1 - (MLUT4_AT_240 / MLUT4_AIC_232B)

def select_by_rule(df):
  coal_low = df[df["MLUT4_FIQ.2BTCF"] < 20]
  sox = df["MLUT4_AT.240"]
  constant_sox_indices = sox[sox.shift(1) == sox][(sox.shift(2) == sox) & (sox.shift(-1) == sox)].index
  constant_sox = df.loc[constant_sox_indices]
  common_index = coal_low.index.union(constant_sox.index)
  return common_index

In [23]:
print(y2_2_y3(df['DeSOx_2nd'],df['MLUT4_AIC.232B']).values,df['MLUT4_AT.240'].values)
print(df.apply(lambda row: solve_DeSOx_2nd(row['MLUT4_AT.240'], row['MLUT4_AIC.232B']), axis=1).values,df['DeSOx_2nd'].values)
print(df.apply(lambda row: y2y3_2_MLUT4_AIC_232B(row['DeSOx_2nd'], row['MLUT4_AT.240']), axis=1).values,df['MLUT4_AIC.232B'].values)

[5.32408375e-02 3.80409050e-02 2.28409398e-02 ... 7.01048297e+00
 2.58543040e+01 2.08521792e+01] [5.32408310e-02 3.80408910e-02 2.28409510e-02 ... 7.01048297e+00
 2.58543040e+01 2.08521792e+01]
[0.99826421 0.99893782 0.99935144 ... 0.85899774 0.62143059 0.63300706] [0.99826421 0.99893782 0.99935144 ... 0.85899774 0.62143059 0.63300706]
[30.67232114 35.81401157 35.21783731 ... 49.71893904 68.29475218
 56.81902033] [30.67232489 35.81402473 35.2178201  ... 49.71893908 68.29475217
 56.81902038]

# main

In [24]:
import pandas as pd
import xgboost as xgb
import numpy as np
from tqdm import tqdm
import warnings
warnings.filterwarnings("ignore")
import pickle
from pykalman import KalmanFilter

df_metrics_list = []
df_metrics_list_y3 = []
result_df_list = []
origin_df = df.copy()

for i in tqdm(range(1,10)):
  df['DeSOx_2nd'] = origin_df['DeSOx_2nd'].shift(-i)
  df["prev_target"] = origin_df[target_col].shift(1)

  # select_by_rule
  common_index = select_by_rule(dataall)
  select_df = df.loc[~df.index.isin(common_index), :]

  # select features
  features = list(特徵篩選結果.head(40)['Feature'])

  # define y_col
  y_col = 'DeSOx_2nd'
  select_df = select_df[features+[y_col]+['MLUT4_AIC.232B', 'MLUT4_AT.240','prev_target']]

  # --- Modeling Code (Corrected Part) ---
  def train_model(train_X, train_y):
      model = xgb.XGBRegressor(
          n_estimators=900,
          random_state=42,
          n_jobs=-1,
          learning_rate=0.028,
          max_depth=8,
          subsample=0.75,
          colsample_bytree=0.75,
          objective='reg:squarederror',
          tree_method='hist'
      )
      return model.fit(train_X, train_y)

  # 1. 時間排序
  select_df = select_df.sort_index()

  # 2. 設定
  target_col = y_col
  time_windows_len = 100 #<--- 調整這裡

  # 效率不應該低於0
  select_df = select_df[select_df["prev_target"]>0]
  select_df = select_df[select_df[y_col]>0]

  # 卡爾曼濾波
  def apply_kalman_filter(series,transition_covariance=0.01,observation_covariance=1.0,initial_state_covariance=1.0):
      series = series.fillna(method='ffill')
      kf = KalmanFilter(
          initial_state_mean=series.iloc[0],
          initial_state_covariance=initial_state_covariance,
          transition_matrices=1.0,
          observation_matrices=1.0,
          transition_covariance=transition_covariance,
          observation_covariance=observation_covariance,
          n_dim_obs=1
      )
      state_means, _ = kf.smooth(series.values)
      return state_means.flatten()

  # 套用卡爾曼濾波
  select_df["prev_target"] = apply_kalman_filter(select_df["prev_target"])
  select_df[y_col] = apply_kalman_filter(select_df[y_col])

  # 定義y3
  select_df['MLUT4_AT-240'] = y2_2_y3(select_df['DeSOx_2nd'],select_df['MLUT4_AIC.232B'])


  # 刪除因 shift 產生的 NaN 資料
  select_df = select_df.dropna().sort_index()

  # 定義特徵欄位除了時間跟target_col不能用其他都可以用
  feature_cols = [col for col in select_df.columns if col not in ['timestamp', target_col]]

  # 開始訓練的索引
  start_idx = time_windows_len

  # 計算total_steps
  total_steps = len(select_df) - start_idx

  # 3. 儲存預測結果
  predictions = []
  y3_predictions = []
  abs_errors = []
  y3_abs_errors = []
  thresholds = []
  indices = []
  MLUT4_AT_240_list = []

  # To store recent errors for threshold calculation for the *current* model
  current_model_recent_errors = []
  threshold_update_window = 100 # Calculate threshold from last 100 errors
  percentile_for_threshold = 90 # 90th percentile of recent errors

  # 4. 初始化進度條
  pbar = tqdm(total=total_steps)

  # 5. 動態預測迴圈
  i = start_idx
  error_exceeded_threshold = True  # Start with training a model

  while i < len(select_df):
      # 早停判斷<不得移除>
      print(pbar)
      if pbar.n >= 1000: # This means it will stop after 1500 predictions, not 1000 training steps.
          break

      # 判斷是否要建模 並記錄
      if 'current_model' not in locals() or error_exceeded_threshold:
          train_df = select_df.iloc[i - time_windows_len:i]
          train_X = train_df[feature_cols]
          train_y = train_df[target_col]

          # train model start
          current_model = train_model(train_X, train_y)

          # Reset recent errors for the new model
          current_model_recent_errors = []
          # For the first prediction after re-training, we won't have enough recent errors
          # to calculate a meaningful threshold. We can set a default or wait.
          # Here, we'll simply let the first few errors build up before calculating.
          current_threshold = np.inf # Set a very high threshold initially for a newly trained model

          error_exceeded_threshold = False # Reset flag

      # 預測i
      test_row = select_df.iloc[i]
      test_X = test_row[feature_cols].values.reshape(1, -1)
      true_y = test_row[target_col]
      pred_y = current_model.predict(test_X)[0]
      error = abs(pred_y - true_y)

      # 反推y3
      pred_y3 = y2_2_y3(pred_y,test_row['MLUT4_AIC.232B'])
      error_y3 = abs(pred_y3 - test_row['MLUT4_AT-240'])

      # Add the current error to the list of recent errors for this model
      current_model_recent_errors.append(error)

      # If we have enough recent errors, calculate the threshold for the *current* model's performance
      if len(current_model_recent_errors) >= threshold_update_window:
          current_threshold = np.percentile(current_model_recent_errors[-threshold_update_window:], percentile_for_threshold)
      elif len(current_model_recent_errors) > 0: # If less than window size, use all available errors
          current_threshold = np.percentile(current_model_recent_errors, percentile_for_threshold)
      else:
          current_threshold = np.inf # Should ideally not happen after first few predictions

      # 紀錄
      predictions.append(pred_y)
      y3_predictions.append(pred_y3)

      abs_errors.append(error)
      y3_abs_errors.append(error_y3)

      thresholds.append(current_threshold)
      indices.append(i)

      # 更新進度條
      pbar.update(1)

      # 根據預測i的結果判斷是否要設置error_exceeded_threshold
      # The check for re-training now uses the threshold calculated from actual recent test errors
      if error > current_threshold:
          error_exceeded_threshold = True
          # If error exceeds, a new model will be trained in the next iteration
          # and 'i' increments by 1
          i += 1
      else:
          # If error does not exceed, stay with the current model for the next prediction
          # 'i' increments by 1, and the loop will try to predict 'i+1' with the *same* model
          i += 1
          error_exceeded_threshold = False # Continue using current model

  # 結束訓練
  pbar.close()

  # 6. 輸出結果表
  result_df = select_df.iloc[indices].copy()
  result_df['prediction'] = predictions
  result_df['abs_error'] = abs_errors
  result_df['threshold'] = thresholds
  result_df['y3_prediction'] = y3_predictions
  result_df['y3_abs_error'] = y3_abs_errors

  # 預覽結果
  print(result_df.head())

  from sklearn.metrics import r2_score, mean_squared_error
  import numpy as np

  # 指標評估
  y_true = result_df[y_col]
  y_pred = result_df['prediction']

  # Calculate R-squared
  r2 = r2_score(y_true, y_pred)
  # Calculate RMSE
  rmse = np.sqrt(mean_squared_error(y_true, y_pred))
  # Calculate MAPE
  mape = np.mean(np.abs((y_true - y_pred) / y_true[y_true != 0])) * 100 if np.any(y_true != 0) else 0


  # 假設 r2, rmse, mape 是事先計算好的指標
  metrics = {
      'Metric': ['R-squared', 'RMSE', 'MAPE'],
      'Value': [r2, rmse, mape],
      'Unit': ['', '', '%']
  }
  df_metrics = pd.DataFrame(metrics)
  df_metrics_list.append(df_metrics)

  # 指標評估
  y_true = result_df['MLUT4_AT-240']
  y_pred = result_df['y3_prediction']

  # Calculate R-squared
  r2 = r2_score(y_true, y_pred)
  # Calculate RMSE
  rmse = np.sqrt(mean_squared_error(y_true, y_pred))
  # Calculate MAPE
  mape = np.mean(np.abs((y_true - y_pred) / y_true[y_true != 0])) * 100 if np.any(y_true != 0) else 0


  # 假設 r2, rmse, mape 是事先計算好的指標
  metrics = {
      'Metric': ['R-squared', 'RMSE', 'MAPE'],
      'Value': [r2, rmse, mape],
      'Unit': ['', '', '%']
  }
  df_metrics = pd.DataFrame(metrics)
  df_metrics_list_y3.append(df_metrics)

  0%|          | 0/9 [00:00<?, ?it/s]
  0%|          | 0/7494 [00:00<?, ?it/s]

  0%|          | 0/7494 [00:00<?, ?it/s]

  0%|          | 1/7494 [00:00<1:06:37,  1.87it/s]

  0%|          | 1/7494 [00:00<1:06:37,  1.87it/s]
  0%|          | 2/7494 [00:00<1:06:36,  1.87it/s]

  0%|          | 3/7494 [00:01<40:39,  3.07it/s]

  0%|          | 3/7494 [00:01<40:39,  3.07it/s]
  0%|          | 4/7494 [00:01<40:39,  3.07it/s]
  0%|          | 5/7494 [00:01<40:38,  3.07it/s]

  0%|          | 6/7494 [00:01<30:01,  4.16it/s]

  0%|          | 6/7494 [00:01<30:01,  4.16it/s]
  0%|          | 7/7494 [00:01<30:00,  4.16it/s]
  0%|          | 8/7494 [00:01<30:00,  4.16it/s]
  0%|          | 9/7494 [00:01<30:00,  4.16it/s]

  0%|          | 10/7494 [00:02<22:23,  5.57it/s]

  0%|          | 10/7494 [00:02<22:23,  5.57it/s]
  0%|          | 11/7494 [00:02<22:23,  5.57it/s]
  0%|          | 12/7494 [00:02<22:23,  5.57it/s]

  0%|          | 13/7494 [00:02<22:05,  5.64it/s]

  0%|          | 13/7494 [00:02<22:05,  5.64it/s]
  0%|          | 14/7494 [00:02<22:05,  5.64it/s]
  0%|          | 15/7494 [00:02<22:05,  5.64it/s]
  0%|          | 16/7494 [00:02<22:05,  5.64it/s]
  0%|          | 17/7494 [00:02<22:05,  5.64it/s]
  0%|          | 18/7494 [00:02<22:04,  5.64it/s]
  0%|          | 19/7494 [00:02<22:04,  5.64it/s]

  0%|          | 20/7494 [00:03<14:31,  8.57it/s]

  0%|          | 20/7494 [00:03<14:31,  8.57it/s]
  0%|          | 21/7494 [00:03<14:31,  8.57it/s]

  0%|          | 22/7494 [00:03<17:40,  7.04it/s]

  0%|          | 22/7494 [00:03<17:40,  7.04it/s]
  0%|          | 23/7494 [00:03<17:40,  7.04it/s]

  0%|          | 24/7494 [00:04<20:12,  6.16it/s]

  0%|          | 24/7494 [00:04<20:12,  6.16it/s]
  0%|          | 25/7494 [00:04<20:12,  6.16it/s]

  0%|          | 26/7494 [00:04<22:42,  5.48it/s]

  0%|          | 26/7494 [00:04<22:42,  5.48it/s]
  0%|          | 27/7494 [00:04<22:42,  5.48it/s]

  0%|          | 28/7494 [00:05<24:13,  5.14it/s]

  0%|          | 28/7494 [00:05<24:13,  5.14it/s]
  0%|          | 29/7494 [00:05<24:12,  5.14it/s]

  0%|          | 30/7494 [00:05<25:42,  4.84it/s]

  0%|          | 30/7494 [00:05<25:42,  4.84it/s]
  0%|          | 31/7494 [00:05<25:42,  4.84it/s]
  0%|          | 32/7494 [00:05<25:42,  4.84it/s]
  0%|          | 33/7494 [00:05<25:42,  4.84it/s]

  0%|          | 34/7494 [00:06<21:04,  5.90it/s]

  0%|          | 34/7494 [00:06<21:04,  5.90it/s]
  0%|          | 35/7494 [00:06<21:04,  5.90it/s]

  0%|          | 36/7494 [00:06<22:54,  5.43it/s]

  0%|          | 36/7494 [00:06<22:54,  5.43it/s]
  0%|          | 37/7494 [00:06<22:54,  5.43it/s]

  1%|          | 38/7494 [00:09<1:02:09,  2.00it/s]

  1%|          | 38/7494 [00:09<1:02:09,  2.00it/s]
  1%|          | 39/7494 [00:09<1:02:08,  2.00it/s]

  1%|          | 40/7494 [00:09<54:07,  2.30it/s]

  1%|          | 40/7494 [00:09<54:07,  2.30it/s]
  1%|          | 41/7494 [00:09<54:06,  2.30it/s]

  1%|          | 42/7494 [00:10<47:31,  2.61it/s]

  1%|          | 42/7494 [00:10<47:31,  2.61it/s]
  1%|          | 43/7494 [00:10<47:30,  2.61it/s]

  1%|          | 44/7494 [00:10<42:46,  2.90it/s]

  1%|          | 44/7494 [00:10<42:46,  2.90it/s]
  1%|          | 45/7494 [00:10<42:45,  2.90it/s]
  1%|          | 46/7494 [00:10<42:45,  2.90it/s]

  1%|          | 47/7494 [00:11<34:30,  3.60it/s]

  1%|          | 47/7494 [00:11<34:30,  3.60it/s]
  1%|          | 48/7494 [00:11<34:30,  3.60it/s]

  1%|          | 49/7494 [00:11<33:08,  3.74it/s]

  1%|          | 49/7494 [00:11<33:08,  3.74it/s]
  1%|          | 50/7494 [00:11<33:08,  3.74it/s]
  1%|          | 51/7494 [00:11<33:08,  3.74it/s]

  1%|          | 52/7494 [00:12<28:39,  4.33it/s]

  1%|          | 52/7494 [00:12<28:39,  4.33it/s]
  1%|          | 53/7494 [00:12<28:39,  4.33it/s]
  1%|          | 54/7494 [00:12<28:39,  4.33it/s]

  1%|          | 55/7494 [00:12<25:47,  4.81it/s]

  1%|          | 55/7494 [00:12<25:47,  4.81it/s]
  1%|          | 56/7494 [00:12<25:47,  4.81it/s]

  1%|          | 57/7494 [00:13<27:03,  4.58it/s]

  1%|          | 57/7494 [00:13<27:03,  4.58it/s]
  1%|          | 58/7494 [00:13<27:02,  4.58it/s]

  1%|          | 59/7494 [00:13<27:34,  4.49it/s]

  1%|          | 59/7494 [00:13<27:34,  4.49it/s]
  1%|          | 60/7494 [00:13<27:34,  4.49it/s]

  1%|          | 61/7494 [00:14<28:24,  4.36it/s]

  1%|          | 61/7494 [00:14<28:24,  4.36it/s]
  1%|          | 62/7494 [00:14<28:24,  4.36it/s]
  1%|          | 63/7494 [00:14<28:24,  4.36it/s]

  1%|          | 64/7494 [00:14<25:04,  4.94it/s]

  1%|          | 64/7494 [00:14<25:04,  4.94it/s]
  1%|          | 65/7494 [00:14<25:04,  4.94it/s]

  1%|          | 66/7494 [00:15<26:24,  4.69it/s]

  1%|          | 66/7494 [00:15<26:24,  4.69it/s]
  1%|          | 67/7494 [00:15<26:24,  4.69it/s]

  1%|          | 68/7494 [00:15<27:00,  4.58it/s]

  1%|          | 68/7494 [00:15<27:00,  4.58it/s]
  1%|          | 69/7494 [00:15<27:00,  4.58it/s]

  1%|          | 70/7494 [00:16<27:58,  4.42it/s]

  1%|          | 70/7494 [00:16<27:58,  4.42it/s]
  1%|          | 71/7494 [00:16<27:58,  4.42it/s]
  1%|          | 72/7494 [00:16<27:57,  4.42it/s]
  1%|          | 73/7494 [00:16<27:57,  4.42it/s]
  1%|          | 74/7494 [00:16<27:57,  4.42it/s]

  1%|          | 75/7494 [00:16<19:57,  6.19it/s]

  1%|          | 75/7494 [00:16<19:57,  6.19it/s]
  1%|          | 76/7494 [00:16<19:57,  6.19it/s]
  1%|          | 77/7494 [00:16<19:57,  6.19it/s]

  1%|          | 78/7494 [00:17<19:53,  6.21it/s]

  1%|          | 78/7494 [00:17<19:53,  6.21it/s]
  1%|          | 79/7494 [00:17<19:53,  6.21it/s]

  1%|          | 80/7494 [00:17<21:55,  5.63it/s]

  1%|          | 80/7494 [00:17<21:55,  5.63it/s]
  1%|          | 81/7494 [00:17<21:55,  5.63it/s]

  1%|          | 82/7494 [00:18<23:41,  5.22it/s]

  1%|          | 82/7494 [00:18<23:41,  5.22it/s]
  1%|          | 83/7494 [00:18<23:40,  5.22it/s]

  1%|          | 84/7494 [00:18<26:22,  4.68it/s]

  1%|          | 84/7494 [00:18<26:22,  4.68it/s]
  1%|          | 85/7494 [00:18<26:22,  4.68it/s]

  1%|          | 86/7494 [00:19<28:11,  4.38it/s]

  1%|          | 86/7494 [00:19<28:11,  4.38it/s]
  1%|          | 87/7494 [00:19<28:11,  4.38it/s]

  1%|          | 88/7494 [00:21<1:07:46,  1.82it/s]

  1%|          | 88/7494 [00:21<1:07:46,  1.82it/s]
  1%|          | 89/7494 [00:21<1:07:46,  1.82it/s]
  1%|          | 90/7494 [00:21<1:07:45,  1.82it/s]

  1%|          | 91/7494 [00:22<51:22,  2.40it/s]

  1%|          | 91/7494 [00:22<51:22,  2.40it/s]
  1%|          | 92/7494 [00:22<51:21,  2.40it/s]

  1%|          | 93/7494 [00:23<46:17,  2.66it/s]

  1%|          | 93/7494 [00:23<46:17,  2.66it/s]
  1%|▏         | 94/7494 [00:23<46:16,  2.66it/s]

  1%|▏         | 95/7494 [00:23<43:07,  2.86it/s]

  1%|▏         | 95/7494 [00:23<43:07,  2.86it/s]
  1%|▏         | 96/7494 [00:23<43:07,  2.86it/s]

  1%|▏         | 97/7494 [00:24<40:09,  3.07it/s]

  1%|▏         | 97/7494 [00:24<40:09,  3.07it/s]
  1%|▏         | 98/7494 [00:24<40:09,  3.07it/s]

  1%|▏         | 99/7494 [00:24<38:50,  3.17it/s]

  1%|▏         | 99/7494 [00:24<38:50,  3.17it/s]
  1%|▏         | 100/7494 [00:24<38:50,  3.17it/s]
  1%|▏         | 101/7494 [00:24<38:50,  3.17it/s]

  1%|▏         | 102/7494 [00:25<32:27,  3.80it/s]

  1%|▏         | 102/7494 [00:25<32:27,  3.80it/s]
  1%|▏         | 103/7494 [00:25<32:26,  3.80it/s]

  1%|▏         | 104/7494 [00:25<33:06,  3.72it/s]

  1%|▏         | 104/7494 [00:25<33:06,  3.72it/s]
  1%|▏         | 105/7494 [00:25<33:05,  3.72it/s]

  1%|▏         | 106/7494 [00:26<33:15,  3.70it/s]

  1%|▏         | 106/7494 [00:26<33:15,  3.70it/s]
  1%|▏         | 107/7494 [00:26<33:15,  3.70it/s]

  1%|▏         | 108/7494 [00:26<33:41,  3.65it/s]

  1%|▏         | 108/7494 [00:26<33:41,  3.65it/s]
  1%|▏         | 109/7494 [00:26<33:40,  3.65it/s]

  1%|▏         | 110/7494 [00:27<33:27,  3.68it/s]

  1%|▏         | 110/7494 [00:27<33:27,  3.68it/s]
  1%|▏         | 111/7494 [00:27<33:27,  3.68it/s]

  1%|▏         | 112/7494 [00:28<33:41,  3.65it/s]

  1%|▏         | 112/7494 [00:28<33:41,  3.65it/s]
  2%|▏         | 113/7494 [00:28<33:41,  3.65it/s]

  2%|▏         | 114/7494 [00:28<33:09,  3.71it/s]

  2%|▏         | 114/7494 [00:28<33:09,  3.71it/s]
  2%|▏         | 115/7494 [00:28<33:09,  3.71it/s]
  2%|▏         | 116/7494 [00:28<33:09,  3.71it/s]

  2%|▏         | 117/7494 [00:29<28:58,  4.24it/s]

  2%|▏         | 117/7494 [00:29<28:58,  4.24it/s]
  2%|▏         | 118/7494 [00:29<28:58,  4.24it/s]

  2%|▏         | 119/7494 [00:29<29:52,  4.11it/s]

  2%|▏         | 119/7494 [00:29<29:52,  4.11it/s]
  2%|▏         | 120/7494 [00:29<29:52,  4.11it/s]

  2%|▏         | 121/7494 [00:30<30:43,  4.00it/s]

  2%|▏         | 121/7494 [00:30<30:43,  4.00it/s]
  2%|▏         | 122/7494 [00:30<30:43,  4.00it/s]

  2%|▏         | 123/7494 [00:30<31:46,  3.87it/s]

  2%|▏         | 123/7494 [00:30<31:46,  3.87it/s]
  2%|▏         | 124/7494 [00:30<31:46,  3.87it/s]

  2%|▏         | 125/7494 [00:31<31:34,  3.89it/s]

  2%|▏         | 125/7494 [00:31<31:34,  3.89it/s]
  2%|▏         | 126/7494 [00:31<31:34,  3.89it/s]

  2%|▏         | 127/7494 [00:31<31:35,  3.89it/s]

  2%|▏         | 127/7494 [00:31<31:35,  3.89it/s]
  2%|▏         | 128/7494 [00:31<31:35,  3.89it/s]

  2%|▏         | 129/7494 [00:34<1:13:17,  1.67it/s]

  2%|▏         | 129/7494 [00:34<1:13:17,  1.67it/s]
  2%|▏         | 130/7494 [00:34<1:13:17,  1.67it/s]
  2%|▏         | 131/7494 [00:34<1:13:16,  1.67it/s]
  2%|▏         | 132/7494 [00:34<1:13:16,  1.67it/s]

  2%|▏         | 133/7494 [00:35<47:24,  2.59it/s]

  2%|▏         | 133/7494 [00:35<47:24,  2.59it/s]
  2%|▏         | 134/7494 [00:35<47:23,  2.59it/s]

  2%|▏         | 135/7494 [00:35<43:49,  2.80it/s]

  2%|▏         | 135/7494 [00:35<43:49,  2.80it/s]
  2%|▏         | 136/7494 [00:35<43:49,  2.80it/s]
  2%|▏         | 137/7494 [00:35<43:49,  2.80it/s]

  2%|▏         | 138/7494 [00:36<36:15,  3.38it/s]

  2%|▏         | 138/7494 [00:36<36:15,  3.38it/s]
  2%|▏         | 139/7494 [00:36<36:14,  3.38it/s]
  2%|▏         | 140/7494 [00:36<36:14,  3.38it/s]
  2%|▏         | 141/7494 [00:36<36:14,  3.38it/s]

  2%|▏         | 142/7494 [00:36<28:03,  4.37it/s]

  2%|▏         | 142/7494 [00:36<28:03,  4.37it/s]
  2%|▏         | 143/7494 [00:36<28:03,  4.37it/s]

  2%|▏         | 144/7494 [00:37<29:15,  4.19it/s]

  2%|▏         | 144/7494 [00:37<29:15,  4.19it/s]
  2%|▏         | 145/7494 [00:37<29:14,  4.19it/s]

  2%|▏         | 146/7494 [00:37<30:07,  4.07it/s]

  2%|▏         | 146/7494 [00:37<30:07,  4.07it/s]
  2%|▏         | 147/7494 [00:37<30:06,  4.07it/s]

  2%|▏         | 148/7494 [00:38<31:20,  3.91it/s]

  2%|▏         | 148/7494 [00:38<31:20,  3.91it/s]
  2%|▏         | 149/7494 [00:38<31:19,  3.91it/s]

  2%|▏         | 150/7494 [00:38<31:24,  3.90it/s]

  2%|▏         | 150/7494 [00:38<31:24,  3.90it/s]
  2%|▏         | 151/7494 [00:38<31:24,  3.90it/s]

  2%|▏         | 152/7494 [00:39<31:50,  3.84it/s]

  2%|▏         | 152/7494 [00:39<31:50,  3.84it/s]
  2%|▏         | 153/7494 [00:39<31:50,  3.84it/s]
  2%|▏         | 154/7494 [00:39<31:49,  3.84it/s]
  2%|▏         | 155/7494 [00:39<31:49,  3.84it/s]

  2%|▏         | 156/7494 [00:39<24:36,  4.97it/s]

  2%|▏         | 156/7494 [00:39<24:36,  4.97it/s]
  2%|▏         | 157/7494 [00:39<24:36,  4.97it/s]

  2%|▏         | 158/7494 [00:40<26:51,  4.55it/s]

  2%|▏         | 158/7494 [00:40<26:51,  4.55it/s]
  2%|▏         | 159/7494 [00:40<26:50,  4.55it/s]

  2%|▏         | 160/7494 [00:40<27:52,  4.38it/s]

  2%|▏         | 160/7494 [00:40<27:52,  4.38it/s]
  2%|▏         | 161/7494 [00:40<27:52,  4.38it/s]

  2%|▏         | 162/7494 [00:41<29:10,  4.19it/s]

  2%|▏         | 162/7494 [00:41<29:10,  4.19it/s]
  2%|▏         | 163/7494 [00:41<29:09,  4.19it/s]

  2%|▏         | 164/7494 [00:42<29:34,  4.13it/s]

  2%|▏         | 164/7494 [00:42<29:34,  4.13it/s]
  2%|▏         | 165/7494 [00:42<29:34,  4.13it/s]

  2%|▏         | 166/7494 [00:42<30:49,  3.96it/s]

  2%|▏         | 166/7494 [00:42<30:49,  3.96it/s]
  2%|▏         | 167/7494 [00:42<30:48,  3.96it/s]

  2%|▏         | 168/7494 [00:43<31:07,  3.92it/s]

  2%|▏         | 168/7494 [00:43<31:07,  3.92it/s]
  2%|▏         | 169/7494 [00:43<31:07,  3.92it/s]

  2%|▏         | 170/7494 [00:43<32:16,  3.78it/s]

  2%|▏         | 170/7494 [00:43<32:16,  3.78it/s]
  2%|▏         | 171/7494 [00:43<32:15,  3.78it/s]

  2%|▏         | 172/7494 [00:44<32:45,  3.73it/s]

  2%|▏         | 172/7494 [00:44<32:45,  3.73it/s]
  2%|▏         | 173/7494 [00:44<32:45,  3.73it/s]
  2%|▏         | 174/7494 [00:44<32:44,  3.73it/s]
  2%|▏         | 175/7494 [00:44<32:44,  3.73it/s]

  2%|▏         | 176/7494 [00:47<58:09,  2.10it/s]

  2%|▏         | 176/7494 [00:47<58:09,  2.10it/s]
  2%|▏         | 177/7494 [00:47<58:09,  2.10it/s]

  2%|▏         | 178/7494 [00:47<52:34,  2.32it/s]

  2%|▏         | 178/7494 [00:47<52:34,  2.32it/s]
  2%|▏         | 179/7494 [00:47<52:33,  2.32it/s]
  2%|▏         | 180/7494 [00:47<52:33,  2.32it/s]

  2%|▏         | 181/7494 [00:48<42:06,  2.89it/s]

  2%|▏         | 181/7494 [00:48<42:06,  2.89it/s]
  2%|▏         | 182/7494 [00:48<42:06,  2.89it/s]

  2%|▏         | 183/7494 [00:48<40:38,  3.00it/s]

  2%|▏         | 183/7494 [00:48<40:38,  3.00it/s]
  2%|▏         | 184/7494 [00:48<40:38,  3.00it/s]

  2%|▏         | 185/7494 [00:49<38:44,  3.14it/s]

  2%|▏         | 185/7494 [00:49<38:44,  3.14it/s]
  2%|▏         | 186/7494 [00:49<38:44,  3.14it/s]

  2%|▏         | 187/7494 [00:49<37:48,  3.22it/s]

  2%|▏         | 187/7494 [00:49<37:48,  3.22it/s]
  3%|▎         | 188/7494 [00:49<37:48,  3.22it/s]

  3%|▎         | 189/7494 [00:50<36:49,  3.31it/s]

  3%|▎         | 189/7494 [00:50<36:49,  3.31it/s]
  3%|▎         | 190/7494 [00:50<36:49,  3.31it/s]
  3%|▎         | 191/7494 [00:50<36:49,  3.31it/s]
  3%|▎         | 192/7494 [00:50<36:48,  3.31it/s]
  3%|▎         | 193/7494 [00:50<36:48,  3.31it/s]
  3%|▎         | 194/7494 [00:50<36:48,  3.31it/s]
  3%|▎         | 195/7494 [00:50<36:47,  3.31it/s]
  3%|▎         | 196/7494 [00:50<36:47,  3.31it/s]
  3%|▎         | 197/7494 [00:50<36:47,  3.31it/s]
  3%|▎         | 198/7494 [00:50<36:47,  3.31it/s]
  3%|▎         | 199/7494 [00:50<36:46,  3.31it/s]

  3%|▎         | 200/7494 [00:51<16:02,  7.58it/s]

  3%|▎         | 200/7494 [00:51<16:02,  7.58it/s]
  3%|▎         | 201/7494 [00:51<16:01,  7.58it/s]

  3%|▎         | 202/7494 [00:51<18:32,  6.55it/s]

  3%|▎         | 202/7494 [00:51<18:32,  6.55it/s]
  3%|▎         | 203/7494 [00:51<18:32,  6.55it/s]

  3%|▎         | 204/7494 [00:52<21:10,  5.74it/s]

  3%|▎         | 204/7494 [00:52<21:10,  5.74it/s]
  3%|▎         | 205/7494 [00:52<21:10,  5.74it/s]
  3%|▎         | 206/7494 [00:52<21:10,  5.74it/s]
  3%|▎         | 207/7494 [00:52<21:10,  5.74it/s]
  3%|▎         | 208/7494 [00:52<21:10,  5.74it/s]
  3%|▎         | 209/7494 [00:52<21:10,  5.74it/s]
  3%|▎         | 210/7494 [00:52<21:09,  5.74it/s]
  3%|▎         | 211/7494 [00:52<21:09,  5.74it/s]
  3%|▎         | 212/7494 [00:52<21:09,  5.74it/s]
  3%|▎         | 213/7494 [00:52<21:09,  5.74it/s]
  3%|▎         | 214/7494 [00:52<21:09,  5.74it/s]
  3%|▎         | 215/7494 [00:52<21:08,  5.74it/s]
  3%|▎         | 216/7494 [00:52<21:08,  5.74it/s]
  3%|▎         | 217/7494 [00:52<21:08,  5.74it/s]

  3%|▎         | 218/7494 [00:52<10:49, 11.20it/s]

  3%|▎         | 218/7494 [00:52<10:49, 11.20it/s]
  3%|▎         | 219/7494 [00:52<10:49, 11.20it/s]

  3%|▎         | 220/7494 [00:53<13:13,  9.17it/s]

  3%|▎         | 220/7494 [00:53<13:13,  9.17it/s]
  3%|▎         | 221/7494 [00:53<13:13,  9.17it/s]

  3%|▎         | 222/7494 [00:53<16:15,  7.46it/s]

  3%|▎         | 222/7494 [00:53<16:15,  7.46it/s]
  3%|▎         | 223/7494 [00:53<16:15,  7.46it/s]
  3%|▎         | 224/7494 [00:53<16:15,  7.46it/s]

  3%|▎         | 225/7494 [00:54<17:26,  6.95it/s]

  3%|▎         | 225/7494 [00:54<17:26,  6.95it/s]
  3%|▎         | 226/7494 [00:54<17:25,  6.95it/s]

  3%|▎         | 227/7494 [00:55<20:32,  5.90it/s]

  3%|▎         | 227/7494 [00:55<20:32,  5.90it/s]
  3%|▎         | 228/7494 [00:55<20:32,  5.90it/s]

  3%|▎         | 229/7494 [00:55<22:59,  5.27it/s]

  3%|▎         | 229/7494 [00:55<22:59,  5.27it/s]
  3%|▎         | 230/7494 [00:55<22:59,  5.27it/s]

  3%|▎         | 231/7494 [00:56<25:39,  4.72it/s]

  3%|▎         | 231/7494 [00:56<25:39,  4.72it/s]
  3%|▎         | 232/7494 [00:56<25:39,  4.72it/s]

  3%|▎         | 233/7494 [00:56<27:24,  4.42it/s]

  3%|▎         | 233/7494 [00:56<27:24,  4.42it/s]
  3%|▎         | 234/7494 [00:56<27:24,  4.42it/s]
  3%|▎         | 235/7494 [00:56<27:23,  4.42it/s]
  3%|▎         | 236/7494 [00:56<27:23,  4.42it/s]
  3%|▎         | 237/7494 [00:56<27:23,  4.42it/s]

  3%|▎         | 238/7494 [00:58<39:38,  3.05it/s]

  3%|▎         | 238/7494 [00:58<39:38,  3.05it/s]
  3%|▎         | 239/7494 [00:58<39:38,  3.05it/s]

  3%|▎         | 240/7494 [01:00<45:33,  2.65it/s]

  3%|▎         | 240/7494 [01:00<45:33,  2.65it/s]
  3%|▎         | 241/7494 [01:00<45:33,  2.65it/s]

  3%|▎         | 242/7494 [01:00<43:04,  2.81it/s]

  3%|▎         | 242/7494 [01:00<43:04,  2.81it/s]
  3%|▎         | 243/7494 [01:00<43:04,  2.81it/s]

  3%|▎         | 244/7494 [01:01<40:18,  3.00it/s]

  3%|▎         | 244/7494 [01:01<40:18,  3.00it/s]
  3%|▎         | 245/7494 [01:01<40:18,  3.00it/s]

  3%|▎         | 246/7494 [01:01<38:59,  3.10it/s]

  3%|▎         | 246/7494 [01:01<38:59,  3.10it/s]
  3%|▎         | 247/7494 [01:01<38:59,  3.10it/s]

  3%|▎         | 248/7494 [01:02<37:55,  3.18it/s]

  3%|▎         | 248/7494 [01:02<37:55,  3.18it/s]
  3%|▎         | 249/7494 [01:02<37:55,  3.18it/s]

  3%|▎         | 250/7494 [01:02<36:56,  3.27it/s]

  3%|▎         | 250/7494 [01:02<36:56,  3.27it/s]
  3%|▎         | 251/7494 [01:02<36:56,  3.27it/s]
  3%|▎         | 252/7494 [01:02<36:56,  3.27it/s]
  3%|▎         | 253/7494 [01:02<36:55,  3.27it/s]
  3%|▎         | 254/7494 [01:02<36:55,  3.27it/s]
  3%|▎         | 255/7494 [01:02<36:55,  3.27it/s]

  3%|▎         | 256/7494 [01:03<23:07,  5.22it/s]

  3%|▎         | 256/7494 [01:03<23:07,  5.22it/s]
  3%|▎         | 257/7494 [01:03<23:06,  5.22it/s]

  3%|▎         | 258/7494 [01:03<25:13,  4.78it/s]

  3%|▎         | 258/7494 [01:03<25:13,  4.78it/s]
  3%|▎         | 259/7494 [01:03<25:13,  4.78it/s]
  3%|▎         | 260/7494 [01:04<25:13,  4.78it/s]
  3%|▎         | 261/7494 [01:04<25:13,  4.78it/s]
  3%|▎         | 262/7494 [01:04<25:13,  4.78it/s]
  4%|▎         | 263/7494 [01:04<25:12,  4.78it/s]
  4%|▎         | 264/7494 [01:04<25:12,  4.78it/s]

  4%|▎         | 265/7494 [01:04<17:21,  6.94it/s]

  4%|▎         | 265/7494 [01:04<17:21,  6.94it/s]
  4%|▎         | 266/7494 [01:04<17:21,  6.94it/s]

  4%|▎         | 267/7494 [01:05<19:43,  6.10it/s]

  4%|▎         | 267/7494 [01:05<19:43,  6.10it/s]
  4%|▎         | 268/7494 [01:05<19:43,  6.10it/s]

  4%|▎         | 269/7494 [01:05<22:21,  5.38it/s]

  4%|▎         | 269/7494 [01:05<22:21,  5.38it/s]
  4%|▎         | 270/7494 [01:05<22:21,  5.38it/s]

  4%|▎         | 271/7494 [01:06<24:24,  4.93it/s]

  4%|▎         | 271/7494 [01:06<24:24,  4.93it/s]
  4%|▎         | 272/7494 [01:06<24:24,  4.93it/s]

  4%|▎         | 273/7494 [01:06<26:36,  4.52it/s]

  4%|▎         | 273/7494 [01:06<26:36,  4.52it/s]
  4%|▎         | 274/7494 [01:06<26:36,  4.52it/s]
  4%|▎         | 275/7494 [01:06<26:35,  4.52it/s]
  4%|▎         | 276/7494 [01:06<26:35,  4.52it/s]
  4%|▎         | 277/7494 [01:06<26:35,  4.52it/s]

  4%|▎         | 278/7494 [01:07<20:30,  5.87it/s]

  4%|▎         | 278/7494 [01:07<20:30,  5.87it/s]
  4%|▎         | 279/7494 [01:07<20:30,  5.87it/s]

  4%|▎         | 280/7494 [01:07<23:38,  5.09it/s]

  4%|▎         | 280/7494 [01:07<23:38,  5.09it/s]
  4%|▎         | 281/7494 [01:07<23:37,  5.09it/s]

  4%|▍         | 282/7494 [01:08<26:41,  4.50it/s]

  4%|▍         | 282/7494 [01:08<26:41,  4.50it/s]
  4%|▍         | 283/7494 [01:08<26:40,  4.50it/s]

  4%|▍         | 284/7494 [01:09<28:44,  4.18it/s]

  4%|▍         | 284/7494 [01:09<28:44,  4.18it/s]
  4%|▍         | 285/7494 [01:09<28:44,  4.18it/s]

  4%|▍         | 286/7494 [01:09<31:11,  3.85it/s]

  4%|▍         | 286/7494 [01:09<31:11,  3.85it/s]
  4%|▍         | 287/7494 [01:09<31:11,  3.85it/s]

  4%|▍         | 288/7494 [01:12<1:07:04,  1.79it/s]

  4%|▍         | 288/7494 [01:12<1:07:04,  1.79it/s]
  4%|▍         | 289/7494 [01:12<1:07:04,  1.79it/s]

  4%|▍         | 290/7494 [01:13<58:40,  2.05it/s]

  4%|▍         | 290/7494 [01:13<58:40,  2.05it/s]
  4%|▍         | 291/7494 [01:13<58:39,  2.05it/s]

  4%|▍         | 292/7494 [01:13<51:34,  2.33it/s]

  4%|▍         | 292/7494 [01:13<51:34,  2.33it/s]
  4%|▍         | 293/7494 [01:13<51:33,  2.33it/s]

  4%|▍         | 294/7494 [01:14<49:14,  2.44it/s]

  4%|▍         | 294/7494 [01:14<49:14,  2.44it/s]
  4%|▍         | 295/7494 [01:14<49:14,  2.44it/s]
  4%|▍         | 296/7494 [01:14<49:13,  2.44it/s]

  4%|▍         | 297/7494 [01:15<42:46,  2.80it/s]

  4%|▍         | 297/7494 [01:15<42:46,  2.80it/s]
  4%|▍         | 298/7494 [01:15<42:45,  2.80it/s]
  4%|▍         | 299/7494 [01:15<42:45,  2.80it/s]

  4%|▍         | 300/7494 [01:15<38:29,  3.11it/s]

  4%|▍         | 300/7494 [01:15<38:29,  3.11it/s]
  4%|▍         | 301/7494 [01:15<38:29,  3.11it/s]

  4%|▍         | 302/7494 [01:16<40:00,  3.00it/s]

  4%|▍         | 302/7494 [01:16<40:00,  3.00it/s]
  4%|▍         | 303/7494 [01:16<39:59,  3.00it/s]

  4%|▍         | 304/7494 [01:17<42:15,  2.84it/s]

  4%|▍         | 304/7494 [01:17<42:15,  2.84it/s]
  4%|▍         | 305/7494 [01:17<42:14,  2.84it/s]

  4%|▍         | 306/7494 [01:18<43:32,  2.75it/s]

  4%|▍         | 306/7494 [01:18<43:32,  2.75it/s]
  4%|▍         | 307/7494 [01:18<43:31,  2.75it/s]

  4%|▍         | 308/7494 [01:19<47:35,  2.52it/s]

  4%|▍         | 308/7494 [01:19<47:35,  2.52it/s]
  4%|▍         | 309/7494 [01:19<47:34,  2.52it/s]
  4%|▍         | 310/7494 [01:19<47:34,  2.52it/s]

  4%|▍         | 311/7494 [01:20<49:30,  2.42it/s]

  4%|▍         | 311/7494 [01:20<49:30,  2.42it/s]
  4%|▍         | 312/7494 [01:20<49:30,  2.42it/s]

  4%|▍         | 313/7494 [01:21<51:07,  2.34it/s]

  4%|▍         | 313/7494 [01:21<51:07,  2.34it/s]
  4%|▍         | 314/7494 [01:21<51:06,  2.34it/s]
  4%|▍         | 315/7494 [01:21<51:06,  2.34it/s]
  4%|▍         | 316/7494 [01:21<51:05,  2.34it/s]
  4%|▍         | 317/7494 [01:21<51:05,  2.34it/s]

  4%|▍         | 318/7494 [01:22<32:58,  3.63it/s]

  4%|▍         | 318/7494 [01:22<32:58,  3.63it/s]
  4%|▍         | 319/7494 [01:22<32:58,  3.63it/s]

  4%|▍         | 320/7494 [01:25<1:06:04,  1.81it/s]

  4%|▍         | 320/7494 [01:25<1:06:04,  1.81it/s]
  4%|▍         | 321/7494 [01:25<1:06:03,  1.81it/s]

  4%|▍         | 322/7494 [01:25<58:40,  2.04it/s]

  4%|▍         | 322/7494 [01:25<58:40,  2.04it/s]
  4%|▍         | 323/7494 [01:25<58:39,  2.04it/s]

  4%|▍         | 324/7494 [01:26<51:51,  2.30it/s]

  4%|▍         | 324/7494 [01:26<51:51,  2.30it/s]
  4%|▍         | 325/7494 [01:26<51:51,  2.30it/s]

  4%|▍         | 326/7494 [01:26<47:04,  2.54it/s]

  4%|▍         | 326/7494 [01:26<47:04,  2.54it/s]
  4%|▍         | 327/7494 [01:26<47:04,  2.54it/s]

  4%|▍         | 328/7494 [01:27<43:17,  2.76it/s]

  4%|▍         | 328/7494 [01:27<43:17,  2.76it/s]
  4%|▍         | 329/7494 [01:27<43:17,  2.76it/s]

  4%|▍         | 330/7494 [01:27<40:42,  2.93it/s]

  4%|▍         | 330/7494 [01:27<40:42,  2.93it/s]
  4%|▍         | 331/7494 [01:27<40:41,  2.93it/s]

  4%|▍         | 332/7494 [01:28<38:05,  3.13it/s]

  4%|▍         | 332/7494 [01:28<38:05,  3.13it/s]
  4%|▍         | 333/7494 [01:28<38:05,  3.13it/s]

  4%|▍         | 334/7494 [01:29<36:46,  3.25it/s]

  4%|▍         | 334/7494 [01:29<36:46,  3.25it/s]
  4%|▍         | 335/7494 [01:29<36:45,  3.25it/s]

  4%|▍         | 336/7494 [01:29<36:16,  3.29it/s]

  4%|▍         | 336/7494 [01:29<36:16,  3.29it/s]
  4%|▍         | 337/7494 [01:29<36:16,  3.29it/s]
  5%|▍         | 338/7494 [01:29<36:16,  3.29it/s]
  5%|▍         | 339/7494 [01:29<36:15,  3.29it/s]
  5%|▍         | 340/7494 [01:29<36:15,  3.29it/s]
  5%|▍         | 341/7494 [01:29<36:15,  3.29it/s]
  5%|▍         | 342/7494 [01:29<36:14,  3.29it/s]

  5%|▍         | 343/7494 [01:30<20:21,  5.85it/s]

  5%|▍         | 343/7494 [01:30<20:21,  5.85it/s]
  5%|▍         | 344/7494 [01:30<20:21,  5.85it/s]

  5%|▍         | 345/7494 [01:30<23:04,  5.16it/s]

  5%|▍         | 345/7494 [01:30<23:04,  5.16it/s]
  5%|▍         | 346/7494 [01:30<23:04,  5.16it/s]

  5%|▍         | 347/7494 [01:31<25:13,  4.72it/s]

  5%|▍         | 347/7494 [01:31<25:13,  4.72it/s]
  5%|▍         | 348/7494 [01:31<25:12,  4.72it/s]

  5%|▍         | 349/7494 [01:31<27:29,  4.33it/s]

  5%|▍         | 349/7494 [01:31<27:29,  4.33it/s]
  5%|▍         | 350/7494 [01:31<27:28,  4.33it/s]

  5%|▍         | 351/7494 [01:32<28:50,  4.13it/s]

  5%|▍         | 351/7494 [01:32<28:50,  4.13it/s]
  5%|▍         | 352/7494 [01:32<28:50,  4.13it/s]

  5%|▍         | 353/7494 [01:33<30:36,  3.89it/s]

  5%|▍         | 353/7494 [01:33<30:36,  3.89it/s]
  5%|▍         | 354/7494 [01:33<30:36,  3.89it/s]

  5%|▍         | 355/7494 [01:33<31:23,  3.79it/s]

  5%|▍         | 355/7494 [01:33<31:23,  3.79it/s]
  5%|▍         | 356/7494 [01:33<31:23,  3.79it/s]

  5%|▍         | 357/7494 [01:34<33:12,  3.58it/s]

  5%|▍         | 357/7494 [01:34<33:12,  3.58it/s]
  5%|▍         | 358/7494 [01:34<33:12,  3.58it/s]

  5%|▍         | 359/7494 [01:34<33:58,  3.50it/s]

  5%|▍         | 359/7494 [01:34<33:58,  3.50it/s]
  5%|▍         | 360/7494 [01:34<33:57,  3.50it/s]

  5%|▍         | 361/7494 [01:37<1:14:13,  1.60it/s]

  5%|▍         | 361/7494 [01:37<1:14:13,  1.60it/s]
  5%|▍         | 362/7494 [01:37<1:14:12,  1.60it/s]

  5%|▍         | 363/7494 [01:38<1:03:57,  1.86it/s]

  5%|▍         | 363/7494 [01:38<1:03:57,  1.86it/s]
  5%|▍         | 364/7494 [01:38<1:03:57,  1.86it/s]

  5%|▍         | 365/7494 [01:38<55:12,  2.15it/s]

  5%|▍         | 365/7494 [01:38<55:12,  2.15it/s]
  5%|▍         | 366/7494 [01:38<55:12,  2.15it/s]

  5%|▍         | 367/7494 [01:39<48:55,  2.43it/s]

  5%|▍         | 367/7494 [01:39<48:55,  2.43it/s]
  5%|▍         | 368/7494 [01:39<48:54,  2.43it/s]

  5%|▍         | 369/7494 [01:40<44:46,  2.65it/s]

  5%|▍         | 369/7494 [01:40<44:46,  2.65it/s]
  5%|▍         | 370/7494 [01:40<44:45,  2.65it/s]

  5%|▍         | 371/7494 [01:40<41:39,  2.85it/s]

  5%|▍         | 371/7494 [01:40<41:39,  2.85it/s]
  5%|▍         | 372/7494 [01:40<41:39,  2.85it/s]

  5%|▍         | 373/7494 [01:41<39:52,  2.98it/s]

  5%|▍         | 373/7494 [01:41<39:52,  2.98it/s]
  5%|▍         | 374/7494 [01:41<39:52,  2.98it/s]

  5%|▌         | 375/7494 [01:41<38:26,  3.09it/s]

  5%|▌         | 375/7494 [01:41<38:26,  3.09it/s]
  5%|▌         | 376/7494 [01:41<38:26,  3.09it/s]

  5%|▌         | 377/7494 [01:42<38:17,  3.10it/s]

  5%|▌         | 377/7494 [01:42<38:17,  3.10it/s]
  5%|▌         | 378/7494 [01:42<38:17,  3.10it/s]

  5%|▌         | 379/7494 [01:43<37:28,  3.16it/s]

  5%|▌         | 379/7494 [01:43<37:28,  3.16it/s]
  5%|▌         | 380/7494 [01:43<37:28,  3.16it/s]
  5%|▌         | 381/7494 [01:43<37:27,  3.16it/s]
  5%|▌         | 382/7494 [01:43<37:27,  3.16it/s]
  5%|▌         | 383/7494 [01:43<37:27,  3.16it/s]
  5%|▌         | 384/7494 [01:43<37:26,  3.16it/s]

  5%|▌         | 385/7494 [01:43<22:30,  5.26it/s]

  5%|▌         | 385/7494 [01:43<22:30,  5.26it/s]
  5%|▌         | 386/7494 [01:43<22:30,  5.26it/s]

  5%|▌         | 387/7494 [01:44<24:41,  4.80it/s]

  5%|▌         | 387/7494 [01:44<24:41,  4.80it/s]
  5%|▌         | 388/7494 [01:44<24:41,  4.80it/s]

  5%|▌         | 389/7494 [01:44<26:27,  4.48it/s]

  5%|▌         | 389/7494 [01:44<26:27,  4.48it/s]
  5%|▌         | 390/7494 [01:44<26:27,  4.48it/s]

  5%|▌         | 391/7494 [01:45<27:57,  4.24it/s]

  5%|▌         | 391/7494 [01:45<27:57,  4.24it/s]
  5%|▌         | 392/7494 [01:45<27:56,  4.24it/s]

  5%|▌         | 393/7494 [01:45<28:58,  4.09it/s]

  5%|▌         | 393/7494 [01:45<28:58,  4.09it/s]
  5%|▌         | 394/7494 [01:45<28:57,  4.09it/s]

  5%|▌         | 395/7494 [01:46<30:11,  3.92it/s]

  5%|▌         | 395/7494 [01:46<30:11,  3.92it/s]
  5%|▌         | 396/7494 [01:46<30:10,  3.92it/s]

  5%|▌         | 397/7494 [01:46<30:37,  3.86it/s]

  5%|▌         | 397/7494 [01:47<30:37,  3.86it/s]
  5%|▌         | 398/7494 [01:47<30:37,  3.86it/s]
  5%|▌         | 399/7494 [01:47<30:37,  3.86it/s]

  5%|▌         | 400/7494 [01:47<30:14,  3.91it/s]

  5%|▌         | 400/7494 [01:47<30:14,  3.91it/s]
  5%|▌         | 401/7494 [01:47<30:14,  3.91it/s]
  5%|▌         | 402/7494 [01:47<30:14,  3.91it/s]
  5%|▌         | 403/7494 [01:47<30:13,  3.91it/s]
  5%|▌         | 404/7494 [01:47<30:13,  3.91it/s]

  5%|▌         | 405/7494 [01:50<45:40,  2.59it/s]

  5%|▌         | 405/7494 [01:50<45:40,  2.59it/s]
  5%|▌         | 406/7494 [01:50<45:39,  2.59it/s]

  5%|▌         | 407/7494 [01:50<43:01,  2.75it/s]

  5%|▌         | 407/7494 [01:50<43:01,  2.75it/s]
  5%|▌         | 408/7494 [01:50<43:00,  2.75it/s]
  5%|▌         | 409/7494 [01:50<43:00,  2.75it/s]

  5%|▌         | 410/7494 [01:51<36:09,  3.26it/s]

  5%|▌         | 410/7494 [01:51<36:09,  3.26it/s]
  5%|▌         | 411/7494 [01:51<36:09,  3.26it/s]
  5%|▌         | 412/7494 [01:51<36:09,  3.26it/s]
  6%|▌         | 413/7494 [01:51<36:08,  3.26it/s]
  6%|▌         | 414/7494 [01:51<36:08,  3.26it/s]
  6%|▌         | 415/7494 [01:51<36:08,  3.26it/s]

  6%|▌         | 416/7494 [01:52<24:02,  4.91it/s]

  6%|▌         | 416/7494 [01:52<24:02,  4.91it/s]
  6%|▌         | 417/7494 [01:52<24:01,  4.91it/s]

  6%|▌         | 418/7494 [01:52<25:49,  4.57it/s]

  6%|▌         | 418/7494 [01:52<25:49,  4.57it/s]
  6%|▌         | 419/7494 [01:52<25:49,  4.57it/s]

  6%|▌         | 420/7494 [01:53<26:54,  4.38it/s]

  6%|▌         | 420/7494 [01:53<26:54,  4.38it/s]
  6%|▌         | 421/7494 [01:53<26:53,  4.38it/s]

  6%|▌         | 422/7494 [01:53<28:37,  4.12it/s]

  6%|▌         | 422/7494 [01:53<28:37,  4.12it/s]
  6%|▌         | 423/7494 [01:53<28:37,  4.12it/s]
  6%|▌         | 424/7494 [01:53<28:37,  4.12it/s]
  6%|▌         | 425/7494 [01:53<28:36,  4.12it/s]
  6%|▌         | 426/7494 [01:53<28:36,  4.12it/s]
  6%|▌         | 427/7494 [01:53<28:36,  4.12it/s]
  6%|▌         | 428/7494 [01:53<28:36,  4.12it/s]
  6%|▌         | 429/7494 [01:53<28:35,  4.12it/s]
  6%|▌         | 430/7494 [01:53<28:35,  4.12it/s]
  6%|▌         | 431/7494 [01:53<28:35,  4.12it/s]

  6%|▌         | 432/7494 [01:54<14:56,  7.88it/s]

  6%|▌         | 432/7494 [01:54<14:56,  7.88it/s]
  6%|▌         | 433/7494 [01:54<14:55,  7.88it/s]
  6%|▌         | 434/7494 [01:54<14:55,  7.88it/s]

  6%|▌         | 435/7494 [01:54<16:21,  7.19it/s]

  6%|▌         | 435/7494 [01:54<16:21,  7.19it/s]
  6%|▌         | 436/7494 [01:54<16:21,  7.19it/s]

  6%|▌         | 437/7494 [01:55<18:43,  6.28it/s]

  6%|▌         | 437/7494 [01:55<18:43,  6.28it/s]
  6%|▌         | 438/7494 [01:55<18:43,  6.28it/s]
  6%|▌         | 439/7494 [01:55<18:43,  6.28it/s]
  6%|▌         | 440/7494 [01:55<18:42,  6.28it/s]

  6%|▌         | 441/7494 [01:55<18:09,  6.47it/s]

  6%|▌         | 441/7494 [01:55<18:09,  6.47it/s]
  6%|▌         | 442/7494 [01:55<18:09,  6.47it/s]

  6%|▌         | 443/7494 [01:56<20:45,  5.66it/s]

  6%|▌         | 443/7494 [01:56<20:45,  5.66it/s]
  6%|▌         | 444/7494 [01:56<20:45,  5.66it/s]

  6%|▌         | 445/7494 [01:57<23:22,  5.03it/s]

  6%|▌         | 445/7494 [01:57<23:22,  5.03it/s]
  6%|▌         | 446/7494 [01:57<23:22,  5.03it/s]

  6%|▌         | 447/7494 [01:57<25:02,  4.69it/s]

  6%|▌         | 447/7494 [01:57<25:02,  4.69it/s]
  6%|▌         | 448/7494 [01:57<25:02,  4.69it/s]

  6%|▌         | 449/7494 [01:58<26:54,  4.36it/s]

  6%|▌         | 449/7494 [01:58<26:54,  4.36it/s]
  6%|▌         | 450/7494 [01:58<26:54,  4.36it/s]

  6%|▌         | 451/7494 [01:58<27:51,  4.21it/s]

  6%|▌         | 451/7494 [01:58<27:51,  4.21it/s]
  6%|▌         | 452/7494 [01:58<27:51,  4.21it/s]

  6%|▌         | 453/7494 [01:59<29:25,  3.99it/s]

  6%|▌         | 453/7494 [01:59<29:25,  3.99it/s]
  6%|▌         | 454/7494 [01:59<29:25,  3.99it/s]
  6%|▌         | 455/7494 [01:59<29:25,  3.99it/s]

  6%|▌         | 456/7494 [01:59<26:28,  4.43it/s]

  6%|▌         | 456/7494 [01:59<26:28,  4.43it/s]
  6%|▌         | 457/7494 [01:59<26:28,  4.43it/s]

  6%|▌         | 458/7494 [02:02<57:08,  2.05it/s]

  6%|▌         | 458/7494 [02:02<57:08,  2.05it/s]
  6%|▌         | 459/7494 [02:02<57:08,  2.05it/s]

  6%|▌         | 460/7494 [02:03<56:09,  2.09it/s]

  6%|▌         | 460/7494 [02:03<56:09,  2.09it/s]
  6%|▌         | 461/7494 [02:03<56:08,  2.09it/s]

  6%|▌         | 462/7494 [02:03<49:38,  2.36it/s]

  6%|▌         | 462/7494 [02:03<49:38,  2.36it/s]
  6%|▌         | 463/7494 [02:03<49:38,  2.36it/s]

  6%|▌         | 464/7494 [02:04<44:49,  2.61it/s]

  6%|▌         | 464/7494 [02:04<44:49,  2.61it/s]
  6%|▌         | 465/7494 [02:04<44:49,  2.61it/s]

  6%|▌         | 466/7494 [02:04<40:39,  2.88it/s]

  6%|▌         | 466/7494 [02:04<40:39,  2.88it/s]
  6%|▌         | 467/7494 [02:04<40:38,  2.88it/s]

  6%|▌         | 468/7494 [02:05<38:16,  3.06it/s]

  6%|▌         | 468/7494 [02:05<38:16,  3.06it/s]
  6%|▋         | 469/7494 [02:05<38:16,  3.06it/s]
  6%|▋         | 470/7494 [02:05<38:16,  3.06it/s]
  6%|▋         | 471/7494 [02:05<38:15,  3.06it/s]
  6%|▋         | 472/7494 [02:05<38:15,  3.06it/s]
  6%|▋         | 473/7494 [02:05<38:15,  3.06it/s]
  6%|▋         | 474/7494 [02:05<38:14,  3.06it/s]

  6%|▋         | 475/7494 [02:05<20:47,  5.63it/s]

  6%|▋         | 475/7494 [02:05<20:47,  5.63it/s]
  6%|▋         | 476/7494 [02:05<20:46,  5.63it/s]

  6%|▋         | 477/7494 [02:06<22:48,  5.13it/s]

  6%|▋         | 477/7494 [02:06<22:48,  5.13it/s]
  6%|▋         | 478/7494 [02:06<22:48,  5.13it/s]

  6%|▋         | 479/7494 [02:06<24:20,  4.80it/s]

  6%|▋         | 479/7494 [02:06<24:20,  4.80it/s]
  6%|▋         | 480/7494 [02:06<24:19,  4.80it/s]

  6%|▋         | 481/7494 [02:07<25:56,  4.50it/s]

  6%|▋         | 481/7494 [02:07<25:56,  4.50it/s]
  6%|▋         | 482/7494 [02:07<25:56,  4.50it/s]

  6%|▋         | 483/7494 [02:07<27:10,  4.30it/s]

  6%|▋         | 483/7494 [02:07<27:10,  4.30it/s]
  6%|▋         | 484/7494 [02:08<27:09,  4.30it/s]

  6%|▋         | 485/7494 [02:08<29:30,  3.96it/s]

  6%|▋         | 485/7494 [02:08<29:30,  3.96it/s]
  6%|▋         | 486/7494 [02:08<29:30,  3.96it/s]

  6%|▋         | 487/7494 [02:09<29:59,  3.89it/s]

  6%|▋         | 487/7494 [02:09<29:59,  3.89it/s]
  7%|▋         | 488/7494 [02:09<29:58,  3.89it/s]

  7%|▋         | 489/7494 [02:09<30:49,  3.79it/s]

  7%|▋         | 489/7494 [02:09<30:49,  3.79it/s]
  7%|▋         | 490/7494 [02:09<30:48,  3.79it/s]

  7%|▋         | 491/7494 [02:10<31:15,  3.73it/s]

  7%|▋         | 491/7494 [02:10<31:15,  3.73it/s]
  7%|▋         | 492/7494 [02:10<31:14,  3.73it/s]

  7%|▋         | 493/7494 [02:10<31:51,  3.66it/s]

  7%|▋         | 493/7494 [02:10<31:51,  3.66it/s]
  7%|▋         | 494/7494 [02:10<31:50,  3.66it/s]

  7%|▋         | 495/7494 [02:11<32:15,  3.62it/s]

  7%|▋         | 495/7494 [02:11<32:15,  3.62it/s]
  7%|▋         | 496/7494 [02:11<32:14,  3.62it/s]
  7%|▋         | 497/7494 [02:11<32:14,  3.62it/s]

  7%|▋         | 498/7494 [02:11<28:08,  4.14it/s]

  7%|▋         | 498/7494 [02:11<28:08,  4.14it/s]
  7%|▋         | 499/7494 [02:11<28:07,  4.14it/s]
  7%|▋         | 500/7494 [02:11<28:07,  4.14it/s]
  7%|▋         | 501/7494 [02:11<28:07,  4.14it/s]
  7%|▋         | 502/7494 [02:11<28:07,  4.14it/s]
  7%|▋         | 503/7494 [02:11<28:06,  4.14it/s]
  7%|▋         | 504/7494 [02:11<28:06,  4.14it/s]

  7%|▋         | 505/7494 [02:12<17:37,  6.61it/s]

  7%|▋         | 505/7494 [02:12<17:37,  6.61it/s]
  7%|▋         | 506/7494 [02:12<17:36,  6.61it/s]

  7%|▋         | 507/7494 [02:15<44:46,  2.60it/s]

  7%|▋         | 507/7494 [02:15<44:46,  2.60it/s]
  7%|▋         | 508/7494 [02:15<44:45,  2.60it/s]

  7%|▋         | 509/7494 [02:15<42:10,  2.76it/s]

  7%|▋         | 509/7494 [02:15<42:10,  2.76it/s]
  7%|▋         | 510/7494 [02:15<42:10,  2.76it/s]

  7%|▋         | 511/7494 [02:16<39:36,  2.94it/s]

  7%|▋         | 511/7494 [02:16<39:36,  2.94it/s]
  7%|▋         | 512/7494 [02:16<39:36,  2.94it/s]

  7%|▋         | 513/7494 [02:16<38:14,  3.04it/s]

  7%|▋         | 513/7494 [02:16<38:14,  3.04it/s]
  7%|▋         | 514/7494 [02:17<38:14,  3.04it/s]

  7%|▋         | 515/7494 [02:17<36:16,  3.21it/s]

  7%|▋         | 515/7494 [02:17<36:16,  3.21it/s]
  7%|▋         | 516/7494 [02:17<36:16,  3.21it/s]

  7%|▋         | 517/7494 [02:18<35:08,  3.31it/s]

  7%|▋         | 517/7494 [02:18<35:08,  3.31it/s]
  7%|▋         | 518/7494 [02:18<35:07,  3.31it/s]

  7%|▋         | 519/7494 [02:18<33:43,  3.45it/s]

  7%|▋         | 519/7494 [02:18<33:43,  3.45it/s]
  7%|▋         | 520/7494 [02:18<33:43,  3.45it/s]
  7%|▋         | 521/7494 [02:18<33:42,  3.45it/s]
  7%|▋         | 522/7494 [02:18<33:42,  3.45it/s]

  7%|▋         | 523/7494 [02:19<25:39,  4.53it/s]

  7%|▋         | 523/7494 [02:19<25:39,  4.53it/s]
  7%|▋         | 524/7494 [02:19<25:39,  4.53it/s]

  7%|▋         | 525/7494 [02:19<26:49,  4.33it/s]

  7%|▋         | 525/7494 [02:19<26:49,  4.33it/s]
  7%|▋         | 526/7494 [02:19<26:49,  4.33it/s]

  7%|▋         | 527/7494 [02:20<28:16,  4.11it/s]

  7%|▋         | 527/7494 [02:20<28:16,  4.11it/s]
  7%|▋         | 528/7494 [02:20<28:16,  4.11it/s]
  7%|▋         | 529/7494 [02:20<28:16,  4.11it/s]
  7%|▋         | 530/7494 [02:20<28:16,  4.11it/s]
  7%|▋         | 531/7494 [02:20<28:15,  4.11it/s]

  7%|▋         | 532/7494 [02:20<20:35,  5.63it/s]

  7%|▋         | 532/7494 [02:20<20:35,  5.63it/s]
  7%|▋         | 533/7494 [02:20<20:35,  5.63it/s]

  7%|▋         | 534/7494 [02:21<23:14,  4.99it/s]

  7%|▋         | 534/7494 [02:21<23:14,  4.99it/s]
  7%|▋         | 535/7494 [02:21<23:14,  4.99it/s]

  7%|▋         | 536/7494 [02:21<24:52,  4.66it/s]

  7%|▋         | 536/7494 [02:21<24:52,  4.66it/s]
  7%|▋         | 537/7494 [02:21<24:52,  4.66it/s]

  7%|▋         | 538/7494 [02:22<27:09,  4.27it/s]

  7%|▋         | 538/7494 [02:22<27:09,  4.27it/s]
  7%|▋         | 539/7494 [02:22<27:08,  4.27it/s]

  7%|▋         | 540/7494 [02:22<28:39,  4.04it/s]

  7%|▋         | 540/7494 [02:23<28:39,  4.04it/s]
  7%|▋         | 541/7494 [02:23<28:39,  4.04it/s]

  7%|▋         | 542/7494 [02:23<29:30,  3.93it/s]

  7%|▋         | 542/7494 [02:23<29:30,  3.93it/s]
  7%|▋         | 543/7494 [02:23<29:29,  3.93it/s]

  7%|▋         | 544/7494 [02:24<30:28,  3.80it/s]

  7%|▋         | 544/7494 [02:24<30:28,  3.80it/s]
  7%|▋         | 545/7494 [02:24<30:28,  3.80it/s]

  7%|▋         | 546/7494 [02:24<30:54,  3.75it/s]

  7%|▋         | 546/7494 [02:24<30:54,  3.75it/s]
  7%|▋         | 547/7494 [02:24<30:54,  3.75it/s]

  7%|▋         | 548/7494 [02:25<34:50,  3.32it/s]

  7%|▋         | 548/7494 [02:25<34:50,  3.32it/s]
  7%|▋         | 549/7494 [02:25<34:50,  3.32it/s]

  7%|▋         | 550/7494 [02:28<1:09:09,  1.67it/s]

  7%|▋         | 550/7494 [02:28<1:09:09,  1.67it/s]
  7%|▋         | 551/7494 [02:28<1:09:08,  1.67it/s]

  7%|▋         | 552/7494 [02:28<58:45,  1.97it/s]

  7%|▋         | 552/7494 [02:28<58:45,  1.97it/s]
  7%|▋         | 553/7494 [02:28<58:45,  1.97it/s]

  7%|▋         | 554/7494 [02:29<50:42,  2.28it/s]

  7%|▋         | 554/7494 [02:29<50:42,  2.28it/s]
  7%|▋         | 555/7494 [02:29<50:41,  2.28it/s]

  7%|▋         | 556/7494 [02:29<45:26,  2.54it/s]

  7%|▋         | 556/7494 [02:29<45:26,  2.54it/s]
  7%|▋         | 557/7494 [02:29<45:25,  2.54it/s]

  7%|▋         | 558/7494 [02:30<41:13,  2.80it/s]

  7%|▋         | 558/7494 [02:30<41:13,  2.80it/s]
  7%|▋         | 559/7494 [02:30<41:13,  2.80it/s]
  7%|▋         | 560/7494 [02:30<41:13,  2.80it/s]
  7%|▋         | 561/7494 [02:30<41:12,  2.80it/s]
  7%|▋         | 562/7494 [02:30<41:12,  2.80it/s]
  8%|▊         | 563/7494 [02:30<41:11,  2.80it/s]
  8%|▊         | 564/7494 [02:30<41:11,  2.80it/s]

  8%|▊         | 565/7494 [02:30<22:12,  5.20it/s]

  8%|▊         | 565/7494 [02:30<22:12,  5.20it/s]
  8%|▊         | 566/7494 [02:30<22:12,  5.20it/s]

  8%|▊         | 567/7494 [02:31<24:23,  4.73it/s]

  8%|▊         | 567/7494 [02:31<24:23,  4.73it/s]
  8%|▊         | 568/7494 [02:31<24:23,  4.73it/s]

  8%|▊         | 569/7494 [02:31<25:53,  4.46it/s]

  8%|▊         | 569/7494 [02:32<25:53,  4.46it/s]
  8%|▊         | 570/7494 [02:32<25:53,  4.46it/s]

  8%|▊         | 571/7494 [02:32<27:40,  4.17it/s]

  8%|▊         | 571/7494 [02:32<27:40,  4.17it/s]
  8%|▊         | 572/7494 [02:32<27:40,  4.17it/s]

  8%|▊         | 573/7494 [02:33<28:22,  4.06it/s]

  8%|▊         | 573/7494 [02:33<28:22,  4.06it/s]
  8%|▊         | 574/7494 [02:33<28:22,  4.06it/s]

  8%|▊         | 575/7494 [02:33<29:38,  3.89it/s]

  8%|▊         | 575/7494 [02:33<29:38,  3.89it/s]
  8%|▊         | 576/7494 [02:33<29:37,  3.89it/s]

  8%|▊         | 577/7494 [02:34<30:16,  3.81it/s]

  8%|▊         | 577/7494 [02:34<30:16,  3.81it/s]
  8%|▊         | 578/7494 [02:34<30:16,  3.81it/s]

  8%|▊         | 579/7494 [02:34<30:48,  3.74it/s]

  8%|▊         | 579/7494 [02:34<30:48,  3.74it/s]
  8%|▊         | 580/7494 [02:34<30:48,  3.74it/s]

  8%|▊         | 581/7494 [02:35<30:59,  3.72it/s]

  8%|▊         | 581/7494 [02:35<30:59,  3.72it/s]
  8%|▊         | 582/7494 [02:35<30:59,  3.72it/s]
  8%|▊         | 583/7494 [02:35<30:58,  3.72it/s]
  8%|▊         | 584/7494 [02:35<30:58,  3.72it/s]
  8%|▊         | 585/7494 [02:35<30:58,  3.72it/s]
  8%|▊         | 586/7494 [02:35<30:58,  3.72it/s]
  8%|▊         | 587/7494 [02:35<30:57,  3.72it/s]
  8%|▊         | 588/7494 [02:35<30:57,  3.72it/s]

  8%|▊         | 589/7494 [02:35<16:56,  6.80it/s]

  8%|▊         | 589/7494 [02:35<16:56,  6.80it/s]
  8%|▊         | 590/7494 [02:35<16:55,  6.80it/s]
  8%|▊         | 591/7494 [02:35<16:55,  6.80it/s]
  8%|▊         | 592/7494 [02:35<16:55,  6.80it/s]

  8%|▊         | 593/7494 [02:36<16:27,  6.99it/s]

  8%|▊         | 593/7494 [02:36<16:27,  6.99it/s]
  8%|▊         | 594/7494 [02:36<16:27,  6.99it/s]
  8%|▊         | 595/7494 [02:36<16:27,  6.99it/s]
  8%|▊         | 596/7494 [02:36<16:27,  6.99it/s]
  8%|▊         | 597/7494 [02:36<16:27,  6.99it/s]

  8%|▊         | 598/7494 [02:37<15:18,  7.51it/s]

  8%|▊         | 598/7494 [02:37<15:18,  7.51it/s]
  8%|▊         | 599/7494 [02:37<15:18,  7.51it/s]
  8%|▊         | 600/7494 [02:37<15:17,  7.51it/s]
  8%|▊         | 601/7494 [02:37<15:17,  7.51it/s]
  8%|▊         | 602/7494 [02:37<15:17,  7.51it/s]
  8%|▊         | 603/7494 [02:37<15:17,  7.51it/s]
  8%|▊         | 604/7494 [02:37<15:17,  7.51it/s]
  8%|▊         | 605/7494 [02:37<15:17,  7.51it/s]
  8%|▊         | 606/7494 [02:37<15:17,  7.51it/s]
  8%|▊         | 607/7494 [02:37<15:17,  7.51it/s]
  8%|▊         | 608/7494 [02:37<15:16,  7.51it/s]
  8%|▊         | 609/7494 [02:37<15:16,  7.51it/s]
  8%|▊         | 610/7494 [02:37<15:16,  7.51it/s]
  8%|▊         | 611/7494 [02:37<15:16,  7.51it/s]
  8%|▊         | 612/7494 [02:37<15:16,  7.51it/s]
  8%|▊         | 613/7494 [02:37<15:16,  7.51it/s]
  8%|▊         | 614/7494 [02:37<15:16,  7.51it/s]
  8%|▊         | 615/7494 [02:37<15:15,  7.51it/s]
  8%|▊         | 616/7494 [02:37<15:15,  7.51it/s]
  8%|▊         | 617/7494 [02:37<15:15,  7.51it/s]
  8%|▊         | 618/7494 [02:37<15:15,  7.51it/s]

  8%|▊         | 619/7494 [02:37<07:15, 15.80it/s]

  8%|▊         | 619/7494 [02:37<07:15, 15.80it/s]
  8%|▊         | 620/7494 [02:37<07:15, 15.80it/s]

  8%|▊         | 621/7494 [02:40<20:47,  5.51it/s]

  8%|▊         | 621/7494 [02:40<20:47,  5.51it/s]
  8%|▊         | 622/7494 [02:40<20:47,  5.51it/s]

  8%|▊         | 623/7494 [02:41<22:01,  5.20it/s]

  8%|▊         | 623/7494 [02:41<22:01,  5.20it/s]
  8%|▊         | 624/7494 [02:41<22:00,  5.20it/s]
  8%|▊         | 625/7494 [02:41<22:00,  5.20it/s]

  8%|▊         | 626/7494 [02:41<21:44,  5.26it/s]

  8%|▊         | 626/7494 [02:41<21:44,  5.26it/s]
  8%|▊         | 627/7494 [02:41<21:44,  5.26it/s]

  8%|▊         | 628/7494 [02:42<23:23,  4.89it/s]

  8%|▊         | 628/7494 [02:42<23:23,  4.89it/s]
  8%|▊         | 629/7494 [02:42<23:23,  4.89it/s]

  8%|▊         | 630/7494 [02:42<24:44,  4.62it/s]

  8%|▊         | 630/7494 [02:42<24:44,  4.62it/s]
  8%|▊         | 631/7494 [02:42<24:43,  4.62it/s]
  8%|▊         | 632/7494 [02:42<24:43,  4.62it/s]
  8%|▊         | 633/7494 [02:42<24:43,  4.62it/s]
  8%|▊         | 634/7494 [02:42<24:43,  4.62it/s]
  8%|▊         | 635/7494 [02:42<24:43,  4.62it/s]
  8%|▊         | 636/7494 [02:42<24:42,  4.62it/s]

  9%|▊         | 637/7494 [02:43<17:25,  6.56it/s]

  9%|▊         | 637/7494 [02:43<17:25,  6.56it/s]
  9%|▊         | 638/7494 [02:43<17:25,  6.56it/s]

  9%|▊         | 639/7494 [02:43<19:20,  5.91it/s]

  9%|▊         | 639/7494 [02:43<19:20,  5.91it/s]
  9%|▊         | 640/7494 [02:43<19:20,  5.91it/s]
  9%|▊         | 641/7494 [02:43<19:20,  5.91it/s]
  9%|▊         | 642/7494 [02:43<19:19,  5.91it/s]

  9%|▊         | 643/7494 [02:44<18:15,  6.26it/s]

  9%|▊         | 643/7494 [02:44<18:15,  6.26it/s]
  9%|▊         | 644/7494 [02:44<18:14,  6.26it/s]

  9%|▊         | 645/7494 [02:44<20:19,  5.62it/s]

  9%|▊         | 645/7494 [02:44<20:19,  5.62it/s]
  9%|▊         | 646/7494 [02:44<20:19,  5.62it/s]

  9%|▊         | 647/7494 [02:45<22:46,  5.01it/s]

  9%|▊         | 647/7494 [02:45<22:46,  5.01it/s]
  9%|▊         | 648/7494 [02:45<22:46,  5.01it/s]

  9%|▊         | 649/7494 [02:46<24:39,  4.63it/s]

  9%|▊         | 649/7494 [02:46<24:39,  4.63it/s]
  9%|▊         | 650/7494 [02:46<24:39,  4.63it/s]

  9%|▊         | 651/7494 [02:46<26:17,  4.34it/s]

  9%|▊         | 651/7494 [02:46<26:17,  4.34it/s]
  9%|▊         | 652/7494 [02:46<26:17,  4.34it/s]

  9%|▊         | 653/7494 [02:47<28:16,  4.03it/s]

  9%|▊         | 653/7494 [02:47<28:16,  4.03it/s]
  9%|▊         | 654/7494 [02:47<28:15,  4.03it/s]

  9%|▊         | 655/7494 [02:47<28:57,  3.93it/s]

  9%|▊         | 655/7494 [02:47<28:57,  3.93it/s]
  9%|▉         | 656/7494 [02:47<28:57,  3.93it/s]
  9%|▉         | 657/7494 [02:47<28:57,  3.93it/s]

  9%|▉         | 658/7494 [02:48<26:08,  4.36it/s]

  9%|▉         | 658/7494 [02:48<26:08,  4.36it/s]
  9%|▉         | 659/7494 [02:48<26:08,  4.36it/s]

  9%|▉         | 660/7494 [02:48<27:20,  4.16it/s]

  9%|▉         | 660/7494 [02:48<27:20,  4.16it/s]
  9%|▉         | 661/7494 [02:48<27:20,  4.16it/s]

  9%|▉         | 662/7494 [02:49<28:57,  3.93it/s]

  9%|▉         | 662/7494 [02:49<28:57,  3.93it/s]
  9%|▉         | 663/7494 [02:49<28:57,  3.93it/s]

  9%|▉         | 664/7494 [02:49<29:33,  3.85it/s]

  9%|▉         | 664/7494 [02:49<29:33,  3.85it/s]
  9%|▉         | 665/7494 [02:50<29:32,  3.85it/s]

  9%|▉         | 666/7494 [02:50<33:01,  3.45it/s]

  9%|▉         | 666/7494 [02:50<33:01,  3.45it/s]
  9%|▉         | 667/7494 [02:50<33:01,  3.45it/s]

  9%|▉         | 668/7494 [02:53<1:06:49,  1.70it/s]

  9%|▉         | 668/7494 [02:53<1:06:49,  1.70it/s]
  9%|▉         | 669/7494 [02:53<1:06:48,  1.70it/s]

  9%|▉         | 670/7494 [02:53<57:01,  1.99it/s]

  9%|▉         | 670/7494 [02:53<57:01,  1.99it/s]
  9%|▉         | 671/7494 [02:53<57:00,  1.99it/s]

  9%|▉         | 672/7494 [02:54<49:45,  2.29it/s]

  9%|▉         | 672/7494 [02:54<49:45,  2.29it/s]
  9%|▉         | 673/7494 [02:54<49:45,  2.29it/s]

  9%|▉         | 674/7494 [02:55<44:02,  2.58it/s]

  9%|▉         | 674/7494 [02:55<44:02,  2.58it/s]
  9%|▉         | 675/7494 [02:55<44:01,  2.58it/s]

  9%|▉         | 676/7494 [02:55<40:32,  2.80it/s]

  9%|▉         | 676/7494 [02:55<40:32,  2.80it/s]
  9%|▉         | 677/7494 [02:55<40:32,  2.80it/s]

  9%|▉         | 678/7494 [02:56<37:17,  3.05it/s]

  9%|▉         | 678/7494 [02:56<37:17,  3.05it/s]
  9%|▉         | 679/7494 [02:56<37:16,  3.05it/s]

  9%|▉         | 680/7494 [02:56<35:43,  3.18it/s]

  9%|▉         | 680/7494 [02:56<35:43,  3.18it/s]
  9%|▉         | 681/7494 [02:56<35:43,  3.18it/s]

  9%|▉         | 682/7494 [02:57<34:03,  3.33it/s]

  9%|▉         | 682/7494 [02:57<34:03,  3.33it/s]
  9%|▉         | 683/7494 [02:57<34:03,  3.33it/s]

  9%|▉         | 684/7494 [02:57<33:38,  3.37it/s]

  9%|▉         | 684/7494 [02:57<33:38,  3.37it/s]
  9%|▉         | 685/7494 [02:57<33:37,  3.37it/s]
  9%|▉         | 686/7494 [02:57<33:37,  3.37it/s]

  9%|▉         | 687/7494 [02:58<28:14,  4.02it/s]

  9%|▉         | 687/7494 [02:58<28:14,  4.02it/s]
  9%|▉         | 688/7494 [02:58<28:14,  4.02it/s]

  9%|▉         | 689/7494 [02:58<28:56,  3.92it/s]

  9%|▉         | 689/7494 [02:58<28:56,  3.92it/s]
  9%|▉         | 690/7494 [02:58<28:55,  3.92it/s]
  9%|▉         | 691/7494 [02:58<28:55,  3.92it/s]
  9%|▉         | 692/7494 [02:58<28:55,  3.92it/s]
  9%|▉         | 693/7494 [02:58<28:55,  3.92it/s]
  9%|▉         | 694/7494 [02:58<28:54,  3.92it/s]
  9%|▉         | 695/7494 [02:58<28:54,  3.92it/s]
  9%|▉         | 696/7494 [02:58<28:54,  3.92it/s]
  9%|▉         | 697/7494 [02:58<28:54,  3.92it/s]
  9%|▉         | 698/7494 [02:58<28:53,  3.92it/s]
  9%|▉         | 699/7494 [02:58<28:53,  3.92it/s]
  9%|▉         | 700/7494 [02:58<28:53,  3.92it/s]

  9%|▉         | 701/7494 [02:59<12:19,  9.18it/s]

  9%|▉         | 701/7494 [02:59<12:19,  9.18it/s]
  9%|▉         | 702/7494 [02:59<12:19,  9.18it/s]

  9%|▉         | 703/7494 [02:59<14:58,  7.55it/s]

  9%|▉         | 703/7494 [02:59<14:58,  7.55it/s]
  9%|▉         | 704/7494 [02:59<14:58,  7.55it/s]

  9%|▉         | 705/7494 [03:00<17:31,  6.46it/s]

  9%|▉         | 705/7494 [03:00<17:31,  6.46it/s]
  9%|▉         | 706/7494 [03:00<17:31,  6.46it/s]

  9%|▉         | 707/7494 [03:01<20:16,  5.58it/s]

  9%|▉         | 707/7494 [03:01<20:16,  5.58it/s]
  9%|▉         | 708/7494 [03:01<20:16,  5.58it/s]

  9%|▉         | 709/7494 [03:01<22:19,  5.06it/s]

  9%|▉         | 709/7494 [03:01<22:19,  5.06it/s]
  9%|▉         | 710/7494 [03:01<22:19,  5.06it/s]

  9%|▉         | 711/7494 [03:02<24:26,  4.62it/s]

  9%|▉         | 711/7494 [03:02<24:26,  4.62it/s]
 10%|▉         | 712/7494 [03:02<24:26,  4.62it/s]
 10%|▉         | 713/7494 [03:02<24:26,  4.62it/s]

 10%|▉         | 714/7494 [03:02<22:54,  4.93it/s]

 10%|▉         | 714/7494 [03:02<22:54,  4.93it/s]
 10%|▉         | 715/7494 [03:02<22:54,  4.93it/s]

 10%|▉         | 716/7494 [03:04<36:28,  3.10it/s]

 10%|▉         | 716/7494 [03:04<36:28,  3.10it/s]
 10%|▉         | 717/7494 [03:04<36:28,  3.10it/s]

 10%|▉         | 718/7494 [03:06<56:28,  2.00it/s]

 10%|▉         | 718/7494 [03:06<56:28,  2.00it/s]
 10%|▉         | 719/7494 [03:06<56:27,  2.00it/s]

 10%|▉         | 720/7494 [03:06<49:10,  2.30it/s]

 10%|▉         | 720/7494 [03:06<49:10,  2.30it/s]
 10%|▉         | 721/7494 [03:06<49:09,  2.30it/s]

 10%|▉         | 722/7494 [03:07<44:28,  2.54it/s]

 10%|▉         | 722/7494 [03:07<44:28,  2.54it/s]
 10%|▉         | 723/7494 [03:07<44:27,  2.54it/s]

 10%|▉         | 724/7494 [03:07<40:43,  2.77it/s]

 10%|▉         | 724/7494 [03:07<40:43,  2.77it/s]
 10%|▉         | 725/7494 [03:07<40:42,  2.77it/s]

 10%|▉         | 726/7494 [03:08<38:55,  2.90it/s]

 10%|▉         | 726/7494 [03:08<38:55,  2.90it/s]
 10%|▉         | 727/7494 [03:08<38:54,  2.90it/s]

 10%|▉         | 728/7494 [03:08<37:00,  3.05it/s]

 10%|▉         | 728/7494 [03:08<37:00,  3.05it/s]
 10%|▉         | 729/7494 [03:08<36:59,  3.05it/s]

 10%|▉         | 730/7494 [03:09<36:09,  3.12it/s]

 10%|▉         | 730/7494 [03:09<36:09,  3.12it/s]
 10%|▉         | 731/7494 [03:09<36:08,  3.12it/s]

 10%|▉         | 732/7494 [03:10<34:52,  3.23it/s]

 10%|▉         | 732/7494 [03:10<34:52,  3.23it/s]
 10%|▉         | 733/7494 [03:10<34:51,  3.23it/s]
 10%|▉         | 734/7494 [03:10<34:51,  3.23it/s]
 10%|▉         | 735/7494 [03:10<34:51,  3.23it/s]

 10%|▉         | 736/7494 [03:10<26:44,  4.21it/s]

 10%|▉         | 736/7494 [03:10<26:44,  4.21it/s]
 10%|▉         | 737/7494 [03:10<26:44,  4.21it/s]

 10%|▉         | 738/7494 [03:11<28:30,  3.95it/s]

 10%|▉         | 738/7494 [03:11<28:30,  3.95it/s]
 10%|▉         | 739/7494 [03:11<28:30,  3.95it/s]
 10%|▉         | 740/7494 [03:11<28:29,  3.95it/s]

 10%|▉         | 741/7494 [03:11<26:00,  4.33it/s]

 10%|▉         | 741/7494 [03:11<26:00,  4.33it/s]
 10%|▉         | 742/7494 [03:11<25:59,  4.33it/s]

 10%|▉         | 743/7494 [03:12<27:54,  4.03it/s]

 10%|▉         | 743/7494 [03:12<27:54,  4.03it/s]
 10%|▉         | 744/7494 [03:12<27:54,  4.03it/s]
 10%|▉         | 745/7494 [03:12<27:53,  4.03it/s]
 10%|▉         | 746/7494 [03:12<27:53,  4.03it/s]
 10%|▉         | 747/7494 [03:12<27:53,  4.03it/s]
 10%|▉         | 748/7494 [03:12<27:53,  4.03it/s]
 10%|▉         | 749/7494 [03:12<27:52,  4.03it/s]

 10%|█         | 750/7494 [03:13<17:30,  6.42it/s]

 10%|█         | 750/7494 [03:13<17:30,  6.42it/s]
 10%|█         | 751/7494 [03:13<17:29,  6.42it/s]
 10%|█         | 752/7494 [03:13<17:29,  6.42it/s]

 10%|█         | 753/7494 [03:13<18:56,  5.93it/s]

 10%|█         | 753/7494 [03:13<18:56,  5.93it/s]
 10%|█         | 754/7494 [03:13<18:56,  5.93it/s]
 10%|█         | 755/7494 [03:13<18:55,  5.93it/s]

 10%|█         | 756/7494 [03:14<19:34,  5.74it/s]

 10%|█         | 756/7494 [03:14<19:34,  5.74it/s]
 10%|█         | 757/7494 [03:14<19:33,  5.74it/s]

 10%|█         | 758/7494 [03:14<22:37,  4.96it/s]

 10%|█         | 758/7494 [03:14<22:37,  4.96it/s]
 10%|█         | 759/7494 [03:14<22:37,  4.96it/s]
 10%|█         | 760/7494 [03:14<22:37,  4.96it/s]
 10%|█         | 761/7494 [03:14<22:37,  4.96it/s]
 10%|█         | 762/7494 [03:14<22:37,  4.96it/s]
 10%|█         | 763/7494 [03:14<22:36,  4.96it/s]
 10%|█         | 764/7494 [03:14<22:36,  4.96it/s]
 10%|█         | 765/7494 [03:14<22:36,  4.96it/s]
 10%|█         | 766/7494 [03:14<22:36,  4.96it/s]
 10%|█         | 767/7494 [03:14<22:36,  4.96it/s]
 10%|█         | 768/7494 [03:14<22:35,  4.96it/s]
 10%|█         | 769/7494 [03:14<22:35,  4.96it/s]
 10%|█         | 770/7494 [03:14<22:35,  4.96it/s]
 10%|█         | 771/7494 [03:14<22:35,  4.96it/s]

 10%|█         | 772/7494 [03:15<10:43, 10.45it/s]

 10%|█         | 772/7494 [03:15<10:43, 10.45it/s]
 10%|█         | 773/7494 [03:15<10:43, 10.45it/s]
 10%|█         | 774/7494 [03:15<10:43, 10.45it/s]

 10%|█         | 775/7494 [03:16<17:44,  6.31it/s]

 10%|█         | 775/7494 [03:16<17:44,  6.31it/s]
 10%|█         | 776/7494 [03:16<17:44,  6.31it/s]

 10%|█         | 777/7494 [03:18<31:11,  3.59it/s]

 10%|█         | 777/7494 [03:18<31:11,  3.59it/s]
 10%|█         | 778/7494 [03:18<31:11,  3.59it/s]

 10%|█         | 779/7494 [03:19<31:11,  3.59it/s]

 10%|█         | 779/7494 [03:19<31:11,  3.59it/s]
 10%|█         | 780/7494 [03:19<31:10,  3.59it/s]

 10%|█         | 781/7494 [03:20<31:34,  3.54it/s]

 10%|█         | 781/7494 [03:20<31:34,  3.54it/s]
 10%|█         | 782/7494 [03:20<31:34,  3.54it/s]

 10%|█         | 783/7494 [03:20<32:04,  3.49it/s]

 10%|█         | 783/7494 [03:20<32:04,  3.49it/s]
 10%|█         | 784/7494 [03:20<32:04,  3.49it/s]

 10%|█         | 785/7494 [03:21<33:00,  3.39it/s]

 10%|█         | 785/7494 [03:21<33:00,  3.39it/s]
 10%|█         | 786/7494 [03:21<32:59,  3.39it/s]

 11%|█         | 787/7494 [03:21<33:26,  3.34it/s]

 11%|█         | 787/7494 [03:21<33:26,  3.34it/s]
 11%|█         | 788/7494 [03:21<33:26,  3.34it/s]

 11%|█         | 789/7494 [03:22<33:45,  3.31it/s]

 11%|█         | 789/7494 [03:22<33:45,  3.31it/s]
 11%|█         | 790/7494 [03:22<33:45,  3.31it/s]

 11%|█         | 791/7494 [03:23<34:09,  3.27it/s]

 11%|█         | 791/7494 [03:23<34:09,  3.27it/s]
 11%|█         | 792/7494 [03:23<34:09,  3.27it/s]
 11%|█         | 793/7494 [03:23<34:09,  3.27it/s]

 11%|█         | 794/7494 [03:23<29:58,  3.73it/s]

 11%|█         | 794/7494 [03:23<29:58,  3.73it/s]
 11%|█         | 795/7494 [03:23<29:58,  3.73it/s]
 11%|█         | 796/7494 [03:23<29:58,  3.73it/s]
 11%|█         | 797/7494 [03:23<29:57,  3.73it/s]
 11%|█         | 798/7494 [03:23<29:57,  3.73it/s]

 11%|█         | 799/7494 [03:24<22:48,  4.89it/s]

 11%|█         | 799/7494 [03:24<22:48,  4.89it/s]
 11%|█         | 800/7494 [03:24<22:48,  4.89it/s]

 11%|█         | 801/7494 [03:25<25:20,  4.40it/s]

 11%|█         | 801/7494 [03:25<25:20,  4.40it/s]
 11%|█         | 802/7494 [03:25<25:20,  4.40it/s]
 11%|█         | 803/7494 [03:25<25:20,  4.40it/s]

 11%|█         | 804/7494 [03:25<24:30,  4.55it/s]

 11%|█         | 804/7494 [03:25<24:30,  4.55it/s]
 11%|█         | 805/7494 [03:25<24:30,  4.55it/s]
 11%|█         | 806/7494 [03:25<24:29,  4.55it/s]
 11%|█         | 807/7494 [03:25<24:29,  4.55it/s]
 11%|█         | 808/7494 [03:25<24:29,  4.55it/s]

 11%|█         | 809/7494 [03:26<19:53,  5.60it/s]

 11%|█         | 809/7494 [03:26<19:53,  5.60it/s]
 11%|█         | 810/7494 [03:26<19:53,  5.60it/s]

 11%|█         | 811/7494 [03:26<22:37,  4.92it/s]

 11%|█         | 811/7494 [03:26<22:37,  4.92it/s]
 11%|█         | 812/7494 [03:26<22:37,  4.92it/s]
 11%|█         | 813/7494 [03:26<22:37,  4.92it/s]

 11%|█         | 814/7494 [03:27<22:52,  4.87it/s]

 11%|█         | 814/7494 [03:27<22:52,  4.87it/s]
 11%|█         | 815/7494 [03:27<22:52,  4.87it/s]
 11%|█         | 816/7494 [03:27<22:52,  4.87it/s]

 11%|█         | 817/7494 [03:28<23:14,  4.79it/s]

 11%|█         | 817/7494 [03:28<23:14,  4.79it/s]
 11%|█         | 818/7494 [03:28<23:14,  4.79it/s]

 11%|█         | 819/7494 [03:30<45:55,  2.42it/s]

 11%|█         | 819/7494 [03:30<45:55,  2.42it/s]
 11%|█         | 820/7494 [03:30<45:54,  2.42it/s]
 11%|█         | 821/7494 [03:30<45:54,  2.42it/s]

 11%|█         | 822/7494 [03:31<46:22,  2.40it/s]

 11%|█         | 822/7494 [03:31<46:22,  2.40it/s]
 11%|█         | 823/7494 [03:31<46:22,  2.40it/s]

 11%|█         | 824/7494 [03:32<43:50,  2.54it/s]

 11%|█         | 824/7494 [03:32<43:50,  2.54it/s]
 11%|█         | 825/7494 [03:32<43:49,  2.54it/s]

 11%|█         | 826/7494 [03:32<41:22,  2.69it/s]

 11%|█         | 826/7494 [03:32<41:22,  2.69it/s]
 11%|█         | 827/7494 [03:32<41:21,  2.69it/s]
 11%|█         | 828/7494 [03:32<41:21,  2.69it/s]

 11%|█         | 829/7494 [03:33<35:34,  3.12it/s]

 11%|█         | 829/7494 [03:33<35:34,  3.12it/s]
 11%|█         | 830/7494 [03:33<35:34,  3.12it/s]

 11%|█         | 831/7494 [03:34<35:23,  3.14it/s]

 11%|█         | 831/7494 [03:34<35:23,  3.14it/s]
 11%|█         | 832/7494 [03:34<35:23,  3.14it/s]

 11%|█         | 833/7494 [03:34<35:24,  3.14it/s]

 11%|█         | 833/7494 [03:34<35:24,  3.14it/s]
 11%|█         | 834/7494 [03:34<35:24,  3.14it/s]

 11%|█         | 835/7494 [03:35<35:33,  3.12it/s]

 11%|█         | 835/7494 [03:35<35:33,  3.12it/s]
 11%|█         | 836/7494 [03:35<35:33,  3.12it/s]

 11%|█         | 837/7494 [03:36<34:44,  3.19it/s]

 11%|█         | 837/7494 [03:36<34:44,  3.19it/s]
 11%|█         | 838/7494 [03:36<34:44,  3.19it/s]

 11%|█         | 839/7494 [03:36<34:49,  3.19it/s]

 11%|█         | 839/7494 [03:36<34:49,  3.19it/s]
 11%|█         | 840/7494 [03:36<34:48,  3.19it/s]
 11%|█         | 841/7494 [03:36<34:48,  3.19it/s]

 11%|█         | 842/7494 [03:37<30:25,  3.64it/s]

 11%|█         | 842/7494 [03:37<30:25,  3.64it/s]
 11%|█         | 843/7494 [03:37<30:25,  3.64it/s]
 11%|█▏        | 844/7494 [03:37<30:24,  3.64it/s]

 11%|█▏        | 845/7494 [03:38<27:52,  3.98it/s]

 11%|█▏        | 845/7494 [03:38<27:52,  3.98it/s]
 11%|█▏        | 846/7494 [03:38<27:52,  3.98it/s]

 11%|█▏        | 847/7494 [03:38<30:30,  3.63it/s]

 11%|█▏        | 847/7494 [03:38<30:30,  3.63it/s]
 11%|█▏        | 848/7494 [03:38<30:30,  3.63it/s]

 11%|█▏        | 849/7494 [03:39<30:53,  3.59it/s]

 11%|█▏        | 849/7494 [03:39<30:53,  3.59it/s]
 11%|█▏        | 850/7494 [03:39<30:53,  3.59it/s]

 11%|█▏        | 851/7494 [03:39<31:36,  3.50it/s]

 11%|█▏        | 851/7494 [03:39<31:36,  3.50it/s]
 11%|█▏        | 852/7494 [03:39<31:36,  3.50it/s]

 11%|█▏        | 853/7494 [03:40<31:53,  3.47it/s]

 11%|█▏        | 853/7494 [03:40<31:53,  3.47it/s]
 11%|█▏        | 854/7494 [03:40<31:52,  3.47it/s]

 11%|█▏        | 855/7494 [03:41<32:09,  3.44it/s]

 11%|█▏        | 855/7494 [03:41<32:09,  3.44it/s]
 11%|█▏        | 856/7494 [03:41<32:09,  3.44it/s]

 11%|█▏        | 857/7494 [03:43<1:09:01,  1.60it/s]

 11%|█▏        | 857/7494 [03:43<1:09:01,  1.60it/s]
 11%|█▏        | 858/7494 [03:43<1:09:00,  1.60it/s]

 11%|█▏        | 859/7494 [03:44<58:02,  1.91it/s]

 11%|█▏        | 859/7494 [03:44<58:02,  1.91it/s]
 11%|█▏        | 860/7494 [03:44<58:01,  1.91it/s]

 11%|█▏        | 861/7494 [03:45<50:24,  2.19it/s]

 11%|█▏        | 861/7494 [03:45<50:24,  2.19it/s]
 12%|█▏        | 862/7494 [03:45<50:24,  2.19it/s]
 12%|█▏        | 863/7494 [03:45<50:23,  2.19it/s]
 12%|█▏        | 864/7494 [03:45<50:23,  2.19it/s]

 12%|█▏        | 865/7494 [03:45<34:10,  3.23it/s]

 12%|█▏        | 865/7494 [03:45<34:10,  3.23it/s]
 12%|█▏        | 866/7494 [03:45<34:10,  3.23it/s]
 12%|█▏        | 867/7494 [03:45<34:10,  3.23it/s]

 12%|█▏        | 868/7494 [03:46<29:42,  3.72it/s]

 12%|█▏        | 868/7494 [03:46<29:42,  3.72it/s]
 12%|█▏        | 869/7494 [03:46<29:42,  3.72it/s]

 12%|█▏        | 870/7494 [03:46<29:29,  3.74it/s]

 12%|█▏        | 870/7494 [03:46<29:29,  3.74it/s]
 12%|█▏        | 871/7494 [03:46<29:29,  3.74it/s]

 12%|█▏        | 872/7494 [03:47<29:42,  3.71it/s]

 12%|█▏        | 872/7494 [03:47<29:42,  3.71it/s]
 12%|█▏        | 873/7494 [03:47<29:42,  3.71it/s]

 12%|█▏        | 874/7494 [03:47<29:53,  3.69it/s]

 12%|█▏        | 874/7494 [03:47<29:53,  3.69it/s]
 12%|█▏        | 875/7494 [03:47<29:52,  3.69it/s]

 12%|█▏        | 876/7494 [03:48<30:26,  3.62it/s]

 12%|█▏        | 876/7494 [03:48<30:26,  3.62it/s]
 12%|█▏        | 877/7494 [03:48<30:26,  3.62it/s]

 12%|█▏        | 878/7494 [03:48<30:10,  3.65it/s]

 12%|█▏        | 878/7494 [03:48<30:10,  3.65it/s]
 12%|█▏        | 879/7494 [03:49<30:09,  3.65it/s]

 12%|█▏        | 880/7494 [03:49<30:12,  3.65it/s]

 12%|█▏        | 880/7494 [03:49<30:12,  3.65it/s]
 12%|█▏        | 881/7494 [03:49<30:12,  3.65it/s]

 12%|█▏        | 882/7494 [03:50<29:35,  3.72it/s]

 12%|█▏        | 882/7494 [03:50<29:35,  3.72it/s]
 12%|█▏        | 883/7494 [03:50<29:35,  3.72it/s]

 12%|█▏        | 884/7494 [03:50<29:50,  3.69it/s]

 12%|█▏        | 884/7494 [03:50<29:50,  3.69it/s]
 12%|█▏        | 885/7494 [03:50<29:50,  3.69it/s]

 12%|█▏        | 886/7494 [03:51<29:45,  3.70it/s]

 12%|█▏        | 886/7494 [03:51<29:45,  3.70it/s]
 12%|█▏        | 887/7494 [03:51<29:44,  3.70it/s]

 12%|█▏        | 888/7494 [03:51<30:20,  3.63it/s]

 12%|█▏        | 888/7494 [03:51<30:20,  3.63it/s]
 12%|█▏        | 889/7494 [03:51<30:20,  3.63it/s]

 12%|█▏        | 890/7494 [03:52<30:32,  3.60it/s]

 12%|█▏        | 890/7494 [03:52<30:32,  3.60it/s]
 12%|█▏        | 891/7494 [03:52<30:31,  3.60it/s]

 12%|█▏        | 892/7494 [03:52<30:17,  3.63it/s]

 12%|█▏        | 892/7494 [03:52<30:17,  3.63it/s]
 12%|█▏        | 893/7494 [03:52<30:17,  3.63it/s]
 12%|█▏        | 894/7494 [03:52<30:17,  3.63it/s]

 12%|█▏        | 895/7494 [03:53<26:33,  4.14it/s]

 12%|█▏        | 895/7494 [03:53<26:33,  4.14it/s]
 12%|█▏        | 896/7494 [03:53<26:33,  4.14it/s]

 12%|█▏        | 897/7494 [03:54<30:44,  3.58it/s]

 12%|█▏        | 897/7494 [03:54<30:44,  3.58it/s]
 12%|█▏        | 898/7494 [03:54<30:44,  3.58it/s]
 12%|█▏        | 899/7494 [03:54<30:44,  3.58it/s]

 12%|█▏        | 900/7494 [03:56<54:55,  2.00it/s]

 12%|█▏        | 900/7494 [03:56<54:55,  2.00it/s]
 12%|█▏        | 901/7494 [03:56<54:54,  2.00it/s]

 12%|█▏        | 902/7494 [03:57<48:47,  2.25it/s]

 12%|█▏        | 902/7494 [03:57<48:47,  2.25it/s]
 12%|█▏        | 903/7494 [03:57<48:47,  2.25it/s]
 12%|█▏        | 904/7494 [03:57<48:46,  2.25it/s]
 12%|█▏        | 905/7494 [03:57<48:46,  2.25it/s]
 12%|█▏        | 906/7494 [03:57<48:46,  2.25it/s]
 12%|█▏        | 907/7494 [03:57<48:45,  2.25it/s]

 12%|█▏        | 908/7494 [03:57<28:50,  3.81it/s]

 12%|█▏        | 908/7494 [03:57<28:50,  3.81it/s]
 12%|█▏        | 909/7494 [03:57<28:50,  3.81it/s]

 12%|█▏        | 910/7494 [03:58<29:27,  3.73it/s]

 12%|█▏        | 910/7494 [03:58<29:27,  3.73it/s]
 12%|█▏        | 911/7494 [03:58<29:26,  3.73it/s]
 12%|█▏        | 912/7494 [03:58<29:26,  3.73it/s]

 12%|█▏        | 913/7494 [03:59<26:49,  4.09it/s]

 12%|█▏        | 913/7494 [03:59<26:49,  4.09it/s]
 12%|█▏        | 914/7494 [03:59<26:49,  4.09it/s]

 12%|█▏        | 915/7494 [03:59<28:00,  3.91it/s]

 12%|█▏        | 915/7494 [03:59<28:00,  3.91it/s]
 12%|█▏        | 916/7494 [03:59<28:00,  3.91it/s]

 12%|█▏        | 917/7494 [04:00<28:21,  3.87it/s]

 12%|█▏        | 917/7494 [04:00<28:21,  3.87it/s]
 12%|█▏        | 918/7494 [04:00<28:20,  3.87it/s]

 12%|█▏        | 919/7494 [04:00<29:29,  3.72it/s]

 12%|█▏        | 919/7494 [04:00<29:29,  3.72it/s]
 12%|█▏        | 920/7494 [04:00<29:28,  3.72it/s]

 12%|█▏        | 921/7494 [04:01<29:44,  3.68it/s]

 12%|█▏        | 921/7494 [04:01<29:44,  3.68it/s]
 12%|█▏        | 922/7494 [04:01<29:44,  3.68it/s]

 12%|█▏        | 923/7494 [04:01<30:43,  3.56it/s]

 12%|█▏        | 923/7494 [04:01<30:43,  3.56it/s]
 12%|█▏        | 924/7494 [04:01<30:43,  3.56it/s]
 12%|█▏        | 925/7494 [04:02<30:42,  3.56it/s]

 12%|█▏        | 926/7494 [04:02<26:43,  4.10it/s]

 12%|█▏        | 926/7494 [04:02<26:43,  4.10it/s]
 12%|█▏        | 927/7494 [04:02<26:43,  4.10it/s]

 12%|█▏        | 928/7494 [04:03<27:48,  3.94it/s]

 12%|█▏        | 928/7494 [04:03<27:48,  3.94it/s]
 12%|█▏        | 929/7494 [04:03<27:48,  3.94it/s]

 12%|█▏        | 930/7494 [04:03<28:24,  3.85it/s]

 12%|█▏        | 930/7494 [04:03<28:24,  3.85it/s]
 12%|█▏        | 931/7494 [04:03<28:24,  3.85it/s]

 12%|█▏        | 932/7494 [04:04<29:16,  3.74it/s]

 12%|█▏        | 932/7494 [04:04<29:16,  3.74it/s]
 12%|█▏        | 933/7494 [04:04<29:15,  3.74it/s]

 12%|█▏        | 934/7494 [04:04<29:36,  3.69it/s]

 12%|█▏        | 934/7494 [04:04<29:36,  3.69it/s]
 12%|█▏        | 935/7494 [04:04<29:36,  3.69it/s]

 12%|█▏        | 936/7494 [04:05<29:23,  3.72it/s]

 12%|█▏        | 936/7494 [04:05<29:23,  3.72it/s]
 13%|█▎        | 937/7494 [04:05<29:23,  3.72it/s]

 13%|█▎        | 938/7494 [04:05<29:58,  3.65it/s]

 13%|█▎        | 938/7494 [04:05<29:58,  3.65it/s]
 13%|█▎        | 939/7494 [04:05<29:58,  3.65it/s]

 13%|█▎        | 940/7494 [04:06<29:52,  3.66it/s]

 13%|█▎        | 940/7494 [04:06<29:52,  3.66it/s]
 13%|█▎        | 941/7494 [04:06<29:52,  3.66it/s]

 13%|█▎        | 942/7494 [04:09<1:08:35,  1.59it/s]

 13%|█▎        | 942/7494 [04:09<1:08:35,  1.59it/s]
 13%|█▎        | 943/7494 [04:09<1:08:34,  1.59it/s]

 13%|█▎        | 944/7494 [04:09<57:15,  1.91it/s]

 13%|█▎        | 944/7494 [04:09<57:15,  1.91it/s]
 13%|█▎        | 945/7494 [04:09<57:15,  1.91it/s]

 13%|█▎        | 946/7494 [04:10<49:36,  2.20it/s]

 13%|█▎        | 946/7494 [04:10<49:36,  2.20it/s]
 13%|█▎        | 947/7494 [04:10<49:36,  2.20it/s]

 13%|█▎        | 948/7494 [04:11<43:37,  2.50it/s]

 13%|█▎        | 948/7494 [04:11<43:37,  2.50it/s]
 13%|█▎        | 949/7494 [04:11<43:37,  2.50it/s]

 13%|█▎        | 950/7494 [04:11<40:03,  2.72it/s]

 13%|█▎        | 950/7494 [04:11<40:03,  2.72it/s]
 13%|█▎        | 951/7494 [04:11<40:03,  2.72it/s]

 13%|█▎        | 952/7494 [04:12<36:53,  2.96it/s]

 13%|█▎        | 952/7494 [04:12<36:53,  2.96it/s]
 13%|█▎        | 953/7494 [04:12<36:53,  2.96it/s]

 13%|█▎        | 954/7494 [04:12<35:19,  3.09it/s]

 13%|█▎        | 954/7494 [04:12<35:19,  3.09it/s]
 13%|█▎        | 955/7494 [04:12<35:19,  3.09it/s]

 13%|█▎        | 956/7494 [04:13<34:07,  3.19it/s]

 13%|█▎        | 956/7494 [04:13<34:07,  3.19it/s]
 13%|█▎        | 957/7494 [04:13<34:07,  3.19it/s]

 13%|█▎        | 958/7494 [04:13<32:25,  3.36it/s]

 13%|█▎        | 958/7494 [04:13<32:25,  3.36it/s]
 13%|█▎        | 959/7494 [04:13<32:25,  3.36it/s]

 13%|█▎        | 960/7494 [04:14<32:02,  3.40it/s]

 13%|█▎        | 960/7494 [04:14<32:02,  3.40it/s]
 13%|█▎        | 961/7494 [04:14<32:02,  3.40it/s]

 13%|█▎        | 962/7494 [04:14<30:58,  3.52it/s]

 13%|█▎        | 962/7494 [04:14<30:58,  3.52it/s]
 13%|█▎        | 963/7494 [04:14<30:57,  3.52it/s]

 13%|█▎        | 964/7494 [04:15<30:46,  3.54it/s]

 13%|█▎        | 964/7494 [04:15<30:46,  3.54it/s]
 13%|█▎        | 965/7494 [04:15<30:46,  3.54it/s]

 13%|█▎        | 966/7494 [04:16<30:12,  3.60it/s]

 13%|█▎        | 966/7494 [04:16<30:12,  3.60it/s]
 13%|█▎        | 967/7494 [04:16<30:12,  3.60it/s]
 13%|█▎        | 968/7494 [04:16<30:12,  3.60it/s]
 13%|█▎        | 969/7494 [04:16<30:12,  3.60it/s]
 13%|█▎        | 970/7494 [04:16<30:11,  3.60it/s]

 13%|█▎        | 971/7494 [04:16<21:03,  5.16it/s]

 13%|█▎        | 971/7494 [04:16<21:03,  5.16it/s]
 13%|█▎        | 972/7494 [04:16<21:03,  5.16it/s]
 13%|█▎        | 973/7494 [04:16<21:02,  5.16it/s]
 13%|█▎        | 974/7494 [04:16<21:02,  5.16it/s]
 13%|█▎        | 975/7494 [04:16<21:02,  5.16it/s]

 13%|█▎        | 976/7494 [04:17<17:01,  6.38it/s]

 13%|█▎        | 976/7494 [04:17<17:01,  6.38it/s]
 13%|█▎        | 977/7494 [04:17<17:01,  6.38it/s]

 13%|█▎        | 978/7494 [04:17<19:34,  5.55it/s]

 13%|█▎        | 978/7494 [04:17<19:34,  5.55it/s]
 13%|█▎        | 979/7494 [04:17<19:33,  5.55it/s]

 13%|█▎        | 980/7494 [04:18<21:46,  4.99it/s]

 13%|█▎        | 980/7494 [04:18<21:46,  4.99it/s]
 13%|█▎        | 981/7494 [04:18<21:46,  4.99it/s]

 13%|█▎        | 982/7494 [04:18<23:59,  4.52it/s]

 13%|█▎        | 982/7494 [04:18<23:59,  4.52it/s]
 13%|█▎        | 983/7494 [04:18<23:59,  4.52it/s]

 13%|█▎        | 984/7494 [04:19<27:48,  3.90it/s]

 13%|█▎        | 984/7494 [04:19<27:48,  3.90it/s]
 13%|█▎        | 985/7494 [04:19<27:47,  3.90it/s]

 13%|█▎        | 986/7494 [04:22<58:16,  1.86it/s]

 13%|█▎        | 986/7494 [04:22<58:16,  1.86it/s]
 13%|█▎        | 987/7494 [04:22<58:15,  1.86it/s]
 13%|█▎        | 988/7494 [04:22<58:15,  1.86it/s]
 13%|█▎        | 989/7494 [04:22<58:14,  1.86it/s]
 13%|█▎        | 990/7494 [04:22<58:14,  1.86it/s]

 13%|█▎        | 991/7494 [04:22<35:53,  3.02it/s]

 13%|█▎        | 991/7494 [04:22<35:53,  3.02it/s]
 13%|█▎        | 992/7494 [04:22<35:52,  3.02it/s]

 13%|█▎        | 993/7494 [04:23<34:28,  3.14it/s]

 13%|█▎        | 993/7494 [04:23<34:28,  3.14it/s]
 13%|█▎        | 994/7494 [04:23<34:27,  3.14it/s]
 13%|█▎        | 995/7494 [04:23<34:27,  3.14it/s]

 13%|█▎        | 996/7494 [04:23<29:57,  3.61it/s]

 13%|█▎        | 996/7494 [04:23<29:57,  3.61it/s]
 13%|█▎        | 997/7494 [04:23<29:57,  3.61it/s]
 13%|█▎        | 998/7494 [04:23<29:57,  3.61it/s]

 13%|█▎        | 1000/7494 [04:24<28:36,  3.78it/s]
 11%|█         | 1/9 [04:29<35:53, 269.13s/it]

 13%|█▎        | 999/7494 [04:24<26:28,  4.09it/s]
 13%|█▎        | 1000/7494 [04:24<26:28,  4.09it/s]
                     MLUT4_AT.232A  MLUT4_RQ.2BTLS  MLUT4_TE.252A  \
Time
2025-05-25 05:20:05       0.852984        0.855904       0.842414
2025-05-25 05:30:05       0.876511        0.874611       0.847393
2025-05-25 05:35:05       0.877479        0.885625       0.860507
2025-05-25 05:40:05       0.878625        0.849563       0.860377
2025-05-25 05:45:05       0.877141        0.871733       0.849503

                     MLUT4_SIV.B7921  MLUT4_AIA792101B  MLUT4_PDT.956  \
Time
2025-05-25 05:20:05         0.903258          0.872434       0.899219
2025-05-25 05:30:05         0.903158          0.872244       0.916372
2025-05-25 05:35:05         0.903349          0.872158       0.914016
2025-05-25 05:40:05         0.903300          0.872148       0.910043
2025-05-25 05:45:05         0.903219          0.872148       0.914286

                     MLUT4_TE.252F  MLUT4_PT.231  MLUT4_FIC.231C  \
Time
2025-05-25 05:20:05       0.887579      0.869354        0.857897
2025-05-25 05:30:05       0.879727      0.867235        0.857888
2025-05-25 05:35:05       0.893944      0.867041        0.857883
2025-05-25 05:40:05       0.872940      0.866275        0.857879
2025-05-25 05:45:05       0.876962      0.865383        0.857874

                     MLUT4_FIC.231A  ...  DeSOx_2nd  MLUT4_AIC.232B  \
Time                                 ...
2025-05-25 05:20:05        0.859975  ...   0.889295       85.012138
2025-05-25 05:30:05        0.856716  ...   0.889888       88.954571
2025-05-25 05:35:05        0.860662  ...   0.890037       93.745851
2025-05-25 05:40:05        0.859286  ...   0.890560       85.305571
2025-05-25 05:45:05        0.859582  ...   0.890529      101.874866

                     MLUT4_AT.240  prev_target  MLUT4_AT-240  prediction  \
Time
2025-05-25 05:20:05     14.151761     0.888806      9.411285    0.888631
2025-05-25 05:30:05      9.316637     0.890104      9.794943    0.886732
2025-05-25 05:35:05      6.155893     0.890862     10.308552    0.888980
2025-05-25 05:40:05     12.572007     0.891577      9.335810    0.890810
2025-05-25 05:45:05      5.497275     0.891864     11.152374    0.887760

                     abs_error  threshold  y3_prediction  y3_abs_error
Time
2025-05-25 05:20:05   0.000664   0.000664       9.467753      0.056468
2025-05-25 05:30:05   0.003156   0.002907      10.075676      0.280733
2025-05-25 05:35:05   0.001057   0.001057      10.407634      0.099081
2025-05-25 05:40:05   0.000250   0.000976       9.314494      0.021317
2025-05-25 05:45:05   0.002769   0.002427      11.434473      0.282099

[5 rows x 50 columns]

  0%|          | 0/7491 [00:00<?, ?it/s]

  0%|          | 0/7491 [00:00<?, ?it/s]

  0%|          | 1/7491 [00:00<1:09:12,  1.80it/s]

  0%|          | 1/7491 [00:00<1:09:12,  1.80it/s]
  0%|          | 2/7491 [00:00<1:09:11,  1.80it/s]

  0%|          | 3/7491 [00:01<42:39,  2.93it/s]

  0%|          | 3/7491 [00:01<42:39,  2.93it/s]
  0%|          | 4/7491 [00:01<42:38,  2.93it/s]
  0%|          | 5/7491 [00:01<42:38,  2.93it/s]

  0%|          | 6/7491 [00:01<30:19,  4.11it/s]

  0%|          | 6/7491 [00:01<30:19,  4.11it/s]
  0%|          | 7/7491 [00:01<30:19,  4.11it/s]
  0%|          | 8/7491 [00:01<30:18,  4.11it/s]
  0%|          | 9/7491 [00:01<30:18,  4.11it/s]
  0%|          | 10/7491 [00:01<30:18,  4.11it/s]

  0%|          | 11/7491 [00:02<19:50,  6.28it/s]

  0%|          | 11/7491 [00:02<19:50,  6.28it/s]
  0%|          | 12/7491 [00:02<19:50,  6.28it/s]

  0%|          | 13/7491 [00:02<23:02,  5.41it/s]

  0%|          | 13/7491 [00:02<23:02,  5.41it/s]
  0%|          | 14/7491 [00:02<23:02,  5.41it/s]
  0%|          | 15/7491 [00:02<23:02,  5.41it/s]
  0%|          | 16/7491 [00:02<23:02,  5.41it/s]
  0%|          | 17/7491 [00:02<23:02,  5.41it/s]
  0%|          | 18/7491 [00:02<23:01,  5.41it/s]
  0%|          | 19/7491 [00:02<23:01,  5.41it/s]
  0%|          | 20/7491 [00:02<23:01,  5.41it/s]
  0%|          | 21/7491 [00:02<23:01,  5.41it/s]

  0%|          | 22/7491 [00:03<13:04,  9.52it/s]

  0%|          | 22/7491 [00:03<13:04,  9.52it/s]
  0%|          | 23/7491 [00:03<13:04,  9.52it/s]

  0%|          | 24/7491 [00:05<31:32,  3.95it/s]

  0%|          | 24/7491 [00:05<31:32,  3.95it/s]
  0%|          | 25/7491 [00:05<31:32,  3.95it/s]

  0%|          | 26/7491 [00:06<41:05,  3.03it/s]

  0%|          | 26/7491 [00:06<41:05,  3.03it/s]
  0%|          | 27/7491 [00:06<41:05,  3.03it/s]

  0%|          | 28/7491 [00:07<39:08,  3.18it/s]

  0%|          | 28/7491 [00:07<39:08,  3.18it/s]
  0%|          | 29/7491 [00:07<39:08,  3.18it/s]

  0%|          | 30/7491 [00:07<37:15,  3.34it/s]

  0%|          | 30/7491 [00:07<37:15,  3.34it/s]
  0%|          | 31/7491 [00:07<37:15,  3.34it/s]
  0%|          | 32/7491 [00:07<37:15,  3.34it/s]
  0%|          | 33/7491 [00:07<37:15,  3.34it/s]

  0%|          | 34/7491 [00:08<28:47,  4.32it/s]

  0%|          | 34/7491 [00:08<28:47,  4.32it/s]
  0%|          | 35/7491 [00:08<28:46,  4.32it/s]

  0%|          | 36/7491 [00:08<29:14,  4.25it/s]

  0%|          | 36/7491 [00:08<29:14,  4.25it/s]
  0%|          | 37/7491 [00:08<29:13,  4.25it/s]
  1%|          | 38/7491 [00:08<29:13,  4.25it/s]
  1%|          | 39/7491 [00:08<29:13,  4.25it/s]
  1%|          | 40/7491 [00:08<29:13,  4.25it/s]
  1%|          | 41/7491 [00:08<29:12,  4.25it/s]
  1%|          | 42/7491 [00:08<29:12,  4.25it/s]
  1%|          | 43/7491 [00:08<29:12,  4.25it/s]
  1%|          | 44/7491 [00:08<29:12,  4.25it/s]
  1%|          | 45/7491 [00:08<29:11,  4.25it/s]
  1%|          | 46/7491 [00:08<29:11,  4.25it/s]
  1%|          | 47/7491 [00:08<29:11,  4.25it/s]
  1%|          | 48/7491 [00:08<29:11,  4.25it/s]
  1%|          | 49/7491 [00:08<29:11,  4.25it/s]
  1%|          | 50/7491 [00:08<29:10,  4.25it/s]
  1%|          | 51/7491 [00:08<29:10,  4.25it/s]
  1%|          | 52/7491 [00:08<29:10,  4.25it/s]

  1%|          | 53/7491 [00:09<10:58, 11.29it/s]

  1%|          | 53/7491 [00:09<10:58, 11.29it/s]
  1%|          | 54/7491 [00:09<10:58, 11.29it/s]
  1%|          | 55/7491 [00:09<10:58, 11.29it/s]
  1%|          | 56/7491 [00:09<10:58, 11.29it/s]

  1%|          | 57/7491 [00:09<11:51, 10.45it/s]

  1%|          | 57/7491 [00:09<11:51, 10.45it/s]
  1%|          | 58/7491 [00:09<11:51, 10.45it/s]

  1%|          | 59/7491 [00:10<14:41,  8.43it/s]

  1%|          | 59/7491 [00:10<14:41,  8.43it/s]
  1%|          | 60/7491 [00:10<14:41,  8.43it/s]

  1%|          | 61/7491 [00:10<16:53,  7.33it/s]

  1%|          | 61/7491 [00:10<16:53,  7.33it/s]
  1%|          | 62/7491 [00:10<16:53,  7.33it/s]
  1%|          | 63/7491 [00:10<16:53,  7.33it/s]

  1%|          | 64/7491 [00:11<17:58,  6.89it/s]

  1%|          | 64/7491 [00:11<17:58,  6.89it/s]
  1%|          | 65/7491 [00:11<17:58,  6.89it/s]

  1%|          | 66/7491 [00:11<20:14,  6.11it/s]

  1%|          | 66/7491 [00:11<20:14,  6.11it/s]
  1%|          | 67/7491 [00:11<20:14,  6.11it/s]

  1%|          | 68/7491 [00:12<22:50,  5.42it/s]

  1%|          | 68/7491 [00:12<22:50,  5.42it/s]
  1%|          | 69/7491 [00:12<22:49,  5.42it/s]
  1%|          | 70/7491 [00:12<22:49,  5.42it/s]

  1%|          | 71/7491 [00:12<22:05,  5.60it/s]

  1%|          | 71/7491 [00:12<22:05,  5.60it/s]
  1%|          | 72/7491 [00:12<22:05,  5.60it/s]
  1%|          | 73/7491 [00:12<22:05,  5.60it/s]

  1%|          | 74/7491 [00:13<22:05,  5.60it/s]

  1%|          | 74/7491 [00:13<22:05,  5.60it/s]
  1%|          | 75/7491 [00:13<22:05,  5.60it/s]
  1%|          | 76/7491 [00:13<22:05,  5.60it/s]

  1%|          | 77/7491 [00:13<21:24,  5.77it/s]

  1%|          | 77/7491 [00:13<21:24,  5.77it/s]
  1%|          | 78/7491 [00:13<21:24,  5.77it/s]

  1%|          | 79/7491 [00:14<24:09,  5.11it/s]

  1%|          | 79/7491 [00:14<24:09,  5.11it/s]
  1%|          | 80/7491 [00:14<24:08,  5.11it/s]

  1%|          | 81/7491 [00:14<25:45,  4.80it/s]

  1%|          | 81/7491 [00:14<25:45,  4.80it/s]
  1%|          | 82/7491 [00:14<25:45,  4.80it/s]

  1%|          | 83/7491 [00:15<27:41,  4.46it/s]

  1%|          | 83/7491 [00:15<27:41,  4.46it/s]
  1%|          | 84/7491 [00:15<27:41,  4.46it/s]

  1%|          | 85/7491 [00:15<29:11,  4.23it/s]

  1%|          | 85/7491 [00:15<29:11,  4.23it/s]
  1%|          | 86/7491 [00:15<29:11,  4.23it/s]

  1%|          | 87/7491 [00:16<33:51,  3.64it/s]

  1%|          | 87/7491 [00:16<33:51,  3.64it/s]
  1%|          | 88/7491 [00:16<33:51,  3.64it/s]

  1%|          | 89/7491 [00:19<1:10:28,  1.75it/s]

  1%|          | 89/7491 [00:19<1:10:28,  1.75it/s]
  1%|          | 90/7491 [00:19<1:10:28,  1.75it/s]

  1%|          | 91/7491 [00:19<1:00:43,  2.03it/s]

  1%|          | 91/7491 [00:19<1:00:43,  2.03it/s]
  1%|          | 92/7491 [00:19<1:00:43,  2.03it/s]

  1%|          | 93/7491 [00:20<53:08,  2.32it/s]

  1%|          | 93/7491 [00:20<53:08,  2.32it/s]
  1%|▏         | 94/7491 [00:20<53:07,  2.32it/s]

  1%|▏         | 95/7491 [00:20<48:41,  2.53it/s]

  1%|▏         | 95/7491 [00:20<48:41,  2.53it/s]
  1%|▏         | 96/7491 [00:20<48:41,  2.53it/s]

  1%|▏         | 97/7491 [00:21<45:24,  2.71it/s]

  1%|▏         | 97/7491 [00:21<45:24,  2.71it/s]
  1%|▏         | 98/7491 [00:21<45:24,  2.71it/s]

  1%|▏         | 99/7491 [00:22<42:16,  2.91it/s]

  1%|▏         | 99/7491 [00:22<42:16,  2.91it/s]
  1%|▏         | 100/7491 [00:22<42:15,  2.91it/s]

  1%|▏         | 101/7491 [00:22<40:30,  3.04it/s]

  1%|▏         | 101/7491 [00:22<40:30,  3.04it/s]
  1%|▏         | 102/7491 [00:22<40:30,  3.04it/s]

  1%|▏         | 103/7491 [00:23<38:31,  3.20it/s]

  1%|▏         | 103/7491 [00:23<38:31,  3.20it/s]
  1%|▏         | 104/7491 [00:23<38:31,  3.20it/s]
  1%|▏         | 105/7491 [00:23<38:31,  3.20it/s]
  1%|▏         | 106/7491 [00:23<38:30,  3.20it/s]
  1%|▏         | 107/7491 [00:23<38:30,  3.20it/s]
  1%|▏         | 108/7491 [00:23<38:30,  3.20it/s]
  1%|▏         | 109/7491 [00:23<38:29,  3.20it/s]
  1%|▏         | 110/7491 [00:23<38:29,  3.20it/s]
  1%|▏         | 111/7491 [00:23<38:29,  3.20it/s]

  1%|▏         | 112/7491 [00:23<18:31,  6.64it/s]

  1%|▏         | 112/7491 [00:23<18:31,  6.64it/s]
  2%|▏         | 113/7491 [00:23<18:31,  6.64it/s]

  2%|▏         | 114/7491 [00:24<21:21,  5.76it/s]

  2%|▏         | 114/7491 [00:24<21:21,  5.76it/s]
  2%|▏         | 115/7491 [00:24<21:21,  5.76it/s]
  2%|▏         | 116/7491 [00:24<21:20,  5.76it/s]

  2%|▏         | 117/7491 [00:25<21:57,  5.60it/s]

  2%|▏         | 117/7491 [00:25<21:57,  5.60it/s]
  2%|▏         | 118/7491 [00:25<21:57,  5.60it/s]

  2%|▏         | 119/7491 [00:25<24:29,  5.02it/s]

  2%|▏         | 119/7491 [00:25<24:29,  5.02it/s]
  2%|▏         | 120/7491 [00:25<24:28,  5.02it/s]

  2%|▏         | 121/7491 [00:26<27:03,  4.54it/s]

  2%|▏         | 121/7491 [00:26<27:03,  4.54it/s]
  2%|▏         | 122/7491 [00:26<27:03,  4.54it/s]

  2%|▏         | 123/7491 [00:26<28:57,  4.24it/s]

  2%|▏         | 123/7491 [00:26<28:57,  4.24it/s]
  2%|▏         | 124/7491 [00:26<28:56,  4.24it/s]

  2%|▏         | 125/7491 [00:27<30:09,  4.07it/s]

  2%|▏         | 125/7491 [00:27<30:09,  4.07it/s]
  2%|▏         | 126/7491 [00:27<30:08,  4.07it/s]

  2%|▏         | 127/7491 [00:27<31:23,  3.91it/s]

  2%|▏         | 127/7491 [00:27<31:23,  3.91it/s]
  2%|▏         | 128/7491 [00:27<31:23,  3.91it/s]

  2%|▏         | 129/7491 [00:28<32:03,  3.83it/s]

  2%|▏         | 129/7491 [00:28<32:03,  3.83it/s]
  2%|▏         | 130/7491 [00:28<32:02,  3.83it/s]
  2%|▏         | 131/7491 [00:28<32:02,  3.83it/s]
  2%|▏         | 132/7491 [00:28<32:02,  3.83it/s]

  2%|▏         | 133/7491 [00:29<26:24,  4.64it/s]

  2%|▏         | 133/7491 [00:29<26:24,  4.64it/s]
  2%|▏         | 134/7491 [00:29<26:24,  4.64it/s]

  2%|▏         | 135/7491 [00:31<1:00:52,  2.01it/s]

  2%|▏         | 135/7491 [00:31<1:00:52,  2.01it/s]
  2%|▏         | 136/7491 [00:31<1:00:51,  2.01it/s]
  2%|▏         | 137/7491 [00:31<1:00:51,  2.01it/s]

  2%|▏         | 138/7491 [00:32<48:12,  2.54it/s]

  2%|▏         | 138/7491 [00:32<48:12,  2.54it/s]
  2%|▏         | 139/7491 [00:32<48:12,  2.54it/s]
  2%|▏         | 140/7491 [00:32<48:11,  2.54it/s]
  2%|▏         | 141/7491 [00:32<48:11,  2.54it/s]

  2%|▏         | 142/7491 [00:32<35:57,  3.41it/s]

  2%|▏         | 142/7491 [00:32<35:57,  3.41it/s]
  2%|▏         | 143/7491 [00:32<35:57,  3.41it/s]

  2%|▏         | 144/7491 [00:33<36:02,  3.40it/s]

  2%|▏         | 144/7491 [00:33<36:02,  3.40it/s]
  2%|▏         | 145/7491 [00:33<36:01,  3.40it/s]
  2%|▏         | 146/7491 [00:33<36:01,  3.40it/s]
  2%|▏         | 147/7491 [00:33<36:01,  3.40it/s]

  2%|▏         | 148/7491 [00:34<29:08,  4.20it/s]

  2%|▏         | 148/7491 [00:34<29:08,  4.20it/s]
  2%|▏         | 149/7491 [00:34<29:08,  4.20it/s]

  2%|▏         | 150/7491 [00:34<29:50,  4.10it/s]

  2%|▏         | 150/7491 [00:34<29:50,  4.10it/s]
  2%|▏         | 151/7491 [00:34<29:50,  4.10it/s]

  2%|▏         | 152/7491 [00:35<31:19,  3.90it/s]

  2%|▏         | 152/7491 [00:35<31:19,  3.90it/s]
  2%|▏         | 153/7491 [00:35<31:19,  3.90it/s]

  2%|▏         | 154/7491 [00:35<31:37,  3.87it/s]

  2%|▏         | 154/7491 [00:35<31:37,  3.87it/s]
  2%|▏         | 155/7491 [00:35<31:37,  3.87it/s]

  2%|▏         | 156/7491 [00:36<32:21,  3.78it/s]

  2%|▏         | 156/7491 [00:36<32:21,  3.78it/s]
  2%|▏         | 157/7491 [00:36<32:21,  3.78it/s]

  2%|▏         | 158/7491 [00:36<32:24,  3.77it/s]

  2%|▏         | 158/7491 [00:36<32:24,  3.77it/s]
  2%|▏         | 159/7491 [00:36<32:24,  3.77it/s]
  2%|▏         | 160/7491 [00:36<32:23,  3.77it/s]

  2%|▏         | 161/7491 [00:37<29:05,  4.20it/s]

  2%|▏         | 161/7491 [00:37<29:05,  4.20it/s]
  2%|▏         | 162/7491 [00:37<29:05,  4.20it/s]

  2%|▏         | 163/7491 [00:38<30:18,  4.03it/s]

  2%|▏         | 163/7491 [00:38<30:18,  4.03it/s]
  2%|▏         | 164/7491 [00:38<30:18,  4.03it/s]

  2%|▏         | 165/7491 [00:38<31:36,  3.86it/s]

  2%|▏         | 165/7491 [00:38<31:36,  3.86it/s]
  2%|▏         | 166/7491 [00:38<31:35,  3.86it/s]

  2%|▏         | 167/7491 [00:39<32:32,  3.75it/s]

  2%|▏         | 167/7491 [00:39<32:32,  3.75it/s]
  2%|▏         | 168/7491 [00:39<32:31,  3.75it/s]

  2%|▏         | 169/7491 [00:39<33:24,  3.65it/s]

  2%|▏         | 169/7491 [00:39<33:24,  3.65it/s]
  2%|▏         | 170/7491 [00:39<33:24,  3.65it/s]

  2%|▏         | 171/7491 [00:40<35:12,  3.46it/s]

  2%|▏         | 171/7491 [00:40<35:12,  3.46it/s]
  2%|▏         | 172/7491 [00:40<35:12,  3.46it/s]
  2%|▏         | 173/7491 [00:40<35:12,  3.46it/s]

  2%|▏         | 174/7491 [00:40<30:52,  3.95it/s]

  2%|▏         | 174/7491 [00:40<30:52,  3.95it/s]
  2%|▏         | 175/7491 [00:41<30:52,  3.95it/s]

  2%|▏         | 176/7491 [00:41<33:52,  3.60it/s]

  2%|▏         | 176/7491 [00:41<33:52,  3.60it/s]
  2%|▏         | 177/7491 [00:41<33:52,  3.60it/s]

  2%|▏         | 178/7491 [00:44<1:10:18,  1.73it/s]

  2%|▏         | 178/7491 [00:44<1:10:18,  1.73it/s]
  2%|▏         | 179/7491 [00:44<1:10:17,  1.73it/s]

  2%|▏         | 180/7491 [00:45<1:01:10,  1.99it/s]

  2%|▏         | 180/7491 [00:45<1:01:10,  1.99it/s]
  2%|▏         | 181/7491 [00:45<1:01:09,  1.99it/s]

  2%|▏         | 182/7491 [00:45<54:19,  2.24it/s]

  2%|▏         | 182/7491 [00:45<54:19,  2.24it/s]
  2%|▏         | 183/7491 [00:45<54:19,  2.24it/s]
  2%|▏         | 184/7491 [00:45<54:19,  2.24it/s]

  2%|▏         | 185/7491 [00:46<42:30,  2.86it/s]

  2%|▏         | 185/7491 [00:46<42:30,  2.86it/s]
  2%|▏         | 186/7491 [00:46<42:30,  2.86it/s]
  2%|▏         | 187/7491 [00:46<42:29,  2.86it/s]
  3%|▎         | 188/7491 [00:46<42:29,  2.86it/s]
  3%|▎         | 189/7491 [00:46<42:29,  2.86it/s]
  3%|▎         | 190/7491 [00:46<42:28,  2.86it/s]

  3%|▎         | 191/7491 [00:46<26:54,  4.52it/s]

  3%|▎         | 191/7491 [00:46<26:54,  4.52it/s]
  3%|▎         | 192/7491 [00:46<26:53,  4.52it/s]

  3%|▎         | 193/7491 [00:47<28:26,  4.28it/s]

  3%|▎         | 193/7491 [00:47<28:26,  4.28it/s]
  3%|▎         | 194/7491 [00:47<28:26,  4.28it/s]

  3%|▎         | 195/7491 [00:48<30:23,  4.00it/s]

  3%|▎         | 195/7491 [00:48<30:23,  4.00it/s]
  3%|▎         | 196/7491 [00:48<30:23,  4.00it/s]
  3%|▎         | 197/7491 [00:48<30:23,  4.00it/s]

  3%|▎         | 198/7491 [00:48<28:12,  4.31it/s]

  3%|▎         | 198/7491 [00:48<28:12,  4.31it/s]
  3%|▎         | 199/7491 [00:48<28:11,  4.31it/s]

  3%|▎         | 200/7491 [00:49<30:27,  3.99it/s]

  3%|▎         | 200/7491 [00:49<30:27,  3.99it/s]
  3%|▎         | 201/7491 [00:49<30:27,  3.99it/s]

  3%|▎         | 202/7491 [00:49<32:17,  3.76it/s]

  3%|▎         | 202/7491 [00:49<32:17,  3.76it/s]
  3%|▎         | 203/7491 [00:49<32:17,  3.76it/s]

  3%|▎         | 204/7491 [00:50<33:10,  3.66it/s]

  3%|▎         | 204/7491 [00:50<33:10,  3.66it/s]
  3%|▎         | 205/7491 [00:50<33:10,  3.66it/s]
  3%|▎         | 206/7491 [00:50<33:10,  3.66it/s]

  3%|▎         | 207/7491 [00:51<30:23,  3.99it/s]

  3%|▎         | 207/7491 [00:51<30:23,  3.99it/s]
  3%|▎         | 208/7491 [00:51<30:23,  3.99it/s]
  3%|▎         | 209/7491 [00:51<30:22,  3.99it/s]

  3%|▎         | 210/7491 [00:51<27:56,  4.34it/s]

  3%|▎         | 210/7491 [00:51<27:56,  4.34it/s]
  3%|▎         | 211/7491 [00:51<27:56,  4.34it/s]

  3%|▎         | 212/7491 [00:52<30:17,  4.00it/s]

  3%|▎         | 212/7491 [00:52<30:17,  4.00it/s]
  3%|▎         | 213/7491 [00:52<30:17,  4.00it/s]

  3%|▎         | 214/7491 [00:52<31:50,  3.81it/s]

  3%|▎         | 214/7491 [00:52<31:50,  3.81it/s]
  3%|▎         | 215/7491 [00:52<31:49,  3.81it/s]

  3%|▎         | 216/7491 [00:53<33:09,  3.66it/s]

  3%|▎         | 216/7491 [00:53<33:09,  3.66it/s]
  3%|▎         | 217/7491 [00:53<33:08,  3.66it/s]

  3%|▎         | 218/7491 [00:54<34:11,  3.55it/s]

  3%|▎         | 218/7491 [00:54<34:11,  3.55it/s]
  3%|▎         | 219/7491 [00:54<34:10,  3.55it/s]

  3%|▎         | 220/7491 [00:56<1:13:31,  1.65it/s]

  3%|▎         | 220/7491 [00:56<1:13:31,  1.65it/s]
  3%|▎         | 221/7491 [00:56<1:13:30,  1.65it/s]

  3%|▎         | 222/7491 [00:57<1:02:41,  1.93it/s]

  3%|▎         | 222/7491 [00:57<1:02:41,  1.93it/s]
  3%|▎         | 223/7491 [00:57<1:02:41,  1.93it/s]

  3%|▎         | 224/7491 [00:58<54:41,  2.21it/s]

  3%|▎         | 224/7491 [00:58<54:41,  2.21it/s]
  3%|▎         | 225/7491 [00:58<54:41,  2.21it/s]

  3%|▎         | 226/7491 [00:58<49:49,  2.43it/s]

  3%|▎         | 226/7491 [00:58<49:49,  2.43it/s]
  3%|▎         | 227/7491 [00:58<49:49,  2.43it/s]

  3%|▎         | 228/7491 [00:59<46:21,  2.61it/s]

  3%|▎         | 228/7491 [00:59<46:21,  2.61it/s]
  3%|▎         | 229/7491 [00:59<46:20,  2.61it/s]

  3%|▎         | 230/7491 [00:59<43:35,  2.78it/s]

  3%|▎         | 230/7491 [00:59<43:35,  2.78it/s]
  3%|▎         | 231/7491 [00:59<43:35,  2.78it/s]

  3%|▎         | 232/7491 [01:00<41:56,  2.88it/s]

  3%|▎         | 232/7491 [01:00<41:56,  2.88it/s]
  3%|▎         | 233/7491 [01:00<41:56,  2.88it/s]

  3%|▎         | 234/7491 [01:01<40:26,  2.99it/s]

  3%|▎         | 234/7491 [01:01<40:26,  2.99it/s]
  3%|▎         | 235/7491 [01:01<40:25,  2.99it/s]

  3%|▎         | 236/7491 [01:01<39:47,  3.04it/s]

  3%|▎         | 236/7491 [01:01<39:47,  3.04it/s]
  3%|▎         | 237/7491 [01:01<39:47,  3.04it/s]

  3%|▎         | 238/7491 [01:02<39:19,  3.07it/s]

  3%|▎         | 238/7491 [01:02<39:19,  3.07it/s]
  3%|▎         | 239/7491 [01:02<39:19,  3.07it/s]

  3%|▎         | 240/7491 [01:03<38:46,  3.12it/s]

  3%|▎         | 240/7491 [01:03<38:46,  3.12it/s]
  3%|▎         | 241/7491 [01:03<38:45,  3.12it/s]

  3%|▎         | 242/7491 [01:03<38:44,  3.12it/s]

  3%|▎         | 242/7491 [01:03<38:44,  3.12it/s]
  3%|▎         | 243/7491 [01:03<38:43,  3.12it/s]

  3%|▎         | 244/7491 [01:04<38:14,  3.16it/s]

  3%|▎         | 244/7491 [01:04<38:14,  3.16it/s]
  3%|▎         | 245/7491 [01:04<38:14,  3.16it/s]

  3%|▎         | 246/7491 [01:05<38:53,  3.10it/s]

  3%|▎         | 246/7491 [01:05<38:53,  3.10it/s]
  3%|▎         | 247/7491 [01:05<38:53,  3.10it/s]

  3%|▎         | 248/7491 [01:05<39:22,  3.07it/s]

  3%|▎         | 248/7491 [01:05<39:22,  3.07it/s]
  3%|▎         | 249/7491 [01:05<39:21,  3.07it/s]

  3%|▎         | 250/7491 [01:06<38:35,  3.13it/s]

  3%|▎         | 250/7491 [01:06<38:35,  3.13it/s]
  3%|▎         | 251/7491 [01:06<38:35,  3.13it/s]
  3%|▎         | 252/7491 [01:06<38:35,  3.13it/s]
  3%|▎         | 253/7491 [01:06<38:35,  3.13it/s]
  3%|▎         | 254/7491 [01:06<38:34,  3.13it/s]

  3%|▎         | 255/7491 [01:08<47:48,  2.52it/s]

  3%|▎         | 255/7491 [01:08<47:48,  2.52it/s]
  3%|▎         | 256/7491 [01:08<47:47,  2.52it/s]

  3%|▎         | 257/7491 [01:09<54:40,  2.20it/s]

  3%|▎         | 257/7491 [01:09<54:40,  2.20it/s]
  3%|▎         | 258/7491 [01:09<54:40,  2.20it/s]

  3%|▎         | 259/7491 [01:10<50:17,  2.40it/s]

  3%|▎         | 259/7491 [01:10<50:17,  2.40it/s]
  3%|▎         | 260/7491 [01:10<50:16,  2.40it/s]

  3%|▎         | 261/7491 [01:11<46:47,  2.57it/s]

  3%|▎         | 261/7491 [01:11<46:47,  2.57it/s]
  3%|▎         | 262/7491 [01:11<46:47,  2.57it/s]

  4%|▎         | 263/7491 [01:11<43:44,  2.75it/s]

  4%|▎         | 263/7491 [01:11<43:44,  2.75it/s]
  4%|▎         | 264/7491 [01:11<43:44,  2.75it/s]

  4%|▎         | 265/7491 [01:12<42:08,  2.86it/s]

  4%|▎         | 265/7491 [01:12<42:08,  2.86it/s]
  4%|▎         | 266/7491 [01:12<42:08,  2.86it/s]
  4%|▎         | 267/7491 [01:12<42:08,  2.86it/s]

  4%|▎         | 268/7491 [01:13<39:19,  3.06it/s]

  4%|▎         | 268/7491 [01:13<39:19,  3.06it/s]
  4%|▎         | 269/7491 [01:13<39:19,  3.06it/s]

  4%|▎         | 270/7491 [01:13<38:12,  3.15it/s]

  4%|▎         | 270/7491 [01:13<38:12,  3.15it/s]
  4%|▎         | 271/7491 [01:13<38:12,  3.15it/s]

  4%|▎         | 272/7491 [01:14<38:22,  3.14it/s]

  4%|▎         | 272/7491 [01:14<38:22,  3.14it/s]
  4%|▎         | 273/7491 [01:14<38:21,  3.14it/s]

  4%|▎         | 274/7491 [01:15<38:13,  3.15it/s]

  4%|▎         | 274/7491 [01:15<38:13,  3.15it/s]
  4%|▎         | 275/7491 [01:15<38:13,  3.15it/s]

  4%|▎         | 276/7491 [01:15<37:27,  3.21it/s]

  4%|▎         | 276/7491 [01:15<37:27,  3.21it/s]
  4%|▎         | 277/7491 [01:15<37:27,  3.21it/s]

  4%|▎         | 278/7491 [01:16<37:30,  3.20it/s]

  4%|▎         | 278/7491 [01:16<37:30,  3.20it/s]
  4%|▎         | 279/7491 [01:16<37:30,  3.20it/s]

  4%|▎         | 280/7491 [01:16<36:26,  3.30it/s]

  4%|▎         | 280/7491 [01:16<36:26,  3.30it/s]
  4%|▍         | 281/7491 [01:16<36:26,  3.30it/s]

  4%|▍         | 282/7491 [01:17<36:25,  3.30it/s]

  4%|▍         | 282/7491 [01:17<36:25,  3.30it/s]
  4%|▍         | 283/7491 [01:17<36:25,  3.30it/s]

  4%|▍         | 284/7491 [01:18<37:11,  3.23it/s]

  4%|▍         | 284/7491 [01:18<37:11,  3.23it/s]
  4%|▍         | 285/7491 [01:18<37:11,  3.23it/s]

  4%|▍         | 286/7491 [01:18<36:54,  3.25it/s]

  4%|▍         | 286/7491 [01:18<36:54,  3.25it/s]
  4%|▍         | 287/7491 [01:18<36:54,  3.25it/s]
  4%|▍         | 288/7491 [01:18<36:54,  3.25it/s]

  4%|▍         | 289/7491 [01:19<32:22,  3.71it/s]

  4%|▍         | 289/7491 [01:19<32:22,  3.71it/s]
  4%|▍         | 290/7491 [01:19<32:22,  3.71it/s]

  4%|▍         | 291/7491 [01:22<1:12:09,  1.66it/s]

  4%|▍         | 291/7491 [01:22<1:12:09,  1.66it/s]
  4%|▍         | 292/7491 [01:22<1:12:08,  1.66it/s]
  4%|▍         | 293/7491 [01:22<1:12:07,  1.66it/s]
  4%|▍         | 294/7491 [01:22<1:12:07,  1.66it/s]
  4%|▍         | 295/7491 [01:22<1:12:06,  1.66it/s]
  4%|▍         | 296/7491 [01:22<1:12:06,  1.66it/s]

  4%|▍         | 297/7491 [01:22<39:50,  3.01it/s]

  4%|▍         | 297/7491 [01:22<39:50,  3.01it/s]
  4%|▍         | 298/7491 [01:23<39:50,  3.01it/s]

  4%|▍         | 299/7491 [01:23<39:14,  3.05it/s]

  4%|▍         | 299/7491 [01:23<39:14,  3.05it/s]
  4%|▍         | 300/7491 [01:23<39:14,  3.05it/s]

  4%|▍         | 301/7491 [01:24<38:32,  3.11it/s]

  4%|▍         | 301/7491 [01:24<38:32,  3.11it/s]
  4%|▍         | 302/7491 [01:24<38:32,  3.11it/s]
  4%|▍         | 303/7491 [01:24<38:31,  3.11it/s]

  4%|▍         | 304/7491 [01:24<34:05,  3.51it/s]

  4%|▍         | 304/7491 [01:24<34:05,  3.51it/s]
  4%|▍         | 305/7491 [01:24<34:05,  3.51it/s]

  4%|▍         | 306/7491 [01:25<35:01,  3.42it/s]

  4%|▍         | 306/7491 [01:25<35:01,  3.42it/s]
  4%|▍         | 307/7491 [01:25<35:01,  3.42it/s]

  4%|▍         | 308/7491 [01:26<35:13,  3.40it/s]

  4%|▍         | 308/7491 [01:26<35:13,  3.40it/s]
  4%|▍         | 309/7491 [01:26<35:13,  3.40it/s]

  4%|▍         | 310/7491 [01:26<35:30,  3.37it/s]

  4%|▍         | 310/7491 [01:26<35:30,  3.37it/s]
  4%|▍         | 311/7491 [01:26<35:30,  3.37it/s]

  4%|▍         | 312/7491 [01:27<35:15,  3.39it/s]

  4%|▍         | 312/7491 [01:27<35:15,  3.39it/s]
  4%|▍         | 313/7491 [01:27<35:14,  3.39it/s]

  4%|▍         | 314/7491 [01:27<35:21,  3.38it/s]

  4%|▍         | 314/7491 [01:27<35:21,  3.38it/s]
  4%|▍         | 315/7491 [01:27<35:21,  3.38it/s]
  4%|▍         | 316/7491 [01:27<35:20,  3.38it/s]

  4%|▍         | 317/7491 [01:28<30:24,  3.93it/s]

  4%|▍         | 317/7491 [01:28<30:24,  3.93it/s]
  4%|▍         | 318/7491 [01:28<30:23,  3.93it/s]

  4%|▍         | 319/7491 [01:28<31:31,  3.79it/s]

  4%|▍         | 319/7491 [01:28<31:31,  3.79it/s]
  4%|▍         | 320/7491 [01:28<31:31,  3.79it/s]

  4%|▍         | 321/7491 [01:29<32:01,  3.73it/s]

  4%|▍         | 321/7491 [01:29<32:01,  3.73it/s]
  4%|▍         | 322/7491 [01:29<32:01,  3.73it/s]

  4%|▍         | 323/7491 [01:30<32:42,  3.65it/s]

  4%|▍         | 323/7491 [01:30<32:42,  3.65it/s]
  4%|▍         | 324/7491 [01:30<32:41,  3.65it/s]

  4%|▍         | 325/7491 [01:30<32:41,  3.65it/s]

  4%|▍         | 325/7491 [01:30<32:41,  3.65it/s]
  4%|▍         | 326/7491 [01:30<32:40,  3.65it/s]

  4%|▍         | 327/7491 [01:31<32:31,  3.67it/s]

  4%|▍         | 327/7491 [01:31<32:31,  3.67it/s]
  4%|▍         | 328/7491 [01:31<32:31,  3.67it/s]
  4%|▍         | 329/7491 [01:31<32:31,  3.67it/s]
  4%|▍         | 330/7491 [01:31<32:31,  3.67it/s]
  4%|▍         | 331/7491 [01:31<32:30,  3.67it/s]

  4%|▍         | 332/7491 [01:31<22:52,  5.22it/s]

  4%|▍         | 332/7491 [01:31<22:52,  5.22it/s]
  4%|▍         | 333/7491 [01:31<22:52,  5.22it/s]

  4%|▍         | 334/7491 [01:32<26:56,  4.43it/s]

  4%|▍         | 334/7491 [01:32<26:56,  4.43it/s]
  4%|▍         | 335/7491 [01:32<26:56,  4.43it/s]

  4%|▍         | 336/7491 [01:35<1:00:01,  1.99it/s]

  4%|▍         | 336/7491 [01:35<1:00:01,  1.99it/s]
  4%|▍         | 337/7491 [01:35<1:00:00,  1.99it/s]
  5%|▍         | 338/7491 [01:35<1:00:00,  1.99it/s]
  5%|▍         | 339/7491 [01:35<59:59,  1.99it/s]

  5%|▍         | 340/7491 [01:35<42:10,  2.83it/s]

  5%|▍         | 340/7491 [01:35<42:10,  2.83it/s]
  5%|▍         | 341/7491 [01:35<42:10,  2.83it/s]

  5%|▍         | 342/7491 [01:36<40:26,  2.95it/s]

  5%|▍         | 342/7491 [01:36<40:26,  2.95it/s]
  5%|▍         | 343/7491 [01:36<40:25,  2.95it/s]

  5%|▍         | 344/7491 [01:36<38:15,  3.11it/s]

  5%|▍         | 344/7491 [01:36<38:15,  3.11it/s]
  5%|▍         | 345/7491 [01:36<38:15,  3.11it/s]

  5%|▍         | 346/7491 [01:37<37:22,  3.19it/s]

  5%|▍         | 346/7491 [01:37<37:22,  3.19it/s]
  5%|▍         | 347/7491 [01:37<37:22,  3.19it/s]

  5%|▍         | 348/7491 [01:37<36:17,  3.28it/s]

  5%|▍         | 348/7491 [01:37<36:17,  3.28it/s]
  5%|▍         | 349/7491 [01:38<36:17,  3.28it/s]

  5%|▍         | 350/7491 [01:38<35:28,  3.35it/s]

  5%|▍         | 350/7491 [01:38<35:28,  3.35it/s]
  5%|▍         | 351/7491 [01:38<35:28,  3.35it/s]

  5%|▍         | 352/7491 [01:39<35:49,  3.32it/s]

  5%|▍         | 352/7491 [01:39<35:49,  3.32it/s]
  5%|▍         | 353/7491 [01:39<35:48,  3.32it/s]

  5%|▍         | 354/7491 [01:39<35:29,  3.35it/s]

  5%|▍         | 354/7491 [01:39<35:29,  3.35it/s]
  5%|▍         | 355/7491 [01:39<35:28,  3.35it/s]

  5%|▍         | 356/7491 [01:40<35:55,  3.31it/s]

  5%|▍         | 356/7491 [01:40<35:55,  3.31it/s]
  5%|▍         | 357/7491 [01:40<35:55,  3.31it/s]

  5%|▍         | 358/7491 [01:41<36:22,  3.27it/s]

  5%|▍         | 358/7491 [01:41<36:22,  3.27it/s]
  5%|▍         | 359/7491 [01:41<36:22,  3.27it/s]
  5%|▍         | 360/7491 [01:41<36:22,  3.27it/s]
  5%|▍         | 361/7491 [01:41<36:21,  3.27it/s]

  5%|▍         | 362/7491 [01:41<28:25,  4.18it/s]

  5%|▍         | 362/7491 [01:41<28:25,  4.18it/s]
  5%|▍         | 363/7491 [01:41<28:25,  4.18it/s]

  5%|▍         | 364/7491 [01:42<30:56,  3.84it/s]

  5%|▍         | 364/7491 [01:42<30:56,  3.84it/s]
  5%|▍         | 365/7491 [01:42<30:55,  3.84it/s]

  5%|▍         | 366/7491 [01:42<32:18,  3.67it/s]

  5%|▍         | 366/7491 [01:42<32:18,  3.67it/s]
  5%|▍         | 367/7491 [01:42<32:18,  3.67it/s]
  5%|▍         | 368/7491 [01:42<32:18,  3.67it/s]

  5%|▍         | 369/7491 [01:43<29:14,  4.06it/s]

  5%|▍         | 369/7491 [01:43<29:14,  4.06it/s]
  5%|▍         | 370/7491 [01:43<29:13,  4.06it/s]

  5%|▍         | 371/7491 [01:44<30:21,  3.91it/s]

  5%|▍         | 371/7491 [01:44<30:21,  3.91it/s]
  5%|▍         | 372/7491 [01:44<30:21,  3.91it/s]

  5%|▍         | 373/7491 [01:44<31:39,  3.75it/s]

  5%|▍         | 373/7491 [01:44<31:39,  3.75it/s]
  5%|▍         | 374/7491 [01:44<31:39,  3.75it/s]

  5%|▌         | 375/7491 [01:47<1:10:10,  1.69it/s]

  5%|▌         | 375/7491 [01:47<1:10:10,  1.69it/s]
  5%|▌         | 376/7491 [01:47<1:10:09,  1.69it/s]

  5%|▌         | 377/7491 [01:48<1:00:16,  1.97it/s]

  5%|▌         | 377/7491 [01:48<1:00:16,  1.97it/s]
  5%|▌         | 378/7491 [01:48<1:00:15,  1.97it/s]

  5%|▌         | 379/7491 [01:48<53:05,  2.23it/s]

  5%|▌         | 379/7491 [01:48<53:05,  2.23it/s]
  5%|▌         | 380/7491 [01:48<53:05,  2.23it/s]
  5%|▌         | 381/7491 [01:48<53:04,  2.23it/s]

  5%|▌         | 382/7491 [01:49<41:15,  2.87it/s]

  5%|▌         | 382/7491 [01:49<41:15,  2.87it/s]
  5%|▌         | 383/7491 [01:49<41:15,  2.87it/s]

  5%|▌         | 384/7491 [01:49<39:17,  3.02it/s]

  5%|▌         | 384/7491 [01:49<39:17,  3.02it/s]
  5%|▌         | 385/7491 [01:49<39:16,  3.02it/s]

  5%|▌         | 386/7491 [01:50<37:32,  3.15it/s]

  5%|▌         | 386/7491 [01:50<37:32,  3.15it/s]
  5%|▌         | 387/7491 [01:50<37:31,  3.15it/s]
  5%|▌         | 388/7491 [01:50<37:31,  3.15it/s]
  5%|▌         | 389/7491 [01:50<37:31,  3.15it/s]
  5%|▌         | 390/7491 [01:50<37:30,  3.15it/s]
  5%|▌         | 391/7491 [01:50<37:30,  3.15it/s]
  5%|▌         | 392/7491 [01:50<37:30,  3.15it/s]
  5%|▌         | 393/7491 [01:50<37:29,  3.15it/s]

  5%|▌         | 394/7491 [01:51<20:10,  5.86it/s]

  5%|▌         | 394/7491 [01:51<20:10,  5.86it/s]
  5%|▌         | 395/7491 [01:51<20:10,  5.86it/s]

  5%|▌         | 396/7491 [01:51<22:21,  5.29it/s]

  5%|▌         | 396/7491 [01:51<22:21,  5.29it/s]
  5%|▌         | 397/7491 [01:51<22:20,  5.29it/s]

  5%|▌         | 398/7491 [01:52<24:46,  4.77it/s]

  5%|▌         | 398/7491 [01:52<24:46,  4.77it/s]
  5%|▌         | 399/7491 [01:52<24:46,  4.77it/s]

  5%|▌         | 400/7491 [01:52<27:03,  4.37it/s]

  5%|▌         | 400/7491 [01:52<27:03,  4.37it/s]
  5%|▌         | 401/7491 [01:52<27:03,  4.37it/s]

  5%|▌         | 402/7491 [01:53<28:23,  4.16it/s]

  5%|▌         | 402/7491 [01:53<28:23,  4.16it/s]
  5%|▌         | 403/7491 [01:53<28:23,  4.16it/s]

  5%|▌         | 404/7491 [01:53<29:52,  3.95it/s]

  5%|▌         | 404/7491 [01:53<29:52,  3.95it/s]
  5%|▌         | 405/7491 [01:53<29:52,  3.95it/s]

  5%|▌         | 406/7491 [01:54<30:42,  3.85it/s]

  5%|▌         | 406/7491 [01:54<30:42,  3.85it/s]
  5%|▌         | 407/7491 [01:54<30:42,  3.85it/s]
  5%|▌         | 408/7491 [01:54<30:41,  3.85it/s]
  5%|▌         | 409/7491 [01:54<30:41,  3.85it/s]
  5%|▌         | 410/7491 [01:54<30:41,  3.85it/s]
  5%|▌         | 411/7491 [01:54<30:40,  3.85it/s]
  5%|▌         | 412/7491 [01:54<30:40,  3.85it/s]
  6%|▌         | 413/7491 [01:54<30:40,  3.85it/s]
  6%|▌         | 414/7491 [01:54<30:40,  3.85it/s]

  6%|▌         | 415/7491 [01:55<16:03,  7.34it/s]

  6%|▌         | 415/7491 [01:55<16:03,  7.34it/s]
  6%|▌         | 416/7491 [01:55<16:03,  7.34it/s]

  6%|▌         | 417/7491 [01:55<18:47,  6.28it/s]

  6%|▌         | 417/7491 [01:55<18:47,  6.28it/s]
  6%|▌         | 418/7491 [01:55<18:47,  6.28it/s]

  6%|▌         | 419/7491 [01:56<21:49,  5.40it/s]

  6%|▌         | 419/7491 [01:56<21:49,  5.40it/s]
  6%|▌         | 420/7491 [01:56<21:49,  5.40it/s]
  6%|▌         | 421/7491 [01:56<21:48,  5.40it/s]
  6%|▌         | 422/7491 [01:56<21:48,  5.40it/s]
  6%|▌         | 423/7491 [01:56<21:48,  5.40it/s]
  6%|▌         | 424/7491 [01:56<21:48,  5.40it/s]
  6%|▌         | 425/7491 [01:56<21:48,  5.40it/s]
  6%|▌         | 426/7491 [01:56<21:47,  5.40it/s]
  6%|▌         | 427/7491 [01:56<21:47,  5.40it/s]
  6%|▌         | 428/7491 [01:56<21:47,  5.40it/s]
  6%|▌         | 429/7491 [01:56<21:47,  5.40it/s]
  6%|▌         | 430/7491 [01:56<21:47,  5.40it/s]
  6%|▌         | 431/7491 [01:56<21:47,  5.40it/s]
  6%|▌         | 432/7491 [01:56<21:46,  5.40it/s]
  6%|▌         | 433/7491 [01:56<21:46,  5.40it/s]
  6%|▌         | 434/7491 [01:56<21:46,  5.40it/s]
  6%|▌         | 435/7491 [01:56<21:46,  5.40it/s]
  6%|▌         | 436/7491 [01:56<21:46,  5.40it/s]
  6%|▌         | 437/7491 [01:56<21:45,  5.40it/s]

  6%|▌         | 438/7491 [01:56<08:38, 13.60it/s]

  6%|▌         | 438/7491 [01:56<08:38, 13.60it/s]
  6%|▌         | 439/7491 [01:56<08:38, 13.60it/s]
  6%|▌         | 440/7491 [01:56<08:38, 13.60it/s]

  6%|▌         | 441/7491 [01:57<10:47, 10.90it/s]

  6%|▌         | 441/7491 [01:57<10:47, 10.90it/s]
  6%|▌         | 442/7491 [01:57<10:46, 10.90it/s]

  6%|▌         | 443/7491 [02:00<29:22,  4.00it/s]

  6%|▌         | 443/7491 [02:00<29:22,  4.00it/s]
  6%|▌         | 444/7491 [02:00<29:22,  4.00it/s]
  6%|▌         | 445/7491 [02:00<29:22,  4.00it/s]

  6%|▌         | 446/7491 [02:00<28:00,  4.19it/s]

  6%|▌         | 446/7491 [02:00<28:00,  4.19it/s]
  6%|▌         | 447/7491 [02:00<27:59,  4.19it/s]
  6%|▌         | 448/7491 [02:00<27:59,  4.19it/s]
  6%|▌         | 449/7491 [02:00<27:59,  4.19it/s]
  6%|▌         | 450/7491 [02:00<27:59,  4.19it/s]
  6%|▌         | 451/7491 [02:00<27:58,  4.19it/s]
  6%|▌         | 452/7491 [02:00<27:58,  4.19it/s]
  6%|▌         | 453/7491 [02:00<27:58,  4.19it/s]
  6%|▌         | 454/7491 [02:00<27:58,  4.19it/s]
  6%|▌         | 455/7491 [02:00<27:57,  4.19it/s]
  6%|▌         | 456/7491 [02:00<27:57,  4.19it/s]
  6%|▌         | 457/7491 [02:00<27:57,  4.19it/s]

  6%|▌         | 458/7491 [02:01<16:10,  7.25it/s]

  6%|▌         | 458/7491 [02:01<16:10,  7.25it/s]
  6%|▌         | 459/7491 [02:01<16:10,  7.25it/s]

  6%|▌         | 460/7491 [02:01<17:59,  6.52it/s]

  6%|▌         | 460/7491 [02:01<17:59,  6.52it/s]
  6%|▌         | 461/7491 [02:02<17:59,  6.52it/s]
  6%|▌         | 462/7491 [02:02<17:58,  6.52it/s]
  6%|▌         | 463/7491 [02:02<17:58,  6.52it/s]

  6%|▌         | 464/7491 [02:02<17:40,  6.63it/s]

  6%|▌         | 464/7491 [02:02<17:40,  6.63it/s]
  6%|▌         | 465/7491 [02:02<17:40,  6.63it/s]

  6%|▌         | 466/7491 [02:03<19:45,  5.93it/s]

  6%|▌         | 466/7491 [02:03<19:45,  5.93it/s]
  6%|▌         | 467/7491 [02:03<19:45,  5.93it/s]
  6%|▌         | 468/7491 [02:03<19:45,  5.93it/s]
  6%|▋         | 469/7491 [02:03<19:45,  5.93it/s]
  6%|▋         | 470/7491 [02:03<19:44,  5.93it/s]
  6%|▋         | 471/7491 [02:03<19:44,  5.93it/s]
  6%|▋         | 472/7491 [02:03<19:44,  5.93it/s]

  6%|▋         | 473/7491 [02:03<15:22,  7.61it/s]

  6%|▋         | 473/7491 [02:03<15:22,  7.61it/s]
  6%|▋         | 474/7491 [02:03<15:22,  7.61it/s]
  6%|▋         | 475/7491 [02:03<15:22,  7.61it/s]

  6%|▋         | 476/7491 [02:04<16:24,  7.12it/s]

  6%|▋         | 476/7491 [02:04<16:24,  7.12it/s]
  6%|▋         | 477/7491 [02:04<16:24,  7.12it/s]

  6%|▋         | 478/7491 [02:04<19:02,  6.14it/s]

  6%|▋         | 478/7491 [02:04<19:02,  6.14it/s]
  6%|▋         | 479/7491 [02:04<19:02,  6.14it/s]

  6%|▋         | 480/7491 [02:05<21:43,  5.38it/s]

  6%|▋         | 480/7491 [02:05<21:43,  5.38it/s]
  6%|▋         | 481/7491 [02:05<21:42,  5.38it/s]

  6%|▋         | 482/7491 [02:05<24:06,  4.85it/s]

  6%|▋         | 482/7491 [02:05<24:06,  4.85it/s]
  6%|▋         | 483/7491 [02:05<24:06,  4.85it/s]

  6%|▋         | 484/7491 [02:06<26:45,  4.36it/s]

  6%|▋         | 484/7491 [02:06<26:45,  4.36it/s]
  6%|▋         | 485/7491 [02:06<26:45,  4.36it/s]

  6%|▋         | 486/7491 [02:07<28:30,  4.10it/s]

  6%|▋         | 486/7491 [02:07<28:30,  4.10it/s]
  7%|▋         | 487/7491 [02:07<28:30,  4.10it/s]

  7%|▋         | 488/7491 [02:07<30:23,  3.84it/s]

  7%|▋         | 488/7491 [02:07<30:23,  3.84it/s]
  7%|▋         | 489/7491 [02:07<30:23,  3.84it/s]
  7%|▋         | 490/7491 [02:07<30:23,  3.84it/s]
  7%|▋         | 491/7491 [02:07<30:23,  3.84it/s]

  7%|▋         | 492/7491 [02:08<24:19,  4.80it/s]

  7%|▋         | 492/7491 [02:08<24:19,  4.80it/s]
  7%|▋         | 493/7491 [02:08<24:18,  4.80it/s]

  7%|▋         | 494/7491 [02:08<26:56,  4.33it/s]

  7%|▋         | 494/7491 [02:08<26:56,  4.33it/s]
  7%|▋         | 495/7491 [02:08<26:56,  4.33it/s]
  7%|▋         | 496/7491 [02:08<26:55,  4.33it/s]
  7%|▋         | 497/7491 [02:08<26:55,  4.33it/s]
  7%|▋         | 498/7491 [02:08<26:55,  4.33it/s]
  7%|▋         | 499/7491 [02:08<26:55,  4.33it/s]
  7%|▋         | 500/7491 [02:08<26:54,  4.33it/s]
  7%|▋         | 501/7491 [02:08<26:54,  4.33it/s]
  7%|▋         | 502/7491 [02:08<26:54,  4.33it/s]
  7%|▋         | 503/7491 [02:08<26:54,  4.33it/s]
  7%|▋         | 504/7491 [02:08<26:53,  4.33it/s]

  7%|▋         | 505/7491 [02:09<13:22,  8.70it/s]

  7%|▋         | 505/7491 [02:09<13:22,  8.70it/s]
  7%|▋         | 506/7491 [02:09<13:22,  8.70it/s]

  7%|▋         | 507/7491 [02:10<16:54,  6.88it/s]

  7%|▋         | 507/7491 [02:10<16:54,  6.88it/s]
  7%|▋         | 508/7491 [02:10<16:54,  6.88it/s]
  7%|▋         | 509/7491 [02:10<16:54,  6.88it/s]

  7%|▋         | 510/7491 [02:12<38:33,  3.02it/s]

  7%|▋         | 510/7491 [02:12<38:33,  3.02it/s]
  7%|▋         | 511/7491 [02:12<38:33,  3.02it/s]

  7%|▋         | 512/7491 [02:13<37:29,  3.10it/s]

  7%|▋         | 512/7491 [02:13<37:29,  3.10it/s]
  7%|▋         | 513/7491 [02:13<37:28,  3.10it/s]
  7%|▋         | 514/7491 [02:13<37:28,  3.10it/s]

  7%|▋         | 515/7491 [02:14<33:10,  3.50it/s]

  7%|▋         | 515/7491 [02:14<33:10,  3.50it/s]
  7%|▋         | 516/7491 [02:14<33:10,  3.50it/s]

  7%|▋         | 517/7491 [02:14<32:30,  3.58it/s]

  7%|▋         | 517/7491 [02:14<32:30,  3.58it/s]
  7%|▋         | 518/7491 [02:14<32:30,  3.58it/s]

  7%|▋         | 519/7491 [02:15<32:31,  3.57it/s]

  7%|▋         | 519/7491 [02:15<32:31,  3.57it/s]
  7%|▋         | 520/7491 [02:15<32:31,  3.57it/s]
  7%|▋         | 521/7491 [02:15<32:30,  3.57it/s]
  7%|▋         | 522/7491 [02:15<32:30,  3.57it/s]

  7%|▋         | 523/7491 [02:15<25:21,  4.58it/s]

  7%|▋         | 523/7491 [02:15<25:21,  4.58it/s]
  7%|▋         | 524/7491 [02:15<25:21,  4.58it/s]

  7%|▋         | 525/7491 [02:16<26:39,  4.35it/s]

  7%|▋         | 525/7491 [02:16<26:39,  4.35it/s]
  7%|▋         | 526/7491 [02:16<26:39,  4.35it/s]

  7%|▋         | 527/7491 [02:16<27:28,  4.22it/s]

  7%|▋         | 527/7491 [02:16<27:28,  4.22it/s]
  7%|▋         | 528/7491 [02:16<27:28,  4.22it/s]

  7%|▋         | 529/7491 [02:17<28:15,  4.11it/s]

  7%|▋         | 529/7491 [02:17<28:15,  4.11it/s]
  7%|▋         | 530/7491 [02:17<28:14,  4.11it/s]

  7%|▋         | 531/7491 [02:17<28:37,  4.05it/s]

  7%|▋         | 531/7491 [02:17<28:37,  4.05it/s]
  7%|▋         | 532/7491 [02:17<28:36,  4.05it/s]

  7%|▋         | 533/7491 [02:18<29:35,  3.92it/s]

  7%|▋         | 533/7491 [02:18<29:35,  3.92it/s]
  7%|▋         | 534/7491 [02:18<29:35,  3.92it/s]

  7%|▋         | 535/7491 [02:18<30:01,  3.86it/s]

  7%|▋         | 535/7491 [02:18<30:01,  3.86it/s]
  7%|▋         | 536/7491 [02:18<30:01,  3.86it/s]

  7%|▋         | 537/7491 [02:19<30:51,  3.76it/s]

  7%|▋         | 537/7491 [02:19<30:51,  3.76it/s]
  7%|▋         | 538/7491 [02:19<30:51,  3.76it/s]

  7%|▋         | 539/7491 [02:19<31:13,  3.71it/s]

  7%|▋         | 539/7491 [02:19<31:13,  3.71it/s]
  7%|▋         | 540/7491 [02:19<31:13,  3.71it/s]

  7%|▋         | 541/7491 [02:20<31:50,  3.64it/s]

  7%|▋         | 541/7491 [02:20<31:50,  3.64it/s]
  7%|▋         | 542/7491 [02:20<31:50,  3.64it/s]

  7%|▋         | 543/7491 [02:21<31:39,  3.66it/s]

  7%|▋         | 543/7491 [02:21<31:39,  3.66it/s]
  7%|▋         | 544/7491 [02:21<31:39,  3.66it/s]

  7%|▋         | 545/7491 [02:21<32:26,  3.57it/s]

  7%|▋         | 545/7491 [02:21<32:26,  3.57it/s]
  7%|▋         | 546/7491 [02:21<32:26,  3.57it/s]

  7%|▋         | 547/7491 [02:22<33:13,  3.48it/s]

  7%|▋         | 547/7491 [02:22<33:13,  3.48it/s]
  7%|▋         | 548/7491 [02:22<33:13,  3.48it/s]

  7%|▋         | 549/7491 [02:24<1:06:17,  1.75it/s]

  7%|▋         | 549/7491 [02:24<1:06:17,  1.75it/s]
  7%|▋         | 550/7491 [02:24<1:06:16,  1.75it/s]

  7%|▋         | 551/7491 [02:25<1:02:21,  1.85it/s]

  7%|▋         | 551/7491 [02:25<1:02:21,  1.85it/s]
  7%|▋         | 552/7491 [02:25<1:02:21,  1.85it/s]
  7%|▋         | 553/7491 [02:25<1:02:20,  1.85it/s]
  7%|▋         | 554/7491 [02:25<1:02:20,  1.85it/s]

  7%|▋         | 555/7491 [02:26<41:10,  2.81it/s]

  7%|▋         | 555/7491 [02:26<41:10,  2.81it/s]
  7%|▋         | 556/7491 [02:26<41:09,  2.81it/s]

  7%|▋         | 557/7491 [02:26<39:10,  2.95it/s]

  7%|▋         | 557/7491 [02:26<39:10,  2.95it/s]
  7%|▋         | 558/7491 [02:26<39:10,  2.95it/s]
  7%|▋         | 559/7491 [02:26<39:10,  2.95it/s]
  7%|▋         | 560/7491 [02:26<39:09,  2.95it/s]

  7%|▋         | 561/7491 [02:27<29:33,  3.91it/s]

  7%|▋         | 561/7491 [02:27<29:33,  3.91it/s]
  8%|▊         | 562/7491 [02:27<29:33,  3.91it/s]
  8%|▊         | 563/7491 [02:27<29:33,  3.91it/s]
  8%|▊         | 564/7491 [02:27<29:33,  3.91it/s]

  8%|▊         | 565/7491 [02:27<24:43,  4.67it/s]

  8%|▊         | 565/7491 [02:27<24:43,  4.67it/s]
  8%|▊         | 566/7491 [02:27<24:43,  4.67it/s]

  8%|▊         | 567/7491 [02:28<26:37,  4.33it/s]

  8%|▊         | 567/7491 [02:28<26:37,  4.33it/s]
  8%|▊         | 568/7491 [02:28<26:37,  4.33it/s]

  8%|▊         | 569/7491 [02:29<27:49,  4.15it/s]

  8%|▊         | 569/7491 [02:29<27:49,  4.15it/s]
  8%|▊         | 570/7491 [02:29<27:49,  4.15it/s]

  8%|▊         | 571/7491 [02:29<29:11,  3.95it/s]

  8%|▊         | 571/7491 [02:29<29:11,  3.95it/s]
  8%|▊         | 572/7491 [02:29<29:11,  3.95it/s]
  8%|▊         | 573/7491 [02:29<29:11,  3.95it/s]

  8%|▊         | 574/7491 [02:30<26:40,  4.32it/s]

  8%|▊         | 574/7491 [02:30<26:40,  4.32it/s]
  8%|▊         | 575/7491 [02:30<26:40,  4.32it/s]
  8%|▊         | 576/7491 [02:30<26:39,  4.32it/s]

  8%|▊         | 577/7491 [02:30<25:23,  4.54it/s]

  8%|▊         | 577/7491 [02:30<25:23,  4.54it/s]
  8%|▊         | 578/7491 [02:30<25:22,  4.54it/s]

  8%|▊         | 579/7491 [02:31<27:07,  4.25it/s]

  8%|▊         | 579/7491 [02:31<27:07,  4.25it/s]
  8%|▊         | 580/7491 [02:31<27:07,  4.25it/s]

  8%|▊         | 581/7491 [02:31<28:57,  3.98it/s]

  8%|▊         | 581/7491 [02:31<28:57,  3.98it/s]
  8%|▊         | 582/7491 [02:31<28:57,  3.98it/s]

  8%|▊         | 583/7491 [02:32<29:37,  3.89it/s]

  8%|▊         | 583/7491 [02:32<29:37,  3.89it/s]
  8%|▊         | 584/7491 [02:32<29:37,  3.89it/s]

  8%|▊         | 585/7491 [02:33<30:44,  3.74it/s]

  8%|▊         | 585/7491 [02:33<30:44,  3.74it/s]
  8%|▊         | 586/7491 [02:33<30:44,  3.74it/s]

  8%|▊         | 587/7491 [02:33<31:22,  3.67it/s]

  8%|▊         | 587/7491 [02:33<31:22,  3.67it/s]
  8%|▊         | 588/7491 [02:33<31:21,  3.67it/s]

  8%|▊         | 589/7491 [02:34<31:38,  3.63it/s]

  8%|▊         | 589/7491 [02:34<31:38,  3.63it/s]
  8%|▊         | 590/7491 [02:34<31:38,  3.63it/s]

  8%|▊         | 591/7491 [02:34<32:15,  3.56it/s]

  8%|▊         | 591/7491 [02:34<32:15,  3.56it/s]
  8%|▊         | 592/7491 [02:34<32:15,  3.56it/s]
  8%|▊         | 593/7491 [02:34<32:15,  3.56it/s]
  8%|▊         | 594/7491 [02:34<32:15,  3.56it/s]
  8%|▊         | 595/7491 [02:34<32:14,  3.56it/s]

  8%|▊         | 596/7491 [02:35<25:00,  4.59it/s]

  8%|▊         | 596/7491 [02:35<25:00,  4.59it/s]
  8%|▊         | 597/7491 [02:35<25:00,  4.59it/s]

  8%|▊         | 598/7491 [02:38<53:15,  2.16it/s]

  8%|▊         | 598/7491 [02:38<53:15,  2.16it/s]
  8%|▊         | 599/7491 [02:38<53:14,  2.16it/s]
  8%|▊         | 600/7491 [02:38<53:14,  2.16it/s]
  8%|▊         | 601/7491 [02:38<53:14,  2.16it/s]
  8%|▊         | 602/7491 [02:38<53:13,  2.16it/s]
  8%|▊         | 603/7491 [02:38<53:13,  2.16it/s]
  8%|▊         | 604/7491 [02:38<53:12,  2.16it/s]

  8%|▊         | 605/7491 [02:38<30:00,  3.83it/s]

  8%|▊         | 605/7491 [02:38<30:00,  3.83it/s]
  8%|▊         | 606/7491 [02:38<29:59,  3.83it/s]

  8%|▊         | 607/7491 [02:39<30:40,  3.74it/s]

  8%|▊         | 607/7491 [02:39<30:40,  3.74it/s]
  8%|▊         | 608/7491 [02:39<30:40,  3.74it/s]

  8%|▊         | 609/7491 [02:39<31:51,  3.60it/s]

  8%|▊         | 609/7491 [02:39<31:51,  3.60it/s]
  8%|▊         | 610/7491 [02:40<31:51,  3.60it/s]

  8%|▊         | 611/7491 [02:40<31:55,  3.59it/s]

  8%|▊         | 611/7491 [02:40<31:55,  3.59it/s]
  8%|▊         | 612/7491 [02:40<31:54,  3.59it/s]

  8%|▊         | 613/7491 [02:41<33:22,  3.43it/s]

  8%|▊         | 613/7491 [02:41<33:22,  3.43it/s]
  8%|▊         | 614/7491 [02:41<33:22,  3.43it/s]

  8%|▊         | 615/7491 [02:41<33:16,  3.44it/s]

  8%|▊         | 615/7491 [02:41<33:16,  3.44it/s]
  8%|▊         | 616/7491 [02:41<33:15,  3.44it/s]

  8%|▊         | 617/7491 [02:42<33:37,  3.41it/s]

  8%|▊         | 617/7491 [02:42<33:37,  3.41it/s]
  8%|▊         | 618/7491 [02:42<33:37,  3.41it/s]

  8%|▊         | 619/7491 [02:42<33:26,  3.43it/s]

  8%|▊         | 619/7491 [02:42<33:26,  3.43it/s]
  8%|▊         | 620/7491 [02:42<33:25,  3.43it/s]

  8%|▊         | 621/7491 [02:43<33:48,  3.39it/s]

  8%|▊         | 621/7491 [02:43<33:48,  3.39it/s]
  8%|▊         | 622/7491 [02:43<33:48,  3.39it/s]
  8%|▊         | 623/7491 [02:43<33:47,  3.39it/s]

  8%|▊         | 624/7491 [02:44<29:43,  3.85it/s]

  8%|▊         | 624/7491 [02:44<29:43,  3.85it/s]
  8%|▊         | 625/7491 [02:44<29:42,  3.85it/s]

  8%|▊         | 626/7491 [02:44<30:36,  3.74it/s]

  8%|▊         | 626/7491 [02:44<30:36,  3.74it/s]
  8%|▊         | 627/7491 [02:44<30:36,  3.74it/s]

  8%|▊         | 628/7491 [02:45<31:30,  3.63it/s]

  8%|▊         | 628/7491 [02:45<31:30,  3.63it/s]
  8%|▊         | 629/7491 [02:45<31:30,  3.63it/s]

  8%|▊         | 630/7491 [02:45<32:05,  3.56it/s]

  8%|▊         | 630/7491 [02:45<32:05,  3.56it/s]
  8%|▊         | 631/7491 [02:45<32:04,  3.56it/s]

  8%|▊         | 632/7491 [02:46<32:45,  3.49it/s]

  8%|▊         | 632/7491 [02:46<32:45,  3.49it/s]
  8%|▊         | 633/7491 [02:46<32:45,  3.49it/s]

  8%|▊         | 634/7491 [02:47<32:47,  3.49it/s]

  8%|▊         | 634/7491 [02:47<32:47,  3.49it/s]
  8%|▊         | 635/7491 [02:47<32:46,  3.49it/s]

  8%|▊         | 636/7491 [02:47<33:10,  3.44it/s]

  8%|▊         | 636/7491 [02:47<33:10,  3.44it/s]
  9%|▊         | 637/7491 [02:47<33:10,  3.44it/s]

  9%|▊         | 638/7491 [02:50<1:07:58,  1.68it/s]

  9%|▊         | 638/7491 [02:50<1:07:58,  1.68it/s]
  9%|▊         | 639/7491 [02:50<1:07:57,  1.68it/s]

  9%|▊         | 640/7491 [02:51<1:00:58,  1.87it/s]

  9%|▊         | 640/7491 [02:51<1:00:58,  1.87it/s]
  9%|▊         | 641/7491 [02:51<1:00:57,  1.87it/s]

  9%|▊         | 642/7491 [02:51<53:18,  2.14it/s]

  9%|▊         | 642/7491 [02:51<53:18,  2.14it/s]
  9%|▊         | 643/7491 [02:51<53:18,  2.14it/s]

  9%|▊         | 644/7491 [02:52<47:39,  2.39it/s]

  9%|▊         | 644/7491 [02:52<47:39,  2.39it/s]
  9%|▊         | 645/7491 [02:52<47:39,  2.39it/s]

  9%|▊         | 646/7491 [02:52<43:55,  2.60it/s]

  9%|▊         | 646/7491 [02:52<43:55,  2.60it/s]
  9%|▊         | 647/7491 [02:53<43:54,  2.60it/s]

  9%|▊         | 648/7491 [02:53<40:55,  2.79it/s]

  9%|▊         | 648/7491 [02:53<40:55,  2.79it/s]
  9%|▊         | 649/7491 [02:53<40:54,  2.79it/s]

  9%|▊         | 650/7491 [02:54<39:09,  2.91it/s]

  9%|▊         | 650/7491 [02:54<39:09,  2.91it/s]
  9%|▊         | 651/7491 [02:54<39:09,  2.91it/s]

  9%|▊         | 652/7491 [02:54<37:53,  3.01it/s]

  9%|▊         | 652/7491 [02:54<37:53,  3.01it/s]
  9%|▊         | 653/7491 [02:54<37:53,  3.01it/s]
  9%|▊         | 654/7491 [02:54<37:52,  3.01it/s]

  9%|▊         | 655/7491 [02:55<32:11,  3.54it/s]

  9%|▊         | 655/7491 [02:55<32:11,  3.54it/s]
  9%|▉         | 656/7491 [02:55<32:11,  3.54it/s]
  9%|▉         | 657/7491 [02:55<32:10,  3.54it/s]

  9%|▉         | 658/7491 [02:56<29:11,  3.90it/s]

  9%|▉         | 658/7491 [02:56<29:11,  3.90it/s]
  9%|▉         | 659/7491 [02:56<29:11,  3.90it/s]

  9%|▉         | 660/7491 [02:56<30:14,  3.76it/s]

  9%|▉         | 660/7491 [02:56<30:14,  3.76it/s]
  9%|▉         | 661/7491 [02:56<30:14,  3.76it/s]

  9%|▉         | 662/7491 [02:57<31:20,  3.63it/s]

  9%|▉         | 662/7491 [02:57<31:20,  3.63it/s]
  9%|▉         | 663/7491 [02:57<31:20,  3.63it/s]
  9%|▉         | 664/7491 [02:57<31:19,  3.63it/s]

  9%|▉         | 665/7491 [02:57<28:04,  4.05it/s]

  9%|▉         | 665/7491 [02:57<28:04,  4.05it/s]
  9%|▉         | 666/7491 [02:57<28:04,  4.05it/s]

  9%|▉         | 667/7491 [02:58<29:25,  3.87it/s]

  9%|▉         | 667/7491 [02:58<29:25,  3.87it/s]
  9%|▉         | 668/7491 [02:58<29:25,  3.87it/s]
  9%|▉         | 669/7491 [02:58<29:24,  3.87it/s]

  9%|▉         | 670/7491 [02:59<27:24,  4.15it/s]

  9%|▉         | 670/7491 [02:59<27:24,  4.15it/s]
  9%|▉         | 671/7491 [02:59<27:24,  4.15it/s]

  9%|▉         | 672/7491 [02:59<28:52,  3.94it/s]

  9%|▉         | 672/7491 [02:59<28:52,  3.94it/s]
  9%|▉         | 673/7491 [02:59<28:52,  3.94it/s]

  9%|▉         | 674/7491 [03:00<30:23,  3.74it/s]

  9%|▉         | 674/7491 [03:00<30:23,  3.74it/s]
  9%|▉         | 675/7491 [03:00<30:23,  3.74it/s]

  9%|▉         | 676/7491 [03:00<33:33,  3.38it/s]

  9%|▉         | 676/7491 [03:00<33:33,  3.38it/s]
  9%|▉         | 677/7491 [03:00<33:33,  3.38it/s]

  9%|▉         | 678/7491 [03:03<1:07:15,  1.69it/s]

  9%|▉         | 678/7491 [03:03<1:07:15,  1.69it/s]
  9%|▉         | 679/7491 [03:03<1:07:15,  1.69it/s]
  9%|▉         | 680/7491 [03:03<1:07:14,  1.69it/s]

  9%|▉         | 681/7491 [03:04<50:17,  2.26it/s]

  9%|▉         | 681/7491 [03:04<50:17,  2.26it/s]
  9%|▉         | 682/7491 [03:04<50:17,  2.26it/s]

  9%|▉         | 683/7491 [03:04<45:34,  2.49it/s]

  9%|▉         | 683/7491 [03:04<45:34,  2.49it/s]
  9%|▉         | 684/7491 [03:04<45:33,  2.49it/s]
  9%|▉         | 685/7491 [03:04<45:33,  2.49it/s]
  9%|▉         | 686/7491 [03:04<45:33,  2.49it/s]
  9%|▉         | 687/7491 [03:04<45:32,  2.49it/s]
  9%|▉         | 688/7491 [03:04<45:32,  2.49it/s]
  9%|▉         | 689/7491 [03:04<45:31,  2.49it/s]

  9%|▉         | 690/7491 [03:05<25:24,  4.46it/s]

  9%|▉         | 690/7491 [03:05<25:24,  4.46it/s]
  9%|▉         | 691/7491 [03:05<25:24,  4.46it/s]
  9%|▉         | 692/7491 [03:05<25:24,  4.46it/s]
  9%|▉         | 693/7491 [03:05<25:24,  4.46it/s]
  9%|▉         | 694/7491 [03:05<25:24,  4.46it/s]
  9%|▉         | 695/7491 [03:05<25:23,  4.46it/s]
  9%|▉         | 696/7491 [03:05<25:23,  4.46it/s]
  9%|▉         | 697/7491 [03:05<25:23,  4.46it/s]

  9%|▉         | 698/7491 [03:06<17:15,  6.56it/s]

  9%|▉         | 698/7491 [03:06<17:15,  6.56it/s]
  9%|▉         | 699/7491 [03:06<17:14,  6.56it/s]

  9%|▉         | 700/7491 [03:06<19:34,  5.78it/s]

  9%|▉         | 700/7491 [03:06<19:34,  5.78it/s]
  9%|▉         | 701/7491 [03:06<19:34,  5.78it/s]
  9%|▉         | 702/7491 [03:06<19:34,  5.78it/s]

  9%|▉         | 703/7491 [03:07<19:53,  5.69it/s]

  9%|▉         | 703/7491 [03:07<19:53,  5.69it/s]
  9%|▉         | 704/7491 [03:07<19:53,  5.69it/s]

  9%|▉         | 705/7491 [03:07<22:35,  5.00it/s]

  9%|▉         | 705/7491 [03:07<22:35,  5.00it/s]
  9%|▉         | 706/7491 [03:07<22:35,  5.00it/s]

  9%|▉         | 707/7491 [03:08<24:22,  4.64it/s]

  9%|▉         | 707/7491 [03:08<24:22,  4.64it/s]
  9%|▉         | 708/7491 [03:08<24:21,  4.64it/s]
  9%|▉         | 709/7491 [03:08<24:21,  4.64it/s]

  9%|▉         | 710/7491 [03:08<23:59,  4.71it/s]

  9%|▉         | 710/7491 [03:08<23:59,  4.71it/s]
  9%|▉         | 711/7491 [03:09<23:59,  4.71it/s]

 10%|▉         | 712/7491 [03:09<26:32,  4.26it/s]

 10%|▉         | 712/7491 [03:09<26:32,  4.26it/s]
 10%|▉         | 713/7491 [03:09<26:32,  4.26it/s]

 10%|▉         | 714/7491 [03:10<27:45,  4.07it/s]

 10%|▉         | 714/7491 [03:10<27:45,  4.07it/s]
 10%|▉         | 715/7491 [03:10<27:44,  4.07it/s]

 10%|▉         | 716/7491 [03:10<29:15,  3.86it/s]

 10%|▉         | 716/7491 [03:10<29:15,  3.86it/s]
 10%|▉         | 717/7491 [03:10<29:15,  3.86it/s]

 10%|▉         | 718/7491 [03:11<30:43,  3.67it/s]

 10%|▉         | 718/7491 [03:11<30:43,  3.67it/s]
 10%|▉         | 719/7491 [03:11<30:42,  3.67it/s]

 10%|▉         | 720/7491 [03:11<31:48,  3.55it/s]

 10%|▉         | 720/7491 [03:11<31:48,  3.55it/s]
 10%|▉         | 721/7491 [03:11<31:48,  3.55it/s]

 10%|▉         | 722/7491 [03:12<31:43,  3.56it/s]

 10%|▉         | 722/7491 [03:12<31:43,  3.56it/s]
 10%|▉         | 723/7491 [03:12<31:43,  3.56it/s]

 10%|▉         | 724/7491 [03:13<32:12,  3.50it/s]

 10%|▉         | 724/7491 [03:13<32:12,  3.50it/s]
 10%|▉         | 725/7491 [03:13<32:12,  3.50it/s]

 10%|▉         | 726/7491 [03:16<1:10:57,  1.59it/s]

 10%|▉         | 726/7491 [03:16<1:10:57,  1.59it/s]
 10%|▉         | 727/7491 [03:16<1:10:57,  1.59it/s]

 10%|▉         | 728/7491 [03:16<59:25,  1.90it/s]

 10%|▉         | 728/7491 [03:16<59:25,  1.90it/s]
 10%|▉         | 729/7491 [03:16<59:25,  1.90it/s]

 10%|▉         | 730/7491 [03:17<51:52,  2.17it/s]

 10%|▉         | 730/7491 [03:17<51:52,  2.17it/s]
 10%|▉         | 731/7491 [03:17<51:51,  2.17it/s]

 10%|▉         | 732/7491 [03:17<46:45,  2.41it/s]

 10%|▉         | 732/7491 [03:17<46:45,  2.41it/s]
 10%|▉         | 733/7491 [03:17<46:45,  2.41it/s]
 10%|▉         | 734/7491 [03:17<46:44,  2.41it/s]

 10%|▉         | 735/7491 [03:18<38:03,  2.96it/s]

 10%|▉         | 735/7491 [03:18<38:03,  2.96it/s]
 10%|▉         | 736/7491 [03:18<38:02,  2.96it/s]

 10%|▉         | 737/7491 [03:19<37:22,  3.01it/s]

 10%|▉         | 737/7491 [03:19<37:22,  3.01it/s]
 10%|▉         | 738/7491 [03:19<37:22,  3.01it/s]
 10%|▉         | 739/7491 [03:19<37:21,  3.01it/s]
 10%|▉         | 740/7491 [03:19<37:21,  3.01it/s]

 10%|▉         | 741/7491 [03:19<28:36,  3.93it/s]

 10%|▉         | 741/7491 [03:19<28:36,  3.93it/s]
 10%|▉         | 742/7491 [03:19<28:35,  3.93it/s]

 10%|▉         | 743/7491 [03:20<30:22,  3.70it/s]

 10%|▉         | 743/7491 [03:20<30:22,  3.70it/s]
 10%|▉         | 744/7491 [03:20<30:22,  3.70it/s]
 10%|▉         | 745/7491 [03:20<30:21,  3.70it/s]
 10%|▉         | 746/7491 [03:20<30:21,  3.70it/s]
 10%|▉         | 747/7491 [03:20<30:21,  3.70it/s]
 10%|▉         | 748/7491 [03:20<30:21,  3.70it/s]
 10%|▉         | 749/7491 [03:20<30:20,  3.70it/s]

 10%|█         | 750/7491 [03:21<19:34,  5.74it/s]

 10%|█         | 750/7491 [03:21<19:34,  5.74it/s]
 10%|█         | 751/7491 [03:21<19:34,  5.74it/s]
 10%|█         | 752/7491 [03:21<19:34,  5.74it/s]

 10%|█         | 753/7491 [03:21<20:14,  5.55it/s]

 10%|█         | 753/7491 [03:21<20:14,  5.55it/s]
 10%|█         | 754/7491 [03:21<20:14,  5.55it/s]
 10%|█         | 755/7491 [03:21<20:14,  5.55it/s]
 10%|█         | 756/7491 [03:21<20:14,  5.55it/s]
 10%|█         | 757/7491 [03:21<20:14,  5.55it/s]
 10%|█         | 758/7491 [03:21<20:13,  5.55it/s]

 10%|█         | 759/7491 [03:22<16:40,  6.73it/s]

 10%|█         | 759/7491 [03:22<16:40,  6.73it/s]
 10%|█         | 760/7491 [03:22<16:39,  6.73it/s]
 10%|█         | 761/7491 [03:22<16:39,  6.73it/s]

 10%|█         | 762/7491 [03:22<18:01,  6.22it/s]

 10%|█         | 762/7491 [03:22<18:01,  6.22it/s]
 10%|█         | 763/7491 [03:22<18:01,  6.22it/s]
 10%|█         | 764/7491 [03:22<18:01,  6.22it/s]

 10%|█         | 765/7491 [03:23<19:20,  5.80it/s]

 10%|█         | 765/7491 [03:23<19:20,  5.80it/s]
 10%|█         | 766/7491 [03:23<19:20,  5.80it/s]

 10%|█         | 767/7491 [03:24<21:59,  5.10it/s]

 10%|█         | 767/7491 [03:24<21:59,  5.10it/s]
 10%|█         | 768/7491 [03:24<21:59,  5.10it/s]

 10%|█         | 769/7491 [03:24<24:37,  4.55it/s]

 10%|█         | 769/7491 [03:24<24:37,  4.55it/s]
 10%|█         | 770/7491 [03:24<24:37,  4.55it/s]

 10%|█         | 771/7491 [03:25<26:52,  4.17it/s]

 10%|█         | 771/7491 [03:25<26:52,  4.17it/s]
 10%|█         | 772/7491 [03:25<26:52,  4.17it/s]

 10%|█         | 773/7491 [03:25<28:21,  3.95it/s]

 10%|█         | 773/7491 [03:25<28:21,  3.95it/s]
 10%|█         | 774/7491 [03:25<28:21,  3.95it/s]

 10%|█         | 775/7491 [03:28<1:02:35,  1.79it/s]

 10%|█         | 775/7491 [03:28<1:02:35,  1.79it/s]
 10%|█         | 776/7491 [03:28<1:02:34,  1.79it/s]

 10%|█         | 777/7491 [03:29<54:20,  2.06it/s]

 10%|█         | 777/7491 [03:29<54:20,  2.06it/s]
 10%|█         | 778/7491 [03:29<54:19,  2.06it/s]

 10%|█         | 779/7491 [03:29<48:38,  2.30it/s]

 10%|█         | 779/7491 [03:29<48:38,  2.30it/s]
 10%|█         | 780/7491 [03:29<48:38,  2.30it/s]

 10%|█         | 781/7491 [03:30<44:20,  2.52it/s]

 10%|█         | 781/7491 [03:30<44:20,  2.52it/s]
 10%|█         | 782/7491 [03:30<44:20,  2.52it/s]

 10%|█         | 783/7491 [03:31<41:18,  2.71it/s]

 10%|█         | 783/7491 [03:31<41:18,  2.71it/s]
 10%|█         | 784/7491 [03:31<41:18,  2.71it/s]

 10%|█         | 785/7491 [03:31<39:29,  2.83it/s]

 10%|█         | 785/7491 [03:31<39:29,  2.83it/s]
 10%|█         | 786/7491 [03:31<39:29,  2.83it/s]

 11%|█         | 787/7491 [03:32<37:53,  2.95it/s]

 11%|█         | 787/7491 [03:32<37:53,  2.95it/s]
 11%|█         | 788/7491 [03:32<37:53,  2.95it/s]
 11%|█         | 789/7491 [03:32<37:53,  2.95it/s]
 11%|█         | 790/7491 [03:32<37:52,  2.95it/s]
 11%|█         | 791/7491 [03:32<37:52,  2.95it/s]
 11%|█         | 792/7491 [03:32<37:52,  2.95it/s]
 11%|█         | 793/7491 [03:32<37:51,  2.95it/s]
 11%|█         | 794/7491 [03:32<37:51,  2.95it/s]
 11%|█         | 795/7491 [03:32<37:51,  2.95it/s]
 11%|█         | 796/7491 [03:32<37:50,  2.95it/s]
 11%|█         | 797/7491 [03:32<37:50,  2.95it/s]
 11%|█         | 798/7491 [03:32<37:50,  2.95it/s]
 11%|█         | 799/7491 [03:32<37:49,  2.95it/s]
 11%|█         | 800/7491 [03:32<37:49,  2.95it/s]

 11%|█         | 801/7491 [03:33<13:34,  8.21it/s]

 11%|█         | 801/7491 [03:33<13:34,  8.21it/s]
 11%|█         | 802/7491 [03:33<13:34,  8.21it/s]

 11%|█         | 803/7491 [03:33<16:19,  6.83it/s]

 11%|█         | 803/7491 [03:33<16:19,  6.83it/s]
 11%|█         | 804/7491 [03:33<16:19,  6.83it/s]
 11%|█         | 805/7491 [03:33<16:19,  6.83it/s]
 11%|█         | 806/7491 [03:33<16:19,  6.83it/s]

 11%|█         | 807/7491 [03:34<16:47,  6.63it/s]

 11%|█         | 807/7491 [03:34<16:47,  6.63it/s]
 11%|█         | 808/7491 [03:34<16:47,  6.63it/s]

 11%|█         | 809/7491 [03:34<20:19,  5.48it/s]

 11%|█         | 809/7491 [03:34<20:19,  5.48it/s]
 11%|█         | 810/7491 [03:34<20:19,  5.48it/s]

 11%|█         | 811/7491 [03:35<23:07,  4.82it/s]

 11%|█         | 811/7491 [03:35<23:07,  4.82it/s]
 11%|█         | 812/7491 [03:35<23:06,  4.82it/s]

 11%|█         | 813/7491 [03:36<26:04,  4.27it/s]

 11%|█         | 813/7491 [03:36<26:04,  4.27it/s]
 11%|█         | 814/7491 [03:36<26:04,  4.27it/s]
 11%|█         | 815/7491 [03:36<26:04,  4.27it/s]
 11%|█         | 816/7491 [03:36<26:03,  4.27it/s]

 11%|█         | 817/7491 [03:36<23:17,  4.78it/s]

 11%|█         | 817/7491 [03:36<23:17,  4.78it/s]
 11%|█         | 818/7491 [03:36<23:16,  4.78it/s]

 11%|█         | 819/7491 [03:37<25:37,  4.34it/s]

 11%|█         | 819/7491 [03:37<25:37,  4.34it/s]
 11%|█         | 820/7491 [03:37<25:37,  4.34it/s]

 11%|█         | 821/7491 [03:38<28:01,  3.97it/s]

 11%|█         | 821/7491 [03:38<28:01,  3.97it/s]
 11%|█         | 822/7491 [03:38<28:01,  3.97it/s]

 11%|█         | 823/7491 [03:40<56:18,  1.97it/s]

 11%|█         | 823/7491 [03:40<56:18,  1.97it/s]
 11%|█         | 824/7491 [03:40<56:18,  1.97it/s]

 11%|█         | 825/7491 [03:41<56:09,  1.98it/s]

 11%|█         | 825/7491 [03:41<56:09,  1.98it/s]
 11%|█         | 826/7491 [03:41<56:08,  1.98it/s]

 11%|█         | 827/7491 [03:42<50:41,  2.19it/s]

 11%|█         | 827/7491 [03:42<50:41,  2.19it/s]
 11%|█         | 828/7491 [03:42<50:40,  2.19it/s]

 11%|█         | 829/7491 [03:43<46:01,  2.41it/s]

 11%|█         | 829/7491 [03:43<46:01,  2.41it/s]
 11%|█         | 830/7491 [03:43<46:00,  2.41it/s]

 11%|█         | 831/7491 [03:43<42:35,  2.61it/s]

 11%|█         | 831/7491 [03:43<42:35,  2.61it/s]
 11%|█         | 832/7491 [03:43<42:35,  2.61it/s]

 11%|█         | 833/7491 [03:44<40:51,  2.72it/s]

 11%|█         | 833/7491 [03:44<40:51,  2.72it/s]
 11%|█         | 834/7491 [03:44<40:51,  2.72it/s]

 11%|█         | 835/7491 [03:44<38:36,  2.87it/s]

 11%|█         | 835/7491 [03:44<38:36,  2.87it/s]
 11%|█         | 836/7491 [03:44<38:35,  2.87it/s]

 11%|█         | 837/7491 [03:45<37:19,  2.97it/s]

 11%|█         | 837/7491 [03:45<37:19,  2.97it/s]
 11%|█         | 838/7491 [03:45<37:19,  2.97it/s]

 11%|█         | 839/7491 [03:46<36:31,  3.03it/s]

 11%|█         | 839/7491 [03:46<36:31,  3.03it/s]
 11%|█         | 840/7491 [03:46<36:31,  3.03it/s]

 11%|█         | 841/7491 [03:46<35:46,  3.10it/s]

 11%|█         | 841/7491 [03:46<35:46,  3.10it/s]
 11%|█         | 842/7491 [03:46<35:46,  3.10it/s]

 11%|█▏        | 843/7491 [03:47<34:37,  3.20it/s]

 11%|█▏        | 843/7491 [03:47<34:37,  3.20it/s]
 11%|█▏        | 844/7491 [03:47<34:37,  3.20it/s]

 11%|█▏        | 845/7491 [03:47<34:25,  3.22it/s]

 11%|█▏        | 845/7491 [03:47<34:25,  3.22it/s]
 11%|█▏        | 846/7491 [03:47<34:25,  3.22it/s]

 11%|█▏        | 847/7491 [03:48<34:23,  3.22it/s]

 11%|█▏        | 847/7491 [03:48<34:23,  3.22it/s]
 11%|█▏        | 848/7491 [03:48<34:23,  3.22it/s]

 11%|█▏        | 849/7491 [03:49<34:02,  3.25it/s]

 11%|█▏        | 849/7491 [03:49<34:02,  3.25it/s]
 11%|█▏        | 850/7491 [03:49<34:01,  3.25it/s]

 11%|█▏        | 851/7491 [03:49<34:02,  3.25it/s]

 11%|█▏        | 851/7491 [03:49<34:02,  3.25it/s]
 11%|█▏        | 852/7491 [03:49<34:02,  3.25it/s]

 11%|█▏        | 853/7491 [03:50<33:12,  3.33it/s]

 11%|█▏        | 853/7491 [03:50<33:12,  3.33it/s]
 11%|█▏        | 854/7491 [03:50<33:12,  3.33it/s]

 11%|█▏        | 855/7491 [03:50<33:09,  3.34it/s]

 11%|█▏        | 855/7491 [03:50<33:09,  3.34it/s]
 11%|█▏        | 856/7491 [03:50<33:09,  3.34it/s]

 11%|█▏        | 857/7491 [03:52<56:45,  1.95it/s]

 11%|█▏        | 857/7491 [03:52<56:45,  1.95it/s]
 11%|█▏        | 858/7491 [03:52<56:45,  1.95it/s]

 11%|█▏        | 859/7491 [03:54<1:02:40,  1.76it/s]

 11%|█▏        | 859/7491 [03:54<1:02:40,  1.76it/s]
 11%|█▏        | 860/7491 [03:54<1:02:39,  1.76it/s]

 11%|█▏        | 861/7491 [03:54<53:30,  2.07it/s]

 11%|█▏        | 861/7491 [03:54<53:30,  2.07it/s]
 12%|█▏        | 862/7491 [03:54<53:29,  2.07it/s]
 12%|█▏        | 863/7491 [03:54<53:29,  2.07it/s]
 12%|█▏        | 864/7491 [03:54<53:28,  2.07it/s]
 12%|█▏        | 865/7491 [03:54<53:28,  2.07it/s]
 12%|█▏        | 866/7491 [03:54<53:27,  2.07it/s]

 12%|█▏        | 867/7491 [03:55<29:27,  3.75it/s]

 12%|█▏        | 867/7491 [03:55<29:27,  3.75it/s]
 12%|█▏        | 868/7491 [03:55<29:26,  3.75it/s]

 12%|█▏        | 869/7491 [03:56<30:12,  3.65it/s]

 12%|█▏        | 869/7491 [03:56<30:12,  3.65it/s]
 12%|█▏        | 870/7491 [03:56<30:11,  3.65it/s]

 12%|█▏        | 871/7491 [03:56<30:12,  3.65it/s]

 12%|█▏        | 871/7491 [03:56<30:12,  3.65it/s]
 12%|█▏        | 872/7491 [03:56<30:12,  3.65it/s]

 12%|█▏        | 873/7491 [03:57<31:04,  3.55it/s]

 12%|█▏        | 873/7491 [03:57<31:04,  3.55it/s]
 12%|█▏        | 874/7491 [03:57<31:03,  3.55it/s]

 12%|█▏        | 875/7491 [03:57<31:01,  3.55it/s]

 12%|█▏        | 875/7491 [03:57<31:01,  3.55it/s]
 12%|█▏        | 876/7491 [03:57<31:01,  3.55it/s]

 12%|█▏        | 877/7491 [03:58<31:20,  3.52it/s]

 12%|█▏        | 877/7491 [03:58<31:20,  3.52it/s]
 12%|█▏        | 878/7491 [03:58<31:19,  3.52it/s]

 12%|█▏        | 879/7491 [03:59<32:09,  3.43it/s]

 12%|█▏        | 879/7491 [03:59<32:09,  3.43it/s]
 12%|█▏        | 880/7491 [03:59<32:09,  3.43it/s]

 12%|█▏        | 881/7491 [03:59<32:01,  3.44it/s]

 12%|█▏        | 881/7491 [03:59<32:01,  3.44it/s]
 12%|█▏        | 882/7491 [03:59<32:00,  3.44it/s]

 12%|█▏        | 883/7491 [04:00<32:54,  3.35it/s]

 12%|█▏        | 883/7491 [04:00<32:54,  3.35it/s]
 12%|█▏        | 884/7491 [04:00<32:53,  3.35it/s]

 12%|█▏        | 885/7491 [04:00<32:27,  3.39it/s]

 12%|█▏        | 885/7491 [04:00<32:27,  3.39it/s]
 12%|█▏        | 886/7491 [04:00<32:26,  3.39it/s]

 12%|█▏        | 887/7491 [04:01<32:42,  3.36it/s]

 12%|█▏        | 887/7491 [04:01<32:42,  3.36it/s]
 12%|█▏        | 888/7491 [04:01<32:42,  3.36it/s]

 12%|█▏        | 889/7491 [04:02<32:25,  3.39it/s]

 12%|█▏        | 889/7491 [04:02<32:25,  3.39it/s]
 12%|█▏        | 890/7491 [04:02<32:25,  3.39it/s]

 12%|█▏        | 891/7491 [04:02<32:26,  3.39it/s]

 12%|█▏        | 891/7491 [04:02<32:26,  3.39it/s]
 12%|█▏        | 892/7491 [04:02<32:25,  3.39it/s]

 12%|█▏        | 893/7491 [04:03<32:33,  3.38it/s]

 12%|█▏        | 893/7491 [04:03<32:33,  3.38it/s]
 12%|█▏        | 894/7491 [04:03<32:33,  3.38it/s]

 12%|█▏        | 895/7491 [04:03<32:41,  3.36it/s]

 12%|█▏        | 895/7491 [04:03<32:41,  3.36it/s]
 12%|█▏        | 896/7491 [04:03<32:40,  3.36it/s]

 12%|█▏        | 897/7491 [04:06<1:11:26,  1.54it/s]

 12%|█▏        | 897/7491 [04:06<1:11:26,  1.54it/s]
 12%|█▏        | 898/7491 [04:06<1:11:26,  1.54it/s]
 12%|█▏        | 899/7491 [04:06<1:11:25,  1.54it/s]
 12%|█▏        | 900/7491 [04:06<1:11:24,  1.54it/s]
 12%|█▏        | 901/7491 [04:06<1:11:24,  1.54it/s]
 12%|█▏        | 902/7491 [04:06<1:11:23,  1.54it/s]

 12%|█▏        | 903/7491 [04:07<37:39,  2.92it/s]

 12%|█▏        | 903/7491 [04:07<37:39,  2.92it/s]
 12%|█▏        | 904/7491 [04:07<37:38,  2.92it/s]

 12%|█▏        | 905/7491 [04:08<37:02,  2.96it/s]

 12%|█▏        | 905/7491 [04:08<37:02,  2.96it/s]
 12%|█▏        | 906/7491 [04:08<37:02,  2.96it/s]

 12%|█▏        | 907/7491 [04:08<36:28,  3.01it/s]

 12%|█▏        | 907/7491 [04:08<36:28,  3.01it/s]
 12%|█▏        | 908/7491 [04:08<36:27,  3.01it/s]

 12%|█▏        | 909/7491 [04:09<35:45,  3.07it/s]

 12%|█▏        | 909/7491 [04:09<35:45,  3.07it/s]
 12%|█▏        | 910/7491 [04:09<35:44,  3.07it/s]
 12%|█▏        | 911/7491 [04:09<35:44,  3.07it/s]

 12%|█▏        | 912/7491 [04:09<31:02,  3.53it/s]

 12%|█▏        | 912/7491 [04:09<31:02,  3.53it/s]
 12%|█▏        | 913/7491 [04:09<31:02,  3.53it/s]
 12%|█▏        | 914/7491 [04:09<31:02,  3.53it/s]

 12%|█▏        | 915/7491 [04:10<27:46,  3.95it/s]

 12%|█▏        | 915/7491 [04:10<27:46,  3.95it/s]
 12%|█▏        | 916/7491 [04:10<27:45,  3.95it/s]

 12%|█▏        | 917/7491 [04:11<29:17,  3.74it/s]

 12%|█▏        | 917/7491 [04:11<29:17,  3.74it/s]
 12%|█▏        | 918/7491 [04:11<29:17,  3.74it/s]

 12%|█▏        | 919/7491 [04:11<30:22,  3.61it/s]

 12%|█▏        | 919/7491 [04:11<30:22,  3.61it/s]
 12%|█▏        | 920/7491 [04:11<30:22,  3.61it/s]

 12%|█▏        | 921/7491 [04:12<31:06,  3.52it/s]

 12%|█▏        | 921/7491 [04:12<31:06,  3.52it/s]
 12%|█▏        | 922/7491 [04:12<31:06,  3.52it/s]

 12%|█▏        | 923/7491 [04:12<31:38,  3.46it/s]

 12%|█▏        | 923/7491 [04:12<31:38,  3.46it/s]
 12%|█▏        | 924/7491 [04:12<31:37,  3.46it/s]
 12%|█▏        | 925/7491 [04:12<31:37,  3.46it/s]

 12%|█▏        | 926/7491 [04:13<27:42,  3.95it/s]

 12%|█▏        | 926/7491 [04:13<27:42,  3.95it/s]
 12%|█▏        | 927/7491 [04:13<27:42,  3.95it/s]

 12%|█▏        | 928/7491 [04:14<29:11,  3.75it/s]

 12%|█▏        | 928/7491 [04:14<29:11,  3.75it/s]
 12%|█▏        | 929/7491 [04:14<29:11,  3.75it/s]

 12%|█▏        | 930/7491 [04:14<30:28,  3.59it/s]

 12%|█▏        | 930/7491 [04:14<30:28,  3.59it/s]
 12%|█▏        | 931/7491 [04:14<30:28,  3.59it/s]

 12%|█▏        | 932/7491 [04:15<31:18,  3.49it/s]

 12%|█▏        | 932/7491 [04:15<31:18,  3.49it/s]
 12%|█▏        | 933/7491 [04:15<31:18,  3.49it/s]

 12%|█▏        | 934/7491 [04:15<32:13,  3.39it/s]

 12%|█▏        | 934/7491 [04:15<32:13,  3.39it/s]
 12%|█▏        | 935/7491 [04:15<32:13,  3.39it/s]

 12%|█▏        | 936/7491 [04:16<32:12,  3.39it/s]

 12%|█▏        | 936/7491 [04:16<32:12,  3.39it/s]
 13%|█▎        | 937/7491 [04:16<32:11,  3.39it/s]

 13%|█▎        | 938/7491 [04:19<1:09:31,  1.57it/s]

 13%|█▎        | 938/7491 [04:19<1:09:31,  1.57it/s]
 13%|█▎        | 939/7491 [04:19<1:09:30,  1.57it/s]

 13%|█▎        | 940/7491 [04:20<58:50,  1.86it/s]

 13%|█▎        | 940/7491 [04:20<58:50,  1.86it/s]
 13%|█▎        | 941/7491 [04:20<58:50,  1.86it/s]

 13%|█▎        | 942/7491 [04:20<51:30,  2.12it/s]

 13%|█▎        | 942/7491 [04:20<51:30,  2.12it/s]
 13%|█▎        | 943/7491 [04:20<51:29,  2.12it/s]

 13%|█▎        | 944/7491 [04:21<46:25,  2.35it/s]

 13%|█▎        | 944/7491 [04:21<46:25,  2.35it/s]
 13%|█▎        | 945/7491 [04:21<46:24,  2.35it/s]

 13%|█▎        | 946/7491 [04:21<42:27,  2.57it/s]

 13%|█▎        | 946/7491 [04:21<42:27,  2.57it/s]
 13%|█▎        | 947/7491 [04:21<42:27,  2.57it/s]

 13%|█▎        | 948/7491 [04:22<39:52,  2.73it/s]

 13%|█▎        | 948/7491 [04:22<39:52,  2.73it/s]
 13%|█▎        | 949/7491 [04:22<39:52,  2.73it/s]

 13%|█▎        | 950/7491 [04:23<37:29,  2.91it/s]

 13%|█▎        | 950/7491 [04:23<37:29,  2.91it/s]
 13%|█▎        | 951/7491 [04:23<37:29,  2.91it/s]
 13%|█▎        | 952/7491 [04:23<37:29,  2.91it/s]

 13%|█▎        | 953/7491 [04:23<31:47,  3.43it/s]

 13%|█▎        | 953/7491 [04:23<31:47,  3.43it/s]
 13%|█▎        | 954/7491 [04:23<31:47,  3.43it/s]

 13%|█▎        | 955/7491 [04:24<32:04,  3.40it/s]

 13%|█▎        | 955/7491 [04:24<32:04,  3.40it/s]
 13%|█▎        | 956/7491 [04:24<32:04,  3.40it/s]

 13%|█▎        | 957/7491 [04:24<31:53,  3.42it/s]

 13%|█▎        | 957/7491 [04:24<31:53,  3.42it/s]
 13%|█▎        | 958/7491 [04:24<31:52,  3.42it/s]

 13%|█▎        | 959/7491 [04:25<32:12,  3.38it/s]

 13%|█▎        | 959/7491 [04:25<32:12,  3.38it/s]
 13%|█▎        | 960/7491 [04:25<32:12,  3.38it/s]

 13%|█▎        | 961/7491 [04:26<31:47,  3.42it/s]

 13%|█▎        | 961/7491 [04:26<31:47,  3.42it/s]
 13%|█▎        | 962/7491 [04:26<31:47,  3.42it/s]

 13%|█▎        | 963/7491 [04:26<32:08,  3.39it/s]

 13%|█▎        | 963/7491 [04:26<32:08,  3.39it/s]
 13%|█▎        | 964/7491 [04:26<32:07,  3.39it/s]

 13%|█▎        | 965/7491 [04:27<31:42,  3.43it/s]

 13%|█▎        | 965/7491 [04:27<31:42,  3.43it/s]
 13%|█▎        | 966/7491 [04:27<31:42,  3.43it/s]

 13%|█▎        | 967/7491 [04:27<31:55,  3.41it/s]

 13%|█▎        | 967/7491 [04:27<31:55,  3.41it/s]
 13%|█▎        | 968/7491 [04:27<31:55,  3.41it/s]

 13%|█▎        | 969/7491 [04:28<31:54,  3.41it/s]

 13%|█▎        | 969/7491 [04:28<31:54,  3.41it/s]
 13%|█▎        | 970/7491 [04:28<31:54,  3.41it/s]

 13%|█▎        | 971/7491 [04:29<32:03,  3.39it/s]

 13%|█▎        | 971/7491 [04:29<32:03,  3.39it/s]
 13%|█▎        | 972/7491 [04:29<32:03,  3.39it/s]
 13%|█▎        | 973/7491 [04:29<32:03,  3.39it/s]
 13%|█▎        | 974/7491 [04:29<32:02,  3.39it/s]
 13%|█▎        | 975/7491 [04:29<32:02,  3.39it/s]
 13%|█▎        | 976/7491 [04:29<32:02,  3.39it/s]
 13%|█▎        | 977/7491 [04:29<32:01,  3.39it/s]
 13%|█▎        | 978/7491 [04:29<32:01,  3.39it/s]

 13%|█▎        | 979/7491 [04:32<37:21,  2.91it/s]

 13%|█▎        | 979/7491 [04:32<37:21,  2.91it/s]
 13%|█▎        | 980/7491 [04:32<37:21,  2.91it/s]
 13%|█▎        | 981/7491 [04:32<37:20,  2.91it/s]
 13%|█▎        | 982/7491 [04:32<37:20,  2.91it/s]

 13%|█▎        | 983/7491 [04:32<30:24,  3.57it/s]

 13%|█▎        | 983/7491 [04:32<30:24,  3.57it/s]
 13%|█▎        | 984/7491 [04:32<30:24,  3.57it/s]

 13%|█▎        | 985/7491 [04:33<30:46,  3.52it/s]

 13%|█▎        | 985/7491 [04:33<30:46,  3.52it/s]
 13%|█▎        | 986/7491 [04:33<30:46,  3.52it/s]

 13%|█▎        | 987/7491 [04:33<31:25,  3.45it/s]

 13%|█▎        | 987/7491 [04:33<31:25,  3.45it/s]
 13%|█▎        | 988/7491 [04:33<31:25,  3.45it/s]

 13%|█▎        | 989/7491 [04:34<31:26,  3.45it/s]

 13%|█▎        | 989/7491 [04:34<31:26,  3.45it/s]
 13%|█▎        | 990/7491 [04:34<31:26,  3.45it/s]

 13%|█▎        | 991/7491 [04:35<31:44,  3.41it/s]

 13%|█▎        | 991/7491 [04:35<31:44,  3.41it/s]
 13%|█▎        | 992/7491 [04:35<31:43,  3.41it/s]
 13%|█▎        | 993/7491 [04:35<31:43,  3.41it/s]

 13%|█▎        | 994/7491 [04:35<27:58,  3.87it/s]

 13%|█▎        | 994/7491 [04:35<27:58,  3.87it/s]
 13%|█▎        | 995/7491 [04:35<27:58,  3.87it/s]

 13%|█▎        | 996/7491 [04:36<29:09,  3.71it/s]

 13%|█▎        | 996/7491 [04:36<29:09,  3.71it/s]
 13%|█▎        | 997/7491 [04:36<29:09,  3.71it/s]

 13%|█▎        | 998/7491 [04:36<29:46,  3.63it/s]

 13%|█▎        | 998/7491 [04:36<29:46,  3.63it/s]
 13%|█▎        | 999/7491 [04:36<29:46,  3.63it/s]

 13%|█▎        | 1000/7491 [04:37<30:00,  3.60it/s]
 22%|██▏       | 2/9 [09:10<32:15, 276.46s/it]

 13%|█▎        | 1000/7491 [04:37<30:46,  3.52it/s]
                     MLUT4_AT.232A  MLUT4_RQ.2BTLS  MLUT4_TE.252A  \
Time
2025-05-25 05:20:05       0.852984        0.855904       0.842414
2025-05-25 05:30:05       0.876511        0.874611       0.847393
2025-05-25 05:35:05       0.877479        0.885625       0.860507
2025-05-25 05:40:05       0.878625        0.849563       0.860377
2025-05-25 05:45:05       0.877141        0.871733       0.849503

                     MLUT4_SIV.B7921  MLUT4_AIA792101B  MLUT4_PDT.956  \
Time
2025-05-25 05:20:05         0.903258          0.872434       0.899219
2025-05-25 05:30:05         0.903158          0.872244       0.916372
2025-05-25 05:35:05         0.903349          0.872158       0.914016
2025-05-25 05:40:05         0.903300          0.872148       0.910043
2025-05-25 05:45:05         0.903219          0.872148       0.914286

                     MLUT4_TE.252F  MLUT4_PT.231  MLUT4_FIC.231C  \
Time
2025-05-25 05:20:05       0.887579      0.869354        0.857897
2025-05-25 05:30:05       0.879727      0.867235        0.857888
2025-05-25 05:35:05       0.893944      0.867041        0.857883
2025-05-25 05:40:05       0.872940      0.866275        0.857879
2025-05-25 05:45:05       0.876962      0.865383        0.857874

                     MLUT4_FIC.231A  ...  DeSOx_2nd  MLUT4_AIC.232B  \
Time                                 ...
2025-05-25 05:20:05        0.859975  ...   0.890380       85.012138
2025-05-25 05:30:05        0.856716  ...   0.890383       88.954571
2025-05-25 05:35:05        0.860662  ...   0.890764       93.745851
2025-05-25 05:40:05        0.859286  ...   0.890592       85.305571
2025-05-25 05:45:05        0.859582  ...   0.889551      101.874866

                     MLUT4_AT.240  prev_target  MLUT4_AT-240  prediction  \
Time
2025-05-25 05:20:05     14.151761     0.888806      9.319026    0.888496
2025-05-25 05:30:05      9.316637     0.890104      9.750918    0.887446
2025-05-25 05:35:05      6.155893     0.890862     10.240433    0.889025
2025-05-25 05:40:05     12.572007     0.891577      9.333126    0.889974
2025-05-25 05:45:05      5.497275     0.891864     11.251932    0.885925

                     abs_error  threshold  y3_prediction  y3_abs_error
Time
2025-05-25 05:20:05   0.001884   0.001884       9.479185      0.160159
2025-05-25 05:30:05   0.002937   0.002832      10.012178      0.261260
2025-05-25 05:35:05   0.001739   0.001739      10.403460      0.163026
2025-05-25 05:40:05   0.000618   0.001627       9.385821      0.052695
2025-05-25 05:45:05   0.003627   0.003249      11.621382      0.369450

[5 rows x 50 columns]

  0%|          | 0/7488 [00:00<?, ?it/s]

  0%|          | 0/7488 [00:00<?, ?it/s]

  0%|          | 1/7488 [00:01<4:08:51,  1.99s/it]

  0%|          | 1/7488 [00:01<4:08:51,  1.99s/it]
  0%|          | 2/7488 [00:02<4:08:49,  1.99s/it]

  0%|          | 3/7488 [00:02<1:30:40,  1.38it/s]

  0%|          | 3/7488 [00:02<1:30:40,  1.38it/s]
  0%|          | 4/7488 [00:02<1:30:39,  1.38it/s]
  0%|          | 5/7488 [00:02<1:30:38,  1.38it/s]
  0%|          | 6/7488 [00:02<1:30:38,  1.38it/s]
  0%|          | 7/7488 [00:02<1:30:37,  1.38it/s]
  0%|          | 8/7488 [00:02<1:30:36,  1.38it/s]
  0%|          | 9/7488 [00:02<1:30:36,  1.38it/s]
  0%|          | 10/7488 [00:02<1:30:35,  1.38it/s]
  0%|          | 11/7488 [00:02<1:30:34,  1.38it/s]
  0%|          | 12/7488 [00:02<1:30:33,  1.38it/s]

  0%|          | 13/7488 [00:03<20:03,  6.21it/s]

  0%|          | 13/7488 [00:03<20:03,  6.21it/s]
  0%|          | 14/7488 [00:03<20:02,  6.21it/s]
  0%|          | 15/7488 [00:03<20:02,  6.21it/s]
  0%|          | 16/7488 [00:03<20:02,  6.21it/s]
  0%|          | 17/7488 [00:03<20:02,  6.21it/s]

  0%|          | 18/7488 [00:03<17:34,  7.09it/s]

  0%|          | 18/7488 [00:03<17:34,  7.09it/s]
  0%|          | 19/7488 [00:03<17:34,  7.09it/s]

  0%|          | 20/7488 [00:04<20:05,  6.20it/s]

  0%|          | 20/7488 [00:04<20:05,  6.20it/s]
  0%|          | 21/7488 [00:04<20:04,  6.20it/s]

  0%|          | 22/7488 [00:04<22:47,  5.46it/s]

  0%|          | 22/7488 [00:04<22:47,  5.46it/s]
  0%|          | 23/7488 [00:04<22:47,  5.46it/s]

  0%|          | 24/7488 [00:05<25:02,  4.97it/s]

  0%|          | 24/7488 [00:05<25:02,  4.97it/s]
  0%|          | 25/7488 [00:05<25:02,  4.97it/s]

  0%|          | 26/7488 [00:05<27:06,  4.59it/s]

  0%|          | 26/7488 [00:05<27:06,  4.59it/s]
  0%|          | 27/7488 [00:05<27:05,  4.59it/s]

  0%|          | 28/7488 [00:06<28:09,  4.42it/s]

  0%|          | 28/7488 [00:06<28:09,  4.42it/s]
  0%|          | 29/7488 [00:06<28:08,  4.42it/s]

  0%|          | 30/7488 [00:06<29:40,  4.19it/s]

  0%|          | 30/7488 [00:06<29:40,  4.19it/s]
  0%|          | 31/7488 [00:06<29:39,  4.19it/s]
  0%|          | 32/7488 [00:06<29:39,  4.19it/s]
  0%|          | 33/7488 [00:06<29:39,  4.19it/s]

  0%|          | 34/7488 [00:07<23:44,  5.23it/s]

  0%|          | 34/7488 [00:07<23:44,  5.23it/s]
  0%|          | 35/7488 [00:07<23:44,  5.23it/s]

  0%|          | 36/7488 [00:07<26:16,  4.73it/s]

  0%|          | 36/7488 [00:07<26:16,  4.73it/s]
  0%|          | 37/7488 [00:07<26:15,  4.73it/s]
  1%|          | 38/7488 [00:07<26:15,  4.73it/s]

  1%|          | 39/7488 [00:08<24:33,  5.06it/s]

  1%|          | 39/7488 [00:08<24:33,  5.06it/s]
  1%|          | 40/7488 [00:08<24:33,  5.06it/s]

  1%|          | 41/7488 [00:08<26:46,  4.63it/s]

  1%|          | 41/7488 [00:08<26:46,  4.63it/s]
  1%|          | 42/7488 [00:08<26:46,  4.63it/s]

  1%|          | 43/7488 [00:09<28:12,  4.40it/s]

  1%|          | 43/7488 [00:09<28:12,  4.40it/s]
  1%|          | 44/7488 [00:09<28:12,  4.40it/s]

  1%|          | 45/7488 [00:10<29:44,  4.17it/s]

  1%|          | 45/7488 [00:10<29:44,  4.17it/s]
  1%|          | 46/7488 [00:10<29:44,  4.17it/s]
  1%|          | 47/7488 [00:10<29:44,  4.17it/s]

  1%|          | 48/7488 [00:10<26:35,  4.66it/s]

  1%|          | 48/7488 [00:10<26:35,  4.66it/s]
  1%|          | 49/7488 [00:10<26:35,  4.66it/s]

  1%|          | 50/7488 [00:11<28:18,  4.38it/s]

  1%|          | 50/7488 [00:11<28:18,  4.38it/s]
  1%|          | 51/7488 [00:11<28:17,  4.38it/s]
  1%|          | 52/7488 [00:11<28:17,  4.38it/s]

  1%|          | 53/7488 [00:11<25:36,  4.84it/s]

  1%|          | 53/7488 [00:11<25:36,  4.84it/s]
  1%|          | 54/7488 [00:11<25:36,  4.84it/s]

  1%|          | 55/7488 [00:14<1:04:13,  1.93it/s]

  1%|          | 55/7488 [00:14<1:04:13,  1.93it/s]
  1%|          | 56/7488 [00:14<1:04:12,  1.93it/s]

  1%|          | 57/7488 [00:14<56:10,  2.20it/s]

  1%|          | 57/7488 [00:14<56:10,  2.20it/s]
  1%|          | 58/7488 [00:14<56:09,  2.20it/s]
  1%|          | 59/7488 [00:14<56:09,  2.20it/s]
  1%|          | 60/7488 [00:14<56:08,  2.20it/s]
  1%|          | 61/7488 [00:15<56:08,  2.20it/s]

  1%|          | 62/7488 [00:15<35:04,  3.53it/s]

  1%|          | 62/7488 [00:15<35:04,  3.53it/s]
  1%|          | 63/7488 [00:15<35:03,  3.53it/s]

  1%|          | 64/7488 [00:16<35:03,  3.53it/s]

  1%|          | 64/7488 [00:16<35:03,  3.53it/s]
  1%|          | 65/7488 [00:16<35:03,  3.53it/s]

  1%|          | 66/7488 [00:16<34:14,  3.61it/s]

  1%|          | 66/7488 [00:16<34:14,  3.61it/s]
  1%|          | 67/7488 [00:16<34:14,  3.61it/s]

  1%|          | 68/7488 [00:17<34:14,  3.61it/s]

  1%|          | 68/7488 [00:17<34:14,  3.61it/s]
  1%|          | 69/7488 [00:17<34:13,  3.61it/s]

  1%|          | 70/7488 [00:17<33:48,  3.66it/s]

  1%|          | 70/7488 [00:17<33:48,  3.66it/s]
  1%|          | 71/7488 [00:17<33:48,  3.66it/s]
  1%|          | 72/7488 [00:17<33:47,  3.66it/s]

  1%|          | 73/7488 [00:18<29:55,  4.13it/s]

  1%|          | 73/7488 [00:18<29:55,  4.13it/s]
  1%|          | 74/7488 [00:18<29:54,  4.13it/s]

  1%|          | 75/7488 [00:18<30:27,  4.06it/s]

  1%|          | 75/7488 [00:18<30:27,  4.06it/s]
  1%|          | 76/7488 [00:18<30:27,  4.06it/s]

  1%|          | 77/7488 [00:19<31:40,  3.90it/s]

  1%|          | 77/7488 [00:19<31:40,  3.90it/s]
  1%|          | 78/7488 [00:19<31:40,  3.90it/s]

  1%|          | 79/7488 [00:19<32:02,  3.85it/s]

  1%|          | 79/7488 [00:19<32:02,  3.85it/s]
  1%|          | 80/7488 [00:19<32:02,  3.85it/s]

  1%|          | 81/7488 [00:20<33:12,  3.72it/s]

  1%|          | 81/7488 [00:20<33:12,  3.72it/s]
  1%|          | 82/7488 [00:20<33:12,  3.72it/s]

  1%|          | 83/7488 [00:21<34:20,  3.59it/s]

  1%|          | 83/7488 [00:21<34:20,  3.59it/s]
  1%|          | 84/7488 [00:21<34:20,  3.59it/s]
  1%|          | 85/7488 [00:21<34:20,  3.59it/s]

  1%|          | 86/7488 [00:21<31:33,  3.91it/s]

  1%|          | 86/7488 [00:21<31:33,  3.91it/s]
  1%|          | 87/7488 [00:21<31:33,  3.91it/s]

  1%|          | 88/7488 [00:22<34:02,  3.62it/s]

  1%|          | 88/7488 [00:22<34:02,  3.62it/s]
  1%|          | 89/7488 [00:22<34:01,  3.62it/s]

  1%|          | 90/7488 [00:22<35:37,  3.46it/s]

  1%|          | 90/7488 [00:23<35:37,  3.46it/s]
  1%|          | 91/7488 [00:23<35:37,  3.46it/s]

  1%|          | 92/7488 [00:23<36:45,  3.35it/s]

  1%|          | 92/7488 [00:23<36:45,  3.35it/s]
  1%|          | 93/7488 [00:23<36:45,  3.35it/s]

  1%|▏         | 94/7488 [00:24<36:54,  3.34it/s]

  1%|▏         | 94/7488 [00:24<36:54,  3.34it/s]
  1%|▏         | 95/7488 [00:24<36:54,  3.34it/s]

  1%|▏         | 96/7488 [00:27<1:18:41,  1.57it/s]

  1%|▏         | 96/7488 [00:27<1:18:41,  1.57it/s]
  1%|▏         | 97/7488 [00:27<1:18:41,  1.57it/s]

  1%|▏         | 98/7488 [00:27<1:06:59,  1.84it/s]

  1%|▏         | 98/7488 [00:27<1:06:59,  1.84it/s]
  1%|▏         | 99/7488 [00:27<1:06:59,  1.84it/s]

  1%|▏         | 100/7488 [00:28<58:53,  2.09it/s]

  1%|▏         | 100/7488 [00:28<58:53,  2.09it/s]
  1%|▏         | 101/7488 [00:28<58:53,  2.09it/s]

  1%|▏         | 102/7488 [00:29<52:56,  2.32it/s]

  1%|▏         | 102/7488 [00:29<52:56,  2.32it/s]
  1%|▏         | 103/7488 [00:29<52:56,  2.32it/s]

  1%|▏         | 104/7488 [00:29<48:49,  2.52it/s]

  1%|▏         | 104/7488 [00:29<48:49,  2.52it/s]
  1%|▏         | 105/7488 [00:29<48:48,  2.52it/s]
  1%|▏         | 106/7488 [00:29<48:48,  2.52it/s]

  1%|▏         | 107/7488 [00:30<39:11,  3.14it/s]

  1%|▏         | 107/7488 [00:30<39:11,  3.14it/s]
  1%|▏         | 108/7488 [00:30<39:11,  3.14it/s]

  1%|▏         | 109/7488 [00:30<39:07,  3.14it/s]

  1%|▏         | 109/7488 [00:30<39:07,  3.14it/s]
  1%|▏         | 110/7488 [00:30<39:06,  3.14it/s]
  1%|▏         | 111/7488 [00:30<39:06,  3.14it/s]

  1%|▏         | 112/7488 [00:31<33:23,  3.68it/s]

  1%|▏         | 112/7488 [00:31<33:23,  3.68it/s]
  2%|▏         | 113/7488 [00:31<33:23,  3.68it/s]

  2%|▏         | 114/7488 [00:32<34:39,  3.55it/s]

  2%|▏         | 114/7488 [00:32<34:39,  3.55it/s]
  2%|▏         | 115/7488 [00:32<34:39,  3.55it/s]

  2%|▏         | 116/7488 [00:32<35:30,  3.46it/s]

  2%|▏         | 116/7488 [00:32<35:30,  3.46it/s]
  2%|▏         | 117/7488 [00:32<35:30,  3.46it/s]
  2%|▏         | 118/7488 [00:32<35:30,  3.46it/s]

  2%|▏         | 119/7488 [00:33<31:27,  3.90it/s]

  2%|▏         | 119/7488 [00:33<31:27,  3.90it/s]
  2%|▏         | 120/7488 [00:33<31:27,  3.90it/s]

  2%|▏         | 121/7488 [00:33<33:00,  3.72it/s]

  2%|▏         | 121/7488 [00:33<33:00,  3.72it/s]
  2%|▏         | 122/7488 [00:33<32:59,  3.72it/s]

  2%|▏         | 123/7488 [00:34<34:02,  3.61it/s]

  2%|▏         | 123/7488 [00:34<34:02,  3.61it/s]
  2%|▏         | 124/7488 [00:34<34:02,  3.61it/s]

  2%|▏         | 125/7488 [00:35<35:07,  3.49it/s]

  2%|▏         | 125/7488 [00:35<35:07,  3.49it/s]
  2%|▏         | 126/7488 [00:35<35:07,  3.49it/s]

  2%|▏         | 127/7488 [00:35<35:04,  3.50it/s]

  2%|▏         | 127/7488 [00:35<35:04,  3.50it/s]
  2%|▏         | 128/7488 [00:35<35:03,  3.50it/s]

  2%|▏         | 129/7488 [00:36<35:41,  3.44it/s]

  2%|▏         | 129/7488 [00:36<35:41,  3.44it/s]
  2%|▏         | 130/7488 [00:36<35:40,  3.44it/s]
  2%|▏         | 131/7488 [00:36<35:40,  3.44it/s]

  2%|▏         | 132/7488 [00:36<31:56,  3.84it/s]

  2%|▏         | 132/7488 [00:36<31:56,  3.84it/s]
  2%|▏         | 133/7488 [00:37<31:56,  3.84it/s]
  2%|▏         | 134/7488 [00:37<31:56,  3.84it/s]

  2%|▏         | 135/7488 [00:39<1:01:04,  2.01it/s]

  2%|▏         | 135/7488 [00:39<1:01:04,  2.01it/s]
  2%|▏         | 136/7488 [00:39<1:01:03,  2.01it/s]
  2%|▏         | 137/7488 [00:39<1:01:03,  2.01it/s]
  2%|▏         | 138/7488 [00:39<1:01:02,  2.01it/s]
  2%|▏         | 139/7488 [00:39<1:01:02,  2.01it/s]
  2%|▏         | 140/7488 [00:39<1:01:01,  2.01it/s]
  2%|▏         | 141/7488 [00:39<1:01:01,  2.01it/s]

  2%|▏         | 142/7488 [00:40<33:36,  3.64it/s]

  2%|▏         | 142/7488 [00:40<33:36,  3.64it/s]
  2%|▏         | 143/7488 [00:40<33:36,  3.64it/s]

  2%|▏         | 144/7488 [00:40<33:45,  3.63it/s]

  2%|▏         | 144/7488 [00:40<33:45,  3.63it/s]
  2%|▏         | 145/7488 [00:40<33:45,  3.63it/s]

  2%|▏         | 146/7488 [00:41<34:03,  3.59it/s]

  2%|▏         | 146/7488 [00:41<34:03,  3.59it/s]
  2%|▏         | 147/7488 [00:41<34:03,  3.59it/s]

  2%|▏         | 148/7488 [00:42<34:12,  3.58it/s]

  2%|▏         | 148/7488 [00:42<34:12,  3.58it/s]
  2%|▏         | 149/7488 [00:42<34:12,  3.58it/s]

  2%|▏         | 150/7488 [00:42<35:09,  3.48it/s]

  2%|▏         | 150/7488 [00:42<35:09,  3.48it/s]
  2%|▏         | 151/7488 [00:42<35:09,  3.48it/s]
  2%|▏         | 152/7488 [00:42<35:09,  3.48it/s]
  2%|▏         | 153/7488 [00:42<35:08,  3.48it/s]
  2%|▏         | 154/7488 [00:42<35:08,  3.48it/s]
  2%|▏         | 155/7488 [00:42<35:08,  3.48it/s]
  2%|▏         | 156/7488 [00:42<35:07,  3.48it/s]
  2%|▏         | 157/7488 [00:42<35:07,  3.48it/s]
  2%|▏         | 158/7488 [00:42<35:07,  3.48it/s]

  2%|▏         | 159/7488 [00:43<18:50,  6.48it/s]

  2%|▏         | 159/7488 [00:43<18:50,  6.48it/s]
  2%|▏         | 160/7488 [00:43<18:50,  6.48it/s]

  2%|▏         | 161/7488 [00:43<21:29,  5.68it/s]

  2%|▏         | 161/7488 [00:43<21:29,  5.68it/s]
  2%|▏         | 162/7488 [00:43<21:29,  5.68it/s]

  2%|▏         | 163/7488 [00:44<24:18,  5.02it/s]

  2%|▏         | 163/7488 [00:44<24:18,  5.02it/s]
  2%|▏         | 164/7488 [00:44<24:18,  5.02it/s]

  2%|▏         | 165/7488 [00:45<26:50,  4.55it/s]

  2%|▏         | 165/7488 [00:45<26:50,  4.55it/s]
  2%|▏         | 166/7488 [00:45<26:50,  4.55it/s]

  2%|▏         | 167/7488 [00:45<29:28,  4.14it/s]

  2%|▏         | 167/7488 [00:45<29:28,  4.14it/s]
  2%|▏         | 168/7488 [00:45<29:27,  4.14it/s]

  2%|▏         | 169/7488 [00:46<31:09,  3.91it/s]

  2%|▏         | 169/7488 [00:46<31:09,  3.91it/s]
  2%|▏         | 170/7488 [00:46<31:09,  3.91it/s]

  2%|▏         | 171/7488 [00:46<33:03,  3.69it/s]

  2%|▏         | 171/7488 [00:46<33:03,  3.69it/s]
  2%|▏         | 172/7488 [00:46<33:03,  3.69it/s]
  2%|▏         | 173/7488 [00:46<33:02,  3.69it/s]

  2%|▏         | 174/7488 [00:47<30:26,  4.01it/s]

  2%|▏         | 174/7488 [00:47<30:26,  4.01it/s]
  2%|▏         | 175/7488 [00:47<30:25,  4.01it/s]

  2%|▏         | 176/7488 [00:48<32:12,  3.78it/s]

  2%|▏         | 176/7488 [00:48<32:12,  3.78it/s]
  2%|▏         | 177/7488 [00:48<32:11,  3.78it/s]

  2%|▏         | 178/7488 [00:48<34:07,  3.57it/s]

  2%|▏         | 178/7488 [00:48<34:07,  3.57it/s]
  2%|▏         | 179/7488 [00:48<34:07,  3.57it/s]

  2%|▏         | 180/7488 [00:49<34:45,  3.50it/s]

  2%|▏         | 180/7488 [00:49<34:45,  3.50it/s]
  2%|▏         | 181/7488 [00:49<34:45,  3.50it/s]

  2%|▏         | 182/7488 [00:52<1:15:41,  1.61it/s]

  2%|▏         | 182/7488 [00:52<1:15:41,  1.61it/s]
  2%|▏         | 183/7488 [00:52<1:15:40,  1.61it/s]
  2%|▏         | 184/7488 [00:52<1:15:40,  1.61it/s]

  2%|▏         | 185/7488 [00:53<56:53,  2.14it/s]

  2%|▏         | 185/7488 [00:53<56:53,  2.14it/s]
  2%|▏         | 186/7488 [00:53<56:52,  2.14it/s]
  2%|▏         | 187/7488 [00:53<56:52,  2.14it/s]
  3%|▎         | 188/7488 [00:53<56:51,  2.14it/s]
  3%|▎         | 189/7488 [00:53<56:51,  2.14it/s]

  3%|▎         | 190/7488 [00:53<36:46,  3.31it/s]

  3%|▎         | 190/7488 [00:53<36:46,  3.31it/s]
  3%|▎         | 191/7488 [00:53<36:45,  3.31it/s]

  3%|▎         | 192/7488 [00:54<36:46,  3.31it/s]

  3%|▎         | 192/7488 [00:54<36:46,  3.31it/s]
  3%|▎         | 193/7488 [00:54<36:46,  3.31it/s]

  3%|▎         | 194/7488 [00:54<37:04,  3.28it/s]

  3%|▎         | 194/7488 [00:54<37:04,  3.28it/s]
  3%|▎         | 195/7488 [00:54<37:04,  3.28it/s]
  3%|▎         | 196/7488 [00:54<37:03,  3.28it/s]

  3%|▎         | 197/7488 [00:55<32:42,  3.72it/s]

  3%|▎         | 197/7488 [00:55<32:42,  3.72it/s]
  3%|▎         | 198/7488 [00:55<32:41,  3.72it/s]

  3%|▎         | 199/7488 [00:56<34:19,  3.54it/s]

  3%|▎         | 199/7488 [00:56<34:19,  3.54it/s]
  3%|▎         | 200/7488 [00:56<34:18,  3.54it/s]

  3%|▎         | 201/7488 [00:56<35:07,  3.46it/s]

  3%|▎         | 201/7488 [00:56<35:07,  3.46it/s]
  3%|▎         | 202/7488 [00:56<35:07,  3.46it/s]

  3%|▎         | 203/7488 [00:57<36:06,  3.36it/s]

  3%|▎         | 203/7488 [00:57<36:06,  3.36it/s]
  3%|▎         | 204/7488 [00:57<36:05,  3.36it/s]
  3%|▎         | 205/7488 [00:57<36:05,  3.36it/s]
  3%|▎         | 206/7488 [00:57<36:05,  3.36it/s]
  3%|▎         | 207/7488 [00:57<36:04,  3.36it/s]
  3%|▎         | 208/7488 [00:57<36:04,  3.36it/s]
  3%|▎         | 209/7488 [00:57<36:04,  3.36it/s]
  3%|▎         | 210/7488 [00:57<36:04,  3.36it/s]
  3%|▎         | 211/7488 [00:57<36:03,  3.36it/s]
  3%|▎         | 212/7488 [00:57<36:03,  3.36it/s]
  3%|▎         | 213/7488 [00:57<36:03,  3.36it/s]
  3%|▎         | 214/7488 [00:57<36:02,  3.36it/s]
  3%|▎         | 215/7488 [00:57<36:02,  3.36it/s]
  3%|▎         | 216/7488 [00:57<36:02,  3.36it/s]
  3%|▎         | 217/7488 [00:57<36:02,  3.36it/s]

  3%|▎         | 218/7488 [00:58<13:16,  9.13it/s]

  3%|▎         | 218/7488 [00:58<13:16,  9.13it/s]
  3%|▎         | 219/7488 [00:58<13:16,  9.13it/s]

  3%|▎         | 220/7488 [00:58<16:45,  7.23it/s]

  3%|▎         | 220/7488 [00:58<16:45,  7.23it/s]
  3%|▎         | 221/7488 [00:58<16:45,  7.23it/s]

  3%|▎         | 222/7488 [00:59<20:10,  6.00it/s]

  3%|▎         | 222/7488 [00:59<20:10,  6.00it/s]
  3%|▎         | 223/7488 [00:59<20:10,  6.00it/s]

  3%|▎         | 224/7488 [00:59<23:20,  5.19it/s]

  3%|▎         | 224/7488 [00:59<23:20,  5.19it/s]
  3%|▎         | 225/7488 [00:59<23:20,  5.19it/s]

  3%|▎         | 226/7488 [01:00<26:32,  4.56it/s]

  3%|▎         | 226/7488 [01:00<26:32,  4.56it/s]
  3%|▎         | 227/7488 [01:00<26:31,  4.56it/s]

  3%|▎         | 228/7488 [01:01<29:35,  4.09it/s]

  3%|▎         | 228/7488 [01:01<29:35,  4.09it/s]
  3%|▎         | 229/7488 [01:01<29:35,  4.09it/s]
  3%|▎         | 230/7488 [01:01<29:34,  4.09it/s]
  3%|▎         | 231/7488 [01:01<29:34,  4.09it/s]
  3%|▎         | 232/7488 [01:01<29:34,  4.09it/s]

  3%|▎         | 233/7488 [01:01<23:08,  5.23it/s]

  3%|▎         | 233/7488 [01:01<23:08,  5.23it/s]
  3%|▎         | 234/7488 [01:01<23:08,  5.23it/s]
  3%|▎         | 235/7488 [01:01<23:07,  5.23it/s]
  3%|▎         | 236/7488 [01:01<23:07,  5.23it/s]

  3%|▎         | 237/7488 [01:04<45:09,  2.68it/s]

  3%|▎         | 237/7488 [01:04<45:09,  2.68it/s]
  3%|▎         | 238/7488 [01:04<45:09,  2.68it/s]
  3%|▎         | 239/7488 [01:04<45:08,  2.68it/s]

  3%|▎         | 240/7488 [01:05<40:15,  3.00it/s]

  3%|▎         | 240/7488 [01:05<40:15,  3.00it/s]
  3%|▎         | 241/7488 [01:05<40:15,  3.00it/s]

  3%|▎         | 242/7488 [01:06<39:38,  3.05it/s]

  3%|▎         | 242/7488 [01:06<39:38,  3.05it/s]
  3%|▎         | 243/7488 [01:06<39:38,  3.05it/s]

  3%|▎         | 244/7488 [01:06<39:45,  3.04it/s]

  3%|▎         | 244/7488 [01:06<39:45,  3.04it/s]
  3%|▎         | 245/7488 [01:06<39:44,  3.04it/s]

  3%|▎         | 246/7488 [01:07<39:10,  3.08it/s]

  3%|▎         | 246/7488 [01:07<39:10,  3.08it/s]
  3%|▎         | 247/7488 [01:07<39:10,  3.08it/s]

  3%|▎         | 248/7488 [01:08<39:08,  3.08it/s]

  3%|▎         | 248/7488 [01:08<39:08,  3.08it/s]
  3%|▎         | 249/7488 [01:08<39:08,  3.08it/s]
  3%|▎         | 250/7488 [01:08<39:07,  3.08it/s]
  3%|▎         | 251/7488 [01:08<39:07,  3.08it/s]
  3%|▎         | 252/7488 [01:08<39:07,  3.08it/s]
  3%|▎         | 253/7488 [01:08<39:06,  3.08it/s]
  3%|▎         | 254/7488 [01:08<39:06,  3.08it/s]

  3%|▎         | 255/7488 [01:08<23:17,  5.18it/s]

  3%|▎         | 255/7488 [01:08<23:17,  5.18it/s]
  3%|▎         | 256/7488 [01:08<23:16,  5.18it/s]

  3%|▎         | 257/7488 [01:09<25:32,  4.72it/s]

  3%|▎         | 257/7488 [01:09<25:32,  4.72it/s]
  3%|▎         | 258/7488 [01:09<25:31,  4.72it/s]

  3%|▎         | 259/7488 [01:09<27:54,  4.32it/s]

  3%|▎         | 259/7488 [01:09<27:54,  4.32it/s]
  3%|▎         | 260/7488 [01:09<27:54,  4.32it/s]

  3%|▎         | 261/7488 [01:10<29:21,  4.10it/s]

  3%|▎         | 261/7488 [01:10<29:21,  4.10it/s]
  3%|▎         | 262/7488 [01:10<29:20,  4.10it/s]

  4%|▎         | 263/7488 [01:11<31:11,  3.86it/s]

  4%|▎         | 263/7488 [01:11<31:11,  3.86it/s]
  4%|▎         | 264/7488 [01:11<31:11,  3.86it/s]

  4%|▎         | 265/7488 [01:11<32:43,  3.68it/s]

  4%|▎         | 265/7488 [01:11<32:43,  3.68it/s]
  4%|▎         | 266/7488 [01:11<32:43,  3.68it/s]
  4%|▎         | 267/7488 [01:11<32:43,  3.68it/s]

  4%|▎         | 268/7488 [01:12<29:33,  4.07it/s]

  4%|▎         | 268/7488 [01:12<29:33,  4.07it/s]
  4%|▎         | 269/7488 [01:12<29:32,  4.07it/s]

  4%|▎         | 270/7488 [01:12<31:29,  3.82it/s]

  4%|▎         | 270/7488 [01:12<31:29,  3.82it/s]
  4%|▎         | 271/7488 [01:12<31:29,  3.82it/s]

  4%|▎         | 272/7488 [01:13<32:23,  3.71it/s]

  4%|▎         | 272/7488 [01:13<32:23,  3.71it/s]
  4%|▎         | 273/7488 [01:13<32:23,  3.71it/s]
  4%|▎         | 274/7488 [01:13<32:23,  3.71it/s]
  4%|▎         | 275/7488 [01:13<32:22,  3.71it/s]
  4%|▎         | 276/7488 [01:13<32:22,  3.71it/s]

  4%|▎         | 277/7488 [01:14<24:10,  4.97it/s]

  4%|▎         | 277/7488 [01:14<24:10,  4.97it/s]
  4%|▎         | 278/7488 [01:14<24:10,  4.97it/s]

  4%|▎         | 279/7488 [01:14<28:33,  4.21it/s]

  4%|▎         | 279/7488 [01:14<28:33,  4.21it/s]
  4%|▎         | 280/7488 [01:14<28:33,  4.21it/s]

  4%|▍         | 281/7488 [01:17<1:01:20,  1.96it/s]

  4%|▍         | 281/7488 [01:17<1:01:20,  1.96it/s]
  4%|▍         | 282/7488 [01:17<1:01:20,  1.96it/s]

  4%|▍         | 283/7488 [01:18<55:49,  2.15it/s]

  4%|▍         | 283/7488 [01:18<55:49,  2.15it/s]
  4%|▍         | 284/7488 [01:18<55:48,  2.15it/s]
  4%|▍         | 285/7488 [01:18<55:48,  2.15it/s]

  4%|▍         | 286/7488 [01:18<45:05,  2.66it/s]

  4%|▍         | 286/7488 [01:18<45:05,  2.66it/s]
  4%|▍         | 287/7488 [01:18<45:05,  2.66it/s]
  4%|▍         | 288/7488 [01:18<45:04,  2.66it/s]
  4%|▍         | 289/7488 [01:19<45:04,  2.66it/s]

  4%|▍         | 290/7488 [01:19<34:51,  3.44it/s]

  4%|▍         | 290/7488 [01:19<34:51,  3.44it/s]
  4%|▍         | 291/7488 [01:19<34:50,  3.44it/s]

  4%|▍         | 292/7488 [01:20<35:43,  3.36it/s]

  4%|▍         | 292/7488 [01:20<35:43,  3.36it/s]
  4%|▍         | 293/7488 [01:20<35:42,  3.36it/s]

  4%|▍         | 294/7488 [01:20<36:03,  3.32it/s]

  4%|▍         | 294/7488 [01:20<36:03,  3.32it/s]
  4%|▍         | 295/7488 [01:20<36:03,  3.32it/s]

  4%|▍         | 296/7488 [01:21<36:45,  3.26it/s]

  4%|▍         | 296/7488 [01:21<36:45,  3.26it/s]
  4%|▍         | 297/7488 [01:21<36:44,  3.26it/s]

  4%|▍         | 298/7488 [01:22<37:20,  3.21it/s]

  4%|▍         | 298/7488 [01:22<37:20,  3.21it/s]
  4%|▍         | 299/7488 [01:22<37:20,  3.21it/s]

  4%|▍         | 300/7488 [01:22<38:16,  3.13it/s]

  4%|▍         | 300/7488 [01:22<38:16,  3.13it/s]
  4%|▍         | 301/7488 [01:22<38:16,  3.13it/s]

  4%|▍         | 302/7488 [01:23<38:25,  3.12it/s]

  4%|▍         | 302/7488 [01:23<38:25,  3.12it/s]
  4%|▍         | 303/7488 [01:23<38:25,  3.12it/s]

  4%|▍         | 304/7488 [01:24<38:47,  3.09it/s]

  4%|▍         | 304/7488 [01:24<38:47,  3.09it/s]
  4%|▍         | 305/7488 [01:24<38:47,  3.09it/s]

  4%|▍         | 306/7488 [01:24<39:28,  3.03it/s]

  4%|▍         | 306/7488 [01:24<39:28,  3.03it/s]
  4%|▍         | 307/7488 [01:24<39:27,  3.03it/s]
  4%|▍         | 308/7488 [01:24<39:27,  3.03it/s]
  4%|▍         | 309/7488 [01:24<39:27,  3.03it/s]
  4%|▍         | 310/7488 [01:24<39:26,  3.03it/s]
  4%|▍         | 311/7488 [01:24<39:26,  3.03it/s]
  4%|▍         | 312/7488 [01:24<39:26,  3.03it/s]
  4%|▍         | 313/7488 [01:24<39:26,  3.03it/s]
  4%|▍         | 314/7488 [01:24<39:25,  3.03it/s]
  4%|▍         | 315/7488 [01:24<39:25,  3.03it/s]
  4%|▍         | 316/7488 [01:24<39:25,  3.03it/s]
  4%|▍         | 317/7488 [01:24<39:24,  3.03it/s]
  4%|▍         | 318/7488 [01:24<39:24,  3.03it/s]
  4%|▍         | 319/7488 [01:24<39:24,  3.03it/s]
  4%|▍         | 320/7488 [01:24<39:23,  3.03it/s]
  4%|▍         | 321/7488 [01:24<39:23,  3.03it/s]
  4%|▍         | 322/7488 [01:24<39:23,  3.03it/s]

  4%|▍         | 323/7488 [01:25<12:09,  9.83it/s]

  4%|▍         | 323/7488 [01:25<12:09,  9.83it/s]
  4%|▍         | 324/7488 [01:25<12:08,  9.83it/s]

  4%|▍         | 325/7488 [01:26<14:45,  8.09it/s]

  4%|▍         | 325/7488 [01:26<14:45,  8.09it/s]
  4%|▍         | 326/7488 [01:26<14:45,  8.09it/s]

  4%|▍         | 327/7488 [01:26<17:35,  6.79it/s]

  4%|▍         | 327/7488 [01:26<17:35,  6.79it/s]
  4%|▍         | 328/7488 [01:26<17:34,  6.79it/s]
  4%|▍         | 329/7488 [01:26<17:34,  6.79it/s]
  4%|▍         | 330/7488 [01:26<17:34,  6.79it/s]

  4%|▍         | 331/7488 [01:27<17:17,  6.90it/s]

  4%|▍         | 331/7488 [01:27<17:17,  6.90it/s]
  4%|▍         | 332/7488 [01:27<17:17,  6.90it/s]

  4%|▍         | 333/7488 [01:30<43:51,  2.72it/s]

  4%|▍         | 333/7488 [01:30<43:51,  2.72it/s]
  4%|▍         | 334/7488 [01:30<43:51,  2.72it/s]
  4%|▍         | 335/7488 [01:30<43:51,  2.72it/s]
  4%|▍         | 336/7488 [01:30<43:50,  2.72it/s]
  5%|▍         | 337/7488 [01:30<43:50,  2.72it/s]
  5%|▍         | 338/7488 [01:30<43:49,  2.72it/s]
  5%|▍         | 339/7488 [01:30<43:49,  2.72it/s]
  5%|▍         | 340/7488 [01:30<43:49,  2.72it/s]

  5%|▍         | 341/7488 [01:30<26:36,  4.48it/s]

  5%|▍         | 341/7488 [01:30<26:36,  4.48it/s]
  5%|▍         | 342/7488 [01:30<26:35,  4.48it/s]

  5%|▍         | 343/7488 [01:31<27:34,  4.32it/s]

  5%|▍         | 343/7488 [01:31<27:34,  4.32it/s]
  5%|▍         | 344/7488 [01:31<27:34,  4.32it/s]

  5%|▍         | 345/7488 [01:31<29:04,  4.09it/s]

  5%|▍         | 345/7488 [01:31<29:04,  4.09it/s]
  5%|▍         | 346/7488 [01:31<29:04,  4.09it/s]

  5%|▍         | 347/7488 [01:32<29:44,  4.00it/s]

  5%|▍         | 347/7488 [01:32<29:44,  4.00it/s]
  5%|▍         | 348/7488 [01:32<29:43,  4.00it/s]

  5%|▍         | 349/7488 [01:33<31:02,  3.83it/s]

  5%|▍         | 349/7488 [01:33<31:02,  3.83it/s]
  5%|▍         | 350/7488 [01:33<31:02,  3.83it/s]

  5%|▍         | 351/7488 [01:33<31:51,  3.73it/s]

  5%|▍         | 351/7488 [01:33<31:51,  3.73it/s]
  5%|▍         | 352/7488 [01:33<31:51,  3.73it/s]

  5%|▍         | 353/7488 [01:34<33:09,  3.59it/s]

  5%|▍         | 353/7488 [01:34<33:09,  3.59it/s]
  5%|▍         | 354/7488 [01:34<33:08,  3.59it/s]

  5%|▍         | 355/7488 [01:34<34:08,  3.48it/s]

  5%|▍         | 355/7488 [01:34<34:08,  3.48it/s]
  5%|▍         | 356/7488 [01:34<34:07,  3.48it/s]

  5%|▍         | 357/7488 [01:35<34:38,  3.43it/s]

  5%|▍         | 357/7488 [01:35<34:38,  3.43it/s]
  5%|▍         | 358/7488 [01:35<34:37,  3.43it/s]

  5%|▍         | 359/7488 [01:36<35:46,  3.32it/s]

  5%|▍         | 359/7488 [01:36<35:46,  3.32it/s]
  5%|▍         | 360/7488 [01:36<35:46,  3.32it/s]

  5%|▍         | 361/7488 [01:36<35:47,  3.32it/s]

  5%|▍         | 361/7488 [01:36<35:47,  3.32it/s]
  5%|▍         | 362/7488 [01:36<35:46,  3.32it/s]

  5%|▍         | 363/7488 [01:37<36:28,  3.26it/s]

  5%|▍         | 363/7488 [01:37<36:28,  3.26it/s]
  5%|▍         | 364/7488 [01:37<36:27,  3.26it/s]

  5%|▍         | 365/7488 [01:37<37:02,  3.20it/s]

  5%|▍         | 365/7488 [01:37<37:02,  3.20it/s]
  5%|▍         | 366/7488 [01:37<37:02,  3.20it/s]

  5%|▍         | 367/7488 [01:38<36:27,  3.26it/s]

  5%|▍         | 367/7488 [01:38<36:27,  3.26it/s]
  5%|▍         | 368/7488 [01:38<36:26,  3.26it/s]

  5%|▍         | 369/7488 [01:39<36:52,  3.22it/s]

  5%|▍         | 369/7488 [01:39<36:52,  3.22it/s]
  5%|▍         | 370/7488 [01:39<36:51,  3.22it/s]

  5%|▍         | 371/7488 [01:39<36:41,  3.23it/s]

  5%|▍         | 371/7488 [01:39<36:41,  3.23it/s]
  5%|▍         | 372/7488 [01:39<36:41,  3.23it/s]

  5%|▍         | 373/7488 [01:42<1:16:32,  1.55it/s]

  5%|▍         | 373/7488 [01:42<1:16:32,  1.55it/s]
  5%|▍         | 374/7488 [01:42<1:16:32,  1.55it/s]

  5%|▌         | 375/7488 [01:43<1:04:51,  1.83it/s]

  5%|▌         | 375/7488 [01:43<1:04:51,  1.83it/s]
  5%|▌         | 376/7488 [01:43<1:04:50,  1.83it/s]
  5%|▌         | 377/7488 [01:43<1:04:50,  1.83it/s]
  5%|▌         | 378/7488 [01:43<1:04:49,  1.83it/s]
  5%|▌         | 379/7488 [01:43<1:04:49,  1.83it/s]

  5%|▌         | 380/7488 [01:43<38:34,  3.07it/s]

  5%|▌         | 380/7488 [01:43<38:34,  3.07it/s]
  5%|▌         | 381/7488 [01:43<38:34,  3.07it/s]

  5%|▌         | 382/7488 [01:44<37:42,  3.14it/s]

  5%|▌         | 382/7488 [01:44<37:42,  3.14it/s]
  5%|▌         | 383/7488 [01:44<37:42,  3.14it/s]

  5%|▌         | 384/7488 [01:45<36:41,  3.23it/s]

  5%|▌         | 384/7488 [01:45<36:41,  3.23it/s]
  5%|▌         | 385/7488 [01:45<36:40,  3.23it/s]

  5%|▌         | 386/7488 [01:45<36:15,  3.26it/s]

  5%|▌         | 386/7488 [01:45<36:15,  3.26it/s]
  5%|▌         | 387/7488 [01:45<36:15,  3.26it/s]
  5%|▌         | 388/7488 [01:45<36:14,  3.26it/s]
  5%|▌         | 389/7488 [01:45<36:14,  3.26it/s]
  5%|▌         | 390/7488 [01:45<36:14,  3.26it/s]
  5%|▌         | 391/7488 [01:45<36:13,  3.26it/s]

  5%|▌         | 392/7488 [01:46<23:10,  5.10it/s]

  5%|▌         | 392/7488 [01:46<23:10,  5.10it/s]
  5%|▌         | 393/7488 [01:46<23:10,  5.10it/s]

  5%|▌         | 394/7488 [01:46<25:35,  4.62it/s]

  5%|▌         | 394/7488 [01:46<25:35,  4.62it/s]
  5%|▌         | 395/7488 [01:46<25:34,  4.62it/s]

  5%|▌         | 396/7488 [01:47<27:26,  4.31it/s]

  5%|▌         | 396/7488 [01:47<27:26,  4.31it/s]
  5%|▌         | 397/7488 [01:47<27:26,  4.31it/s]

  5%|▌         | 398/7488 [01:47<28:47,  4.10it/s]

  5%|▌         | 398/7488 [01:47<28:47,  4.10it/s]
  5%|▌         | 399/7488 [01:48<28:46,  4.10it/s]
  5%|▌         | 400/7488 [01:48<28:46,  4.10it/s]
  5%|▌         | 401/7488 [01:48<28:46,  4.10it/s]
  5%|▌         | 402/7488 [01:48<28:46,  4.10it/s]

  5%|▌         | 403/7488 [01:48<21:57,  5.38it/s]

  5%|▌         | 403/7488 [01:48<21:57,  5.38it/s]
  5%|▌         | 404/7488 [01:48<21:57,  5.38it/s]

  5%|▌         | 405/7488 [01:49<24:23,  4.84it/s]

  5%|▌         | 405/7488 [01:49<24:23,  4.84it/s]
  5%|▌         | 406/7488 [01:49<24:23,  4.84it/s]
  5%|▌         | 407/7488 [01:49<24:23,  4.84it/s]
  5%|▌         | 408/7488 [01:49<24:23,  4.84it/s]
  5%|▌         | 409/7488 [01:49<24:23,  4.84it/s]
  5%|▌         | 410/7488 [01:49<24:22,  4.84it/s]
  5%|▌         | 411/7488 [01:49<24:22,  4.84it/s]
  6%|▌         | 412/7488 [01:49<24:22,  4.84it/s]
  6%|▌         | 413/7488 [01:49<24:22,  4.84it/s]
  6%|▌         | 414/7488 [01:49<24:22,  4.84it/s]

  6%|▌         | 415/7488 [01:49<13:59,  8.42it/s]

  6%|▌         | 415/7488 [01:49<13:59,  8.42it/s]
  6%|▌         | 416/7488 [01:49<13:59,  8.42it/s]

  6%|▌         | 417/7488 [01:50<17:08,  6.87it/s]

  6%|▌         | 417/7488 [01:50<17:08,  6.87it/s]
  6%|▌         | 418/7488 [01:50<17:08,  6.87it/s]

  6%|▌         | 419/7488 [01:50<20:11,  5.84it/s]

  6%|▌         | 419/7488 [01:50<20:11,  5.84it/s]
  6%|▌         | 420/7488 [01:50<20:10,  5.84it/s]
  6%|▌         | 421/7488 [01:50<20:10,  5.84it/s]
  6%|▌         | 422/7488 [01:50<20:10,  5.84it/s]
  6%|▌         | 423/7488 [01:50<20:10,  5.84it/s]
  6%|▌         | 424/7488 [01:50<20:10,  5.84it/s]
  6%|▌         | 425/7488 [01:50<20:10,  5.84it/s]
  6%|▌         | 426/7488 [01:50<20:09,  5.84it/s]
  6%|▌         | 427/7488 [01:50<20:09,  5.84it/s]

  6%|▌         | 428/7488 [01:51<13:34,  8.66it/s]

  6%|▌         | 428/7488 [01:51<13:34,  8.66it/s]
  6%|▌         | 429/7488 [01:51<13:34,  8.66it/s]

  6%|▌         | 430/7488 [01:52<16:45,  7.02it/s]

  6%|▌         | 430/7488 [01:52<16:45,  7.02it/s]
  6%|▌         | 431/7488 [01:52<16:44,  7.02it/s]

  6%|▌         | 432/7488 [01:53<23:48,  4.94it/s]

  6%|▌         | 432/7488 [01:53<23:48,  4.94it/s]
  6%|▌         | 433/7488 [01:53<23:48,  4.94it/s]

  6%|▌         | 434/7488 [01:55<47:34,  2.47it/s]

  6%|▌         | 434/7488 [01:55<47:34,  2.47it/s]
  6%|▌         | 435/7488 [01:55<47:34,  2.47it/s]
  6%|▌         | 436/7488 [01:55<47:33,  2.47it/s]

  6%|▌         | 437/7488 [01:56<40:45,  2.88it/s]

  6%|▌         | 437/7488 [01:56<40:45,  2.88it/s]
  6%|▌         | 438/7488 [01:56<40:45,  2.88it/s]
  6%|▌         | 439/7488 [01:56<40:45,  2.88it/s]

  6%|▌         | 440/7488 [01:56<35:36,  3.30it/s]

  6%|▌         | 440/7488 [01:56<35:36,  3.30it/s]
  6%|▌         | 441/7488 [01:56<35:36,  3.30it/s]
  6%|▌         | 442/7488 [01:56<35:36,  3.30it/s]

  6%|▌         | 443/7488 [01:57<32:00,  3.67it/s]

  6%|▌         | 443/7488 [01:57<32:00,  3.67it/s]
  6%|▌         | 444/7488 [01:57<31:59,  3.67it/s]
  6%|▌         | 445/7488 [01:57<31:59,  3.67it/s]

  6%|▌         | 446/7488 [01:58<29:28,  3.98it/s]

  6%|▌         | 446/7488 [01:58<29:28,  3.98it/s]
  6%|▌         | 447/7488 [01:58<29:28,  3.98it/s]
  6%|▌         | 448/7488 [01:58<29:28,  3.98it/s]
  6%|▌         | 449/7488 [01:58<29:28,  3.98it/s]
  6%|▌         | 450/7488 [01:58<29:27,  3.98it/s]
  6%|▌         | 451/7488 [01:58<29:27,  3.98it/s]
  6%|▌         | 452/7488 [01:58<29:27,  3.98it/s]
  6%|▌         | 453/7488 [01:58<29:27,  3.98it/s]

  6%|▌         | 454/7488 [01:58<18:21,  6.38it/s]

  6%|▌         | 454/7488 [01:58<18:21,  6.38it/s]
  6%|▌         | 455/7488 [01:58<18:21,  6.38it/s]

  6%|▌         | 456/7488 [01:59<21:28,  5.46it/s]

  6%|▌         | 456/7488 [01:59<21:28,  5.46it/s]
  6%|▌         | 457/7488 [01:59<21:28,  5.46it/s]

  6%|▌         | 458/7488 [01:59<23:36,  4.96it/s]

  6%|▌         | 458/7488 [01:59<23:36,  4.96it/s]
  6%|▌         | 459/7488 [01:59<23:36,  4.96it/s]

  6%|▌         | 460/7488 [02:00<25:46,  4.55it/s]

  6%|▌         | 460/7488 [02:00<25:46,  4.55it/s]
  6%|▌         | 461/7488 [02:00<25:46,  4.55it/s]

  6%|▌         | 462/7488 [02:00<27:23,  4.27it/s]

  6%|▌         | 462/7488 [02:00<27:23,  4.27it/s]
  6%|▌         | 463/7488 [02:00<27:23,  4.27it/s]

  6%|▌         | 464/7488 [02:01<29:07,  4.02it/s]

  6%|▌         | 464/7488 [02:01<29:07,  4.02it/s]
  6%|▌         | 465/7488 [02:01<29:06,  4.02it/s]

  6%|▌         | 466/7488 [02:02<30:19,  3.86it/s]

  6%|▌         | 466/7488 [02:02<30:19,  3.86it/s]
  6%|▌         | 467/7488 [02:02<30:18,  3.86it/s]

  6%|▋         | 468/7488 [02:02<30:51,  3.79it/s]

  6%|▋         | 468/7488 [02:02<30:51,  3.79it/s]
  6%|▋         | 469/7488 [02:02<30:51,  3.79it/s]

  6%|▋         | 470/7488 [02:03<31:45,  3.68it/s]

  6%|▋         | 470/7488 [02:03<31:45,  3.68it/s]
  6%|▋         | 471/7488 [02:03<31:45,  3.68it/s]

  6%|▋         | 472/7488 [02:03<31:45,  3.68it/s]

  6%|▋         | 472/7488 [02:03<31:45,  3.68it/s]
  6%|▋         | 473/7488 [02:03<31:44,  3.68it/s]
  6%|▋         | 474/7488 [02:03<31:44,  3.68it/s]
  6%|▋         | 475/7488 [02:03<31:44,  3.68it/s]

  6%|▋         | 476/7488 [02:04<25:08,  4.65it/s]

  6%|▋         | 476/7488 [02:04<25:08,  4.65it/s]
  6%|▋         | 477/7488 [02:04<25:08,  4.65it/s]

  6%|▋         | 478/7488 [02:04<26:37,  4.39it/s]

  6%|▋         | 478/7488 [02:04<26:37,  4.39it/s]
  6%|▋         | 479/7488 [02:04<26:37,  4.39it/s]

  6%|▋         | 480/7488 [02:06<41:11,  2.84it/s]

  6%|▋         | 480/7488 [02:06<41:11,  2.84it/s]
  6%|▋         | 481/7488 [02:06<41:11,  2.84it/s]

  6%|▋         | 482/7488 [02:08<1:01:17,  1.91it/s]

  6%|▋         | 482/7488 [02:08<1:01:17,  1.91it/s]
  6%|▋         | 483/7488 [02:08<1:01:16,  1.91it/s]

  6%|▋         | 484/7488 [02:09<55:36,  2.10it/s]

  6%|▋         | 484/7488 [02:09<55:36,  2.10it/s]
  6%|▋         | 485/7488 [02:09<55:35,  2.10it/s]

  6%|▋         | 486/7488 [02:09<49:49,  2.34it/s]

  6%|▋         | 486/7488 [02:09<49:49,  2.34it/s]
  7%|▋         | 487/7488 [02:09<49:49,  2.34it/s]

  7%|▋         | 488/7488 [02:10<45:31,  2.56it/s]

  7%|▋         | 488/7488 [02:10<45:31,  2.56it/s]
  7%|▋         | 489/7488 [02:10<45:30,  2.56it/s]

  7%|▋         | 490/7488 [02:10<42:56,  2.72it/s]

  7%|▋         | 490/7488 [02:10<42:56,  2.72it/s]
  7%|▋         | 491/7488 [02:10<42:56,  2.72it/s]

  7%|▋         | 492/7488 [02:11<40:16,  2.90it/s]

  7%|▋         | 492/7488 [02:11<40:16,  2.90it/s]
  7%|▋         | 493/7488 [02:11<40:16,  2.90it/s]

  7%|▋         | 494/7488 [02:12<38:58,  2.99it/s]

  7%|▋         | 494/7488 [02:12<38:58,  2.99it/s]
  7%|▋         | 495/7488 [02:12<38:58,  2.99it/s]
  7%|▋         | 496/7488 [02:12<38:58,  2.99it/s]
  7%|▋         | 497/7488 [02:12<38:57,  2.99it/s]
  7%|▋         | 498/7488 [02:12<38:57,  2.99it/s]

  7%|▋         | 499/7488 [02:12<26:16,  4.43it/s]

  7%|▋         | 499/7488 [02:12<26:16,  4.43it/s]
  7%|▋         | 500/7488 [02:12<26:16,  4.43it/s]
  7%|▋         | 501/7488 [02:12<26:16,  4.43it/s]
  7%|▋         | 502/7488 [02:12<26:15,  4.43it/s]

  7%|▋         | 503/7488 [02:13<22:31,  5.17it/s]

  7%|▋         | 503/7488 [02:13<22:31,  5.17it/s]
  7%|▋         | 504/7488 [02:13<22:30,  5.17it/s]

  7%|▋         | 505/7488 [02:13<24:53,  4.67it/s]

  7%|▋         | 505/7488 [02:13<24:53,  4.67it/s]
  7%|▋         | 506/7488 [02:13<24:53,  4.67it/s]

  7%|▋         | 507/7488 [02:14<26:45,  4.35it/s]

  7%|▋         | 507/7488 [02:14<26:45,  4.35it/s]
  7%|▋         | 508/7488 [02:14<26:45,  4.35it/s]

  7%|▋         | 509/7488 [02:14<28:20,  4.10it/s]

  7%|▋         | 509/7488 [02:14<28:20,  4.10it/s]
  7%|▋         | 510/7488 [02:14<28:20,  4.10it/s]

  7%|▋         | 511/7488 [02:15<29:10,  3.99it/s]

  7%|▋         | 511/7488 [02:15<29:10,  3.99it/s]
  7%|▋         | 512/7488 [02:15<29:10,  3.99it/s]

  7%|▋         | 513/7488 [02:16<30:33,  3.80it/s]

  7%|▋         | 513/7488 [02:16<30:33,  3.80it/s]
  7%|▋         | 514/7488 [02:16<30:33,  3.80it/s]

  7%|▋         | 515/7488 [02:16<30:48,  3.77it/s]

  7%|▋         | 515/7488 [02:16<30:48,  3.77it/s]
  7%|▋         | 516/7488 [02:16<30:48,  3.77it/s]

  7%|▋         | 517/7488 [02:17<31:31,  3.69it/s]

  7%|▋         | 517/7488 [02:17<31:31,  3.69it/s]
  7%|▋         | 518/7488 [02:17<31:31,  3.69it/s]

  7%|▋         | 519/7488 [02:17<31:19,  3.71it/s]

  7%|▋         | 519/7488 [02:17<31:19,  3.71it/s]
  7%|▋         | 520/7488 [02:17<31:19,  3.71it/s]
  7%|▋         | 521/7488 [02:17<31:19,  3.71it/s]

  7%|▋         | 522/7488 [02:20<1:02:08,  1.87it/s]

  7%|▋         | 522/7488 [02:20<1:02:08,  1.87it/s]
  7%|▋         | 523/7488 [02:20<1:02:07,  1.87it/s]

  7%|▋         | 524/7488 [02:21<54:16,  2.14it/s]

  7%|▋         | 524/7488 [02:21<54:16,  2.14it/s]
  7%|▋         | 525/7488 [02:21<54:16,  2.14it/s]

  7%|▋         | 526/7488 [02:21<47:31,  2.44it/s]

  7%|▋         | 526/7488 [02:21<47:31,  2.44it/s]
  7%|▋         | 527/7488 [02:21<47:31,  2.44it/s]

  7%|▋         | 528/7488 [02:22<43:35,  2.66it/s]

  7%|▋         | 528/7488 [02:22<43:35,  2.66it/s]
  7%|▋         | 529/7488 [02:22<43:35,  2.66it/s]

  7%|▋         | 530/7488 [02:22<40:13,  2.88it/s]

  7%|▋         | 530/7488 [02:22<40:13,  2.88it/s]
  7%|▋         | 531/7488 [02:22<40:13,  2.88it/s]

  7%|▋         | 532/7488 [02:23<38:08,  3.04it/s]

  7%|▋         | 532/7488 [02:23<38:08,  3.04it/s]
  7%|▋         | 533/7488 [02:23<38:08,  3.04it/s]

  7%|▋         | 534/7488 [02:23<36:09,  3.20it/s]

  7%|▋         | 534/7488 [02:23<36:09,  3.20it/s]
  7%|▋         | 535/7488 [02:23<36:09,  3.20it/s]

  7%|▋         | 536/7488 [02:24<36:14,  3.20it/s]

  7%|▋         | 536/7488 [02:24<36:14,  3.20it/s]
  7%|▋         | 537/7488 [02:24<36:14,  3.20it/s]

  7%|▋         | 538/7488 [02:25<35:43,  3.24it/s]

  7%|▋         | 538/7488 [02:25<35:43,  3.24it/s]
  7%|▋         | 539/7488 [02:25<35:43,  3.24it/s]
  7%|▋         | 540/7488 [02:25<35:42,  3.24it/s]

  7%|▋         | 541/7488 [02:25<30:59,  3.74it/s]

  7%|▋         | 541/7488 [02:25<30:59,  3.74it/s]
  7%|▋         | 542/7488 [02:25<30:59,  3.74it/s]

  7%|▋         | 543/7488 [02:26<32:33,  3.56it/s]

  7%|▋         | 543/7488 [02:26<32:33,  3.56it/s]
  7%|▋         | 544/7488 [02:26<32:33,  3.56it/s]

  7%|▋         | 545/7488 [02:27<33:19,  3.47it/s]

  7%|▋         | 545/7488 [02:27<33:19,  3.47it/s]
  7%|▋         | 546/7488 [02:27<33:19,  3.47it/s]

  7%|▋         | 547/7488 [02:27<34:17,  3.37it/s]

  7%|▋         | 547/7488 [02:27<34:17,  3.37it/s]
  7%|▋         | 548/7488 [02:27<34:17,  3.37it/s]

  7%|▋         | 549/7488 [02:28<34:05,  3.39it/s]

  7%|▋         | 549/7488 [02:28<34:05,  3.39it/s]
  7%|▋         | 550/7488 [02:28<34:05,  3.39it/s]

  7%|▋         | 551/7488 [02:28<34:04,  3.39it/s]

  7%|▋         | 551/7488 [02:28<34:04,  3.39it/s]
  7%|▋         | 552/7488 [02:28<34:04,  3.39it/s]
  7%|▋         | 553/7488 [02:28<34:03,  3.39it/s]
  7%|▋         | 554/7488 [02:28<34:03,  3.39it/s]
  7%|▋         | 555/7488 [02:28<34:03,  3.39it/s]

  7%|▋         | 556/7488 [02:29<24:13,  4.77it/s]
  8%|▊         | 591/7488 [02:29<04:13, 27.22it/s]
  8%|▊         | 609/7488 [02:29<02:51, 40.20it/s]

  7%|▋         | 556/7488 [02:29<24:13,  4.77it/s]
  7%|▋         | 557/7488 [02:29<24:13,  4.77it/s]
  7%|▋         | 558/7488 [02:29<24:13,  4.77it/s]
  7%|▋         | 559/7488 [02:29<24:12,  4.77it/s]
  7%|▋         | 560/7488 [02:29<24:12,  4.77it/s]
  7%|▋         | 561/7488 [02:29<24:12,  4.77it/s]
  8%|▊         | 562/7488 [02:29<24:12,  4.77it/s]
  8%|▊         | 563/7488 [02:29<24:12,  4.77it/s]
  8%|▊         | 564/7488 [02:29<24:11,  4.77it/s]
  8%|▊         | 565/7488 [02:29<24:11,  4.77it/s]
  8%|▊         | 566/7488 [02:29<24:11,  4.77it/s]
  8%|▊         | 567/7488 [02:29<24:11,  4.77it/s]
  8%|▊         | 568/7488 [02:29<24:11,  4.77it/s]
  8%|▊         | 569/7488 [02:29<24:10,  4.77it/s]
  8%|▊         | 570/7488 [02:29<24:10,  4.77it/s]
  8%|▊         | 571/7488 [02:29<24:10,  4.77it/s]
  8%|▊         | 572/7488 [02:29<24:10,  4.77it/s]
  8%|▊         | 573/7488 [02:29<24:10,  4.77it/s]
  8%|▊         | 574/7488 [02:29<24:09,  4.77it/s]
  8%|▊         | 575/7488 [02:29<24:09,  4.77it/s]
  8%|▊         | 576/7488 [02:29<24:09,  4.77it/s]
  8%|▊         | 577/7488 [02:29<24:09,  4.77it/s]
  8%|▊         | 578/7488 [02:29<24:09,  4.77it/s]
  8%|▊         | 579/7488 [02:29<24:08,  4.77it/s]
  8%|▊         | 580/7488 [02:29<24:08,  4.77it/s]
  8%|▊         | 581/7488 [02:29<24:08,  4.77it/s]
  8%|▊         | 582/7488 [02:29<24:08,  4.77it/s]
  8%|▊         | 583/7488 [02:29<24:07,  4.77it/s]
  8%|▊         | 584/7488 [02:29<24:07,  4.77it/s]
  8%|▊         | 585/7488 [02:29<24:07,  4.77it/s]
  8%|▊         | 586/7488 [02:29<24:07,  4.77it/s]
  8%|▊         | 587/7488 [02:29<24:07,  4.77it/s]
  8%|▊         | 588/7488 [02:29<24:06,  4.77it/s]
  8%|▊         | 589/7488 [02:29<24:06,  4.77it/s]
  8%|▊         | 590/7488 [02:29<24:06,  4.77it/s]
  8%|▊         | 591/7488 [02:29<04:13, 27.22it/s]
  8%|▊         | 592/7488 [02:29<04:13, 27.22it/s]
  8%|▊         | 593/7488 [02:29<04:13, 27.22it/s]
  8%|▊         | 594/7488 [02:29<04:13, 27.22it/s]
  8%|▊         | 595/7488 [02:29<04:13, 27.22it/s]
  8%|▊         | 596/7488 [02:29<04:13, 27.22it/s]
  8%|▊         | 597/7488 [02:29<04:13, 27.22it/s]
  8%|▊         | 598/7488 [02:29<04:13, 27.22it/s]
  8%|▊         | 599/7488 [02:29<04:13, 27.22it/s]
  8%|▊         | 600/7488 [02:29<04:13, 27.22it/s]
  8%|▊         | 601/7488 [02:29<04:12, 27.22it/s]
  8%|▊         | 602/7488 [02:29<04:12, 27.22it/s]
  8%|▊         | 603/7488 [02:29<04:12, 27.22it/s]
  8%|▊         | 604/7488 [02:29<04:12, 27.22it/s]
  8%|▊         | 605/7488 [02:29<04:12, 27.22it/s]
  8%|▊         | 606/7488 [02:29<04:12, 27.22it/s]
  8%|▊         | 607/7488 [02:29<04:12, 27.22it/s]
  8%|▊         | 608/7488 [02:29<04:12, 27.22it/s]
  8%|▊         | 609/7488 [02:29<02:51, 40.20it/s]

  8%|▊         | 632/7488 [02:29<01:53, 60.65it/s]

  8%|▊         | 610/7488 [02:29<02:51, 40.20it/s]
  8%|▊         | 611/7488 [02:29<02:51, 40.20it/s]
  8%|▊         | 612/7488 [02:29<02:51, 40.20it/s]
  8%|▊         | 613/7488 [02:29<02:51, 40.20it/s]
  8%|▊         | 614/7488 [02:29<02:51, 40.20it/s]
  8%|▊         | 615/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 616/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 617/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 618/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 619/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 620/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 621/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 622/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 623/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 624/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 625/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 626/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 627/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 628/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 629/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 630/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 631/7488 [02:29<02:50, 40.20it/s]
  8%|▊         | 632/7488 [02:29<01:53, 60.65it/s]
  8%|▊         | 633/7488 [02:29<01:53, 60.65it/s]
  8%|▊         | 634/7488 [02:29<01:53, 60.65it/s]
  8%|▊         | 635/7488 [02:29<01:52, 60.65it/s]
  8%|▊         | 636/7488 [02:29<01:52, 60.65it/s]
  9%|▊         | 637/7488 [02:29<01:52, 60.65it/s]
  9%|▊         | 638/7488 [02:29<01:52, 60.65it/s]
  9%|▊         | 639/7488 [02:29<01:52, 60.65it/s]
  9%|▊         | 640/7488 [02:30<01:52, 60.65it/s]
  9%|▊         | 641/7488 [02:30<01:52, 60.65it/s]
  9%|▊         | 642/7488 [02:33<01:52, 60.65it/s]
  9%|▊         | 643/7488 [02:33<01:52, 60.65it/s]
  9%|▊         | 644/7488 [02:33<01:52, 60.65it/s]
  9%|▊         | 645/7488 [02:33<01:52, 60.65it/s]
  9%|▊         | 646/7488 [02:34<01:52, 60.65it/s]
  9%|▊         | 647/7488 [02:34<01:52, 60.65it/s]

  9%|▊         | 648/7488 [02:34<11:55,  9.56it/s]

  9%|▊         | 648/7488 [02:34<11:55,  9.56it/s]
  9%|▊         | 649/7488 [02:34<11:55,  9.56it/s]
  9%|▊         | 650/7488 [02:35<11:55,  9.56it/s]
  9%|▊         | 651/7488 [02:35<11:55,  9.56it/s]
  9%|▊         | 652/7488 [02:36<11:54,  9.56it/s]
  9%|▊         | 653/7488 [02:36<11:54,  9.56it/s]
  9%|▊         | 654/7488 [02:36<11:54,  9.56it/s]
  9%|▊         | 655/7488 [02:36<11:54,  9.56it/s]
  9%|▉         | 656/7488 [02:36<11:54,  9.56it/s]
  9%|▉         | 657/7488 [02:37<11:54,  9.56it/s]
  9%|▉         | 658/7488 [02:37<11:54,  9.56it/s]
  9%|▉         | 659/7488 [02:37<11:54,  9.56it/s]

  9%|▉         | 660/7488 [02:37<15:25,  7.37it/s]

  9%|▉         | 660/7488 [02:37<15:25,  7.37it/s]
  9%|▉         | 661/7488 [02:37<15:25,  7.37it/s]
  9%|▉         | 662/7488 [02:38<15:25,  7.37it/s]
  9%|▉         | 663/7488 [02:38<15:25,  7.37it/s]
  9%|▉         | 664/7488 [02:38<15:25,  7.37it/s]
  9%|▉         | 665/7488 [02:38<15:25,  7.37it/s]
  9%|▉         | 666/7488 [02:38<15:25,  7.37it/s]

  9%|▉         | 668/7488 [02:39<17:06,  6.64it/s]

  9%|▉         | 667/7488 [02:39<15:24,  7.37it/s]
  9%|▉         | 668/7488 [02:39<17:06,  6.64it/s]
  9%|▉         | 669/7488 [02:40<17:06,  6.64it/s]
  9%|▉         | 670/7488 [02:40<17:06,  6.64it/s]
  9%|▉         | 671/7488 [02:40<17:06,  6.64it/s]
  9%|▉         | 672/7488 [02:40<17:06,  6.64it/s]

  9%|▉         | 674/7488 [02:41<19:44,  5.75it/s]

  9%|▉         | 673/7488 [02:41<17:06,  6.64it/s]
  9%|▉         | 674/7488 [02:41<19:44,  5.75it/s]
  9%|▉         | 675/7488 [02:41<19:43,  5.75it/s]
  9%|▉         | 676/7488 [02:41<19:43,  5.75it/s]
  9%|▉         | 677/7488 [02:42<19:43,  5.75it/s]
  9%|▉         | 678/7488 [02:42<19:43,  5.75it/s]

  9%|▉         | 679/7488 [02:42<22:48,  4.97it/s]

  9%|▉         | 679/7488 [02:42<22:48,  4.97it/s]
  9%|▉         | 680/7488 [02:42<22:48,  4.97it/s]

  9%|▉         | 682/7488 [02:45<33:20,  3.40it/s]

  9%|▉         | 681/7488 [02:45<22:48,  4.97it/s]
  9%|▉         | 682/7488 [02:45<33:20,  3.40it/s]
  9%|▉         | 683/7488 [02:45<33:20,  3.40it/s]

  9%|▉         | 685/7488 [02:46<31:49,  3.56it/s]

  9%|▉         | 684/7488 [02:46<33:20,  3.40it/s]
  9%|▉         | 685/7488 [02:46<31:49,  3.56it/s]

  9%|▉         | 687/7488 [02:46<31:43,  3.57it/s]

  9%|▉         | 686/7488 [02:46<31:49,  3.56it/s]
  9%|▉         | 687/7488 [02:46<31:43,  3.57it/s]

  9%|▉         | 689/7488 [02:47<32:01,  3.54it/s]

  9%|▉         | 688/7488 [02:47<31:42,  3.57it/s]
  9%|▉         | 689/7488 [02:47<32:01,  3.54it/s]

  9%|▉         | 690/7488 [02:48<35:11,  3.22it/s]

  9%|▉         | 690/7488 [02:48<35:11,  3.22it/s]
  9%|▉         | 691/7488 [02:48<35:11,  3.22it/s]
  9%|▉         | 692/7488 [02:48<35:10,  3.22it/s]
  9%|▉         | 693/7488 [02:48<35:10,  3.22it/s]

  9%|▉         | 694/7488 [02:48<28:34,  3.96it/s]

  9%|▉         | 694/7488 [02:48<28:34,  3.96it/s]
  9%|▉         | 695/7488 [02:48<28:33,  3.96it/s]

  9%|▉         | 696/7488 [02:49<29:37,  3.82it/s]

  9%|▉         | 696/7488 [02:49<29:37,  3.82it/s]
  9%|▉         | 697/7488 [02:49<29:36,  3.82it/s]

  9%|▉         | 698/7488 [02:49<30:42,  3.69it/s]

  9%|▉         | 698/7488 [02:49<30:42,  3.69it/s]
  9%|▉         | 699/7488 [02:49<30:41,  3.69it/s]

  9%|▉         | 700/7488 [02:50<32:20,  3.50it/s]

  9%|▉         | 700/7488 [02:50<32:20,  3.50it/s]
  9%|▉         | 701/7488 [02:50<32:20,  3.50it/s]
  9%|▉         | 702/7488 [02:50<32:20,  3.50it/s]

  9%|▉         | 703/7488 [02:51<29:05,  3.89it/s]

  9%|▉         | 703/7488 [02:51<29:05,  3.89it/s]
  9%|▉         | 704/7488 [02:51<29:05,  3.89it/s]

  9%|▉         | 705/7488 [02:51<30:25,  3.72it/s]

  9%|▉         | 705/7488 [02:51<30:25,  3.72it/s]
  9%|▉         | 706/7488 [02:51<30:24,  3.72it/s]

  9%|▉         | 707/7488 [02:52<31:22,  3.60it/s]

  9%|▉         | 707/7488 [02:52<31:22,  3.60it/s]
  9%|▉         | 708/7488 [02:52<31:22,  3.60it/s]

  9%|▉         | 709/7488 [02:53<32:21,  3.49it/s]

  9%|▉         | 709/7488 [02:53<32:21,  3.49it/s]
  9%|▉         | 710/7488 [02:53<32:21,  3.49it/s]

  9%|▉         | 711/7488 [02:53<32:47,  3.45it/s]

  9%|▉         | 711/7488 [02:53<32:47,  3.45it/s]
 10%|▉         | 712/7488 [02:53<32:46,  3.45it/s]

 10%|▉         | 713/7488 [02:54<32:31,  3.47it/s]

 10%|▉         | 713/7488 [02:54<32:31,  3.47it/s]
 10%|▉         | 714/7488 [02:54<32:31,  3.47it/s]

 10%|▉         | 715/7488 [02:54<32:51,  3.44it/s]

 10%|▉         | 715/7488 [02:54<32:51,  3.44it/s]
 10%|▉         | 716/7488 [02:54<32:50,  3.44it/s]

 10%|▉         | 717/7488 [02:55<33:00,  3.42it/s]

 10%|▉         | 717/7488 [02:55<33:00,  3.42it/s]
 10%|▉         | 718/7488 [02:55<33:00,  3.42it/s]

 10%|▉         | 719/7488 [02:58<1:11:37,  1.58it/s]

 10%|▉         | 719/7488 [02:58<1:11:37,  1.58it/s]
 10%|▉         | 720/7488 [02:58<1:11:36,  1.58it/s]

 10%|▉         | 721/7488 [02:58<1:00:37,  1.86it/s]

 10%|▉         | 721/7488 [02:58<1:00:37,  1.86it/s]
 10%|▉         | 722/7488 [02:58<1:00:36,  1.86it/s]

 10%|▉         | 723/7488 [02:59<53:36,  2.10it/s]

 10%|▉         | 723/7488 [02:59<53:36,  2.10it/s]
 10%|▉         | 724/7488 [02:59<53:35,  2.10it/s]

 10%|▉         | 725/7488 [03:00<47:56,  2.35it/s]

 10%|▉         | 725/7488 [03:00<47:56,  2.35it/s]
 10%|▉         | 726/7488 [03:00<47:56,  2.35it/s]

 10%|▉         | 727/7488 [03:00<43:39,  2.58it/s]

 10%|▉         | 727/7488 [03:00<43:39,  2.58it/s]
 10%|▉         | 728/7488 [03:00<43:39,  2.58it/s]

 10%|▉         | 729/7488 [03:01<41:05,  2.74it/s]

 10%|▉         | 729/7488 [03:01<41:05,  2.74it/s]
 10%|▉         | 730/7488 [03:01<41:05,  2.74it/s]

 10%|▉         | 731/7488 [03:02<39:10,  2.87it/s]

 10%|▉         | 731/7488 [03:02<39:10,  2.87it/s]
 10%|▉         | 732/7488 [03:02<39:10,  2.87it/s]
 10%|▉         | 733/7488 [03:02<39:10,  2.87it/s]
 10%|▉         | 734/7488 [03:02<39:09,  2.87it/s]

 10%|▉         | 735/7488 [03:02<29:20,  3.84it/s]

 10%|▉         | 735/7488 [03:02<29:20,  3.84it/s]
 10%|▉         | 736/7488 [03:02<29:19,  3.84it/s]

 10%|▉         | 737/7488 [03:03<30:52,  3.64it/s]

 10%|▉         | 737/7488 [03:03<30:52,  3.64it/s]
 10%|▉         | 738/7488 [03:03<30:52,  3.64it/s]

 10%|▉         | 739/7488 [03:03<31:52,  3.53it/s]

 10%|▉         | 739/7488 [03:03<31:52,  3.53it/s]
 10%|▉         | 740/7488 [03:03<31:52,  3.53it/s]

 10%|▉         | 741/7488 [03:04<33:09,  3.39it/s]

 10%|▉         | 741/7488 [03:04<33:09,  3.39it/s]
 10%|▉         | 742/7488 [03:04<33:08,  3.39it/s]

 10%|▉         | 743/7488 [03:05<34:06,  3.30it/s]

 10%|▉         | 743/7488 [03:05<34:06,  3.30it/s]
 10%|▉         | 744/7488 [03:05<34:05,  3.30it/s]

 10%|▉         | 745/7488 [03:05<34:01,  3.30it/s]

 10%|▉         | 745/7488 [03:05<34:01,  3.30it/s]
 10%|▉         | 746/7488 [03:05<34:01,  3.30it/s]
 10%|▉         | 747/7488 [03:05<34:01,  3.30it/s]
 10%|▉         | 748/7488 [03:05<34:01,  3.30it/s]

 10%|█         | 749/7488 [03:06<27:04,  4.15it/s]

 10%|█         | 749/7488 [03:06<27:04,  4.15it/s]
 10%|█         | 750/7488 [03:06<27:04,  4.15it/s]

 10%|█         | 751/7488 [03:07<28:49,  3.90it/s]

 10%|█         | 751/7488 [03:07<28:49,  3.90it/s]
 10%|█         | 752/7488 [03:07<28:49,  3.90it/s]

 10%|█         | 753/7488 [03:07<31:05,  3.61it/s]

 10%|█         | 753/7488 [03:07<31:05,  3.61it/s]
 10%|█         | 754/7488 [03:07<31:05,  3.61it/s]
 10%|█         | 755/7488 [03:07<31:04,  3.61it/s]

 10%|█         | 756/7488 [03:09<49:05,  2.29it/s]

 10%|█         | 756/7488 [03:09<49:05,  2.29it/s]
 10%|█         | 757/7488 [03:09<49:05,  2.29it/s]
 10%|█         | 758/7488 [03:09<49:04,  2.29it/s]
 10%|█         | 759/7488 [03:09<49:04,  2.29it/s]
 10%|█         | 760/7488 [03:09<49:03,  2.29it/s]
 10%|█         | 761/7488 [03:09<49:03,  2.29it/s]
 10%|█         | 762/7488 [03:09<49:03,  2.29it/s]
 10%|█         | 763/7488 [03:09<49:02,  2.29it/s]
 10%|█         | 764/7488 [03:10<49:02,  2.29it/s]

 10%|█         | 765/7488 [03:11<29:18,  3.82it/s]

 10%|█         | 765/7488 [03:11<29:18,  3.82it/s]
 10%|█         | 766/7488 [03:11<29:18,  3.82it/s]

 10%|█         | 767/7488 [03:11<30:09,  3.71it/s]

 10%|█         | 767/7488 [03:11<30:09,  3.71it/s]
 10%|█         | 768/7488 [03:11<30:09,  3.71it/s]

 10%|█         | 769/7488 [03:12<31:01,  3.61it/s]

 10%|█         | 769/7488 [03:12<31:01,  3.61it/s]
 10%|█         | 770/7488 [03:12<31:01,  3.61it/s]

 10%|█         | 771/7488 [03:13<31:19,  3.57it/s]

 10%|█         | 771/7488 [03:13<31:19,  3.57it/s]
 10%|█         | 772/7488 [03:13<31:19,  3.57it/s]

 10%|█         | 773/7488 [03:13<32:13,  3.47it/s]

 10%|█         | 773/7488 [03:13<32:13,  3.47it/s]
 10%|█         | 774/7488 [03:13<32:12,  3.47it/s]

 10%|█         | 775/7488 [03:14<32:47,  3.41it/s]

 10%|█         | 775/7488 [03:14<32:47,  3.41it/s]
 10%|█         | 776/7488 [03:14<32:47,  3.41it/s]

 10%|█         | 777/7488 [03:14<33:16,  3.36it/s]

 10%|█         | 777/7488 [03:14<33:16,  3.36it/s]
 10%|█         | 778/7488 [03:14<33:16,  3.36it/s]

 10%|█         | 779/7488 [03:15<33:31,  3.34it/s]

 10%|█         | 779/7488 [03:15<33:31,  3.34it/s]
 10%|█         | 780/7488 [03:15<33:31,  3.34it/s]

 10%|█         | 781/7488 [03:16<34:12,  3.27it/s]

 10%|█         | 781/7488 [03:16<34:12,  3.27it/s]
 10%|█         | 782/7488 [03:16<34:12,  3.27it/s]

 10%|█         | 783/7488 [03:16<34:42,  3.22it/s]

 10%|█         | 783/7488 [03:16<34:42,  3.22it/s]
 10%|█         | 784/7488 [03:16<34:42,  3.22it/s]
 10%|█         | 785/7488 [03:16<34:41,  3.22it/s]

 10%|█         | 786/7488 [03:17<30:28,  3.66it/s]

 10%|█         | 786/7488 [03:17<30:28,  3.66it/s]
 11%|█         | 787/7488 [03:17<30:28,  3.66it/s]

 11%|█         | 788/7488 [03:18<32:19,  3.45it/s]

 11%|█         | 788/7488 [03:18<32:19,  3.45it/s]
 11%|█         | 789/7488 [03:18<32:19,  3.45it/s]
 11%|█         | 790/7488 [03:18<32:19,  3.45it/s]
 11%|█         | 791/7488 [03:18<32:18,  3.45it/s]
 11%|█         | 792/7488 [03:18<32:18,  3.45it/s]

 11%|█         | 793/7488 [03:18<24:13,  4.61it/s]

 11%|█         | 793/7488 [03:18<24:13,  4.61it/s]
 11%|█         | 794/7488 [03:18<24:12,  4.61it/s]

 11%|█         | 795/7488 [03:19<27:04,  4.12it/s]

 11%|█         | 795/7488 [03:19<27:04,  4.12it/s]
 11%|█         | 796/7488 [03:19<27:03,  4.12it/s]
 11%|█         | 797/7488 [03:19<27:03,  4.12it/s]

 11%|█         | 798/7488 [03:20<27:02,  4.12it/s]

 11%|█         | 798/7488 [03:20<27:02,  4.12it/s]
 11%|█         | 799/7488 [03:20<27:02,  4.12it/s]

 11%|█         | 800/7488 [03:21<31:06,  3.58it/s]

 11%|█         | 800/7488 [03:21<31:06,  3.58it/s]
 11%|█         | 801/7488 [03:21<31:06,  3.58it/s]

 11%|█         | 802/7488 [03:23<1:03:06,  1.77it/s]

 11%|█         | 802/7488 [03:23<1:03:06,  1.77it/s]
 11%|█         | 803/7488 [03:23<1:03:05,  1.77it/s]

 11%|█         | 804/7488 [03:24<56:57,  1.96it/s]

 11%|█         | 804/7488 [03:24<56:57,  1.96it/s]
 11%|█         | 805/7488 [03:24<56:57,  1.96it/s]

 11%|█         | 806/7488 [03:25<51:53,  2.15it/s]

 11%|█         | 806/7488 [03:25<51:53,  2.15it/s]
 11%|█         | 807/7488 [03:25<51:53,  2.15it/s]

 11%|█         | 808/7488 [03:25<48:10,  2.31it/s]

 11%|█         | 808/7488 [03:26<48:10,  2.31it/s]
 11%|█         | 809/7488 [03:26<48:10,  2.31it/s]

 11%|█         | 810/7488 [03:26<45:50,  2.43it/s]

 11%|█         | 810/7488 [03:26<45:50,  2.43it/s]
 11%|█         | 811/7488 [03:26<45:50,  2.43it/s]

 11%|█         | 812/7488 [03:27<43:58,  2.53it/s]

 11%|█         | 812/7488 [03:27<43:58,  2.53it/s]
 11%|█         | 813/7488 [03:27<43:58,  2.53it/s]
 11%|█         | 814/7488 [03:27<43:58,  2.53it/s]

 11%|█         | 815/7488 [03:28<36:52,  3.02it/s]

 11%|█         | 815/7488 [03:28<36:52,  3.02it/s]
 11%|█         | 816/7488 [03:28<36:52,  3.02it/s]

 11%|█         | 817/7488 [03:28<37:58,  2.93it/s]

 11%|█         | 817/7488 [03:28<37:58,  2.93it/s]
 11%|█         | 818/7488 [03:28<37:57,  2.93it/s]

 11%|█         | 819/7488 [03:29<39:02,  2.85it/s]

 11%|█         | 819/7488 [03:29<39:02,  2.85it/s]
 11%|█         | 820/7488 [03:29<39:01,  2.85it/s]

 11%|█         | 821/7488 [03:30<38:14,  2.91it/s]

 11%|█         | 821/7488 [03:30<38:14,  2.91it/s]
 11%|█         | 822/7488 [03:30<38:14,  2.91it/s]

 11%|█         | 823/7488 [03:30<38:07,  2.91it/s]

 11%|█         | 823/7488 [03:30<38:07,  2.91it/s]
 11%|█         | 824/7488 [03:30<38:07,  2.91it/s]

 11%|█         | 825/7488 [03:31<37:54,  2.93it/s]

 11%|█         | 825/7488 [03:31<37:54,  2.93it/s]
 11%|█         | 826/7488 [03:31<37:54,  2.93it/s]

 11%|█         | 827/7488 [03:32<37:10,  2.99it/s]

 11%|█         | 827/7488 [03:32<37:10,  2.99it/s]
 11%|█         | 828/7488 [03:32<37:10,  2.99it/s]

 11%|█         | 829/7488 [03:32<37:16,  2.98it/s]

 11%|█         | 829/7488 [03:32<37:16,  2.98it/s]
 11%|█         | 830/7488 [03:32<37:15,  2.98it/s]

 11%|█         | 831/7488 [03:33<39:28,  2.81it/s]

 11%|█         | 831/7488 [03:33<39:28,  2.81it/s]
 11%|█         | 832/7488 [03:33<39:28,  2.81it/s]

 11%|█         | 833/7488 [03:36<1:12:44,  1.52it/s]

 11%|█         | 833/7488 [03:36<1:12:44,  1.52it/s]
 11%|█         | 834/7488 [03:36<1:12:43,  1.52it/s]

 11%|█         | 835/7488 [03:37<1:01:53,  1.79it/s]

 11%|█         | 835/7488 [03:37<1:01:53,  1.79it/s]
 11%|█         | 836/7488 [03:37<1:01:52,  1.79it/s]
 11%|█         | 837/7488 [03:37<1:01:52,  1.79it/s]

 11%|█         | 838/7488 [03:37<46:34,  2.38it/s]

 11%|█         | 838/7488 [03:37<46:34,  2.38it/s]
 11%|█         | 839/7488 [03:37<46:34,  2.38it/s]

 11%|█         | 840/7488 [03:38<43:50,  2.53it/s]

 11%|█         | 840/7488 [03:38<43:50,  2.53it/s]
 11%|█         | 841/7488 [03:38<43:50,  2.53it/s]

 11%|█         | 842/7488 [03:39<41:43,  2.65it/s]

 11%|█         | 842/7488 [03:39<41:43,  2.65it/s]
 11%|█▏        | 843/7488 [03:39<41:43,  2.65it/s]

 11%|█▏        | 844/7488 [03:39<39:19,  2.82it/s]

 11%|█▏        | 844/7488 [03:39<39:19,  2.82it/s]
 11%|█▏        | 845/7488 [03:39<39:18,  2.82it/s]

 11%|█▏        | 846/7488 [03:40<38:12,  2.90it/s]

 11%|█▏        | 846/7488 [03:40<38:12,  2.90it/s]
 11%|█▏        | 847/7488 [03:40<38:12,  2.90it/s]
 11%|█▏        | 848/7488 [03:40<38:12,  2.90it/s]

 11%|█▏        | 849/7488 [03:40<32:09,  3.44it/s]

 11%|█▏        | 849/7488 [03:40<32:09,  3.44it/s]
 11%|█▏        | 850/7488 [03:40<32:09,  3.44it/s]

 11%|█▏        | 851/7488 [03:41<32:22,  3.42it/s]

 11%|█▏        | 851/7488 [03:41<32:22,  3.42it/s]
 11%|█▏        | 852/7488 [03:41<32:22,  3.42it/s]

 11%|█▏        | 853/7488 [03:42<33:02,  3.35it/s]

 11%|█▏        | 853/7488 [03:42<33:02,  3.35it/s]
 11%|█▏        | 854/7488 [03:42<33:02,  3.35it/s]

 11%|█▏        | 855/7488 [03:42<32:57,  3.35it/s]

 11%|█▏        | 855/7488 [03:42<32:57,  3.35it/s]
 11%|█▏        | 856/7488 [03:42<32:57,  3.35it/s]

 11%|█▏        | 857/7488 [03:43<33:09,  3.33it/s]

 11%|█▏        | 857/7488 [03:43<33:09,  3.33it/s]
 11%|█▏        | 858/7488 [03:43<33:09,  3.33it/s]

 11%|█▏        | 859/7488 [03:43<32:45,  3.37it/s]

 11%|█▏        | 859/7488 [03:43<32:45,  3.37it/s]
 11%|█▏        | 860/7488 [03:43<32:45,  3.37it/s]

 11%|█▏        | 861/7488 [03:44<33:02,  3.34it/s]

 11%|█▏        | 861/7488 [03:44<33:02,  3.34it/s]
 12%|█▏        | 862/7488 [03:44<33:02,  3.34it/s]
 12%|█▏        | 863/7488 [03:44<33:02,  3.34it/s]
 12%|█▏        | 864/7488 [03:44<33:01,  3.34it/s]
 12%|█▏        | 865/7488 [03:44<33:01,  3.34it/s]

 12%|█▏        | 866/7488 [03:45<22:37,  4.88it/s]

 12%|█▏        | 866/7488 [03:45<22:37,  4.88it/s]
 12%|█▏        | 867/7488 [03:45<22:37,  4.88it/s]

 12%|█▏        | 868/7488 [03:45<25:14,  4.37it/s]

 12%|█▏        | 868/7488 [03:45<25:14,  4.37it/s]
 12%|█▏        | 869/7488 [03:45<25:13,  4.37it/s]

 12%|█▏        | 870/7488 [03:46<31:58,  3.45it/s]

 12%|█▏        | 870/7488 [03:46<31:58,  3.45it/s]
 12%|█▏        | 871/7488 [03:46<31:57,  3.45it/s]

 12%|█▏        | 872/7488 [03:49<59:30,  1.85it/s]

 12%|█▏        | 872/7488 [03:49<59:30,  1.85it/s]
 12%|█▏        | 873/7488 [03:49<59:30,  1.85it/s]

 12%|█▏        | 874/7488 [03:49<52:21,  2.11it/s]

 12%|█▏        | 874/7488 [03:49<52:21,  2.11it/s]
 12%|█▏        | 875/7488 [03:49<52:21,  2.11it/s]

 12%|█▏        | 876/7488 [03:50<46:55,  2.35it/s]

 12%|█▏        | 876/7488 [03:50<46:55,  2.35it/s]
 12%|█▏        | 877/7488 [03:50<46:55,  2.35it/s]

 12%|█▏        | 878/7488 [03:51<43:38,  2.52it/s]

 12%|█▏        | 878/7488 [03:51<43:38,  2.52it/s]
 12%|█▏        | 879/7488 [03:51<43:38,  2.52it/s]

 12%|█▏        | 880/7488 [03:51<40:51,  2.70it/s]

 12%|█▏        | 880/7488 [03:51<40:51,  2.70it/s]
 12%|█▏        | 881/7488 [03:51<40:51,  2.70it/s]

 12%|█▏        | 882/7488 [03:52<38:20,  2.87it/s]

 12%|█▏        | 882/7488 [03:52<38:20,  2.87it/s]
 12%|█▏        | 883/7488 [03:52<38:20,  2.87it/s]

 12%|█▏        | 884/7488 [03:52<36:58,  2.98it/s]

 12%|█▏        | 884/7488 [03:52<36:58,  2.98it/s]
 12%|█▏        | 885/7488 [03:52<36:58,  2.98it/s]

 12%|█▏        | 886/7488 [03:53<35:17,  3.12it/s]

 12%|█▏        | 886/7488 [03:53<35:17,  3.12it/s]
 12%|█▏        | 887/7488 [03:53<35:16,  3.12it/s]

 12%|█▏        | 888/7488 [03:54<34:49,  3.16it/s]

 12%|█▏        | 888/7488 [03:54<34:49,  3.16it/s]
 12%|█▏        | 889/7488 [03:54<34:49,  3.16it/s]

 12%|█▏        | 890/7488 [03:54<33:52,  3.25it/s]

 12%|█▏        | 890/7488 [03:54<33:52,  3.25it/s]
 12%|█▏        | 891/7488 [03:54<33:52,  3.25it/s]
 12%|█▏        | 892/7488 [03:54<33:52,  3.25it/s]

 12%|█▏        | 893/7488 [03:55<29:15,  3.76it/s]

 12%|█▏        | 893/7488 [03:55<29:15,  3.76it/s]
 12%|█▏        | 894/7488 [03:55<29:15,  3.76it/s]

 12%|█▏        | 895/7488 [03:55<30:27,  3.61it/s]

 12%|█▏        | 895/7488 [03:55<30:27,  3.61it/s]
 12%|█▏        | 896/7488 [03:55<30:26,  3.61it/s]
 12%|█▏        | 897/7488 [03:55<30:26,  3.61it/s]
 12%|█▏        | 898/7488 [03:55<30:26,  3.61it/s]
 12%|█▏        | 899/7488 [03:55<30:26,  3.61it/s]
 12%|█▏        | 900/7488 [03:55<30:25,  3.61it/s]
 12%|█▏        | 901/7488 [03:55<30:25,  3.61it/s]
 12%|█▏        | 902/7488 [03:55<30:25,  3.61it/s]
 12%|█▏        | 903/7488 [03:55<30:25,  3.61it/s]
 12%|█▏        | 904/7488 [03:55<30:24,  3.61it/s]
 12%|█▏        | 905/7488 [03:55<30:24,  3.61it/s]

 12%|█▏        | 906/7488 [03:56<13:47,  7.95it/s]

 12%|█▏        | 906/7488 [03:56<13:47,  7.95it/s]
 12%|█▏        | 907/7488 [03:56<13:47,  7.95it/s]

 12%|█▏        | 908/7488 [03:57<17:02,  6.43it/s]

 12%|█▏        | 908/7488 [03:57<17:02,  6.43it/s]
 12%|█▏        | 909/7488 [03:57<17:02,  6.43it/s]

 12%|█▏        | 910/7488 [03:57<19:51,  5.52it/s]

 12%|█▏        | 910/7488 [03:57<19:51,  5.52it/s]
 12%|█▏        | 911/7488 [03:57<19:50,  5.52it/s]
 12%|█▏        | 912/7488 [03:57<19:50,  5.52it/s]

 12%|█▏        | 913/7488 [03:58<20:54,  5.24it/s]

 12%|█▏        | 913/7488 [03:58<20:54,  5.24it/s]
 12%|█▏        | 914/7488 [03:58<20:54,  5.24it/s]

 12%|█▏        | 915/7488 [03:59<25:46,  4.25it/s]

 12%|█▏        | 915/7488 [03:59<25:46,  4.25it/s]
 12%|█▏        | 916/7488 [03:59<25:46,  4.25it/s]

 12%|█▏        | 917/7488 [04:01<54:31,  2.01it/s]

 12%|█▏        | 917/7488 [04:01<54:31,  2.01it/s]
 12%|█▏        | 918/7488 [04:01<54:30,  2.01it/s]

 12%|█▏        | 919/7488 [04:02<49:24,  2.22it/s]

 12%|█▏        | 919/7488 [04:02<49:24,  2.22it/s]
 12%|█▏        | 920/7488 [04:02<49:23,  2.22it/s]

 12%|█▏        | 921/7488 [04:03<45:42,  2.39it/s]

 12%|█▏        | 921/7488 [04:03<45:42,  2.39it/s]
 12%|█▏        | 922/7488 [04:03<45:41,  2.39it/s]
 12%|█▏        | 923/7488 [04:03<45:41,  2.39it/s]

 12%|█▏        | 924/7488 [04:03<36:58,  2.96it/s]

 12%|█▏        | 924/7488 [04:03<36:58,  2.96it/s]
 12%|█▏        | 925/7488 [04:03<36:58,  2.96it/s]

 12%|█▏        | 926/7488 [04:04<36:16,  3.02it/s]

 12%|█▏        | 926/7488 [04:04<36:16,  3.02it/s]
 12%|█▏        | 927/7488 [04:04<36:15,  3.02it/s]

 12%|█▏        | 928/7488 [04:04<35:27,  3.08it/s]

 12%|█▏        | 928/7488 [04:04<35:27,  3.08it/s]
 12%|█▏        | 929/7488 [04:04<35:27,  3.08it/s]

 12%|█▏        | 930/7488 [04:05<35:20,  3.09it/s]

 12%|█▏        | 930/7488 [04:05<35:20,  3.09it/s]
 12%|█▏        | 931/7488 [04:05<35:19,  3.09it/s]

 12%|█▏        | 932/7488 [04:06<35:35,  3.07it/s]

 12%|█▏        | 932/7488 [04:06<35:35,  3.07it/s]
 12%|█▏        | 933/7488 [04:06<35:35,  3.07it/s]

 12%|█▏        | 934/7488 [04:06<34:53,  3.13it/s]

 12%|█▏        | 934/7488 [04:06<34:53,  3.13it/s]
 12%|█▏        | 935/7488 [04:06<34:53,  3.13it/s]
 12%|█▎        | 936/7488 [04:06<34:52,  3.13it/s]

 13%|█▎        | 937/7488 [04:07<30:14,  3.61it/s]

 13%|█▎        | 937/7488 [04:07<30:14,  3.61it/s]
 13%|█▎        | 938/7488 [04:07<30:14,  3.61it/s]

 13%|█▎        | 939/7488 [04:08<30:52,  3.53it/s]

 13%|█▎        | 939/7488 [04:08<30:52,  3.53it/s]
 13%|█▎        | 940/7488 [04:08<30:52,  3.53it/s]

 13%|█▎        | 941/7488 [04:08<32:20,  3.37it/s]

 13%|█▎        | 941/7488 [04:08<32:20,  3.37it/s]
 13%|█▎        | 942/7488 [04:08<32:19,  3.37it/s]
 13%|█▎        | 943/7488 [04:08<32:19,  3.37it/s]

 13%|█▎        | 944/7488 [04:09<29:59,  3.64it/s]

 13%|█▎        | 944/7488 [04:09<29:59,  3.64it/s]
 13%|█▎        | 945/7488 [04:09<29:59,  3.64it/s]
 13%|█▎        | 946/7488 [04:09<29:58,  3.64it/s]

 13%|█▎        | 947/7488 [04:10<27:33,  3.96it/s]

 13%|█▎        | 947/7488 [04:10<27:33,  3.96it/s]
 13%|█▎        | 948/7488 [04:10<27:33,  3.96it/s]
 13%|█▎        | 949/7488 [04:10<27:33,  3.96it/s]

 13%|█▎        | 950/7488 [04:10<26:28,  4.12it/s]

 13%|█▎        | 950/7488 [04:10<26:28,  4.12it/s]
 13%|█▎        | 951/7488 [04:10<26:27,  4.12it/s]
 13%|█▎        | 952/7488 [04:10<26:27,  4.12it/s]
 13%|█▎        | 953/7488 [04:10<26:27,  4.12it/s]

 13%|█▎        | 954/7488 [04:11<23:22,  4.66it/s]

 13%|█▎        | 954/7488 [04:11<23:22,  4.66it/s]
 13%|█▎        | 955/7488 [04:11<23:22,  4.66it/s]

 13%|█▎        | 956/7488 [04:14<52:57,  2.06it/s]

 13%|█▎        | 956/7488 [04:14<52:57,  2.06it/s]
 13%|█▎        | 957/7488 [04:14<52:56,  2.06it/s]

 13%|█▎        | 958/7488 [04:15<48:40,  2.24it/s]

 13%|█▎        | 958/7488 [04:15<48:40,  2.24it/s]
 13%|█▎        | 959/7488 [04:15<48:39,  2.24it/s]

 13%|█▎        | 960/7488 [04:15<44:52,  2.42it/s]

 13%|█▎        | 960/7488 [04:15<44:52,  2.42it/s]
 13%|█▎        | 961/7488 [04:15<44:51,  2.42it/s]

 13%|█▎        | 962/7488 [04:16<41:57,  2.59it/s]

 13%|█▎        | 962/7488 [04:16<41:57,  2.59it/s]
 13%|█▎        | 963/7488 [04:16<41:57,  2.59it/s]
 13%|█▎        | 964/7488 [04:16<41:57,  2.59it/s]

 13%|█▎        | 965/7488 [04:16<35:13,  3.09it/s]

 13%|█▎        | 965/7488 [04:16<35:13,  3.09it/s]
 13%|█▎        | 966/7488 [04:16<35:13,  3.09it/s]

 13%|█▎        | 967/7488 [04:17<34:30,  3.15it/s]

 13%|█▎        | 967/7488 [04:17<34:30,  3.15it/s]
 13%|█▎        | 968/7488 [04:17<34:30,  3.15it/s]
 13%|█▎        | 969/7488 [04:17<34:30,  3.15it/s]
 13%|█▎        | 970/7488 [04:17<34:29,  3.15it/s]

 13%|█▎        | 971/7488 [04:18<27:30,  3.95it/s]

 13%|█▎        | 971/7488 [04:18<27:30,  3.95it/s]
 13%|█▎        | 972/7488 [04:18<27:29,  3.95it/s]
 13%|█▎        | 973/7488 [04:18<27:29,  3.95it/s]

 13%|█▎        | 974/7488 [04:18<26:06,  4.16it/s]

 13%|█▎        | 974/7488 [04:18<26:06,  4.16it/s]
 13%|█▎        | 975/7488 [04:18<26:06,  4.16it/s]
 13%|█▎        | 976/7488 [04:18<26:05,  4.16it/s]
 13%|█▎        | 977/7488 [04:18<26:05,  4.16it/s]
 13%|█▎        | 978/7488 [04:18<26:05,  4.16it/s]
 13%|█▎        | 979/7488 [04:18<26:05,  4.16it/s]

 13%|█▎        | 980/7488 [04:19<19:01,  5.70it/s]

 13%|█▎        | 980/7488 [04:19<19:01,  5.70it/s]
 13%|█▎        | 981/7488 [04:19<19:01,  5.70it/s]

 13%|█▎        | 982/7488 [04:20<21:40,  5.00it/s]

 13%|█▎        | 982/7488 [04:20<21:40,  5.00it/s]
 13%|█▎        | 983/7488 [04:20<21:40,  5.00it/s]

 13%|█▎        | 984/7488 [04:20<24:02,  4.51it/s]

 13%|█▎        | 984/7488 [04:20<24:02,  4.51it/s]
 13%|█▎        | 985/7488 [04:20<24:02,  4.51it/s]

 13%|█▎        | 986/7488 [04:21<26:28,  4.09it/s]

 13%|█▎        | 986/7488 [04:21<26:28,  4.09it/s]
 13%|█▎        | 987/7488 [04:21<26:28,  4.09it/s]
 13%|█▎        | 988/7488 [04:21<26:27,  4.09it/s]

 13%|█▎        | 989/7488 [04:21<25:13,  4.29it/s]

 13%|█▎        | 989/7488 [04:21<25:13,  4.29it/s]
 13%|█▎        | 990/7488 [04:21<25:13,  4.29it/s]

 13%|█▎        | 991/7488 [04:22<27:28,  3.94it/s]

 13%|█▎        | 991/7488 [04:22<27:28,  3.94it/s]
 13%|█▎        | 992/7488 [04:22<27:27,  3.94it/s]

 13%|█▎        | 1000/7488 [04:23<28:28,  3.80it/s]
 33%|███▎      | 3/9 [13:39<27:18, 273.03s/it]

 13%|█▎        | 993/7488 [04:23<29:02,  3.73it/s]
 13%|█▎        | 994/7488 [04:23<29:01,  3.73it/s]
 13%|█▎        | 995/7488 [04:23<29:01,  3.73it/s]
 13%|█▎        | 996/7488 [04:23<29:01,  3.73it/s]
 13%|█▎        | 997/7488 [04:23<29:01,  3.73it/s]
 13%|█▎        | 998/7488 [04:23<29:00,  3.73it/s]
 13%|█▎        | 999/7488 [04:23<29:00,  3.73it/s]
 13%|█▎        | 1000/7488 [04:23<29:00,  3.73it/s]
                     MLUT4_AT.232A  MLUT4_RQ.2BTLS  MLUT4_TE.252A  \
Time
2025-05-25 05:20:05       0.852984        0.855904       0.842414
2025-05-25 05:30:05       0.876511        0.874611       0.847393
2025-05-25 05:35:05       0.877479        0.885625       0.860507
2025-05-25 05:40:05       0.878625        0.849563       0.860377
2025-05-25 05:45:05       0.877141        0.871733       0.849503

                     MLUT4_SIV.B7921  MLUT4_AIA792101B  MLUT4_PDT.956  \
Time
2025-05-25 05:20:05         0.903258          0.872434       0.899219
2025-05-25 05:30:05         0.903158          0.872244       0.916372
2025-05-25 05:35:05         0.903349          0.872158       0.914016
2025-05-25 05:40:05         0.903300          0.872148       0.910043
2025-05-25 05:45:05         0.903219          0.872148       0.914286

                     MLUT4_TE.252F  MLUT4_PT.231  MLUT4_FIC.231C  \
Time
2025-05-25 05:20:05       0.887579      0.869354        0.857897
2025-05-25 05:30:05       0.879727      0.867235        0.857888
2025-05-25 05:35:05       0.893944      0.867041        0.857883
2025-05-25 05:40:05       0.872940      0.866275        0.857879
2025-05-25 05:45:05       0.876962      0.865383        0.857874

                     MLUT4_FIC.231A  ...  DeSOx_2nd  MLUT4_AIC.232B  \
Time                                 ...
2025-05-25 05:20:05        0.859975  ...   0.890482       85.012138
2025-05-25 05:30:05        0.856716  ...   0.890808       88.954571
2025-05-25 05:35:05        0.860662  ...   0.890581       93.745851
2025-05-25 05:40:05        0.859286  ...   0.889486       85.305571
2025-05-25 05:45:05        0.859582  ...   0.888796      101.874866

                     MLUT4_AT.240  prev_target  MLUT4_AT-240  prediction  \
Time
2025-05-25 05:20:05     14.151761     0.888806      9.310345    0.887177
2025-05-25 05:30:05      9.316637     0.890104      9.713133    0.886360
2025-05-25 05:35:05      6.155893     0.890862     10.257539    0.888668
2025-05-25 05:40:05     12.572007     0.891577      9.427424    0.889396
2025-05-25 05:45:05      5.497275     0.891864     11.328917    0.888820

                     abs_error  threshold  y3_prediction  y3_abs_error
Time
2025-05-25 05:20:05   0.003305   0.003305       9.591320      0.280975
2025-05-25 05:30:05   0.004448   0.004334      10.108820      0.395687
2025-05-25 05:35:05   0.001913   0.001913      10.436868      0.179329
2025-05-25 05:40:05   0.000091   0.001731       9.435157      0.007732
2025-05-25 05:45:05   0.000024   0.001548      11.326485      0.002432

[5 rows x 50 columns]

  0%|          | 0/7486 [00:00<?, ?it/s]

  0%|          | 0/7486 [00:00<?, ?it/s]

  0%|          | 1/7486 [00:00<1:19:42,  1.57it/s]

  0%|          | 1/7486 [00:00<1:19:42,  1.57it/s]
  0%|          | 2/7486 [00:00<1:19:41,  1.57it/s]

  0%|          | 3/7486 [00:01<47:17,  2.64it/s]

  0%|          | 3/7486 [00:01<47:17,  2.64it/s]
  0%|          | 4/7486 [00:01<47:17,  2.64it/s]

  0%|          | 5/7486 [00:01<42:11,  2.95it/s]

  0%|          | 5/7486 [00:01<42:11,  2.95it/s]
  0%|          | 6/7486 [00:01<42:11,  2.95it/s]

  0%|          | 7/7486 [00:02<39:58,  3.12it/s]

  0%|          | 7/7486 [00:02<39:58,  3.12it/s]
  0%|          | 8/7486 [00:02<39:58,  3.12it/s]
  0%|          | 9/7486 [00:02<39:57,  3.12it/s]

  0%|          | 10/7486 [00:03<32:35,  3.82it/s]

  0%|          | 10/7486 [00:03<32:35,  3.82it/s]
  0%|          | 11/7486 [00:03<32:35,  3.82it/s]

  0%|          | 12/7486 [00:03<32:52,  3.79it/s]

  0%|          | 12/7486 [00:03<32:52,  3.79it/s]
  0%|          | 13/7486 [00:03<32:51,  3.79it/s]
  0%|          | 14/7486 [00:03<32:51,  3.79it/s]

  0%|          | 15/7486 [00:04<29:14,  4.26it/s]

  0%|          | 15/7486 [00:04<29:14,  4.26it/s]
  0%|          | 16/7486 [00:04<29:13,  4.26it/s]

  0%|          | 17/7486 [00:04<30:02,  4.14it/s]

  0%|          | 17/7486 [00:04<30:02,  4.14it/s]
  0%|          | 18/7486 [00:04<30:02,  4.14it/s]

  0%|          | 19/7486 [00:05<31:23,  3.96it/s]

  0%|          | 19/7486 [00:05<31:23,  3.96it/s]
  0%|          | 20/7486 [00:05<31:23,  3.96it/s]

  0%|          | 21/7486 [00:05<31:59,  3.89it/s]

  0%|          | 21/7486 [00:05<31:59,  3.89it/s]
  0%|          | 22/7486 [00:05<31:59,  3.89it/s]

  0%|          | 23/7486 [00:06<33:00,  3.77it/s]

  0%|          | 23/7486 [00:06<33:00,  3.77it/s]
  0%|          | 24/7486 [00:06<32:59,  3.77it/s]

  0%|          | 25/7486 [00:06<33:43,  3.69it/s]

  0%|          | 25/7486 [00:06<33:43,  3.69it/s]
  0%|          | 26/7486 [00:06<33:43,  3.69it/s]

  0%|          | 27/7486 [00:07<33:22,  3.72it/s]

  0%|          | 27/7486 [00:07<33:22,  3.72it/s]
  0%|          | 28/7486 [00:07<33:22,  3.72it/s]

  0%|          | 29/7486 [00:07<34:14,  3.63it/s]

  0%|          | 29/7486 [00:07<34:14,  3.63it/s]
  0%|          | 30/7486 [00:08<34:14,  3.63it/s]

  0%|          | 31/7486 [00:08<34:04,  3.65it/s]

  0%|          | 31/7486 [00:08<34:04,  3.65it/s]
  0%|          | 32/7486 [00:08<34:04,  3.65it/s]

  0%|          | 33/7486 [00:11<1:15:53,  1.64it/s]

  0%|          | 33/7486 [00:11<1:15:53,  1.64it/s]
  0%|          | 34/7486 [00:11<1:15:52,  1.64it/s]
  0%|          | 35/7486 [00:11<1:15:52,  1.64it/s]

  0%|          | 36/7486 [00:11<55:00,  2.26it/s]

  0%|          | 36/7486 [00:11<55:00,  2.26it/s]
  0%|          | 37/7486 [00:11<55:00,  2.26it/s]
  1%|          | 38/7486 [00:11<54:59,  2.26it/s]
  1%|          | 39/7486 [00:11<54:59,  2.26it/s]
  1%|          | 40/7486 [00:11<54:58,  2.26it/s]
  1%|          | 41/7486 [00:11<54:58,  2.26it/s]

  1%|          | 42/7486 [00:12<32:20,  3.84it/s]

  1%|          | 42/7486 [00:12<32:20,  3.84it/s]
  1%|          | 43/7486 [00:12<32:19,  3.84it/s]

  1%|          | 44/7486 [00:12<32:10,  3.86it/s]

  1%|          | 44/7486 [00:12<32:10,  3.86it/s]
  1%|          | 45/7486 [00:12<32:09,  3.86it/s]

  1%|          | 46/7486 [00:13<32:33,  3.81it/s]

  1%|          | 46/7486 [00:13<32:33,  3.81it/s]
  1%|          | 47/7486 [00:13<32:33,  3.81it/s]

  1%|          | 48/7486 [00:14<32:28,  3.82it/s]

  1%|          | 48/7486 [00:14<32:28,  3.82it/s]
  1%|          | 49/7486 [00:14<32:28,  3.82it/s]

  1%|          | 50/7486 [00:14<32:55,  3.76it/s]

  1%|          | 50/7486 [00:14<32:55,  3.76it/s]
  1%|          | 51/7486 [00:14<32:55,  3.76it/s]

  1%|          | 52/7486 [00:15<32:26,  3.82it/s]

  1%|          | 52/7486 [00:15<32:26,  3.82it/s]
  1%|          | 53/7486 [00:15<32:26,  3.82it/s]
  1%|          | 54/7486 [00:15<32:25,  3.82it/s]
  1%|          | 55/7486 [00:15<32:25,  3.82it/s]
  1%|          | 56/7486 [00:15<32:25,  3.82it/s]
  1%|          | 57/7486 [00:15<32:25,  3.82it/s]
  1%|          | 58/7486 [00:15<32:24,  3.82it/s]
  1%|          | 59/7486 [00:15<32:24,  3.82it/s]
  1%|          | 60/7486 [00:15<32:24,  3.82it/s]
  1%|          | 61/7486 [00:15<32:24,  3.82it/s]

  1%|          | 62/7486 [00:15<15:41,  7.89it/s]

  1%|          | 62/7486 [00:15<15:41,  7.89it/s]
  1%|          | 63/7486 [00:15<15:41,  7.89it/s]

  1%|          | 64/7486 [00:16<18:24,  6.72it/s]

  1%|          | 64/7486 [00:16<18:24,  6.72it/s]
  1%|          | 65/7486 [00:16<18:24,  6.72it/s]

  1%|          | 66/7486 [00:16<21:26,  5.77it/s]

  1%|          | 66/7486 [00:16<21:26,  5.77it/s]
  1%|          | 67/7486 [00:16<21:25,  5.77it/s]

  1%|          | 68/7486 [00:17<23:38,  5.23it/s]

  1%|          | 68/7486 [00:17<23:38,  5.23it/s]
  1%|          | 69/7486 [00:17<23:38,  5.23it/s]
  1%|          | 70/7486 [00:17<23:37,  5.23it/s]
  1%|          | 71/7486 [00:17<23:37,  5.23it/s]
  1%|          | 72/7486 [00:17<23:37,  5.23it/s]
  1%|          | 73/7486 [00:17<23:37,  5.23it/s]
  1%|          | 74/7486 [00:17<23:37,  5.23it/s]
  1%|          | 75/7486 [00:17<23:36,  5.23it/s]
  1%|          | 76/7486 [00:17<23:36,  5.23it/s]
  1%|          | 77/7486 [00:17<23:36,  5.23it/s]
  1%|          | 78/7486 [00:17<23:36,  5.23it/s]
  1%|          | 79/7486 [00:17<23:36,  5.23it/s]
  1%|          | 80/7486 [00:17<23:36,  5.23it/s]

  1%|          | 81/7486 [00:17<12:06, 10.19it/s]

  1%|          | 81/7486 [00:17<12:06, 10.19it/s]
  1%|          | 82/7486 [00:17<12:06, 10.19it/s]

  1%|          | 83/7486 [00:18<15:21,  8.04it/s]

  1%|          | 83/7486 [00:18<15:21,  8.04it/s]
  1%|          | 84/7486 [00:18<15:21,  8.04it/s]
  1%|          | 85/7486 [00:18<15:20,  8.04it/s]

  1%|          | 86/7486 [00:19<17:25,  7.08it/s]

  1%|          | 86/7486 [00:19<17:25,  7.08it/s]
  1%|          | 87/7486 [00:19<17:25,  7.08it/s]

  1%|          | 88/7486 [00:19<21:03,  5.85it/s]

  1%|          | 88/7486 [00:19<21:03,  5.85it/s]
  1%|          | 89/7486 [00:19<21:03,  5.85it/s]
  1%|          | 90/7486 [00:19<21:03,  5.85it/s]

  1%|          | 91/7486 [00:20<22:07,  5.57it/s]

  1%|          | 91/7486 [00:20<22:07,  5.57it/s]
  1%|          | 92/7486 [00:20<22:07,  5.57it/s]
  1%|          | 93/7486 [00:20<22:07,  5.57it/s]

  1%|▏         | 94/7486 [00:21<23:19,  5.28it/s]

  1%|▏         | 94/7486 [00:21<23:19,  5.28it/s]
  1%|▏         | 95/7486 [00:21<23:19,  5.28it/s]

  1%|▏         | 96/7486 [00:23<56:01,  2.20it/s]

  1%|▏         | 96/7486 [00:23<56:01,  2.20it/s]
  1%|▏         | 97/7486 [00:23<56:00,  2.20it/s]

  1%|▏         | 98/7486 [00:24<51:59,  2.37it/s]

  1%|▏         | 98/7486 [00:24<51:59,  2.37it/s]
  1%|▏         | 99/7486 [00:24<51:58,  2.37it/s]

  1%|▏         | 100/7486 [00:25<49:09,  2.50it/s]

  1%|▏         | 100/7486 [00:25<49:09,  2.50it/s]
  1%|▏         | 101/7486 [00:25<49:08,  2.50it/s]

  1%|▏         | 102/7486 [00:25<46:52,  2.63it/s]

  1%|▏         | 102/7486 [00:25<46:52,  2.63it/s]
  1%|▏         | 103/7486 [00:25<46:51,  2.63it/s]

  1%|▏         | 104/7486 [00:26<44:13,  2.78it/s]

  1%|▏         | 104/7486 [00:26<44:13,  2.78it/s]
  1%|▏         | 105/7486 [00:26<44:12,  2.78it/s]

  1%|▏         | 106/7486 [00:27<42:56,  2.86it/s]

  1%|▏         | 106/7486 [00:27<42:56,  2.86it/s]
  1%|▏         | 107/7486 [00:27<42:56,  2.86it/s]

  1%|▏         | 108/7486 [00:27<41:44,  2.95it/s]

  1%|▏         | 108/7486 [00:27<41:44,  2.95it/s]
  1%|▏         | 109/7486 [00:27<41:44,  2.95it/s]

  1%|▏         | 110/7486 [00:28<41:30,  2.96it/s]

  1%|▏         | 110/7486 [00:28<41:30,  2.96it/s]
  1%|▏         | 111/7486 [00:28<41:29,  2.96it/s]

  1%|▏         | 112/7486 [00:29<41:30,  2.96it/s]

  1%|▏         | 112/7486 [00:29<41:30,  2.96it/s]
  2%|▏         | 113/7486 [00:29<41:30,  2.96it/s]
  2%|▏         | 114/7486 [00:29<41:29,  2.96it/s]

  2%|▏         | 115/7486 [00:29<35:36,  3.45it/s]

  2%|▏         | 115/7486 [00:29<35:36,  3.45it/s]
  2%|▏         | 116/7486 [00:29<35:36,  3.45it/s]

  2%|▏         | 117/7486 [00:30<36:48,  3.34it/s]

  2%|▏         | 117/7486 [00:30<36:48,  3.34it/s]
  2%|▏         | 118/7486 [00:30<36:48,  3.34it/s]

  2%|▏         | 119/7486 [00:31<39:05,  3.14it/s]

  2%|▏         | 119/7486 [00:31<39:05,  3.14it/s]
  2%|▏         | 120/7486 [00:31<39:05,  3.14it/s]

  2%|▏         | 121/7486 [00:31<38:55,  3.15it/s]

  2%|▏         | 121/7486 [00:31<38:55,  3.15it/s]
  2%|▏         | 122/7486 [00:31<38:55,  3.15it/s]
  2%|▏         | 123/7486 [00:31<38:54,  3.15it/s]

  2%|▏         | 124/7486 [00:32<34:15,  3.58it/s]

  2%|▏         | 124/7486 [00:32<34:15,  3.58it/s]
  2%|▏         | 125/7486 [00:32<34:15,  3.58it/s]

  2%|▏         | 126/7486 [00:33<35:12,  3.48it/s]

  2%|▏         | 126/7486 [00:33<35:12,  3.48it/s]
  2%|▏         | 127/7486 [00:33<35:11,  3.48it/s]
  2%|▏         | 128/7486 [00:33<35:11,  3.48it/s]

  2%|▏         | 129/7486 [00:33<31:36,  3.88it/s]

  2%|▏         | 129/7486 [00:33<31:36,  3.88it/s]
  2%|▏         | 130/7486 [00:33<31:35,  3.88it/s]

  2%|▏         | 131/7486 [00:36<1:09:46,  1.76it/s]

  2%|▏         | 131/7486 [00:36<1:09:46,  1.76it/s]
  2%|▏         | 132/7486 [00:36<1:09:45,  1.76it/s]

  2%|▏         | 133/7486 [00:37<1:00:47,  2.02it/s]

  2%|▏         | 133/7486 [00:37<1:00:47,  2.02it/s]
  2%|▏         | 134/7486 [00:37<1:00:47,  2.02it/s]

  2%|▏         | 135/7486 [00:37<54:36,  2.24it/s]

  2%|▏         | 135/7486 [00:37<54:36,  2.24it/s]
  2%|▏         | 136/7486 [00:37<54:35,  2.24it/s]
  2%|▏         | 137/7486 [00:37<54:35,  2.24it/s]
  2%|▏         | 138/7486 [00:37<54:35,  2.24it/s]
  2%|▏         | 139/7486 [00:37<54:34,  2.24it/s]
  2%|▏         | 140/7486 [00:37<54:34,  2.24it/s]
  2%|▏         | 141/7486 [00:37<54:33,  2.24it/s]

  2%|▏         | 142/7486 [00:38<28:52,  4.24it/s]

  2%|▏         | 142/7486 [00:38<28:52,  4.24it/s]
  2%|▏         | 143/7486 [00:38<28:51,  4.24it/s]

  2%|▏         | 144/7486 [00:39<30:26,  4.02it/s]

  2%|▏         | 144/7486 [00:39<30:26,  4.02it/s]
  2%|▏         | 145/7486 [00:39<30:26,  4.02it/s]

  2%|▏         | 146/7486 [00:39<32:05,  3.81it/s]

  2%|▏         | 146/7486 [00:39<32:05,  3.81it/s]
  2%|▏         | 147/7486 [00:39<32:05,  3.81it/s]

  2%|▏         | 148/7486 [00:40<32:59,  3.71it/s]

  2%|▏         | 148/7486 [00:40<32:59,  3.71it/s]
  2%|▏         | 149/7486 [00:40<32:58,  3.71it/s]

  2%|▏         | 150/7486 [00:40<33:56,  3.60it/s]

  2%|▏         | 150/7486 [00:40<33:56,  3.60it/s]
  2%|▏         | 151/7486 [00:40<33:56,  3.60it/s]
  2%|▏         | 152/7486 [00:40<33:55,  3.60it/s]
  2%|▏         | 153/7486 [00:40<33:55,  3.60it/s]
  2%|▏         | 154/7486 [00:40<33:55,  3.60it/s]
  2%|▏         | 155/7486 [00:40<33:55,  3.60it/s]
  2%|▏         | 156/7486 [00:40<33:54,  3.60it/s]

  2%|▏         | 157/7486 [00:41<20:45,  5.88it/s]

  2%|▏         | 157/7486 [00:41<20:45,  5.88it/s]
  2%|▏         | 158/7486 [00:41<20:45,  5.88it/s]

  2%|▏         | 159/7486 [00:42<23:48,  5.13it/s]

  2%|▏         | 159/7486 [00:42<23:48,  5.13it/s]
  2%|▏         | 160/7486 [00:42<23:47,  5.13it/s]

  2%|▏         | 161/7486 [00:42<26:46,  4.56it/s]

  2%|▏         | 161/7486 [00:42<26:46,  4.56it/s]
  2%|▏         | 162/7486 [00:42<26:46,  4.56it/s]

  2%|▏         | 163/7486 [00:43<28:45,  4.24it/s]

  2%|▏         | 163/7486 [00:43<28:45,  4.24it/s]
  2%|▏         | 164/7486 [00:43<28:45,  4.24it/s]

  2%|▏         | 165/7486 [00:43<30:58,  3.94it/s]

  2%|▏         | 165/7486 [00:43<30:58,  3.94it/s]
  2%|▏         | 166/7486 [00:43<30:57,  3.94it/s]

  2%|▏         | 167/7486 [00:44<32:06,  3.80it/s]

  2%|▏         | 167/7486 [00:44<32:06,  3.80it/s]
  2%|▏         | 168/7486 [00:44<32:06,  3.80it/s]

  2%|▏         | 169/7486 [00:45<33:44,  3.61it/s]

  2%|▏         | 169/7486 [00:45<33:44,  3.61it/s]
  2%|▏         | 170/7486 [00:45<33:44,  3.61it/s]

  2%|▏         | 171/7486 [00:45<34:12,  3.56it/s]

  2%|▏         | 171/7486 [00:45<34:12,  3.56it/s]
  2%|▏         | 172/7486 [00:45<34:12,  3.56it/s]
  2%|▏         | 173/7486 [00:45<34:11,  3.56it/s]
  2%|▏         | 174/7486 [00:45<34:11,  3.56it/s]
  2%|▏         | 175/7486 [00:45<34:11,  3.56it/s]
  2%|▏         | 176/7486 [00:45<34:11,  3.56it/s]

  2%|▏         | 177/7486 [00:46<22:52,  5.32it/s]

  2%|▏         | 177/7486 [00:46<22:52,  5.32it/s]
  2%|▏         | 178/7486 [00:46<22:52,  5.32it/s]

  2%|▏         | 179/7486 [00:49<55:32,  2.19it/s]

  2%|▏         | 179/7486 [00:49<55:32,  2.19it/s]
  2%|▏         | 180/7486 [00:49<55:32,  2.19it/s]

  2%|▏         | 181/7486 [00:49<51:38,  2.36it/s]

  2%|▏         | 181/7486 [00:49<51:38,  2.36it/s]
  2%|▏         | 182/7486 [00:49<51:37,  2.36it/s]
  2%|▏         | 183/7486 [00:49<51:37,  2.36it/s]

  2%|▏         | 184/7486 [00:50<43:43,  2.78it/s]

  2%|▏         | 184/7486 [00:50<43:43,  2.78it/s]
  2%|▏         | 185/7486 [00:50<43:43,  2.78it/s]
  2%|▏         | 186/7486 [00:50<43:42,  2.78it/s]
  2%|▏         | 187/7486 [00:50<43:42,  2.78it/s]
  3%|▎         | 188/7486 [00:50<43:42,  2.78it/s]
  3%|▎         | 189/7486 [00:50<43:41,  2.78it/s]
  3%|▎         | 190/7486 [00:50<43:41,  2.78it/s]
  3%|▎         | 191/7486 [00:50<43:41,  2.78it/s]
  3%|▎         | 192/7486 [00:50<43:40,  2.78it/s]
  3%|▎         | 193/7486 [00:50<43:40,  2.78it/s]
  3%|▎         | 194/7486 [00:50<43:40,  2.78it/s]
  3%|▎         | 195/7486 [00:50<43:39,  2.78it/s]

  3%|▎         | 196/7486 [00:51<19:48,  6.14it/s]

  3%|▎         | 196/7486 [00:51<19:48,  6.14it/s]
  3%|▎         | 197/7486 [00:51<19:47,  6.14it/s]

  3%|▎         | 198/7486 [00:51<22:24,  5.42it/s]

  3%|▎         | 198/7486 [00:51<22:24,  5.42it/s]
  3%|▎         | 199/7486 [00:51<22:24,  5.42it/s]

  3%|▎         | 200/7486 [00:52<25:32,  4.76it/s]

  3%|▎         | 200/7486 [00:52<25:32,  4.76it/s]
  3%|▎         | 201/7486 [00:52<25:32,  4.76it/s]

  3%|▎         | 202/7486 [00:53<28:37,  4.24it/s]

  3%|▎         | 202/7486 [00:53<28:37,  4.24it/s]
  3%|▎         | 203/7486 [00:53<28:37,  4.24it/s]

  3%|▎         | 204/7486 [00:53<30:56,  3.92it/s]

  3%|▎         | 204/7486 [00:53<30:56,  3.92it/s]
  3%|▎         | 205/7486 [00:54<30:56,  3.92it/s]

  3%|▎         | 206/7486 [00:54<32:44,  3.71it/s]

  3%|▎         | 206/7486 [00:54<32:44,  3.71it/s]
  3%|▎         | 207/7486 [00:54<32:43,  3.71it/s]

  3%|▎         | 208/7486 [00:55<34:18,  3.54it/s]

  3%|▎         | 208/7486 [00:55<34:18,  3.54it/s]
  3%|▎         | 209/7486 [00:55<34:18,  3.54it/s]
  3%|▎         | 210/7486 [00:55<34:18,  3.54it/s]
  3%|▎         | 211/7486 [00:55<34:17,  3.54it/s]
  3%|▎         | 212/7486 [00:55<34:17,  3.54it/s]
  3%|▎         | 213/7486 [00:55<34:17,  3.54it/s]
  3%|▎         | 214/7486 [00:55<34:17,  3.54it/s]

  3%|▎         | 215/7486 [00:55<21:44,  5.57it/s]

  3%|▎         | 215/7486 [00:55<21:44,  5.57it/s]
  3%|▎         | 216/7486 [00:55<21:44,  5.57it/s]

  3%|▎         | 217/7486 [00:56<24:56,  4.86it/s]

  3%|▎         | 217/7486 [00:56<24:56,  4.86it/s]
  3%|▎         | 218/7486 [00:56<24:56,  4.86it/s]

  3%|▎         | 219/7486 [00:57<27:57,  4.33it/s]

  3%|▎         | 219/7486 [00:57<27:57,  4.33it/s]
  3%|▎         | 220/7486 [00:57<27:56,  4.33it/s]

  3%|▎         | 221/7486 [00:57<31:10,  3.88it/s]

  3%|▎         | 221/7486 [00:57<31:10,  3.88it/s]
  3%|▎         | 222/7486 [00:57<31:10,  3.88it/s]
  3%|▎         | 223/7486 [00:57<31:10,  3.88it/s]

  3%|▎         | 224/7486 [00:58<29:53,  4.05it/s]

  3%|▎         | 224/7486 [00:58<29:53,  4.05it/s]
  3%|▎         | 225/7486 [00:58<29:53,  4.05it/s]

  3%|▎         | 226/7486 [01:00<49:38,  2.44it/s]

  3%|▎         | 226/7486 [01:00<49:38,  2.44it/s]
  3%|▎         | 227/7486 [01:00<49:37,  2.44it/s]

  3%|▎         | 228/7486 [01:02<1:04:58,  1.86it/s]

  3%|▎         | 228/7486 [01:02<1:04:58,  1.86it/s]
  3%|▎         | 229/7486 [01:02<1:04:58,  1.86it/s]
  3%|▎         | 230/7486 [01:02<1:04:57,  1.86it/s]
  3%|▎         | 231/7486 [01:02<1:04:57,  1.86it/s]

  3%|▎         | 232/7486 [01:02<46:21,  2.61it/s]

  3%|▎         | 232/7486 [01:02<46:21,  2.61it/s]
  3%|▎         | 233/7486 [01:02<46:21,  2.61it/s]

  3%|▎         | 234/7486 [01:03<44:46,  2.70it/s]

  3%|▎         | 234/7486 [01:03<44:46,  2.70it/s]
  3%|▎         | 235/7486 [01:03<44:45,  2.70it/s]

  3%|▎         | 236/7486 [01:04<43:55,  2.75it/s]

  3%|▎         | 236/7486 [01:04<43:55,  2.75it/s]
  3%|▎         | 237/7486 [01:04<43:54,  2.75it/s]

  3%|▎         | 238/7486 [01:04<43:06,  2.80it/s]

  3%|▎         | 238/7486 [01:04<43:06,  2.80it/s]
  3%|▎         | 239/7486 [01:04<43:06,  2.80it/s]

  3%|▎         | 240/7486 [01:05<42:01,  2.87it/s]

  3%|▎         | 240/7486 [01:05<42:01,  2.87it/s]
  3%|▎         | 241/7486 [01:05<42:01,  2.87it/s]

  3%|▎         | 242/7486 [01:06<41:38,  2.90it/s]

  3%|▎         | 242/7486 [01:06<41:38,  2.90it/s]
  3%|▎         | 243/7486 [01:06<41:38,  2.90it/s]

  3%|▎         | 244/7486 [01:06<41:44,  2.89it/s]

  3%|▎         | 244/7486 [01:06<41:44,  2.89it/s]
  3%|▎         | 245/7486 [01:07<41:44,  2.89it/s]

  3%|▎         | 246/7486 [01:07<40:58,  2.94it/s]

  3%|▎         | 246/7486 [01:07<40:58,  2.94it/s]
  3%|▎         | 247/7486 [01:07<40:58,  2.94it/s]
  3%|▎         | 248/7486 [01:07<40:58,  2.94it/s]

  3%|▎         | 249/7486 [01:08<35:45,  3.37it/s]

  3%|▎         | 249/7486 [01:08<35:45,  3.37it/s]
  3%|▎         | 250/7486 [01:08<35:44,  3.37it/s]
  3%|▎         | 251/7486 [01:08<35:44,  3.37it/s]

  3%|▎         | 252/7486 [01:08<32:19,  3.73it/s]

  3%|▎         | 252/7486 [01:08<32:19,  3.73it/s]
  3%|▎         | 253/7486 [01:08<32:19,  3.73it/s]

  3%|▎         | 254/7486 [01:09<34:02,  3.54it/s]

  3%|▎         | 254/7486 [01:09<34:02,  3.54it/s]
  3%|▎         | 255/7486 [01:09<34:02,  3.54it/s]

  3%|▎         | 256/7486 [01:10<35:36,  3.38it/s]

  3%|▎         | 256/7486 [01:10<35:36,  3.38it/s]
  3%|▎         | 257/7486 [01:10<35:36,  3.38it/s]
  3%|▎         | 258/7486 [01:10<35:36,  3.38it/s]

  3%|▎         | 259/7486 [01:10<31:45,  3.79it/s]

  3%|▎         | 259/7486 [01:10<31:45,  3.79it/s]
  3%|▎         | 260/7486 [01:10<31:45,  3.79it/s]

  3%|▎         | 261/7486 [01:11<33:14,  3.62it/s]

  3%|▎         | 261/7486 [01:11<33:14,  3.62it/s]
  3%|▎         | 262/7486 [01:11<33:14,  3.62it/s]

  4%|▎         | 263/7486 [01:13<1:02:29,  1.93it/s]

  4%|▎         | 263/7486 [01:13<1:02:29,  1.93it/s]
  4%|▎         | 264/7486 [01:13<1:02:29,  1.93it/s]

  4%|▎         | 265/7486 [01:15<1:03:53,  1.88it/s]

  4%|▎         | 265/7486 [01:15<1:03:53,  1.88it/s]
  4%|▎         | 266/7486 [01:15<1:03:52,  1.88it/s]

  4%|▎         | 267/7486 [01:15<56:21,  2.14it/s]

  4%|▎         | 267/7486 [01:15<56:21,  2.14it/s]
  4%|▎         | 268/7486 [01:15<56:20,  2.14it/s]

  4%|▎         | 269/7486 [01:16<51:16,  2.35it/s]

  4%|▎         | 269/7486 [01:16<51:16,  2.35it/s]
  4%|▎         | 270/7486 [01:16<51:15,  2.35it/s]

  4%|▎         | 271/7486 [01:16<47:45,  2.52it/s]

  4%|▎         | 271/7486 [01:16<47:45,  2.52it/s]
  4%|▎         | 272/7486 [01:16<47:44,  2.52it/s]

  4%|▎         | 273/7486 [01:17<45:40,  2.63it/s]

  4%|▎         | 273/7486 [01:17<45:40,  2.63it/s]
  4%|▎         | 274/7486 [01:17<45:40,  2.63it/s]

  4%|▎         | 275/7486 [01:18<43:18,  2.77it/s]

  4%|▎         | 275/7486 [01:18<43:18,  2.77it/s]
  4%|▎         | 276/7486 [01:18<43:18,  2.77it/s]

  4%|▎         | 277/7486 [01:18<42:49,  2.81it/s]

  4%|▎         | 277/7486 [01:18<42:49,  2.81it/s]
  4%|▎         | 278/7486 [01:18<42:48,  2.81it/s]

  4%|▎         | 279/7486 [01:19<42:05,  2.85it/s]

  4%|▎         | 279/7486 [01:19<42:05,  2.85it/s]
  4%|▎         | 280/7486 [01:19<42:05,  2.85it/s]

  4%|▍         | 281/7486 [01:20<41:19,  2.91it/s]

  4%|▍         | 281/7486 [01:20<41:19,  2.91it/s]
  4%|▍         | 282/7486 [01:20<41:19,  2.91it/s]

  4%|▍         | 283/7486 [01:20<41:14,  2.91it/s]

  4%|▍         | 283/7486 [01:20<41:14,  2.91it/s]
  4%|▍         | 284/7486 [01:20<41:14,  2.91it/s]
  4%|▍         | 285/7486 [01:20<41:14,  2.91it/s]

  4%|▍         | 286/7486 [01:21<35:44,  3.36it/s]

  4%|▍         | 286/7486 [01:21<35:44,  3.36it/s]
  4%|▍         | 287/7486 [01:21<35:44,  3.36it/s]
  4%|▍         | 288/7486 [01:21<35:43,  3.36it/s]
  4%|▍         | 289/7486 [01:21<35:43,  3.36it/s]
  4%|▍         | 290/7486 [01:21<35:43,  3.36it/s]
  4%|▍         | 291/7486 [01:21<35:43,  3.36it/s]
  4%|▍         | 292/7486 [01:21<35:42,  3.36it/s]

  4%|▍         | 293/7486 [01:22<22:05,  5.43it/s]

  4%|▍         | 293/7486 [01:22<22:05,  5.43it/s]
  4%|▍         | 294/7486 [01:22<22:05,  5.43it/s]

  4%|▍         | 295/7486 [01:23<25:58,  4.61it/s]

  4%|▍         | 295/7486 [01:23<25:58,  4.61it/s]
  4%|▍         | 296/7486 [01:23<25:58,  4.61it/s]
  4%|▍         | 297/7486 [01:23<25:58,  4.61it/s]

  4%|▍         | 298/7486 [01:23<26:18,  4.55it/s]

  4%|▍         | 298/7486 [01:23<26:18,  4.55it/s]
  4%|▍         | 299/7486 [01:23<26:18,  4.55it/s]

  4%|▍         | 300/7486 [01:24<29:11,  4.10it/s]

  4%|▍         | 300/7486 [01:24<29:11,  4.10it/s]
  4%|▍         | 301/7486 [01:24<29:11,  4.10it/s]
  4%|▍         | 302/7486 [01:24<29:10,  4.10it/s]
  4%|▍         | 303/7486 [01:24<29:10,  4.10it/s]

  4%|▍         | 304/7486 [01:27<51:59,  2.30it/s]

  4%|▍         | 304/7486 [01:27<51:59,  2.30it/s]
  4%|▍         | 305/7486 [01:27<51:59,  2.30it/s]

  4%|▍         | 306/7486 [01:28<49:14,  2.43it/s]

  4%|▍         | 306/7486 [01:28<49:14,  2.43it/s]
  4%|▍         | 307/7486 [01:28<49:14,  2.43it/s]
  4%|▍         | 308/7486 [01:28<49:14,  2.43it/s]
  4%|▍         | 309/7486 [01:28<49:13,  2.43it/s]
  4%|▍         | 310/7486 [01:28<49:13,  2.43it/s]
  4%|▍         | 311/7486 [01:28<49:12,  2.43it/s]
  4%|▍         | 312/7486 [01:28<49:12,  2.43it/s]
  4%|▍         | 313/7486 [01:28<49:11,  2.43it/s]
  4%|▍         | 314/7486 [01:28<49:11,  2.43it/s]
  4%|▍         | 315/7486 [01:28<49:11,  2.43it/s]
  4%|▍         | 316/7486 [01:28<49:10,  2.43it/s]
  4%|▍         | 317/7486 [01:28<49:10,  2.43it/s]
  4%|▍         | 318/7486 [01:28<49:09,  2.43it/s]
  4%|▍         | 319/7486 [01:28<49:09,  2.43it/s]
  4%|▍         | 320/7486 [01:28<49:09,  2.43it/s]
  4%|▍         | 321/7486 [01:28<49:08,  2.43it/s]

  4%|▍         | 322/7486 [01:28<17:30,  6.82it/s]

  4%|▍         | 322/7486 [01:28<17:30,  6.82it/s]
  4%|▍         | 323/7486 [01:28<17:30,  6.82it/s]

  4%|▍         | 324/7486 [01:29<19:47,  6.03it/s]

  4%|▍         | 324/7486 [01:29<19:47,  6.03it/s]
  4%|▍         | 325/7486 [01:29<19:47,  6.03it/s]

  4%|▍         | 326/7486 [01:29<21:58,  5.43it/s]

  4%|▍         | 326/7486 [01:29<21:58,  5.43it/s]
  4%|▍         | 327/7486 [01:29<21:58,  5.43it/s]
  4%|▍         | 328/7486 [01:29<21:58,  5.43it/s]
  4%|▍         | 329/7486 [01:29<21:58,  5.43it/s]

  4%|▍         | 330/7486 [01:30<20:56,  5.70it/s]

  4%|▍         | 330/7486 [01:30<20:56,  5.70it/s]
  4%|▍         | 331/7486 [01:30<20:56,  5.70it/s]

  4%|▍         | 332/7486 [01:31<24:01,  4.96it/s]

  4%|▍         | 332/7486 [01:31<24:01,  4.96it/s]
  4%|▍         | 333/7486 [01:31<24:01,  4.96it/s]

  4%|▍         | 334/7486 [01:31<25:57,  4.59it/s]

  4%|▍         | 334/7486 [01:31<25:57,  4.59it/s]
  4%|▍         | 335/7486 [01:31<25:57,  4.59it/s]
  4%|▍         | 336/7486 [01:31<25:57,  4.59it/s]
  5%|▍         | 337/7486 [01:31<25:56,  4.59it/s]

  5%|▍         | 338/7486 [01:32<23:21,  5.10it/s]

  5%|▍         | 338/7486 [01:32<23:21,  5.10it/s]
  5%|▍         | 339/7486 [01:32<23:21,  5.10it/s]

  5%|▍         | 340/7486 [01:32<25:48,  4.61it/s]

  5%|▍         | 340/7486 [01:32<25:48,  4.61it/s]
  5%|▍         | 341/7486 [01:32<25:48,  4.61it/s]

  5%|▍         | 342/7486 [01:33<28:14,  4.22it/s]

  5%|▍         | 342/7486 [01:33<28:14,  4.22it/s]
  5%|▍         | 343/7486 [01:33<28:14,  4.22it/s]

  5%|▍         | 344/7486 [01:34<30:01,  3.96it/s]

  5%|▍         | 344/7486 [01:34<30:01,  3.96it/s]
  5%|▍         | 345/7486 [01:34<30:01,  3.96it/s]

  5%|▍         | 346/7486 [01:34<31:53,  3.73it/s]

  5%|▍         | 346/7486 [01:34<31:53,  3.73it/s]
  5%|▍         | 347/7486 [01:34<31:53,  3.73it/s]

  5%|▍         | 348/7486 [01:35<33:45,  3.52it/s]

  5%|▍         | 348/7486 [01:35<33:45,  3.52it/s]
  5%|▍         | 349/7486 [01:35<33:45,  3.52it/s]

  5%|▍         | 350/7486 [01:36<34:38,  3.43it/s]

  5%|▍         | 350/7486 [01:36<34:38,  3.43it/s]
  5%|▍         | 351/7486 [01:36<34:38,  3.43it/s]

  5%|▍         | 352/7486 [01:36<35:43,  3.33it/s]

  5%|▍         | 352/7486 [01:36<35:43,  3.33it/s]
  5%|▍         | 353/7486 [01:36<35:43,  3.33it/s]

  5%|▍         | 354/7486 [01:37<38:17,  3.10it/s]

  5%|▍         | 354/7486 [01:37<38:17,  3.10it/s]
  5%|▍         | 355/7486 [01:37<38:17,  3.10it/s]

  5%|▍         | 356/7486 [01:40<1:15:58,  1.56it/s]

  5%|▍         | 356/7486 [01:40<1:15:58,  1.56it/s]
  5%|▍         | 357/7486 [01:40<1:15:58,  1.56it/s]

  5%|▍         | 358/7486 [01:40<1:05:23,  1.82it/s]

  5%|▍         | 358/7486 [01:40<1:05:23,  1.82it/s]
  5%|▍         | 359/7486 [01:40<1:05:22,  1.82it/s]

  5%|▍         | 360/7486 [01:41<58:34,  2.03it/s]

  5%|▍         | 360/7486 [01:41<58:34,  2.03it/s]
  5%|▍         | 361/7486 [01:41<58:34,  2.03it/s]

  5%|▍         | 362/7486 [01:42<52:59,  2.24it/s]

  5%|▍         | 362/7486 [01:42<52:59,  2.24it/s]
  5%|▍         | 363/7486 [01:42<52:58,  2.24it/s]

  5%|▍         | 364/7486 [01:42<49:00,  2.42it/s]

  5%|▍         | 364/7486 [01:42<49:00,  2.42it/s]
  5%|▍         | 365/7486 [01:43<49:00,  2.42it/s]
  5%|▍         | 366/7486 [01:43<49:00,  2.42it/s]
  5%|▍         | 367/7486 [01:43<48:59,  2.42it/s]

  5%|▍         | 368/7486 [01:43<34:49,  3.41it/s]

  5%|▍         | 368/7486 [01:43<34:49,  3.41it/s]
  5%|▍         | 369/7486 [01:43<34:49,  3.41it/s]

  5%|▍         | 370/7486 [01:44<35:35,  3.33it/s]

  5%|▍         | 370/7486 [01:44<35:35,  3.33it/s]
  5%|▍         | 371/7486 [01:44<35:35,  3.33it/s]

  5%|▍         | 372/7486 [01:44<36:00,  3.29it/s]

  5%|▍         | 372/7486 [01:44<36:00,  3.29it/s]
  5%|▍         | 373/7486 [01:44<35:59,  3.29it/s]

  5%|▍         | 374/7486 [01:45<35:57,  3.30it/s]
  5%|▌         | 398/7486 [01:45<06:44, 17.51it/s]

  5%|▍         | 374/7486 [01:45<35:57,  3.30it/s]
  5%|▌         | 375/7486 [01:45<35:57,  3.30it/s]
  5%|▌         | 376/7486 [01:45<35:57,  3.30it/s]
  5%|▌         | 377/7486 [01:45<35:56,  3.30it/s]
  5%|▌         | 378/7486 [01:45<35:56,  3.30it/s]
  5%|▌         | 379/7486 [01:45<35:56,  3.30it/s]
  5%|▌         | 380/7486 [01:45<35:55,  3.30it/s]
  5%|▌         | 381/7486 [01:45<35:55,  3.30it/s]
  5%|▌         | 382/7486 [01:45<35:55,  3.30it/s]
  5%|▌         | 383/7486 [01:45<35:54,  3.30it/s]
  5%|▌         | 384/7486 [01:45<35:54,  3.30it/s]
  5%|▌         | 385/7486 [01:45<35:54,  3.30it/s]
  5%|▌         | 386/7486 [01:45<35:54,  3.30it/s]
  5%|▌         | 387/7486 [01:45<35:53,  3.30it/s]
  5%|▌         | 388/7486 [01:45<35:53,  3.30it/s]
  5%|▌         | 389/7486 [01:45<35:53,  3.30it/s]
  5%|▌         | 390/7486 [01:45<35:52,  3.30it/s]
  5%|▌         | 391/7486 [01:45<35:52,  3.30it/s]
  5%|▌         | 392/7486 [01:45<35:52,  3.30it/s]
  5%|▌         | 393/7486 [01:45<35:51,  3.30it/s]
  5%|▌         | 394/7486 [01:45<35:51,  3.30it/s]
  5%|▌         | 395/7486 [01:45<35:51,  3.30it/s]
  5%|▌         | 396/7486 [01:45<35:51,  3.30it/s]
  5%|▌         | 397/7486 [01:45<35:50,  3.30it/s]
  5%|▌         | 398/7486 [01:45<06:44, 17.51it/s]
  5%|▌         | 399/7486 [01:45<06:44, 17.51it/s]
  5%|▌         | 400/7486 [01:45<06:44, 17.51it/s]
  5%|▌         | 401/7486 [01:45<06:44, 17.51it/s]
  5%|▌         | 402/7486 [01:45<06:44, 17.51it/s]
  5%|▌         | 403/7486 [01:45<06:44, 17.51it/s]
  5%|▌         | 404/7486 [01:45<06:44, 17.51it/s]
  5%|▌         | 405/7486 [01:45<06:44, 17.51it/s]

  5%|▌         | 406/7486 [01:46<07:33, 15.62it/s]

  5%|▌         | 406/7486 [01:46<07:33, 15.62it/s]
  5%|▌         | 407/7486 [01:46<07:33, 15.62it/s]
  5%|▌         | 408/7486 [01:46<07:33, 15.62it/s]
  5%|▌         | 409/7486 [01:46<07:33, 15.62it/s]
  5%|▌         | 410/7486 [01:46<07:33, 15.62it/s]
  5%|▌         | 411/7486 [01:46<07:33, 15.62it/s]
  6%|▌         | 412/7486 [01:46<07:32, 15.62it/s]

  6%|▌         | 413/7486 [01:46<08:09, 14.44it/s]

  6%|▌         | 413/7486 [01:46<08:09, 14.44it/s]
  6%|▌         | 414/7486 [01:46<08:09, 14.44it/s]
  6%|▌         | 415/7486 [01:47<08:09, 14.44it/s]
  6%|▌         | 416/7486 [01:47<08:09, 14.44it/s]

  6%|▌         | 418/7486 [01:48<12:26,  9.46it/s]

  6%|▌         | 417/7486 [01:48<08:09, 14.44it/s]
  6%|▌         | 418/7486 [01:48<12:26,  9.46it/s]

  6%|▌         | 422/7486 [01:48<13:26,  8.76it/s]

  6%|▌         | 419/7486 [01:48<12:26,  9.46it/s]
  6%|▌         | 420/7486 [01:48<12:26,  9.46it/s]
  6%|▌         | 421/7486 [01:48<12:26,  9.46it/s]
  6%|▌         | 422/7486 [01:48<13:26,  8.76it/s]
  6%|▌         | 423/7486 [01:48<13:25,  8.76it/s]
  6%|▌         | 424/7486 [01:48<13:25,  8.76it/s]
  6%|▌         | 425/7486 [01:48<13:25,  8.76it/s]
  6%|▌         | 426/7486 [01:48<13:25,  8.76it/s]

  6%|▌         | 427/7486 [01:49<13:53,  8.47it/s]

  6%|▌         | 427/7486 [01:49<13:53,  8.47it/s]
  6%|▌         | 428/7486 [01:49<13:53,  8.47it/s]

  6%|▌         | 429/7486 [01:49<16:48,  7.00it/s]

  6%|▌         | 429/7486 [01:49<16:48,  7.00it/s]
  6%|▌         | 430/7486 [01:49<16:47,  7.00it/s]

  6%|▌         | 431/7486 [01:52<40:52,  2.88it/s]

  6%|▌         | 431/7486 [01:52<40:52,  2.88it/s]
  6%|▌         | 432/7486 [01:52<40:51,  2.88it/s]
  6%|▌         | 433/7486 [01:52<40:51,  2.88it/s]
  6%|▌         | 434/7486 [01:52<40:51,  2.88it/s]

  6%|▌         | 435/7486 [01:53<34:25,  3.41it/s]

  6%|▌         | 435/7486 [01:53<34:25,  3.41it/s]
  6%|▌         | 436/7486 [01:53<34:24,  3.41it/s]

  6%|▌         | 437/7486 [01:54<35:11,  3.34it/s]

  6%|▌         | 437/7486 [01:54<35:11,  3.34it/s]
  6%|▌         | 438/7486 [01:54<35:11,  3.34it/s]

  6%|▌         | 439/7486 [01:54<35:37,  3.30it/s]

  6%|▌         | 439/7486 [01:54<35:37,  3.30it/s]
  6%|▌         | 440/7486 [01:54<35:36,  3.30it/s]

  6%|▌         | 441/7486 [01:55<36:15,  3.24it/s]

  6%|▌         | 441/7486 [01:55<36:15,  3.24it/s]
  6%|▌         | 442/7486 [01:55<36:15,  3.24it/s]

  6%|▌         | 443/7486 [01:56<36:19,  3.23it/s]

  6%|▌         | 443/7486 [01:56<36:19,  3.23it/s]
  6%|▌         | 444/7486 [01:56<36:19,  3.23it/s]
  6%|▌         | 445/7486 [01:56<36:19,  3.23it/s]
  6%|▌         | 446/7486 [01:56<36:19,  3.23it/s]

  6%|▌         | 447/7486 [01:56<29:11,  4.02it/s]

  6%|▌         | 447/7486 [01:56<29:11,  4.02it/s]
  6%|▌         | 448/7486 [01:56<29:10,  4.02it/s]

  6%|▌         | 449/7486 [01:57<30:40,  3.82it/s]

  6%|▌         | 449/7486 [01:57<30:40,  3.82it/s]
  6%|▌         | 450/7486 [01:57<30:40,  3.82it/s]

  6%|▌         | 451/7486 [01:57<32:14,  3.64it/s]

  6%|▌         | 451/7486 [01:57<32:14,  3.64it/s]
  6%|▌         | 452/7486 [01:57<32:13,  3.64it/s]

  6%|▌         | 453/7486 [01:58<33:58,  3.45it/s]

  6%|▌         | 453/7486 [01:58<33:58,  3.45it/s]
  6%|▌         | 454/7486 [01:58<33:58,  3.45it/s]

  6%|▌         | 455/7486 [01:59<34:33,  3.39it/s]

  6%|▌         | 455/7486 [01:59<34:33,  3.39it/s]
  6%|▌         | 456/7486 [01:59<34:33,  3.39it/s]
  6%|▌         | 457/7486 [01:59<34:33,  3.39it/s]

  6%|▌         | 458/7486 [01:59<31:20,  3.74it/s]

  6%|▌         | 458/7486 [01:59<31:20,  3.74it/s]
  6%|▌         | 459/7486 [01:59<31:19,  3.74it/s]

  6%|▌         | 460/7486 [02:00<32:25,  3.61it/s]

  6%|▌         | 460/7486 [02:00<32:25,  3.61it/s]
  6%|▌         | 461/7486 [02:00<32:25,  3.61it/s]
  6%|▌         | 462/7486 [02:00<32:24,  3.61it/s]
  6%|▌         | 463/7486 [02:00<32:24,  3.61it/s]

  6%|▌         | 464/7486 [02:01<27:13,  4.30it/s]

  6%|▌         | 464/7486 [02:01<27:13,  4.30it/s]
  6%|▌         | 465/7486 [02:01<27:12,  4.30it/s]

  6%|▌         | 466/7486 [02:01<29:28,  3.97it/s]

  6%|▌         | 466/7486 [02:01<29:28,  3.97it/s]
  6%|▌         | 467/7486 [02:01<29:27,  3.97it/s]
  6%|▋         | 468/7486 [02:01<29:27,  3.97it/s]
  6%|▋         | 469/7486 [02:01<29:27,  3.97it/s]
  6%|▋         | 470/7486 [02:01<29:27,  3.97it/s]
  6%|▋         | 471/7486 [02:01<29:26,  3.97it/s]

  6%|▋         | 472/7486 [02:02<20:28,  5.71it/s]

  6%|▋         | 472/7486 [02:02<20:28,  5.71it/s]
  6%|▋         | 473/7486 [02:02<20:28,  5.71it/s]

  6%|▋         | 474/7486 [02:05<45:54,  2.55it/s]

  6%|▋         | 474/7486 [02:05<45:54,  2.55it/s]
  6%|▋         | 475/7486 [02:05<45:53,  2.55it/s]

  6%|▋         | 476/7486 [02:05<46:05,  2.53it/s]

  6%|▋         | 476/7486 [02:05<46:05,  2.53it/s]
  6%|▋         | 477/7486 [02:05<46:05,  2.53it/s]

  6%|▋         | 478/7486 [02:06<43:46,  2.67it/s]

  6%|▋         | 478/7486 [02:06<43:46,  2.67it/s]
  6%|▋         | 479/7486 [02:06<43:45,  2.67it/s]

  6%|▋         | 480/7486 [02:07<42:03,  2.78it/s]

  6%|▋         | 480/7486 [02:07<42:03,  2.78it/s]
  6%|▋         | 481/7486 [02:07<42:02,  2.78it/s]

  6%|▋         | 482/7486 [02:07<40:04,  2.91it/s]

  6%|▋         | 482/7486 [02:07<40:04,  2.91it/s]
  6%|▋         | 483/7486 [02:07<40:04,  2.91it/s]
  6%|▋         | 484/7486 [02:07<40:03,  2.91it/s]

  6%|▋         | 485/7486 [02:08<34:17,  3.40it/s]

  6%|▋         | 485/7486 [02:08<34:17,  3.40it/s]
  6%|▋         | 486/7486 [02:08<34:16,  3.40it/s]

  7%|▋         | 487/7486 [02:08<34:01,  3.43it/s]

  7%|▋         | 487/7486 [02:08<34:01,  3.43it/s]
  7%|▋         | 488/7486 [02:08<34:01,  3.43it/s]

  7%|▋         | 489/7486 [02:09<34:45,  3.35it/s]

  7%|▋         | 489/7486 [02:09<34:45,  3.35it/s]
  7%|▋         | 490/7486 [02:09<34:45,  3.35it/s]

  7%|▋         | 491/7486 [02:10<35:44,  3.26it/s]

  7%|▋         | 491/7486 [02:10<35:44,  3.26it/s]
  7%|▋         | 492/7486 [02:10<35:43,  3.26it/s]

  7%|▋         | 493/7486 [02:10<35:23,  3.29it/s]

  7%|▋         | 493/7486 [02:10<35:23,  3.29it/s]
  7%|▋         | 494/7486 [02:10<35:23,  3.29it/s]

  7%|▋         | 495/7486 [02:11<36:11,  3.22it/s]

  7%|▋         | 495/7486 [02:11<36:11,  3.22it/s]
  7%|▋         | 496/7486 [02:11<36:11,  3.22it/s]
  7%|▋         | 497/7486 [02:11<36:10,  3.22it/s]

  7%|▋         | 498/7486 [02:12<30:59,  3.76it/s]

  7%|▋         | 498/7486 [02:12<30:59,  3.76it/s]
  7%|▋         | 499/7486 [02:12<30:59,  3.76it/s]
  7%|▋         | 500/7486 [02:12<30:58,  3.76it/s]

  7%|▋         | 501/7486 [02:12<28:23,  4.10it/s]

  7%|▋         | 501/7486 [02:12<28:23,  4.10it/s]
  7%|▋         | 502/7486 [02:12<28:23,  4.10it/s]

  7%|▋         | 503/7486 [02:13<29:45,  3.91it/s]

  7%|▋         | 503/7486 [02:13<29:45,  3.91it/s]
  7%|▋         | 504/7486 [02:13<29:45,  3.91it/s]

  7%|▋         | 505/7486 [02:13<31:09,  3.73it/s]

  7%|▋         | 505/7486 [02:13<31:09,  3.73it/s]
  7%|▋         | 506/7486 [02:13<31:09,  3.73it/s]

  7%|▋         | 507/7486 [02:14<32:19,  3.60it/s]

  7%|▋         | 507/7486 [02:14<32:19,  3.60it/s]
  7%|▋         | 508/7486 [02:14<32:19,  3.60it/s]

  7%|▋         | 509/7486 [02:14<32:49,  3.54it/s]

  7%|▋         | 509/7486 [02:14<32:49,  3.54it/s]
  7%|▋         | 510/7486 [02:15<32:48,  3.54it/s]

  7%|▋         | 511/7486 [02:17<1:00:30,  1.92it/s]

  7%|▋         | 511/7486 [02:17<1:00:30,  1.92it/s]
  7%|▋         | 512/7486 [02:17<1:00:30,  1.92it/s]

  7%|▋         | 513/7486 [02:18<1:02:38,  1.86it/s]

  7%|▋         | 513/7486 [02:18<1:02:38,  1.86it/s]
  7%|▋         | 514/7486 [02:18<1:02:37,  1.86it/s]

  7%|▋         | 515/7486 [02:18<54:20,  2.14it/s]

  7%|▋         | 515/7486 [02:18<54:20,  2.14it/s]
  7%|▋         | 516/7486 [02:18<54:20,  2.14it/s]

  7%|▋         | 517/7486 [02:19<47:55,  2.42it/s]

  7%|▋         | 517/7486 [02:19<47:55,  2.42it/s]
  7%|▋         | 518/7486 [02:19<47:54,  2.42it/s]

  7%|▋         | 519/7486 [02:20<44:18,  2.62it/s]

  7%|▋         | 519/7486 [02:20<44:18,  2.62it/s]
  7%|▋         | 520/7486 [02:20<44:18,  2.62it/s]

  7%|▋         | 521/7486 [02:20<41:13,  2.82it/s]

  7%|▋         | 521/7486 [02:20<41:13,  2.82it/s]
  7%|▋         | 522/7486 [02:20<41:13,  2.82it/s]

  7%|▋         | 523/7486 [02:21<38:49,  2.99it/s]

  7%|▋         | 523/7486 [02:21<38:49,  2.99it/s]
  7%|▋         | 524/7486 [02:21<38:49,  2.99it/s]

  7%|▋         | 525/7486 [02:21<38:05,  3.05it/s]

  7%|▋         | 525/7486 [02:21<38:05,  3.05it/s]
  7%|▋         | 526/7486 [02:21<38:05,  3.05it/s]

  7%|▋         | 527/7486 [02:22<36:12,  3.20it/s]

  7%|▋         | 527/7486 [02:22<36:12,  3.20it/s]
  7%|▋         | 528/7486 [02:22<36:12,  3.20it/s]

  7%|▋         | 529/7486 [02:23<35:37,  3.25it/s]

  7%|▋         | 529/7486 [02:23<35:37,  3.25it/s]
  7%|▋         | 530/7486 [02:23<35:37,  3.25it/s]

  7%|▋         | 531/7486 [02:23<35:05,  3.30it/s]

  7%|▋         | 531/7486 [02:23<35:05,  3.30it/s]
  7%|▋         | 532/7486 [02:23<35:05,  3.30it/s]

  7%|▋         | 533/7486 [02:24<35:27,  3.27it/s]

  7%|▋         | 533/7486 [02:24<35:27,  3.27it/s]
  7%|▋         | 534/7486 [02:24<35:26,  3.27it/s]

  7%|▋         | 535/7486 [02:24<35:20,  3.28it/s]

  7%|▋         | 535/7486 [02:24<35:20,  3.28it/s]
  7%|▋         | 536/7486 [02:24<35:19,  3.28it/s]

  7%|▋         | 537/7486 [02:25<34:53,  3.32it/s]

  7%|▋         | 537/7486 [02:25<34:53,  3.32it/s]
  7%|▋         | 538/7486 [02:25<34:53,  3.32it/s]

  7%|▋         | 539/7486 [02:26<35:10,  3.29it/s]

  7%|▋         | 539/7486 [02:26<35:10,  3.29it/s]
  7%|▋         | 540/7486 [02:26<35:09,  3.29it/s]

  7%|▋         | 541/7486 [02:26<34:38,  3.34it/s]

  7%|▋         | 541/7486 [02:26<34:38,  3.34it/s]
  7%|▋         | 542/7486 [02:26<34:37,  3.34it/s]

  7%|▋         | 543/7486 [02:27<34:59,  3.31it/s]

  7%|▋         | 543/7486 [02:27<34:59,  3.31it/s]
  7%|▋         | 544/7486 [02:27<34:59,  3.31it/s]

  7%|▋         | 545/7486 [02:27<34:41,  3.33it/s]

  7%|▋         | 545/7486 [02:27<34:41,  3.33it/s]
  7%|▋         | 546/7486 [02:27<34:41,  3.33it/s]
  7%|▋         | 547/7486 [02:27<34:40,  3.33it/s]

  7%|▋         | 548/7486 [02:30<1:04:40,  1.79it/s]

  7%|▋         | 548/7486 [02:30<1:04:40,  1.79it/s]
  7%|▋         | 549/7486 [02:30<1:04:39,  1.79it/s]

  7%|▋         | 550/7486 [02:31<57:13,  2.02it/s]

  7%|▋         | 550/7486 [02:31<57:13,  2.02it/s]
  7%|▋         | 551/7486 [02:31<57:13,  2.02it/s]

  7%|▋         | 552/7486 [02:32<50:35,  2.28it/s]

  7%|▋         | 552/7486 [02:32<50:35,  2.28it/s]
  7%|▋         | 553/7486 [02:32<50:34,  2.28it/s]
  7%|▋         | 554/7486 [02:32<50:34,  2.28it/s]

  7%|▋         | 555/7486 [02:32<40:40,  2.84it/s]

  7%|▋         | 555/7486 [02:32<40:40,  2.84it/s]
  7%|▋         | 556/7486 [02:32<40:40,  2.84it/s]

  7%|▋         | 557/7486 [02:33<38:40,  2.99it/s]

  7%|▋         | 557/7486 [02:33<38:40,  2.99it/s]
  7%|▋         | 558/7486 [02:33<38:40,  2.99it/s]
  7%|▋         | 559/7486 [02:33<38:39,  2.99it/s]
  7%|▋         | 560/7486 [02:33<38:39,  2.99it/s]

  7%|▋         | 561/7486 [02:33<29:38,  3.89it/s]

  7%|▋         | 561/7486 [02:33<29:38,  3.89it/s]
  8%|▊         | 562/7486 [02:33<29:38,  3.89it/s]

  8%|▊         | 563/7486 [02:34<31:06,  3.71it/s]

  8%|▊         | 563/7486 [02:34<31:06,  3.71it/s]
  8%|▊         | 564/7486 [02:34<31:06,  3.71it/s]

  8%|▊         | 565/7486 [02:35<31:54,  3.61it/s]

  8%|▊         | 565/7486 [02:35<31:54,  3.61it/s]
  8%|▊         | 566/7486 [02:35<31:54,  3.61it/s]

  8%|▊         | 567/7486 [02:35<32:54,  3.50it/s]

  8%|▊         | 567/7486 [02:35<32:54,  3.50it/s]
  8%|▊         | 568/7486 [02:35<32:54,  3.50it/s]
  8%|▊         | 569/7486 [02:35<32:54,  3.50it/s]
  8%|▊         | 570/7486 [02:35<32:53,  3.50it/s]

  8%|▊         | 571/7486 [02:36<26:25,  4.36it/s]

  8%|▊         | 571/7486 [02:36<26:25,  4.36it/s]
  8%|▊         | 572/7486 [02:36<26:25,  4.36it/s]

  8%|▊         | 573/7486 [02:36<29:01,  3.97it/s]

  8%|▊         | 573/7486 [02:36<29:01,  3.97it/s]
  8%|▊         | 574/7486 [02:36<29:01,  3.97it/s]

  8%|▊         | 575/7486 [02:37<30:55,  3.72it/s]

  8%|▊         | 575/7486 [02:37<30:55,  3.72it/s]
  8%|▊         | 576/7486 [02:37<30:55,  3.72it/s]

  8%|▊         | 577/7486 [02:38<32:00,  3.60it/s]

  8%|▊         | 577/7486 [02:38<32:00,  3.60it/s]
  8%|▊         | 578/7486 [02:38<32:00,  3.60it/s]

  8%|▊         | 579/7486 [02:38<33:21,  3.45it/s]

  8%|▊         | 579/7486 [02:38<33:21,  3.45it/s]
  8%|▊         | 580/7486 [02:38<33:21,  3.45it/s]

  8%|▊         | 581/7486 [02:39<33:56,  3.39it/s]

  8%|▊         | 581/7486 [02:39<33:56,  3.39it/s]
  8%|▊         | 582/7486 [02:39<33:56,  3.39it/s]
  8%|▊         | 583/7486 [02:39<33:56,  3.39it/s]

  8%|▊         | 584/7486 [02:40<30:48,  3.73it/s]

  8%|▊         | 584/7486 [02:40<30:48,  3.73it/s]
  8%|▊         | 585/7486 [02:40<30:48,  3.73it/s]

  8%|▊         | 586/7486 [02:40<34:57,  3.29it/s]

  8%|▊         | 586/7486 [02:40<34:57,  3.29it/s]
  8%|▊         | 587/7486 [02:40<34:57,  3.29it/s]

  8%|▊         | 588/7486 [02:43<1:08:00,  1.69it/s]

  8%|▊         | 588/7486 [02:43<1:08:00,  1.69it/s]
  8%|▊         | 589/7486 [02:43<1:07:59,  1.69it/s]
  8%|▊         | 590/7486 [02:43<1:07:59,  1.69it/s]

  8%|▊         | 591/7486 [02:44<52:01,  2.21it/s]

  8%|▊         | 591/7486 [02:44<52:01,  2.21it/s]
  8%|▊         | 592/7486 [02:44<52:01,  2.21it/s]

  8%|▊         | 593/7486 [02:44<47:44,  2.41it/s]

  8%|▊         | 593/7486 [02:44<47:44,  2.41it/s]
  8%|▊         | 594/7486 [02:44<47:43,  2.41it/s]
  8%|▊         | 595/7486 [02:44<47:43,  2.41it/s]

  8%|▊         | 596/7486 [02:45<38:58,  2.95it/s]

  8%|▊         | 596/7486 [02:45<38:58,  2.95it/s]
  8%|▊         | 597/7486 [02:45<38:58,  2.95it/s]

  8%|▊         | 598/7486 [02:46<38:33,  2.98it/s]

  8%|▊         | 598/7486 [02:46<38:33,  2.98it/s]
  8%|▊         | 599/7486 [02:46<38:32,  2.98it/s]

  8%|▊         | 600/7486 [02:46<37:39,  3.05it/s]

  8%|▊         | 600/7486 [02:46<37:39,  3.05it/s]
  8%|▊         | 601/7486 [02:46<37:39,  3.05it/s]

  8%|▊         | 602/7486 [02:47<37:42,  3.04it/s]

  8%|▊         | 602/7486 [02:47<37:42,  3.04it/s]
  8%|▊         | 603/7486 [02:47<37:41,  3.04it/s]

  8%|▊         | 604/7486 [02:48<37:27,  3.06it/s]

  8%|▊         | 604/7486 [02:48<37:27,  3.06it/s]
  8%|▊         | 605/7486 [02:48<37:27,  3.06it/s]
  8%|▊         | 606/7486 [02:48<37:26,  3.06it/s]

  8%|▊         | 607/7486 [02:48<32:05,  3.57it/s]

  8%|▊         | 607/7486 [02:48<32:05,  3.57it/s]
  8%|▊         | 608/7486 [02:48<32:05,  3.57it/s]

  8%|▊         | 609/7486 [02:49<33:20,  3.44it/s]

  8%|▊         | 609/7486 [02:49<33:20,  3.44it/s]
  8%|▊         | 610/7486 [02:49<33:20,  3.44it/s]

  8%|▊         | 611/7486 [02:49<34:05,  3.36it/s]

  8%|▊         | 611/7486 [02:49<34:05,  3.36it/s]
  8%|▊         | 612/7486 [02:49<34:05,  3.36it/s]

  8%|▊         | 613/7486 [02:50<34:48,  3.29it/s]

  8%|▊         | 613/7486 [02:50<34:48,  3.29it/s]
  8%|▊         | 614/7486 [02:50<34:48,  3.29it/s]

  8%|▊         | 615/7486 [02:51<35:44,  3.20it/s]

  8%|▊         | 615/7486 [02:51<35:44,  3.20it/s]
  8%|▊         | 616/7486 [02:51<35:43,  3.20it/s]
  8%|▊         | 617/7486 [02:51<35:43,  3.20it/s]
  8%|▊         | 618/7486 [02:51<35:43,  3.20it/s]

  8%|▊         | 619/7486 [02:51<27:34,  4.15it/s]

  8%|▊         | 619/7486 [02:51<27:34,  4.15it/s]
  8%|▊         | 620/7486 [02:51<27:33,  4.15it/s]

  8%|▊         | 621/7486 [02:52<29:47,  3.84it/s]

  8%|▊         | 621/7486 [02:52<29:47,  3.84it/s]
  8%|▊         | 622/7486 [02:52<29:47,  3.84it/s]

  8%|▊         | 623/7486 [02:53<31:15,  3.66it/s]

  8%|▊         | 623/7486 [02:53<31:15,  3.66it/s]
  8%|▊         | 624/7486 [02:53<31:14,  3.66it/s]

  8%|▊         | 625/7486 [02:56<1:07:42,  1.69it/s]

  8%|▊         | 625/7486 [02:56<1:07:42,  1.69it/s]
  8%|▊         | 626/7486 [02:56<1:07:41,  1.69it/s]
  8%|▊         | 627/7486 [02:56<1:07:41,  1.69it/s]
  8%|▊         | 628/7486 [02:56<1:07:40,  1.69it/s]
  8%|▊         | 629/7486 [02:56<1:07:40,  1.69it/s]

  8%|▊         | 630/7486 [02:56<41:45,  2.74it/s]

  8%|▊         | 630/7486 [02:56<41:45,  2.74it/s]
  8%|▊         | 631/7486 [02:56<41:45,  2.74it/s]
  8%|▊         | 632/7486 [02:56<41:44,  2.74it/s]

  8%|▊         | 633/7486 [02:57<36:13,  3.15it/s]

  8%|▊         | 633/7486 [02:57<36:13,  3.15it/s]
  8%|▊         | 634/7486 [02:57<36:13,  3.15it/s]

  8%|▊         | 635/7486 [02:57<36:18,  3.15it/s]

  8%|▊         | 635/7486 [02:57<36:18,  3.15it/s]
  8%|▊         | 636/7486 [02:57<36:17,  3.15it/s]

  9%|▊         | 637/7486 [02:58<36:02,  3.17it/s]

  9%|▊         | 637/7486 [02:58<36:02,  3.17it/s]
  9%|▊         | 638/7486 [02:58<36:02,  3.17it/s]

  9%|▊         | 639/7486 [02:59<35:12,  3.24it/s]

  9%|▊         | 639/7486 [02:59<35:12,  3.24it/s]
  9%|▊         | 640/7486 [02:59<35:12,  3.24it/s]
  9%|▊         | 641/7486 [02:59<35:12,  3.24it/s]
  9%|▊         | 642/7486 [02:59<35:12,  3.24it/s]
  9%|▊         | 643/7486 [02:59<35:11,  3.24it/s]
  9%|▊         | 644/7486 [02:59<35:11,  3.24it/s]

  9%|▊         | 645/7486 [02:59<23:20,  4.88it/s]

  9%|▊         | 645/7486 [02:59<23:20,  4.88it/s]
  9%|▊         | 646/7486 [02:59<23:20,  4.88it/s]

  9%|▊         | 647/7486 [03:00<25:54,  4.40it/s]

  9%|▊         | 647/7486 [03:00<25:54,  4.40it/s]
  9%|▊         | 648/7486 [03:00<25:54,  4.40it/s]

  9%|▊         | 649/7486 [03:01<28:11,  4.04it/s]

  9%|▊         | 649/7486 [03:01<28:11,  4.04it/s]
  9%|▊         | 650/7486 [03:01<28:10,  4.04it/s]

  9%|▊         | 651/7486 [03:01<30:47,  3.70it/s]

  9%|▊         | 651/7486 [03:01<30:47,  3.70it/s]
  9%|▊         | 652/7486 [03:01<30:46,  3.70it/s]

  9%|▊         | 653/7486 [03:02<32:02,  3.55it/s]

  9%|▊         | 653/7486 [03:02<32:02,  3.55it/s]
  9%|▊         | 654/7486 [03:02<32:02,  3.55it/s]

  9%|▊         | 655/7486 [03:03<33:08,  3.44it/s]

  9%|▊         | 655/7486 [03:03<33:08,  3.44it/s]
  9%|▉         | 656/7486 [03:03<33:08,  3.44it/s]
  9%|▉         | 657/7486 [03:03<33:07,  3.44it/s]

  9%|▉         | 658/7486 [03:03<29:26,  3.87it/s]

  9%|▉         | 658/7486 [03:03<29:26,  3.87it/s]
  9%|▉         | 659/7486 [03:03<29:26,  3.87it/s]

  9%|▉         | 660/7486 [03:04<31:19,  3.63it/s]

  9%|▉         | 660/7486 [03:04<31:19,  3.63it/s]
  9%|▉         | 661/7486 [03:04<31:19,  3.63it/s]
  9%|▉         | 662/7486 [03:04<31:18,  3.63it/s]
  9%|▉         | 663/7486 [03:04<31:18,  3.63it/s]
  9%|▉         | 664/7486 [03:04<31:18,  3.63it/s]

  9%|▉         | 665/7486 [03:04<23:13,  4.89it/s]

  9%|▉         | 665/7486 [03:04<23:13,  4.89it/s]
  9%|▉         | 666/7486 [03:04<23:13,  4.89it/s]

  9%|▉         | 667/7486 [03:05<25:57,  4.38it/s]

  9%|▉         | 667/7486 [03:05<25:57,  4.38it/s]
  9%|▉         | 668/7486 [03:05<25:57,  4.38it/s]
  9%|▉         | 669/7486 [03:05<25:57,  4.38it/s]

  9%|▉         | 670/7486 [03:08<52:10,  2.18it/s]

  9%|▉         | 670/7486 [03:08<52:10,  2.18it/s]
  9%|▉         | 671/7486 [03:08<52:10,  2.18it/s]

  9%|▉         | 672/7486 [03:09<48:38,  2.34it/s]

  9%|▉         | 672/7486 [03:09<48:38,  2.34it/s]
  9%|▉         | 673/7486 [03:09<48:37,  2.34it/s]

  9%|▉         | 674/7486 [03:09<44:55,  2.53it/s]

  9%|▉         | 674/7486 [03:09<44:55,  2.53it/s]
  9%|▉         | 675/7486 [03:09<44:54,  2.53it/s]

  9%|▉         | 676/7486 [03:10<42:50,  2.65it/s]

  9%|▉         | 676/7486 [03:10<42:50,  2.65it/s]
  9%|▉         | 677/7486 [03:10<42:50,  2.65it/s]

  9%|▉         | 678/7486 [03:10<40:33,  2.80it/s]

  9%|▉         | 678/7486 [03:10<40:33,  2.80it/s]
  9%|▉         | 679/7486 [03:10<40:33,  2.80it/s]
  9%|▉         | 680/7486 [03:10<40:32,  2.80it/s]

  9%|▉         | 681/7486 [03:11<34:10,  3.32it/s]

  9%|▉         | 681/7486 [03:11<34:10,  3.32it/s]
  9%|▉         | 682/7486 [03:11<34:10,  3.32it/s]
  9%|▉         | 683/7486 [03:11<34:10,  3.32it/s]

  9%|▉         | 684/7486 [03:12<30:21,  3.73it/s]

  9%|▉         | 684/7486 [03:12<30:21,  3.73it/s]
  9%|▉         | 685/7486 [03:12<30:21,  3.73it/s]

  9%|▉         | 686/7486 [03:12<30:54,  3.67it/s]

  9%|▉         | 686/7486 [03:12<30:54,  3.67it/s]
  9%|▉         | 687/7486 [03:12<30:54,  3.67it/s]

  9%|▉         | 688/7486 [03:13<31:47,  3.56it/s]

  9%|▉         | 688/7486 [03:13<31:47,  3.56it/s]
  9%|▉         | 689/7486 [03:13<31:47,  3.56it/s]

  9%|▉         | 690/7486 [03:13<31:51,  3.56it/s]

  9%|▉         | 690/7486 [03:13<31:51,  3.56it/s]
  9%|▉         | 691/7486 [03:13<31:50,  3.56it/s]
  9%|▉         | 692/7486 [03:13<31:50,  3.56it/s]
  9%|▉         | 693/7486 [03:13<31:50,  3.56it/s]

  9%|▉         | 694/7486 [03:14<25:31,  4.44it/s]

  9%|▉         | 694/7486 [03:14<25:31,  4.44it/s]
  9%|▉         | 695/7486 [03:14<25:31,  4.44it/s]

  9%|▉         | 696/7486 [03:15<27:21,  4.14it/s]

  9%|▉         | 696/7486 [03:15<27:21,  4.14it/s]
  9%|▉         | 697/7486 [03:15<27:21,  4.14it/s]

  9%|▉         | 698/7486 [03:15<29:00,  3.90it/s]

  9%|▉         | 698/7486 [03:15<29:00,  3.90it/s]
  9%|▉         | 699/7486 [03:15<29:00,  3.90it/s]

  9%|▉         | 700/7486 [03:16<30:39,  3.69it/s]

  9%|▉         | 700/7486 [03:16<30:39,  3.69it/s]
  9%|▉         | 701/7486 [03:16<30:38,  3.69it/s]
  9%|▉         | 702/7486 [03:16<30:38,  3.69it/s]
  9%|▉         | 703/7486 [03:16<30:38,  3.69it/s]

  9%|▉         | 704/7486 [03:16<24:57,  4.53it/s]

  9%|▉         | 704/7486 [03:16<24:57,  4.53it/s]
  9%|▉         | 705/7486 [03:16<24:57,  4.53it/s]

  9%|▉         | 706/7486 [03:17<27:29,  4.11it/s]

  9%|▉         | 706/7486 [03:17<27:29,  4.11it/s]
  9%|▉         | 707/7486 [03:17<27:29,  4.11it/s]
  9%|▉         | 708/7486 [03:17<27:29,  4.11it/s]

  9%|▉         | 709/7486 [03:18<25:49,  4.37it/s]

  9%|▉         | 709/7486 [03:18<25:49,  4.37it/s]
  9%|▉         | 710/7486 [03:18<25:49,  4.37it/s]

  9%|▉         | 711/7486 [03:21<59:35,  1.89it/s]

  9%|▉         | 711/7486 [03:21<59:35,  1.89it/s]
 10%|▉         | 712/7486 [03:21<59:35,  1.89it/s]
 10%|▉         | 713/7486 [03:21<59:34,  1.89it/s]
 10%|▉         | 714/7486 [03:21<59:34,  1.89it/s]
 10%|▉         | 715/7486 [03:21<59:33,  1.89it/s]

 10%|▉         | 716/7486 [03:21<38:35,  2.92it/s]

 10%|▉         | 716/7486 [03:21<38:35,  2.92it/s]
 10%|▉         | 717/7486 [03:21<38:35,  2.92it/s]

 10%|▉         | 718/7486 [03:22<37:48,  2.98it/s]

 10%|▉         | 718/7486 [03:22<37:48,  2.98it/s]
 10%|▉         | 719/7486 [03:22<37:48,  2.98it/s]

 10%|▉         | 720/7486 [03:23<37:42,  2.99it/s]

 10%|▉         | 720/7486 [03:23<37:42,  2.99it/s]
 10%|▉         | 721/7486 [03:23<37:41,  2.99it/s]

 10%|▉         | 722/7486 [03:23<37:08,  3.03it/s]

 10%|▉         | 722/7486 [03:23<37:08,  3.03it/s]
 10%|▉         | 723/7486 [03:23<37:08,  3.03it/s]

 10%|▉         | 724/7486 [03:24<36:36,  3.08it/s]

 10%|▉         | 724/7486 [03:24<36:36,  3.08it/s]
 10%|▉         | 725/7486 [03:24<36:35,  3.08it/s]

 10%|▉         | 726/7486 [03:24<36:27,  3.09it/s]

 10%|▉         | 726/7486 [03:24<36:27,  3.09it/s]
 10%|▉         | 727/7486 [03:24<36:27,  3.09it/s]

 10%|▉         | 728/7486 [03:25<35:45,  3.15it/s]

 10%|▉         | 728/7486 [03:25<35:45,  3.15it/s]
 10%|▉         | 729/7486 [03:25<35:45,  3.15it/s]

 10%|▉         | 730/7486 [03:26<35:34,  3.16it/s]

 10%|▉         | 730/7486 [03:26<35:34,  3.16it/s]
 10%|▉         | 731/7486 [03:26<35:34,  3.16it/s]

 10%|▉         | 732/7486 [03:26<35:08,  3.20it/s]

 10%|▉         | 732/7486 [03:26<35:08,  3.20it/s]
 10%|▉         | 733/7486 [03:26<35:07,  3.20it/s]
 10%|▉         | 734/7486 [03:26<35:07,  3.20it/s]

 10%|▉         | 735/7486 [03:27<31:00,  3.63it/s]

 10%|▉         | 735/7486 [03:27<31:00,  3.63it/s]
 10%|▉         | 736/7486 [03:27<31:00,  3.63it/s]

 10%|▉         | 737/7486 [03:28<32:50,  3.42it/s]

 10%|▉         | 737/7486 [03:28<32:50,  3.42it/s]
 10%|▉         | 738/7486 [03:28<32:50,  3.42it/s]

 10%|▉         | 739/7486 [03:28<33:31,  3.35it/s]

 10%|▉         | 739/7486 [03:28<33:31,  3.35it/s]
 10%|▉         | 740/7486 [03:28<33:30,  3.35it/s]

 10%|▉         | 741/7486 [03:29<36:14,  3.10it/s]

 10%|▉         | 741/7486 [03:29<36:14,  3.10it/s]
 10%|▉         | 742/7486 [03:29<36:14,  3.10it/s]

 10%|▉         | 743/7486 [03:30<36:40,  3.06it/s]

 10%|▉         | 743/7486 [03:30<36:40,  3.06it/s]
 10%|▉         | 744/7486 [03:30<36:40,  3.06it/s]

 10%|▉         | 745/7486 [03:30<36:02,  3.12it/s]

 10%|▉         | 745/7486 [03:30<36:02,  3.12it/s]
 10%|▉         | 746/7486 [03:30<36:01,  3.12it/s]

 10%|▉         | 747/7486 [03:33<1:14:05,  1.52it/s]

 10%|▉         | 747/7486 [03:33<1:14:05,  1.52it/s]
 10%|▉         | 748/7486 [03:33<1:14:04,  1.52it/s]

 10%|█         | 749/7486 [03:34<1:03:04,  1.78it/s]

 10%|█         | 749/7486 [03:34<1:03:04,  1.78it/s]
 10%|█         | 750/7486 [03:34<1:03:03,  1.78it/s]

 10%|█         | 751/7486 [03:34<54:46,  2.05it/s]

 10%|█         | 751/7486 [03:34<54:46,  2.05it/s]
 10%|█         | 752/7486 [03:34<54:46,  2.05it/s]
 10%|█         | 753/7486 [03:34<54:45,  2.05it/s]
 10%|█         | 754/7486 [03:34<54:45,  2.05it/s]

 10%|█         | 755/7486 [03:35<38:20,  2.93it/s]

 10%|█         | 755/7486 [03:35<38:20,  2.93it/s]
 10%|█         | 756/7486 [03:35<38:20,  2.93it/s]

 10%|█         | 757/7486 [03:36<37:33,  2.99it/s]

 10%|█         | 757/7486 [03:36<37:33,  2.99it/s]
 10%|█         | 758/7486 [03:36<37:32,  2.99it/s]
 10%|█         | 759/7486 [03:36<37:32,  2.99it/s]

 10%|█         | 760/7486 [03:36<33:09,  3.38it/s]

 10%|█         | 760/7486 [03:36<33:09,  3.38it/s]
 10%|█         | 761/7486 [03:36<33:09,  3.38it/s]

 10%|█         | 762/7486 [03:37<34:30,  3.25it/s]

 10%|█         | 762/7486 [03:37<34:30,  3.25it/s]
 10%|█         | 763/7486 [03:37<34:30,  3.25it/s]

 10%|█         | 764/7486 [03:38<35:10,  3.19it/s]

 10%|█         | 764/7486 [03:38<35:10,  3.19it/s]
 10%|█         | 765/7486 [03:38<35:10,  3.19it/s]
 10%|█         | 766/7486 [03:38<35:09,  3.19it/s]
 10%|█         | 767/7486 [03:38<35:09,  3.19it/s]
 10%|█         | 768/7486 [03:38<35:09,  3.19it/s]
 10%|█         | 769/7486 [03:38<35:08,  3.19it/s]
 10%|█         | 770/7486 [03:38<35:08,  3.19it/s]

 10%|█         | 771/7486 [03:38<21:22,  5.23it/s]

 10%|█         | 771/7486 [03:38<21:22,  5.23it/s]
 10%|█         | 772/7486 [03:39<21:22,  5.23it/s]

 10%|█         | 773/7486 [03:39<24:25,  4.58it/s]

 10%|█         | 773/7486 [03:39<24:25,  4.58it/s]
 10%|█         | 774/7486 [03:39<24:25,  4.58it/s]

 10%|█         | 775/7486 [03:40<27:05,  4.13it/s]

 10%|█         | 775/7486 [03:40<27:05,  4.13it/s]
 10%|█         | 776/7486 [03:40<27:05,  4.13it/s]

 10%|█         | 777/7486 [03:40<29:25,  3.80it/s]

 10%|█         | 777/7486 [03:40<29:25,  3.80it/s]
 10%|█         | 778/7486 [03:41<29:25,  3.80it/s]

 10%|█         | 779/7486 [03:41<31:32,  3.54it/s]

 10%|█         | 779/7486 [03:41<31:32,  3.54it/s]
 10%|█         | 780/7486 [03:41<31:32,  3.54it/s]

 10%|█         | 781/7486 [03:42<32:44,  3.41it/s]

 10%|█         | 781/7486 [03:42<32:44,  3.41it/s]
 10%|█         | 782/7486 [03:42<32:43,  3.41it/s]

 10%|█         | 783/7486 [03:42<34:18,  3.26it/s]

 10%|█         | 783/7486 [03:43<34:18,  3.26it/s]
 10%|█         | 784/7486 [03:43<34:18,  3.26it/s]

 10%|█         | 785/7486 [03:44<41:58,  2.66it/s]

 10%|█         | 785/7486 [03:44<41:58,  2.66it/s]
 10%|█         | 786/7486 [03:44<41:58,  2.66it/s]

 11%|█         | 787/7486 [03:46<1:09:17,  1.61it/s]

 11%|█         | 787/7486 [03:46<1:09:17,  1.61it/s]
 11%|█         | 788/7486 [03:46<1:09:16,  1.61it/s]
 11%|█         | 789/7486 [03:46<1:09:16,  1.61it/s]
 11%|█         | 790/7486 [03:46<1:09:15,  1.61it/s]
 11%|█         | 791/7486 [03:46<1:09:15,  1.61it/s]
 11%|█         | 792/7486 [03:46<1:09:14,  1.61it/s]
 11%|█         | 793/7486 [03:46<1:09:13,  1.61it/s]
 11%|█         | 794/7486 [03:46<1:09:13,  1.61it/s]

 11%|█         | 795/7486 [03:47<32:37,  3.42it/s]

 11%|█         | 795/7486 [03:47<32:37,  3.42it/s]
 11%|█         | 796/7486 [03:47<32:37,  3.42it/s]
 11%|█         | 797/7486 [03:47<32:36,  3.42it/s]

 11%|█         | 798/7486 [03:47<30:55,  3.60it/s]

 11%|█         | 798/7486 [03:47<30:55,  3.60it/s]
 11%|█         | 799/7486 [03:47<30:55,  3.60it/s]
 11%|█         | 800/7486 [03:47<30:55,  3.60it/s]
 11%|█         | 801/7486 [03:48<30:54,  3.60it/s]
 11%|█         | 802/7486 [03:48<30:54,  3.60it/s]
 11%|█         | 803/7486 [03:48<30:54,  3.60it/s]
 11%|█         | 804/7486 [03:48<30:54,  3.60it/s]
 11%|█         | 805/7486 [03:48<30:53,  3.60it/s]
 11%|█         | 806/7486 [03:48<30:53,  3.60it/s]
 11%|█         | 807/7486 [03:48<30:53,  3.60it/s]
 11%|█         | 808/7486 [03:48<30:53,  3.60it/s]
 11%|█         | 809/7486 [03:48<30:52,  3.60it/s]
 11%|█         | 810/7486 [03:48<30:52,  3.60it/s]
 11%|█         | 811/7486 [03:48<30:52,  3.60it/s]
 11%|█         | 812/7486 [03:48<30:51,  3.60it/s]
 11%|█         | 813/7486 [03:48<30:51,  3.60it/s]

 11%|█         | 814/7486 [03:48<13:55,  7.98it/s]

 11%|█         | 814/7486 [03:48<13:55,  7.98it/s]
 11%|█         | 815/7486 [03:48<13:55,  7.98it/s]

 11%|█         | 816/7486 [03:49<16:40,  6.66it/s]

 11%|█         | 816/7486 [03:49<16:40,  6.66it/s]
 11%|█         | 817/7486 [03:49<16:40,  6.66it/s]

 11%|█         | 818/7486 [03:50<19:49,  5.60it/s]

 11%|█         | 818/7486 [03:50<19:49,  5.60it/s]
 11%|█         | 819/7486 [03:50<19:49,  5.60it/s]

 11%|█         | 820/7486 [03:50<22:37,  4.91it/s]

 11%|█         | 820/7486 [03:50<22:37,  4.91it/s]
 11%|█         | 821/7486 [03:50<22:37,  4.91it/s]

 11%|█         | 822/7486 [03:51<25:39,  4.33it/s]

 11%|█         | 822/7486 [03:51<25:39,  4.33it/s]
 11%|█         | 823/7486 [03:51<25:38,  4.33it/s]

 11%|█         | 824/7486 [03:52<28:37,  3.88it/s]

 11%|█         | 824/7486 [03:52<28:37,  3.88it/s]
 11%|█         | 825/7486 [03:52<28:37,  3.88it/s]

 11%|█         | 826/7486 [03:52<31:03,  3.57it/s]

 11%|█         | 826/7486 [03:52<31:03,  3.57it/s]
 11%|█         | 827/7486 [03:53<31:03,  3.57it/s]

 11%|█         | 828/7486 [03:53<33:15,  3.34it/s]

 11%|█         | 828/7486 [03:53<33:15,  3.34it/s]
 11%|█         | 829/7486 [03:53<33:15,  3.34it/s]

 11%|█         | 830/7486 [03:54<34:39,  3.20it/s]

 11%|█         | 830/7486 [03:54<34:39,  3.20it/s]
 11%|█         | 831/7486 [03:54<34:38,  3.20it/s]

 11%|█         | 832/7486 [03:55<35:27,  3.13it/s]

 11%|█         | 832/7486 [03:55<35:27,  3.13it/s]
 11%|█         | 833/7486 [03:55<35:27,  3.13it/s]

 11%|█         | 834/7486 [03:55<36:04,  3.07it/s]

 11%|█         | 834/7486 [03:55<36:04,  3.07it/s]
 11%|█         | 835/7486 [03:55<36:03,  3.07it/s]

 11%|█         | 836/7486 [03:57<1:00:51,  1.82it/s]

 11%|█         | 836/7486 [03:57<1:00:51,  1.82it/s]
 11%|█         | 837/7486 [03:57<1:00:50,  1.82it/s]

 11%|█         | 838/7486 [03:59<1:05:22,  1.69it/s]

 11%|█         | 838/7486 [03:59<1:05:22,  1.69it/s]
 11%|█         | 839/7486 [03:59<1:05:22,  1.69it/s]

 11%|█         | 840/7486 [04:00<57:55,  1.91it/s]

 11%|█         | 840/7486 [04:00<57:55,  1.91it/s]
 11%|█         | 841/7486 [04:00<57:54,  1.91it/s]

 11%|█         | 842/7486 [04:00<51:46,  2.14it/s]

 11%|█         | 842/7486 [04:00<51:46,  2.14it/s]
 11%|█▏        | 843/7486 [04:00<51:45,  2.14it/s]

 11%|█▏        | 844/7486 [04:01<46:52,  2.36it/s]

 11%|█▏        | 844/7486 [04:01<46:52,  2.36it/s]
 11%|█▏        | 845/7486 [04:01<46:51,  2.36it/s]

 11%|█▏        | 846/7486 [04:02<45:07,  2.45it/s]

 11%|█▏        | 846/7486 [04:02<45:07,  2.45it/s]
 11%|█▏        | 847/7486 [04:02<45:07,  2.45it/s]

 11%|█▏        | 848/7486 [04:02<42:11,  2.62it/s]

 11%|█▏        | 848/7486 [04:02<42:11,  2.62it/s]
 11%|█▏        | 849/7486 [04:02<42:11,  2.62it/s]

 11%|█▏        | 850/7486 [04:03<39:59,  2.77it/s]

 11%|█▏        | 850/7486 [04:03<39:59,  2.77it/s]
 11%|█▏        | 851/7486 [04:03<39:59,  2.77it/s]

 11%|█▏        | 852/7486 [04:04<38:39,  2.86it/s]

 11%|█▏        | 852/7486 [04:04<38:39,  2.86it/s]
 11%|█▏        | 853/7486 [04:04<38:39,  2.86it/s]

 11%|█▏        | 854/7486 [04:04<36:51,  3.00it/s]

 11%|█▏        | 854/7486 [04:04<36:51,  3.00it/s]
 11%|█▏        | 855/7486 [04:04<36:51,  3.00it/s]

 11%|█▏        | 856/7486 [04:05<36:24,  3.04it/s]

 11%|█▏        | 856/7486 [04:05<36:24,  3.04it/s]
 11%|█▏        | 857/7486 [04:05<36:23,  3.04it/s]

 11%|█▏        | 858/7486 [04:05<35:36,  3.10it/s]

 11%|█▏        | 858/7486 [04:05<35:36,  3.10it/s]
 11%|█▏        | 859/7486 [04:05<35:35,  3.10it/s]

 11%|█▏        | 860/7486 [04:06<34:55,  3.16it/s]

 11%|█▏        | 860/7486 [04:06<34:55,  3.16it/s]
 12%|█▏        | 861/7486 [04:06<34:55,  3.16it/s]

 12%|█▏        | 862/7486 [04:07<34:53,  3.16it/s]

 12%|█▏        | 862/7486 [04:07<34:53,  3.16it/s]
 12%|█▏        | 863/7486 [04:07<34:53,  3.16it/s]

 12%|█▏        | 864/7486 [04:07<34:09,  3.23it/s]

 12%|█▏        | 864/7486 [04:07<34:09,  3.23it/s]
 12%|█▏        | 865/7486 [04:07<34:09,  3.23it/s]

 12%|█▏        | 866/7486 [04:08<34:31,  3.20it/s]

 12%|█▏        | 866/7486 [04:08<34:31,  3.20it/s]
 12%|█▏        | 867/7486 [04:08<34:30,  3.20it/s]

 12%|█▏        | 868/7486 [04:08<34:46,  3.17it/s]

 12%|█▏        | 868/7486 [04:08<34:46,  3.17it/s]
 12%|█▏        | 869/7486 [04:09<34:45,  3.17it/s]

 12%|█▏        | 870/7486 [04:11<1:10:11,  1.57it/s]

 12%|█▏        | 870/7486 [04:11<1:10:11,  1.57it/s]
 12%|█▏        | 871/7486 [04:11<1:10:10,  1.57it/s]

 12%|█▏        | 872/7486 [04:12<59:14,  1.86it/s]

 12%|█▏        | 872/7486 [04:12<59:14,  1.86it/s]
 12%|█▏        | 873/7486 [04:12<59:13,  1.86it/s]

 12%|█▏        | 874/7486 [04:12<50:58,  2.16it/s]

 12%|█▏        | 874/7486 [04:12<50:58,  2.16it/s]
 12%|█▏        | 875/7486 [04:12<50:57,  2.16it/s]

 12%|█▏        | 876/7486 [04:13<46:08,  2.39it/s]

 12%|█▏        | 876/7486 [04:13<46:08,  2.39it/s]
 12%|█▏        | 877/7486 [04:13<46:08,  2.39it/s]
 12%|█▏        | 878/7486 [04:13<46:07,  2.39it/s]

 12%|█▏        | 879/7486 [04:14<36:30,  3.02it/s]

 12%|█▏        | 879/7486 [04:14<36:30,  3.02it/s]
 12%|█▏        | 880/7486 [04:14<36:30,  3.02it/s]

 12%|█▏        | 881/7486 [04:14<35:44,  3.08it/s]

 12%|█▏        | 881/7486 [04:14<35:44,  3.08it/s]
 12%|█▏        | 882/7486 [04:14<35:44,  3.08it/s]

 12%|█▏        | 883/7486 [04:15<35:12,  3.13it/s]

 12%|█▏        | 883/7486 [04:15<35:12,  3.13it/s]
 12%|█▏        | 884/7486 [04:15<35:11,  3.13it/s]

 12%|█▏        | 885/7486 [04:15<34:23,  3.20it/s]

 12%|█▏        | 885/7486 [04:15<34:23,  3.20it/s]
 12%|█▏        | 886/7486 [04:16<34:23,  3.20it/s]

 12%|█▏        | 887/7486 [04:16<34:22,  3.20it/s]

 12%|█▏        | 887/7486 [04:16<34:22,  3.20it/s]
 12%|█▏        | 888/7486 [04:16<34:21,  3.20it/s]

 12%|█▏        | 889/7486 [04:17<34:21,  3.20it/s]

 12%|█▏        | 889/7486 [04:17<34:21,  3.20it/s]
 12%|█▏        | 890/7486 [04:17<34:21,  3.20it/s]

 12%|█▏        | 891/7486 [04:17<34:08,  3.22it/s]

 12%|█▏        | 891/7486 [04:17<34:08,  3.22it/s]
 12%|█▏        | 892/7486 [04:17<34:08,  3.22it/s]

 12%|█▏        | 893/7486 [04:18<34:13,  3.21it/s]

 12%|█▏        | 893/7486 [04:18<34:13,  3.21it/s]
 12%|█▏        | 894/7486 [04:18<34:12,  3.21it/s]
 12%|█▏        | 895/7486 [04:18<34:12,  3.21it/s]

 12%|█▏        | 896/7486 [04:19<29:42,  3.70it/s]

 12%|█▏        | 896/7486 [04:19<29:42,  3.70it/s]
 12%|█▏        | 897/7486 [04:19<29:41,  3.70it/s]
 12%|█▏        | 898/7486 [04:19<29:41,  3.70it/s]

 12%|█▏        | 899/7486 [04:19<27:31,  3.99it/s]

 12%|█▏        | 899/7486 [04:19<27:31,  3.99it/s]
 12%|█▏        | 900/7486 [04:19<27:31,  3.99it/s]

 12%|█▏        | 901/7486 [04:20<29:18,  3.75it/s]

 12%|█▏        | 901/7486 [04:20<29:18,  3.75it/s]
 12%|█▏        | 902/7486 [04:20<29:17,  3.75it/s]
 12%|█▏        | 903/7486 [04:20<29:17,  3.75it/s]
 12%|█▏        | 904/7486 [04:20<29:17,  3.75it/s]
 12%|█▏        | 905/7486 [04:20<29:16,  3.75it/s]

 12%|█▏        | 906/7486 [04:21<22:15,  4.93it/s]

 12%|█▏        | 906/7486 [04:21<22:15,  4.93it/s]
 12%|█▏        | 907/7486 [04:21<22:14,  4.93it/s]
 12%|█▏        | 908/7486 [04:21<22:14,  4.93it/s]

 12%|█▏        | 909/7486 [04:23<39:18,  2.79it/s]

 12%|█▏        | 909/7486 [04:23<39:18,  2.79it/s]
 12%|█▏        | 910/7486 [04:23<39:18,  2.79it/s]
 12%|█▏        | 911/7486 [04:23<39:17,  2.79it/s]
 12%|█▏        | 912/7486 [04:23<39:17,  2.79it/s]
 12%|█▏        | 913/7486 [04:23<39:17,  2.79it/s]
 12%|█▏        | 914/7486 [04:23<39:16,  2.79it/s]

 12%|█▏        | 915/7486 [04:24<32:25,  3.38it/s]

 12%|█▏        | 915/7486 [04:24<32:25,  3.38it/s]
 12%|█▏        | 916/7486 [04:24<32:25,  3.38it/s]

 12%|█▏        | 917/7486 [04:25<32:46,  3.34it/s]

 12%|█▏        | 917/7486 [04:25<32:46,  3.34it/s]
 12%|█▏        | 918/7486 [04:25<32:45,  3.34it/s]
 12%|█▏        | 919/7486 [04:25<32:45,  3.34it/s]

 12%|█▏        | 920/7486 [04:25<29:40,  3.69it/s]

 12%|█▏        | 920/7486 [04:25<29:40,  3.69it/s]
 12%|█▏        | 921/7486 [04:25<29:40,  3.69it/s]

 12%|█▏        | 922/7486 [04:26<30:41,  3.56it/s]

 12%|█▏        | 922/7486 [04:26<30:41,  3.56it/s]
 12%|█▏        | 923/7486 [04:26<30:41,  3.56it/s]

 12%|█▏        | 924/7486 [04:27<31:22,  3.49it/s]

 12%|█▏        | 924/7486 [04:27<31:22,  3.49it/s]
 12%|█▏        | 925/7486 [04:27<31:22,  3.49it/s]

 12%|█▏        | 926/7486 [04:27<31:59,  3.42it/s]

 12%|█▏        | 926/7486 [04:27<31:59,  3.42it/s]
 12%|█▏        | 927/7486 [04:27<31:59,  3.42it/s]

 12%|█▏        | 928/7486 [04:28<32:46,  3.33it/s]

 12%|█▏        | 928/7486 [04:28<32:46,  3.33it/s]
 12%|█▏        | 929/7486 [04:28<32:46,  3.33it/s]

 12%|█▏        | 930/7486 [04:28<32:54,  3.32it/s]

 12%|█▏        | 930/7486 [04:28<32:54,  3.32it/s]
 12%|█▏        | 931/7486 [04:28<32:54,  3.32it/s]

 12%|█▏        | 932/7486 [04:29<33:28,  3.26it/s]

 12%|█▏        | 932/7486 [04:29<33:28,  3.26it/s]
 12%|█▏        | 933/7486 [04:29<33:27,  3.26it/s]

 12%|█▏        | 934/7486 [04:30<33:58,  3.21it/s]

 12%|█▏        | 934/7486 [04:30<33:58,  3.21it/s]
 12%|█▏        | 935/7486 [04:30<33:58,  3.21it/s]
 13%|█▎        | 936/7486 [04:30<33:58,  3.21it/s]

 13%|█▎        | 937/7486 [04:30<29:17,  3.73it/s]

 13%|█▎        | 937/7486 [04:30<29:17,  3.73it/s]
 13%|█▎        | 938/7486 [04:30<29:17,  3.73it/s]

 13%|█▎        | 939/7486 [04:31<31:08,  3.50it/s]

 13%|█▎        | 939/7486 [04:31<31:08,  3.50it/s]
 13%|█▎        | 940/7486 [04:31<31:07,  3.50it/s]

 13%|█▎        | 941/7486 [04:32<33:09,  3.29it/s]

 13%|█▎        | 941/7486 [04:32<33:09,  3.29it/s]
 13%|█▎        | 942/7486 [04:32<33:09,  3.29it/s]
 13%|█▎        | 943/7486 [04:32<33:09,  3.29it/s]

 13%|█▎        | 944/7486 [04:32<29:10,  3.74it/s]

 13%|█▎        | 944/7486 [04:32<29:10,  3.74it/s]
 13%|█▎        | 945/7486 [04:32<29:10,  3.74it/s]
 13%|█▎        | 946/7486 [04:32<29:10,  3.74it/s]

 13%|█▎        | 947/7486 [04:33<26:54,  4.05it/s]

 13%|█▎        | 947/7486 [04:33<26:54,  4.05it/s]
 13%|█▎        | 948/7486 [04:33<26:54,  4.05it/s]
 13%|█▎        | 949/7486 [04:33<26:54,  4.05it/s]

 13%|█▎        | 950/7486 [04:34<25:28,  4.28it/s]

 13%|█▎        | 950/7486 [04:34<25:28,  4.28it/s]
 13%|█▎        | 951/7486 [04:34<25:28,  4.28it/s]

 13%|█▎        | 952/7486 [04:36<56:58,  1.91it/s]

 13%|█▎        | 952/7486 [04:36<56:58,  1.91it/s]
 13%|█▎        | 953/7486 [04:36<56:58,  1.91it/s]

 13%|█▎        | 954/7486 [04:37<51:07,  2.13it/s]

 13%|█▎        | 954/7486 [04:37<51:07,  2.13it/s]
 13%|█▎        | 955/7486 [04:37<51:07,  2.13it/s]

 13%|█▎        | 956/7486 [04:38<46:18,  2.35it/s]

 13%|█▎        | 956/7486 [04:38<46:18,  2.35it/s]
 13%|█▎        | 957/7486 [04:38<46:17,  2.35it/s]

 13%|█▎        | 958/7486 [04:38<42:42,  2.55it/s]

 13%|█▎        | 958/7486 [04:38<42:42,  2.55it/s]
 13%|█▎        | 959/7486 [04:38<42:42,  2.55it/s]

 13%|█▎        | 960/7486 [04:39<39:47,  2.73it/s]

 13%|█▎        | 960/7486 [04:39<39:47,  2.73it/s]
 13%|█▎        | 961/7486 [04:39<39:46,  2.73it/s]

 13%|█▎        | 962/7486 [04:39<37:55,  2.87it/s]

 13%|█▎        | 962/7486 [04:39<37:55,  2.87it/s]
 13%|█▎        | 963/7486 [04:39<37:55,  2.87it/s]

 13%|█▎        | 964/7486 [04:40<36:32,  2.97it/s]
 13%|█▎        | 970/7486 [04:40<17:16,  6.29it/s]

 13%|█▎        | 964/7486 [04:40<36:32,  2.97it/s]
 13%|█▎        | 965/7486 [04:40<36:32,  2.97it/s]
 13%|█▎        | 966/7486 [04:40<36:31,  2.97it/s]
 13%|█▎        | 967/7486 [04:40<36:31,  2.97it/s]
 13%|█▎        | 968/7486 [04:40<36:31,  2.97it/s]
 13%|█▎        | 969/7486 [04:40<36:30,  2.97it/s]
 13%|█▎        | 970/7486 [04:40<17:16,  6.29it/s]

 13%|█▎        | 972/7486 [04:41<20:23,  5.32it/s]

 13%|█▎        | 971/7486 [04:41<17:16,  6.29it/s]
 13%|█▎        | 972/7486 [04:41<20:23,  5.32it/s]

 13%|█▎        | 974/7486 [04:41<23:47,  4.56it/s]

 13%|█▎        | 973/7486 [04:41<20:23,  5.32it/s]
 13%|█▎        | 974/7486 [04:41<23:47,  4.56it/s]
 13%|█▎        | 975/7486 [04:41<23:47,  4.56it/s]
 13%|█▎        | 976/7486 [04:41<23:47,  4.56it/s]
 13%|█▎        | 977/7486 [04:41<23:47,  4.56it/s]
 13%|█▎        | 978/7486 [04:41<23:47,  4.56it/s]
 13%|█▎        | 979/7486 [04:41<23:46,  4.56it/s]
 13%|█▎        | 980/7486 [04:41<23:46,  4.56it/s]
 13%|█▎        | 981/7486 [04:41<23:46,  4.56it/s]

 13%|█▎        | 982/7486 [04:42<14:55,  7.26it/s]

 13%|█▎        | 982/7486 [04:42<14:55,  7.26it/s]
 13%|█▎        | 983/7486 [04:42<14:55,  7.26it/s]

 13%|█▎        | 984/7486 [04:43<18:08,  5.98it/s]

 13%|█▎        | 984/7486 [04:43<18:08,  5.98it/s]
 13%|█▎        | 985/7486 [04:43<18:07,  5.98it/s]

 13%|█▎        | 986/7486 [04:43<20:58,  5.16it/s]

 13%|█▎        | 986/7486 [04:43<20:58,  5.16it/s]
 13%|█▎        | 987/7486 [04:43<20:58,  5.16it/s]
 13%|█▎        | 988/7486 [04:43<20:58,  5.16it/s]

 13%|█▎        | 989/7486 [04:44<21:21,  5.07it/s]

 13%|█▎        | 989/7486 [04:44<21:21,  5.07it/s]
 13%|█▎        | 990/7486 [04:44<21:20,  5.07it/s]

 13%|█▎        | 991/7486 [04:44<23:52,  4.53it/s]

 13%|█▎        | 991/7486 [04:44<23:52,  4.53it/s]
 13%|█▎        | 992/7486 [04:45<23:52,  4.53it/s]

 13%|█▎        | 1000/7486 [04:45<30:52,  3.50it/s]
 44%|████▍     | 4/9 [18:30<23:20, 280.19s/it]

 13%|█▎        | 993/7486 [04:45<25:52,  4.18it/s]
 13%|█▎        | 994/7486 [04:45<25:52,  4.18it/s]
 13%|█▎        | 995/7486 [04:45<25:52,  4.18it/s]
 13%|█▎        | 996/7486 [04:45<25:51,  4.18it/s]
 13%|█▎        | 997/7486 [04:45<25:51,  4.18it/s]
 13%|█▎        | 998/7486 [04:45<25:51,  4.18it/s]
 13%|█▎        | 999/7486 [04:45<25:51,  4.18it/s]
 13%|█▎        | 1000/7486 [04:45<25:50,  4.18it/s]
                     MLUT4_AT.232A  MLUT4_RQ.2BTLS  MLUT4_TE.252A  \
Time
2025-05-25 05:20:05       0.852984        0.855904       0.842414
2025-05-25 05:30:05       0.876511        0.874611       0.847393
2025-05-25 05:35:05       0.877479        0.885625       0.860507
2025-05-25 05:40:05       0.878625        0.849563       0.860377
2025-05-25 05:45:05       0.877141        0.871733       0.849503

                     MLUT4_SIV.B7921  MLUT4_AIA792101B  MLUT4_PDT.956  \
Time
2025-05-25 05:20:05         0.903258          0.872434       0.899219
2025-05-25 05:30:05         0.903158          0.872244       0.916372
2025-05-25 05:35:05         0.903349          0.872158       0.914016
2025-05-25 05:40:05         0.903300          0.872148       0.910043
2025-05-25 05:45:05         0.903219          0.872148       0.914286

                     MLUT4_TE.252F  MLUT4_PT.231  MLUT4_FIC.231C  \
Time
2025-05-25 05:20:05       0.887579      0.869354        0.857897
2025-05-25 05:30:05       0.879727      0.867235        0.857888
2025-05-25 05:35:05       0.893944      0.867041        0.857883
2025-05-25 05:40:05       0.872940      0.866275        0.857879
2025-05-25 05:45:05       0.876962      0.865383        0.857874

                     MLUT4_FIC.231A  ...  DeSOx_2nd  MLUT4_AIC.232B  \
Time                                 ...
2025-05-25 05:20:05        0.859975  ...   0.882455       85.012138
2025-05-25 05:30:05        0.856716  ...   0.883006       88.954571
2025-05-25 05:35:05        0.860662  ...   0.882613       93.745851
2025-05-25 05:40:05        0.859286  ...   0.882555       85.305571
2025-05-25 05:45:05        0.859582  ...   0.883647      101.874866

                     MLUT4_AT.240  prev_target  MLUT4_AT-240  prediction  \
Time
2025-05-25 05:20:05     14.151761     0.888806      9.992773    0.881931
2025-05-25 05:30:05      9.316637     0.890104     10.407157    0.881289
2025-05-25 05:35:05      6.155893     0.890862     11.004552    0.882222
2025-05-25 05:40:05     12.572007     0.891577     10.018670    0.881782
2025-05-25 05:45:05      5.497275     0.891864     11.853415    0.882506

                     abs_error  threshold  y3_prediction  y3_abs_error
Time
2025-05-25 05:20:05   0.000524   0.000524      10.037298      0.044525
2025-05-25 05:30:05   0.001717   0.001598      10.559907      0.152750
2025-05-25 05:35:05   0.000391   0.000391      11.041227      0.036675
2025-05-25 05:40:05   0.000773   0.000735      10.084624      0.065954
2025-05-25 05:45:05   0.001141   0.001141      11.969678      0.116263

[5 rows x 50 columns]

  0%|          | 0/7485 [00:00<?, ?it/s]

  0%|          | 0/7485 [00:00<?, ?it/s]

  0%|          | 1/7485 [00:00<1:14:56,  1.66it/s]

  0%|          | 1/7485 [00:00<1:14:56,  1.66it/s]
  0%|          | 2/7485 [00:00<1:14:55,  1.66it/s]

  0%|          | 3/7485 [00:01<45:44,  2.73it/s]

  0%|          | 3/7485 [00:01<45:44,  2.73it/s]
  0%|          | 4/7485 [00:01<45:44,  2.73it/s]
  0%|          | 5/7485 [00:01<45:44,  2.73it/s]

  0%|          | 6/7485 [00:01<32:51,  3.79it/s]

  0%|          | 6/7485 [00:01<32:51,  3.79it/s]
  0%|          | 7/7485 [00:01<32:51,  3.79it/s]
  0%|          | 8/7485 [00:01<32:51,  3.79it/s]

  0%|          | 9/7485 [00:02<29:19,  4.25it/s]

  0%|          | 9/7485 [00:02<29:19,  4.25it/s]
  0%|          | 10/7485 [00:02<29:19,  4.25it/s]
  0%|          | 11/7485 [00:02<29:19,  4.25it/s]

  0%|          | 12/7485 [00:02<26:48,  4.65it/s]

  0%|          | 12/7485 [00:02<26:48,  4.65it/s]
  0%|          | 13/7485 [00:02<26:48,  4.65it/s]
  0%|          | 14/7485 [00:02<26:47,  4.65it/s]

  0%|          | 15/7485 [00:03<26:05,  4.77it/s]

  0%|          | 15/7485 [00:03<26:05,  4.77it/s]
  0%|          | 16/7485 [00:03<26:05,  4.77it/s]

  0%|          | 17/7485 [00:04<28:10,  4.42it/s]

  0%|          | 17/7485 [00:04<28:10,  4.42it/s]
  0%|          | 18/7485 [00:04<28:10,  4.42it/s]

  0%|          | 19/7485 [00:04<30:22,  4.10it/s]

  0%|          | 19/7485 [00:04<30:22,  4.10it/s]
  0%|          | 20/7485 [00:04<30:22,  4.10it/s]

  0%|          | 21/7485 [00:05<31:57,  3.89it/s]

  0%|          | 21/7485 [00:05<31:57,  3.89it/s]
  0%|          | 22/7485 [00:05<31:56,  3.89it/s]

  0%|          | 23/7485 [00:05<33:11,  3.75it/s]

  0%|          | 23/7485 [00:05<33:11,  3.75it/s]
  0%|          | 24/7485 [00:05<33:11,  3.75it/s]

  0%|          | 25/7485 [00:06<33:52,  3.67it/s]

  0%|          | 25/7485 [00:06<33:52,  3.67it/s]
  0%|          | 26/7485 [00:06<33:51,  3.67it/s]

  0%|          | 27/7485 [00:06<34:40,  3.58it/s]

  0%|          | 27/7485 [00:06<34:40,  3.58it/s]
  0%|          | 28/7485 [00:07<34:40,  3.58it/s]

  0%|          | 29/7485 [00:07<34:44,  3.58it/s]

  0%|          | 29/7485 [00:07<34:44,  3.58it/s]
  0%|          | 30/7485 [00:07<34:44,  3.58it/s]

  0%|          | 31/7485 [00:08<34:54,  3.56it/s]

  0%|          | 31/7485 [00:08<34:54,  3.56it/s]
  0%|          | 32/7485 [00:08<34:54,  3.56it/s]

  0%|          | 33/7485 [00:08<35:27,  3.50it/s]

  0%|          | 33/7485 [00:08<35:27,  3.50it/s]
  0%|          | 34/7485 [00:08<35:27,  3.50it/s]
  0%|          | 35/7485 [00:08<35:27,  3.50it/s]

  0%|          | 36/7485 [00:11<1:08:42,  1.81it/s]

  0%|          | 36/7485 [00:11<1:08:42,  1.81it/s]
  0%|          | 37/7485 [00:11<1:08:41,  1.81it/s]
  1%|          | 38/7485 [00:11<1:08:40,  1.81it/s]
  1%|          | 39/7485 [00:11<1:08:40,  1.81it/s]

  1%|          | 40/7485 [00:12<47:14,  2.63it/s]

  1%|          | 40/7485 [00:12<47:14,  2.63it/s]
  1%|          | 41/7485 [00:12<47:14,  2.63it/s]
  1%|          | 42/7485 [00:12<47:13,  2.63it/s]
  1%|          | 43/7485 [00:12<47:13,  2.63it/s]
  1%|          | 44/7485 [00:12<47:13,  2.63it/s]
  1%|          | 45/7485 [00:12<47:12,  2.63it/s]

  1%|          | 46/7485 [00:12<30:11,  4.11it/s]

  1%|          | 46/7485 [00:12<30:11,  4.11it/s]
  1%|          | 47/7485 [00:12<30:11,  4.11it/s]

  1%|          | 48/7485 [00:13<31:14,  3.97it/s]

  1%|          | 48/7485 [00:13<31:14,  3.97it/s]
  1%|          | 49/7485 [00:13<31:13,  3.97it/s]
  1%|          | 50/7485 [00:13<31:13,  3.97it/s]

  1%|          | 51/7485 [00:13<28:37,  4.33it/s]

  1%|          | 51/7485 [00:13<28:37,  4.33it/s]
  1%|          | 52/7485 [00:13<28:36,  4.33it/s]

  1%|          | 53/7485 [00:14<29:57,  4.14it/s]

  1%|          | 53/7485 [00:14<29:57,  4.14it/s]
  1%|          | 54/7485 [00:14<29:56,  4.14it/s]

  1%|          | 55/7485 [00:14<30:34,  4.05it/s]

  1%|          | 55/7485 [00:14<30:34,  4.05it/s]
  1%|          | 56/7485 [00:15<30:33,  4.05it/s]
  1%|          | 57/7485 [00:15<30:33,  4.05it/s]
  1%|          | 58/7485 [00:15<30:33,  4.05it/s]
  1%|          | 59/7485 [00:15<30:33,  4.05it/s]

  1%|          | 60/7485 [00:15<22:51,  5.42it/s]

  1%|          | 60/7485 [00:15<22:51,  5.42it/s]
  1%|          | 61/7485 [00:15<22:50,  5.42it/s]

  1%|          | 62/7485 [00:16<25:29,  4.85it/s]

  1%|          | 62/7485 [00:16<25:29,  4.85it/s]
  1%|          | 63/7485 [00:16<25:29,  4.85it/s]

  1%|          | 64/7485 [00:16<27:13,  4.54it/s]

  1%|          | 64/7485 [00:16<27:13,  4.54it/s]
  1%|          | 65/7485 [00:16<27:12,  4.54it/s]

  1%|          | 66/7485 [00:17<29:02,  4.26it/s]

  1%|          | 66/7485 [00:17<29:02,  4.26it/s]
  1%|          | 67/7485 [00:17<29:02,  4.26it/s]

  1%|          | 68/7485 [00:17<30:08,  4.10it/s]

  1%|          | 68/7485 [00:17<30:08,  4.10it/s]
  1%|          | 69/7485 [00:17<30:08,  4.10it/s]

  1%|          | 70/7485 [00:18<31:27,  3.93it/s]

  1%|          | 70/7485 [00:18<31:27,  3.93it/s]
  1%|          | 71/7485 [00:18<31:27,  3.93it/s]

  1%|          | 72/7485 [00:18<32:01,  3.86it/s]

  1%|          | 72/7485 [00:18<32:01,  3.86it/s]
  1%|          | 73/7485 [00:18<32:01,  3.86it/s]
  1%|          | 74/7485 [00:18<32:01,  3.86it/s]
  1%|          | 75/7485 [00:18<32:01,  3.86it/s]

  1%|          | 76/7485 [00:19<26:01,  4.75it/s]

  1%|          | 76/7485 [00:19<26:01,  4.75it/s]
  1%|          | 77/7485 [00:19<26:00,  4.75it/s]

  1%|          | 78/7485 [00:20<28:02,  4.40it/s]

  1%|          | 78/7485 [00:20<28:02,  4.40it/s]
  1%|          | 79/7485 [00:20<28:02,  4.40it/s]

  1%|          | 80/7485 [00:20<30:24,  4.06it/s]

  1%|          | 80/7485 [00:20<30:24,  4.06it/s]
  1%|          | 81/7485 [00:20<30:24,  4.06it/s]

  1%|          | 82/7485 [00:21<32:08,  3.84it/s]

  1%|          | 82/7485 [00:21<32:08,  3.84it/s]
  1%|          | 83/7485 [00:21<32:08,  3.84it/s]

  1%|          | 84/7485 [00:23<57:25,  2.15it/s]

  1%|          | 84/7485 [00:23<57:25,  2.15it/s]
  1%|          | 85/7485 [00:23<57:24,  2.15it/s]

  1%|          | 86/7485 [00:24<1:07:36,  1.82it/s]

  1%|          | 86/7485 [00:24<1:07:36,  1.82it/s]
  1%|          | 87/7485 [00:24<1:07:35,  1.82it/s]

  1%|          | 88/7485 [00:25<58:59,  2.09it/s]

  1%|          | 88/7485 [00:25<58:59,  2.09it/s]
  1%|          | 89/7485 [00:25<58:59,  2.09it/s]
  1%|          | 90/7485 [00:25<58:58,  2.09it/s]

  1%|          | 91/7485 [00:26<46:50,  2.63it/s]

  1%|          | 91/7485 [00:26<46:50,  2.63it/s]
  1%|          | 92/7485 [00:26<46:50,  2.63it/s]

  1%|          | 93/7485 [00:26<45:07,  2.73it/s]

  1%|          | 93/7485 [00:26<45:07,  2.73it/s]
  1%|▏         | 94/7485 [00:26<45:07,  2.73it/s]

  1%|▏         | 95/7485 [00:27<43:25,  2.84it/s]

  1%|▏         | 95/7485 [00:27<43:25,  2.84it/s]
  1%|▏         | 96/7485 [00:27<43:25,  2.84it/s]

  1%|▏         | 97/7485 [00:27<42:41,  2.88it/s]

  1%|▏         | 97/7485 [00:27<42:41,  2.88it/s]
  1%|▏         | 98/7485 [00:27<42:41,  2.88it/s]

  1%|▏         | 99/7485 [00:28<42:09,  2.92it/s]

  1%|▏         | 99/7485 [00:28<42:09,  2.92it/s]
  1%|▏         | 100/7485 [00:28<42:09,  2.92it/s]

  1%|▏         | 101/7485 [00:29<41:09,  2.99it/s]

  1%|▏         | 101/7485 [00:29<41:09,  2.99it/s]
  1%|▏         | 102/7485 [00:29<41:09,  2.99it/s]

  1%|▏         | 103/7485 [00:29<40:47,  3.02it/s]

  1%|▏         | 103/7485 [00:29<40:47,  3.02it/s]
  1%|▏         | 104/7485 [00:29<40:47,  3.02it/s]
  1%|▏         | 105/7485 [00:29<40:46,  3.02it/s]

  1%|▏         | 106/7485 [00:30<35:07,  3.50it/s]

  1%|▏         | 106/7485 [00:30<35:07,  3.50it/s]
  1%|▏         | 107/7485 [00:30<35:06,  3.50it/s]

  1%|▏         | 108/7485 [00:31<36:45,  3.35it/s]

  1%|▏         | 108/7485 [00:31<36:45,  3.35it/s]
  1%|▏         | 109/7485 [00:31<36:44,  3.35it/s]

  1%|▏         | 110/7485 [00:31<38:16,  3.21it/s]

  1%|▏         | 110/7485 [00:31<38:16,  3.21it/s]
  1%|▏         | 111/7485 [00:31<38:15,  3.21it/s]

  1%|▏         | 112/7485 [00:32<38:55,  3.16it/s]

  1%|▏         | 112/7485 [00:32<38:55,  3.16it/s]
  2%|▏         | 113/7485 [00:32<38:55,  3.16it/s]

  2%|▏         | 114/7485 [00:33<39:38,  3.10it/s]

  2%|▏         | 114/7485 [00:33<39:38,  3.10it/s]
  2%|▏         | 115/7485 [00:33<39:38,  3.10it/s]

  2%|▏         | 116/7485 [00:33<39:55,  3.08it/s]

  2%|▏         | 116/7485 [00:33<39:55,  3.08it/s]
  2%|▏         | 117/7485 [00:33<39:54,  3.08it/s]

  2%|▏         | 118/7485 [00:36<1:09:07,  1.78it/s]

  2%|▏         | 118/7485 [00:36<1:09:07,  1.78it/s]
  2%|▏         | 119/7485 [00:36<1:09:06,  1.78it/s]

  2%|▏         | 120/7485 [00:37<1:13:34,  1.67it/s]

  2%|▏         | 120/7485 [00:37<1:13:34,  1.67it/s]
  2%|▏         | 121/7485 [00:37<1:13:33,  1.67it/s]

  2%|▏         | 122/7485 [00:38<1:03:32,  1.93it/s]

  2%|▏         | 122/7485 [00:38<1:03:32,  1.93it/s]
  2%|▏         | 123/7485 [00:38<1:03:31,  1.93it/s]
  2%|▏         | 124/7485 [00:38<1:03:31,  1.93it/s]

  2%|▏         | 125/7485 [00:38<49:13,  2.49it/s]

  2%|▏         | 125/7485 [00:38<49:13,  2.49it/s]
  2%|▏         | 126/7485 [00:38<49:13,  2.49it/s]

  2%|▏         | 127/7485 [00:39<47:01,  2.61it/s]

  2%|▏         | 127/7485 [00:39<47:01,  2.61it/s]
  2%|▏         | 128/7485 [00:39<47:00,  2.61it/s]

  2%|▏         | 129/7485 [00:40<45:14,  2.71it/s]

  2%|▏         | 129/7485 [00:40<45:14,  2.71it/s]
  2%|▏         | 130/7485 [00:40<45:13,  2.71it/s]
  2%|▏         | 131/7485 [00:40<45:13,  2.71it/s]

  2%|▏         | 132/7485 [00:40<37:52,  3.24it/s]

  2%|▏         | 132/7485 [00:40<37:52,  3.24it/s]
  2%|▏         | 133/7485 [00:40<37:52,  3.24it/s]

  2%|▏         | 134/7485 [00:41<39:25,  3.11it/s]

  2%|▏         | 134/7485 [00:41<39:25,  3.11it/s]
  2%|▏         | 135/7485 [00:41<39:25,  3.11it/s]
  2%|▏         | 136/7485 [00:41<39:25,  3.11it/s]
  2%|▏         | 137/7485 [00:41<39:24,  3.11it/s]
  2%|▏         | 138/7485 [00:41<39:24,  3.11it/s]
  2%|▏         | 139/7485 [00:41<39:24,  3.11it/s]
  2%|▏         | 140/7485 [00:41<39:23,  3.11it/s]

  2%|▏         | 141/7485 [00:42<23:02,  5.31it/s]

  2%|▏         | 141/7485 [00:42<23:02,  5.31it/s]
  2%|▏         | 142/7485 [00:42<23:01,  5.31it/s]
  2%|▏         | 143/7485 [00:42<23:01,  5.31it/s]
  2%|▏         | 144/7485 [00:42<23:01,  5.31it/s]
  2%|▏         | 145/7485 [00:42<23:01,  5.31it/s]

  2%|▏         | 146/7485 [00:42<20:31,  5.96it/s]

  2%|▏         | 146/7485 [00:42<20:31,  5.96it/s]
  2%|▏         | 147/7485 [00:42<20:31,  5.96it/s]

  2%|▏         | 148/7485 [00:43<23:34,  5.19it/s]
  2%|▏         | 158/7485 [00:43<11:11, 10.90it/s]

  2%|▏         | 148/7485 [00:43<23:34,  5.19it/s]
  2%|▏         | 149/7485 [00:43<23:34,  5.19it/s]
  2%|▏         | 150/7485 [00:43<23:34,  5.19it/s]
  2%|▏         | 151/7485 [00:43<23:33,  5.19it/s]
  2%|▏         | 152/7485 [00:43<23:33,  5.19it/s]
  2%|▏         | 153/7485 [00:43<23:33,  5.19it/s]
  2%|▏         | 154/7485 [00:43<23:33,  5.19it/s]
  2%|▏         | 155/7485 [00:43<23:33,  5.19it/s]
  2%|▏         | 156/7485 [00:43<23:32,  5.19it/s]
  2%|▏         | 157/7485 [00:43<23:32,  5.19it/s]
  2%|▏         | 158/7485 [00:43<11:11, 10.90it/s]
  2%|▏         | 159/7485 [00:43<11:11, 10.90it/s]
  2%|▏         | 160/7485 [00:43<11:11, 10.90it/s]
  2%|▏         | 161/7485 [00:43<11:11, 10.90it/s]
  2%|▏         | 162/7485 [00:43<11:11, 10.90it/s]
  2%|▏         | 163/7485 [00:43<11:11, 10.90it/s]
  2%|▏         | 164/7485 [00:43<11:11, 10.90it/s]
  2%|▏         | 165/7485 [00:43<11:11, 10.90it/s]
  2%|▏         | 166/7485 [00:43<11:11, 10.90it/s]
  2%|▏         | 167/7485 [00:43<11:11, 10.90it/s]

  2%|▏         | 168/7485 [00:44<09:47, 12.46it/s]

  2%|▏         | 168/7485 [00:44<09:47, 12.46it/s]
  2%|▏         | 169/7485 [00:44<09:47, 12.46it/s]

  2%|▏         | 171/7485 [00:44<12:31,  9.73it/s]
  2%|▏         | 181/7485 [00:44<07:38, 15.92it/s]

  2%|▏         | 170/7485 [00:44<09:46, 12.46it/s]
  2%|▏         | 171/7485 [00:44<12:31,  9.73it/s]
  2%|▏         | 172/7485 [00:44<12:31,  9.73it/s]
  2%|▏         | 173/7485 [00:44<12:31,  9.73it/s]
  2%|▏         | 174/7485 [00:44<12:31,  9.73it/s]
  2%|▏         | 175/7485 [00:44<12:31,  9.73it/s]
  2%|▏         | 176/7485 [00:44<12:31,  9.73it/s]
  2%|▏         | 177/7485 [00:44<12:31,  9.73it/s]
  2%|▏         | 178/7485 [00:44<12:30,  9.73it/s]
  2%|▏         | 179/7485 [00:44<12:30,  9.73it/s]
  2%|▏         | 180/7485 [00:44<12:30,  9.73it/s]
  2%|▏         | 181/7485 [00:44<07:38, 15.92it/s]
  2%|▏         | 182/7485 [00:44<07:38, 15.92it/s]
  2%|▏         | 183/7485 [00:44<07:38, 15.92it/s]
  2%|▏         | 184/7485 [00:44<07:38, 15.92it/s]
  2%|▏         | 185/7485 [00:44<07:38, 15.92it/s]
  2%|▏         | 186/7485 [00:44<07:38, 15.92it/s]
  2%|▏         | 187/7485 [00:44<07:38, 15.92it/s]
  3%|▎         | 188/7485 [00:44<07:38, 15.92it/s]
  3%|▎         | 189/7485 [00:44<07:38, 15.92it/s]
  3%|▎         | 190/7485 [00:44<07:38, 15.92it/s]
  3%|▎         | 191/7485 [00:44<07:38, 15.92it/s]
  3%|▎         | 192/7485 [00:44<07:38, 15.92it/s]
  3%|▎         | 193/7485 [00:45<07:38, 15.92it/s]
  3%|▎         | 194/7485 [00:45<07:38, 15.92it/s]
  3%|▎         | 195/7485 [00:45<07:38, 15.92it/s]
  3%|▎         | 196/7485 [00:45<07:37, 15.92it/s]
  3%|▎         | 197/7485 [00:45<07:37, 15.92it/s]

  3%|▎         | 198/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 212/7485 [00:45<02:57, 41.09it/s]

  3%|▎         | 198/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 199/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 200/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 201/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 202/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 203/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 204/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 205/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 206/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 207/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 208/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 209/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 210/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 211/7485 [00:45<04:08, 29.29it/s]
  3%|▎         | 212/7485 [00:45<02:57, 41.09it/s]
  3%|▎         | 213/7485 [00:45<02:56, 41.09it/s]
  3%|▎         | 214/7485 [00:45<02:56, 41.09it/s]
  3%|▎         | 215/7485 [00:45<02:56, 41.09it/s]
  3%|▎         | 216/7485 [00:45<02:56, 41.09it/s]
  3%|▎         | 217/7485 [00:45<02:56, 41.09it/s]
  3%|▎         | 218/7485 [00:45<02:56, 41.09it/s]
  3%|▎         | 219/7485 [00:45<02:56, 41.09it/s]
  3%|▎         | 220/7485 [00:45<02:56, 41.09it/s]

  3%|▎         | 222/7485 [00:46<07:01, 17.25it/s]

  3%|▎         | 221/7485 [00:46<02:56, 41.09it/s]
  3%|▎         | 222/7485 [00:46<07:01, 17.25it/s]
  3%|▎         | 223/7485 [00:46<07:00, 17.25it/s]
  3%|▎         | 224/7485 [00:49<07:00, 17.25it/s]
  3%|▎         | 225/7485 [00:49<07:00, 17.25it/s]

  3%|▎         | 229/7485 [00:50<19:00,  6.36it/s]

  3%|▎         | 226/7485 [00:50<07:00, 17.25it/s]
  3%|▎         | 227/7485 [00:50<07:00, 17.25it/s]
  3%|▎         | 228/7485 [00:50<07:00, 17.25it/s]
  3%|▎         | 229/7485 [00:50<19:00,  6.36it/s]
  3%|▎         | 230/7485 [00:50<19:00,  6.36it/s]
  3%|▎         | 231/7485 [00:50<19:00,  6.36it/s]
  3%|▎         | 232/7485 [00:50<18:59,  6.36it/s]

  3%|▎         | 234/7485 [00:50<18:39,  6.47it/s]

  3%|▎         | 233/7485 [00:50<18:59,  6.36it/s]
  3%|▎         | 234/7485 [00:50<18:39,  6.47it/s]
  3%|▎         | 235/7485 [00:50<18:39,  6.47it/s]
  3%|▎         | 236/7485 [00:50<18:39,  6.47it/s]
  3%|▎         | 237/7485 [00:50<18:39,  6.47it/s]

  3%|▎         | 238/7485 [00:51<19:11,  6.30it/s]

  3%|▎         | 238/7485 [00:51<19:11,  6.30it/s]
  3%|▎         | 239/7485 [00:51<19:11,  6.30it/s]
  3%|▎         | 240/7485 [00:51<19:10,  6.30it/s]

  3%|▎         | 241/7485 [00:52<20:30,  5.89it/s]

  3%|▎         | 241/7485 [00:52<20:30,  5.89it/s]
  3%|▎         | 242/7485 [00:52<20:30,  5.89it/s]

  3%|▎         | 243/7485 [00:53<23:35,  5.12it/s]

  3%|▎         | 243/7485 [00:53<23:35,  5.12it/s]
  3%|▎         | 244/7485 [00:53<23:35,  5.12it/s]

  3%|▎         | 245/7485 [00:53<26:39,  4.53it/s]

  3%|▎         | 245/7485 [00:53<26:39,  4.53it/s]
  3%|▎         | 246/7485 [00:53<26:39,  4.53it/s]

  3%|▎         | 247/7485 [00:54<29:12,  4.13it/s]

  3%|▎         | 247/7485 [00:54<29:12,  4.13it/s]
  3%|▎         | 248/7485 [00:54<29:12,  4.13it/s]

  3%|▎         | 249/7485 [00:55<31:52,  3.78it/s]

  3%|▎         | 249/7485 [00:55<31:52,  3.78it/s]
  3%|▎         | 250/7485 [00:55<31:52,  3.78it/s]

  3%|▎         | 251/7485 [00:55<33:32,  3.59it/s]

  3%|▎         | 251/7485 [00:55<33:32,  3.59it/s]
  3%|▎         | 252/7485 [00:55<33:32,  3.59it/s]

  3%|▎         | 253/7485 [00:56<35:50,  3.36it/s]

  3%|▎         | 253/7485 [00:56<35:50,  3.36it/s]
  3%|▎         | 254/7485 [00:56<35:50,  3.36it/s]

  3%|▎         | 255/7485 [00:57<37:27,  3.22it/s]

  3%|▎         | 255/7485 [00:57<37:27,  3.22it/s]
  3%|▎         | 256/7485 [00:57<37:27,  3.22it/s]

  3%|▎         | 257/7485 [00:57<37:53,  3.18it/s]

  3%|▎         | 257/7485 [00:57<37:53,  3.18it/s]
  3%|▎         | 258/7485 [00:57<37:53,  3.18it/s]

  3%|▎         | 259/7485 [00:58<38:33,  3.12it/s]

  3%|▎         | 259/7485 [00:58<38:33,  3.12it/s]
  3%|▎         | 260/7485 [00:58<38:32,  3.12it/s]

  3%|▎         | 261/7485 [00:59<39:28,  3.05it/s]

  3%|▎         | 261/7485 [00:59<39:28,  3.05it/s]
  4%|▎         | 262/7485 [00:59<39:27,  3.05it/s]

  4%|▎         | 263/7485 [01:02<1:20:53,  1.49it/s]

  4%|▎         | 263/7485 [01:02<1:20:53,  1.49it/s]
  4%|▎         | 264/7485 [01:02<1:20:52,  1.49it/s]

  4%|▎         | 265/7485 [01:02<1:08:41,  1.75it/s]

  4%|▎         | 265/7485 [01:02<1:08:41,  1.75it/s]
  4%|▎         | 266/7485 [01:02<1:08:40,  1.75it/s]

  4%|▎         | 267/7485 [01:03<1:00:20,  1.99it/s]

  4%|▎         | 267/7485 [01:03<1:00:20,  1.99it/s]
  4%|▎         | 268/7485 [01:03<1:00:20,  1.99it/s]

  4%|▎         | 269/7485 [01:04<54:01,  2.23it/s]

  4%|▎         | 269/7485 [01:04<54:01,  2.23it/s]
  4%|▎         | 270/7485 [01:04<54:01,  2.23it/s]

  4%|▎         | 271/7485 [01:04<49:54,  2.41it/s]

  4%|▎         | 271/7485 [01:04<49:54,  2.41it/s]
  4%|▎         | 272/7485 [01:04<49:54,  2.41it/s]

  4%|▎         | 273/7485 [01:05<47:22,  2.54it/s]

  4%|▎         | 273/7485 [01:05<47:22,  2.54it/s]
  4%|▎         | 274/7485 [01:05<47:22,  2.54it/s]

  4%|▎         | 275/7485 [01:06<45:23,  2.65it/s]

  4%|▎         | 275/7485 [01:06<45:23,  2.65it/s]
  4%|▎         | 276/7485 [01:06<45:23,  2.65it/s]

  4%|▎         | 277/7485 [01:06<44:03,  2.73it/s]

  4%|▎         | 277/7485 [01:06<44:03,  2.73it/s]
  4%|▎         | 278/7485 [01:07<44:02,  2.73it/s]

  4%|▎         | 279/7485 [01:07<43:12,  2.78it/s]

  4%|▎         | 279/7485 [01:07<43:12,  2.78it/s]
  4%|▎         | 280/7485 [01:07<43:12,  2.78it/s]

  4%|▍         | 281/7485 [01:08<42:38,  2.82it/s]

  4%|▍         | 281/7485 [01:08<42:38,  2.82it/s]
  4%|▍         | 282/7485 [01:08<42:37,  2.82it/s]

  4%|▍         | 283/7485 [01:09<42:28,  2.83it/s]

  4%|▍         | 283/7485 [01:09<42:28,  2.83it/s]
  4%|▍         | 284/7485 [01:09<42:28,  2.83it/s]
  4%|▍         | 285/7485 [01:09<42:28,  2.83it/s]

  4%|▍         | 286/7485 [01:09<37:21,  3.21it/s]

  4%|▍         | 286/7485 [01:09<37:21,  3.21it/s]
  4%|▍         | 287/7485 [01:09<37:20,  3.21it/s]
  4%|▍         | 288/7485 [01:09<37:20,  3.21it/s]
  4%|▍         | 289/7485 [01:09<37:20,  3.21it/s]

  4%|▍         | 290/7485 [01:10<30:06,  3.98it/s]

  4%|▍         | 290/7485 [01:10<30:06,  3.98it/s]
  4%|▍         | 291/7485 [01:10<30:06,  3.98it/s]
  4%|▍         | 292/7485 [01:10<30:06,  3.98it/s]

  4%|▍         | 293/7485 [01:11<30:17,  3.96it/s]

  4%|▍         | 293/7485 [01:11<30:17,  3.96it/s]
  4%|▍         | 294/7485 [01:11<30:16,  3.96it/s]

  4%|▍         | 295/7485 [01:11<32:55,  3.64it/s]

  4%|▍         | 295/7485 [01:11<32:55,  3.64it/s]
  4%|▍         | 296/7485 [01:11<32:54,  3.64it/s]
  4%|▍         | 297/7485 [01:11<32:54,  3.64it/s]

  4%|▍         | 298/7485 [01:14<1:01:21,  1.95it/s]

  4%|▍         | 298/7485 [01:14<1:01:21,  1.95it/s]
  4%|▍         | 299/7485 [01:14<1:01:21,  1.95it/s]
  4%|▍         | 300/7485 [01:14<1:01:20,  1.95it/s]
  4%|▍         | 301/7485 [01:15<1:01:19,  1.95it/s]
  4%|▍         | 302/7485 [01:15<1:01:19,  1.95it/s]
  4%|▍         | 303/7485 [01:15<1:01:18,  1.95it/s]

  4%|▍         | 304/7485 [01:15<38:25,  3.11it/s]

  4%|▍         | 304/7485 [01:15<38:25,  3.11it/s]
  4%|▍         | 305/7485 [01:15<38:25,  3.11it/s]

  4%|▍         | 306/7485 [01:16<39:02,  3.06it/s]

  4%|▍         | 306/7485 [01:16<39:02,  3.06it/s]
  4%|▍         | 307/7485 [01:16<39:02,  3.06it/s]

  4%|▍         | 308/7485 [01:17<39:17,  3.04it/s]

  4%|▍         | 308/7485 [01:17<39:17,  3.04it/s]
  4%|▍         | 309/7485 [01:17<39:16,  3.04it/s]

  4%|▍         | 310/7485 [01:17<38:57,  3.07it/s]

  4%|▍         | 310/7485 [01:17<38:57,  3.07it/s]
  4%|▍         | 311/7485 [01:17<38:57,  3.07it/s]
  4%|▍         | 312/7485 [01:17<38:56,  3.07it/s]
  4%|▍         | 313/7485 [01:17<38:56,  3.07it/s]
  4%|▍         | 314/7485 [01:17<38:56,  3.07it/s]

  4%|▍         | 315/7485 [01:18<28:34,  4.18it/s]

  4%|▍         | 315/7485 [01:18<28:34,  4.18it/s]
  4%|▍         | 316/7485 [01:18<28:34,  4.18it/s]

  4%|▍         | 317/7485 [01:18<30:28,  3.92it/s]

  4%|▍         | 317/7485 [01:18<30:28,  3.92it/s]
  4%|▍         | 318/7485 [01:18<30:28,  3.92it/s]

  4%|▍         | 319/7485 [01:19<32:21,  3.69it/s]

  4%|▍         | 319/7485 [01:19<32:21,  3.69it/s]
  4%|▍         | 320/7485 [01:19<32:21,  3.69it/s]

  4%|▍         | 321/7485 [01:20<33:38,  3.55it/s]

  4%|▍         | 321/7485 [01:20<33:38,  3.55it/s]
  4%|▍         | 322/7485 [01:20<33:38,  3.55it/s]

  4%|▍         | 323/7485 [01:20<33:59,  3.51it/s]

  4%|▍         | 323/7485 [01:20<33:59,  3.51it/s]
  4%|▍         | 324/7485 [01:20<33:58,  3.51it/s]
  4%|▍         | 325/7485 [01:20<33:58,  3.51it/s]
  4%|▍         | 326/7485 [01:20<33:58,  3.51it/s]
  4%|▍         | 327/7485 [01:20<33:58,  3.51it/s]
  4%|▍         | 328/7485 [01:20<33:57,  3.51it/s]

  4%|▍         | 329/7485 [01:21<22:58,  5.19it/s]

  4%|▍         | 329/7485 [01:21<22:58,  5.19it/s]
  4%|▍         | 330/7485 [01:21<22:58,  5.19it/s]

  4%|▍         | 331/7485 [01:22<25:27,  4.68it/s]
  5%|▍         | 340/7485 [01:22<11:52, 10.03it/s]

  4%|▍         | 331/7485 [01:22<25:27,  4.68it/s]
  4%|▍         | 332/7485 [01:22<25:27,  4.68it/s]
  4%|▍         | 333/7485 [01:22<25:26,  4.68it/s]
  4%|▍         | 334/7485 [01:22<25:26,  4.68it/s]
  4%|▍         | 335/7485 [01:22<25:26,  4.68it/s]
  4%|▍         | 336/7485 [01:22<25:26,  4.68it/s]
  5%|▍         | 337/7485 [01:22<25:26,  4.68it/s]
  5%|▍         | 338/7485 [01:22<25:25,  4.68it/s]
  5%|▍         | 339/7485 [01:22<25:25,  4.68it/s]
  5%|▍         | 340/7485 [01:22<11:52, 10.03it/s]
  5%|▍         | 341/7485 [01:22<11:52, 10.03it/s]
  5%|▍         | 342/7485 [01:22<11:52, 10.03it/s]

  5%|▍         | 343/7485 [01:23<19:12,  6.20it/s]

  5%|▍         | 343/7485 [01:23<19:12,  6.20it/s]
  5%|▍         | 344/7485 [01:23<19:12,  6.20it/s]

  5%|▍         | 346/7485 [01:23<20:21,  5.84it/s]

  5%|▍         | 345/7485 [01:23<19:12,  6.20it/s]
  5%|▍         | 346/7485 [01:23<20:21,  5.84it/s]

  5%|▍         | 348/7485 [01:24<23:39,  5.03it/s]

  5%|▍         | 347/7485 [01:24<20:21,  5.84it/s]
  5%|▍         | 348/7485 [01:24<23:39,  5.03it/s]
  5%|▍         | 349/7485 [01:24<23:39,  5.03it/s]
  5%|▍         | 350/7485 [01:24<23:39,  5.03it/s]

  5%|▍         | 351/7485 [01:27<49:14,  2.41it/s]

  5%|▍         | 351/7485 [01:27<49:14,  2.41it/s]
  5%|▍         | 352/7485 [01:27<49:13,  2.41it/s]

  5%|▍         | 353/7485 [01:28<46:53,  2.54it/s]

  5%|▍         | 353/7485 [01:28<46:53,  2.54it/s]
  5%|▍         | 354/7485 [01:28<46:52,  2.54it/s]

  5%|▍         | 355/7485 [01:28<45:15,  2.63it/s]

  5%|▍         | 355/7485 [01:28<45:15,  2.63it/s]
  5%|▍         | 356/7485 [01:28<45:15,  2.63it/s]

  5%|▍         | 357/7485 [01:29<43:35,  2.73it/s]

  5%|▍         | 357/7485 [01:29<43:35,  2.73it/s]
  5%|▍         | 358/7485 [01:29<43:34,  2.73it/s]

  5%|▍         | 359/7485 [01:30<42:46,  2.78it/s]

  5%|▍         | 359/7485 [01:30<42:46,  2.78it/s]
  5%|▍         | 360/7485 [01:30<42:46,  2.78it/s]

  5%|▍         | 361/7485 [01:30<42:11,  2.81it/s]

  5%|▍         | 361/7485 [01:30<42:11,  2.81it/s]
  5%|▍         | 362/7485 [01:30<42:11,  2.81it/s]
  5%|▍         | 363/7485 [01:30<42:11,  2.81it/s]

  5%|▍         | 364/7485 [01:31<36:07,  3.28it/s]

  5%|▍         | 364/7485 [01:31<36:07,  3.28it/s]
  5%|▍         | 365/7485 [01:31<36:07,  3.28it/s]
  5%|▍         | 366/7485 [01:31<36:07,  3.28it/s]
  5%|▍         | 367/7485 [01:31<36:06,  3.28it/s]

  5%|▍         | 368/7485 [01:32<29:21,  4.04it/s]

  5%|▍         | 368/7485 [01:32<29:21,  4.04it/s]
  5%|▍         | 369/7485 [01:32<29:21,  4.04it/s]

  5%|▍         | 370/7485 [01:32<31:47,  3.73it/s]

  5%|▍         | 370/7485 [01:32<31:47,  3.73it/s]
  5%|▍         | 371/7485 [01:32<31:46,  3.73it/s]

  5%|▍         | 372/7485 [01:33<32:56,  3.60it/s]

  5%|▍         | 372/7485 [01:33<32:56,  3.60it/s]
  5%|▍         | 373/7485 [01:33<32:55,  3.60it/s]

  5%|▍         | 374/7485 [01:34<34:39,  3.42it/s]

  5%|▍         | 374/7485 [01:34<34:39,  3.42it/s]
  5%|▌         | 375/7485 [01:34<34:39,  3.42it/s]

  5%|▌         | 376/7485 [01:34<34:53,  3.40it/s]

  5%|▌         | 376/7485 [01:34<34:53,  3.40it/s]
  5%|▌         | 377/7485 [01:34<34:53,  3.40it/s]

  5%|▌         | 378/7485 [01:35<35:16,  3.36it/s]

  5%|▌         | 378/7485 [01:35<35:16,  3.36it/s]
  5%|▌         | 379/7485 [01:35<35:16,  3.36it/s]

  5%|▌         | 380/7485 [01:35<35:48,  3.31it/s]

  5%|▌         | 380/7485 [01:35<35:48,  3.31it/s]
  5%|▌         | 381/7485 [01:35<35:48,  3.31it/s]

  5%|▌         | 382/7485 [01:36<35:44,  3.31it/s]

  5%|▌         | 382/7485 [01:36<35:44,  3.31it/s]
  5%|▌         | 383/7485 [01:36<35:44,  3.31it/s]

  5%|▌         | 384/7485 [01:37<36:04,  3.28it/s]

  5%|▌         | 384/7485 [01:37<36:04,  3.28it/s]
  5%|▌         | 385/7485 [01:37<36:04,  3.28it/s]

  5%|▌         | 386/7485 [01:40<1:15:07,  1.57it/s]

  5%|▌         | 386/7485 [01:40<1:15:07,  1.57it/s]
  5%|▌         | 387/7485 [01:40<1:15:07,  1.57it/s]
  5%|▌         | 388/7485 [01:40<1:15:06,  1.57it/s]
  5%|▌         | 389/7485 [01:40<1:15:05,  1.57it/s]

  5%|▌         | 390/7485 [01:40<48:43,  2.43it/s]

  5%|▌         | 390/7485 [01:40<48:43,  2.43it/s]
  5%|▌         | 391/7485 [01:40<48:42,  2.43it/s]

  5%|▌         | 392/7485 [01:41<46:28,  2.54it/s]

  5%|▌         | 392/7485 [01:41<46:28,  2.54it/s]
  5%|▌         | 393/7485 [01:41<46:27,  2.54it/s]

  5%|▌         | 394/7485 [01:41<43:16,  2.73it/s]

  5%|▌         | 394/7485 [01:41<43:16,  2.73it/s]
  5%|▌         | 395/7485 [01:41<43:16,  2.73it/s]

  5%|▌         | 396/7485 [01:42<41:22,  2.86it/s]

  5%|▌         | 396/7485 [01:42<41:22,  2.86it/s]
  5%|▌         | 397/7485 [01:42<41:22,  2.86it/s]

  5%|▌         | 398/7485 [01:43<39:44,  2.97it/s]

  5%|▌         | 398/7485 [01:43<39:44,  2.97it/s]
  5%|▌         | 399/7485 [01:43<39:44,  2.97it/s]

  5%|▌         | 400/7485 [01:43<39:00,  3.03it/s]

  5%|▌         | 400/7485 [01:43<39:00,  3.03it/s]
  5%|▌         | 401/7485 [01:43<39:00,  3.03it/s]
  5%|▌         | 402/7485 [01:43<38:59,  3.03it/s]

  5%|▌         | 403/7485 [01:44<33:34,  3.52it/s]

  5%|▌         | 403/7485 [01:44<33:34,  3.52it/s]
  5%|▌         | 404/7485 [01:44<33:33,  3.52it/s]
  5%|▌         | 405/7485 [01:44<33:33,  3.52it/s]

  5%|▌         | 406/7485 [01:44<30:07,  3.92it/s]

  5%|▌         | 406/7485 [01:44<30:07,  3.92it/s]
  5%|▌         | 407/7485 [01:44<30:07,  3.92it/s]
  5%|▌         | 408/7485 [01:44<30:07,  3.92it/s]
  5%|▌         | 409/7485 [01:44<30:07,  3.92it/s]
  5%|▌         | 410/7485 [01:44<30:06,  3.92it/s]
  5%|▌         | 411/7485 [01:44<30:06,  3.92it/s]

  6%|▌         | 412/7485 [01:45<21:16,  5.54it/s]

  6%|▌         | 412/7485 [01:45<21:16,  5.54it/s]
  6%|▌         | 413/7485 [01:45<21:16,  5.54it/s]

  6%|▌         | 414/7485 [01:46<24:11,  4.87it/s]

  6%|▌         | 414/7485 [01:46<24:11,  4.87it/s]
  6%|▌         | 415/7485 [01:46<24:11,  4.87it/s]

  6%|▌         | 416/7485 [01:46<27:00,  4.36it/s]

  6%|▌         | 416/7485 [01:46<27:00,  4.36it/s]
  6%|▌         | 417/7485 [01:46<27:00,  4.36it/s]
  6%|▌         | 418/7485 [01:46<27:00,  4.36it/s]
  6%|▌         | 419/7485 [01:46<26:59,  4.36it/s]

  6%|▌         | 420/7485 [01:47<23:36,  4.99it/s]

  6%|▌         | 420/7485 [01:47<23:36,  4.99it/s]
  6%|▌         | 421/7485 [01:47<23:36,  4.99it/s]

  6%|▌         | 422/7485 [01:48<26:16,  4.48it/s]

  6%|▌         | 422/7485 [01:48<26:16,  4.48it/s]
  6%|▌         | 423/7485 [01:48<26:16,  4.48it/s]
  6%|▌         | 424/7485 [01:48<26:15,  4.48it/s]

  6%|▌         | 425/7485 [01:48<26:15,  4.48it/s]

  6%|▌         | 425/7485 [01:48<26:15,  4.48it/s]
  6%|▌         | 426/7485 [01:48<26:15,  4.48it/s]
  6%|▌         | 427/7485 [01:48<26:15,  4.48it/s]
  6%|▌         | 428/7485 [01:48<26:14,  4.48it/s]

  6%|▌         | 429/7485 [01:49<23:33,  4.99it/s]

  6%|▌         | 429/7485 [01:49<23:33,  4.99it/s]
  6%|▌         | 430/7485 [01:49<23:32,  4.99it/s]
  6%|▌         | 431/7485 [01:49<23:32,  4.99it/s]

  6%|▌         | 432/7485 [01:51<41:50,  2.81it/s]

  6%|▌         | 432/7485 [01:51<41:50,  2.81it/s]
  6%|▌         | 433/7485 [01:51<41:49,  2.81it/s]

  6%|▌         | 434/7485 [01:53<50:44,  2.32it/s]

  6%|▌         | 434/7485 [01:53<50:44,  2.32it/s]
  6%|▌         | 435/7485 [01:53<50:43,  2.32it/s]
  6%|▌         | 436/7485 [01:53<50:43,  2.32it/s]

  6%|▌         | 437/7485 [01:53<42:38,  2.75it/s]

  6%|▌         | 437/7485 [01:53<42:38,  2.75it/s]
  6%|▌         | 438/7485 [01:53<42:38,  2.75it/s]

  6%|▌         | 439/7485 [01:54<41:37,  2.82it/s]

  6%|▌         | 439/7485 [01:54<41:37,  2.82it/s]
  6%|▌         | 440/7485 [01:54<41:37,  2.82it/s]

  6%|▌         | 441/7485 [01:54<40:40,  2.89it/s]

  6%|▌         | 441/7485 [01:54<40:40,  2.89it/s]
  6%|▌         | 442/7485 [01:54<40:39,  2.89it/s]

  6%|▌         | 443/7485 [01:55<39:33,  2.97it/s]

  6%|▌         | 443/7485 [01:55<39:33,  2.97it/s]
  6%|▌         | 444/7485 [01:55<39:33,  2.97it/s]
  6%|▌         | 445/7485 [01:55<39:33,  2.97it/s]
  6%|▌         | 446/7485 [01:55<39:32,  2.97it/s]

  6%|▌         | 447/7485 [01:56<30:54,  3.80it/s]

  6%|▌         | 447/7485 [01:56<30:54,  3.80it/s]
  6%|▌         | 448/7485 [01:56<30:53,  3.80it/s]

  6%|▌         | 449/7485 [01:56<32:33,  3.60it/s]

  6%|▌         | 449/7485 [01:56<32:33,  3.60it/s]
  6%|▌         | 450/7485 [01:56<32:32,  3.60it/s]
  6%|▌         | 451/7485 [01:56<32:32,  3.60it/s]

  6%|▌         | 452/7485 [01:57<29:46,  3.94it/s]

  6%|▌         | 452/7485 [01:57<29:46,  3.94it/s]
  6%|▌         | 453/7485 [01:57<29:46,  3.94it/s]

  6%|▌         | 454/7485 [01:58<31:43,  3.69it/s]

  6%|▌         | 454/7485 [01:58<31:43,  3.69it/s]
  6%|▌         | 455/7485 [01:58<31:43,  3.69it/s]

  6%|▌         | 456/7485 [01:58<32:57,  3.55it/s]

  6%|▌         | 456/7485 [01:58<32:57,  3.55it/s]
  6%|▌         | 457/7485 [01:58<32:57,  3.55it/s]

  6%|▌         | 458/7485 [01:59<34:06,  3.43it/s]

  6%|▌         | 458/7485 [01:59<34:06,  3.43it/s]
  6%|▌         | 459/7485 [01:59<34:06,  3.43it/s]

  6%|▌         | 460/7485 [02:00<34:28,  3.40it/s]

  6%|▌         | 460/7485 [02:00<34:28,  3.40it/s]
  6%|▌         | 461/7485 [02:00<34:28,  3.40it/s]
  6%|▌         | 462/7485 [02:00<34:28,  3.40it/s]
  6%|▌         | 463/7485 [02:00<34:27,  3.40it/s]
  6%|▌         | 464/7485 [02:00<34:27,  3.40it/s]
  6%|▌         | 465/7485 [02:00<34:27,  3.40it/s]
  6%|▌         | 466/7485 [02:00<34:27,  3.40it/s]
  6%|▌         | 467/7485 [02:00<34:26,  3.40it/s]
  6%|▋         | 468/7485 [02:00<34:26,  3.40it/s]
  6%|▋         | 469/7485 [02:00<34:26,  3.40it/s]
  6%|▋         | 470/7485 [02:00<34:25,  3.40it/s]
  6%|▋         | 471/7485 [02:00<34:25,  3.40it/s]
  6%|▋         | 472/7485 [02:00<34:25,  3.40it/s]
  6%|▋         | 473/7485 [02:00<34:25,  3.40it/s]
  6%|▋         | 474/7485 [02:00<34:24,  3.40it/s]

  6%|▋         | 475/7485 [02:00<12:22,  9.44it/s]

  6%|▋         | 475/7485 [02:00<12:22,  9.44it/s]
  6%|▋         | 476/7485 [02:00<12:22,  9.44it/s]

  6%|▋         | 477/7485 [02:01<15:23,  7.59it/s]

  6%|▋         | 477/7485 [02:01<15:23,  7.59it/s]
  6%|▋         | 478/7485 [02:01<15:23,  7.59it/s]

  6%|▋         | 479/7485 [02:01<18:20,  6.37it/s]

  6%|▋         | 479/7485 [02:01<18:20,  6.37it/s]
  6%|▋         | 480/7485 [02:01<18:19,  6.37it/s]

  6%|▋         | 481/7485 [02:02<22:03,  5.29it/s]

  6%|▋         | 481/7485 [02:02<22:03,  5.29it/s]
  6%|▋         | 482/7485 [02:02<22:03,  5.29it/s]

  6%|▋         | 483/7485 [02:05<51:38,  2.26it/s]

  6%|▋         | 483/7485 [02:05<51:38,  2.26it/s]
  6%|▋         | 484/7485 [02:05<51:37,  2.26it/s]

  6%|▋         | 485/7485 [02:06<48:27,  2.41it/s]

  6%|▋         | 485/7485 [02:06<48:27,  2.41it/s]
  6%|▋         | 486/7485 [02:06<48:27,  2.41it/s]

  7%|▋         | 487/7485 [02:06<46:22,  2.52it/s]

  7%|▋         | 487/7485 [02:06<46:22,  2.52it/s]
  7%|▋         | 488/7485 [02:06<46:22,  2.52it/s]

  7%|▋         | 489/7485 [02:07<44:21,  2.63it/s]

  7%|▋         | 489/7485 [02:07<44:21,  2.63it/s]
  7%|▋         | 490/7485 [02:07<44:20,  2.63it/s]

  7%|▋         | 491/7485 [02:08<41:58,  2.78it/s]

  7%|▋         | 491/7485 [02:08<41:58,  2.78it/s]
  7%|▋         | 492/7485 [02:08<41:58,  2.78it/s]

  7%|▋         | 493/7485 [02:08<40:23,  2.89it/s]

  7%|▋         | 493/7485 [02:08<40:23,  2.89it/s]
  7%|▋         | 494/7485 [02:08<40:23,  2.89it/s]

  7%|▋         | 495/7485 [02:09<39:00,  2.99it/s]

  7%|▋         | 495/7485 [02:09<39:00,  2.99it/s]
  7%|▋         | 496/7485 [02:09<38:59,  2.99it/s]
  7%|▋         | 497/7485 [02:09<38:59,  2.99it/s]
  7%|▋         | 498/7485 [02:09<38:59,  2.99it/s]
  7%|▋         | 499/7485 [02:09<38:58,  2.99it/s]

  7%|▋         | 500/7485 [02:09<26:38,  4.37it/s]

  7%|▋         | 500/7485 [02:09<26:38,  4.37it/s]
  7%|▋         | 501/7485 [02:09<26:38,  4.37it/s]

  7%|▋         | 502/7485 [02:10<28:58,  4.02it/s]

  7%|▋         | 502/7485 [02:10<28:58,  4.02it/s]
  7%|▋         | 503/7485 [02:10<28:58,  4.02it/s]

  7%|▋         | 504/7485 [02:11<30:32,  3.81it/s]

  7%|▋         | 504/7485 [02:11<30:32,  3.81it/s]
  7%|▋         | 505/7485 [02:11<30:32,  3.81it/s]

  7%|▋         | 506/7485 [02:11<32:48,  3.54it/s]

  7%|▋         | 506/7485 [02:11<32:48,  3.54it/s]
  7%|▋         | 507/7485 [02:11<32:48,  3.54it/s]

  7%|▋         | 508/7485 [02:12<33:13,  3.50it/s]

  7%|▋         | 508/7485 [02:12<33:13,  3.50it/s]
  7%|▋         | 509/7485 [02:12<33:12,  3.50it/s]

  7%|▋         | 510/7485 [02:13<34:28,  3.37it/s]

  7%|▋         | 510/7485 [02:13<34:28,  3.37it/s]
  7%|▋         | 511/7485 [02:13<34:28,  3.37it/s]
  7%|▋         | 512/7485 [02:13<34:28,  3.37it/s]
  7%|▋         | 513/7485 [02:13<34:27,  3.37it/s]
  7%|▋         | 514/7485 [02:13<34:27,  3.37it/s]
  7%|▋         | 515/7485 [02:13<34:27,  3.37it/s]
  7%|▋         | 516/7485 [02:13<34:26,  3.37it/s]
  7%|▋         | 517/7485 [02:13<34:26,  3.37it/s]
  7%|▋         | 518/7485 [02:13<34:26,  3.37it/s]

  7%|▋         | 519/7485 [02:13<17:29,  6.64it/s]

  7%|▋         | 519/7485 [02:13<17:29,  6.64it/s]
  7%|▋         | 520/7485 [02:13<17:29,  6.64it/s]

  7%|▋         | 521/7485 [02:14<20:14,  5.73it/s]

  7%|▋         | 521/7485 [02:14<20:14,  5.73it/s]
  7%|▋         | 522/7485 [02:14<20:14,  5.73it/s]

  7%|▋         | 523/7485 [02:14<23:22,  4.96it/s]

  7%|▋         | 523/7485 [02:14<23:22,  4.96it/s]
  7%|▋         | 524/7485 [02:14<23:22,  4.96it/s]

  7%|▋         | 525/7485 [02:17<55:34,  2.09it/s]

  7%|▋         | 525/7485 [02:17<55:34,  2.09it/s]
  7%|▋         | 526/7485 [02:17<55:34,  2.09it/s]

  7%|▋         | 527/7485 [02:18<50:07,  2.31it/s]

  7%|▋         | 527/7485 [02:18<50:07,  2.31it/s]
  7%|▋         | 528/7485 [02:18<50:07,  2.31it/s]

  7%|▋         | 529/7485 [02:19<46:21,  2.50it/s]

  7%|▋         | 529/7485 [02:19<46:21,  2.50it/s]
  7%|▋         | 530/7485 [02:19<46:20,  2.50it/s]

  7%|▋         | 531/7485 [02:19<43:18,  2.68it/s]

  7%|▋         | 531/7485 [02:19<43:18,  2.68it/s]
  7%|▋         | 532/7485 [02:19<43:18,  2.68it/s]

  7%|▋         | 533/7485 [02:20<41:23,  2.80it/s]

  7%|▋         | 533/7485 [02:20<41:23,  2.80it/s]
  7%|▋         | 534/7485 [02:20<41:23,  2.80it/s]

  7%|▋         | 535/7485 [02:20<39:41,  2.92it/s]

  7%|▋         | 535/7485 [02:20<39:41,  2.92it/s]
  7%|▋         | 536/7485 [02:20<39:40,  2.92it/s]

  7%|▋         | 537/7485 [02:21<38:37,  3.00it/s]

  7%|▋         | 537/7485 [02:21<38:37,  3.00it/s]
  7%|▋         | 538/7485 [02:21<38:37,  3.00it/s]

  7%|▋         | 539/7485 [02:22<38:22,  3.02it/s]

  7%|▋         | 539/7485 [02:22<38:22,  3.02it/s]
  7%|▋         | 540/7485 [02:22<38:21,  3.02it/s]

  7%|▋         | 541/7485 [02:22<37:29,  3.09it/s]

  7%|▋         | 541/7485 [02:22<37:29,  3.09it/s]
  7%|▋         | 542/7485 [02:22<37:29,  3.09it/s]

  7%|▋         | 543/7485 [02:23<37:27,  3.09it/s]

  7%|▋         | 543/7485 [02:23<37:27,  3.09it/s]
  7%|▋         | 544/7485 [02:23<37:26,  3.09it/s]

  7%|▋         | 545/7485 [02:24<36:48,  3.14it/s]

  7%|▋         | 545/7485 [02:24<36:48,  3.14it/s]
  7%|▋         | 546/7485 [02:24<36:48,  3.14it/s]

  7%|▋         | 547/7485 [02:24<36:23,  3.18it/s]

  7%|▋         | 547/7485 [02:24<36:23,  3.18it/s]
  7%|▋         | 548/7485 [02:24<36:23,  3.18it/s]

  7%|▋         | 549/7485 [02:25<36:21,  3.18it/s]

  7%|▋         | 549/7485 [02:25<36:21,  3.18it/s]
  7%|▋         | 550/7485 [02:25<36:21,  3.18it/s]

  7%|▋         | 551/7485 [02:25<35:29,  3.26it/s]

  7%|▋         | 551/7485 [02:25<35:29,  3.26it/s]
  7%|▋         | 552/7485 [02:25<35:29,  3.26it/s]
  7%|▋         | 553/7485 [02:25<35:29,  3.26it/s]
  7%|▋         | 554/7485 [02:25<35:28,  3.26it/s]

  7%|▋         | 555/7485 [02:26<27:44,  4.16it/s]

  7%|▋         | 555/7485 [02:26<27:44,  4.16it/s]
  7%|▋         | 556/7485 [02:26<27:44,  4.16it/s]

  7%|▋         | 557/7485 [02:27<30:02,  3.84it/s]

  7%|▋         | 557/7485 [02:27<30:02,  3.84it/s]
  7%|▋         | 558/7485 [02:27<30:02,  3.84it/s]
  7%|▋         | 559/7485 [02:27<30:01,  3.84it/s]
  7%|▋         | 560/7485 [02:27<30:01,  3.84it/s]

  7%|▋         | 561/7485 [02:27<25:53,  4.46it/s]

  7%|▋         | 561/7485 [02:27<25:53,  4.46it/s]
  8%|▊         | 562/7485 [02:27<25:53,  4.46it/s]
  8%|▊         | 563/7485 [02:27<25:53,  4.46it/s]

  8%|▊         | 564/7485 [02:30<52:24,  2.20it/s]

  8%|▊         | 564/7485 [02:30<52:24,  2.20it/s]
  8%|▊         | 565/7485 [02:30<52:23,  2.20it/s]

  8%|▊         | 566/7485 [02:31<48:25,  2.38it/s]

  8%|▊         | 566/7485 [02:31<48:25,  2.38it/s]
  8%|▊         | 567/7485 [02:31<48:25,  2.38it/s]
  8%|▊         | 568/7485 [02:31<48:25,  2.38it/s]
  8%|▊         | 569/7485 [02:31<48:24,  2.38it/s]

  8%|▊         | 570/7485 [02:31<36:50,  3.13it/s]

  8%|▊         | 570/7485 [02:31<36:50,  3.13it/s]
  8%|▊         | 571/7485 [02:32<36:50,  3.13it/s]
  8%|▊         | 572/7485 [02:32<36:50,  3.13it/s]
  8%|▊         | 573/7485 [02:32<36:49,  3.13it/s]

  8%|▊         | 574/7485 [02:32<30:24,  3.79it/s]

  8%|▊         | 574/7485 [02:32<30:24,  3.79it/s]
  8%|▊         | 575/7485 [02:32<30:23,  3.79it/s]
  8%|▊         | 576/7485 [02:32<30:23,  3.79it/s]
  8%|▊         | 577/7485 [02:32<30:23,  3.79it/s]

  8%|▊         | 578/7485 [02:33<26:13,  4.39it/s]

  8%|▊         | 578/7485 [02:33<26:13,  4.39it/s]
  8%|▊         | 579/7485 [02:33<26:13,  4.39it/s]

  8%|▊         | 580/7485 [02:33<28:19,  4.06it/s]

  8%|▊         | 580/7485 [02:33<28:19,  4.06it/s]
  8%|▊         | 581/7485 [02:33<28:19,  4.06it/s]
  8%|▊         | 582/7485 [02:33<28:18,  4.06it/s]
  8%|▊         | 583/7485 [02:33<28:18,  4.06it/s]

  8%|▊         | 584/7485 [02:34<24:53,  4.62it/s]

  8%|▊         | 584/7485 [02:34<24:53,  4.62it/s]
  8%|▊         | 585/7485 [02:34<24:53,  4.62it/s]

  8%|▊         | 586/7485 [02:35<27:13,  4.22it/s]

  8%|▊         | 586/7485 [02:35<27:13,  4.22it/s]
  8%|▊         | 587/7485 [02:35<27:13,  4.22it/s]
  8%|▊         | 588/7485 [02:35<27:13,  4.22it/s]

  8%|▊         | 589/7485 [02:35<26:28,  4.34it/s]

  8%|▊         | 589/7485 [02:35<26:28,  4.34it/s]
  8%|▊         | 590/7485 [02:35<26:28,  4.34it/s]

  8%|▊         | 591/7485 [02:36<28:09,  4.08it/s]

  8%|▊         | 591/7485 [02:36<28:09,  4.08it/s]
  8%|▊         | 592/7485 [02:36<28:09,  4.08it/s]

  8%|▊         | 593/7485 [02:37<30:28,  3.77it/s]

  8%|▊         | 593/7485 [02:37<30:28,  3.77it/s]
  8%|▊         | 594/7485 [02:37<30:28,  3.77it/s]
  8%|▊         | 595/7485 [02:37<30:28,  3.77it/s]

  8%|▊         | 596/7485 [02:37<28:40,  4.00it/s]

  8%|▊         | 596/7485 [02:37<28:40,  4.00it/s]
  8%|▊         | 597/7485 [02:37<28:40,  4.00it/s]
  8%|▊         | 598/7485 [02:37<28:39,  4.00it/s]

  8%|▊         | 599/7485 [02:38<27:14,  4.21it/s]

  8%|▊         | 599/7485 [02:38<27:14,  4.21it/s]
  8%|▊         | 600/7485 [02:38<27:14,  4.21it/s]

  8%|▊         | 601/7485 [02:39<29:41,  3.86it/s]

  8%|▊         | 601/7485 [02:39<29:41,  3.86it/s]
  8%|▊         | 602/7485 [02:39<29:41,  3.86it/s]

  8%|▊         | 603/7485 [02:39<30:48,  3.72it/s]

  8%|▊         | 603/7485 [02:39<30:48,  3.72it/s]
  8%|▊         | 604/7485 [02:39<30:48,  3.72it/s]

  8%|▊         | 605/7485 [02:40<32:34,  3.52it/s]

  8%|▊         | 605/7485 [02:40<32:34,  3.52it/s]
  8%|▊         | 606/7485 [02:40<32:34,  3.52it/s]

  8%|▊         | 607/7485 [02:43<1:10:34,  1.62it/s]

  8%|▊         | 607/7485 [02:43<1:10:34,  1.62it/s]
  8%|▊         | 608/7485 [02:43<1:10:33,  1.62it/s]

  8%|▊         | 609/7485 [02:43<1:00:18,  1.90it/s]

  8%|▊         | 609/7485 [02:43<1:00:18,  1.90it/s]
  8%|▊         | 610/7485 [02:43<1:00:17,  1.90it/s]

  8%|▊         | 611/7485 [02:44<53:44,  2.13it/s]

  8%|▊         | 611/7485 [02:44<53:44,  2.13it/s]
  8%|▊         | 612/7485 [02:44<53:43,  2.13it/s]
  8%|▊         | 613/7485 [02:44<53:43,  2.13it/s]

  8%|▊         | 614/7485 [02:45<42:32,  2.69it/s]

  8%|▊         | 614/7485 [02:45<42:32,  2.69it/s]
  8%|▊         | 615/7485 [02:45<42:31,  2.69it/s]

  8%|▊         | 616/7485 [02:45<40:35,  2.82it/s]

  8%|▊         | 616/7485 [02:45<40:35,  2.82it/s]
  8%|▊         | 617/7485 [02:45<40:35,  2.82it/s]

  8%|▊         | 618/7485 [02:46<39:25,  2.90it/s]

  8%|▊         | 618/7485 [02:46<39:25,  2.90it/s]
  8%|▊         | 619/7485 [02:46<39:24,  2.90it/s]

  8%|▊         | 620/7485 [02:47<38:05,  3.00it/s]

  8%|▊         | 620/7485 [02:47<38:05,  3.00it/s]
  8%|▊         | 621/7485 [02:47<38:05,  3.00it/s]
  8%|▊         | 622/7485 [02:47<38:05,  3.00it/s]
  8%|▊         | 623/7485 [02:47<38:04,  3.00it/s]
  8%|▊         | 624/7485 [02:47<38:04,  3.00it/s]

  8%|▊         | 625/7485 [02:47<26:35,  4.30it/s]

  8%|▊         | 625/7485 [02:47<26:35,  4.30it/s]
  8%|▊         | 626/7485 [02:47<26:35,  4.30it/s]
  8%|▊         | 627/7485 [02:47<26:35,  4.30it/s]

  8%|▊         | 628/7485 [02:48<26:05,  4.38it/s]

  8%|▊         | 628/7485 [02:48<26:05,  4.38it/s]
  8%|▊         | 629/7485 [02:48<26:04,  4.38it/s]

  8%|▊         | 630/7485 [02:48<28:01,  4.08it/s]

  8%|▊         | 630/7485 [02:48<28:01,  4.08it/s]
  8%|▊         | 631/7485 [02:48<28:01,  4.08it/s]

  8%|▊         | 632/7485 [02:49<30:12,  3.78it/s]

  8%|▊         | 632/7485 [02:49<30:12,  3.78it/s]
  8%|▊         | 633/7485 [02:49<30:12,  3.78it/s]
  8%|▊         | 634/7485 [02:49<30:12,  3.78it/s]
  8%|▊         | 635/7485 [02:49<30:12,  3.78it/s]
  8%|▊         | 636/7485 [02:49<30:11,  3.78it/s]
  9%|▊         | 637/7485 [02:49<30:11,  3.78it/s]
  9%|▊         | 638/7485 [02:49<30:11,  3.78it/s]
  9%|▊         | 639/7485 [02:49<30:10,  3.78it/s]

  9%|▊         | 640/7485 [02:50<18:03,  6.32it/s]

  9%|▊         | 640/7485 [02:50<18:03,  6.32it/s]
  9%|▊         | 641/7485 [02:50<18:03,  6.32it/s]

  9%|▊         | 642/7485 [02:50<21:05,  5.41it/s]

  9%|▊         | 642/7485 [02:50<21:05,  5.41it/s]
  9%|▊         | 643/7485 [02:50<21:05,  5.41it/s]

  9%|▊         | 644/7485 [02:51<24:23,  4.67it/s]

  9%|▊         | 644/7485 [02:51<24:23,  4.67it/s]
  9%|▊         | 645/7485 [02:51<24:23,  4.67it/s]

  9%|▊         | 646/7485 [02:52<27:06,  4.20it/s]

  9%|▊         | 646/7485 [02:52<27:06,  4.20it/s]
  9%|▊         | 647/7485 [02:52<27:06,  4.20it/s]

  9%|▊         | 648/7485 [02:52<29:26,  3.87it/s]

  9%|▊         | 648/7485 [02:52<29:26,  3.87it/s]
  9%|▊         | 649/7485 [02:52<29:26,  3.87it/s]

  9%|▊         | 650/7485 [02:55<1:05:08,  1.75it/s]

  9%|▊         | 650/7485 [02:55<1:05:08,  1.75it/s]
  9%|▊         | 651/7485 [02:55<1:05:07,  1.75it/s]
  9%|▊         | 652/7485 [02:55<1:05:07,  1.75it/s]

  9%|▊         | 653/7485 [02:56<50:30,  2.25it/s]

  9%|▊         | 653/7485 [02:56<50:30,  2.25it/s]
  9%|▊         | 654/7485 [02:56<50:30,  2.25it/s]

  9%|▉         | 655/7485 [02:57<47:15,  2.41it/s]

  9%|▉         | 655/7485 [02:57<47:15,  2.41it/s]
  9%|▉         | 656/7485 [02:57<47:15,  2.41it/s]
  9%|▉         | 657/7485 [02:57<47:14,  2.41it/s]

  9%|▉         | 658/7485 [02:57<39:14,  2.90it/s]

  9%|▉         | 658/7485 [02:57<39:14,  2.90it/s]
  9%|▉         | 659/7485 [02:57<39:13,  2.90it/s]

  9%|▉         | 660/7485 [02:58<38:29,  2.95it/s]

  9%|▉         | 660/7485 [02:58<38:29,  2.95it/s]
  9%|▉         | 661/7485 [02:58<38:29,  2.95it/s]

  9%|▉         | 662/7485 [02:59<38:27,  2.96it/s]

  9%|▉         | 662/7485 [02:59<38:27,  2.96it/s]
  9%|▉         | 663/7485 [02:59<38:26,  2.96it/s]

  9%|▉         | 664/7485 [02:59<37:46,  3.01it/s]

  9%|▉         | 664/7485 [02:59<37:46,  3.01it/s]
  9%|▉         | 665/7485 [02:59<37:46,  3.01it/s]

  9%|▉         | 666/7485 [03:00<37:53,  3.00it/s]

  9%|▉         | 666/7485 [03:00<37:53,  3.00it/s]
  9%|▉         | 667/7485 [03:00<37:53,  3.00it/s]

  9%|▉         | 668/7485 [03:01<38:09,  2.98it/s]

  9%|▉         | 668/7485 [03:01<38:09,  2.98it/s]
  9%|▉         | 669/7485 [03:01<38:09,  2.98it/s]

  9%|▉         | 670/7485 [03:01<37:41,  3.01it/s]

  9%|▉         | 670/7485 [03:01<37:41,  3.01it/s]
  9%|▉         | 671/7485 [03:01<37:40,  3.01it/s]

  9%|▉         | 672/7485 [03:02<38:20,  2.96it/s]

  9%|▉         | 672/7485 [03:02<38:20,  2.96it/s]
  9%|▉         | 673/7485 [03:02<38:20,  2.96it/s]

  9%|▉         | 674/7485 [03:03<38:34,  2.94it/s]

  9%|▉         | 674/7485 [03:03<38:34,  2.94it/s]
  9%|▉         | 675/7485 [03:03<38:34,  2.94it/s]

  9%|▉         | 676/7485 [03:03<37:38,  3.02it/s]

  9%|▉         | 676/7485 [03:03<37:38,  3.02it/s]
  9%|▉         | 677/7485 [03:03<37:37,  3.02it/s]

  9%|▉         | 678/7485 [03:04<37:54,  2.99it/s]

  9%|▉         | 678/7485 [03:04<37:54,  2.99it/s]
  9%|▉         | 679/7485 [03:04<37:54,  2.99it/s]
  9%|▉         | 680/7485 [03:04<37:54,  2.99it/s]
  9%|▉         | 681/7485 [03:04<37:53,  2.99it/s]

  9%|▉         | 682/7485 [03:05<28:24,  3.99it/s]

  9%|▉         | 682/7485 [03:05<28:24,  3.99it/s]
  9%|▉         | 683/7485 [03:05<28:24,  3.99it/s]

  9%|▉         | 684/7485 [03:05<30:23,  3.73it/s]

  9%|▉         | 684/7485 [03:05<30:23,  3.73it/s]
  9%|▉         | 685/7485 [03:05<30:23,  3.73it/s]

  9%|▉         | 686/7485 [03:08<1:05:37,  1.73it/s]

  9%|▉         | 686/7485 [03:08<1:05:37,  1.73it/s]
  9%|▉         | 687/7485 [03:08<1:05:36,  1.73it/s]

  9%|▉         | 688/7485 [03:09<57:04,  1.99it/s]

  9%|▉         | 688/7485 [03:09<57:04,  1.99it/s]
  9%|▉         | 689/7485 [03:09<57:03,  1.99it/s]

  9%|▉         | 690/7485 [03:09<51:07,  2.22it/s]

  9%|▉         | 690/7485 [03:09<51:07,  2.22it/s]
  9%|▉         | 691/7485 [03:09<51:07,  2.22it/s]
  9%|▉         | 692/7485 [03:09<51:06,  2.22it/s]

  9%|▉         | 693/7485 [03:10<41:01,  2.76it/s]

  9%|▉         | 693/7485 [03:10<41:01,  2.76it/s]
  9%|▉         | 694/7485 [03:10<41:01,  2.76it/s]
  9%|▉         | 695/7485 [03:10<41:00,  2.76it/s]

  9%|▉         | 696/7485 [03:11<34:38,  3.27it/s]

  9%|▉         | 696/7485 [03:11<34:38,  3.27it/s]
  9%|▉         | 697/7485 [03:11<34:37,  3.27it/s]

  9%|▉         | 698/7485 [03:11<35:46,  3.16it/s]

  9%|▉         | 698/7485 [03:11<35:46,  3.16it/s]
  9%|▉         | 699/7485 [03:11<35:46,  3.16it/s]

  9%|▉         | 700/7485 [03:12<35:51,  3.15it/s]

  9%|▉         | 700/7485 [03:12<35:51,  3.15it/s]
  9%|▉         | 701/7485 [03:12<35:50,  3.15it/s]
  9%|▉         | 702/7485 [03:12<35:50,  3.15it/s]

  9%|▉         | 703/7485 [03:13<32:12,  3.51it/s]

  9%|▉         | 703/7485 [03:13<32:12,  3.51it/s]
  9%|▉         | 704/7485 [03:13<32:11,  3.51it/s]

  9%|▉         | 705/7485 [03:13<33:20,  3.39it/s]

  9%|▉         | 705/7485 [03:13<33:20,  3.39it/s]
  9%|▉         | 706/7485 [03:13<33:20,  3.39it/s]

  9%|▉         | 707/7485 [03:14<34:06,  3.31it/s]

  9%|▉         | 707/7485 [03:14<34:06,  3.31it/s]
  9%|▉         | 708/7485 [03:14<34:06,  3.31it/s]

  9%|▉         | 709/7485 [03:15<34:42,  3.25it/s]

  9%|▉         | 709/7485 [03:15<34:42,  3.25it/s]
  9%|▉         | 710/7485 [03:15<34:41,  3.25it/s]

  9%|▉         | 711/7485 [03:15<35:21,  3.19it/s]

  9%|▉         | 711/7485 [03:15<35:21,  3.19it/s]
 10%|▉         | 712/7485 [03:15<35:20,  3.19it/s]
 10%|▉         | 713/7485 [03:15<35:20,  3.19it/s]
 10%|▉         | 714/7485 [03:15<35:20,  3.19it/s]
 10%|▉         | 715/7485 [03:15<35:19,  3.19it/s]

 10%|▉         | 716/7485 [03:16<24:42,  4.57it/s]

 10%|▉         | 716/7485 [03:16<24:42,  4.57it/s]
 10%|▉         | 717/7485 [03:16<24:42,  4.57it/s]

 10%|▉         | 718/7485 [03:16<27:46,  4.06it/s]

 10%|▉         | 718/7485 [03:16<27:46,  4.06it/s]
 10%|▉         | 719/7485 [03:16<27:46,  4.06it/s]

 10%|▉         | 720/7485 [03:17<29:31,  3.82it/s]

 10%|▉         | 720/7485 [03:17<29:31,  3.82it/s]
 10%|▉         | 721/7485 [03:17<29:31,  3.82it/s]

 10%|▉         | 722/7485 [03:18<31:34,  3.57it/s]

 10%|▉         | 722/7485 [03:18<31:34,  3.57it/s]
 10%|▉         | 723/7485 [03:18<31:34,  3.57it/s]

 10%|▉         | 724/7485 [03:21<1:07:06,  1.68it/s]

 10%|▉         | 724/7485 [03:21<1:07:06,  1.68it/s]
 10%|▉         | 725/7485 [03:21<1:07:05,  1.68it/s]

 10%|▉         | 726/7485 [03:21<58:10,  1.94it/s]

 10%|▉         | 726/7485 [03:21<58:10,  1.94it/s]
 10%|▉         | 727/7485 [03:21<58:10,  1.94it/s]

 10%|▉         | 728/7485 [03:22<52:08,  2.16it/s]

 10%|▉         | 728/7485 [03:22<52:08,  2.16it/s]
 10%|▉         | 729/7485 [03:22<52:08,  2.16it/s]
 10%|▉         | 730/7485 [03:22<52:07,  2.16it/s]
 10%|▉         | 731/7485 [03:22<52:07,  2.16it/s]

 10%|▉         | 732/7485 [03:23<37:19,  3.01it/s]

 10%|▉         | 732/7485 [03:23<37:19,  3.01it/s]
 10%|▉         | 733/7485 [03:23<37:19,  3.01it/s]
 10%|▉         | 734/7485 [03:23<37:19,  3.01it/s]

 10%|▉         | 735/7485 [03:23<32:58,  3.41it/s]

 10%|▉         | 735/7485 [03:23<32:58,  3.41it/s]
 10%|▉         | 736/7485 [03:23<32:58,  3.41it/s]
 10%|▉         | 737/7485 [03:23<32:57,  3.41it/s]

 10%|▉         | 738/7485 [03:24<30:30,  3.69it/s]
 10%|█         | 752/7485 [03:24<10:20, 10.85it/s]

 10%|▉         | 738/7485 [03:24<30:30,  3.69it/s]
 10%|▉         | 739/7485 [03:24<30:30,  3.69it/s]
 10%|▉         | 740/7485 [03:24<30:29,  3.69it/s]
 10%|▉         | 741/7485 [03:24<30:29,  3.69it/s]
 10%|▉         | 742/7485 [03:24<30:29,  3.69it/s]
 10%|▉         | 743/7485 [03:24<30:29,  3.69it/s]
 10%|▉         | 744/7485 [03:24<30:28,  3.69it/s]
 10%|▉         | 745/7485 [03:24<30:28,  3.69it/s]
 10%|▉         | 746/7485 [03:24<30:28,  3.69it/s]
 10%|▉         | 747/7485 [03:24<30:27,  3.69it/s]
 10%|▉         | 748/7485 [03:24<30:27,  3.69it/s]
 10%|█         | 749/7485 [03:24<30:27,  3.69it/s]
 10%|█         | 750/7485 [03:24<30:27,  3.69it/s]
 10%|█         | 751/7485 [03:24<30:26,  3.69it/s]
 10%|█         | 752/7485 [03:24<10:20, 10.85it/s]
 10%|█         | 753/7485 [03:24<10:20, 10.85it/s]
 10%|█         | 754/7485 [03:24<10:20, 10.85it/s]
 10%|█         | 755/7485 [03:24<10:20, 10.85it/s]
 10%|█         | 756/7485 [03:24<10:20, 10.85it/s]
 10%|█         | 757/7485 [03:24<10:20, 10.85it/s]
 10%|█         | 758/7485 [03:24<10:19, 10.85it/s]
 10%|█         | 759/7485 [03:24<10:19, 10.85it/s]
 10%|█         | 760/7485 [03:24<10:19, 10.85it/s]
 10%|█         | 761/7485 [03:24<10:19, 10.85it/s]

 10%|█         | 762/7485 [03:25<09:18, 12.04it/s]

 10%|█         | 762/7485 [03:25<09:18, 12.04it/s]
 10%|█         | 763/7485 [03:25<09:18, 12.04it/s]
 10%|█         | 764/7485 [03:25<09:18, 12.04it/s]
 10%|█         | 765/7485 [03:25<09:18, 12.04it/s]
 10%|█         | 766/7485 [03:25<09:18, 12.04it/s]
 10%|█         | 767/7485 [03:25<09:18, 12.04it/s]
 10%|█         | 768/7485 [03:25<09:18, 12.04it/s]
 10%|█         | 769/7485 [03:25<09:18, 12.04it/s]
 10%|█         | 770/7485 [03:25<09:17, 12.04it/s]
 10%|█         | 771/7485 [03:25<09:17, 12.04it/s]

 10%|█         | 772/7485 [03:25<08:36, 13.00it/s]

 10%|█         | 772/7485 [03:25<08:36, 13.00it/s]
 10%|█         | 773/7485 [03:25<08:36, 13.00it/s]
 10%|█         | 774/7485 [03:25<08:36, 13.00it/s]

 10%|█         | 775/7485 [03:26<10:58, 10.19it/s]

 10%|█         | 775/7485 [03:26<10:58, 10.19it/s]
 10%|█         | 776/7485 [03:26<10:58, 10.19it/s]

 10%|█         | 778/7485 [03:27<13:17,  8.41it/s]

 10%|█         | 777/7485 [03:27<10:58, 10.19it/s]
 10%|█         | 778/7485 [03:27<13:17,  8.41it/s]

 10%|█         | 780/7485 [03:27<16:23,  6.82it/s]

 10%|█         | 779/7485 [03:27<13:17,  8.41it/s]
 10%|█         | 780/7485 [03:27<16:23,  6.82it/s]

 10%|█         | 782/7485 [03:28<19:52,  5.62it/s]

 10%|█         | 781/7485 [03:28<16:23,  6.82it/s]
 10%|█         | 782/7485 [03:28<19:52,  5.62it/s]

 10%|█         | 783/7485 [03:29<25:57,  4.30it/s]

 10%|█         | 783/7485 [03:29<25:57,  4.30it/s]
 10%|█         | 784/7485 [03:29<25:56,  4.30it/s]

 10%|█         | 785/7485 [03:29<28:27,  3.92it/s]

 10%|█         | 785/7485 [03:29<28:27,  3.92it/s]
 11%|█         | 786/7485 [03:29<28:27,  3.92it/s]

 11%|█         | 787/7485 [03:30<30:58,  3.60it/s]

 11%|█         | 787/7485 [03:30<30:58,  3.60it/s]
 11%|█         | 788/7485 [03:30<30:57,  3.60it/s]

 11%|█         | 789/7485 [03:33<1:05:51,  1.69it/s]

 11%|█         | 789/7485 [03:33<1:05:51,  1.69it/s]
 11%|█         | 790/7485 [03:33<1:05:51,  1.69it/s]
 11%|█         | 791/7485 [03:33<1:05:50,  1.69it/s]
 11%|█         | 792/7485 [03:33<1:05:50,  1.69it/s]

 11%|█         | 793/7485 [03:34<45:46,  2.44it/s]

 11%|█         | 793/7485 [03:34<45:46,  2.44it/s]
 11%|█         | 794/7485 [03:34<45:46,  2.44it/s]

 11%|█         | 795/7485 [03:35<44:15,  2.52it/s]

 11%|█         | 795/7485 [03:35<44:15,  2.52it/s]
 11%|█         | 796/7485 [03:35<44:14,  2.52it/s]

 11%|█         | 797/7485 [03:35<42:59,  2.59it/s]

 11%|█         | 797/7485 [03:35<42:59,  2.59it/s]
 11%|█         | 798/7485 [03:35<42:58,  2.59it/s]

 11%|█         | 799/7485 [03:36<41:48,  2.67it/s]

 11%|█         | 799/7485 [03:36<41:48,  2.67it/s]
 11%|█         | 800/7485 [03:36<41:48,  2.67it/s]

 11%|█         | 801/7485 [03:37<41:11,  2.70it/s]

 11%|█         | 801/7485 [03:37<41:11,  2.70it/s]
 11%|█         | 802/7485 [03:37<41:10,  2.70it/s]
 11%|█         | 803/7485 [03:37<41:10,  2.70it/s]

 11%|█         | 804/7485 [03:37<35:57,  3.10it/s]

 11%|█         | 804/7485 [03:37<35:57,  3.10it/s]
 11%|█         | 805/7485 [03:37<35:56,  3.10it/s]
 11%|█         | 806/7485 [03:37<35:56,  3.10it/s]

 11%|█         | 807/7485 [03:38<32:35,  3.41it/s]

 11%|█         | 807/7485 [03:38<32:35,  3.41it/s]
 11%|█         | 808/7485 [03:38<32:35,  3.41it/s]

 11%|█         | 809/7485 [03:39<34:58,  3.18it/s]

 11%|█         | 809/7485 [03:39<34:58,  3.18it/s]
 11%|█         | 810/7485 [03:39<34:58,  3.18it/s]

 11%|█         | 811/7485 [03:40<36:30,  3.05it/s]

 11%|█         | 811/7485 [03:40<36:30,  3.05it/s]
 11%|█         | 812/7485 [03:40<36:30,  3.05it/s]

 11%|█         | 813/7485 [03:40<37:36,  2.96it/s]

 11%|█         | 813/7485 [03:40<37:36,  2.96it/s]
 11%|█         | 814/7485 [03:40<37:36,  2.96it/s]

 11%|█         | 815/7485 [03:41<38:25,  2.89it/s]

 11%|█         | 815/7485 [03:41<38:25,  2.89it/s]
 11%|█         | 816/7485 [03:41<38:25,  2.89it/s]

 11%|█         | 817/7485 [03:42<39:44,  2.80it/s]

 11%|█         | 817/7485 [03:42<39:44,  2.80it/s]
 11%|█         | 818/7485 [03:42<39:43,  2.80it/s]

 11%|█         | 819/7485 [03:43<40:01,  2.78it/s]

 11%|█         | 819/7485 [03:43<40:01,  2.78it/s]
 11%|█         | 820/7485 [03:43<40:00,  2.78it/s]

 11%|█         | 821/7485 [03:43<43:00,  2.58it/s]

 11%|█         | 821/7485 [03:43<43:00,  2.58it/s]
 11%|█         | 822/7485 [03:43<43:00,  2.58it/s]

 11%|█         | 823/7485 [03:46<1:15:28,  1.47it/s]

 11%|█         | 823/7485 [03:46<1:15:28,  1.47it/s]
 11%|█         | 824/7485 [03:46<1:15:27,  1.47it/s]

 11%|█         | 825/7485 [03:47<1:04:51,  1.71it/s]

 11%|█         | 825/7485 [03:47<1:04:51,  1.71it/s]
 11%|█         | 826/7485 [03:47<1:04:51,  1.71it/s]

 11%|█         | 827/7485 [03:48<56:48,  1.95it/s]

 11%|█         | 827/7485 [03:48<56:48,  1.95it/s]
 11%|█         | 828/7485 [03:48<56:47,  1.95it/s]

 11%|█         | 829/7485 [03:48<52:13,  2.12it/s]

 11%|█         | 829/7485 [03:48<52:13,  2.12it/s]
 11%|█         | 830/7485 [03:48<52:13,  2.12it/s]

 11%|█         | 831/7485 [03:49<48:38,  2.28it/s]

 11%|█         | 831/7485 [03:49<48:38,  2.28it/s]
 11%|█         | 832/7485 [03:49<48:38,  2.28it/s]

 11%|█         | 833/7485 [03:50<45:07,  2.46it/s]

 11%|█         | 833/7485 [03:50<45:07,  2.46it/s]
 11%|█         | 834/7485 [03:50<45:06,  2.46it/s]

 11%|█         | 835/7485 [03:50<42:52,  2.58it/s]

 11%|█         | 835/7485 [03:50<42:52,  2.58it/s]
 11%|█         | 836/7485 [03:50<42:52,  2.58it/s]

 11%|█         | 837/7485 [03:51<41:44,  2.65it/s]

 11%|█         | 837/7485 [03:51<41:44,  2.65it/s]
 11%|█         | 838/7485 [03:51<41:44,  2.65it/s]

 11%|█         | 839/7485 [03:52<40:38,  2.73it/s]

 11%|█         | 839/7485 [03:52<40:38,  2.73it/s]
 11%|█         | 840/7485 [03:52<40:38,  2.73it/s]
 11%|█         | 841/7485 [03:52<40:38,  2.73it/s]

 11%|█         | 842/7485 [03:52<34:17,  3.23it/s]

 11%|█         | 842/7485 [03:52<34:17,  3.23it/s]
 11%|█▏        | 843/7485 [03:52<34:17,  3.23it/s]

 11%|█▏        | 844/7485 [03:53<34:56,  3.17it/s]

 11%|█▏        | 844/7485 [03:53<34:56,  3.17it/s]
 11%|█▏        | 845/7485 [03:53<34:56,  3.17it/s]

 11%|█▏        | 846/7485 [03:54<34:49,  3.18it/s]

 11%|█▏        | 846/7485 [03:54<34:49,  3.18it/s]
 11%|█▏        | 847/7485 [03:54<34:48,  3.18it/s]

 11%|█▏        | 848/7485 [03:54<35:18,  3.13it/s]

 11%|█▏        | 848/7485 [03:54<35:18,  3.13it/s]
 11%|█▏        | 849/7485 [03:54<35:18,  3.13it/s]

 11%|█▏        | 850/7485 [03:55<35:22,  3.13it/s]

 11%|█▏        | 850/7485 [03:55<35:22,  3.13it/s]
 11%|█▏        | 851/7485 [03:55<35:22,  3.13it/s]

 11%|█▏        | 852/7485 [03:56<35:17,  3.13it/s]

 11%|█▏        | 852/7485 [03:56<35:17,  3.13it/s]
 11%|█▏        | 853/7485 [03:56<35:16,  3.13it/s]

 11%|█▏        | 854/7485 [03:59<1:12:48,  1.52it/s]

 11%|█▏        | 854/7485 [03:59<1:12:48,  1.52it/s]
 11%|█▏        | 855/7485 [03:59<1:12:47,  1.52it/s]

 11%|█▏        | 856/7485 [03:59<1:01:18,  1.80it/s]

 11%|█▏        | 856/7485 [03:59<1:01:18,  1.80it/s]
 11%|█▏        | 857/7485 [03:59<1:01:18,  1.80it/s]

 11%|█▏        | 858/7485 [04:00<53:57,  2.05it/s]

 11%|█▏        | 858/7485 [04:00<53:57,  2.05it/s]
 11%|█▏        | 859/7485 [04:00<53:57,  2.05it/s]
 11%|█▏        | 860/7485 [04:00<53:56,  2.05it/s]

 12%|█▏        | 861/7485 [04:01<42:08,  2.62it/s]

 12%|█▏        | 861/7485 [04:01<42:08,  2.62it/s]
 12%|█▏        | 862/7485 [04:01<42:08,  2.62it/s]
 12%|█▏        | 863/7485 [04:01<42:07,  2.62it/s]
 12%|█▏        | 864/7485 [04:01<42:07,  2.62it/s]

 12%|█▏        | 865/7485 [04:01<31:42,  3.48it/s]

 12%|█▏        | 865/7485 [04:01<31:42,  3.48it/s]
 12%|█▏        | 866/7485 [04:01<31:42,  3.48it/s]

 12%|█▏        | 867/7485 [04:02<32:48,  3.36it/s]

 12%|█▏        | 867/7485 [04:02<32:48,  3.36it/s]
 12%|█▏        | 868/7485 [04:02<32:47,  3.36it/s]

 12%|█▏        | 869/7485 [04:03<33:37,  3.28it/s]

 12%|█▏        | 869/7485 [04:03<33:37,  3.28it/s]
 12%|█▏        | 870/7485 [04:03<33:36,  3.28it/s]

 12%|█▏        | 871/7485 [04:03<33:55,  3.25it/s]

 12%|█▏        | 871/7485 [04:03<33:55,  3.25it/s]
 12%|█▏        | 872/7485 [04:03<33:55,  3.25it/s]

 12%|█▏        | 873/7485 [04:04<34:37,  3.18it/s]

 12%|█▏        | 873/7485 [04:04<34:37,  3.18it/s]
 12%|█▏        | 874/7485 [04:04<34:37,  3.18it/s]

 12%|█▏        | 875/7485 [04:04<34:44,  3.17it/s]

 12%|█▏        | 875/7485 [04:04<34:44,  3.17it/s]
 12%|█▏        | 876/7485 [04:04<34:43,  3.17it/s]

 12%|█▏        | 877/7485 [04:05<35:57,  3.06it/s]

 12%|█▏        | 877/7485 [04:05<35:57,  3.06it/s]
 12%|█▏        | 878/7485 [04:05<35:56,  3.06it/s]

 12%|█▏        | 879/7485 [04:06<36:23,  3.03it/s]

 12%|█▏        | 879/7485 [04:06<36:23,  3.03it/s]
 12%|█▏        | 880/7485 [04:06<36:23,  3.03it/s]

 12%|█▏        | 881/7485 [04:06<36:21,  3.03it/s]

 12%|█▏        | 881/7485 [04:06<36:21,  3.03it/s]
 12%|█▏        | 882/7485 [04:07<36:20,  3.03it/s]

 12%|█▏        | 883/7485 [04:07<36:32,  3.01it/s]

 12%|█▏        | 883/7485 [04:07<36:32,  3.01it/s]
 12%|█▏        | 884/7485 [04:07<36:32,  3.01it/s]

 12%|█▏        | 885/7485 [04:08<36:45,  2.99it/s]

 12%|█▏        | 885/7485 [04:08<36:45,  2.99it/s]
 12%|█▏        | 886/7485 [04:08<36:45,  2.99it/s]

 12%|█▏        | 887/7485 [04:09<39:42,  2.77it/s]

 12%|█▏        | 887/7485 [04:09<39:42,  2.77it/s]
 12%|█▏        | 888/7485 [04:09<39:42,  2.77it/s]

 12%|█▏        | 889/7485 [04:11<1:13:44,  1.49it/s]

 12%|█▏        | 889/7485 [04:11<1:13:44,  1.49it/s]
 12%|█▏        | 890/7485 [04:12<1:13:44,  1.49it/s]

 12%|█▏        | 891/7485 [04:12<1:02:43,  1.75it/s]

 12%|█▏        | 891/7485 [04:12<1:02:43,  1.75it/s]
 12%|█▏        | 892/7485 [04:12<1:02:42,  1.75it/s]

 12%|█▏        | 893/7485 [04:13<54:33,  2.01it/s]

 12%|█▏        | 893/7485 [04:13<54:33,  2.01it/s]
 12%|█▏        | 894/7485 [04:13<54:32,  2.01it/s]

 12%|█▏        | 895/7485 [04:13<49:00,  2.24it/s]

 12%|█▏        | 895/7485 [04:13<49:00,  2.24it/s]
 12%|█▏        | 896/7485 [04:13<48:59,  2.24it/s]

 12%|█▏        | 897/7485 [04:14<45:38,  2.41it/s]

 12%|█▏        | 897/7485 [04:14<45:38,  2.41it/s]
 12%|█▏        | 898/7485 [04:14<45:38,  2.41it/s]

 12%|█▏        | 899/7485 [04:15<42:40,  2.57it/s]

 12%|█▏        | 899/7485 [04:15<42:40,  2.57it/s]
 12%|█▏        | 900/7485 [04:15<42:40,  2.57it/s]

 12%|█▏        | 901/7485 [04:15<40:56,  2.68it/s]

 12%|█▏        | 901/7485 [04:15<40:56,  2.68it/s]
 12%|█▏        | 902/7485 [04:15<40:55,  2.68it/s]

 12%|█▏        | 903/7485 [04:16<39:54,  2.75it/s]

 12%|█▏        | 903/7485 [04:16<39:54,  2.75it/s]
 12%|█▏        | 904/7485 [04:16<39:53,  2.75it/s]

 12%|█▏        | 905/7485 [04:17<38:32,  2.85it/s]

 12%|█▏        | 905/7485 [04:17<38:32,  2.85it/s]
 12%|█▏        | 906/7485 [04:17<38:31,  2.85it/s]

 12%|█▏        | 907/7485 [04:17<37:59,  2.89it/s]

 12%|█▏        | 907/7485 [04:17<37:59,  2.89it/s]
 12%|█▏        | 908/7485 [04:17<37:58,  2.89it/s]

 12%|█▏        | 909/7485 [04:18<37:04,  2.96it/s]

 12%|█▏        | 909/7485 [04:18<37:04,  2.96it/s]
 12%|█▏        | 910/7485 [04:18<37:03,  2.96it/s]

 12%|█▏        | 911/7485 [04:19<37:23,  2.93it/s]

 12%|█▏        | 911/7485 [04:19<37:23,  2.93it/s]
 12%|█▏        | 912/7485 [04:19<37:23,  2.93it/s]

 12%|█▏        | 913/7485 [04:19<37:20,  2.93it/s]

 12%|█▏        | 913/7485 [04:19<37:20,  2.93it/s]
 12%|█▏        | 914/7485 [04:19<37:20,  2.93it/s]
 12%|█▏        | 915/7485 [04:19<37:20,  2.93it/s]

 12%|█▏        | 916/7485 [04:20<32:01,  3.42it/s]

 12%|█▏        | 916/7485 [04:20<32:01,  3.42it/s]
 12%|█▏        | 917/7485 [04:20<32:00,  3.42it/s]
 12%|█▏        | 918/7485 [04:20<32:00,  3.42it/s]

 12%|█▏        | 919/7485 [04:21<29:19,  3.73it/s]

 12%|█▏        | 919/7485 [04:21<29:19,  3.73it/s]
 12%|█▏        | 920/7485 [04:21<29:19,  3.73it/s]

 12%|█▏        | 921/7485 [04:24<1:02:37,  1.75it/s]

 12%|█▏        | 921/7485 [04:24<1:02:37,  1.75it/s]
 12%|█▏        | 922/7485 [04:24<1:02:36,  1.75it/s]

 12%|█▏        | 923/7485 [04:24<55:11,  1.98it/s]

 12%|█▏        | 923/7485 [04:24<55:11,  1.98it/s]
 12%|█▏        | 924/7485 [04:24<55:10,  1.98it/s]

 12%|█▏        | 925/7485 [04:25<50:15,  2.18it/s]

 12%|█▏        | 925/7485 [04:25<50:15,  2.18it/s]
 12%|█▏        | 926/7485 [04:25<50:15,  2.18it/s]

 12%|█▏        | 927/7485 [04:26<46:55,  2.33it/s]

 12%|█▏        | 927/7485 [04:26<46:55,  2.33it/s]
 12%|█▏        | 928/7485 [04:26<46:55,  2.33it/s]
 12%|█▏        | 929/7485 [04:26<46:54,  2.33it/s]

 12%|█▏        | 930/7485 [04:26<38:27,  2.84it/s]

 12%|█▏        | 930/7485 [04:26<38:27,  2.84it/s]
 12%|█▏        | 931/7485 [04:26<38:27,  2.84it/s]

 12%|█▏        | 932/7485 [04:27<37:58,  2.88it/s]

 12%|█▏        | 932/7485 [04:27<37:58,  2.88it/s]
 12%|█▏        | 933/7485 [04:27<37:58,  2.88it/s]

 12%|█▏        | 934/7485 [04:28<37:56,  2.88it/s]

 12%|█▏        | 934/7485 [04:28<37:56,  2.88it/s]
 12%|█▏        | 935/7485 [04:28<37:56,  2.88it/s]

 13%|█▎        | 936/7485 [04:28<37:23,  2.92it/s]

 13%|█▎        | 936/7485 [04:28<37:23,  2.92it/s]
 13%|█▎        | 937/7485 [04:28<37:23,  2.92it/s]

 13%|█▎        | 938/7485 [04:29<38:00,  2.87it/s]

 13%|█▎        | 938/7485 [04:29<38:00,  2.87it/s]
 13%|█▎        | 939/7485 [04:29<38:00,  2.87it/s]

 13%|█▎        | 940/7485 [04:30<37:56,  2.88it/s]

 13%|█▎        | 940/7485 [04:30<37:56,  2.88it/s]
 13%|█▎        | 941/7485 [04:30<37:55,  2.88it/s]
 13%|█▎        | 942/7485 [04:30<37:55,  2.88it/s]

 13%|█▎        | 943/7485 [04:31<32:49,  3.32it/s]

 13%|█▎        | 943/7485 [04:31<32:49,  3.32it/s]
 13%|█▎        | 944/7485 [04:31<32:49,  3.32it/s]

 13%|█▎        | 945/7485 [04:31<33:59,  3.21it/s]

 13%|█▎        | 945/7485 [04:31<33:59,  3.21it/s]
 13%|█▎        | 946/7485 [04:31<33:59,  3.21it/s]

 13%|█▎        | 947/7485 [04:32<35:03,  3.11it/s]

 13%|█▎        | 947/7485 [04:32<35:03,  3.11it/s]
 13%|█▎        | 948/7485 [04:32<35:03,  3.11it/s]
 13%|█▎        | 949/7485 [04:32<35:03,  3.11it/s]
 13%|█▎        | 950/7485 [04:32<35:02,  3.11it/s]
 13%|█▎        | 951/7485 [04:32<35:02,  3.11it/s]

 13%|█▎        | 952/7485 [04:33<24:50,  4.38it/s]

 13%|█▎        | 952/7485 [04:33<24:50,  4.38it/s]
 13%|█▎        | 953/7485 [04:33<24:50,  4.38it/s]

 13%|█▎        | 954/7485 [04:33<27:10,  4.00it/s]

 13%|█▎        | 954/7485 [04:33<27:10,  4.00it/s]
 13%|█▎        | 955/7485 [04:33<27:10,  4.00it/s]

 13%|█▎        | 956/7485 [04:36<59:21,  1.83it/s]

 13%|█▎        | 956/7485 [04:36<59:21,  1.83it/s]
 13%|█▎        | 957/7485 [04:36<59:20,  1.83it/s]

 13%|█▎        | 958/7485 [04:37<53:19,  2.04it/s]

 13%|█▎        | 958/7485 [04:37<53:19,  2.04it/s]
 13%|█▎        | 959/7485 [04:37<53:18,  2.04it/s]

 13%|█▎        | 960/7485 [04:38<48:48,  2.23it/s]

 13%|█▎        | 960/7485 [04:38<48:48,  2.23it/s]
 13%|█▎        | 961/7485 [04:38<48:48,  2.23it/s]

 13%|█▎        | 962/7485 [04:38<45:26,  2.39it/s]

 13%|█▎        | 962/7485 [04:38<45:26,  2.39it/s]
 13%|█▎        | 963/7485 [04:38<45:26,  2.39it/s]

 13%|█▎        | 964/7485 [04:39<43:02,  2.53it/s]

 13%|█▎        | 964/7485 [04:39<43:02,  2.53it/s]
 13%|█▎        | 965/7485 [04:39<43:01,  2.53it/s]
 13%|█▎        | 966/7485 [04:39<43:01,  2.53it/s]

 13%|█▎        | 967/7485 [04:40<36:31,  2.97it/s]

 13%|█▎        | 967/7485 [04:40<36:31,  2.97it/s]
 13%|█▎        | 968/7485 [04:40<36:30,  2.97it/s]

 13%|█▎        | 969/7485 [04:40<36:35,  2.97it/s]

 13%|█▎        | 969/7485 [04:40<36:35,  2.97it/s]
 13%|█▎        | 970/7485 [04:40<36:35,  2.97it/s]
 13%|█▎        | 971/7485 [04:40<36:34,  2.97it/s]

 13%|█▎        | 972/7485 [04:41<32:22,  3.35it/s]

 13%|█▎        | 972/7485 [04:41<32:22,  3.35it/s]
 13%|█▎        | 973/7485 [04:41<32:21,  3.35it/s]

 13%|█▎        | 974/7485 [04:42<34:47,  3.12it/s]

 13%|█▎        | 974/7485 [04:42<34:47,  3.12it/s]
 13%|█▎        | 975/7485 [04:42<34:46,  3.12it/s]
 13%|█▎        | 976/7485 [04:42<34:46,  3.12it/s]

 13%|█▎        | 977/7485 [04:42<31:19,  3.46it/s]

 13%|█▎        | 977/7485 [04:42<31:19,  3.46it/s]
 13%|█▎        | 978/7485 [04:42<31:18,  3.46it/s]

 13%|█▎        | 979/7485 [04:43<32:04,  3.38it/s]

 13%|█▎        | 979/7485 [04:43<32:04,  3.38it/s]
 13%|█▎        | 980/7485 [04:43<32:04,  3.38it/s]
 13%|█▎        | 981/7485 [04:43<32:04,  3.38it/s]
 13%|█▎        | 982/7485 [04:43<32:03,  3.38it/s]
 13%|█▎        | 983/7485 [04:43<32:03,  3.38it/s]
 13%|█▎        | 984/7485 [04:43<32:03,  3.38it/s]
 13%|█▎        | 985/7485 [04:43<32:02,  3.38it/s]
 13%|█▎        | 986/7485 [04:43<32:02,  3.38it/s]
 13%|█▎        | 987/7485 [04:43<32:02,  3.38it/s]
 13%|█▎        | 988/7485 [04:43<32:01,  3.38it/s]
 13%|█▎        | 989/7485 [04:43<32:01,  3.38it/s]

 13%|█▎        | 990/7485 [04:44<16:07,  6.72it/s]

 13%|█▎        | 990/7485 [04:44<16:07,  6.72it/s]
 13%|█▎        | 991/7485 [04:44<16:06,  6.72it/s]

 13%|█▎        | 1000/7485 [04:45<30:49,  3.51it/s]
 56%|█████▌    | 5/9 [23:21<18:55, 283.91s/it]

 13%|█▎        | 992/7485 [04:45<19:03,  5.68it/s]
 13%|█▎        | 993/7485 [04:45<19:03,  5.68it/s]
 13%|█▎        | 994/7485 [04:45<19:03,  5.68it/s]
 13%|█▎        | 995/7485 [04:45<19:02,  5.68it/s]
 13%|█▎        | 996/7485 [04:45<19:02,  5.68it/s]
 13%|█▎        | 997/7485 [04:45<19:02,  5.68it/s]
 13%|█▎        | 998/7485 [04:45<19:02,  5.68it/s]
 13%|█▎        | 999/7485 [04:45<19:02,  5.68it/s]
 13%|█▎        | 1000/7485 [04:45<19:02,  5.68it/s]
                     MLUT4_AT.232A  MLUT4_RQ.2BTLS  MLUT4_TE.252A  \
Time
2025-05-25 05:20:05       0.852984        0.855904       0.842414
2025-05-25 05:30:05       0.876511        0.874611       0.847393
2025-05-25 05:35:05       0.877479        0.885625       0.860507
2025-05-25 05:40:05       0.878625        0.849563       0.860377
2025-05-25 05:45:05       0.877141        0.871733       0.849503

                     MLUT4_SIV.B7921  MLUT4_AIA792101B  MLUT4_PDT.956  \
Time
2025-05-25 05:20:05         0.903258          0.872434       0.899219
2025-05-25 05:30:05         0.903158          0.872244       0.916372
2025-05-25 05:35:05         0.903349          0.872158       0.914016
2025-05-25 05:40:05         0.903300          0.872148       0.910043
2025-05-25 05:45:05         0.903219          0.872148       0.914286

                     MLUT4_TE.252F  MLUT4_PT.231  MLUT4_FIC.231C  \
Time
2025-05-25 05:20:05       0.887579      0.869354        0.857897
2025-05-25 05:30:05       0.879727      0.867235        0.857888
2025-05-25 05:35:05       0.893944      0.867041        0.857883
2025-05-25 05:40:05       0.872940      0.866275        0.857879
2025-05-25 05:45:05       0.876962      0.865383        0.857874

                     MLUT4_FIC.231A  ...  DeSOx_2nd  MLUT4_AIC.232B  \
Time                                 ...
2025-05-25 05:20:05        0.859975  ...   0.882902       85.012138
2025-05-25 05:30:05        0.856716  ...   0.882444       88.954571
2025-05-25 05:35:05        0.860662  ...   0.882319       93.745851
2025-05-25 05:40:05        0.859286  ...   0.883341       85.305571
2025-05-25 05:45:05        0.859582  ...   0.883465      101.874866

                     MLUT4_AT.240  prev_target  MLUT4_AT-240  prediction  \
Time
2025-05-25 05:20:05     14.151761     0.888806      9.954719    0.883104
2025-05-25 05:30:05      9.316637     0.890104     10.457175    0.881844
2025-05-25 05:35:05      6.155893     0.890862     11.032122    0.881643
2025-05-25 05:40:05     12.572007     0.891577      9.951674    0.882737
2025-05-25 05:45:05      5.497275     0.891864     11.872017    0.881863

                     abs_error  threshold  y3_prediction  y3_abs_error
Time
2025-05-25 05:20:05   0.000202   0.000202       9.937582      0.017137
2025-05-25 05:30:05   0.000600   0.000560      10.510544      0.053369
2025-05-25 05:35:05   0.000676   0.000676      11.095461      0.063339
2025-05-25 05:40:05   0.000604   0.000668      10.003168      0.051494
2025-05-25 05:45:05   0.001602   0.001417      12.035191      0.163175

[5 rows x 50 columns]

  0%|          | 0/7483 [00:00<?, ?it/s]

  0%|          | 0/7483 [00:00<?, ?it/s]

  0%|          | 1/7483 [00:00<1:13:14,  1.70it/s]

  0%|          | 1/7483 [00:00<1:13:14,  1.70it/s]
  0%|          | 2/7483 [00:00<1:13:13,  1.70it/s]
  0%|          | 3/7483 [00:00<1:13:12,  1.70it/s]
  0%|          | 4/7483 [00:00<1:13:12,  1.70it/s]
  0%|          | 5/7483 [00:00<1:13:11,  1.70it/s]

  0%|          | 6/7483 [00:01<22:21,  5.57it/s]

  0%|          | 6/7483 [00:01<22:21,  5.57it/s]
  0%|          | 7/7483 [00:01<22:21,  5.57it/s]

  0%|          | 8/7483 [00:01<26:44,  4.66it/s]

  0%|          | 8/7483 [00:01<26:44,  4.66it/s]
  0%|          | 9/7483 [00:01<26:44,  4.66it/s]

  0%|          | 10/7483 [00:02<29:58,  4.15it/s]

  0%|          | 10/7483 [00:02<29:58,  4.15it/s]
  0%|          | 11/7483 [00:02<29:58,  4.15it/s]
  0%|          | 12/7483 [00:02<29:58,  4.15it/s]
  0%|          | 13/7483 [00:02<29:57,  4.15it/s]
  0%|          | 14/7483 [00:02<29:57,  4.15it/s]

  0%|          | 15/7483 [00:02<21:33,  5.77it/s]

  0%|          | 15/7483 [00:02<21:33,  5.77it/s]
  0%|          | 16/7483 [00:02<21:33,  5.77it/s]

  0%|          | 17/7483 [00:03<24:37,  5.05it/s]

  0%|          | 17/7483 [00:03<24:37,  5.05it/s]
  0%|          | 18/7483 [00:03<24:37,  5.05it/s]

  0%|          | 19/7483 [00:04<27:37,  4.50it/s]

  0%|          | 19/7483 [00:04<27:37,  4.50it/s]
  0%|          | 20/7483 [00:04<27:37,  4.50it/s]

  0%|          | 21/7483 [00:04<29:34,  4.20it/s]

  0%|          | 21/7483 [00:04<29:34,  4.20it/s]
  0%|          | 22/7483 [00:04<29:34,  4.20it/s]

  0%|          | 23/7483 [00:05<31:37,  3.93it/s]

  0%|          | 23/7483 [00:05<31:37,  3.93it/s]
  0%|          | 24/7483 [00:05<31:36,  3.93it/s]

  0%|          | 25/7483 [00:05<32:58,  3.77it/s]

  0%|          | 25/7483 [00:05<32:58,  3.77it/s]
  0%|          | 26/7483 [00:05<32:58,  3.77it/s]

  0%|          | 27/7483 [00:06<34:04,  3.65it/s]

  0%|          | 27/7483 [00:06<34:04,  3.65it/s]
  0%|          | 28/7483 [00:06<34:04,  3.65it/s]

  0%|          | 29/7483 [00:06<34:05,  3.64it/s]

  0%|          | 29/7483 [00:06<34:05,  3.64it/s]
  0%|          | 30/7483 [00:07<34:04,  3.64it/s]

  0%|          | 31/7483 [00:07<35:09,  3.53it/s]

  0%|          | 31/7483 [00:07<35:09,  3.53it/s]
  0%|          | 32/7483 [00:07<35:09,  3.53it/s]

  0%|          | 33/7483 [00:08<36:06,  3.44it/s]
  1%|          | 42/7483 [00:08<13:21,  9.29it/s]

  0%|          | 33/7483 [00:08<36:06,  3.44it/s]
  0%|          | 34/7483 [00:08<36:06,  3.44it/s]
  0%|          | 35/7483 [00:08<36:06,  3.44it/s]
  0%|          | 36/7483 [00:08<36:06,  3.44it/s]
  0%|          | 37/7483 [00:08<36:05,  3.44it/s]
  1%|          | 38/7483 [00:08<36:05,  3.44it/s]
  1%|          | 39/7483 [00:08<36:05,  3.44it/s]
  1%|          | 40/7483 [00:08<36:04,  3.44it/s]
  1%|          | 41/7483 [00:08<36:04,  3.44it/s]
  1%|          | 42/7483 [00:08<13:21,  9.29it/s]
  1%|          | 43/7483 [00:08<13:20,  9.29it/s]
  1%|          | 44/7483 [00:08<13:20,  9.29it/s]

  1%|          | 45/7483 [00:10<36:03,  3.44it/s]

  1%|          | 45/7483 [00:10<36:03,  3.44it/s]
  1%|          | 46/7483 [00:10<36:02,  3.44it/s]
  1%|          | 47/7483 [00:10<36:02,  3.44it/s]

  1%|          | 48/7483 [00:12<41:11,  3.01it/s]

  1%|          | 48/7483 [00:12<41:11,  3.01it/s]
  1%|          | 49/7483 [00:12<41:10,  3.01it/s]

  1%|          | 50/7483 [00:12<40:26,  3.06it/s]

  1%|          | 50/7483 [00:12<40:26,  3.06it/s]
  1%|          | 51/7483 [00:12<40:26,  3.06it/s]

  1%|          | 52/7483 [00:13<39:55,  3.10it/s]

  1%|          | 52/7483 [00:13<39:55,  3.10it/s]
  1%|          | 53/7483 [00:13<39:55,  3.10it/s]
  1%|          | 54/7483 [00:13<39:55,  3.10it/s]

  1%|          | 55/7483 [00:14<34:38,  3.57it/s]

  1%|          | 55/7483 [00:14<34:38,  3.57it/s]
  1%|          | 56/7483 [00:14<34:38,  3.57it/s]
  1%|          | 57/7483 [00:14<34:37,  3.57it/s]
  1%|          | 58/7483 [00:14<34:37,  3.57it/s]

  1%|          | 59/7483 [00:14<28:32,  4.33it/s]

  1%|          | 59/7483 [00:14<28:32,  4.33it/s]
  1%|          | 60/7483 [00:14<28:32,  4.33it/s]

  1%|          | 61/7483 [00:15<29:57,  4.13it/s]

  1%|          | 61/7483 [00:15<29:57,  4.13it/s]
  1%|          | 62/7483 [00:15<29:57,  4.13it/s]

  1%|          | 63/7483 [00:15<31:40,  3.90it/s]

  1%|          | 63/7483 [00:15<31:40,  3.90it/s]
  1%|          | 64/7483 [00:15<31:40,  3.90it/s]

  1%|          | 65/7483 [00:16<32:34,  3.80it/s]

  1%|          | 65/7483 [00:16<32:34,  3.80it/s]
  1%|          | 66/7483 [00:16<32:33,  3.80it/s]

  1%|          | 67/7483 [00:17<33:40,  3.67it/s]

  1%|          | 67/7483 [00:17<33:40,  3.67it/s]
  1%|          | 68/7483 [00:17<33:40,  3.67it/s]

  1%|          | 69/7483 [00:17<34:51,  3.54it/s]

  1%|          | 69/7483 [00:17<34:51,  3.54it/s]
  1%|          | 70/7483 [00:17<34:51,  3.54it/s]

  1%|          | 71/7483 [00:18<35:09,  3.51it/s]

  1%|          | 71/7483 [00:18<35:09,  3.51it/s]
  1%|          | 72/7483 [00:18<35:09,  3.51it/s]
  1%|          | 73/7483 [00:18<35:09,  3.51it/s]
  1%|          | 74/7483 [00:18<35:09,  3.51it/s]
  1%|          | 75/7483 [00:18<35:08,  3.51it/s]
  1%|          | 76/7483 [00:18<35:08,  3.51it/s]
  1%|          | 77/7483 [00:18<35:08,  3.51it/s]
  1%|          | 78/7483 [00:18<35:07,  3.51it/s]

  1%|          | 79/7483 [00:18<19:49,  6.23it/s]

  1%|          | 79/7483 [00:18<19:49,  6.23it/s]
  1%|          | 80/7483 [00:18<19:48,  6.23it/s]

  1%|          | 81/7483 [00:19<22:59,  5.37it/s]

  1%|          | 81/7483 [00:19<22:59,  5.37it/s]
  1%|          | 82/7483 [00:19<22:58,  5.37it/s]

  1%|          | 83/7483 [00:20<26:41,  4.62it/s]

  1%|          | 83/7483 [00:20<26:41,  4.62it/s]
  1%|          | 84/7483 [00:20<26:41,  4.62it/s]
  1%|          | 85/7483 [00:20<26:41,  4.62it/s]

  1%|          | 86/7483 [00:20<27:19,  4.51it/s]

  1%|          | 86/7483 [00:20<27:19,  4.51it/s]
  1%|          | 87/7483 [00:20<27:19,  4.51it/s]
  1%|          | 88/7483 [00:20<27:18,  4.51it/s]

  1%|          | 89/7483 [00:21<27:02,  4.56it/s]

  1%|          | 89/7483 [00:21<27:02,  4.56it/s]
  1%|          | 90/7483 [00:21<27:01,  4.56it/s]

  1%|          | 91/7483 [00:24<1:02:02,  1.99it/s]

  1%|          | 91/7483 [00:24<1:02:02,  1.99it/s]
  1%|          | 92/7483 [00:24<1:02:02,  1.99it/s]

  1%|          | 93/7483 [00:25<57:36,  2.14it/s]

  1%|          | 93/7483 [00:25<57:36,  2.14it/s]
  1%|▏         | 94/7483 [00:25<57:35,  2.14it/s]

  1%|▏         | 95/7483 [00:25<53:48,  2.29it/s]

  1%|▏         | 95/7483 [00:25<53:48,  2.29it/s]
  1%|▏         | 96/7483 [00:25<53:48,  2.29it/s]

  1%|▏         | 97/7483 [00:26<50:51,  2.42it/s]

  1%|▏         | 97/7483 [00:26<50:51,  2.42it/s]
  1%|▏         | 98/7483 [00:26<50:50,  2.42it/s]

  1%|▏         | 99/7483 [00:27<48:41,  2.53it/s]
  1%|▏         | 108/7483 [00:27<18:22,  6.69it/s]

  1%|▏         | 99/7483 [00:27<48:41,  2.53it/s]
  1%|▏         | 100/7483 [00:27<48:41,  2.53it/s]
  1%|▏         | 101/7483 [00:27<48:41,  2.53it/s]
  1%|▏         | 102/7483 [00:27<48:40,  2.53it/s]
  1%|▏         | 103/7483 [00:27<48:40,  2.53it/s]
  1%|▏         | 104/7483 [00:27<48:39,  2.53it/s]
  1%|▏         | 105/7483 [00:27<48:39,  2.53it/s]
  1%|▏         | 106/7483 [00:27<48:39,  2.53it/s]
  1%|▏         | 107/7483 [00:27<48:38,  2.53it/s]
  1%|▏         | 108/7483 [00:27<18:22,  6.69it/s]
  1%|▏         | 109/7483 [00:27<18:22,  6.69it/s]

  1%|▏         | 111/7483 [00:28<20:18,  6.05it/s]

  1%|▏         | 110/7483 [00:28<18:21,  6.69it/s]
  1%|▏         | 111/7483 [00:28<20:18,  6.05it/s]
  1%|▏         | 112/7483 [00:28<20:18,  6.05it/s]

  2%|▏         | 114/7483 [00:28<22:12,  5.53it/s]

  2%|▏         | 113/7483 [00:28<20:18,  6.05it/s]
  2%|▏         | 114/7483 [00:28<22:12,  5.53it/s]

  2%|▏         | 116/7483 [00:29<25:55,  4.73it/s]

  2%|▏         | 115/7483 [00:29<22:11,  5.53it/s]
  2%|▏         | 116/7483 [00:29<25:55,  4.73it/s]

  2%|▏         | 118/7483 [00:30<29:14,  4.20it/s]

  2%|▏         | 117/7483 [00:30<25:55,  4.73it/s]
  2%|▏         | 118/7483 [00:30<29:14,  4.20it/s]

  2%|▏         | 119/7483 [00:30<36:38,  3.35it/s]

  2%|▏         | 119/7483 [00:30<36:38,  3.35it/s]
  2%|▏         | 120/7483 [00:30<36:38,  3.35it/s]

  2%|▏         | 121/7483 [00:31<38:16,  3.21it/s]

  2%|▏         | 121/7483 [00:31<38:16,  3.21it/s]
  2%|▏         | 122/7483 [00:31<38:15,  3.21it/s]

  2%|▏         | 123/7483 [00:32<38:55,  3.15it/s]

  2%|▏         | 123/7483 [00:32<38:55,  3.15it/s]
  2%|▏         | 124/7483 [00:32<38:54,  3.15it/s]

  2%|▏         | 125/7483 [00:32<40:10,  3.05it/s]

  2%|▏         | 125/7483 [00:32<40:10,  3.05it/s]
  2%|▏         | 126/7483 [00:32<40:10,  3.05it/s]
  2%|▏         | 127/7483 [00:32<40:10,  3.05it/s]
  2%|▏         | 128/7483 [00:32<40:09,  3.05it/s]

  2%|▏         | 129/7483 [00:33<31:15,  3.92it/s]

  2%|▏         | 129/7483 [00:33<31:15,  3.92it/s]
  2%|▏         | 130/7483 [00:33<31:15,  3.92it/s]

  2%|▏         | 131/7483 [00:34<33:06,  3.70it/s]

  2%|▏         | 131/7483 [00:34<33:06,  3.70it/s]
  2%|▏         | 132/7483 [00:34<33:05,  3.70it/s]

  2%|▏         | 133/7483 [00:37<1:11:13,  1.72it/s]

  2%|▏         | 133/7483 [00:37<1:11:13,  1.72it/s]
  2%|▏         | 134/7483 [00:37<1:11:12,  1.72it/s]
  2%|▏         | 135/7483 [00:37<1:11:12,  1.72it/s]
  2%|▏         | 136/7483 [00:37<1:11:11,  1.72it/s]
  2%|▏         | 137/7483 [00:37<1:11:11,  1.72it/s]
  2%|▏         | 138/7483 [00:37<1:11:10,  1.72it/s]
  2%|▏         | 139/7483 [00:37<1:11:10,  1.72it/s]
  2%|▏         | 140/7483 [00:37<1:11:09,  1.72it/s]

  2%|▏         | 141/7483 [00:37<34:51,  3.51it/s]

  2%|▏         | 141/7483 [00:37<34:51,  3.51it/s]
  2%|▏         | 142/7483 [00:37<34:51,  3.51it/s]
  2%|▏         | 143/7483 [00:37<34:51,  3.51it/s]

  2%|▏         | 144/7483 [00:38<32:25,  3.77it/s]

  2%|▏         | 144/7483 [00:38<32:25,  3.77it/s]
  2%|▏         | 145/7483 [00:38<32:25,  3.77it/s]

  2%|▏         | 146/7483 [00:39<33:51,  3.61it/s]

  2%|▏         | 146/7483 [00:39<33:51,  3.61it/s]
  2%|▏         | 147/7483 [00:39<33:51,  3.61it/s]

  2%|▏         | 148/7483 [00:39<35:25,  3.45it/s]

  2%|▏         | 148/7483 [00:39<35:25,  3.45it/s]
  2%|▏         | 149/7483 [00:39<35:25,  3.45it/s]
  2%|▏         | 150/7483 [00:39<35:24,  3.45it/s]
  2%|▏         | 151/7483 [00:39<35:24,  3.45it/s]
  2%|▏         | 152/7483 [00:39<35:24,  3.45it/s]
  2%|▏         | 153/7483 [00:39<35:23,  3.45it/s]
  2%|▏         | 154/7483 [00:39<35:23,  3.45it/s]
  2%|▏         | 155/7483 [00:39<35:23,  3.45it/s]
  2%|▏         | 156/7483 [00:39<35:23,  3.45it/s]
  2%|▏         | 157/7483 [00:39<35:22,  3.45it/s]
  2%|▏         | 158/7483 [00:39<35:22,  3.45it/s]
  2%|▏         | 159/7483 [00:39<35:22,  3.45it/s]

  2%|▏         | 160/7483 [00:40<16:45,  7.28it/s]

  2%|▏         | 160/7483 [00:40<16:45,  7.28it/s]
  2%|▏         | 161/7483 [00:40<16:45,  7.28it/s]

  2%|▏         | 162/7483 [00:40<19:52,  6.14it/s]

  2%|▏         | 162/7483 [00:40<19:52,  6.14it/s]
  2%|▏         | 163/7483 [00:41<19:52,  6.14it/s]

  2%|▏         | 164/7483 [00:41<23:01,  5.30it/s]

  2%|▏         | 164/7483 [00:41<23:01,  5.30it/s]
  2%|▏         | 165/7483 [00:41<23:01,  5.30it/s]

  2%|▏         | 166/7483 [00:42<26:24,  4.62it/s]

  2%|▏         | 166/7483 [00:42<26:24,  4.62it/s]
  2%|▏         | 167/7483 [00:42<26:24,  4.62it/s]

  2%|▏         | 168/7483 [00:42<29:24,  4.15it/s]

  2%|▏         | 168/7483 [00:42<29:24,  4.15it/s]
  2%|▏         | 169/7483 [00:42<29:23,  4.15it/s]

  2%|▏         | 170/7483 [00:43<31:45,  3.84it/s]
  2%|▏         | 181/7483 [00:43<11:59, 10.15it/s]

  2%|▏         | 170/7483 [00:43<31:45,  3.84it/s]
  2%|▏         | 171/7483 [00:43<31:45,  3.84it/s]
  2%|▏         | 172/7483 [00:43<31:44,  3.84it/s]
  2%|▏         | 173/7483 [00:43<31:44,  3.84it/s]
  2%|▏         | 174/7483 [00:43<31:44,  3.84it/s]
  2%|▏         | 175/7483 [00:43<31:44,  3.84it/s]
  2%|▏         | 176/7483 [00:43<31:43,  3.84it/s]
  2%|▏         | 177/7483 [00:43<31:43,  3.84it/s]
  2%|▏         | 178/7483 [00:43<31:43,  3.84it/s]
  2%|▏         | 179/7483 [00:43<31:43,  3.84it/s]
  2%|▏         | 180/7483 [00:43<31:42,  3.84it/s]
  2%|▏         | 181/7483 [00:43<11:59, 10.15it/s]
  2%|▏         | 182/7483 [00:43<11:59, 10.15it/s]
  2%|▏         | 183/7483 [00:43<11:59, 10.15it/s]
  2%|▏         | 184/7483 [00:43<11:59, 10.15it/s]
  2%|▏         | 185/7483 [00:43<11:59, 10.15it/s]

  2%|▏         | 186/7483 [00:43<09:18, 13.08it/s]
  3%|▎         | 194/7483 [00:43<06:14, 19.46it/s]

  2%|▏         | 186/7483 [00:43<09:18, 13.08it/s]
  2%|▏         | 187/7483 [00:43<09:17, 13.08it/s]
  3%|▎         | 188/7483 [00:43<09:17, 13.08it/s]
  3%|▎         | 189/7483 [00:43<09:17, 13.08it/s]
  3%|▎         | 190/7483 [00:43<09:17, 13.08it/s]
  3%|▎         | 191/7483 [00:43<09:17, 13.08it/s]
  3%|▎         | 192/7483 [00:43<09:17, 13.08it/s]
  3%|▎         | 193/7483 [00:43<09:17, 13.08it/s]
  3%|▎         | 194/7483 [00:43<06:14, 19.46it/s]
  3%|▎         | 195/7483 [00:43<06:14, 19.46it/s]
  3%|▎         | 196/7483 [00:44<06:14, 19.46it/s]
  3%|▎         | 197/7483 [00:44<06:14, 19.46it/s]

  3%|▎         | 199/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 210/7483 [00:44<03:29, 34.79it/s]

  3%|▎         | 198/7483 [00:44<06:14, 19.46it/s]
  3%|▎         | 199/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 200/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 201/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 202/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 203/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 204/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 205/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 206/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 207/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 208/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 209/7483 [00:44<05:19, 22.79it/s]
  3%|▎         | 210/7483 [00:44<03:29, 34.79it/s]
  3%|▎         | 211/7483 [00:44<03:29, 34.79it/s]
  3%|▎         | 212/7483 [00:44<03:29, 34.79it/s]
  3%|▎         | 213/7483 [00:44<03:28, 34.79it/s]
  3%|▎         | 214/7483 [00:44<03:28, 34.79it/s]
  3%|▎         | 215/7483 [00:44<03:28, 34.79it/s]
  3%|▎         | 216/7483 [00:44<03:28, 34.79it/s]

  3%|▎         | 217/7483 [00:44<06:19, 19.15it/s]

  3%|▎         | 217/7483 [00:44<06:19, 19.15it/s]
  3%|▎         | 218/7483 [00:44<06:19, 19.15it/s]
  3%|▎         | 219/7483 [00:45<06:19, 19.15it/s]
  3%|▎         | 220/7483 [00:45<06:19, 19.15it/s]

  3%|▎         | 222/7483 [00:46<12:16,  9.85it/s]

  3%|▎         | 221/7483 [00:46<06:19, 19.15it/s]
  3%|▎         | 222/7483 [00:46<12:16,  9.85it/s]
  3%|▎         | 223/7483 [00:47<12:16,  9.85it/s]
  3%|▎         | 224/7483 [00:47<12:16,  9.85it/s]
  3%|▎         | 225/7483 [00:47<12:16,  9.85it/s]

  3%|▎         | 226/7483 [00:49<32:22,  3.74it/s]

  3%|▎         | 226/7483 [00:49<32:22,  3.74it/s]
  3%|▎         | 227/7483 [00:49<32:22,  3.74it/s]
  3%|▎         | 228/7483 [00:49<32:21,  3.74it/s]
  3%|▎         | 229/7483 [00:49<32:21,  3.74it/s]
  3%|▎         | 230/7483 [00:49<32:21,  3.74it/s]
  3%|▎         | 231/7483 [00:49<32:21,  3.74it/s]

  3%|▎         | 232/7483 [00:50<26:51,  4.50it/s]

  3%|▎         | 232/7483 [00:50<26:51,  4.50it/s]
  3%|▎         | 233/7483 [00:50<26:51,  4.50it/s]

  3%|▎         | 234/7483 [00:51<29:06,  4.15it/s]

  3%|▎         | 234/7483 [00:51<29:06,  4.15it/s]
  3%|▎         | 235/7483 [00:51<29:05,  4.15it/s]

  3%|▎         | 236/7483 [00:52<31:35,  3.82it/s]

  3%|▎         | 236/7483 [00:52<31:35,  3.82it/s]
  3%|▎         | 237/7483 [00:52<31:35,  3.82it/s]

  3%|▎         | 238/7483 [00:52<33:43,  3.58it/s]

  3%|▎         | 238/7483 [00:52<33:43,  3.58it/s]
  3%|▎         | 239/7483 [00:52<33:43,  3.58it/s]
  3%|▎         | 240/7483 [00:52<33:42,  3.58it/s]

  3%|▎         | 241/7483 [00:53<32:30,  3.71it/s]

  3%|▎         | 241/7483 [00:53<32:30,  3.71it/s]
  3%|▎         | 242/7483 [00:53<32:30,  3.71it/s]

  3%|▎         | 243/7483 [00:54<34:41,  3.48it/s]

  3%|▎         | 243/7483 [00:54<34:41,  3.48it/s]
  3%|▎         | 244/7483 [00:54<34:40,  3.48it/s]

  3%|▎         | 245/7483 [00:55<37:06,  3.25it/s]

  3%|▎         | 245/7483 [00:55<37:06,  3.25it/s]
  3%|▎         | 246/7483 [00:55<37:06,  3.25it/s]
  3%|▎         | 247/7483 [00:55<37:06,  3.25it/s]
  3%|▎         | 248/7483 [00:55<37:05,  3.25it/s]
  3%|▎         | 249/7483 [00:55<37:05,  3.25it/s]

  3%|▎         | 250/7483 [00:55<28:19,  4.26it/s]

  3%|▎         | 250/7483 [00:55<28:19,  4.26it/s]
  3%|▎         | 251/7483 [00:55<28:19,  4.26it/s]

  3%|▎         | 252/7483 [00:56<30:53,  3.90it/s]

  3%|▎         | 252/7483 [00:56<30:53,  3.90it/s]
  3%|▎         | 253/7483 [00:56<30:53,  3.90it/s]

  3%|▎         | 254/7483 [00:57<33:09,  3.63it/s]

  3%|▎         | 254/7483 [00:57<33:09,  3.63it/s]
  3%|▎         | 255/7483 [00:57<33:09,  3.63it/s]
  3%|▎         | 256/7483 [00:57<33:09,  3.63it/s]

  3%|▎         | 257/7483 [00:57<31:24,  3.83it/s]

  3%|▎         | 257/7483 [00:57<31:24,  3.83it/s]
  3%|▎         | 258/7483 [00:57<31:24,  3.83it/s]

  3%|▎         | 259/7483 [00:58<33:33,  3.59it/s]

  3%|▎         | 259/7483 [00:58<33:33,  3.59it/s]
  3%|▎         | 260/7483 [00:58<33:33,  3.59it/s]

  3%|▎         | 261/7483 [00:59<35:31,  3.39it/s]

  3%|▎         | 261/7483 [00:59<35:31,  3.39it/s]
  4%|▎         | 262/7483 [00:59<35:31,  3.39it/s]

  4%|▎         | 263/7483 [01:01<1:10:06,  1.72it/s]

  4%|▎         | 263/7483 [01:01<1:10:06,  1.72it/s]
  4%|▎         | 264/7483 [01:01<1:10:05,  1.72it/s]

  4%|▎         | 265/7483 [01:02<1:04:22,  1.87it/s]

  4%|▎         | 265/7483 [01:02<1:04:22,  1.87it/s]
  4%|▎         | 266/7483 [01:02<1:04:21,  1.87it/s]

  4%|▎         | 267/7483 [01:03<57:48,  2.08it/s]

  4%|▎         | 267/7483 [01:03<57:48,  2.08it/s]
  4%|▎         | 268/7483 [01:03<57:47,  2.08it/s]

  4%|▎         | 269/7483 [01:04<54:19,  2.21it/s]

  4%|▎         | 269/7483 [01:04<54:19,  2.21it/s]
  4%|▎         | 270/7483 [01:04<54:19,  2.21it/s]

  4%|▎         | 271/7483 [01:04<49:56,  2.41it/s]

  4%|▎         | 271/7483 [01:04<49:56,  2.41it/s]
  4%|▎         | 272/7483 [01:04<49:56,  2.41it/s]

  4%|▎         | 273/7483 [01:05<47:30,  2.53it/s]

  4%|▎         | 273/7483 [01:05<47:30,  2.53it/s]
  4%|▎         | 274/7483 [01:05<47:30,  2.53it/s]

  4%|▎         | 275/7483 [01:06<46:27,  2.59it/s]

  4%|▎         | 275/7483 [01:06<46:27,  2.59it/s]
  4%|▎         | 276/7483 [01:06<46:26,  2.59it/s]

  4%|▎         | 277/7483 [01:06<44:32,  2.70it/s]

  4%|▎         | 277/7483 [01:06<44:32,  2.70it/s]
  4%|▎         | 278/7483 [01:06<44:31,  2.70it/s]

  4%|▎         | 279/7483 [01:07<44:26,  2.70it/s]

  4%|▎         | 279/7483 [01:07<44:26,  2.70it/s]
  4%|▎         | 280/7483 [01:07<44:25,  2.70it/s]

  4%|▍         | 281/7483 [01:08<44:35,  2.69it/s]

  4%|▍         | 281/7483 [01:08<44:35,  2.69it/s]
  4%|▍         | 282/7483 [01:08<44:35,  2.69it/s]

  4%|▍         | 283/7483 [01:09<44:41,  2.68it/s]

  4%|▍         | 283/7483 [01:09<44:41,  2.68it/s]
  4%|▍         | 284/7483 [01:09<44:41,  2.68it/s]
  4%|▍         | 285/7483 [01:09<44:41,  2.68it/s]

  4%|▍         | 286/7483 [01:09<38:04,  3.15it/s]

  4%|▍         | 286/7483 [01:09<38:04,  3.15it/s]
  4%|▍         | 287/7483 [01:09<38:04,  3.15it/s]

  4%|▍         | 288/7483 [01:10<39:29,  3.04it/s]

  4%|▍         | 288/7483 [01:10<39:29,  3.04it/s]
  4%|▍         | 289/7483 [01:10<39:29,  3.04it/s]

  4%|▍         | 290/7483 [01:11<40:53,  2.93it/s]

  4%|▍         | 290/7483 [01:11<40:53,  2.93it/s]
  4%|▍         | 291/7483 [01:11<40:53,  2.93it/s]

  4%|▍         | 292/7483 [01:12<41:28,  2.89it/s]

  4%|▍         | 292/7483 [01:12<41:28,  2.89it/s]
  4%|▍         | 293/7483 [01:12<41:28,  2.89it/s]
  4%|▍         | 294/7483 [01:12<41:28,  2.89it/s]
  4%|▍         | 295/7483 [01:12<41:27,  2.89it/s]

  4%|▍         | 296/7483 [01:14<1:02:37,  1.91it/s]

  4%|▍         | 296/7483 [01:14<1:02:37,  1.91it/s]
  4%|▍         | 297/7483 [01:15<1:02:37,  1.91it/s]

  4%|▍         | 298/7483 [01:15<57:54,  2.07it/s]

  4%|▍         | 298/7483 [01:15<57:54,  2.07it/s]
  4%|▍         | 299/7483 [01:15<57:53,  2.07it/s]
  4%|▍         | 300/7483 [01:15<57:53,  2.07it/s]
  4%|▍         | 301/7483 [01:15<57:52,  2.07it/s]

  4%|▍         | 302/7483 [01:16<42:38,  2.81it/s]

  4%|▍         | 302/7483 [01:16<42:38,  2.81it/s]
  4%|▍         | 303/7483 [01:16<42:38,  2.81it/s]

  4%|▍         | 304/7483 [01:17<42:29,  2.82it/s]

  4%|▍         | 304/7483 [01:17<42:29,  2.82it/s]
  4%|▍         | 305/7483 [01:17<42:29,  2.82it/s]

  4%|▍         | 306/7483 [01:17<42:08,  2.84it/s]

  4%|▍         | 306/7483 [01:17<42:08,  2.84it/s]
  4%|▍         | 307/7483 [01:17<42:07,  2.84it/s]

  4%|▍         | 308/7483 [01:18<41:27,  2.88it/s]

  4%|▍         | 308/7483 [01:18<41:27,  2.88it/s]
  4%|▍         | 309/7483 [01:18<41:26,  2.88it/s]

  4%|▍         | 310/7483 [01:19<41:30,  2.88it/s]

  4%|▍         | 310/7483 [01:19<41:30,  2.88it/s]
  4%|▍         | 311/7483 [01:19<41:30,  2.88it/s]

  4%|▍         | 312/7483 [01:19<41:27,  2.88it/s]

  4%|▍         | 312/7483 [01:19<41:27,  2.88it/s]
  4%|▍         | 313/7483 [01:19<41:27,  2.88it/s]

  4%|▍         | 314/7483 [01:20<40:25,  2.96it/s]

  4%|▍         | 314/7483 [01:20<40:25,  2.96it/s]
  4%|▍         | 315/7483 [01:20<40:24,  2.96it/s]

  4%|▍         | 316/7483 [01:21<40:27,  2.95it/s]

  4%|▍         | 316/7483 [01:21<40:27,  2.95it/s]
  4%|▍         | 317/7483 [01:21<40:27,  2.95it/s]
  4%|▍         | 318/7483 [01:21<40:26,  2.95it/s]
  4%|▍         | 319/7483 [01:21<40:26,  2.95it/s]

  4%|▍         | 320/7483 [01:21<31:50,  3.75it/s]

  4%|▍         | 320/7483 [01:21<31:50,  3.75it/s]
  4%|▍         | 321/7483 [01:21<31:49,  3.75it/s]

  4%|▍         | 322/7483 [01:22<33:44,  3.54it/s]

  4%|▍         | 322/7483 [01:22<33:44,  3.54it/s]
  4%|▍         | 323/7483 [01:22<33:44,  3.54it/s]

  4%|▍         | 324/7483 [01:23<35:25,  3.37it/s]

  4%|▍         | 324/7483 [01:23<35:25,  3.37it/s]
  4%|▍         | 325/7483 [01:23<35:24,  3.37it/s]
  4%|▍         | 326/7483 [01:23<35:24,  3.37it/s]

  4%|▍         | 327/7483 [01:23<32:20,  3.69it/s]

  4%|▍         | 327/7483 [01:23<32:20,  3.69it/s]
  4%|▍         | 328/7483 [01:23<32:20,  3.69it/s]

  4%|▍         | 329/7483 [01:24<33:45,  3.53it/s]

  4%|▍         | 329/7483 [01:24<33:45,  3.53it/s]
  4%|▍         | 330/7483 [01:24<33:44,  3.53it/s]

  4%|▍         | 331/7483 [01:27<1:12:18,  1.65it/s]

  4%|▍         | 331/7483 [01:27<1:12:18,  1.65it/s]
  4%|▍         | 332/7483 [01:27<1:12:17,  1.65it/s]

  4%|▍         | 333/7483 [01:28<1:03:17,  1.88it/s]

  4%|▍         | 333/7483 [01:28<1:03:17,  1.88it/s]
  4%|▍         | 334/7483 [01:28<1:03:16,  1.88it/s]

  4%|▍         | 335/7483 [01:28<56:05,  2.12it/s]

  4%|▍         | 335/7483 [01:28<56:05,  2.12it/s]
  4%|▍         | 336/7483 [01:28<56:05,  2.12it/s]

  5%|▍         | 337/7483 [01:29<51:14,  2.32it/s]

  5%|▍         | 337/7483 [01:29<51:14,  2.32it/s]
  5%|▍         | 338/7483 [01:29<51:14,  2.32it/s]

  5%|▍         | 339/7483 [01:30<47:46,  2.49it/s]

  5%|▍         | 339/7483 [01:30<47:46,  2.49it/s]
  5%|▍         | 340/7483 [01:30<47:46,  2.49it/s]

  5%|▍         | 341/7483 [01:30<44:53,  2.65it/s]

  5%|▍         | 341/7483 [01:30<44:53,  2.65it/s]
  5%|▍         | 342/7483 [01:30<44:53,  2.65it/s]

  5%|▍         | 343/7483 [01:31<43:52,  2.71it/s]

  5%|▍         | 343/7483 [01:31<43:52,  2.71it/s]
  5%|▍         | 344/7483 [01:31<43:51,  2.71it/s]

  5%|▍         | 345/7483 [01:32<42:37,  2.79it/s]

  5%|▍         | 345/7483 [01:32<42:37,  2.79it/s]
  5%|▍         | 346/7483 [01:32<42:36,  2.79it/s]

  5%|▍         | 347/7483 [01:32<42:12,  2.82it/s]

  5%|▍         | 347/7483 [01:32<42:12,  2.82it/s]
  5%|▍         | 348/7483 [01:32<42:11,  2.82it/s]

  5%|▍         | 349/7483 [01:33<42:24,  2.80it/s]

  5%|▍         | 349/7483 [01:33<42:24,  2.80it/s]
  5%|▍         | 350/7483 [01:33<42:24,  2.80it/s]

  5%|▍         | 351/7483 [01:34<42:09,  2.82it/s]

  5%|▍         | 351/7483 [01:34<42:09,  2.82it/s]
  5%|▍         | 352/7483 [01:34<42:09,  2.82it/s]

  5%|▍         | 353/7483 [01:34<41:52,  2.84it/s]

  5%|▍         | 353/7483 [01:34<41:52,  2.84it/s]
  5%|▍         | 354/7483 [01:34<41:52,  2.84it/s]

  5%|▍         | 355/7483 [01:35<41:43,  2.85it/s]

  5%|▍         | 355/7483 [01:35<41:43,  2.85it/s]
  5%|▍         | 356/7483 [01:35<41:43,  2.85it/s]

  5%|▍         | 357/7483 [01:36<41:16,  2.88it/s]

  5%|▍         | 357/7483 [01:36<41:16,  2.88it/s]
  5%|▍         | 358/7483 [01:36<41:15,  2.88it/s]

  5%|▍         | 359/7483 [01:37<41:34,  2.86it/s]

  5%|▍         | 359/7483 [01:37<41:34,  2.86it/s]
  5%|▍         | 360/7483 [01:37<41:34,  2.86it/s]

  5%|▍         | 361/7483 [01:40<1:21:45,  1.45it/s]

  5%|▍         | 361/7483 [01:40<1:21:45,  1.45it/s]
  5%|▍         | 362/7483 [01:40<1:21:45,  1.45it/s]
  5%|▍         | 363/7483 [01:40<1:21:44,  1.45it/s]

  5%|▍         | 364/7483 [01:40<1:00:40,  1.96it/s]

  5%|▍         | 364/7483 [01:40<1:00:40,  1.96it/s]
  5%|▍         | 365/7483 [01:40<1:00:40,  1.96it/s]

  5%|▍         | 366/7483 [01:41<55:02,  2.15it/s]

  5%|▍         | 366/7483 [01:41<55:02,  2.15it/s]
  5%|▍         | 367/7483 [01:41<55:02,  2.15it/s]

  5%|▍         | 368/7483 [01:42<51:27,  2.30it/s]

  5%|▍         | 368/7483 [01:42<51:27,  2.30it/s]
  5%|▍         | 369/7483 [01:42<51:26,  2.30it/s]

  5%|▍         | 370/7483 [01:42<48:13,  2.46it/s]

  5%|▍         | 370/7483 [01:42<48:13,  2.46it/s]
  5%|▍         | 371/7483 [01:42<48:13,  2.46it/s]

  5%|▍         | 372/7483 [01:43<45:28,  2.61it/s]

  5%|▍         | 372/7483 [01:43<45:28,  2.61it/s]
  5%|▍         | 373/7483 [01:43<45:28,  2.61it/s]

  5%|▍         | 374/7483 [01:44<44:01,  2.69it/s]
  5%|▌         | 385/7483 [01:44<14:08,  8.36it/s]

  5%|▍         | 374/7483 [01:44<44:01,  2.69it/s]
  5%|▌         | 375/7483 [01:44<44:00,  2.69it/s]
  5%|▌         | 376/7483 [01:44<44:00,  2.69it/s]
  5%|▌         | 377/7483 [01:44<44:00,  2.69it/s]
  5%|▌         | 378/7483 [01:44<43:59,  2.69it/s]
  5%|▌         | 379/7483 [01:44<43:59,  2.69it/s]
  5%|▌         | 380/7483 [01:44<43:59,  2.69it/s]
  5%|▌         | 381/7483 [01:44<43:58,  2.69it/s]
  5%|▌         | 382/7483 [01:44<43:58,  2.69it/s]
  5%|▌         | 383/7483 [01:44<43:57,  2.69it/s]
  5%|▌         | 384/7483 [01:44<43:57,  2.69it/s]
  5%|▌         | 385/7483 [01:44<14:08,  8.36it/s]
  5%|▌         | 386/7483 [01:44<14:08,  8.36it/s]
  5%|▌         | 387/7483 [01:44<14:08,  8.36it/s]
  5%|▌         | 388/7483 [01:44<14:08,  8.36it/s]
  5%|▌         | 389/7483 [01:44<14:08,  8.36it/s]
  5%|▌         | 390/7483 [01:44<14:08,  8.36it/s]
  5%|▌         | 391/7483 [01:44<14:08,  8.36it/s]

  5%|▌         | 393/7483 [01:44<08:56, 13.21it/s]

  5%|▌         | 392/7483 [01:44<14:08,  8.36it/s]
  5%|▌         | 393/7483 [01:44<08:56, 13.21it/s]
  5%|▌         | 394/7483 [01:44<08:56, 13.21it/s]
  5%|▌         | 395/7483 [01:44<08:56, 13.21it/s]

  5%|▌         | 398/7483 [01:45<10:49, 10.91it/s]

  5%|▌         | 396/7483 [01:45<08:56, 13.21it/s]
  5%|▌         | 397/7483 [01:45<08:56, 13.21it/s]
  5%|▌         | 398/7483 [01:45<10:49, 10.91it/s]
  5%|▌         | 399/7483 [01:45<10:49, 10.91it/s]

  5%|▌         | 402/7483 [01:45<12:53,  9.15it/s]

  5%|▌         | 400/7483 [01:45<10:49, 10.91it/s]
  5%|▌         | 401/7483 [01:45<10:49, 10.91it/s]
  5%|▌         | 402/7483 [01:45<12:53,  9.15it/s]

  5%|▌         | 405/7483 [01:46<15:38,  7.54it/s]

  5%|▌         | 403/7483 [01:46<12:53,  9.15it/s]
  5%|▌         | 404/7483 [01:46<12:53,  9.15it/s]
  5%|▌         | 405/7483 [01:46<15:38,  7.54it/s]

  5%|▌         | 407/7483 [01:47<19:24,  6.08it/s]

  5%|▌         | 406/7483 [01:47<15:38,  7.54it/s]
  5%|▌         | 407/7483 [01:47<19:24,  6.08it/s]
  5%|▌         | 408/7483 [01:47<19:24,  6.08it/s]
  5%|▌         | 409/7483 [01:47<19:24,  6.08it/s]
  5%|▌         | 410/7483 [01:47<19:24,  6.08it/s]
  5%|▌         | 411/7483 [01:47<19:23,  6.08it/s]

  6%|▌         | 412/7483 [01:47<18:02,  6.53it/s]

  6%|▌         | 412/7483 [01:47<18:02,  6.53it/s]
  6%|▌         | 413/7483 [01:47<18:02,  6.53it/s]

  6%|▌         | 414/7483 [01:48<21:43,  5.42it/s]

  6%|▌         | 414/7483 [01:48<21:43,  5.42it/s]
  6%|▌         | 415/7483 [01:48<21:42,  5.42it/s]

  6%|▌         | 416/7483 [01:48<24:46,  4.76it/s]

  6%|▌         | 416/7483 [01:48<24:46,  4.76it/s]
  6%|▌         | 417/7483 [01:48<24:45,  4.76it/s]
  6%|▌         | 418/7483 [01:48<24:45,  4.76it/s]
  6%|▌         | 419/7483 [01:49<24:45,  4.76it/s]

  6%|▌         | 420/7483 [01:49<22:44,  5.18it/s]

  6%|▌         | 420/7483 [01:49<22:44,  5.18it/s]
  6%|▌         | 421/7483 [01:49<22:44,  5.18it/s]
  6%|▌         | 422/7483 [01:49<22:44,  5.18it/s]

  6%|▌         | 423/7483 [01:52<48:45,  2.41it/s]

  6%|▌         | 423/7483 [01:52<48:45,  2.41it/s]
  6%|▌         | 424/7483 [01:52<48:45,  2.41it/s]
  6%|▌         | 425/7483 [01:52<48:45,  2.41it/s]

  6%|▌         | 426/7483 [01:53<41:47,  2.81it/s]

  6%|▌         | 426/7483 [01:53<41:47,  2.81it/s]
  6%|▌         | 427/7483 [01:53<41:47,  2.81it/s]

  6%|▌         | 428/7483 [01:53<41:18,  2.85it/s]

  6%|▌         | 428/7483 [01:53<41:18,  2.85it/s]
  6%|▌         | 429/7483 [01:53<41:18,  2.85it/s]

  6%|▌         | 430/7483 [01:54<40:58,  2.87it/s]

  6%|▌         | 430/7483 [01:54<40:58,  2.87it/s]
  6%|▌         | 431/7483 [01:54<40:58,  2.87it/s]

  6%|▌         | 432/7483 [01:55<40:14,  2.92it/s]

  6%|▌         | 432/7483 [01:55<40:14,  2.92it/s]
  6%|▌         | 433/7483 [01:55<40:14,  2.92it/s]

  6%|▌         | 434/7483 [01:55<40:09,  2.93it/s]

  6%|▌         | 434/7483 [01:55<40:09,  2.93it/s]
  6%|▌         | 435/7483 [01:55<40:09,  2.93it/s]
  6%|▌         | 436/7483 [01:55<40:08,  2.93it/s]

  6%|▌         | 437/7483 [01:56<35:06,  3.34it/s]

  6%|▌         | 437/7483 [01:56<35:06,  3.34it/s]
  6%|▌         | 438/7483 [01:56<35:06,  3.34it/s]

  6%|▌         | 439/7483 [01:57<35:42,  3.29it/s]

  6%|▌         | 439/7483 [01:57<35:42,  3.29it/s]
  6%|▌         | 440/7483 [01:57<35:42,  3.29it/s]

  6%|▌         | 441/7483 [01:57<36:37,  3.20it/s]

  6%|▌         | 441/7483 [01:57<36:37,  3.20it/s]
  6%|▌         | 442/7483 [01:57<36:37,  3.20it/s]
  6%|▌         | 443/7483 [01:57<36:37,  3.20it/s]

  6%|▌         | 444/7483 [01:58<32:50,  3.57it/s]

  6%|▌         | 444/7483 [01:58<32:50,  3.57it/s]
  6%|▌         | 445/7483 [01:58<32:50,  3.57it/s]

  6%|▌         | 446/7483 [01:59<34:11,  3.43it/s]

  6%|▌         | 446/7483 [01:59<34:11,  3.43it/s]
  6%|▌         | 447/7483 [01:59<34:11,  3.43it/s]
  6%|▌         | 448/7483 [01:59<34:10,  3.43it/s]
  6%|▌         | 449/7483 [01:59<34:10,  3.43it/s]

  6%|▌         | 450/7483 [01:59<28:10,  4.16it/s]

  6%|▌         | 450/7483 [01:59<28:10,  4.16it/s]
  6%|▌         | 451/7483 [01:59<28:10,  4.16it/s]

  6%|▌         | 452/7483 [02:00<30:18,  3.87it/s]

  6%|▌         | 452/7483 [02:00<30:18,  3.87it/s]
  6%|▌         | 453/7483 [02:00<30:18,  3.87it/s]

  6%|▌         | 454/7483 [02:01<32:24,  3.62it/s]

  6%|▌         | 454/7483 [02:01<32:24,  3.62it/s]
  6%|▌         | 455/7483 [02:01<32:23,  3.62it/s]

  6%|▌         | 456/7483 [02:01<34:23,  3.41it/s]

  6%|▌         | 456/7483 [02:01<34:23,  3.41it/s]
  6%|▌         | 457/7483 [02:01<34:23,  3.41it/s]

  6%|▌         | 458/7483 [02:02<34:57,  3.35it/s]

  6%|▌         | 458/7483 [02:02<34:57,  3.35it/s]
  6%|▌         | 459/7483 [02:02<34:57,  3.35it/s]
  6%|▌         | 460/7483 [02:02<34:56,  3.35it/s]

  6%|▌         | 461/7483 [02:05<1:04:13,  1.82it/s]

  6%|▌         | 461/7483 [02:05<1:04:13,  1.82it/s]
  6%|▌         | 462/7483 [02:05<1:04:13,  1.82it/s]
  6%|▌         | 463/7483 [02:05<1:04:12,  1.82it/s]
  6%|▌         | 464/7483 [02:05<1:04:12,  1.82it/s]
  6%|▌         | 465/7483 [02:05<1:04:11,  1.82it/s]
  6%|▌         | 466/7483 [02:05<1:04:11,  1.82it/s]
  6%|▌         | 467/7483 [02:05<1:04:10,  1.82it/s]
  6%|▋         | 468/7483 [02:05<1:04:09,  1.82it/s]
  6%|▋         | 469/7483 [02:05<1:04:09,  1.82it/s]

  6%|▋         | 470/7483 [02:06<29:59,  3.90it/s]

  6%|▋         | 470/7483 [02:06<29:59,  3.90it/s]
  6%|▋         | 471/7483 [02:06<29:59,  3.90it/s]

  6%|▋         | 472/7483 [02:06<30:57,  3.77it/s]

  6%|▋         | 472/7483 [02:06<30:57,  3.77it/s]
  6%|▋         | 473/7483 [02:06<30:57,  3.77it/s]

  6%|▋         | 474/7483 [02:07<32:09,  3.63it/s]

  6%|▋         | 474/7483 [02:07<32:09,  3.63it/s]
  6%|▋         | 475/7483 [02:07<32:08,  3.63it/s]

  6%|▋         | 476/7483 [02:07<33:06,  3.53it/s]

  6%|▋         | 476/7483 [02:07<33:06,  3.53it/s]
  6%|▋         | 477/7483 [02:07<33:06,  3.53it/s]

  6%|▋         | 478/7483 [02:08<34:09,  3.42it/s]

  6%|▋         | 478/7483 [02:08<34:09,  3.42it/s]
  6%|▋         | 479/7483 [02:08<34:08,  3.42it/s]

  6%|▋         | 480/7483 [02:09<35:08,  3.32it/s]

  6%|▋         | 480/7483 [02:09<35:08,  3.32it/s]
  6%|▋         | 481/7483 [02:09<35:08,  3.32it/s]

  6%|▋         | 482/7483 [02:09<35:20,  3.30it/s]

  6%|▋         | 482/7483 [02:09<35:20,  3.30it/s]
  6%|▋         | 483/7483 [02:09<35:20,  3.30it/s]

  6%|▋         | 484/7483 [02:10<36:16,  3.22it/s]

  6%|▋         | 484/7483 [02:10<36:16,  3.22it/s]
  6%|▋         | 485/7483 [02:10<36:16,  3.22it/s]

  6%|▋         | 486/7483 [02:11<37:15,  3.13it/s]

  6%|▋         | 486/7483 [02:11<37:15,  3.13it/s]
  7%|▋         | 487/7483 [02:11<37:15,  3.13it/s]

  7%|▋         | 488/7483 [02:11<37:25,  3.12it/s]

  7%|▋         | 488/7483 [02:11<37:25,  3.12it/s]
  7%|▋         | 489/7483 [02:11<37:24,  3.12it/s]

  7%|▋         | 490/7483 [02:12<38:17,  3.04it/s]

  7%|▋         | 490/7483 [02:12<38:17,  3.04it/s]
  7%|▋         | 491/7483 [02:12<38:17,  3.04it/s]
  7%|▋         | 492/7483 [02:12<38:16,  3.04it/s]

  7%|▋         | 493/7483 [02:13<33:25,  3.49it/s]

  7%|▋         | 493/7483 [02:13<33:25,  3.49it/s]
  7%|▋         | 494/7483 [02:13<33:25,  3.49it/s]

  7%|▋         | 495/7483 [02:13<34:39,  3.36it/s]

  7%|▋         | 495/7483 [02:13<34:39,  3.36it/s]
  7%|▋         | 496/7483 [02:13<34:38,  3.36it/s]
  7%|▋         | 497/7483 [02:13<34:38,  3.36it/s]
  7%|▋         | 498/7483 [02:13<34:38,  3.36it/s]
  7%|▋         | 499/7483 [02:13<34:38,  3.36it/s]

  7%|▋         | 500/7483 [02:14<25:11,  4.62it/s]

  7%|▋         | 500/7483 [02:14<25:11,  4.62it/s]
  7%|▋         | 501/7483 [02:14<25:11,  4.62it/s]

  7%|▋         | 502/7483 [02:15<27:21,  4.25it/s]

  7%|▋         | 502/7483 [02:15<27:21,  4.25it/s]
  7%|▋         | 503/7483 [02:15<27:21,  4.25it/s]

  7%|▋         | 504/7483 [02:18<1:01:51,  1.88it/s]

  7%|▋         | 504/7483 [02:18<1:01:51,  1.88it/s]
  7%|▋         | 505/7483 [02:18<1:01:50,  1.88it/s]

  7%|▋         | 506/7483 [02:18<55:51,  2.08it/s]

  7%|▋         | 506/7483 [02:18<55:51,  2.08it/s]
  7%|▋         | 507/7483 [02:18<55:50,  2.08it/s]

  7%|▋         | 508/7483 [02:19<50:18,  2.31it/s]

  7%|▋         | 508/7483 [02:19<50:18,  2.31it/s]
  7%|▋         | 509/7483 [02:19<50:18,  2.31it/s]

  7%|▋         | 510/7483 [02:20<47:06,  2.47it/s]

  7%|▋         | 510/7483 [02:20<47:06,  2.47it/s]
  7%|▋         | 511/7483 [02:20<47:06,  2.47it/s]
  7%|▋         | 512/7483 [02:20<47:05,  2.47it/s]

  7%|▋         | 513/7483 [02:20<38:15,  3.04it/s]

  7%|▋         | 513/7483 [02:20<38:15,  3.04it/s]
  7%|▋         | 514/7483 [02:20<38:14,  3.04it/s]
  7%|▋         | 515/7483 [02:20<38:14,  3.04it/s]

  7%|▋         | 516/7483 [02:21<33:33,  3.46it/s]

  7%|▋         | 516/7483 [02:21<33:33,  3.46it/s]
  7%|▋         | 517/7483 [02:21<33:33,  3.46it/s]
  7%|▋         | 518/7483 [02:21<33:33,  3.46it/s]

  7%|▋         | 519/7483 [02:21<30:24,  3.82it/s]

  7%|▋         | 519/7483 [02:21<30:24,  3.82it/s]
  7%|▋         | 520/7483 [02:21<30:24,  3.82it/s]

  7%|▋         | 521/7483 [02:22<32:18,  3.59it/s]

  7%|▋         | 521/7483 [02:22<32:18,  3.59it/s]
  7%|▋         | 522/7483 [02:22<32:18,  3.59it/s]

  7%|▋         | 523/7483 [02:23<33:01,  3.51it/s]

  7%|▋         | 523/7483 [02:23<33:01,  3.51it/s]
  7%|▋         | 524/7483 [02:23<33:01,  3.51it/s]

  7%|▋         | 525/7483 [02:23<33:20,  3.48it/s]

  7%|▋         | 525/7483 [02:23<33:20,  3.48it/s]
  7%|▋         | 526/7483 [02:23<33:19,  3.48it/s]

  7%|▋         | 527/7483 [02:24<34:07,  3.40it/s]

  7%|▋         | 527/7483 [02:24<34:07,  3.40it/s]
  7%|▋         | 528/7483 [02:24<34:07,  3.40it/s]

  7%|▋         | 529/7483 [02:24<35:02,  3.31it/s]

  7%|▋         | 529/7483 [02:24<35:02,  3.31it/s]
  7%|▋         | 530/7483 [02:25<35:01,  3.31it/s]

  7%|▋         | 531/7483 [02:25<34:53,  3.32it/s]

  7%|▋         | 531/7483 [02:25<34:53,  3.32it/s]
  7%|▋         | 532/7483 [02:25<34:53,  3.32it/s]

  7%|▋         | 533/7483 [02:26<35:05,  3.30it/s]

  7%|▋         | 533/7483 [02:26<35:05,  3.30it/s]
  7%|▋         | 534/7483 [02:26<35:05,  3.30it/s]

  7%|▋         | 535/7483 [02:26<35:31,  3.26it/s]

  7%|▋         | 535/7483 [02:26<35:31,  3.26it/s]
  7%|▋         | 536/7483 [02:26<35:31,  3.26it/s]

  7%|▋         | 537/7483 [02:27<36:45,  3.15it/s]

  7%|▋         | 537/7483 [02:27<36:45,  3.15it/s]
  7%|▋         | 538/7483 [02:27<36:44,  3.15it/s]

  7%|▋         | 539/7483 [02:29<1:03:30,  1.82it/s]

  7%|▋         | 539/7483 [02:29<1:03:30,  1.82it/s]
  7%|▋         | 540/7483 [02:29<1:03:30,  1.82it/s]

  7%|▋         | 541/7483 [02:31<1:07:24,  1.72it/s]

  7%|▋         | 541/7483 [02:31<1:07:24,  1.72it/s]
  7%|▋         | 542/7483 [02:31<1:07:23,  1.72it/s]
  7%|▋         | 543/7483 [02:31<1:07:22,  1.72it/s]

  7%|▋         | 544/7483 [02:31<51:00,  2.27it/s]

  7%|▋         | 544/7483 [02:31<51:00,  2.27it/s]
  7%|▋         | 545/7483 [02:31<50:59,  2.27it/s]
  7%|▋         | 546/7483 [02:31<50:59,  2.27it/s]
  7%|▋         | 547/7483 [02:31<50:58,  2.27it/s]

  7%|▋         | 548/7483 [02:32<37:11,  3.11it/s]

  7%|▋         | 548/7483 [02:32<37:11,  3.11it/s]
  7%|▋         | 549/7483 [02:32<37:10,  3.11it/s]

  7%|▋         | 550/7483 [02:32<37:10,  3.11it/s]

  7%|▋         | 550/7483 [02:32<37:10,  3.11it/s]
  7%|▋         | 551/7483 [02:32<37:09,  3.11it/s]

  7%|▋         | 552/7483 [02:33<37:30,  3.08it/s]

  7%|▋         | 552/7483 [02:33<37:30,  3.08it/s]
  7%|▋         | 553/7483 [02:33<37:29,  3.08it/s]
  7%|▋         | 554/7483 [02:33<37:29,  3.08it/s]

  7%|▋         | 555/7483 [02:34<33:07,  3.49it/s]

  7%|▋         | 555/7483 [02:34<33:07,  3.49it/s]
  7%|▋         | 556/7483 [02:34<33:06,  3.49it/s]

  7%|▋         | 557/7483 [02:34<34:12,  3.38it/s]

  7%|▋         | 557/7483 [02:34<34:12,  3.38it/s]
  7%|▋         | 558/7483 [02:34<34:11,  3.38it/s]
  7%|▋         | 559/7483 [02:35<34:11,  3.38it/s]
  7%|▋         | 560/7483 [02:35<34:11,  3.38it/s]
  7%|▋         | 561/7483 [02:35<34:10,  3.38it/s]
  8%|▊         | 562/7483 [02:35<34:10,  3.38it/s]

  8%|▊         | 563/7483 [02:35<23:09,  4.98it/s]

  8%|▊         | 563/7483 [02:35<23:09,  4.98it/s]
  8%|▊         | 564/7483 [02:35<23:09,  4.98it/s]

  8%|▊         | 565/7483 [02:36<25:52,  4.46it/s]

  8%|▊         | 565/7483 [02:36<25:52,  4.46it/s]
  8%|▊         | 566/7483 [02:36<25:52,  4.46it/s]

  8%|▊         | 567/7483 [02:36<28:30,  4.04it/s]

  8%|▊         | 567/7483 [02:36<28:30,  4.04it/s]
  8%|▊         | 568/7483 [02:36<28:30,  4.04it/s]

  8%|▊         | 569/7483 [02:37<30:50,  3.74it/s]

  8%|▊         | 569/7483 [02:37<30:50,  3.74it/s]
  8%|▊         | 570/7483 [02:37<30:50,  3.74it/s]

  8%|▊         | 571/7483 [02:38<32:11,  3.58it/s]

  8%|▊         | 571/7483 [02:38<32:11,  3.58it/s]
  8%|▊         | 572/7483 [02:38<32:11,  3.58it/s]

  8%|▊         | 573/7483 [02:38<33:33,  3.43it/s]

  8%|▊         | 573/7483 [02:38<33:33,  3.43it/s]
  8%|▊         | 574/7483 [02:38<33:33,  3.43it/s]

  8%|▊         | 575/7483 [02:39<34:08,  3.37it/s]

  8%|▊         | 575/7483 [02:39<34:08,  3.37it/s]
  8%|▊         | 576/7483 [02:39<34:07,  3.37it/s]

  8%|▊         | 577/7483 [02:40<35:31,  3.24it/s]

  8%|▊         | 577/7483 [02:40<35:31,  3.24it/s]
  8%|▊         | 578/7483 [02:40<35:30,  3.24it/s]

  8%|▊         | 579/7483 [02:41<42:16,  2.72it/s]

  8%|▊         | 579/7483 [02:41<42:16,  2.72it/s]
  8%|▊         | 580/7483 [02:41<42:15,  2.72it/s]

  8%|▊         | 581/7483 [02:43<1:12:46,  1.58it/s]

  8%|▊         | 581/7483 [02:43<1:12:46,  1.58it/s]
  8%|▊         | 582/7483 [02:43<1:12:45,  1.58it/s]
  8%|▊         | 583/7483 [02:43<1:12:45,  1.58it/s]
  8%|▊         | 584/7483 [02:43<1:12:44,  1.58it/s]
  8%|▊         | 585/7483 [02:43<1:12:44,  1.58it/s]
  8%|▊         | 586/7483 [02:43<1:12:43,  1.58it/s]

  8%|▊         | 587/7483 [02:44<39:11,  2.93it/s]

  8%|▊         | 587/7483 [02:44<39:11,  2.93it/s]
  8%|▊         | 588/7483 [02:44<39:11,  2.93it/s]
  8%|▊         | 589/7483 [02:44<39:10,  2.93it/s]
  8%|▊         | 590/7483 [02:44<39:10,  2.93it/s]
  8%|▊         | 591/7483 [02:44<39:10,  2.93it/s]

  8%|▊         | 592/7483 [02:45<29:41,  3.87it/s]

  8%|▊         | 592/7483 [02:45<29:41,  3.87it/s]
  8%|▊         | 593/7483 [02:45<29:41,  3.87it/s]

  8%|▊         | 594/7483 [02:45<31:03,  3.70it/s]

  8%|▊         | 594/7483 [02:45<31:03,  3.70it/s]
  8%|▊         | 595/7483 [02:45<31:02,  3.70it/s]
  8%|▊         | 596/7483 [02:45<31:02,  3.70it/s]
  8%|▊         | 597/7483 [02:45<31:02,  3.70it/s]

  8%|▊         | 598/7483 [02:46<26:54,  4.26it/s]

  8%|▊         | 598/7483 [02:46<26:54,  4.26it/s]
  8%|▊         | 599/7483 [02:46<26:54,  4.26it/s]

  8%|▊         | 600/7483 [02:47<28:51,  3.97it/s]

  8%|▊         | 600/7483 [02:47<28:51,  3.97it/s]
  8%|▊         | 601/7483 [02:47<28:51,  3.97it/s]

  8%|▊         | 602/7483 [02:47<30:39,  3.74it/s]

  8%|▊         | 602/7483 [02:47<30:39,  3.74it/s]
  8%|▊         | 603/7483 [02:47<30:38,  3.74it/s]

  8%|▊         | 604/7483 [02:48<32:16,  3.55it/s]

  8%|▊         | 604/7483 [02:48<32:16,  3.55it/s]
  8%|▊         | 605/7483 [02:48<32:16,  3.55it/s]
  8%|▊         | 606/7483 [02:48<32:16,  3.55it/s]

  8%|▊         | 607/7483 [02:48<29:51,  3.84it/s]

  8%|▊         | 607/7483 [02:48<29:51,  3.84it/s]
  8%|▊         | 608/7483 [02:48<29:51,  3.84it/s]

  8%|▊         | 609/7483 [02:49<31:50,  3.60it/s]

  8%|▊         | 609/7483 [02:49<31:50,  3.60it/s]
  8%|▊         | 610/7483 [02:49<31:50,  3.60it/s]

  8%|▊         | 611/7483 [02:50<33:32,  3.41it/s]

  8%|▊         | 611/7483 [02:50<33:32,  3.41it/s]
  8%|▊         | 612/7483 [02:50<33:32,  3.41it/s]

  8%|▊         | 613/7483 [02:50<34:20,  3.33it/s]

  8%|▊         | 613/7483 [02:50<34:20,  3.33it/s]
  8%|▊         | 614/7483 [02:50<34:19,  3.33it/s]

  8%|▊         | 615/7483 [02:51<35:11,  3.25it/s]

  8%|▊         | 615/7483 [02:51<35:11,  3.25it/s]
  8%|▊         | 616/7483 [02:51<35:10,  3.25it/s]
  8%|▊         | 617/7483 [02:51<35:10,  3.25it/s]
  8%|▊         | 618/7483 [02:51<35:10,  3.25it/s]

  8%|▊         | 619/7483 [02:52<28:52,  3.96it/s]

  8%|▊         | 619/7483 [02:52<28:52,  3.96it/s]
  8%|▊         | 620/7483 [02:52<28:52,  3.96it/s]

  8%|▊         | 621/7483 [02:52<30:36,  3.74it/s]

  8%|▊         | 621/7483 [02:52<30:36,  3.74it/s]
  8%|▊         | 622/7483 [02:52<30:36,  3.74it/s]

  8%|▊         | 623/7483 [02:55<52:53,  2.16it/s]

  8%|▊         | 623/7483 [02:55<52:53,  2.16it/s]
  8%|▊         | 624/7483 [02:55<52:52,  2.16it/s]

  8%|▊         | 625/7483 [02:56<1:01:25,  1.86it/s]

  8%|▊         | 625/7483 [02:56<1:01:25,  1.86it/s]
  8%|▊         | 626/7483 [02:56<1:01:24,  1.86it/s]

  8%|▊         | 627/7483 [02:57<54:23,  2.10it/s]

  8%|▊         | 627/7483 [02:57<54:23,  2.10it/s]
  8%|▊         | 628/7483 [02:57<54:23,  2.10it/s]

  8%|▊         | 629/7483 [02:57<49:34,  2.30it/s]

  8%|▊         | 629/7483 [02:57<49:34,  2.30it/s]
  8%|▊         | 630/7483 [02:57<49:34,  2.30it/s]
  8%|▊         | 631/7483 [02:57<49:33,  2.30it/s]
  8%|▊         | 632/7483 [02:57<49:33,  2.30it/s]

  8%|▊         | 633/7483 [02:58<35:19,  3.23it/s]

  8%|▊         | 633/7483 [02:58<35:19,  3.23it/s]
  8%|▊         | 634/7483 [02:58<35:19,  3.23it/s]
  8%|▊         | 635/7483 [02:58<35:19,  3.23it/s]

  8%|▊         | 636/7483 [02:59<32:00,  3.56it/s]

  8%|▊         | 636/7483 [02:59<32:00,  3.56it/s]
  9%|▊         | 637/7483 [02:59<32:00,  3.56it/s]

  9%|▊         | 638/7483 [02:59<33:10,  3.44it/s]

  9%|▊         | 638/7483 [02:59<33:10,  3.44it/s]
  9%|▊         | 639/7483 [02:59<33:10,  3.44it/s]

  9%|▊         | 640/7483 [03:00<34:07,  3.34it/s]

  9%|▊         | 640/7483 [03:00<34:07,  3.34it/s]
  9%|▊         | 641/7483 [03:00<34:07,  3.34it/s]

  9%|▊         | 642/7483 [03:01<35:23,  3.22it/s]

  9%|▊         | 642/7483 [03:01<35:23,  3.22it/s]
  9%|▊         | 643/7483 [03:01<35:23,  3.22it/s]

  9%|▊         | 644/7483 [03:01<36:07,  3.16it/s]

  9%|▊         | 644/7483 [03:01<36:07,  3.16it/s]
  9%|▊         | 645/7483 [03:01<36:07,  3.16it/s]
  9%|▊         | 646/7483 [03:01<36:06,  3.16it/s]

  9%|▊         | 647/7483 [03:02<31:52,  3.57it/s]

  9%|▊         | 647/7483 [03:02<31:52,  3.57it/s]
  9%|▊         | 648/7483 [03:02<31:52,  3.57it/s]
  9%|▊         | 649/7483 [03:02<31:51,  3.57it/s]

  9%|▊         | 650/7483 [03:03<29:33,  3.85it/s]

  9%|▊         | 650/7483 [03:03<29:33,  3.85it/s]
  9%|▊         | 651/7483 [03:03<29:33,  3.85it/s]

  9%|▊         | 652/7483 [03:03<31:18,  3.64it/s]

  9%|▊         | 652/7483 [03:03<31:18,  3.64it/s]
  9%|▊         | 653/7483 [03:03<31:17,  3.64it/s]

  9%|▊         | 654/7483 [03:04<33:00,  3.45it/s]

  9%|▊         | 654/7483 [03:04<33:00,  3.45it/s]
  9%|▉         | 655/7483 [03:04<32:59,  3.45it/s]
  9%|▉         | 656/7483 [03:04<32:59,  3.45it/s]
  9%|▉         | 657/7483 [03:04<32:59,  3.45it/s]
  9%|▉         | 658/7483 [03:04<32:59,  3.45it/s]
  9%|▉         | 659/7483 [03:04<32:58,  3.45it/s]
  9%|▉         | 660/7483 [03:04<32:58,  3.45it/s]
  9%|▉         | 661/7483 [03:04<32:58,  3.45it/s]
  9%|▉         | 662/7483 [03:04<32:57,  3.45it/s]
  9%|▉         | 663/7483 [03:04<32:57,  3.45it/s]

  9%|▉         | 664/7483 [03:05<16:37,  6.84it/s]

  9%|▉         | 664/7483 [03:05<16:37,  6.84it/s]
  9%|▉         | 665/7483 [03:05<16:36,  6.84it/s]

  9%|▉         | 666/7483 [03:05<19:49,  5.73it/s]

  9%|▉         | 666/7483 [03:05<19:49,  5.73it/s]
  9%|▉         | 667/7483 [03:05<19:49,  5.73it/s]

  9%|▉         | 668/7483 [03:08<41:03,  2.77it/s]

  9%|▉         | 668/7483 [03:08<41:03,  2.77it/s]
  9%|▉         | 669/7483 [03:08<41:03,  2.77it/s]

  9%|▉         | 670/7483 [03:09<47:33,  2.39it/s]

  9%|▉         | 670/7483 [03:09<47:33,  2.39it/s]
  9%|▉         | 671/7483 [03:09<47:33,  2.39it/s]

  9%|▉         | 672/7483 [03:10<45:15,  2.51it/s]

  9%|▉         | 672/7483 [03:10<45:15,  2.51it/s]
  9%|▉         | 673/7483 [03:10<45:14,  2.51it/s]

  9%|▉         | 674/7483 [03:10<43:32,  2.61it/s]

  9%|▉         | 674/7483 [03:10<43:32,  2.61it/s]
  9%|▉         | 675/7483 [03:10<43:32,  2.61it/s]

  9%|▉         | 676/7483 [03:11<42:22,  2.68it/s]

  9%|▉         | 676/7483 [03:11<42:22,  2.68it/s]
  9%|▉         | 677/7483 [03:11<42:22,  2.68it/s]

  9%|▉         | 678/7483 [03:12<41:38,  2.72it/s]

  9%|▉         | 678/7483 [03:12<41:38,  2.72it/s]
  9%|▉         | 679/7483 [03:12<41:38,  2.72it/s]
  9%|▉         | 680/7483 [03:12<41:37,  2.72it/s]
  9%|▉         | 681/7483 [03:12<41:37,  2.72it/s]

  9%|▉         | 682/7483 [03:12<32:01,  3.54it/s]

  9%|▉         | 682/7483 [03:12<32:01,  3.54it/s]
  9%|▉         | 683/7483 [03:12<32:01,  3.54it/s]

  9%|▉         | 684/7483 [03:13<33:22,  3.40it/s]

  9%|▉         | 684/7483 [03:13<33:22,  3.40it/s]
  9%|▉         | 685/7483 [03:13<33:21,  3.40it/s]

  9%|▉         | 686/7483 [03:14<34:09,  3.32it/s]

  9%|▉         | 686/7483 [03:14<34:09,  3.32it/s]
  9%|▉         | 687/7483 [03:14<34:09,  3.32it/s]

  9%|▉         | 688/7483 [03:14<35:41,  3.17it/s]

  9%|▉         | 688/7483 [03:14<35:41,  3.17it/s]
  9%|▉         | 689/7483 [03:14<35:41,  3.17it/s]

  9%|▉         | 690/7483 [03:15<36:27,  3.11it/s]

  9%|▉         | 690/7483 [03:15<36:27,  3.11it/s]
  9%|▉         | 691/7483 [03:15<36:27,  3.11it/s]

  9%|▉         | 692/7483 [03:16<36:44,  3.08it/s]

  9%|▉         | 692/7483 [03:16<36:44,  3.08it/s]
  9%|▉         | 693/7483 [03:16<36:44,  3.08it/s]
  9%|▉         | 694/7483 [03:16<36:43,  3.08it/s]
  9%|▉         | 695/7483 [03:16<36:43,  3.08it/s]
  9%|▉         | 696/7483 [03:16<36:43,  3.08it/s]

  9%|▉         | 697/7483 [03:16<26:12,  4.32it/s]

  9%|▉         | 697/7483 [03:16<26:12,  4.32it/s]
  9%|▉         | 698/7483 [03:16<26:12,  4.32it/s]

  9%|▉         | 699/7483 [03:17<28:51,  3.92it/s]

  9%|▉         | 699/7483 [03:17<28:51,  3.92it/s]
  9%|▉         | 700/7483 [03:17<28:51,  3.92it/s]

  9%|▉         | 701/7483 [03:18<30:53,  3.66it/s]

  9%|▉         | 701/7483 [03:18<30:53,  3.66it/s]
  9%|▉         | 702/7483 [03:18<30:53,  3.66it/s]

  9%|▉         | 703/7483 [03:18<33:00,  3.42it/s]

  9%|▉         | 703/7483 [03:18<33:00,  3.42it/s]
  9%|▉         | 704/7483 [03:18<32:59,  3.42it/s]

  9%|▉         | 705/7483 [03:21<1:08:45,  1.64it/s]

  9%|▉         | 705/7483 [03:21<1:08:45,  1.64it/s]
  9%|▉         | 706/7483 [03:21<1:08:45,  1.64it/s]

  9%|▉         | 707/7483 [03:22<1:00:51,  1.86it/s]

  9%|▉         | 707/7483 [03:22<1:00:51,  1.86it/s]
  9%|▉         | 708/7483 [03:22<1:00:50,  1.86it/s]

  9%|▉         | 709/7483 [03:23<54:15,  2.08it/s]

  9%|▉         | 709/7483 [03:23<54:15,  2.08it/s]
  9%|▉         | 710/7483 [03:23<54:15,  2.08it/s]

 10%|▉         | 711/7483 [03:23<49:30,  2.28it/s]

 10%|▉         | 711/7483 [03:23<49:30,  2.28it/s]
 10%|▉         | 712/7483 [03:23<49:29,  2.28it/s]
 10%|▉         | 713/7483 [03:23<49:29,  2.28it/s]
 10%|▉         | 714/7483 [03:23<49:28,  2.28it/s]

 10%|▉         | 715/7483 [03:24<35:26,  3.18it/s]

 10%|▉         | 715/7483 [03:24<35:26,  3.18it/s]
 10%|▉         | 716/7483 [03:24<35:25,  3.18it/s]

 10%|▉         | 717/7483 [03:25<36:27,  3.09it/s]

 10%|▉         | 717/7483 [03:25<36:27,  3.09it/s]
 10%|▉         | 718/7483 [03:25<36:27,  3.09it/s]

 10%|▉         | 719/7483 [03:25<36:58,  3.05it/s]

 10%|▉         | 719/7483 [03:25<36:58,  3.05it/s]
 10%|▉         | 720/7483 [03:25<36:57,  3.05it/s]

 10%|▉         | 721/7483 [03:26<36:46,  3.06it/s]

 10%|▉         | 721/7483 [03:26<36:46,  3.06it/s]
 10%|▉         | 722/7483 [03:26<36:46,  3.06it/s]

 10%|▉         | 723/7483 [03:27<37:01,  3.04it/s]

 10%|▉         | 723/7483 [03:27<37:01,  3.04it/s]
 10%|▉         | 724/7483 [03:27<37:00,  3.04it/s]

 10%|▉         | 725/7483 [03:27<36:54,  3.05it/s]

 10%|▉         | 725/7483 [03:27<36:54,  3.05it/s]
 10%|▉         | 726/7483 [03:27<36:53,  3.05it/s]

 10%|▉         | 727/7483 [03:28<37:39,  2.99it/s]

 10%|▉         | 727/7483 [03:28<37:39,  2.99it/s]
 10%|▉         | 728/7483 [03:28<37:38,  2.99it/s]

 10%|▉         | 729/7483 [03:29<38:04,  2.96it/s]

 10%|▉         | 729/7483 [03:29<38:04,  2.96it/s]
 10%|▉         | 730/7483 [03:29<38:03,  2.96it/s]

 10%|▉         | 731/7483 [03:29<37:58,  2.96it/s]
 10%|▉         | 737/7483 [03:30<18:00,  6.24it/s]

 10%|▉         | 731/7483 [03:29<37:58,  2.96it/s]
 10%|▉         | 732/7483 [03:29<37:58,  2.96it/s]
 10%|▉         | 733/7483 [03:29<37:58,  2.96it/s]
 10%|▉         | 734/7483 [03:29<37:57,  2.96it/s]
 10%|▉         | 735/7483 [03:29<37:57,  2.96it/s]
 10%|▉         | 736/7483 [03:30<37:57,  2.96it/s]
 10%|▉         | 737/7483 [03:30<18:00,  6.24it/s]
 10%|▉         | 738/7483 [03:30<18:00,  6.24it/s]
 10%|▉         | 739/7483 [03:30<18:00,  6.24it/s]
 10%|▉         | 740/7483 [03:30<17:59,  6.24it/s]

 10%|▉         | 742/7483 [03:30<11:54,  9.44it/s]

 10%|▉         | 741/7483 [03:30<17:59,  6.24it/s]
 10%|▉         | 742/7483 [03:30<11:54,  9.44it/s]
 10%|▉         | 743/7483 [03:30<11:54,  9.44it/s]
 10%|▉         | 744/7483 [03:30<11:54,  9.44it/s]
 10%|▉         | 745/7483 [03:30<11:53,  9.44it/s]

 10%|▉         | 746/7483 [03:30<14:15,  7.87it/s]

 10%|▉         | 746/7483 [03:30<14:15,  7.87it/s]
 10%|▉         | 747/7483 [03:30<14:15,  7.87it/s]
 10%|▉         | 748/7483 [03:30<14:15,  7.87it/s]
 10%|█         | 749/7483 [03:30<14:15,  7.87it/s]
 10%|█         | 750/7483 [03:30<14:15,  7.87it/s]

 10%|█         | 751/7483 [03:31<15:57,  7.03it/s]

 10%|█         | 751/7483 [03:31<15:57,  7.03it/s]
 10%|█         | 752/7483 [03:31<15:57,  7.03it/s]

 10%|█         | 753/7483 [03:34<40:01,  2.80it/s]

 10%|█         | 753/7483 [03:34<40:01,  2.80it/s]
 10%|█         | 754/7483 [03:34<40:00,  2.80it/s]

 10%|█         | 755/7483 [03:35<39:36,  2.83it/s]

 10%|█         | 755/7483 [03:35<39:36,  2.83it/s]
 10%|█         | 756/7483 [03:35<39:35,  2.83it/s]
 10%|█         | 757/7483 [03:35<39:35,  2.83it/s]

 10%|█         | 758/7483 [03:35<35:43,  3.14it/s]

 10%|█         | 758/7483 [03:35<35:43,  3.14it/s]
 10%|█         | 759/7483 [03:35<35:42,  3.14it/s]

 10%|█         | 760/7483 [03:36<36:25,  3.08it/s]

 10%|█         | 760/7483 [03:36<36:25,  3.08it/s]
 10%|█         | 761/7483 [03:36<36:25,  3.08it/s]

 10%|█         | 762/7483 [03:37<36:47,  3.04it/s]
 10%|█         | 771/7483 [03:37<15:16,  7.32it/s]

 10%|█         | 762/7483 [03:37<36:47,  3.04it/s]
 10%|█         | 763/7483 [03:37<36:46,  3.04it/s]
 10%|█         | 764/7483 [03:37<36:46,  3.04it/s]
 10%|█         | 765/7483 [03:37<36:46,  3.04it/s]
 10%|█         | 766/7483 [03:37<36:45,  3.04it/s]
 10%|█         | 767/7483 [03:37<36:45,  3.04it/s]
 10%|█         | 768/7483 [03:37<36:45,  3.04it/s]
 10%|█         | 769/7483 [03:37<36:44,  3.04it/s]
 10%|█         | 770/7483 [03:37<36:44,  3.04it/s]
 10%|█         | 771/7483 [03:37<15:16,  7.32it/s]
 10%|█         | 772/7483 [03:38<15:16,  7.32it/s]
 10%|█         | 773/7483 [03:38<15:16,  7.32it/s]

 10%|█         | 774/7483 [03:38<22:53,  4.89it/s]

 10%|█         | 774/7483 [03:38<22:53,  4.89it/s]
 10%|█         | 775/7483 [03:38<22:53,  4.89it/s]

 10%|█         | 777/7483 [03:39<23:19,  4.79it/s]

 10%|█         | 776/7483 [03:39<22:52,  4.89it/s]
 10%|█         | 777/7483 [03:39<23:19,  4.79it/s]

 10%|█         | 779/7483 [03:40<26:18,  4.25it/s]

 10%|█         | 778/7483 [03:40<23:19,  4.79it/s]
 10%|█         | 779/7483 [03:40<26:18,  4.25it/s]

 10%|█         | 781/7483 [03:40<29:17,  3.81it/s]

 10%|█         | 780/7483 [03:40<26:18,  4.25it/s]
 10%|█         | 781/7483 [03:40<29:17,  3.81it/s]

 10%|█         | 782/7483 [03:41<35:34,  3.14it/s]

 10%|█         | 782/7483 [03:41<35:34,  3.14it/s]
 10%|█         | 783/7483 [03:41<35:33,  3.14it/s]

 10%|█         | 784/7483 [03:42<36:33,  3.05it/s]

 10%|█         | 784/7483 [03:42<36:33,  3.05it/s]
 10%|█         | 785/7483 [03:42<36:33,  3.05it/s]

 11%|█         | 786/7483 [03:42<37:34,  2.97it/s]

 11%|█         | 786/7483 [03:42<37:34,  2.97it/s]
 11%|█         | 787/7483 [03:42<37:33,  2.97it/s]
 11%|█         | 788/7483 [03:42<37:33,  2.97it/s]

 11%|█         | 789/7483 [03:43<33:02,  3.38it/s]

 11%|█         | 789/7483 [03:43<33:02,  3.38it/s]
 11%|█         | 790/7483 [03:43<33:02,  3.38it/s]

 11%|█         | 791/7483 [03:45<57:14,  1.95it/s]

 11%|█         | 791/7483 [03:45<57:14,  1.95it/s]
 11%|█         | 792/7483 [03:45<57:13,  1.95it/s]

 11%|█         | 793/7483 [03:47<1:03:13,  1.76it/s]

 11%|█         | 793/7483 [03:47<1:03:13,  1.76it/s]
 11%|█         | 794/7483 [03:47<1:03:13,  1.76it/s]

 11%|█         | 795/7483 [03:47<56:52,  1.96it/s]

 11%|█         | 795/7483 [03:47<56:52,  1.96it/s]
 11%|█         | 796/7483 [03:47<56:52,  1.96it/s]

 11%|█         | 797/7483 [03:48<52:06,  2.14it/s]

 11%|█         | 797/7483 [03:48<52:06,  2.14it/s]
 11%|█         | 798/7483 [03:48<52:05,  2.14it/s]

 11%|█         | 799/7483 [03:49<49:14,  2.26it/s]

 11%|█         | 799/7483 [03:49<49:14,  2.26it/s]
 11%|█         | 800/7483 [03:49<49:14,  2.26it/s]

 11%|█         | 801/7483 [03:50<46:56,  2.37it/s]

 11%|█         | 801/7483 [03:50<46:56,  2.37it/s]
 11%|█         | 802/7483 [03:50<46:56,  2.37it/s]

 11%|█         | 803/7483 [03:50<45:10,  2.46it/s]

 11%|█         | 803/7483 [03:50<45:10,  2.46it/s]
 11%|█         | 804/7483 [03:50<45:10,  2.46it/s]
 11%|█         | 805/7483 [03:50<45:10,  2.46it/s]
 11%|█         | 806/7483 [03:50<45:09,  2.46it/s]
 11%|█         | 807/7483 [03:50<45:09,  2.46it/s]
 11%|█         | 808/7483 [03:51<45:08,  2.46it/s]
 11%|█         | 809/7483 [03:51<45:08,  2.46it/s]
 11%|█         | 810/7483 [03:51<45:08,  2.46it/s]

 11%|█         | 811/7483 [03:51<23:39,  4.70it/s]

 11%|█         | 811/7483 [03:51<23:39,  4.70it/s]
 11%|█         | 812/7483 [03:51<23:39,  4.70it/s]

 11%|█         | 813/7483 [03:52<27:44,  4.01it/s]

 11%|█         | 813/7483 [03:52<27:44,  4.01it/s]
 11%|█         | 814/7483 [03:52<27:44,  4.01it/s]
 11%|█         | 815/7483 [03:52<27:44,  4.01it/s]

 11%|█         | 816/7483 [03:53<28:01,  3.96it/s]

 11%|█         | 816/7483 [03:53<28:01,  3.96it/s]
 11%|█         | 817/7483 [03:53<28:01,  3.96it/s]

 11%|█         | 818/7483 [03:54<30:52,  3.60it/s]

 11%|█         | 818/7483 [03:54<30:52,  3.60it/s]
 11%|█         | 819/7483 [03:54<30:52,  3.60it/s]

 11%|█         | 820/7483 [03:54<33:50,  3.28it/s]

 11%|█         | 820/7483 [03:54<33:50,  3.28it/s]
 11%|█         | 821/7483 [03:54<33:50,  3.28it/s]

 11%|█         | 822/7483 [03:55<36:21,  3.05it/s]

 11%|█         | 822/7483 [03:55<36:21,  3.05it/s]
 11%|█         | 823/7483 [03:55<36:21,  3.05it/s]

 11%|█         | 824/7483 [03:56<38:09,  2.91it/s]

 11%|█         | 824/7483 [03:56<38:09,  2.91it/s]
 11%|█         | 825/7483 [03:56<38:09,  2.91it/s]

 11%|█         | 826/7483 [03:59<1:13:31,  1.51it/s]

 11%|█         | 826/7483 [03:59<1:13:31,  1.51it/s]
 11%|█         | 827/7483 [03:59<1:13:30,  1.51it/s]

 11%|█         | 828/7483 [04:00<1:04:48,  1.71it/s]

 11%|█         | 828/7483 [04:00<1:04:48,  1.71it/s]
 11%|█         | 829/7483 [04:00<1:04:48,  1.71it/s]

 11%|█         | 830/7483 [04:00<58:13,  1.90it/s]

 11%|█         | 830/7483 [04:00<58:13,  1.90it/s]
 11%|█         | 831/7483 [04:01<58:13,  1.90it/s]

 11%|█         | 832/7483 [04:01<53:25,  2.07it/s]

 11%|█         | 832/7483 [04:01<53:25,  2.07it/s]
 11%|█         | 833/7483 [04:01<53:25,  2.07it/s]

 11%|█         | 834/7483 [04:02<49:22,  2.24it/s]

 11%|█         | 834/7483 [04:02<49:22,  2.24it/s]
 11%|█         | 835/7483 [04:02<49:21,  2.24it/s]

 11%|█         | 836/7483 [04:03<46:35,  2.38it/s]

 11%|█         | 836/7483 [04:03<46:35,  2.38it/s]
 11%|█         | 837/7483 [04:03<46:35,  2.38it/s]

 11%|█         | 838/7483 [04:03<44:40,  2.48it/s]

 11%|█         | 838/7483 [04:03<44:40,  2.48it/s]
 11%|█         | 839/7483 [04:03<44:40,  2.48it/s]

 11%|█         | 840/7483 [04:04<42:43,  2.59it/s]

 11%|█         | 840/7483 [04:04<42:43,  2.59it/s]
 11%|█         | 841/7483 [04:04<42:43,  2.59it/s]

 11%|█▏        | 842/7483 [04:05<41:53,  2.64it/s]

 11%|█▏        | 842/7483 [04:05<41:53,  2.64it/s]
 11%|█▏        | 843/7483 [04:05<41:53,  2.64it/s]

 11%|█▏        | 844/7483 [04:06<41:14,  2.68it/s]

 11%|█▏        | 844/7483 [04:06<41:14,  2.68it/s]
 11%|█▏        | 845/7483 [04:06<41:14,  2.68it/s]

 11%|█▏        | 846/7483 [04:06<40:09,  2.75it/s]

 11%|█▏        | 846/7483 [04:06<40:09,  2.75it/s]
 11%|█▏        | 847/7483 [04:06<40:09,  2.75it/s]

 11%|█▏        | 848/7483 [04:07<39:27,  2.80it/s]

 11%|█▏        | 848/7483 [04:07<39:27,  2.80it/s]
 11%|█▏        | 849/7483 [04:07<39:26,  2.80it/s]

 11%|█▏        | 850/7483 [04:08<39:02,  2.83it/s]

 11%|█▏        | 850/7483 [04:08<39:02,  2.83it/s]
 11%|█▏        | 851/7483 [04:08<39:02,  2.83it/s]

 11%|█▏        | 852/7483 [04:08<38:32,  2.87it/s]

 11%|█▏        | 852/7483 [04:08<38:32,  2.87it/s]
 11%|█▏        | 853/7483 [04:08<38:32,  2.87it/s]

 11%|█▏        | 854/7483 [04:11<1:07:21,  1.64it/s]

 11%|█▏        | 854/7483 [04:11<1:07:21,  1.64it/s]
 11%|█▏        | 855/7483 [04:11<1:07:20,  1.64it/s]

 11%|█▏        | 856/7483 [04:12<1:07:13,  1.64it/s]

 11%|█▏        | 856/7483 [04:12<1:07:13,  1.64it/s]
 11%|█▏        | 857/7483 [04:12<1:07:12,  1.64it/s]

 11%|█▏        | 858/7483 [04:13<57:57,  1.91it/s]

 11%|█▏        | 858/7483 [04:13<57:57,  1.91it/s]
 11%|█▏        | 859/7483 [04:13<57:56,  1.91it/s]
 11%|█▏        | 860/7483 [04:13<57:56,  1.91it/s]
 12%|█▏        | 861/7483 [04:13<57:55,  1.91it/s]

 12%|█▏        | 862/7483 [04:13<39:58,  2.76it/s]

 12%|█▏        | 862/7483 [04:13<39:58,  2.76it/s]
 12%|█▏        | 863/7483 [04:13<39:57,  2.76it/s]

 12%|█▏        | 864/7483 [04:14<38:56,  2.83it/s]

 12%|█▏        | 864/7483 [04:14<38:56,  2.83it/s]
 12%|█▏        | 865/7483 [04:14<38:56,  2.83it/s]

 12%|█▏        | 866/7483 [04:15<38:34,  2.86it/s]

 12%|█▏        | 866/7483 [04:15<38:34,  2.86it/s]
 12%|█▏        | 867/7483 [04:15<38:34,  2.86it/s]

 12%|█▏        | 868/7483 [04:15<38:20,  2.88it/s]

 12%|█▏        | 868/7483 [04:15<38:20,  2.88it/s]
 12%|█▏        | 869/7483 [04:15<38:20,  2.88it/s]

 12%|█▏        | 870/7483 [04:16<38:04,  2.89it/s]

 12%|█▏        | 870/7483 [04:16<38:04,  2.89it/s]
 12%|█▏        | 871/7483 [04:16<38:04,  2.89it/s]

 12%|█▏        | 872/7483 [04:17<37:53,  2.91it/s]

 12%|█▏        | 872/7483 [04:17<37:53,  2.91it/s]
 12%|█▏        | 873/7483 [04:17<37:53,  2.91it/s]

 12%|█▏        | 874/7483 [04:17<37:45,  2.92it/s]

 12%|█▏        | 874/7483 [04:17<37:45,  2.92it/s]
 12%|█▏        | 875/7483 [04:17<37:45,  2.92it/s]

 12%|█▏        | 876/7483 [04:18<37:42,  2.92it/s]

 12%|█▏        | 876/7483 [04:18<37:42,  2.92it/s]
 12%|█▏        | 877/7483 [04:18<37:42,  2.92it/s]
 12%|█▏        | 878/7483 [04:18<37:42,  2.92it/s]

 12%|█▏        | 879/7483 [04:19<32:05,  3.43it/s]

 12%|█▏        | 879/7483 [04:19<32:05,  3.43it/s]
 12%|█▏        | 880/7483 [04:19<32:05,  3.43it/s]

 12%|█▏        | 881/7483 [04:19<33:27,  3.29it/s]

 12%|█▏        | 881/7483 [04:19<33:27,  3.29it/s]
 12%|█▏        | 882/7483 [04:19<33:26,  3.29it/s]

 12%|█▏        | 883/7483 [04:20<34:15,  3.21it/s]

 12%|█▏        | 883/7483 [04:20<34:15,  3.21it/s]
 12%|█▏        | 884/7483 [04:20<34:15,  3.21it/s]

 12%|█▏        | 885/7483 [04:21<35:19,  3.11it/s]

 12%|█▏        | 885/7483 [04:21<35:19,  3.11it/s]
 12%|█▏        | 886/7483 [04:21<35:19,  3.11it/s]

 12%|█▏        | 887/7483 [04:21<35:49,  3.07it/s]

 12%|█▏        | 887/7483 [04:21<35:49,  3.07it/s]
 12%|█▏        | 888/7483 [04:21<35:49,  3.07it/s]

 12%|█▏        | 889/7483 [04:24<1:13:10,  1.50it/s]

 12%|█▏        | 889/7483 [04:24<1:13:10,  1.50it/s]
 12%|█▏        | 890/7483 [04:24<1:13:09,  1.50it/s]

 12%|█▏        | 891/7483 [04:25<1:02:05,  1.77it/s]

 12%|█▏        | 891/7483 [04:25<1:02:05,  1.77it/s]
 12%|█▏        | 892/7483 [04:25<1:02:05,  1.77it/s]

 12%|█▏        | 893/7483 [04:26<55:05,  1.99it/s]

 12%|█▏        | 893/7483 [04:26<55:05,  1.99it/s]
 12%|█▏        | 894/7483 [04:26<55:05,  1.99it/s]

 12%|█▏        | 895/7483 [04:26<49:47,  2.21it/s]

 12%|█▏        | 895/7483 [04:26<49:47,  2.21it/s]
 12%|█▏        | 896/7483 [04:26<49:46,  2.21it/s]

 12%|█▏        | 897/7483 [04:27<45:49,  2.40it/s]

 12%|█▏        | 897/7483 [04:27<45:49,  2.40it/s]
 12%|█▏        | 898/7483 [04:27<45:48,  2.40it/s]

 12%|█▏        | 899/7483 [04:28<43:51,  2.50it/s]

 12%|█▏        | 899/7483 [04:28<43:51,  2.50it/s]
 12%|█▏        | 900/7483 [04:28<43:50,  2.50it/s]

 12%|█▏        | 901/7483 [04:28<42:05,  2.61it/s]

 12%|█▏        | 901/7483 [04:28<42:05,  2.61it/s]
 12%|█▏        | 902/7483 [04:28<42:04,  2.61it/s]

 12%|█▏        | 903/7483 [04:29<40:18,  2.72it/s]

 12%|█▏        | 903/7483 [04:29<40:18,  2.72it/s]
 12%|█▏        | 904/7483 [04:29<40:18,  2.72it/s]
 12%|█▏        | 905/7483 [04:29<40:18,  2.72it/s]
 12%|█▏        | 906/7483 [04:29<40:17,  2.72it/s]
 12%|█▏        | 907/7483 [04:29<40:17,  2.72it/s]
 12%|█▏        | 908/7483 [04:29<40:17,  2.72it/s]
 12%|█▏        | 909/7483 [04:29<40:16,  2.72it/s]
 12%|█▏        | 910/7483 [04:29<40:16,  2.72it/s]

 12%|█▏        | 911/7483 [04:30<20:53,  5.24it/s]

 12%|█▏        | 911/7483 [04:30<20:53,  5.24it/s]
 12%|█▏        | 912/7483 [04:30<20:53,  5.24it/s]

 12%|█▏        | 913/7483 [04:30<23:47,  4.60it/s]

 12%|█▏        | 913/7483 [04:30<23:47,  4.60it/s]
 12%|█▏        | 914/7483 [04:30<23:47,  4.60it/s]
 12%|█▏        | 915/7483 [04:30<23:47,  4.60it/s]

 12%|█▏        | 916/7483 [04:31<23:28,  4.66it/s]

 12%|█▏        | 916/7483 [04:31<23:28,  4.66it/s]
 12%|█▏        | 917/7483 [04:31<23:27,  4.66it/s]
 12%|█▏        | 918/7483 [04:31<23:27,  4.66it/s]

 12%|█▏        | 919/7483 [04:32<23:40,  4.62it/s]

 12%|█▏        | 919/7483 [04:32<23:40,  4.62it/s]
 12%|█▏        | 920/7483 [04:32<23:40,  4.62it/s]

 12%|█▏        | 921/7483 [04:32<26:09,  4.18it/s]

 12%|█▏        | 921/7483 [04:32<26:09,  4.18it/s]
 12%|█▏        | 922/7483 [04:32<26:09,  4.18it/s]

 12%|█▏        | 923/7483 [04:33<28:38,  3.82it/s]

 12%|█▏        | 923/7483 [04:33<28:38,  3.82it/s]
 12%|█▏        | 924/7483 [04:33<28:37,  3.82it/s]

 12%|█▏        | 925/7483 [04:34<30:40,  3.56it/s]

 12%|█▏        | 925/7483 [04:34<30:40,  3.56it/s]
 12%|█▏        | 926/7483 [04:34<30:40,  3.56it/s]

 12%|█▏        | 927/7483 [04:37<1:05:00,  1.68it/s]

 12%|█▏        | 927/7483 [04:37<1:05:00,  1.68it/s]
 12%|█▏        | 928/7483 [04:37<1:04:59,  1.68it/s]

 12%|█▏        | 929/7483 [04:37<57:20,  1.90it/s]

 12%|█▏        | 929/7483 [04:37<57:20,  1.90it/s]
 12%|█▏        | 930/7483 [04:37<57:19,  1.90it/s]

 12%|█▏        | 931/7483 [04:38<51:20,  2.13it/s]

 12%|█▏        | 931/7483 [04:38<51:20,  2.13it/s]
 12%|█▏        | 932/7483 [04:38<51:20,  2.13it/s]

 12%|█▏        | 933/7483 [04:39<46:52,  2.33it/s]

 12%|█▏        | 933/7483 [04:39<46:52,  2.33it/s]
 12%|█▏        | 934/7483 [04:39<46:52,  2.33it/s]

 12%|█▏        | 935/7483 [04:39<44:02,  2.48it/s]

 12%|█▏        | 935/7483 [04:39<44:02,  2.48it/s]
 13%|█▎        | 936/7483 [04:39<44:02,  2.48it/s]

 13%|█▎        | 937/7483 [04:40<41:51,  2.61it/s]

 13%|█▎        | 937/7483 [04:40<41:51,  2.61it/s]
 13%|█▎        | 938/7483 [04:40<41:50,  2.61it/s]

 13%|█▎        | 939/7483 [04:41<39:54,  2.73it/s]

 13%|█▎        | 939/7483 [04:41<39:54,  2.73it/s]
 13%|█▎        | 940/7483 [04:41<39:54,  2.73it/s]

 13%|█▎        | 941/7483 [04:41<39:12,  2.78it/s]

 13%|█▎        | 941/7483 [04:41<39:12,  2.78it/s]
 13%|█▎        | 942/7483 [04:41<39:12,  2.78it/s]
 13%|█▎        | 943/7483 [04:41<39:11,  2.78it/s]

 13%|█▎        | 944/7483 [04:42<33:03,  3.30it/s]

 13%|█▎        | 944/7483 [04:42<33:03,  3.30it/s]
 13%|█▎        | 945/7483 [04:42<33:03,  3.30it/s]

 13%|█▎        | 946/7483 [04:43<33:47,  3.22it/s]

 13%|█▎        | 946/7483 [04:43<33:47,  3.22it/s]
 13%|█▎        | 947/7483 [04:43<33:47,  3.22it/s]

 13%|█▎        | 948/7483 [04:43<34:28,  3.16it/s]

 13%|█▎        | 948/7483 [04:43<34:28,  3.16it/s]
 13%|█▎        | 949/7483 [04:43<34:28,  3.16it/s]

 13%|█▎        | 950/7483 [04:44<34:43,  3.14it/s]

 13%|█▎        | 950/7483 [04:44<34:43,  3.14it/s]
 13%|█▎        | 951/7483 [04:44<34:43,  3.14it/s]

 13%|█▎        | 952/7483 [04:45<35:27,  3.07it/s]

 13%|█▎        | 952/7483 [04:45<35:27,  3.07it/s]
 13%|█▎        | 953/7483 [04:45<35:27,  3.07it/s]

 13%|█▎        | 954/7483 [04:45<35:39,  3.05it/s]

 13%|█▎        | 954/7483 [04:45<35:39,  3.05it/s]
 13%|█▎        | 955/7483 [04:45<35:39,  3.05it/s]

 13%|█▎        | 956/7483 [04:46<35:24,  3.07it/s]

 13%|█▎        | 956/7483 [04:46<35:24,  3.07it/s]
 13%|█▎        | 957/7483 [04:46<35:23,  3.07it/s]

 13%|█▎        | 958/7483 [04:47<37:39,  2.89it/s]

 13%|█▎        | 958/7483 [04:47<37:39,  2.89it/s]
 13%|█▎        | 959/7483 [04:47<37:38,  2.89it/s]
 13%|█▎        | 960/7483 [04:47<37:38,  2.89it/s]
 13%|█▎        | 961/7483 [04:47<37:38,  2.89it/s]

 13%|█▎        | 962/7483 [04:50<55:52,  1.95it/s]
 13%|█▎        | 970/7483 [04:50<24:57,  4.35it/s]

 13%|█▎        | 962/7483 [04:50<55:52,  1.95it/s]
 13%|█▎        | 963/7483 [04:50<55:51,  1.95it/s]
 13%|█▎        | 964/7483 [04:50<55:50,  1.95it/s]
 13%|█▎        | 965/7483 [04:50<55:50,  1.95it/s]
 13%|█▎        | 966/7483 [04:50<55:49,  1.95it/s]
 13%|█▎        | 967/7483 [04:50<55:49,  1.95it/s]
 13%|█▎        | 968/7483 [04:50<55:48,  1.95it/s]
 13%|█▎        | 969/7483 [04:50<55:48,  1.95it/s]
 13%|█▎        | 970/7483 [04:50<24:57,  4.35it/s]

 13%|█▎        | 973/7483 [04:50<24:28,  4.43it/s]

 13%|█▎        | 971/7483 [04:50<24:57,  4.35it/s]
 13%|█▎        | 972/7483 [04:50<24:56,  4.35it/s]
 13%|█▎        | 973/7483 [04:50<24:28,  4.43it/s]
 13%|█▎        | 974/7483 [04:50<24:28,  4.43it/s]

 13%|█▎        | 975/7483 [04:51<26:31,  4.09it/s]

 13%|█▎        | 975/7483 [04:51<26:31,  4.09it/s]
 13%|█▎        | 976/7483 [04:51<26:30,  4.09it/s]

 13%|█▎        | 977/7483 [04:52<28:33,  3.80it/s]

 13%|█▎        | 977/7483 [04:52<28:33,  3.80it/s]
 13%|█▎        | 978/7483 [04:52<28:33,  3.80it/s]

 13%|█▎        | 979/7483 [04:52<30:34,  3.54it/s]

 13%|█▎        | 979/7483 [04:52<30:34,  3.54it/s]
 13%|█▎        | 980/7483 [04:52<30:34,  3.54it/s]

 13%|█▎        | 981/7483 [04:53<31:58,  3.39it/s]

 13%|█▎        | 981/7483 [04:53<31:58,  3.39it/s]
 13%|█▎        | 982/7483 [04:53<31:58,  3.39it/s]

 13%|█▎        | 983/7483 [04:54<32:51,  3.30it/s]

 13%|█▎        | 983/7483 [04:54<32:51,  3.30it/s]
 13%|█▎        | 984/7483 [04:54<32:50,  3.30it/s]

 13%|█▎        | 985/7483 [04:54<33:24,  3.24it/s]

 13%|█▎        | 985/7483 [04:54<33:24,  3.24it/s]
 13%|█▎        | 986/7483 [04:54<33:24,  3.24it/s]

 13%|█▎        | 987/7483 [04:55<34:15,  3.16it/s]

 13%|█▎        | 987/7483 [04:55<34:15,  3.16it/s]
 13%|█▎        | 988/7483 [04:55<34:15,  3.16it/s]

 13%|█▎        | 989/7483 [04:56<34:20,  3.15it/s]

 13%|█▎        | 989/7483 [04:56<34:20,  3.15it/s]
 13%|█▎        | 990/7483 [04:56<34:20,  3.15it/s]

 13%|█▎        | 991/7483 [04:56<34:39,  3.12it/s]

 13%|█▎        | 991/7483 [04:56<34:39,  3.12it/s]
 13%|█▎        | 992/7483 [04:56<34:39,  3.12it/s]

 13%|█▎        | 993/7483 [04:57<34:53,  3.10it/s]

 13%|█▎        | 993/7483 [04:57<34:53,  3.10it/s]
 13%|█▎        | 994/7483 [04:57<34:53,  3.10it/s]
 13%|█▎        | 995/7483 [04:57<34:52,  3.10it/s]

 13%|█▎        | 996/7483 [04:58<30:21,  3.56it/s]

 13%|█▎        | 996/7483 [04:58<30:21,  3.56it/s]
 13%|█▎        | 997/7483 [04:58<30:21,  3.56it/s]

 13%|█▎        | 998/7483 [04:58<32:02,  3.37it/s]

 13%|█▎        | 998/7483 [04:58<32:02,  3.37it/s]
 13%|█▎        | 999/7483 [04:58<32:02,  3.37it/s]

 13%|█▎        | 1000/7483 [04:59<32:21,  3.34it/s]
 67%|██████▋   | 6/9 [28:26<14:32, 290.99s/it]

 13%|█▎        | 1000/7483 [04:59<33:01,  3.27it/s]
                     MLUT4_AT.232A  MLUT4_RQ.2BTLS  MLUT4_TE.252A  \
Time
2025-05-25 05:20:05       0.852984        0.855904       0.842414
2025-05-25 05:30:05       0.876511        0.874611       0.847393
2025-05-25 05:35:05       0.877479        0.885625       0.860507
2025-05-25 05:40:05       0.878625        0.849563       0.860377
2025-05-25 05:45:05       0.877141        0.871733       0.849503

                     MLUT4_SIV.B7921  MLUT4_AIA792101B  MLUT4_PDT.956  \
Time
2025-05-25 05:20:05         0.903258          0.872434       0.899219
2025-05-25 05:30:05         0.903158          0.872244       0.916372
2025-05-25 05:35:05         0.903349          0.872158       0.914016
2025-05-25 05:40:05         0.903300          0.872148       0.910043
2025-05-25 05:45:05         0.903219          0.872148       0.914286

                     MLUT4_TE.252F  MLUT4_PT.231  MLUT4_FIC.231C  \
Time
2025-05-25 05:20:05       0.887579      0.869354        0.857897
2025-05-25 05:30:05       0.879727      0.867235        0.857888
2025-05-25 05:35:05       0.893944      0.867041        0.857883
2025-05-25 05:40:05       0.872940      0.866275        0.857879
2025-05-25 05:45:05       0.876962      0.865383        0.857874

                     MLUT4_FIC.231A  ...  DeSOx_2nd  MLUT4_AIC.232B  \
Time                                 ...
2025-05-25 05:20:05        0.859975  ...   0.887614       85.012138
2025-05-25 05:30:05        0.856716  ...   0.886998       88.954571
2025-05-25 05:35:05        0.860662  ...   0.887576       93.745851
2025-05-25 05:40:05        0.859286  ...   0.887298       85.305571
2025-05-25 05:45:05        0.859582  ...   0.886243      101.874866

                     MLUT4_AT.240  prev_target  MLUT4_AT-240  prediction  \
Time
2025-05-25 05:20:05     14.151761     0.888806      9.554181    0.884520
2025-05-25 05:30:05      9.316637     0.890104     10.052046    0.884258
2025-05-25 05:35:05      6.155893     0.890862     10.539312    0.885075
2025-05-25 05:40:05     12.572007     0.891577      9.614145    0.885334
2025-05-25 05:45:05      5.497275     0.891864     11.588959    0.882460

                     abs_error  threshold  y3_prediction  y3_abs_error
Time
2025-05-25 05:20:05   0.003094   0.003094       9.817172      0.262991
2025-05-25 05:30:05   0.002740   0.003058      10.295793      0.243747
2025-05-25 05:35:05   0.002501   0.003023      10.773772      0.234461
2025-05-25 05:40:05   0.001963   0.002988       9.781607      0.167462
2025-05-25 05:45:05   0.003784   0.003508      11.974408      0.385450

[5 rows x 50 columns]

  0%|          | 0/7481 [00:00<?, ?it/s]

  0%|          | 0/7481 [00:00<?, ?it/s]

  0%|          | 1/7481 [00:00<1:15:54,  1.64it/s]

  0%|          | 1/7481 [00:00<1:15:54,  1.64it/s]
  0%|          | 2/7481 [00:00<1:15:53,  1.64it/s]

  0%|          | 3/7481 [00:01<48:55,  2.55it/s]

  0%|          | 3/7481 [00:01<48:55,  2.55it/s]
  0%|          | 4/7481 [00:01<48:55,  2.55it/s]

  0%|          | 5/7481 [00:01<43:30,  2.86it/s]

  0%|          | 5/7481 [00:01<43:30,  2.86it/s]
  0%|          | 6/7481 [00:01<43:30,  2.86it/s]

  0%|          | 7/7481 [00:02<41:55,  2.97it/s]

  0%|          | 7/7481 [00:02<41:55,  2.97it/s]
  0%|          | 8/7481 [00:02<41:55,  2.97it/s]

  0%|          | 9/7481 [00:03<41:19,  3.01it/s]

  0%|          | 9/7481 [00:03<41:19,  3.01it/s]
  0%|          | 10/7481 [00:03<41:19,  3.01it/s]

  0%|          | 11/7481 [00:03<39:48,  3.13it/s]

  0%|          | 11/7481 [00:03<39:48,  3.13it/s]
  0%|          | 12/7481 [00:03<39:48,  3.13it/s]
  0%|          | 13/7481 [00:03<39:47,  3.13it/s]
  0%|          | 14/7481 [00:03<39:47,  3.13it/s]
  0%|          | 15/7481 [00:03<39:47,  3.13it/s]
  0%|          | 16/7481 [00:03<39:46,  3.13it/s]
  0%|          | 17/7481 [00:03<39:46,  3.13it/s]

  0%|          | 18/7481 [00:04<21:52,  5.69it/s]

  0%|          | 18/7481 [00:04<21:52,  5.69it/s]
  0%|          | 19/7481 [00:04<21:52,  5.69it/s]

  0%|          | 20/7481 [00:05<25:14,  4.93it/s]

  0%|          | 20/7481 [00:05<25:14,  4.93it/s]
  0%|          | 21/7481 [00:05<25:14,  4.93it/s]

  0%|          | 22/7481 [00:05<28:12,  4.41it/s]

  0%|          | 22/7481 [00:05<28:12,  4.41it/s]
  0%|          | 23/7481 [00:05<28:12,  4.41it/s]
  0%|          | 24/7481 [00:05<28:12,  4.41it/s]

  0%|          | 25/7481 [00:06<27:18,  4.55it/s]

  0%|          | 25/7481 [00:06<27:18,  4.55it/s]
  0%|          | 26/7481 [00:06<27:18,  4.55it/s]

  0%|          | 27/7481 [00:06<30:06,  4.13it/s]

  0%|          | 27/7481 [00:06<30:06,  4.13it/s]
  0%|          | 28/7481 [00:06<30:06,  4.13it/s]

  0%|          | 29/7481 [00:07<32:46,  3.79it/s]

  0%|          | 29/7481 [00:07<32:46,  3.79it/s]
  0%|          | 30/7481 [00:07<32:46,  3.79it/s]

  0%|          | 31/7481 [00:08<36:02,  3.44it/s]

  0%|          | 31/7481 [00:08<36:02,  3.44it/s]
  0%|          | 32/7481 [00:08<36:02,  3.44it/s]

  0%|          | 33/7481 [00:11<1:14:02,  1.68it/s]
  1%|          | 46/7481 [00:11<21:28,  5.77it/s]

  0%|          | 33/7481 [00:11<1:14:02,  1.68it/s]
  0%|          | 34/7481 [00:11<1:14:02,  1.68it/s]
  0%|          | 35/7481 [00:11<1:14:01,  1.68it/s]
  0%|          | 36/7481 [00:11<1:14:00,  1.68it/s]
  0%|          | 37/7481 [00:11<1:14:00,  1.68it/s]
  1%|          | 38/7481 [00:11<1:13:59,  1.68it/s]
  1%|          | 39/7481 [00:11<1:13:59,  1.68it/s]
  1%|          | 40/7481 [00:11<1:13:58,  1.68it/s]
  1%|          | 41/7481 [00:11<1:13:57,  1.68it/s]
  1%|          | 42/7481 [00:11<1:13:57,  1.68it/s]
  1%|          | 43/7481 [00:11<1:13:56,  1.68it/s]
  1%|          | 44/7481 [00:11<1:13:56,  1.68it/s]
  1%|          | 45/7481 [00:11<1:13:55,  1.68it/s]
  1%|          | 46/7481 [00:11<21:28,  5.77it/s]
  1%|          | 47/7481 [00:11<21:28,  5.77it/s]
  1%|          | 48/7481 [00:11<21:28,  5.77it/s]
  1%|          | 49/7481 [00:12<21:27,  5.77it/s]
  1%|          | 50/7481 [00:12<21:27,  5.77it/s]

  1%|          | 51/7481 [00:12<27:50,  4.45it/s]

  1%|          | 51/7481 [00:12<27:50,  4.45it/s]
  1%|          | 52/7481 [00:12<27:50,  4.45it/s]

  1%|          | 54/7481 [00:13<28:02,  4.41it/s]

  1%|          | 53/7481 [00:13<27:50,  4.45it/s]
  1%|          | 54/7481 [00:13<28:02,  4.41it/s]
  1%|          | 55/7481 [00:14<28:02,  4.41it/s]
  1%|          | 56/7481 [00:14<28:01,  4.41it/s]

  1%|          | 57/7481 [00:14<33:07,  3.74it/s]

  1%|          | 57/7481 [00:14<33:07,  3.74it/s]
  1%|          | 58/7481 [00:14<33:06,  3.74it/s]

  1%|          | 59/7481 [00:15<34:13,  3.61it/s]

  1%|          | 59/7481 [00:15<34:13,  3.61it/s]
  1%|          | 60/7481 [00:15<34:13,  3.61it/s]

  1%|          | 61/7481 [00:16<35:35,  3.47it/s]

  1%|          | 61/7481 [00:16<35:35,  3.47it/s]
  1%|          | 62/7481 [00:16<35:35,  3.47it/s]

  1%|          | 63/7481 [00:16<36:28,  3.39it/s]

  1%|          | 63/7481 [00:16<36:28,  3.39it/s]
  1%|          | 64/7481 [00:16<36:27,  3.39it/s]

  1%|          | 65/7481 [00:17<37:03,  3.34it/s]

  1%|          | 65/7481 [00:17<37:03,  3.34it/s]
  1%|          | 66/7481 [00:17<37:03,  3.34it/s]

  1%|          | 67/7481 [00:18<38:48,  3.18it/s]

  1%|          | 67/7481 [00:18<38:48,  3.18it/s]
  1%|          | 68/7481 [00:18<38:48,  3.18it/s]

  1%|          | 69/7481 [00:18<38:42,  3.19it/s]

  1%|          | 69/7481 [00:18<38:42,  3.19it/s]
  1%|          | 70/7481 [00:18<38:42,  3.19it/s]
  1%|          | 71/7481 [00:18<38:42,  3.19it/s]

  1%|          | 72/7481 [00:19<34:43,  3.56it/s]

  1%|          | 72/7481 [00:19<34:43,  3.56it/s]
  1%|          | 73/7481 [00:19<34:43,  3.56it/s]
  1%|          | 74/7481 [00:19<34:43,  3.56it/s]

  1%|          | 75/7481 [00:20<32:22,  3.81it/s]

  1%|          | 75/7481 [00:20<32:22,  3.81it/s]
  1%|          | 76/7481 [00:20<32:22,  3.81it/s]

  1%|          | 77/7481 [00:20<35:08,  3.51it/s]

  1%|          | 77/7481 [00:20<35:08,  3.51it/s]
  1%|          | 78/7481 [00:20<35:07,  3.51it/s]

  1%|          | 79/7481 [00:23<1:11:57,  1.71it/s]

  1%|          | 79/7481 [00:23<1:11:57,  1.71it/s]
  1%|          | 80/7481 [00:23<1:11:57,  1.71it/s]

  1%|          | 81/7481 [00:24<1:04:11,  1.92it/s]

  1%|          | 81/7481 [00:24<1:04:11,  1.92it/s]
  1%|          | 82/7481 [00:24<1:04:10,  1.92it/s]

  1%|          | 83/7481 [00:25<57:59,  2.13it/s]

  1%|          | 83/7481 [00:25<57:59,  2.13it/s]
  1%|          | 84/7481 [00:25<57:59,  2.13it/s]
  1%|          | 85/7481 [00:25<57:59,  2.13it/s]

  1%|          | 86/7481 [00:25<47:35,  2.59it/s]

  1%|          | 86/7481 [00:25<47:35,  2.59it/s]
  1%|          | 87/7481 [00:25<47:35,  2.59it/s]

  1%|          | 88/7481 [00:26<47:01,  2.62it/s]

  1%|          | 88/7481 [00:26<47:01,  2.62it/s]
  1%|          | 89/7481 [00:26<47:00,  2.62it/s]
  1%|          | 90/7481 [00:26<47:00,  2.62it/s]

  1%|          | 91/7481 [00:27<41:24,  2.97it/s]

  1%|          | 91/7481 [00:27<41:24,  2.97it/s]
  1%|          | 92/7481 [00:27<41:24,  2.97it/s]

  1%|          | 93/7481 [00:28<42:25,  2.90it/s]

  1%|          | 93/7481 [00:28<42:25,  2.90it/s]
  1%|▏         | 94/7481 [00:28<42:24,  2.90it/s]

  1%|▏         | 95/7481 [00:28<43:40,  2.82it/s]

  1%|▏         | 95/7481 [00:28<43:40,  2.82it/s]
  1%|▏         | 96/7481 [00:28<43:39,  2.82it/s]

  1%|▏         | 97/7481 [00:29<44:19,  2.78it/s]

  1%|▏         | 97/7481 [00:29<44:19,  2.78it/s]
  1%|▏         | 98/7481 [00:29<44:19,  2.78it/s]

  1%|▏         | 99/7481 [00:30<44:02,  2.79it/s]

  1%|▏         | 99/7481 [00:30<44:02,  2.79it/s]
  1%|▏         | 100/7481 [00:30<44:02,  2.79it/s]
  1%|▏         | 101/7481 [00:30<44:02,  2.79it/s]
  1%|▏         | 102/7481 [00:30<44:01,  2.79it/s]
  1%|▏         | 103/7481 [00:30<44:01,  2.79it/s]

  1%|▏         | 104/7481 [00:31<31:02,  3.96it/s]

  1%|▏         | 104/7481 [00:31<31:02,  3.96it/s]
  1%|▏         | 105/7481 [00:31<31:01,  3.96it/s]

  1%|▏         | 106/7481 [00:31<33:59,  3.62it/s]

  1%|▏         | 106/7481 [00:31<33:59,  3.62it/s]
  1%|▏         | 107/7481 [00:31<33:58,  3.62it/s]

  1%|▏         | 108/7481 [00:32<35:53,  3.42it/s]

  1%|▏         | 108/7481 [00:32<35:53,  3.42it/s]
  1%|▏         | 109/7481 [00:32<35:53,  3.42it/s]

  1%|▏         | 110/7481 [00:33<37:58,  3.24it/s]

  1%|▏         | 110/7481 [00:33<37:58,  3.24it/s]
  1%|▏         | 111/7481 [00:33<37:57,  3.24it/s]
  1%|▏         | 112/7481 [00:33<37:57,  3.24it/s]

  2%|▏         | 113/7481 [00:36<1:07:55,  1.81it/s]

  2%|▏         | 113/7481 [00:36<1:07:55,  1.81it/s]
  2%|▏         | 114/7481 [00:36<1:07:54,  1.81it/s]

  2%|▏         | 115/7481 [00:36<1:02:00,  1.98it/s]

  2%|▏         | 115/7481 [00:36<1:02:00,  1.98it/s]
  2%|▏         | 116/7481 [00:36<1:01:59,  1.98it/s]

  2%|▏         | 117/7481 [00:37<57:05,  2.15it/s]

  2%|▏         | 117/7481 [00:37<57:05,  2.15it/s]
  2%|▏         | 118/7481 [00:37<57:04,  2.15it/s]

  2%|▏         | 119/7481 [00:38<53:49,  2.28it/s]

  2%|▏         | 119/7481 [00:38<53:49,  2.28it/s]
  2%|▏         | 120/7481 [00:38<53:49,  2.28it/s]

  2%|▏         | 121/7481 [00:39<51:23,  2.39it/s]

  2%|▏         | 121/7481 [00:39<51:23,  2.39it/s]
  2%|▏         | 122/7481 [00:39<51:23,  2.39it/s]
  2%|▏         | 123/7481 [00:39<51:23,  2.39it/s]
  2%|▏         | 124/7481 [00:39<51:22,  2.39it/s]
  2%|▏         | 125/7481 [00:39<51:22,  2.39it/s]
  2%|▏         | 126/7481 [00:39<51:21,  2.39it/s]
  2%|▏         | 127/7481 [00:39<51:21,  2.39it/s]

  2%|▏         | 128/7481 [00:39<28:09,  4.35it/s]

  2%|▏         | 128/7481 [00:39<28:09,  4.35it/s]
  2%|▏         | 129/7481 [00:39<28:08,  4.35it/s]

  2%|▏         | 130/7481 [00:40<30:56,  3.96it/s]

  2%|▏         | 130/7481 [00:40<30:56,  3.96it/s]
  2%|▏         | 131/7481 [00:40<30:56,  3.96it/s]

  2%|▏         | 132/7481 [00:41<34:00,  3.60it/s]

  2%|▏         | 132/7481 [00:41<34:00,  3.60it/s]
  2%|▏         | 133/7481 [00:41<33:59,  3.60it/s]
  2%|▏         | 134/7481 [00:41<33:59,  3.60it/s]
  2%|▏         | 135/7481 [00:41<33:59,  3.60it/s]
  2%|▏         | 136/7481 [00:41<33:58,  3.60it/s]

  2%|▏         | 137/7481 [00:41<26:32,  4.61it/s]

  2%|▏         | 137/7481 [00:41<26:32,  4.61it/s]
  2%|▏         | 138/7481 [00:41<26:32,  4.61it/s]
  2%|▏         | 139/7481 [00:41<26:32,  4.61it/s]

  2%|▏         | 140/7481 [00:42<26:47,  4.57it/s]

  2%|▏         | 140/7481 [00:42<26:47,  4.57it/s]
  2%|▏         | 141/7481 [00:42<26:47,  4.57it/s]
  2%|▏         | 142/7481 [00:42<26:46,  4.57it/s]

  2%|▏         | 143/7481 [00:43<27:12,  4.50it/s]

  2%|▏         | 143/7481 [00:43<27:12,  4.50it/s]
  2%|▏         | 144/7481 [00:43<27:12,  4.50it/s]

  2%|▏         | 145/7481 [00:43<29:51,  4.10it/s]

  2%|▏         | 145/7481 [00:43<29:51,  4.10it/s]
  2%|▏         | 146/7481 [00:43<29:50,  4.10it/s]

  2%|▏         | 147/7481 [00:44<32:54,  3.71it/s]

  2%|▏         | 147/7481 [00:44<32:54,  3.71it/s]
  2%|▏         | 148/7481 [00:44<32:53,  3.71it/s]

  2%|▏         | 149/7481 [00:45<35:20,  3.46it/s]

  2%|▏         | 149/7481 [00:45<35:20,  3.46it/s]
  2%|▏         | 150/7481 [00:45<35:20,  3.46it/s]

  2%|▏         | 151/7481 [00:45<36:28,  3.35it/s]

  2%|▏         | 151/7481 [00:45<36:28,  3.35it/s]
  2%|▏         | 152/7481 [00:45<36:28,  3.35it/s]
  2%|▏         | 153/7481 [00:45<36:28,  3.35it/s]

  2%|▏         | 154/7481 [00:49<1:08:17,  1.79it/s]

  2%|▏         | 154/7481 [00:49<1:08:17,  1.79it/s]
  2%|▏         | 155/7481 [00:49<1:08:17,  1.79it/s]

  2%|▏         | 156/7481 [00:49<1:01:13,  1.99it/s]

  2%|▏         | 156/7481 [00:49<1:01:13,  1.99it/s]
  2%|▏         | 157/7481 [00:49<1:01:12,  1.99it/s]

  2%|▏         | 158/7481 [00:50<55:32,  2.20it/s]

  2%|▏         | 158/7481 [00:50<55:32,  2.20it/s]
  2%|▏         | 159/7481 [00:50<55:31,  2.20it/s]

  2%|▏         | 160/7481 [00:51<52:08,  2.34it/s]

  2%|▏         | 160/7481 [00:51<52:08,  2.34it/s]
  2%|▏         | 161/7481 [00:51<52:08,  2.34it/s]

  2%|▏         | 162/7481 [00:51<49:20,  2.47it/s]

  2%|▏         | 162/7481 [00:51<49:20,  2.47it/s]
  2%|▏         | 163/7481 [00:51<49:19,  2.47it/s]

  2%|▏         | 164/7481 [00:52<47:01,  2.59it/s]

  2%|▏         | 164/7481 [00:52<47:01,  2.59it/s]
  2%|▏         | 165/7481 [00:52<47:01,  2.59it/s]

  2%|▏         | 166/7481 [00:53<45:30,  2.68it/s]

  2%|▏         | 166/7481 [00:53<45:30,  2.68it/s]
  2%|▏         | 167/7481 [00:53<45:30,  2.68it/s]

  2%|▏         | 168/7481 [00:53<44:36,  2.73it/s]

  2%|▏         | 168/7481 [00:53<44:36,  2.73it/s]
  2%|▏         | 169/7481 [00:53<44:35,  2.73it/s]

  2%|▏         | 170/7481 [00:54<43:45,  2.78it/s]
  2%|▏         | 176/7481 [00:54<20:26,  5.96it/s]
  2%|▏         | 181/7481 [00:54<13:16,  9.17it/s]

  2%|▏         | 170/7481 [00:54<43:45,  2.78it/s]
  2%|▏         | 171/7481 [00:54<43:45,  2.78it/s]
  2%|▏         | 172/7481 [00:54<43:45,  2.78it/s]
  2%|▏         | 173/7481 [00:54<43:44,  2.78it/s]
  2%|▏         | 174/7481 [00:54<43:44,  2.78it/s]
  2%|▏         | 175/7481 [00:54<43:44,  2.78it/s]
  2%|▏         | 176/7481 [00:54<20:26,  5.96it/s]
  2%|▏         | 177/7481 [00:54<20:26,  5.96it/s]
  2%|▏         | 178/7481 [00:54<20:26,  5.96it/s]
  2%|▏         | 179/7481 [00:54<20:26,  5.96it/s]
  2%|▏         | 180/7481 [00:54<20:26,  5.96it/s]
  2%|▏         | 181/7481 [00:54<13:16,  9.17it/s]

  2%|▏         | 187/7481 [00:54<08:46, 13.85it/s]
  3%|▎         | 192/7481 [00:54<06:45, 17.97it/s]

  2%|▏         | 182/7481 [00:54<13:16,  9.17it/s]
  2%|▏         | 183/7481 [00:54<13:15,  9.17it/s]
  2%|▏         | 184/7481 [00:54<13:15,  9.17it/s]
  2%|▏         | 185/7481 [00:54<13:15,  9.17it/s]
  2%|▏         | 186/7481 [00:54<13:15,  9.17it/s]
  2%|▏         | 187/7481 [00:54<08:46, 13.85it/s]
  3%|▎         | 188/7481 [00:54<08:46, 13.85it/s]
  3%|▎         | 189/7481 [00:54<08:46, 13.85it/s]
  3%|▎         | 190/7481 [00:54<08:46, 13.85it/s]
  3%|▎         | 191/7481 [00:54<08:46, 13.85it/s]
  3%|▎         | 192/7481 [00:54<06:45, 17.97it/s]

  3%|▎         | 201/7481 [00:54<04:18, 28.16it/s]

  3%|▎         | 193/7481 [00:54<06:45, 17.97it/s]
  3%|▎         | 194/7481 [00:54<06:45, 17.97it/s]
  3%|▎         | 195/7481 [00:54<06:45, 17.97it/s]
  3%|▎         | 196/7481 [00:54<06:45, 17.97it/s]
  3%|▎         | 197/7481 [00:54<06:45, 17.97it/s]
  3%|▎         | 198/7481 [00:54<06:45, 17.97it/s]
  3%|▎         | 199/7481 [00:54<06:45, 17.97it/s]
  3%|▎         | 200/7481 [00:54<06:45, 17.97it/s]
  3%|▎         | 201/7481 [00:55<04:18, 28.16it/s]
  3%|▎         | 202/7481 [00:55<04:18, 28.16it/s]
  3%|▎         | 203/7481 [00:55<04:18, 28.16it/s]
  3%|▎         | 204/7481 [00:55<04:18, 28.16it/s]
  3%|▎         | 205/7481 [00:55<04:18, 28.16it/s]
  3%|▎         | 206/7481 [00:55<04:18, 28.16it/s]

  3%|▎         | 207/7481 [00:55<03:42, 32.66it/s]
  3%|▎         | 213/7481 [00:55<03:23, 35.79it/s]

  3%|▎         | 207/7481 [00:55<03:42, 32.66it/s]
  3%|▎         | 208/7481 [00:55<03:42, 32.66it/s]
  3%|▎         | 209/7481 [00:55<03:42, 32.66it/s]
  3%|▎         | 210/7481 [00:55<03:42, 32.66it/s]
  3%|▎         | 211/7481 [00:55<03:42, 32.66it/s]
  3%|▎         | 212/7481 [00:55<03:42, 32.66it/s]
  3%|▎         | 213/7481 [00:55<03:23, 35.79it/s]
  3%|▎         | 214/7481 [00:55<03:23, 35.79it/s]
  3%|▎         | 215/7481 [00:55<03:23, 35.79it/s]
  3%|▎         | 216/7481 [00:55<03:23, 35.79it/s]

  3%|▎         | 219/7481 [00:55<03:06, 39.00it/s]

  3%|▎         | 217/7481 [00:55<03:22, 35.79it/s]
  3%|▎         | 218/7481 [00:55<03:22, 35.79it/s]
  3%|▎         | 219/7481 [00:55<03:06, 39.00it/s]
  3%|▎         | 220/7481 [00:55<03:06, 39.00it/s]
  3%|▎         | 221/7481 [00:55<03:06, 39.00it/s]
  3%|▎         | 222/7481 [00:55<03:06, 39.00it/s]
  3%|▎         | 223/7481 [00:56<03:06, 39.00it/s]
  3%|▎         | 224/7481 [00:56<03:06, 39.00it/s]

  3%|▎         | 225/7481 [00:56<11:18, 10.70it/s]

  3%|▎         | 225/7481 [00:56<11:18, 10.70it/s]
  3%|▎         | 226/7481 [00:56<11:18, 10.70it/s]
  3%|▎         | 227/7481 [00:56<11:18, 10.70it/s]
  3%|▎         | 228/7481 [00:56<11:18, 10.70it/s]
  3%|▎         | 229/7481 [00:56<11:18, 10.70it/s]
  3%|▎         | 230/7481 [00:56<11:17, 10.70it/s]
  3%|▎         | 231/7481 [00:56<11:17, 10.70it/s]
  3%|▎         | 232/7481 [00:56<11:17, 10.70it/s]
  3%|▎         | 233/7481 [00:56<11:17, 10.70it/s]
  3%|▎         | 234/7481 [00:56<11:17, 10.70it/s]
  3%|▎         | 235/7481 [00:56<11:17, 10.70it/s]

  3%|▎         | 236/7481 [00:57<09:50, 12.27it/s]

  3%|▎         | 236/7481 [00:57<09:50, 12.27it/s]
  3%|▎         | 237/7481 [00:57<09:50, 12.27it/s]

  3%|▎         | 240/7481 [00:58<12:09,  9.93it/s]

  3%|▎         | 238/7481 [00:58<09:50, 12.27it/s]
  3%|▎         | 239/7481 [00:58<09:50, 12.27it/s]
  3%|▎         | 240/7481 [00:58<12:09,  9.93it/s]
  3%|▎         | 241/7481 [01:01<12:08,  9.93it/s]
  3%|▎         | 242/7481 [01:01<12:08,  9.93it/s]

  3%|▎         | 243/7481 [01:02<34:55,  3.45it/s]

  3%|▎         | 243/7481 [01:02<34:55,  3.45it/s]
  3%|▎         | 244/7481 [01:02<34:54,  3.45it/s]

  3%|▎         | 245/7481 [01:02<35:54,  3.36it/s]

  3%|▎         | 245/7481 [01:02<35:54,  3.36it/s]
  3%|▎         | 246/7481 [01:02<35:54,  3.36it/s]

  3%|▎         | 247/7481 [01:03<37:06,  3.25it/s]

  3%|▎         | 247/7481 [01:03<37:06,  3.25it/s]
  3%|▎         | 248/7481 [01:03<37:06,  3.25it/s]

  3%|▎         | 249/7481 [01:04<38:13,  3.15it/s]

  3%|▎         | 249/7481 [01:04<38:13,  3.15it/s]
  3%|▎         | 250/7481 [01:04<38:13,  3.15it/s]

  3%|▎         | 251/7481 [01:04<39:11,  3.08it/s]

  3%|▎         | 251/7481 [01:04<39:11,  3.08it/s]
  3%|▎         | 252/7481 [01:04<39:10,  3.08it/s]

  3%|▎         | 253/7481 [01:05<39:55,  3.02it/s]

  3%|▎         | 253/7481 [01:05<39:55,  3.02it/s]
  3%|▎         | 254/7481 [01:05<39:54,  3.02it/s]

  3%|▎         | 255/7481 [01:06<40:35,  2.97it/s]

  3%|▎         | 255/7481 [01:06<40:35,  2.97it/s]
  3%|▎         | 256/7481 [01:06<40:35,  2.97it/s]

  3%|▎         | 257/7481 [01:06<40:52,  2.95it/s]
  3%|▎         | 261/7481 [01:07<24:39,  4.88it/s]

  3%|▎         | 257/7481 [01:06<40:52,  2.95it/s]
  3%|▎         | 258/7481 [01:07<40:52,  2.95it/s]
  3%|▎         | 259/7481 [01:07<40:52,  2.95it/s]
  3%|▎         | 260/7481 [01:07<40:51,  2.95it/s]
  3%|▎         | 261/7481 [01:07<24:39,  4.88it/s]
  4%|▎         | 262/7481 [01:07<24:39,  4.88it/s]

  4%|▎         | 263/7481 [01:07<28:44,  4.19it/s]

  4%|▎         | 263/7481 [01:07<28:44,  4.19it/s]
  4%|▎         | 264/7481 [01:07<28:44,  4.19it/s]

  4%|▎         | 265/7481 [01:08<32:08,  3.74it/s]

  4%|▎         | 265/7481 [01:08<32:08,  3.74it/s]
  4%|▎         | 266/7481 [01:08<32:08,  3.74it/s]

  4%|▎         | 267/7481 [01:09<34:25,  3.49it/s]

  4%|▎         | 267/7481 [01:09<34:25,  3.49it/s]
  4%|▎         | 268/7481 [01:09<34:24,  3.49it/s]
  4%|▎         | 269/7481 [01:09<34:24,  3.49it/s]

  4%|▎         | 270/7481 [01:09<32:36,  3.69it/s]

  4%|▎         | 270/7481 [01:09<32:36,  3.69it/s]
  4%|▎         | 271/7481 [01:09<32:36,  3.69it/s]

  4%|▎         | 272/7481 [01:10<35:28,  3.39it/s]

  4%|▎         | 272/7481 [01:10<35:28,  3.39it/s]
  4%|▎         | 273/7481 [01:10<35:28,  3.39it/s]

  4%|▎         | 274/7481 [01:11<39:22,  3.05it/s]

  4%|▎         | 274/7481 [01:11<39:22,  3.05it/s]
  4%|▎         | 275/7481 [01:11<39:22,  3.05it/s]

  4%|▎         | 276/7481 [01:14<1:16:28,  1.57it/s]

  4%|▎         | 276/7481 [01:14<1:16:28,  1.57it/s]
  4%|▎         | 277/7481 [01:14<1:16:27,  1.57it/s]

  4%|▎         | 278/7481 [01:15<1:07:18,  1.78it/s]

  4%|▎         | 278/7481 [01:15<1:07:18,  1.78it/s]
  4%|▎         | 279/7481 [01:15<1:07:18,  1.78it/s]

  4%|▎         | 280/7481 [01:15<1:00:30,  1.98it/s]
  4%|▍         | 284/7481 [01:15<34:35,  3.47it/s]

  4%|▎         | 280/7481 [01:15<1:00:30,  1.98it/s]
  4%|▍         | 281/7481 [01:15<1:00:30,  1.98it/s]
  4%|▍         | 282/7481 [01:15<1:00:29,  1.98it/s]
  4%|▍         | 283/7481 [01:15<1:00:29,  1.98it/s]
  4%|▍         | 284/7481 [01:15<34:35,  3.47it/s]
  4%|▍         | 285/7481 [01:15<34:34,  3.47it/s]

  4%|▍         | 286/7481 [01:16<36:42,  3.27it/s]

  4%|▍         | 286/7481 [01:16<36:42,  3.27it/s]
  4%|▍         | 287/7481 [01:16<36:42,  3.27it/s]
  4%|▍         | 288/7481 [01:16<36:42,  3.27it/s]
  4%|▍         | 289/7481 [01:16<36:41,  3.27it/s]

  4%|▍         | 290/7481 [01:17<30:50,  3.89it/s]

  4%|▍         | 290/7481 [01:17<30:50,  3.89it/s]
  4%|▍         | 291/7481 [01:17<30:50,  3.89it/s]

  4%|▍         | 292/7481 [01:18<36:02,  3.32it/s]

  4%|▍         | 292/7481 [01:18<36:02,  3.32it/s]
  4%|▍         | 293/7481 [01:18<36:02,  3.32it/s]

  4%|▍         | 294/7481 [01:19<38:04,  3.15it/s]

  4%|▍         | 294/7481 [01:19<38:04,  3.15it/s]
  4%|▍         | 295/7481 [01:19<38:03,  3.15it/s]

  4%|▍         | 296/7481 [01:19<39:32,  3.03it/s]

  4%|▍         | 296/7481 [01:19<39:32,  3.03it/s]
  4%|▍         | 297/7481 [01:19<39:32,  3.03it/s]

  4%|▍         | 298/7481 [01:20<40:48,  2.93it/s]

  4%|▍         | 298/7481 [01:20<40:48,  2.93it/s]
  4%|▍         | 299/7481 [01:20<40:48,  2.93it/s]

  4%|▍         | 300/7481 [01:21<41:46,  2.87it/s]

  4%|▍         | 300/7481 [01:21<41:46,  2.87it/s]
  4%|▍         | 301/7481 [01:21<41:45,  2.87it/s]

  4%|▍         | 302/7481 [01:22<42:53,  2.79it/s]

  4%|▍         | 302/7481 [01:22<42:53,  2.79it/s]
  4%|▍         | 303/7481 [01:22<42:52,  2.79it/s]

  4%|▍         | 304/7481 [01:22<43:03,  2.78it/s]

  4%|▍         | 304/7481 [01:22<43:03,  2.78it/s]
  4%|▍         | 305/7481 [01:22<43:03,  2.78it/s]

  4%|▍         | 306/7481 [01:23<43:05,  2.77it/s]

  4%|▍         | 306/7481 [01:23<43:05,  2.77it/s]
  4%|▍         | 307/7481 [01:23<43:05,  2.77it/s]

  4%|▍         | 308/7481 [01:25<1:07:24,  1.77it/s]

  4%|▍         | 308/7481 [01:25<1:07:24,  1.77it/s]
  4%|▍         | 309/7481 [01:25<1:07:23,  1.77it/s]

  4%|▍         | 310/7481 [01:27<1:16:13,  1.57it/s]

  4%|▍         | 310/7481 [01:27<1:16:13,  1.57it/s]
  4%|▍         | 311/7481 [01:27<1:16:12,  1.57it/s]

  4%|▍         | 312/7481 [01:27<1:06:31,  1.80it/s]

  4%|▍         | 312/7481 [01:27<1:06:31,  1.80it/s]
  4%|▍         | 313/7481 [01:27<1:06:31,  1.80it/s]
  4%|▍         | 314/7481 [01:27<1:06:30,  1.80it/s]

  4%|▍         | 315/7481 [01:28<52:14,  2.29it/s]

  4%|▍         | 315/7481 [01:28<52:14,  2.29it/s]
  4%|▍         | 316/7481 [01:28<52:14,  2.29it/s]

  4%|▍         | 317/7481 [01:29<50:11,  2.38it/s]

  4%|▍         | 317/7481 [01:29<50:11,  2.38it/s]
  4%|▍         | 318/7481 [01:29<50:10,  2.38it/s]

  4%|▍         | 319/7481 [01:30<47:43,  2.50it/s]

  4%|▍         | 319/7481 [01:30<47:43,  2.50it/s]
  4%|▍         | 320/7481 [01:30<47:42,  2.50it/s]

  4%|▍         | 321/7481 [01:30<45:54,  2.60it/s]

  4%|▍         | 321/7481 [01:30<45:54,  2.60it/s]
  4%|▍         | 322/7481 [01:30<45:54,  2.60it/s]

  4%|▍         | 323/7481 [01:31<45:08,  2.64it/s]

  4%|▍         | 323/7481 [01:31<45:08,  2.64it/s]
  4%|▍         | 324/7481 [01:31<45:08,  2.64it/s]
  4%|▍         | 325/7481 [01:31<45:07,  2.64it/s]
  4%|▍         | 326/7481 [01:31<45:07,  2.64it/s]

  4%|▍         | 327/7481 [01:32<34:15,  3.48it/s]

  4%|▍         | 327/7481 [01:32<34:15,  3.48it/s]
  4%|▍         | 328/7481 [01:32<34:15,  3.48it/s]

  4%|▍         | 329/7481 [01:32<36:32,  3.26it/s]

  4%|▍         | 329/7481 [01:32<36:32,  3.26it/s]
  4%|▍         | 330/7481 [01:32<36:32,  3.26it/s]

  4%|▍         | 331/7481 [01:33<39:01,  3.05it/s]

  4%|▍         | 331/7481 [01:33<39:01,  3.05it/s]
  4%|▍         | 332/7481 [01:33<39:01,  3.05it/s]
  4%|▍         | 333/7481 [01:33<39:00,  3.05it/s]
  4%|▍         | 334/7481 [01:33<39:00,  3.05it/s]
  4%|▍         | 335/7481 [01:33<39:00,  3.05it/s]
  4%|▍         | 336/7481 [01:33<38:59,  3.05it/s]
  5%|▍         | 337/7481 [01:33<38:59,  3.05it/s]

  5%|▍         | 338/7481 [01:34<24:04,  4.94it/s]

  5%|▍         | 338/7481 [01:34<24:04,  4.94it/s]
  5%|▍         | 339/7481 [01:34<24:04,  4.94it/s]

  5%|▍         | 340/7481 [01:35<28:07,  4.23it/s]

  5%|▍         | 340/7481 [01:35<28:07,  4.23it/s]
  5%|▍         | 341/7481 [01:35<28:07,  4.23it/s]

  5%|▍         | 342/7481 [01:36<31:46,  3.74it/s]

  5%|▍         | 342/7481 [01:36<31:46,  3.74it/s]
  5%|▍         | 343/7481 [01:36<31:46,  3.74it/s]

  5%|▍         | 344/7481 [01:36<34:53,  3.41it/s]

  5%|▍         | 344/7481 [01:36<34:53,  3.41it/s]
  5%|▍         | 345/7481 [01:36<34:53,  3.41it/s]

  5%|▍         | 346/7481 [01:39<1:11:29,  1.66it/s]

  5%|▍         | 346/7481 [01:39<1:11:29,  1.66it/s]
  5%|▍         | 347/7481 [01:39<1:11:28,  1.66it/s]

  5%|▍         | 348/7481 [01:40<1:05:09,  1.82it/s]

  5%|▍         | 348/7481 [01:40<1:05:09,  1.82it/s]
  5%|▍         | 349/7481 [01:40<1:05:08,  1.82it/s]
  5%|▍         | 350/7481 [01:40<1:05:08,  1.82it/s]

  5%|▍         | 351/7481 [01:41<53:01,  2.24it/s]

  5%|▍         | 351/7481 [01:41<53:01,  2.24it/s]
  5%|▍         | 352/7481 [01:41<53:00,  2.24it/s]

  5%|▍         | 353/7481 [01:42<51:28,  2.31it/s]

  5%|▍         | 353/7481 [01:42<51:28,  2.31it/s]
  5%|▍         | 354/7481 [01:42<51:28,  2.31it/s]

  5%|▍         | 355/7481 [01:42<49:34,  2.40it/s]

  5%|▍         | 355/7481 [01:42<49:34,  2.40it/s]
  5%|▍         | 356/7481 [01:43<49:34,  2.40it/s]

  5%|▍         | 357/7481 [01:43<48:53,  2.43it/s]

  5%|▍         | 357/7481 [01:43<48:53,  2.43it/s]
  5%|▍         | 358/7481 [01:43<48:52,  2.43it/s]

  5%|▍         | 359/7481 [01:44<48:04,  2.47it/s]

  5%|▍         | 359/7481 [01:44<48:04,  2.47it/s]
  5%|▍         | 360/7481 [01:44<48:03,  2.47it/s]

  5%|▍         | 361/7481 [01:45<47:37,  2.49it/s]

  5%|▍         | 361/7481 [01:45<47:37,  2.49it/s]
  5%|▍         | 362/7481 [01:45<47:37,  2.49it/s]
  5%|▍         | 363/7481 [01:45<47:37,  2.49it/s]

  5%|▍         | 364/7481 [01:46<40:35,  2.92it/s]

  5%|▍         | 364/7481 [01:46<40:35,  2.92it/s]
  5%|▍         | 365/7481 [01:46<40:34,  2.92it/s]

  5%|▍         | 366/7481 [01:46<41:44,  2.84it/s]

  5%|▍         | 366/7481 [01:46<41:44,  2.84it/s]
  5%|▍         | 367/7481 [01:46<41:43,  2.84it/s]
  5%|▍         | 368/7481 [01:46<41:43,  2.84it/s]

  5%|▍         | 369/7481 [01:47<37:33,  3.16it/s]

  5%|▍         | 369/7481 [01:47<37:33,  3.16it/s]
  5%|▍         | 370/7481 [01:47<37:33,  3.16it/s]

  5%|▍         | 371/7481 [01:48<40:35,  2.92it/s]

  5%|▍         | 371/7481 [01:48<40:35,  2.92it/s]
  5%|▍         | 372/7481 [01:48<40:35,  2.92it/s]

  5%|▍         | 373/7481 [01:49<41:04,  2.88it/s]

  5%|▍         | 373/7481 [01:49<41:04,  2.88it/s]
  5%|▍         | 374/7481 [01:49<41:03,  2.88it/s]

  5%|▌         | 375/7481 [01:52<1:20:33,  1.47it/s]

  5%|▌         | 375/7481 [01:52<1:20:33,  1.47it/s]
  5%|▌         | 376/7481 [01:52<1:20:32,  1.47it/s]
  5%|▌         | 377/7481 [01:52<1:20:31,  1.47it/s]
  5%|▌         | 378/7481 [01:52<1:20:31,  1.47it/s]
  5%|▌         | 379/7481 [01:52<1:20:30,  1.47it/s]

  5%|▌         | 380/7481 [01:52<48:54,  2.42it/s]

  5%|▌         | 380/7481 [01:52<48:54,  2.42it/s]
  5%|▌         | 381/7481 [01:52<48:54,  2.42it/s]

  5%|▌         | 382/7481 [01:53<47:23,  2.50it/s]

  5%|▌         | 382/7481 [01:53<47:23,  2.50it/s]
  5%|▌         | 383/7481 [01:53<47:23,  2.50it/s]

  5%|▌         | 384/7481 [01:54<45:36,  2.59it/s]

  5%|▌         | 384/7481 [01:54<45:36,  2.59it/s]
  5%|▌         | 385/7481 [01:54<45:35,  2.59it/s]
  5%|▌         | 386/7481 [01:54<45:35,  2.59it/s]
  5%|▌         | 387/7481 [01:54<45:35,  2.59it/s]

  5%|▌         | 388/7481 [01:55<35:23,  3.34it/s]

  5%|▌         | 388/7481 [01:55<35:23,  3.34it/s]
  5%|▌         | 389/7481 [01:55<35:23,  3.34it/s]

  5%|▌         | 390/7481 [01:55<37:08,  3.18it/s]

  5%|▌         | 390/7481 [01:55<37:08,  3.18it/s]
  5%|▌         | 391/7481 [01:55<37:08,  3.18it/s]
  5%|▌         | 392/7481 [01:55<37:08,  3.18it/s]

  5%|▌         | 393/7481 [01:56<33:52,  3.49it/s]

  5%|▌         | 393/7481 [01:56<33:52,  3.49it/s]
  5%|▌         | 394/7481 [01:56<33:51,  3.49it/s]

  5%|▌         | 395/7481 [01:57<35:29,  3.33it/s]

  5%|▌         | 395/7481 [01:57<35:29,  3.33it/s]
  5%|▌         | 396/7481 [01:57<35:29,  3.33it/s]
  5%|▌         | 397/7481 [01:57<35:28,  3.33it/s]

  5%|▌         | 398/7481 [01:57<32:51,  3.59it/s]

  5%|▌         | 398/7481 [01:57<32:51,  3.59it/s]
  5%|▌         | 399/7481 [01:57<32:51,  3.59it/s]
  5%|▌         | 400/7481 [01:57<32:51,  3.59it/s]

  5%|▌         | 401/7481 [01:58<30:37,  3.85it/s]

  5%|▌         | 401/7481 [01:58<30:37,  3.85it/s]
  5%|▌         | 402/7481 [01:58<30:36,  3.85it/s]
  5%|▌         | 403/7481 [01:58<30:36,  3.85it/s]
  5%|▌         | 404/7481 [01:58<30:36,  3.85it/s]
  5%|▌         | 405/7481 [01:58<30:36,  3.85it/s]

  5%|▌         | 406/7481 [01:59<24:34,  4.80it/s]

  5%|▌         | 406/7481 [01:59<24:34,  4.80it/s]
  5%|▌         | 407/7481 [01:59<24:34,  4.80it/s]
  5%|▌         | 408/7481 [01:59<24:33,  4.80it/s]
  5%|▌         | 409/7481 [01:59<24:33,  4.80it/s]
  5%|▌         | 410/7481 [01:59<24:33,  4.80it/s]

  5%|▌         | 411/7481 [01:59<21:08,  5.57it/s]

  5%|▌         | 411/7481 [01:59<21:08,  5.57it/s]
  6%|▌         | 412/7481 [01:59<21:08,  5.57it/s]

  6%|▌         | 413/7481 [02:00<24:21,  4.84it/s]

  6%|▌         | 413/7481 [02:00<24:21,  4.84it/s]
  6%|▌         | 414/7481 [02:00<24:21,  4.84it/s]

  6%|▌         | 415/7481 [02:01<27:41,  4.25it/s]

  6%|▌         | 415/7481 [02:01<27:41,  4.25it/s]
  6%|▌         | 416/7481 [02:01<27:40,  4.25it/s]
  6%|▌         | 417/7481 [02:01<27:40,  4.25it/s]
  6%|▌         | 418/7481 [02:01<27:40,  4.25it/s]
  6%|▌         | 419/7481 [02:01<27:40,  4.25it/s]

  6%|▌         | 420/7481 [02:01<22:36,  5.21it/s]

  6%|▌         | 420/7481 [02:01<22:36,  5.21it/s]
  6%|▌         | 421/7481 [02:01<22:36,  5.21it/s]

  6%|▌         | 422/7481 [02:04<52:30,  2.24it/s]

  6%|▌         | 422/7481 [02:04<52:30,  2.24it/s]
  6%|▌         | 423/7481 [02:04<52:29,  2.24it/s]

  6%|▌         | 424/7481 [02:05<49:57,  2.35it/s]

  6%|▌         | 424/7481 [02:05<49:57,  2.35it/s]
  6%|▌         | 425/7481 [02:05<49:57,  2.35it/s]
  6%|▌         | 426/7481 [02:05<49:56,  2.35it/s]

  6%|▌         | 427/7481 [02:06<42:56,  2.74it/s]

  6%|▌         | 427/7481 [02:06<42:56,  2.74it/s]
  6%|▌         | 428/7481 [02:06<42:56,  2.74it/s]

  6%|▌         | 429/7481 [02:07<42:30,  2.76it/s]

  6%|▌         | 429/7481 [02:07<42:30,  2.76it/s]
  6%|▌         | 430/7481 [02:07<42:30,  2.76it/s]

  6%|▌         | 431/7481 [02:07<42:33,  2.76it/s]

  6%|▌         | 431/7481 [02:07<42:33,  2.76it/s]
  6%|▌         | 432/7481 [02:07<42:32,  2.76it/s]
  6%|▌         | 433/7481 [02:07<42:32,  2.76it/s]
  6%|▌         | 434/7481 [02:07<42:32,  2.76it/s]
  6%|▌         | 435/7481 [02:07<42:31,  2.76it/s]

  6%|▌         | 436/7481 [02:08<30:17,  3.88it/s]

  6%|▌         | 436/7481 [02:08<30:17,  3.88it/s]
  6%|▌         | 437/7481 [02:08<30:16,  3.88it/s]

  6%|▌         | 438/7481 [02:09<32:15,  3.64it/s]

  6%|▌         | 438/7481 [02:09<32:15,  3.64it/s]
  6%|▌         | 439/7481 [02:09<32:15,  3.64it/s]

  6%|▌         | 440/7481 [02:09<34:18,  3.42it/s]

  6%|▌         | 440/7481 [02:09<34:18,  3.42it/s]
  6%|▌         | 441/7481 [02:09<34:18,  3.42it/s]
  6%|▌         | 442/7481 [02:09<34:18,  3.42it/s]
  6%|▌         | 443/7481 [02:09<34:18,  3.42it/s]

  6%|▌         | 444/7481 [02:10<29:02,  4.04it/s]

  6%|▌         | 444/7481 [02:10<29:02,  4.04it/s]
  6%|▌         | 445/7481 [02:10<29:02,  4.04it/s]

  6%|▌         | 446/7481 [02:11<31:27,  3.73it/s]

  6%|▌         | 446/7481 [02:11<31:27,  3.73it/s]
  6%|▌         | 447/7481 [02:11<31:26,  3.73it/s]

  6%|▌         | 448/7481 [02:11<33:52,  3.46it/s]

  6%|▌         | 448/7481 [02:11<33:52,  3.46it/s]
  6%|▌         | 449/7481 [02:11<33:51,  3.46it/s]

  6%|▌         | 450/7481 [02:12<35:50,  3.27it/s]

  6%|▌         | 450/7481 [02:12<35:50,  3.27it/s]
  6%|▌         | 451/7481 [02:12<35:50,  3.27it/s]
  6%|▌         | 452/7481 [02:12<35:49,  3.27it/s]

  6%|▌         | 453/7481 [02:13<32:25,  3.61it/s]

  6%|▌         | 453/7481 [02:13<32:25,  3.61it/s]
  6%|▌         | 454/7481 [02:13<32:25,  3.61it/s]
  6%|▌         | 455/7481 [02:13<32:25,  3.61it/s]

  6%|▌         | 456/7481 [02:14<30:48,  3.80it/s]

  6%|▌         | 456/7481 [02:14<30:48,  3.80it/s]
  6%|▌         | 457/7481 [02:14<30:48,  3.80it/s]

  6%|▌         | 458/7481 [02:14<33:02,  3.54it/s]

  6%|▌         | 458/7481 [02:14<33:02,  3.54it/s]
  6%|▌         | 459/7481 [02:14<33:01,  3.54it/s]
  6%|▌         | 460/7481 [02:14<33:01,  3.54it/s]

  6%|▌         | 461/7481 [02:17<1:01:29,  1.90it/s]

  6%|▌         | 461/7481 [02:17<1:01:29,  1.90it/s]
  6%|▌         | 462/7481 [02:17<1:01:28,  1.90it/s]

  6%|▌         | 463/7481 [02:18<56:53,  2.06it/s]

  6%|▌         | 463/7481 [02:18<56:53,  2.06it/s]
  6%|▌         | 464/7481 [02:18<56:53,  2.06it/s]

  6%|▌         | 465/7481 [02:19<52:17,  2.24it/s]

  6%|▌         | 465/7481 [02:19<52:17,  2.24it/s]
  6%|▌         | 466/7481 [02:19<52:17,  2.24it/s]

  6%|▌         | 467/7481 [02:19<48:23,  2.42it/s]

  6%|▌         | 467/7481 [02:19<48:23,  2.42it/s]
  6%|▋         | 468/7481 [02:19<48:22,  2.42it/s]

  6%|▋         | 469/7481 [02:20<46:28,  2.51it/s]

  6%|▋         | 469/7481 [02:20<46:28,  2.51it/s]
  6%|▋         | 470/7481 [02:20<46:28,  2.51it/s]

  6%|▋         | 471/7481 [02:21<44:32,  2.62it/s]

  6%|▋         | 471/7481 [02:21<44:32,  2.62it/s]
  6%|▋         | 472/7481 [02:21<44:32,  2.62it/s]

  6%|▋         | 473/7481 [02:21<42:35,  2.74it/s]

  6%|▋         | 473/7481 [02:21<42:35,  2.74it/s]
  6%|▋         | 474/7481 [02:21<42:34,  2.74it/s]

  6%|▋         | 475/7481 [02:22<41:32,  2.81it/s]

  6%|▋         | 475/7481 [02:22<41:32,  2.81it/s]
  6%|▋         | 476/7481 [02:22<41:32,  2.81it/s]

  6%|▋         | 477/7481 [02:23<40:33,  2.88it/s]

  6%|▋         | 477/7481 [02:23<40:33,  2.88it/s]
  6%|▋         | 478/7481 [02:23<40:32,  2.88it/s]

  6%|▋         | 479/7481 [02:23<39:49,  2.93it/s]

  6%|▋         | 479/7481 [02:23<39:49,  2.93it/s]
  6%|▋         | 480/7481 [02:23<39:49,  2.93it/s]

  6%|▋         | 481/7481 [02:24<39:40,  2.94it/s]

  6%|▋         | 481/7481 [02:24<39:40,  2.94it/s]
  6%|▋         | 482/7481 [02:24<39:40,  2.94it/s]

  6%|▋         | 483/7481 [02:25<39:01,  2.99it/s]

  6%|▋         | 483/7481 [02:25<39:01,  2.99it/s]
  6%|▋         | 484/7481 [02:25<39:01,  2.99it/s]

  6%|▋         | 485/7481 [02:25<39:12,  2.97it/s]

  6%|▋         | 485/7481 [02:25<39:12,  2.97it/s]
  6%|▋         | 486/7481 [02:25<39:11,  2.97it/s]

  7%|▋         | 487/7481 [02:26<39:02,  2.99it/s]

  7%|▋         | 487/7481 [02:26<39:02,  2.99it/s]
  7%|▋         | 488/7481 [02:26<39:02,  2.99it/s]

  7%|▋         | 489/7481 [02:27<38:37,  3.02it/s]

  7%|▋         | 489/7481 [02:27<38:37,  3.02it/s]
  7%|▋         | 490/7481 [02:27<38:37,  3.02it/s]

  7%|▋         | 491/7481 [02:29<1:08:42,  1.70it/s]

  7%|▋         | 491/7481 [02:29<1:08:42,  1.70it/s]
  7%|▋         | 492/7481 [02:29<1:08:42,  1.70it/s]

  7%|▋         | 493/7481 [02:30<1:07:56,  1.71it/s]

  7%|▋         | 493/7481 [02:30<1:07:56,  1.71it/s]
  7%|▋         | 494/7481 [02:30<1:07:55,  1.71it/s]

  7%|▋         | 495/7481 [02:31<58:36,  1.99it/s]

  7%|▋         | 495/7481 [02:31<58:36,  1.99it/s]
  7%|▋         | 496/7481 [02:31<58:35,  1.99it/s]
  7%|▋         | 497/7481 [02:31<58:35,  1.99it/s]

  7%|▋         | 498/7481 [02:31<45:47,  2.54it/s]

  7%|▋         | 498/7481 [02:31<45:47,  2.54it/s]
  7%|▋         | 499/7481 [02:31<45:47,  2.54it/s]

  7%|▋         | 500/7481 [02:32<43:35,  2.67it/s]

  7%|▋         | 500/7481 [02:32<43:35,  2.67it/s]
  7%|▋         | 501/7481 [02:32<43:34,  2.67it/s]

  7%|▋         | 502/7481 [02:33<41:56,  2.77it/s]

  7%|▋         | 502/7481 [02:33<41:56,  2.77it/s]
  7%|▋         | 503/7481 [02:33<41:55,  2.77it/s]

  7%|▋         | 504/7481 [02:33<41:10,  2.82it/s]

  7%|▋         | 504/7481 [02:33<41:10,  2.82it/s]
  7%|▋         | 505/7481 [02:33<41:09,  2.82it/s]

  7%|▋         | 506/7481 [02:34<39:50,  2.92it/s]

  7%|▋         | 506/7481 [02:34<39:50,  2.92it/s]
  7%|▋         | 507/7481 [02:34<39:49,  2.92it/s]
  7%|▋         | 508/7481 [02:34<39:49,  2.92it/s]

  7%|▋         | 509/7481 [02:35<34:33,  3.36it/s]

  7%|▋         | 509/7481 [02:35<34:33,  3.36it/s]
  7%|▋         | 510/7481 [02:35<34:32,  3.36it/s]
  7%|▋         | 511/7481 [02:35<34:32,  3.36it/s]
  7%|▋         | 512/7481 [02:35<34:32,  3.36it/s]

  7%|▋         | 513/7481 [02:35<28:07,  4.13it/s]

  7%|▋         | 513/7481 [02:35<28:07,  4.13it/s]
  7%|▋         | 514/7481 [02:35<28:07,  4.13it/s]
  7%|▋         | 515/7481 [02:35<28:07,  4.13it/s]

  7%|▋         | 516/7481 [02:36<26:44,  4.34it/s]

  7%|▋         | 516/7481 [02:36<26:44,  4.34it/s]
  7%|▋         | 517/7481 [02:36<26:44,  4.34it/s]

  7%|▋         | 518/7481 [02:37<29:32,  3.93it/s]

  7%|▋         | 518/7481 [02:37<29:32,  3.93it/s]
  7%|▋         | 519/7481 [02:37<29:31,  3.93it/s]

  7%|▋         | 520/7481 [02:37<31:31,  3.68it/s]

  7%|▋         | 520/7481 [02:37<31:31,  3.68it/s]
  7%|▋         | 521/7481 [02:37<31:31,  3.68it/s]
  7%|▋         | 522/7481 [02:37<31:30,  3.68it/s]
  7%|▋         | 523/7481 [02:37<31:30,  3.68it/s]
  7%|▋         | 524/7481 [02:37<31:30,  3.68it/s]
  7%|▋         | 525/7481 [02:37<31:29,  3.68it/s]

  7%|▋         | 526/7481 [02:38<21:44,  5.33it/s]

  7%|▋         | 526/7481 [02:38<21:44,  5.33it/s]
  7%|▋         | 527/7481 [02:38<21:44,  5.33it/s]

  7%|▋         | 528/7481 [02:39<25:00,  4.63it/s]

  7%|▋         | 528/7481 [02:39<25:00,  4.63it/s]
  7%|▋         | 529/7481 [02:39<24:59,  4.63it/s]

  7%|▋         | 530/7481 [02:39<27:30,  4.21it/s]

  7%|▋         | 530/7481 [02:39<27:30,  4.21it/s]
  7%|▋         | 531/7481 [02:39<27:30,  4.21it/s]

  7%|▋         | 532/7481 [02:40<35:55,  3.22it/s]

  7%|▋         | 532/7481 [02:40<35:55,  3.22it/s]
  7%|▋         | 533/7481 [02:40<35:54,  3.22it/s]

  7%|▋         | 534/7481 [02:43<1:04:19,  1.80it/s]

  7%|▋         | 534/7481 [02:43<1:04:19,  1.80it/s]
  7%|▋         | 535/7481 [02:43<1:04:18,  1.80it/s]

  7%|▋         | 536/7481 [02:44<57:40,  2.01it/s]

  7%|▋         | 536/7481 [02:44<57:40,  2.01it/s]
  7%|▋         | 537/7481 [02:44<57:39,  2.01it/s]

  7%|▋         | 538/7481 [02:44<52:52,  2.19it/s]

  7%|▋         | 538/7481 [02:44<52:52,  2.19it/s]
  7%|▋         | 539/7481 [02:44<52:51,  2.19it/s]

  7%|▋         | 540/7481 [02:45<49:23,  2.34it/s]

  7%|▋         | 540/7481 [02:45<49:23,  2.34it/s]
  7%|▋         | 541/7481 [02:45<49:22,  2.34it/s]

  7%|▋         | 542/7481 [02:46<46:05,  2.51it/s]

  7%|▋         | 542/7481 [02:46<46:05,  2.51it/s]
  7%|▋         | 543/7481 [02:46<46:05,  2.51it/s]

  7%|▋         | 544/7481 [02:46<44:04,  2.62it/s]

  7%|▋         | 544/7481 [02:46<44:04,  2.62it/s]
  7%|▋         | 545/7481 [02:46<44:04,  2.62it/s]

  7%|▋         | 546/7481 [02:47<42:30,  2.72it/s]

  7%|▋         | 546/7481 [02:47<42:30,  2.72it/s]
  7%|▋         | 547/7481 [02:47<42:30,  2.72it/s]

  7%|▋         | 548/7481 [02:48<41:02,  2.82it/s]

  7%|▋         | 548/7481 [02:48<41:02,  2.82it/s]
  7%|▋         | 549/7481 [02:48<41:02,  2.82it/s]

  7%|▋         | 550/7481 [02:48<40:54,  2.82it/s]

  7%|▋         | 550/7481 [02:48<40:54,  2.82it/s]
  7%|▋         | 551/7481 [02:48<40:53,  2.82it/s]

  7%|▋         | 552/7481 [02:49<40:09,  2.88it/s]

  7%|▋         | 552/7481 [02:49<40:09,  2.88it/s]
  7%|▋         | 553/7481 [02:49<40:09,  2.88it/s]
  7%|▋         | 554/7481 [02:49<40:09,  2.88it/s]

  7%|▋         | 555/7481 [02:50<34:28,  3.35it/s]

  7%|▋         | 555/7481 [02:50<34:28,  3.35it/s]
  7%|▋         | 556/7481 [02:50<34:27,  3.35it/s]

  7%|▋         | 557/7481 [02:50<35:51,  3.22it/s]

  7%|▋         | 557/7481 [02:50<35:51,  3.22it/s]
  7%|▋         | 558/7481 [02:50<35:50,  3.22it/s]

  7%|▋         | 559/7481 [02:51<37:14,  3.10it/s]

  7%|▋         | 559/7481 [02:51<37:14,  3.10it/s]
  7%|▋         | 560/7481 [02:51<37:14,  3.10it/s]

  7%|▋         | 561/7481 [02:52<37:30,  3.07it/s]

  7%|▋         | 561/7481 [02:52<37:30,  3.07it/s]
  8%|▊         | 562/7481 [02:52<37:30,  3.07it/s]

  8%|▊         | 563/7481 [02:52<37:56,  3.04it/s]

  8%|▊         | 563/7481 [02:52<37:56,  3.04it/s]
  8%|▊         | 564/7481 [02:52<37:55,  3.04it/s]

  8%|▊         | 565/7481 [02:55<1:17:12,  1.49it/s]

  8%|▊         | 565/7481 [02:55<1:17:12,  1.49it/s]
  8%|▊         | 566/7481 [02:55<1:17:11,  1.49it/s]

  8%|▊         | 567/7481 [02:56<1:06:05,  1.74it/s]

  8%|▊         | 567/7481 [02:56<1:06:05,  1.74it/s]
  8%|▊         | 568/7481 [02:56<1:06:05,  1.74it/s]

  8%|▊         | 569/7481 [02:57<58:13,  1.98it/s]

  8%|▊         | 569/7481 [02:57<58:13,  1.98it/s]
  8%|▊         | 570/7481 [02:57<58:13,  1.98it/s]

  8%|▊         | 571/7481 [02:57<52:59,  2.17it/s]

  8%|▊         | 571/7481 [02:57<52:59,  2.17it/s]
  8%|▊         | 572/7481 [02:57<52:58,  2.17it/s]

  8%|▊         | 573/7481 [02:58<48:11,  2.39it/s]

  8%|▊         | 573/7481 [02:58<48:11,  2.39it/s]
  8%|▊         | 574/7481 [02:58<48:10,  2.39it/s]

  8%|▊         | 575/7481 [02:59<45:49,  2.51it/s]

  8%|▊         | 575/7481 [02:59<45:49,  2.51it/s]
  8%|▊         | 576/7481 [02:59<45:49,  2.51it/s]

  8%|▊         | 577/7481 [02:59<43:44,  2.63it/s]

  8%|▊         | 577/7481 [02:59<43:44,  2.63it/s]
  8%|▊         | 578/7481 [02:59<43:44,  2.63it/s]
  8%|▊         | 579/7481 [02:59<43:43,  2.63it/s]

  8%|▊         | 580/7481 [03:00<36:39,  3.14it/s]

  8%|▊         | 580/7481 [03:00<36:39,  3.14it/s]
  8%|▊         | 581/7481 [03:00<36:38,  3.14it/s]

  8%|▊         | 582/7481 [03:01<37:32,  3.06it/s]

  8%|▊         | 582/7481 [03:01<37:32,  3.06it/s]
  8%|▊         | 583/7481 [03:01<37:32,  3.06it/s]
  8%|▊         | 584/7481 [03:01<37:32,  3.06it/s]
  8%|▊         | 585/7481 [03:01<37:31,  3.06it/s]
  8%|▊         | 586/7481 [03:01<37:31,  3.06it/s]
  8%|▊         | 587/7481 [03:01<37:31,  3.06it/s]

  8%|▊         | 588/7481 [03:01<24:10,  4.75it/s]

  8%|▊         | 588/7481 [03:01<24:10,  4.75it/s]
  8%|▊         | 589/7481 [03:01<24:10,  4.75it/s]

  8%|▊         | 590/7481 [03:02<26:51,  4.28it/s]

  8%|▊         | 590/7481 [03:02<26:51,  4.28it/s]
  8%|▊         | 591/7481 [03:02<26:50,  4.28it/s]
  8%|▊         | 592/7481 [03:02<26:50,  4.28it/s]

  8%|▊         | 593/7481 [03:03<26:57,  4.26it/s]

  8%|▊         | 593/7481 [03:03<26:57,  4.26it/s]
  8%|▊         | 594/7481 [03:03<26:56,  4.26it/s]
  8%|▊         | 595/7481 [03:03<26:56,  4.26it/s]

  8%|▊         | 596/7481 [03:03<26:30,  4.33it/s]

  8%|▊         | 596/7481 [03:03<26:30,  4.33it/s]
  8%|▊         | 597/7481 [03:04<26:29,  4.33it/s]

  8%|▊         | 598/7481 [03:04<29:05,  3.94it/s]

  8%|▊         | 598/7481 [03:04<29:05,  3.94it/s]
  8%|▊         | 599/7481 [03:04<29:05,  3.94it/s]

  8%|▊         | 600/7481 [03:05<31:34,  3.63it/s]

  8%|▊         | 600/7481 [03:05<31:34,  3.63it/s]
  8%|▊         | 601/7481 [03:05<31:34,  3.63it/s]

  8%|▊         | 602/7481 [03:08<1:07:25,  1.70it/s]

  8%|▊         | 602/7481 [03:08<1:07:25,  1.70it/s]
  8%|▊         | 603/7481 [03:08<1:07:24,  1.70it/s]

  8%|▊         | 604/7481 [03:09<59:44,  1.92it/s]

  8%|▊         | 604/7481 [03:09<59:44,  1.92it/s]
  8%|▊         | 605/7481 [03:09<59:43,  1.92it/s]
  8%|▊         | 606/7481 [03:09<59:43,  1.92it/s]

  8%|▊         | 607/7481 [03:09<47:48,  2.40it/s]

  8%|▊         | 607/7481 [03:09<47:48,  2.40it/s]
  8%|▊         | 608/7481 [03:09<47:48,  2.40it/s]

  8%|▊         | 609/7481 [03:10<45:46,  2.50it/s]

  8%|▊         | 609/7481 [03:10<45:46,  2.50it/s]
  8%|▊         | 610/7481 [03:10<45:46,  2.50it/s]

  8%|▊         | 611/7481 [03:11<44:05,  2.60it/s]

  8%|▊         | 611/7481 [03:11<44:05,  2.60it/s]
  8%|▊         | 612/7481 [03:11<44:05,  2.60it/s]

  8%|▊         | 613/7481 [03:11<43:23,  2.64it/s]
  8%|▊         | 617/7481 [03:11<25:27,  4.49it/s]

  8%|▊         | 613/7481 [03:11<43:23,  2.64it/s]
  8%|▊         | 614/7481 [03:11<43:23,  2.64it/s]
  8%|▊         | 615/7481 [03:11<43:22,  2.64it/s]
  8%|▊         | 616/7481 [03:11<43:22,  2.64it/s]
  8%|▊         | 617/7481 [03:11<25:27,  4.49it/s]
  8%|▊         | 618/7481 [03:11<25:27,  4.49it/s]
  8%|▊         | 619/7481 [03:11<25:26,  4.49it/s]

  8%|▊         | 620/7481 [03:12<26:01,  4.39it/s]

  8%|▊         | 620/7481 [03:12<26:01,  4.39it/s]
  8%|▊         | 621/7481 [03:12<26:01,  4.39it/s]

  8%|▊         | 622/7481 [03:13<29:07,  3.93it/s]

  8%|▊         | 622/7481 [03:13<29:07,  3.93it/s]
  8%|▊         | 623/7481 [03:13<29:06,  3.93it/s]
  8%|▊         | 624/7481 [03:13<29:06,  3.93it/s]

  8%|▊         | 625/7481 [03:14<28:39,  3.99it/s]

  8%|▊         | 625/7481 [03:14<28:39,  3.99it/s]
  8%|▊         | 626/7481 [03:14<28:39,  3.99it/s]
  8%|▊         | 627/7481 [03:14<28:39,  3.99it/s]

  8%|▊         | 628/7481 [03:14<27:56,  4.09it/s]

  8%|▊         | 628/7481 [03:14<27:56,  4.09it/s]
  8%|▊         | 629/7481 [03:14<27:56,  4.09it/s]
  8%|▊         | 630/7481 [03:14<27:56,  4.09it/s]
  8%|▊         | 631/7481 [03:14<27:55,  4.09it/s]

  8%|▊         | 632/7481 [03:15<24:30,  4.66it/s]

  8%|▊         | 632/7481 [03:15<24:30,  4.66it/s]
  8%|▊         | 633/7481 [03:15<24:30,  4.66it/s]
  8%|▊         | 634/7481 [03:15<24:30,  4.66it/s]
  8%|▊         | 635/7481 [03:15<24:30,  4.66it/s]
  9%|▊         | 636/7481 [03:15<24:29,  4.66it/s]
  9%|▊         | 637/7481 [03:15<24:29,  4.66it/s]
  9%|▊         | 638/7481 [03:15<24:29,  4.66it/s]
  9%|▊         | 639/7481 [03:15<24:29,  4.66it/s]

  9%|▊         | 640/7481 [03:16<16:59,  6.71it/s]

  9%|▊         | 640/7481 [03:16<16:59,  6.71it/s]
  9%|▊         | 641/7481 [03:16<16:59,  6.71it/s]

  9%|▊         | 642/7481 [03:16<20:58,  5.43it/s]

  9%|▊         | 642/7481 [03:16<20:58,  5.43it/s]
  9%|▊         | 643/7481 [03:16<20:58,  5.43it/s]

  9%|▊         | 644/7481 [03:17<24:01,  4.74it/s]

  9%|▊         | 644/7481 [03:17<24:01,  4.74it/s]
  9%|▊         | 645/7481 [03:17<24:01,  4.74it/s]

  9%|▊         | 646/7481 [03:18<27:32,  4.14it/s]

  9%|▊         | 646/7481 [03:18<27:32,  4.14it/s]
  9%|▊         | 647/7481 [03:18<27:32,  4.14it/s]

  9%|▊         | 648/7481 [03:21<59:13,  1.92it/s]

  9%|▊         | 648/7481 [03:21<59:13,  1.92it/s]
  9%|▊         | 649/7481 [03:21<59:12,  1.92it/s]

  9%|▊         | 650/7481 [03:21<53:44,  2.12it/s]

  9%|▊         | 650/7481 [03:21<53:44,  2.12it/s]
  9%|▊         | 651/7481 [03:21<53:44,  2.12it/s]

  9%|▊         | 652/7481 [03:22<49:43,  2.29it/s]

  9%|▊         | 652/7481 [03:22<49:43,  2.29it/s]
  9%|▊         | 653/7481 [03:22<49:43,  2.29it/s]

  9%|▊         | 654/7481 [03:23<46:42,  2.44it/s]
  9%|▉         | 659/7481 [03:23<24:57,  4.56it/s]

  9%|▊         | 654/7481 [03:23<46:42,  2.44it/s]
  9%|▉         | 655/7481 [03:23<46:41,  2.44it/s]
  9%|▉         | 656/7481 [03:23<46:41,  2.44it/s]
  9%|▉         | 657/7481 [03:23<46:40,  2.44it/s]
  9%|▉         | 658/7481 [03:23<46:40,  2.44it/s]
  9%|▉         | 659/7481 [03:23<24:57,  4.56it/s]
  9%|▉         | 660/7481 [03:23<24:56,  4.56it/s]
  9%|▉         | 661/7481 [03:23<24:56,  4.56it/s]
  9%|▉         | 662/7481 [03:23<24:56,  4.56it/s]
  9%|▉         | 663/7481 [03:23<24:56,  4.56it/s]

  9%|▉         | 664/7481 [03:23<21:07,  5.38it/s]

  9%|▉         | 664/7481 [03:23<21:07,  5.38it/s]
  9%|▉         | 665/7481 [03:23<21:07,  5.38it/s]

  9%|▉         | 666/7481 [03:24<24:47,  4.58it/s]

  9%|▉         | 666/7481 [03:24<24:47,  4.58it/s]
  9%|▉         | 667/7481 [03:24<24:46,  4.58it/s]

  9%|▉         | 668/7481 [03:25<28:08,  4.03it/s]

  9%|▉         | 668/7481 [03:25<28:08,  4.03it/s]
  9%|▉         | 669/7481 [03:25<28:08,  4.03it/s]

  9%|▉         | 670/7481 [03:26<30:30,  3.72it/s]

  9%|▉         | 670/7481 [03:26<30:30,  3.72it/s]
  9%|▉         | 671/7481 [03:26<30:30,  3.72it/s]

  9%|▉         | 672/7481 [03:26<33:08,  3.42it/s]

  9%|▉         | 672/7481 [03:26<33:08,  3.42it/s]
  9%|▉         | 673/7481 [03:26<33:08,  3.42it/s]

  9%|▉         | 674/7481 [03:27<35:07,  3.23it/s]

  9%|▉         | 674/7481 [03:27<35:07,  3.23it/s]
  9%|▉         | 675/7481 [03:27<35:07,  3.23it/s]

  9%|▉         | 676/7481 [03:28<35:59,  3.15it/s]

  9%|▉         | 676/7481 [03:28<35:59,  3.15it/s]
  9%|▉         | 677/7481 [03:28<35:59,  3.15it/s]

  9%|▉         | 678/7481 [03:28<37:18,  3.04it/s]

  9%|▉         | 678/7481 [03:28<37:18,  3.04it/s]
  9%|▉         | 679/7481 [03:28<37:18,  3.04it/s]
  9%|▉         | 680/7481 [03:28<37:17,  3.04it/s]
  9%|▉         | 681/7481 [03:28<37:17,  3.04it/s]

  9%|▉         | 682/7481 [03:29<29:13,  3.88it/s]

  9%|▉         | 682/7481 [03:29<29:13,  3.88it/s]
  9%|▉         | 683/7481 [03:29<29:13,  3.88it/s]

  9%|▉         | 684/7481 [03:30<31:10,  3.63it/s]

  9%|▉         | 684/7481 [03:30<31:10,  3.63it/s]
  9%|▉         | 685/7481 [03:30<31:10,  3.63it/s]

  9%|▉         | 686/7481 [03:30<33:49,  3.35it/s]

  9%|▉         | 686/7481 [03:30<33:49,  3.35it/s]
  9%|▉         | 687/7481 [03:31<33:49,  3.35it/s]
  9%|▉         | 688/7481 [03:31<33:49,  3.35it/s]
  9%|▉         | 689/7481 [03:31<33:49,  3.35it/s]

  9%|▉         | 690/7481 [03:33<54:46,  2.07it/s]

  9%|▉         | 690/7481 [03:33<54:46,  2.07it/s]
  9%|▉         | 691/7481 [03:33<54:46,  2.07it/s]

  9%|▉         | 692/7481 [03:34<51:14,  2.21it/s]

  9%|▉         | 692/7481 [03:34<51:14,  2.21it/s]
  9%|▉         | 693/7481 [03:34<51:13,  2.21it/s]
  9%|▉         | 694/7481 [03:34<51:13,  2.21it/s]

  9%|▉         | 695/7481 [03:35<42:36,  2.65it/s]

  9%|▉         | 695/7481 [03:35<42:36,  2.65it/s]
  9%|▉         | 696/7481 [03:35<42:36,  2.65it/s]

  9%|▉         | 697/7481 [03:36<42:12,  2.68it/s]

  9%|▉         | 697/7481 [03:36<42:12,  2.68it/s]
  9%|▉         | 698/7481 [03:36<42:12,  2.68it/s]

  9%|▉         | 699/7481 [03:36<42:00,  2.69it/s]

  9%|▉         | 699/7481 [03:36<42:00,  2.69it/s]
  9%|▉         | 700/7481 [03:36<41:59,  2.69it/s]

  9%|▉         | 701/7481 [03:37<41:06,  2.75it/s]

  9%|▉         | 701/7481 [03:37<41:06,  2.75it/s]
  9%|▉         | 702/7481 [03:37<41:06,  2.75it/s]
  9%|▉         | 703/7481 [03:37<41:06,  2.75it/s]

  9%|▉         | 704/7481 [03:38<35:46,  3.16it/s]

  9%|▉         | 704/7481 [03:38<35:46,  3.16it/s]
  9%|▉         | 705/7481 [03:38<35:45,  3.16it/s]

  9%|▉         | 706/7481 [03:38<37:03,  3.05it/s]

  9%|▉         | 706/7481 [03:38<37:03,  3.05it/s]
  9%|▉         | 707/7481 [03:38<37:02,  3.05it/s]

  9%|▉         | 708/7481 [03:39<36:51,  3.06it/s]

  9%|▉         | 708/7481 [03:39<36:51,  3.06it/s]
  9%|▉         | 709/7481 [03:39<36:50,  3.06it/s]

  9%|▉         | 710/7481 [03:40<37:27,  3.01it/s]

  9%|▉         | 710/7481 [03:40<37:27,  3.01it/s]
 10%|▉         | 711/7481 [03:40<37:27,  3.01it/s]

 10%|▉         | 712/7481 [03:40<37:58,  2.97it/s]

 10%|▉         | 712/7481 [03:40<37:58,  2.97it/s]
 10%|▉         | 713/7481 [03:40<37:58,  2.97it/s]

 10%|▉         | 714/7481 [03:41<37:57,  2.97it/s]

 10%|▉         | 714/7481 [03:41<37:57,  2.97it/s]
 10%|▉         | 715/7481 [03:41<37:56,  2.97it/s]

 10%|▉         | 716/7481 [03:42<38:05,  2.96it/s]

 10%|▉         | 716/7481 [03:42<38:05,  2.96it/s]
 10%|▉         | 717/7481 [03:42<38:05,  2.96it/s]

 10%|▉         | 718/7481 [03:42<38:51,  2.90it/s]

 10%|▉         | 718/7481 [03:42<38:51,  2.90it/s]
 10%|▉         | 719/7481 [03:42<38:50,  2.90it/s]

 10%|▉         | 720/7481 [03:43<41:28,  2.72it/s]

 10%|▉         | 720/7481 [03:43<41:28,  2.72it/s]
 10%|▉         | 721/7481 [03:43<41:27,  2.72it/s]

 10%|▉         | 722/7481 [03:46<1:15:46,  1.49it/s]

 10%|▉         | 722/7481 [03:46<1:15:46,  1.49it/s]
 10%|▉         | 723/7481 [03:46<1:15:45,  1.49it/s]

 10%|▉         | 724/7481 [03:47<1:04:49,  1.74it/s]

 10%|▉         | 724/7481 [03:47<1:04:49,  1.74it/s]
 10%|▉         | 725/7481 [03:47<1:04:49,  1.74it/s]

 10%|▉         | 726/7481 [03:48<57:10,  1.97it/s]

 10%|▉         | 726/7481 [03:48<57:10,  1.97it/s]
 10%|▉         | 727/7481 [03:48<57:10,  1.97it/s]

 10%|▉         | 728/7481 [03:48<52:20,  2.15it/s]

 10%|▉         | 728/7481 [03:48<52:20,  2.15it/s]
 10%|▉         | 729/7481 [03:48<52:20,  2.15it/s]
 10%|▉         | 730/7481 [03:48<52:20,  2.15it/s]
 10%|▉         | 731/7481 [03:48<52:19,  2.15it/s]
 10%|▉         | 732/7481 [03:48<52:19,  2.15it/s]
 10%|▉         | 733/7481 [03:48<52:18,  2.15it/s]
 10%|▉         | 734/7481 [03:48<52:18,  2.15it/s]

 10%|▉         | 735/7481 [03:49<28:19,  3.97it/s]

 10%|▉         | 735/7481 [03:49<28:19,  3.97it/s]
 10%|▉         | 736/7481 [03:49<28:19,  3.97it/s]
 10%|▉         | 737/7481 [03:49<28:19,  3.97it/s]

 10%|▉         | 738/7481 [03:50<27:46,  4.05it/s]
 10%|▉         | 743/7481 [03:50<17:53,  6.27it/s]

 10%|▉         | 738/7481 [03:50<27:46,  4.05it/s]
 10%|▉         | 739/7481 [03:50<27:46,  4.05it/s]
 10%|▉         | 740/7481 [03:50<27:46,  4.05it/s]
 10%|▉         | 741/7481 [03:50<27:45,  4.05it/s]
 10%|▉         | 742/7481 [03:50<27:45,  4.05it/s]
 10%|▉         | 743/7481 [03:50<17:53,  6.27it/s]
 10%|▉         | 744/7481 [03:50<17:53,  6.27it/s]

 10%|▉         | 745/7481 [03:51<22:16,  5.04it/s]

 10%|▉         | 745/7481 [03:51<22:16,  5.04it/s]
 10%|▉         | 746/7481 [03:51<22:16,  5.04it/s]

 10%|▉         | 747/7481 [03:51<26:09,  4.29it/s]

 10%|▉         | 747/7481 [03:51<26:09,  4.29it/s]
 10%|▉         | 748/7481 [03:51<26:08,  4.29it/s]

 10%|█         | 749/7481 [03:52<29:37,  3.79it/s]

 10%|█         | 749/7481 [03:52<29:37,  3.79it/s]
 10%|█         | 750/7481 [03:52<29:37,  3.79it/s]

 10%|█         | 751/7481 [03:53<31:55,  3.51it/s]

 10%|█         | 751/7481 [03:53<31:55,  3.51it/s]
 10%|█         | 752/7481 [03:53<31:55,  3.51it/s]

 10%|█         | 753/7481 [03:53<34:18,  3.27it/s]

 10%|█         | 753/7481 [03:53<34:18,  3.27it/s]
 10%|█         | 754/7481 [03:53<34:18,  3.27it/s]

 10%|█         | 755/7481 [03:54<35:48,  3.13it/s]

 10%|█         | 755/7481 [03:54<35:48,  3.13it/s]
 10%|█         | 756/7481 [03:54<35:48,  3.13it/s]
 10%|█         | 757/7481 [03:54<35:48,  3.13it/s]

 10%|█         | 758/7481 [03:55<32:23,  3.46it/s]

 10%|█         | 758/7481 [03:55<32:23,  3.46it/s]
 10%|█         | 759/7481 [03:55<32:22,  3.46it/s]

 10%|█         | 760/7481 [03:56<35:06,  3.19it/s]

 10%|█         | 760/7481 [03:56<35:06,  3.19it/s]
 10%|█         | 761/7481 [03:56<35:06,  3.19it/s]

 10%|█         | 762/7481 [03:59<1:10:46,  1.58it/s]
 10%|█         | 768/7481 [03:59<33:51,  3.30it/s]

 10%|█         | 762/7481 [03:59<1:10:46,  1.58it/s]
 10%|█         | 763/7481 [03:59<1:10:45,  1.58it/s]
 10%|█         | 764/7481 [03:59<1:10:45,  1.58it/s]
 10%|█         | 765/7481 [03:59<1:10:44,  1.58it/s]
 10%|█         | 766/7481 [03:59<1:10:43,  1.58it/s]
 10%|█         | 767/7481 [03:59<1:10:43,  1.58it/s]
 10%|█         | 768/7481 [03:59<33:51,  3.30it/s]
 10%|█         | 769/7481 [03:59<33:51,  3.30it/s]

 10%|█         | 770/7481 [03:59<35:17,  3.17it/s]

 10%|█         | 770/7481 [03:59<35:17,  3.17it/s]
 10%|█         | 771/7481 [03:59<35:17,  3.17it/s]

 10%|█         | 772/7481 [04:00<35:53,  3.12it/s]

 10%|█         | 772/7481 [04:00<35:53,  3.12it/s]
 10%|█         | 773/7481 [04:00<35:52,  3.12it/s]

 10%|█         | 774/7481 [04:01<37:13,  3.00it/s]

 10%|█         | 774/7481 [04:01<37:13,  3.00it/s]
 10%|█         | 775/7481 [04:01<37:13,  3.00it/s]

 10%|█         | 776/7481 [04:02<38:25,  2.91it/s]

 10%|█         | 776/7481 [04:02<38:25,  2.91it/s]
 10%|█         | 777/7481 [04:02<38:25,  2.91it/s]
 10%|█         | 778/7481 [04:02<38:24,  2.91it/s]

 10%|█         | 779/7481 [04:02<34:19,  3.25it/s]

 10%|█         | 779/7481 [04:02<34:19,  3.25it/s]
 10%|█         | 780/7481 [04:02<34:19,  3.25it/s]

 10%|█         | 781/7481 [04:03<36:21,  3.07it/s]

 10%|█         | 781/7481 [04:03<36:21,  3.07it/s]
 10%|█         | 782/7481 [04:03<36:20,  3.07it/s]

 10%|█         | 783/7481 [04:04<38:01,  2.94it/s]

 10%|█         | 783/7481 [04:04<38:01,  2.94it/s]
 10%|█         | 784/7481 [04:04<38:01,  2.94it/s]

 10%|█         | 785/7481 [04:05<39:24,  2.83it/s]

 10%|█         | 785/7481 [04:05<39:24,  2.83it/s]
 11%|█         | 786/7481 [04:05<39:24,  2.83it/s]

 11%|█         | 787/7481 [04:05<40:18,  2.77it/s]

 11%|█         | 787/7481 [04:05<40:18,  2.77it/s]
 11%|█         | 788/7481 [04:05<40:18,  2.77it/s]

 11%|█         | 789/7481 [04:06<41:14,  2.70it/s]

 11%|█         | 789/7481 [04:06<41:14,  2.70it/s]
 11%|█         | 790/7481 [04:06<41:14,  2.70it/s]

 11%|█         | 791/7481 [04:07<42:22,  2.63it/s]

 11%|█         | 791/7481 [04:07<42:22,  2.63it/s]
 11%|█         | 792/7481 [04:07<42:22,  2.63it/s]

 11%|█         | 793/7481 [04:08<43:02,  2.59it/s]

 11%|█         | 793/7481 [04:08<43:02,  2.59it/s]
 11%|█         | 794/7481 [04:08<43:01,  2.59it/s]
 11%|█         | 795/7481 [04:08<43:01,  2.59it/s]

 11%|█         | 796/7481 [04:10<58:58,  1.89it/s]

 11%|█         | 796/7481 [04:10<58:58,  1.89it/s]
 11%|█         | 797/7481 [04:10<58:57,  1.89it/s]

 11%|█         | 798/7481 [04:12<1:06:43,  1.67it/s]
 11%|█         | 802/7481 [04:12<39:00,  2.85it/s]
 11%|█         | 806/7481 [04:12<25:07,  4.43it/s]

 11%|█         | 798/7481 [04:12<1:06:43,  1.67it/s]
 11%|█         | 799/7481 [04:12<1:06:42,  1.67it/s]
 11%|█         | 800/7481 [04:12<1:06:42,  1.67it/s]
 11%|█         | 801/7481 [04:12<1:06:41,  1.67it/s]
 11%|█         | 802/7481 [04:12<39:00,  2.85it/s]
 11%|█         | 803/7481 [04:12<38:59,  2.85it/s]
 11%|█         | 804/7481 [04:12<38:59,  2.85it/s]
 11%|█         | 805/7481 [04:12<38:59,  2.85it/s]
 11%|█         | 806/7481 [04:12<25:07,  4.43it/s]
 11%|█         | 807/7481 [04:12<25:06,  4.43it/s]
 11%|█         | 808/7481 [04:12<25:06,  4.43it/s]
 11%|█         | 809/7481 [04:12<25:06,  4.43it/s]
 11%|█         | 810/7481 [04:12<25:06,  4.43it/s]

 11%|█         | 811/7481 [04:13<22:51,  4.86it/s]

 11%|█         | 811/7481 [04:13<22:51,  4.86it/s]
 11%|█         | 812/7481 [04:13<22:50,  4.86it/s]

 11%|█         | 813/7481 [04:14<26:56,  4.12it/s]

 11%|█         | 813/7481 [04:14<26:56,  4.12it/s]
 11%|█         | 814/7481 [04:14<26:56,  4.12it/s]
 11%|█         | 815/7481 [04:14<26:56,  4.12it/s]

 11%|█         | 816/7481 [04:14<27:49,  3.99it/s]

 11%|█         | 816/7481 [04:14<27:49,  3.99it/s]
 11%|█         | 817/7481 [04:14<27:49,  3.99it/s]

 11%|█         | 818/7481 [04:15<31:00,  3.58it/s]

 11%|█         | 818/7481 [04:15<31:00,  3.58it/s]
 11%|█         | 819/7481 [04:15<31:00,  3.58it/s]

 11%|█         | 820/7481 [04:16<34:12,  3.24it/s]

 11%|█         | 820/7481 [04:16<34:12,  3.24it/s]
 11%|█         | 821/7481 [04:16<34:12,  3.24it/s]

 11%|█         | 822/7481 [04:17<36:12,  3.06it/s]

 11%|█         | 822/7481 [04:17<36:12,  3.06it/s]
 11%|█         | 823/7481 [04:17<36:12,  3.06it/s]

 11%|█         | 824/7481 [04:17<37:58,  2.92it/s]

 11%|█         | 824/7481 [04:17<37:58,  2.92it/s]
 11%|█         | 825/7481 [04:18<37:57,  2.92it/s]

 11%|█         | 826/7481 [04:18<38:23,  2.89it/s]

 11%|█         | 826/7481 [04:18<38:23,  2.89it/s]
 11%|█         | 827/7481 [04:18<38:22,  2.89it/s]

 11%|█         | 828/7481 [04:19<40:19,  2.75it/s]

 11%|█         | 828/7481 [04:19<40:19,  2.75it/s]
 11%|█         | 829/7481 [04:19<40:19,  2.75it/s]

 11%|█         | 830/7481 [04:20<40:49,  2.72it/s]

 11%|█         | 830/7481 [04:20<40:49,  2.72it/s]
 11%|█         | 831/7481 [04:20<40:48,  2.72it/s]

 11%|█         | 832/7481 [04:21<41:18,  2.68it/s]

 11%|█         | 832/7481 [04:21<41:18,  2.68it/s]
 11%|█         | 833/7481 [04:21<41:17,  2.68it/s]

 11%|█         | 834/7481 [04:21<41:24,  2.68it/s]

 11%|█         | 834/7481 [04:21<41:24,  2.68it/s]
 11%|█         | 835/7481 [04:21<41:23,  2.68it/s]

 11%|█         | 836/7481 [04:24<1:16:26,  1.45it/s]

 11%|█         | 836/7481 [04:24<1:16:26,  1.45it/s]
 11%|█         | 837/7481 [04:24<1:16:26,  1.45it/s]
 11%|█         | 838/7481 [04:24<1:16:25,  1.45it/s]

 11%|█         | 839/7481 [04:25<57:16,  1.93it/s]

 11%|█         | 839/7481 [04:25<57:16,  1.93it/s]
 11%|█         | 840/7481 [04:25<57:15,  1.93it/s]

 11%|█         | 841/7481 [04:26<51:59,  2.13it/s]

 11%|█         | 841/7481 [04:26<51:59,  2.13it/s]
 11%|█▏        | 842/7481 [04:26<51:59,  2.13it/s]

 11%|█▏        | 843/7481 [04:26<48:18,  2.29it/s]

 11%|█▏        | 843/7481 [04:26<48:18,  2.29it/s]
 11%|█▏        | 844/7481 [04:26<48:18,  2.29it/s]

 11%|█▏        | 845/7481 [04:27<45:27,  2.43it/s]

 11%|█▏        | 845/7481 [04:27<45:27,  2.43it/s]
 11%|█▏        | 846/7481 [04:27<45:27,  2.43it/s]

 11%|█▏        | 847/7481 [04:28<42:59,  2.57it/s]

 11%|█▏        | 847/7481 [04:28<42:59,  2.57it/s]
 11%|█▏        | 848/7481 [04:28<42:59,  2.57it/s]

 11%|█▏        | 849/7481 [04:28<41:44,  2.65it/s]

 11%|█▏        | 849/7481 [04:28<41:44,  2.65it/s]
 11%|█▏        | 850/7481 [04:28<41:43,  2.65it/s]
 11%|█▏        | 851/7481 [04:28<41:43,  2.65it/s]

 11%|█▏        | 852/7481 [04:29<35:36,  3.10it/s]

 11%|█▏        | 852/7481 [04:29<35:36,  3.10it/s]
 11%|█▏        | 853/7481 [04:29<35:35,  3.10it/s]

 11%|█▏        | 854/7481 [04:30<35:51,  3.08it/s]

 11%|█▏        | 854/7481 [04:30<35:51,  3.08it/s]
 11%|█▏        | 855/7481 [04:30<35:51,  3.08it/s]

 11%|█▏        | 856/7481 [04:30<36:27,  3.03it/s]

 11%|█▏        | 856/7481 [04:30<36:27,  3.03it/s]
 11%|█▏        | 857/7481 [04:30<36:26,  3.03it/s]

 11%|█▏        | 858/7481 [04:31<36:55,  2.99it/s]

 11%|█▏        | 858/7481 [04:31<36:55,  2.99it/s]
 11%|█▏        | 859/7481 [04:31<36:55,  2.99it/s]
 11%|█▏        | 860/7481 [04:31<36:55,  2.99it/s]
 12%|█▏        | 861/7481 [04:31<36:54,  2.99it/s]

 12%|█▏        | 862/7481 [04:32<28:32,  3.87it/s]

 12%|█▏        | 862/7481 [04:32<28:32,  3.87it/s]
 12%|█▏        | 863/7481 [04:32<28:32,  3.87it/s]

 12%|█▏        | 864/7481 [04:32<30:43,  3.59it/s]

 12%|█▏        | 864/7481 [04:32<30:43,  3.59it/s]
 12%|█▏        | 865/7481 [04:32<30:43,  3.59it/s]

 12%|█▏        | 866/7481 [04:33<32:26,  3.40it/s]

 12%|█▏        | 866/7481 [04:33<32:26,  3.40it/s]
 12%|█▏        | 867/7481 [04:33<32:26,  3.40it/s]

 12%|█▏        | 868/7481 [04:34<33:44,  3.27it/s]

 12%|█▏        | 868/7481 [04:34<33:44,  3.27it/s]
 12%|█▏        | 869/7481 [04:34<33:44,  3.27it/s]

 12%|█▏        | 870/7481 [04:37<1:09:32,  1.58it/s]

 12%|█▏        | 870/7481 [04:37<1:09:32,  1.58it/s]
 12%|█▏        | 871/7481 [04:37<1:09:31,  1.58it/s]

 12%|█▏        | 872/7481 [04:37<1:00:48,  1.81it/s]

 12%|█▏        | 872/7481 [04:37<1:00:48,  1.81it/s]
 12%|█▏        | 873/7481 [04:37<1:00:48,  1.81it/s]

 12%|█▏        | 874/7481 [04:38<53:29,  2.06it/s]

 12%|█▏        | 874/7481 [04:38<53:29,  2.06it/s]
 12%|█▏        | 875/7481 [04:38<53:29,  2.06it/s]

 12%|█▏        | 876/7481 [04:39<48:53,  2.25it/s]

 12%|█▏        | 876/7481 [04:39<48:53,  2.25it/s]
 12%|█▏        | 877/7481 [04:39<48:53,  2.25it/s]
 12%|█▏        | 878/7481 [04:39<48:52,  2.25it/s]

 12%|█▏        | 879/7481 [04:39<39:52,  2.76it/s]

 12%|█▏        | 879/7481 [04:39<39:52,  2.76it/s]
 12%|█▏        | 880/7481 [04:40<39:52,  2.76it/s]

 12%|█▏        | 881/7481 [04:40<38:29,  2.86it/s]

 12%|█▏        | 881/7481 [04:40<38:29,  2.86it/s]
 12%|█▏        | 882/7481 [04:40<38:29,  2.86it/s]

 12%|█▏        | 883/7481 [04:41<38:40,  2.84it/s]

 12%|█▏        | 883/7481 [04:41<38:40,  2.84it/s]
 12%|█▏        | 884/7481 [04:41<38:40,  2.84it/s]

 12%|█▏        | 885/7481 [04:42<38:37,  2.85it/s]

 12%|█▏        | 885/7481 [04:42<38:37,  2.85it/s]
 12%|█▏        | 886/7481 [04:42<38:37,  2.85it/s]

 12%|█▏        | 887/7481 [04:42<38:27,  2.86it/s]

 12%|█▏        | 887/7481 [04:42<38:27,  2.86it/s]
 12%|█▏        | 888/7481 [04:42<38:27,  2.86it/s]

 12%|█▏        | 889/7481 [04:43<38:18,  2.87it/s]

 12%|█▏        | 889/7481 [04:43<38:18,  2.87it/s]
 12%|█▏        | 890/7481 [04:43<38:18,  2.87it/s]

 12%|█▏        | 891/7481 [04:44<37:36,  2.92it/s]

 12%|█▏        | 891/7481 [04:44<37:36,  2.92it/s]
 12%|█▏        | 892/7481 [04:44<37:35,  2.92it/s]
 12%|█▏        | 893/7481 [04:44<37:35,  2.92it/s]
 12%|█▏        | 894/7481 [04:44<37:35,  2.92it/s]

 12%|█▏        | 895/7481 [04:44<29:11,  3.76it/s]

 12%|█▏        | 895/7481 [04:44<29:11,  3.76it/s]
 12%|█▏        | 896/7481 [04:44<29:11,  3.76it/s]

 12%|█▏        | 897/7481 [04:45<31:31,  3.48it/s]

 12%|█▏        | 897/7481 [04:45<31:31,  3.48it/s]
 12%|█▏        | 898/7481 [04:45<31:31,  3.48it/s]
 12%|█▏        | 899/7481 [04:45<31:31,  3.48it/s]

 12%|█▏        | 900/7481 [04:46<29:15,  3.75it/s]

 12%|█▏        | 900/7481 [04:46<29:15,  3.75it/s]
 12%|█▏        | 901/7481 [04:46<29:15,  3.75it/s]
 12%|█▏        | 902/7481 [04:46<29:14,  3.75it/s]
 12%|█▏        | 903/7481 [04:46<29:14,  3.75it/s]
 12%|█▏        | 904/7481 [04:46<29:14,  3.75it/s]

 12%|█▏        | 905/7481 [04:46<23:03,  4.75it/s]

 12%|█▏        | 905/7481 [04:46<23:03,  4.75it/s]
 12%|█▏        | 906/7481 [04:46<23:03,  4.75it/s]

 12%|█▏        | 907/7481 [04:49<52:05,  2.10it/s]

 12%|█▏        | 907/7481 [04:49<52:05,  2.10it/s]
 12%|█▏        | 908/7481 [04:49<52:04,  2.10it/s]

 12%|█▏        | 909/7481 [04:50<48:57,  2.24it/s]

 12%|█▏        | 909/7481 [04:50<48:57,  2.24it/s]
 12%|█▏        | 910/7481 [04:50<48:57,  2.24it/s]

 12%|█▏        | 911/7481 [04:51<46:03,  2.38it/s]

 12%|█▏        | 911/7481 [04:51<46:03,  2.38it/s]
 12%|█▏        | 912/7481 [04:51<46:02,  2.38it/s]

 12%|█▏        | 913/7481 [04:51<44:07,  2.48it/s]

 12%|█▏        | 913/7481 [04:51<44:07,  2.48it/s]
 12%|█▏        | 914/7481 [04:51<44:07,  2.48it/s]
 12%|█▏        | 915/7481 [04:51<44:06,  2.48it/s]

 12%|█▏        | 916/7481 [04:52<37:39,  2.91it/s]

 12%|█▏        | 916/7481 [04:52<37:39,  2.91it/s]
 12%|█▏        | 917/7481 [04:52<37:38,  2.91it/s]

 12%|█▏        | 918/7481 [04:53<37:34,  2.91it/s]

 12%|█▏        | 918/7481 [04:53<37:34,  2.91it/s]
 12%|█▏        | 919/7481 [04:53<37:34,  2.91it/s]
 12%|█▏        | 920/7481 [04:53<37:33,  2.91it/s]
 12%|█▏        | 921/7481 [04:53<37:33,  2.91it/s]
 12%|█▏        | 922/7481 [04:53<37:33,  2.91it/s]
 12%|█▏        | 923/7481 [04:53<37:32,  2.91it/s]

 12%|█▏        | 924/7481 [04:54<25:06,  4.35it/s]

 12%|█▏        | 924/7481 [04:54<25:06,  4.35it/s]
 12%|█▏        | 925/7481 [04:54<25:05,  4.35it/s]

 12%|█▏        | 926/7481 [04:54<27:48,  3.93it/s]

 12%|█▏        | 926/7481 [04:54<27:48,  3.93it/s]
 12%|█▏        | 927/7481 [04:54<27:47,  3.93it/s]

 12%|█▏        | 928/7481 [04:55<30:09,  3.62it/s]

 12%|█▏        | 928/7481 [04:55<30:09,  3.62it/s]
 12%|█▏        | 929/7481 [04:55<30:09,  3.62it/s]

 12%|█▏        | 930/7481 [04:56<32:30,  3.36it/s]

 12%|█▏        | 930/7481 [04:56<32:30,  3.36it/s]
 12%|█▏        | 931/7481 [04:56<32:30,  3.36it/s]

 12%|█▏        | 932/7481 [04:56<34:18,  3.18it/s]

 12%|█▏        | 932/7481 [04:56<34:18,  3.18it/s]
 12%|█▏        | 933/7481 [04:57<34:18,  3.18it/s]

 12%|█▏        | 934/7481 [04:57<35:05,  3.11it/s]

 12%|█▏        | 934/7481 [04:57<35:05,  3.11it/s]
 12%|█▏        | 935/7481 [04:57<35:05,  3.11it/s]
 13%|█▎        | 936/7481 [04:57<35:05,  3.11it/s]

 13%|█▎        | 937/7481 [04:58<31:43,  3.44it/s]

 13%|█▎        | 937/7481 [04:58<31:43,  3.44it/s]
 13%|█▎        | 938/7481 [04:58<31:43,  3.44it/s]

 13%|█▎        | 939/7481 [04:59<33:58,  3.21it/s]

 13%|█▎        | 939/7481 [04:59<33:58,  3.21it/s]
 13%|█▎        | 940/7481 [04:59<33:58,  3.21it/s]

 13%|█▎        | 941/7481 [05:01<1:02:25,  1.75it/s]

 13%|█▎        | 941/7481 [05:01<1:02:25,  1.75it/s]
 13%|█▎        | 942/7481 [05:01<1:02:25,  1.75it/s]
 13%|█▎        | 943/7481 [05:01<1:02:24,  1.75it/s]

 13%|█▎        | 944/7481 [05:02<53:53,  2.02it/s]

 13%|█▎        | 944/7481 [05:02<53:53,  2.02it/s]
 13%|█▎        | 945/7481 [05:02<53:53,  2.02it/s]
 13%|█▎        | 946/7481 [05:02<53:52,  2.02it/s]
 13%|█▎        | 947/7481 [05:02<53:52,  2.02it/s]

 13%|█▎        | 948/7481 [05:03<39:50,  2.73it/s]

 13%|█▎        | 948/7481 [05:03<39:50,  2.73it/s]
 13%|█▎        | 949/7481 [05:03<39:49,  2.73it/s]
 13%|█▎        | 950/7481 [05:03<39:49,  2.73it/s]

 13%|█▎        | 951/7481 [05:04<35:39,  3.05it/s]

 13%|█▎        | 951/7481 [05:04<35:39,  3.05it/s]
 13%|█▎        | 952/7481 [05:04<35:38,  3.05it/s]
 13%|█▎        | 953/7481 [05:04<35:38,  3.05it/s]

 13%|█▎        | 954/7481 [05:04<32:20,  3.36it/s]
 13%|█▎        | 960/7481 [05:05<18:17,  5.94it/s]

 13%|█▎        | 954/7481 [05:04<32:20,  3.36it/s]
 13%|█▎        | 955/7481 [05:04<32:20,  3.36it/s]
 13%|█▎        | 956/7481 [05:04<32:19,  3.36it/s]
 13%|█▎        | 957/7481 [05:04<32:19,  3.36it/s]
 13%|█▎        | 958/7481 [05:04<32:19,  3.36it/s]
 13%|█▎        | 959/7481 [05:04<32:18,  3.36it/s]
 13%|█▎        | 960/7481 [05:05<18:17,  5.94it/s]
 13%|█▎        | 961/7481 [05:05<18:16,  5.94it/s]
 13%|█▎        | 962/7481 [05:05<18:16,  5.94it/s]
 13%|█▎        | 963/7481 [05:05<18:16,  5.94it/s]

 13%|█▎        | 964/7481 [05:05<13:34,  8.00it/s]
 13%|█▎        | 969/7481 [05:05<09:31, 11.39it/s]

 13%|█▎        | 964/7481 [05:05<13:34,  8.00it/s]
 13%|█▎        | 965/7481 [05:05<13:34,  8.00it/s]
 13%|█▎        | 966/7481 [05:05<13:34,  8.00it/s]
 13%|█▎        | 967/7481 [05:05<13:34,  8.00it/s]
 13%|█▎        | 968/7481 [05:05<13:33,  8.00it/s]
 13%|█▎        | 969/7481 [05:05<09:31, 11.39it/s]
 13%|█▎        | 970/7481 [05:05<09:31, 11.39it/s]
 13%|█▎        | 971/7481 [05:05<09:31, 11.39it/s]
 13%|█▎        | 972/7481 [05:05<09:31, 11.39it/s]
 13%|█▎        | 973/7481 [05:05<09:31, 11.39it/s]
 13%|█▎        | 974/7481 [05:05<09:31, 11.39it/s]

 13%|█▎        | 975/7481 [05:05<06:45, 16.06it/s]
 13%|█▎        | 984/7481 [05:05<04:17, 25.23it/s]

 13%|█▎        | 975/7481 [05:05<06:45, 16.06it/s]
 13%|█▎        | 976/7481 [05:05<06:44, 16.06it/s]
 13%|█▎        | 977/7481 [05:05<06:44, 16.06it/s]
 13%|█▎        | 978/7481 [05:05<06:44, 16.06it/s]
 13%|█▎        | 979/7481 [05:05<06:44, 16.06it/s]
 13%|█▎        | 980/7481 [05:05<06:44, 16.06it/s]
 13%|█▎        | 981/7481 [05:05<06:44, 16.06it/s]
 13%|█▎        | 982/7481 [05:05<06:44, 16.06it/s]
 13%|█▎        | 983/7481 [05:05<06:44, 16.06it/s]
 13%|█▎        | 984/7481 [05:05<04:17, 25.23it/s]
 13%|█▎        | 985/7481 [05:06<04:17, 25.23it/s]
 13%|█▎        | 986/7481 [05:06<04:17, 25.23it/s]
 13%|█▎        | 987/7481 [05:06<04:17, 25.23it/s]
 13%|█▎        | 988/7481 [05:06<04:17, 25.23it/s]

 13%|█▎        | 990/7481 [05:07<13:47,  7.84it/s]

 13%|█▎        | 989/7481 [05:07<04:17, 25.23it/s]
 13%|█▎        | 990/7481 [05:07<13:47,  7.84it/s]
 13%|█▎        | 991/7481 [05:08<13:47,  7.84it/s]
 13%|█▎        | 992/7481 [05:08<13:47,  7.84it/s]

 13%|█▎        | 994/7481 [05:08<18:02,  5.99it/s]

 13%|█▎        | 993/7481 [05:08<13:47,  7.84it/s]
 13%|█▎        | 994/7481 [05:08<18:02,  5.99it/s]
 13%|█▎        | 995/7481 [05:09<18:02,  5.99it/s]
 13%|█▎        | 996/7481 [05:09<18:01,  5.99it/s]

 13%|█▎        | 997/7481 [05:09<23:02,  4.69it/s]

 13%|█▎        | 997/7481 [05:09<23:02,  4.69it/s]
 13%|█▎        | 998/7481 [05:09<23:02,  4.69it/s]

 13%|█▎        | 1000/7481 [05:10<33:33,  3.22it/s]
 78%|███████▊  | 7/9 [33:42<09:58, 299.15s/it]

 13%|█▎        | 999/7481 [05:10<25:20,  4.26it/s]
 13%|█▎        | 1000/7481 [05:10<25:20,  4.26it/s]
                     MLUT4_AT.232A  MLUT4_RQ.2BTLS  MLUT4_TE.252A  \
Time
2025-05-25 05:20:05       0.852984        0.855904       0.842414
2025-05-25 05:30:05       0.876511        0.874611       0.847393
2025-05-25 05:35:05       0.877479        0.885625       0.860507
2025-05-25 05:40:05       0.878625        0.849563       0.860377
2025-05-25 05:45:05       0.877141        0.871733       0.849503

                     MLUT4_SIV.B7921  MLUT4_AIA792101B  MLUT4_PDT.956  \
Time
2025-05-25 05:20:05         0.903258          0.872434       0.899219
2025-05-25 05:30:05         0.903158          0.872244       0.916372
2025-05-25 05:35:05         0.903349          0.872158       0.914016
2025-05-25 05:40:05         0.903300          0.872148       0.910043
2025-05-25 05:45:05         0.903219          0.872148       0.914286

                     MLUT4_TE.252F  MLUT4_PT.231  MLUT4_FIC.231C  \
Time
2025-05-25 05:20:05       0.887579      0.869354        0.857897
2025-05-25 05:30:05       0.879727      0.867235        0.857888
2025-05-25 05:35:05       0.893944      0.867041        0.857883
2025-05-25 05:40:05       0.872940      0.866275        0.857879
2025-05-25 05:45:05       0.876962      0.865383        0.857874

                     MLUT4_FIC.231A  ...  DeSOx_2nd  MLUT4_AIC.232B  \
Time                                 ...
2025-05-25 05:20:05        0.859975  ...   0.893886       85.012138
2025-05-25 05:30:05        0.856716  ...   0.893778       88.954571
2025-05-25 05:35:05        0.860662  ...   0.892876       93.745851
2025-05-25 05:40:05        0.859286  ...   0.891253       85.305571
2025-05-25 05:45:05        0.859582  ...   0.890520      101.874866

                     MLUT4_AT.240  prev_target  MLUT4_AT-240  prediction  \
Time
2025-05-25 05:20:05     14.151761     0.888806      9.020973    0.889775
2025-05-25 05:30:05      9.316637     0.890104      9.448959    0.889592
2025-05-25 05:35:05      6.155893     0.890862     10.042477    0.892363
2025-05-25 05:40:05     12.572007     0.891577      9.276738    0.893389
2025-05-25 05:45:05      5.497275     0.891864     11.153274    0.892113

                     abs_error  threshold  y3_prediction  y3_abs_error
Time
2025-05-25 05:20:05   0.004111   0.004111       9.370424      0.349452
2025-05-25 05:30:05   0.004185   0.004178       9.821260      0.372300
2025-05-25 05:35:05   0.000513   0.000513      10.090555      0.048078
2025-05-25 05:40:05   0.002136   0.001974       9.094488      0.182250
2025-05-25 05:45:05   0.001593   0.001593      10.990971      0.162304

[5 rows x 50 columns]

  0%|          | 0/7480 [00:00<?, ?it/s]

  0%|          | 0/7480 [00:00<?, ?it/s]

  0%|          | 1/7480 [00:00<1:16:29,  1.63it/s]

  0%|          | 1/7480 [00:00<1:16:29,  1.63it/s]
  0%|          | 2/7480 [00:00<1:16:29,  1.63it/s]
  0%|          | 3/7480 [00:00<1:16:28,  1.63it/s]
  0%|          | 4/7480 [00:00<1:16:27,  1.63it/s]
  0%|          | 5/7480 [00:00<1:16:27,  1.63it/s]
  0%|          | 6/7480 [00:00<1:16:26,  1.63it/s]
  0%|          | 7/7480 [00:00<1:16:26,  1.63it/s]
  0%|          | 8/7480 [00:00<1:16:25,  1.63it/s]

  0%|          | 9/7480 [00:01<15:16,  8.15it/s]

  0%|          | 9/7480 [00:01<15:16,  8.15it/s]
  0%|          | 10/7480 [00:01<15:16,  8.15it/s]

  0%|          | 11/7480 [00:01<21:19,  5.84it/s]

  0%|          | 11/7480 [00:01<21:19,  5.84it/s]
  0%|          | 12/7480 [00:01<21:19,  5.84it/s]

  0%|          | 13/7480 [00:02<25:19,  4.91it/s]

  0%|          | 13/7480 [00:02<25:19,  4.91it/s]
  0%|          | 14/7480 [00:02<25:19,  4.91it/s]

  0%|          | 15/7480 [00:03<29:04,  4.28it/s]

  0%|          | 15/7480 [00:03<29:04,  4.28it/s]
  0%|          | 16/7480 [00:03<29:04,  4.28it/s]

  0%|          | 17/7480 [00:03<32:14,  3.86it/s]

  0%|          | 17/7480 [00:03<32:14,  3.86it/s]
  0%|          | 18/7480 [00:03<32:14,  3.86it/s]

  0%|          | 19/7480 [00:04<34:39,  3.59it/s]

  0%|          | 19/7480 [00:04<34:39,  3.59it/s]
  0%|          | 20/7480 [00:04<34:39,  3.59it/s]

  0%|          | 21/7480 [00:05<36:24,  3.41it/s]

  0%|          | 21/7480 [00:05<36:24,  3.41it/s]
  0%|          | 22/7480 [00:05<36:24,  3.41it/s]

  0%|          | 23/7480 [00:05<36:16,  3.43it/s]

  0%|          | 23/7480 [00:05<36:16,  3.43it/s]
  0%|          | 24/7480 [00:05<36:16,  3.43it/s]

  0%|          | 25/7480 [00:06<36:57,  3.36it/s]

  0%|          | 25/7480 [00:06<36:57,  3.36it/s]
  0%|          | 26/7480 [00:06<36:57,  3.36it/s]

  0%|          | 27/7480 [00:06<36:59,  3.36it/s]

  0%|          | 27/7480 [00:06<36:59,  3.36it/s]
  0%|          | 28/7480 [00:06<36:59,  3.36it/s]

  0%|          | 29/7480 [00:07<37:36,  3.30it/s]

  0%|          | 29/7480 [00:07<37:36,  3.30it/s]
  0%|          | 30/7480 [00:07<37:35,  3.30it/s]

  0%|          | 31/7480 [00:08<38:14,  3.25it/s]

  0%|          | 31/7480 [00:08<38:14,  3.25it/s]
  0%|          | 32/7480 [00:08<38:13,  3.25it/s]

  0%|          | 33/7480 [00:08<38:11,  3.25it/s]

  0%|          | 33/7480 [00:08<38:11,  3.25it/s]
  0%|          | 34/7480 [00:08<38:11,  3.25it/s]
  0%|          | 35/7480 [00:08<38:11,  3.25it/s]
  0%|          | 36/7480 [00:08<38:10,  3.25it/s]

  0%|          | 37/7480 [00:09<30:12,  4.11it/s]

  0%|          | 37/7480 [00:09<30:12,  4.11it/s]
  1%|          | 38/7480 [00:09<30:12,  4.11it/s]

  1%|          | 39/7480 [00:12<1:06:24,  1.87it/s]

  1%|          | 39/7480 [00:12<1:06:24,  1.87it/s]
  1%|          | 40/7480 [00:12<1:06:23,  1.87it/s]

  1%|          | 41/7480 [00:12<59:23,  2.09it/s]

  1%|          | 41/7480 [00:12<59:23,  2.09it/s]
  1%|          | 42/7480 [00:12<59:23,  2.09it/s]

  1%|          | 43/7480 [00:13<53:17,  2.33it/s]

  1%|          | 43/7480 [00:13<53:17,  2.33it/s]
  1%|          | 44/7480 [00:13<53:17,  2.33it/s]

  1%|          | 45/7480 [00:14<48:27,  2.56it/s]

  1%|          | 45/7480 [00:14<48:27,  2.56it/s]
  1%|          | 46/7480 [00:14<48:27,  2.56it/s]

  1%|          | 47/7480 [00:14<45:55,  2.70it/s]

  1%|          | 47/7480 [00:14<45:55,  2.70it/s]
  1%|          | 48/7480 [00:14<45:55,  2.70it/s]

  1%|          | 49/7480 [00:15<43:28,  2.85it/s]

  1%|          | 49/7480 [00:15<43:28,  2.85it/s]
  1%|          | 50/7480 [00:15<43:28,  2.85it/s]

  1%|          | 51/7480 [00:15<42:22,  2.92it/s]

  1%|          | 51/7480 [00:15<42:22,  2.92it/s]
  1%|          | 52/7480 [00:16<42:22,  2.92it/s]

  1%|          | 53/7480 [00:16<41:00,  3.02it/s]

  1%|          | 53/7480 [00:16<41:00,  3.02it/s]
  1%|          | 54/7480 [00:16<41:00,  3.02it/s]

  1%|          | 55/7480 [00:17<39:48,  3.11it/s]

  1%|          | 55/7480 [00:17<39:48,  3.11it/s]
  1%|          | 56/7480 [00:17<39:48,  3.11it/s]

  1%|          | 57/7480 [00:17<39:55,  3.10it/s]

  1%|          | 57/7480 [00:17<39:55,  3.10it/s]
  1%|          | 58/7480 [00:17<39:54,  3.10it/s]

  1%|          | 59/7480 [00:18<39:18,  3.15it/s]

  1%|          | 59/7480 [00:18<39:18,  3.15it/s]
  1%|          | 60/7480 [00:18<39:17,  3.15it/s]

  1%|          | 61/7480 [00:19<39:43,  3.11it/s]

  1%|          | 61/7480 [00:19<39:43,  3.11it/s]
  1%|          | 62/7480 [00:19<39:43,  3.11it/s]

  1%|          | 63/7480 [00:19<39:38,  3.12it/s]

  1%|          | 63/7480 [00:19<39:38,  3.12it/s]
  1%|          | 64/7480 [00:19<39:38,  3.12it/s]

  1%|          | 65/7480 [00:20<39:07,  3.16it/s]

  1%|          | 65/7480 [00:20<39:07,  3.16it/s]
  1%|          | 66/7480 [00:20<39:07,  3.16it/s]
  1%|          | 67/7480 [00:20<39:06,  3.16it/s]

  1%|          | 68/7480 [00:21<34:39,  3.57it/s]

  1%|          | 68/7480 [00:21<34:39,  3.57it/s]
  1%|          | 69/7480 [00:21<34:38,  3.57it/s]

  1%|          | 70/7480 [00:21<35:31,  3.48it/s]

  1%|          | 70/7480 [00:21<35:31,  3.48it/s]
  1%|          | 71/7480 [00:21<35:30,  3.48it/s]

  1%|          | 72/7480 [00:23<1:03:59,  1.93it/s]

  1%|          | 72/7480 [00:23<1:03:59,  1.93it/s]
  1%|          | 73/7480 [00:23<1:03:59,  1.93it/s]

  1%|          | 74/7480 [00:25<1:07:31,  1.83it/s]

  1%|          | 74/7480 [00:25<1:07:31,  1.83it/s]
  1%|          | 75/7480 [00:25<1:07:30,  1.83it/s]

  1%|          | 76/7480 [00:25<59:03,  2.09it/s]

  1%|          | 76/7480 [00:25<59:03,  2.09it/s]
  1%|          | 77/7480 [00:25<59:02,  2.09it/s]

  1%|          | 78/7480 [00:26<53:23,  2.31it/s]

  1%|          | 78/7480 [00:26<53:23,  2.31it/s]
  1%|          | 79/7480 [00:26<53:23,  2.31it/s]

  1%|          | 80/7480 [00:27<49:57,  2.47it/s]

  1%|          | 80/7480 [00:27<49:57,  2.47it/s]
  1%|          | 81/7480 [00:27<49:56,  2.47it/s]

  1%|          | 82/7480 [00:27<47:52,  2.58it/s]

  1%|          | 82/7480 [00:27<47:52,  2.58it/s]
  1%|          | 83/7480 [00:27<47:51,  2.58it/s]

  1%|          | 84/7480 [00:28<46:37,  2.64it/s]

  1%|          | 84/7480 [00:28<46:37,  2.64it/s]
  1%|          | 85/7480 [00:28<46:37,  2.64it/s]

  1%|          | 86/7480 [00:29<45:22,  2.72it/s]

  1%|          | 86/7480 [00:29<45:22,  2.72it/s]
  1%|          | 87/7480 [00:29<45:22,  2.72it/s]

  1%|          | 88/7480 [00:29<44:43,  2.75it/s]

  1%|          | 88/7480 [00:29<44:43,  2.75it/s]
  1%|          | 89/7480 [00:29<44:43,  2.75it/s]
  1%|          | 90/7480 [00:29<44:42,  2.75it/s]

  1%|          | 91/7480 [00:30<39:12,  3.14it/s]

  1%|          | 91/7480 [00:30<39:12,  3.14it/s]
  1%|          | 92/7480 [00:30<39:12,  3.14it/s]

  1%|          | 93/7480 [00:31<41:02,  3.00it/s]

  1%|          | 93/7480 [00:31<41:02,  3.00it/s]
  1%|▏         | 94/7480 [00:31<41:02,  3.00it/s]

  1%|▏         | 95/7480 [00:32<41:19,  2.98it/s]

  1%|▏         | 95/7480 [00:32<41:19,  2.98it/s]
  1%|▏         | 96/7480 [00:32<41:19,  2.98it/s]

  1%|▏         | 97/7480 [00:32<42:00,  2.93it/s]

  1%|▏         | 97/7480 [00:32<42:00,  2.93it/s]
  1%|▏         | 98/7480 [00:32<42:00,  2.93it/s]

  1%|▏         | 99/7480 [00:33<43:33,  2.82it/s]

  1%|▏         | 99/7480 [00:33<43:33,  2.82it/s]
  1%|▏         | 100/7480 [00:33<43:33,  2.82it/s]
  1%|▏         | 101/7480 [00:33<43:33,  2.82it/s]
  1%|▏         | 102/7480 [00:33<43:32,  2.82it/s]

  1%|▏         | 103/7480 [00:34<33:17,  3.69it/s]

  1%|▏         | 103/7480 [00:34<33:17,  3.69it/s]
  1%|▏         | 104/7480 [00:34<33:17,  3.69it/s]

  1%|▏         | 105/7480 [00:35<48:57,  2.51it/s]

  1%|▏         | 105/7480 [00:35<48:57,  2.51it/s]
  1%|▏         | 106/7480 [00:35<48:57,  2.51it/s]

  1%|▏         | 107/7480 [00:37<1:10:04,  1.75it/s]

  1%|▏         | 107/7480 [00:37<1:10:04,  1.75it/s]
  1%|▏         | 108/7480 [00:37<1:10:03,  1.75it/s]

  1%|▏         | 109/7480 [00:38<1:03:18,  1.94it/s]

  1%|▏         | 109/7480 [00:38<1:03:18,  1.94it/s]
  1%|▏         | 110/7480 [00:38<1:03:17,  1.94it/s]

  1%|▏         | 111/7480 [00:39<57:56,  2.12it/s]

  1%|▏         | 111/7480 [00:39<57:56,  2.12it/s]
  1%|▏         | 112/7480 [00:39<57:56,  2.12it/s]

  2%|▏         | 113/7480 [00:40<54:32,  2.25it/s]

  2%|▏         | 113/7480 [00:40<54:32,  2.25it/s]
  2%|▏         | 114/7480 [00:40<54:31,  2.25it/s]

  2%|▏         | 115/7480 [00:40<50:54,  2.41it/s]

  2%|▏         | 115/7480 [00:40<50:54,  2.41it/s]
  2%|▏         | 116/7480 [00:40<50:54,  2.41it/s]

  2%|▏         | 117/7480 [00:41<49:03,  2.50it/s]

  2%|▏         | 117/7480 [00:41<49:03,  2.50it/s]
  2%|▏         | 118/7480 [00:41<49:03,  2.50it/s]

  2%|▏         | 119/7480 [00:42<47:56,  2.56it/s]

  2%|▏         | 119/7480 [00:42<47:56,  2.56it/s]
  2%|▏         | 120/7480 [00:42<47:55,  2.56it/s]

  2%|▏         | 121/7480 [00:42<46:21,  2.65it/s]

  2%|▏         | 121/7480 [00:42<46:21,  2.65it/s]
  2%|▏         | 122/7480 [00:42<46:21,  2.65it/s]
  2%|▏         | 123/7480 [00:42<46:20,  2.65it/s]
  2%|▏         | 124/7480 [00:42<46:20,  2.65it/s]
  2%|▏         | 125/7480 [00:42<46:20,  2.65it/s]
  2%|▏         | 126/7480 [00:42<46:19,  2.65it/s]
  2%|▏         | 127/7480 [00:42<46:19,  2.65it/s]

  2%|▏         | 128/7480 [00:43<25:57,  4.72it/s]

  2%|▏         | 128/7480 [00:43<25:57,  4.72it/s]
  2%|▏         | 129/7480 [00:43<25:57,  4.72it/s]

  2%|▏         | 130/7480 [00:44<29:26,  4.16it/s]
  2%|▏         | 134/7480 [00:44<20:04,  6.10it/s]

  2%|▏         | 130/7480 [00:44<29:26,  4.16it/s]
  2%|▏         | 131/7480 [00:44<29:26,  4.16it/s]
  2%|▏         | 132/7480 [00:44<29:26,  4.16it/s]
  2%|▏         | 133/7480 [00:44<29:26,  4.16it/s]
  2%|▏         | 134/7480 [00:44<20:04,  6.10it/s]
  2%|▏         | 135/7480 [00:44<20:04,  6.10it/s]
  2%|▏         | 136/7480 [00:44<20:04,  6.10it/s]
  2%|▏         | 137/7480 [00:44<20:04,  6.10it/s]
  2%|▏         | 138/7480 [00:44<20:04,  6.10it/s]
  2%|▏         | 139/7480 [00:44<20:03,  6.10it/s]
  2%|▏         | 140/7480 [00:44<20:03,  6.10it/s]
  2%|▏         | 141/7480 [00:44<20:03,  6.10it/s]
  2%|▏         | 142/7480 [00:44<20:03,  6.10it/s]

  2%|▏         | 143/7480 [00:45<14:41,  8.33it/s]

  2%|▏         | 143/7480 [00:45<14:41,  8.33it/s]
  2%|▏         | 144/7480 [00:45<14:40,  8.33it/s]

  2%|▏         | 145/7480 [00:45<18:35,  6.57it/s]
  2%|▏         | 149/7480 [00:45<14:02,  8.70it/s]

  2%|▏         | 145/7480 [00:45<18:35,  6.57it/s]
  2%|▏         | 146/7480 [00:45<18:35,  6.57it/s]
  2%|▏         | 147/7480 [00:45<18:35,  6.57it/s]
  2%|▏         | 148/7480 [00:45<18:35,  6.57it/s]
  2%|▏         | 149/7480 [00:45<14:02,  8.70it/s]
  2%|▏         | 150/7480 [00:46<14:02,  8.70it/s]
  2%|▏         | 151/7480 [00:46<14:02,  8.70it/s]
  2%|▏         | 152/7480 [00:46<14:02,  8.70it/s]

  2%|▏         | 153/7480 [00:46<16:11,  7.54it/s]

  2%|▏         | 153/7480 [00:46<16:11,  7.54it/s]
  2%|▏         | 154/7480 [00:46<16:11,  7.54it/s]

  2%|▏         | 155/7480 [00:47<20:53,  5.84it/s]

  2%|▏         | 155/7480 [00:47<20:53,  5.84it/s]
  2%|▏         | 156/7480 [00:47<20:53,  5.84it/s]

  2%|▏         | 157/7480 [00:50<53:23,  2.29it/s]

  2%|▏         | 157/7480 [00:50<53:23,  2.29it/s]
  2%|▏         | 158/7480 [00:50<53:23,  2.29it/s]

  2%|▏         | 159/7480 [00:51<50:58,  2.39it/s]

  2%|▏         | 159/7480 [00:51<50:58,  2.39it/s]
  2%|▏         | 160/7480 [00:51<50:57,  2.39it/s]

  2%|▏         | 161/7480 [00:51<49:30,  2.46it/s]

  2%|▏         | 161/7480 [00:51<49:30,  2.46it/s]
  2%|▏         | 162/7480 [00:51<49:29,  2.46it/s]

  2%|▏         | 163/7480 [00:52<48:20,  2.52it/s]

  2%|▏         | 163/7480 [00:52<48:20,  2.52it/s]
  2%|▏         | 164/7480 [00:52<48:19,  2.52it/s]

  2%|▏         | 165/7480 [00:53<46:24,  2.63it/s]

  2%|▏         | 165/7480 [00:53<46:24,  2.63it/s]
  2%|▏         | 166/7480 [00:53<46:24,  2.63it/s]
  2%|▏         | 167/7480 [00:53<46:24,  2.63it/s]

  2%|▏         | 168/7480 [00:53<40:16,  3.03it/s]

  2%|▏         | 168/7480 [00:53<40:16,  3.03it/s]
  2%|▏         | 169/7480 [00:54<40:16,  3.03it/s]

  2%|▏         | 170/7480 [00:54<41:57,  2.90it/s]

  2%|▏         | 170/7480 [00:54<41:57,  2.90it/s]
  2%|▏         | 171/7480 [00:54<41:57,  2.90it/s]

  2%|▏         | 172/7480 [00:55<42:36,  2.86it/s]

  2%|▏         | 172/7480 [00:55<42:36,  2.86it/s]
  2%|▏         | 173/7480 [00:55<42:36,  2.86it/s]
  2%|▏         | 174/7480 [00:55<42:36,  2.86it/s]
  2%|▏         | 175/7480 [00:55<42:35,  2.86it/s]

  2%|▏         | 176/7480 [00:56<33:57,  3.59it/s]

  2%|▏         | 176/7480 [00:56<33:57,  3.59it/s]
  2%|▏         | 177/7480 [00:56<33:56,  3.59it/s]

  2%|▏         | 178/7480 [00:56<36:36,  3.32it/s]

  2%|▏         | 178/7480 [00:56<36:36,  3.32it/s]
  2%|▏         | 179/7480 [00:56<36:36,  3.32it/s]

  2%|▏         | 180/7480 [00:57<38:49,  3.13it/s]
  2%|▏         | 185/7480 [00:57<21:37,  5.62it/s]

  2%|▏         | 180/7480 [00:57<38:49,  3.13it/s]
  2%|▏         | 181/7480 [00:57<38:48,  3.13it/s]
  2%|▏         | 182/7480 [00:57<38:48,  3.13it/s]
  2%|▏         | 183/7480 [00:57<38:48,  3.13it/s]
  2%|▏         | 184/7480 [00:57<38:47,  3.13it/s]
  2%|▏         | 185/7480 [00:57<21:37,  5.62it/s]
  2%|▏         | 186/7480 [00:57<21:37,  5.62it/s]
  2%|▎         | 187/7480 [00:57<21:37,  5.62it/s]
  3%|▎         | 188/7480 [00:57<21:37,  5.62it/s]
  3%|▎         | 189/7480 [00:57<21:37,  5.62it/s]
  3%|▎         | 190/7480 [00:57<21:36,  5.62it/s]
  3%|▎         | 191/7480 [00:57<21:36,  5.62it/s]

  3%|▎         | 192/7480 [00:58<17:09,  7.08it/s]

  3%|▎         | 192/7480 [00:58<17:09,  7.08it/s]
  3%|▎         | 193/7480 [00:58<17:09,  7.08it/s]

  3%|▎         | 194/7480 [00:59<21:53,  5.55it/s]

  3%|▎         | 194/7480 [00:59<21:53,  5.55it/s]
  3%|▎         | 195/7480 [00:59<21:53,  5.55it/s]

  3%|▎         | 196/7480 [01:00<26:18,  4.61it/s]

  3%|▎         | 196/7480 [01:00<26:18,  4.61it/s]
  3%|▎         | 197/7480 [01:00<26:18,  4.61it/s]

  3%|▎         | 198/7480 [01:02<59:08,  2.05it/s]

  3%|▎         | 198/7480 [01:02<59:08,  2.05it/s]
  3%|▎         | 199/7480 [01:03<59:07,  2.05it/s]

  3%|▎         | 200/7480 [01:03<55:50,  2.17it/s]

  3%|▎         | 200/7480 [01:03<55:50,  2.17it/s]
  3%|▎         | 201/7480 [01:03<55:50,  2.17it/s]
  3%|▎         | 202/7480 [01:03<55:49,  2.17it/s]
  3%|▎         | 203/7480 [01:03<55:49,  2.17it/s]

  3%|▎         | 204/7480 [01:04<42:25,  2.86it/s]

  3%|▎         | 204/7480 [01:04<42:25,  2.86it/s]
  3%|▎         | 205/7480 [01:04<42:25,  2.86it/s]

  3%|▎         | 206/7480 [01:05<42:49,  2.83it/s]

  3%|▎         | 206/7480 [01:05<42:49,  2.83it/s]
  3%|▎         | 207/7480 [01:05<42:49,  2.83it/s]

  3%|▎         | 208/7480 [01:05<42:49,  2.83it/s]

  3%|▎         | 208/7480 [01:05<42:49,  2.83it/s]
  3%|▎         | 209/7480 [01:05<42:49,  2.83it/s]

  3%|▎         | 210/7480 [01:06<42:58,  2.82it/s]

  3%|▎         | 210/7480 [01:06<42:58,  2.82it/s]
  3%|▎         | 211/7480 [01:06<42:58,  2.82it/s]

  3%|▎         | 212/7480 [01:07<42:56,  2.82it/s]

  3%|▎         | 212/7480 [01:07<42:56,  2.82it/s]
  3%|▎         | 213/7480 [01:07<42:56,  2.82it/s]

  3%|▎         | 214/7480 [01:08<42:39,  2.84it/s]

  3%|▎         | 214/7480 [01:08<42:39,  2.84it/s]
  3%|▎         | 215/7480 [01:08<42:39,  2.84it/s]

  3%|▎         | 216/7480 [01:08<43:22,  2.79it/s]

  3%|▎         | 216/7480 [01:08<43:22,  2.79it/s]
  3%|▎         | 217/7480 [01:08<43:21,  2.79it/s]

  3%|▎         | 218/7480 [01:09<43:51,  2.76it/s]

  3%|▎         | 218/7480 [01:09<43:51,  2.76it/s]
  3%|▎         | 219/7480 [01:09<43:51,  2.76it/s]

  3%|▎         | 220/7480 [01:10<44:01,  2.75it/s]

  3%|▎         | 220/7480 [01:10<44:01,  2.75it/s]
  3%|▎         | 221/7480 [01:10<44:01,  2.75it/s]

  3%|▎         | 222/7480 [01:11<44:52,  2.70it/s]

  3%|▎         | 222/7480 [01:11<44:52,  2.70it/s]
  3%|▎         | 223/7480 [01:11<44:52,  2.70it/s]

  3%|▎         | 224/7480 [01:11<45:38,  2.65it/s]

  3%|▎         | 224/7480 [01:11<45:38,  2.65it/s]
  3%|▎         | 225/7480 [01:11<45:38,  2.65it/s]

  3%|▎         | 226/7480 [01:12<46:04,  2.62it/s]

  3%|▎         | 226/7480 [01:12<46:04,  2.62it/s]
  3%|▎         | 227/7480 [01:12<46:04,  2.62it/s]

  3%|▎         | 228/7480 [01:15<1:25:37,  1.41it/s]

  3%|▎         | 228/7480 [01:15<1:25:37,  1.41it/s]
  3%|▎         | 229/7480 [01:15<1:25:36,  1.41it/s]
  3%|▎         | 230/7480 [01:15<1:25:35,  1.41it/s]

  3%|▎         | 231/7480 [01:16<1:04:06,  1.88it/s]

  3%|▎         | 231/7480 [01:16<1:04:06,  1.88it/s]
  3%|▎         | 232/7480 [01:16<1:04:06,  1.88it/s]
  3%|▎         | 233/7480 [01:16<1:04:05,  1.88it/s]

  3%|▎         | 234/7480 [01:17<51:59,  2.32it/s]

  3%|▎         | 234/7480 [01:17<51:59,  2.32it/s]
  3%|▎         | 235/7480 [01:17<51:58,  2.32it/s]

  3%|▎         | 236/7480 [01:17<50:12,  2.40it/s]

  3%|▎         | 236/7480 [01:17<50:12,  2.40it/s]
  3%|▎         | 237/7480 [01:17<50:12,  2.40it/s]

  3%|▎         | 238/7480 [01:18<48:11,  2.50it/s]

  3%|▎         | 238/7480 [01:18<48:11,  2.50it/s]
  3%|▎         | 239/7480 [01:18<48:11,  2.50it/s]

  3%|▎         | 240/7480 [01:19<47:24,  2.55it/s]

  3%|▎         | 240/7480 [01:19<47:24,  2.55it/s]
  3%|▎         | 241/7480 [01:19<47:23,  2.55it/s]

  3%|▎         | 242/7480 [01:20<47:22,  2.55it/s]

  3%|▎         | 242/7480 [01:20<47:22,  2.55it/s]
  3%|▎         | 243/7480 [01:20<47:22,  2.55it/s]

  3%|▎         | 244/7480 [01:20<46:14,  2.61it/s]

  3%|▎         | 244/7480 [01:20<46:14,  2.61it/s]
  3%|▎         | 245/7480 [01:20<46:13,  2.61it/s]
  3%|▎         | 246/7480 [01:20<46:13,  2.61it/s]

  3%|▎         | 247/7480 [01:21<40:10,  3.00it/s]

  3%|▎         | 247/7480 [01:21<40:10,  3.00it/s]
  3%|▎         | 248/7480 [01:21<40:09,  3.00it/s]

  3%|▎         | 249/7480 [01:22<41:25,  2.91it/s]

  3%|▎         | 249/7480 [01:22<41:25,  2.91it/s]
  3%|▎         | 250/7480 [01:22<41:25,  2.91it/s]

  3%|▎         | 251/7480 [01:23<42:24,  2.84it/s]

  3%|▎         | 251/7480 [01:23<42:24,  2.84it/s]
  3%|▎         | 252/7480 [01:23<42:24,  2.84it/s]
  3%|▎         | 253/7480 [01:23<42:24,  2.84it/s]
  3%|▎         | 254/7480 [01:23<42:23,  2.84it/s]

  3%|▎         | 255/7480 [01:23<32:53,  3.66it/s]

  3%|▎         | 255/7480 [01:23<32:53,  3.66it/s]
  3%|▎         | 256/7480 [01:23<32:53,  3.66it/s]

  3%|▎         | 257/7480 [01:24<35:32,  3.39it/s]

  3%|▎         | 257/7480 [01:24<35:32,  3.39it/s]
  3%|▎         | 258/7480 [01:24<35:32,  3.39it/s]

  3%|▎         | 259/7480 [01:25<39:41,  3.03it/s]

  3%|▎         | 259/7480 [01:25<39:41,  3.03it/s]
  3%|▎         | 260/7480 [01:25<39:41,  3.03it/s]

  3%|▎         | 261/7480 [01:28<1:15:33,  1.59it/s]

  3%|▎         | 261/7480 [01:28<1:15:33,  1.59it/s]
  4%|▎         | 262/7480 [01:28<1:15:33,  1.59it/s]

  4%|▎         | 263/7480 [01:28<1:06:09,  1.82it/s]

  4%|▎         | 263/7480 [01:28<1:06:09,  1.82it/s]
  4%|▎         | 264/7480 [01:28<1:06:09,  1.82it/s]

  4%|▎         | 265/7480 [01:29<59:55,  2.01it/s]

  4%|▎         | 265/7480 [01:29<59:55,  2.01it/s]
  4%|▎         | 266/7480 [01:29<59:54,  2.01it/s]

  4%|▎         | 267/7480 [01:30<55:43,  2.16it/s]

  4%|▎         | 267/7480 [01:30<55:43,  2.16it/s]
  4%|▎         | 268/7480 [01:30<55:42,  2.16it/s]
  4%|▎         | 269/7480 [01:30<55:42,  2.16it/s]
  4%|▎         | 270/7480 [01:30<55:41,  2.16it/s]

  4%|▎         | 271/7480 [01:31<40:12,  2.99it/s]

  4%|▎         | 271/7480 [01:31<40:12,  2.99it/s]
  4%|▎         | 272/7480 [01:31<40:12,  2.99it/s]

  4%|▎         | 273/7480 [01:31<41:11,  2.92it/s]

  4%|▎         | 273/7480 [01:31<41:11,  2.92it/s]
  4%|▎         | 274/7480 [01:31<41:11,  2.92it/s]

  4%|▎         | 275/7480 [01:32<41:51,  2.87it/s]

  4%|▎         | 275/7480 [01:32<41:51,  2.87it/s]
  4%|▎         | 276/7480 [01:32<41:51,  2.87it/s]

  4%|▎         | 277/7480 [01:33<41:59,  2.86it/s]

  4%|▎         | 277/7480 [01:33<41:59,  2.86it/s]
  4%|▎         | 278/7480 [01:33<41:59,  2.86it/s]

  4%|▎         | 279/7480 [01:34<44:03,  2.72it/s]

  4%|▎         | 279/7480 [01:34<44:03,  2.72it/s]
  4%|▎         | 280/7480 [01:34<44:03,  2.72it/s]

  4%|▍         | 281/7480 [01:34<45:27,  2.64it/s]

  4%|▍         | 281/7480 [01:34<45:27,  2.64it/s]
  4%|▍         | 282/7480 [01:34<45:27,  2.64it/s]

  4%|▍         | 283/7480 [01:35<46:14,  2.59it/s]

  4%|▍         | 283/7480 [01:35<46:14,  2.59it/s]
  4%|▍         | 284/7480 [01:35<46:13,  2.59it/s]

  4%|▍         | 285/7480 [01:36<46:11,  2.60it/s]

  4%|▍         | 285/7480 [01:36<46:11,  2.60it/s]
  4%|▍         | 286/7480 [01:36<46:10,  2.60it/s]

  4%|▍         | 287/7480 [01:37<45:43,  2.62it/s]

  4%|▍         | 287/7480 [01:37<45:43,  2.62it/s]
  4%|▍         | 288/7480 [01:37<45:43,  2.62it/s]

  4%|▍         | 289/7480 [01:39<1:15:44,  1.58it/s]

  4%|▍         | 289/7480 [01:39<1:15:44,  1.58it/s]
  4%|▍         | 290/7480 [01:39<1:15:44,  1.58it/s]

  4%|▍         | 291/7480 [01:41<1:17:38,  1.54it/s]

  4%|▍         | 291/7480 [01:41<1:17:38,  1.54it/s]
  4%|▍         | 292/7480 [01:41<1:17:38,  1.54it/s]

  4%|▍         | 293/7480 [01:41<1:07:45,  1.77it/s]

  4%|▍         | 293/7480 [01:41<1:07:45,  1.77it/s]
  4%|▍         | 294/7480 [01:41<1:07:45,  1.77it/s]

  4%|▍         | 295/7480 [01:42<1:00:21,  1.98it/s]

  4%|▍         | 295/7480 [01:42<1:00:21,  1.98it/s]
  4%|▍         | 296/7480 [01:42<1:00:21,  1.98it/s]

  4%|▍         | 297/7480 [01:43<55:28,  2.16it/s]

  4%|▍         | 297/7480 [01:43<55:28,  2.16it/s]
  4%|▍         | 298/7480 [01:43<55:28,  2.16it/s]

  4%|▍         | 299/7480 [01:44<52:16,  2.29it/s]

  4%|▍         | 299/7480 [01:44<52:16,  2.29it/s]
  4%|▍         | 300/7480 [01:44<52:16,  2.29it/s]

  4%|▍         | 301/7480 [01:44<49:57,  2.39it/s]

  4%|▍         | 301/7480 [01:44<49:57,  2.39it/s]
  4%|▍         | 302/7480 [01:44<49:57,  2.39it/s]
  4%|▍         | 303/7480 [01:44<49:57,  2.39it/s]

  4%|▍         | 304/7480 [01:45<42:21,  2.82it/s]

  4%|▍         | 304/7480 [01:45<42:21,  2.82it/s]
  4%|▍         | 305/7480 [01:45<42:21,  2.82it/s]

  4%|▍         | 306/7480 [01:46<43:03,  2.78it/s]

  4%|▍         | 306/7480 [01:46<43:03,  2.78it/s]
  4%|▍         | 307/7480 [01:46<43:03,  2.78it/s]

  4%|▍         | 308/7480 [01:47<43:31,  2.75it/s]

  4%|▍         | 308/7480 [01:47<43:31,  2.75it/s]
  4%|▍         | 309/7480 [01:47<43:30,  2.75it/s]

  4%|▍         | 310/7480 [01:47<43:20,  2.76it/s]

  4%|▍         | 310/7480 [01:47<43:20,  2.76it/s]
  4%|▍         | 311/7480 [01:47<43:19,  2.76it/s]

  4%|▍         | 312/7480 [01:48<44:09,  2.71it/s]

  4%|▍         | 312/7480 [01:48<44:09,  2.71it/s]
  4%|▍         | 313/7480 [01:48<44:09,  2.71it/s]
  4%|▍         | 314/7480 [01:48<44:08,  2.71it/s]

  4%|▍         | 315/7480 [01:49<38:34,  3.10it/s]

  4%|▍         | 315/7480 [01:49<38:34,  3.10it/s]
  4%|▍         | 316/7480 [01:49<38:34,  3.10it/s]

  4%|▍         | 317/7480 [01:49<39:28,  3.02it/s]

  4%|▍         | 317/7480 [01:49<39:28,  3.02it/s]
  4%|▍         | 318/7480 [01:49<39:28,  3.02it/s]

  4%|▍         | 319/7480 [01:50<43:40,  2.73it/s]

  4%|▍         | 319/7480 [01:50<43:40,  2.73it/s]
  4%|▍         | 320/7480 [01:50<43:40,  2.73it/s]

  4%|▍         | 321/7480 [01:53<1:19:02,  1.51it/s]
  4%|▍         | 325/7480 [01:53<45:07,  2.64it/s]

  4%|▍         | 321/7480 [01:53<1:19:02,  1.51it/s]
  4%|▍         | 322/7480 [01:53<1:19:02,  1.51it/s]
  4%|▍         | 323/7480 [01:53<1:19:01,  1.51it/s]
  4%|▍         | 324/7480 [01:53<1:19:00,  1.51it/s]
  4%|▍         | 325/7480 [01:53<45:07,  2.64it/s]

  4%|▍         | 327/7480 [01:54<44:56,  2.65it/s]

  4%|▍         | 326/7480 [01:54<45:07,  2.64it/s]
  4%|▍         | 327/7480 [01:54<44:56,  2.65it/s]

  4%|▍         | 328/7480 [01:55<50:27,  2.36it/s]

  4%|▍         | 328/7480 [01:55<50:27,  2.36it/s]
  4%|▍         | 329/7480 [01:55<50:26,  2.36it/s]

  4%|▍         | 330/7480 [01:55<48:27,  2.46it/s]

  4%|▍         | 330/7480 [01:55<48:27,  2.46it/s]
  4%|▍         | 331/7480 [01:56<48:27,  2.46it/s]

  4%|▍         | 332/7480 [01:56<47:10,  2.53it/s]

  4%|▍         | 332/7480 [01:56<47:10,  2.53it/s]
  4%|▍         | 333/7480 [01:56<47:10,  2.53it/s]

  4%|▍         | 334/7480 [01:57<45:59,  2.59it/s]

  4%|▍         | 334/7480 [01:57<45:59,  2.59it/s]
  4%|▍         | 335/7480 [01:57<45:59,  2.59it/s]

  4%|▍         | 336/7480 [01:58<45:38,  2.61it/s]

  4%|▍         | 336/7480 [01:58<45:38,  2.61it/s]
  5%|▍         | 337/7480 [01:58<45:38,  2.61it/s]

  5%|▍         | 338/7480 [01:58<45:34,  2.61it/s]

  5%|▍         | 338/7480 [01:58<45:34,  2.61it/s]
  5%|▍         | 339/7480 [01:58<45:33,  2.61it/s]

  5%|▍         | 340/7480 [01:59<44:49,  2.65it/s]

  5%|▍         | 340/7480 [01:59<44:49,  2.65it/s]
  5%|▍         | 341/7480 [01:59<44:48,  2.65it/s]

  5%|▍         | 342/7480 [02:00<44:08,  2.69it/s]

  5%|▍         | 342/7480 [02:00<44:08,  2.69it/s]
  5%|▍         | 343/7480 [02:00<44:08,  2.69it/s]

  5%|▍         | 344/7480 [02:01<44:38,  2.66it/s]

  5%|▍         | 344/7480 [02:01<44:38,  2.66it/s]
  5%|▍         | 345/7480 [02:01<44:38,  2.66it/s]

  5%|▍         | 346/7480 [02:01<44:44,  2.66it/s]

  5%|▍         | 346/7480 [02:01<44:44,  2.66it/s]
  5%|▍         | 347/7480 [02:01<44:44,  2.66it/s]

  5%|▍         | 348/7480 [02:02<44:37,  2.66it/s]

  5%|▍         | 348/7480 [02:02<44:37,  2.66it/s]
  5%|▍         | 349/7480 [02:02<44:37,  2.66it/s]
  5%|▍         | 350/7480 [02:02<44:37,  2.66it/s]

  5%|▍         | 351/7480 [02:03<41:39,  2.85it/s]

  5%|▍         | 351/7480 [02:03<41:39,  2.85it/s]
  5%|▍         | 352/7480 [02:03<41:39,  2.85it/s]
  5%|▍         | 353/7480 [02:03<41:38,  2.85it/s]

  5%|▍         | 354/7480 [02:06<1:08:11,  1.74it/s]

  5%|▍         | 354/7480 [02:06<1:08:11,  1.74it/s]
  5%|▍         | 355/7480 [02:06<1:08:11,  1.74it/s]

  5%|▍         | 356/7480 [02:07<1:02:37,  1.90it/s]

  5%|▍         | 356/7480 [02:07<1:02:37,  1.90it/s]
  5%|▍         | 357/7480 [02:07<1:02:37,  1.90it/s]

  5%|▍         | 358/7480 [02:08<57:31,  2.06it/s]

  5%|▍         | 358/7480 [02:08<57:31,  2.06it/s]
  5%|▍         | 359/7480 [02:08<57:31,  2.06it/s]
  5%|▍         | 360/7480 [02:08<57:30,  2.06it/s]
  5%|▍         | 361/7480 [02:08<57:30,  2.06it/s]
  5%|▍         | 362/7480 [02:08<57:29,  2.06it/s]

  5%|▍         | 363/7480 [02:08<38:21,  3.09it/s]

  5%|▍         | 363/7480 [02:08<38:21,  3.09it/s]
  5%|▍         | 364/7480 [02:08<38:20,  3.09it/s]

  5%|▍         | 365/7480 [02:09<39:55,  2.97it/s]

  5%|▍         | 365/7480 [02:09<39:55,  2.97it/s]
  5%|▍         | 366/7480 [02:09<39:55,  2.97it/s]

  5%|▍         | 367/7480 [02:10<41:14,  2.87it/s]

  5%|▍         | 367/7480 [02:10<41:14,  2.87it/s]
  5%|▍         | 368/7480 [02:10<41:14,  2.87it/s]

  5%|▍         | 369/7480 [02:11<41:50,  2.83it/s]

  5%|▍         | 369/7480 [02:11<41:50,  2.83it/s]
  5%|▍         | 370/7480 [02:11<41:50,  2.83it/s]

  5%|▍         | 371/7480 [02:11<42:45,  2.77it/s]

  5%|▍         | 371/7480 [02:11<42:45,  2.77it/s]
  5%|▍         | 372/7480 [02:11<42:44,  2.77it/s]

  5%|▍         | 373/7480 [02:12<43:11,  2.74it/s]

  5%|▍         | 373/7480 [02:12<43:11,  2.74it/s]
  5%|▌         | 374/7480 [02:12<43:10,  2.74it/s]

  5%|▌         | 375/7480 [02:13<42:46,  2.77it/s]

  5%|▌         | 375/7480 [02:13<42:46,  2.77it/s]
  5%|▌         | 376/7480 [02:13<42:46,  2.77it/s]
  5%|▌         | 377/7480 [02:13<42:46,  2.77it/s]
  5%|▌         | 378/7480 [02:13<42:45,  2.77it/s]

  5%|▌         | 379/7480 [02:14<33:05,  3.58it/s]

  5%|▌         | 379/7480 [02:14<33:05,  3.58it/s]
  5%|▌         | 380/7480 [02:14<33:04,  3.58it/s]

  5%|▌         | 381/7480 [02:14<35:56,  3.29it/s]

  5%|▌         | 381/7480 [02:14<35:56,  3.29it/s]
  5%|▌         | 382/7480 [02:14<35:56,  3.29it/s]
  5%|▌         | 383/7480 [02:14<35:56,  3.29it/s]
  5%|▌         | 384/7480 [02:14<35:55,  3.29it/s]
  5%|▌         | 385/7480 [02:14<35:55,  3.29it/s]
  5%|▌         | 386/7480 [02:14<35:55,  3.29it/s]
  5%|▌         | 387/7480 [02:14<35:54,  3.29it/s]
  5%|▌         | 388/7480 [02:14<35:54,  3.29it/s]
  5%|▌         | 389/7480 [02:14<35:54,  3.29it/s]
  5%|▌         | 390/7480 [02:14<35:54,  3.29it/s]
  5%|▌         | 391/7480 [02:14<35:53,  3.29it/s]
  5%|▌         | 392/7480 [02:14<35:53,  3.29it/s]

  5%|▌         | 393/7480 [02:15<16:45,  7.05it/s]

  5%|▌         | 393/7480 [02:15<16:45,  7.05it/s]
  5%|▌         | 394/7480 [02:15<16:44,  7.05it/s]

  5%|▌         | 395/7480 [02:16<20:53,  5.65it/s]

  5%|▌         | 395/7480 [02:16<20:53,  5.65it/s]
  5%|▌         | 396/7480 [02:16<20:53,  5.65it/s]

  5%|▌         | 397/7480 [02:19<45:33,  2.59it/s]

  5%|▌         | 397/7480 [02:19<45:33,  2.59it/s]
  5%|▌         | 398/7480 [02:19<45:32,  2.59it/s]

  5%|▌         | 399/7480 [02:19<44:59,  2.62it/s]
  5%|▌         | 403/7480 [02:20<30:12,  3.90it/s]

  5%|▌         | 399/7480 [02:19<44:59,  2.62it/s]
  5%|▌         | 400/7480 [02:19<44:59,  2.62it/s]
  5%|▌         | 401/7480 [02:20<44:59,  2.62it/s]
  5%|▌         | 402/7480 [02:20<44:58,  2.62it/s]
  5%|▌         | 403/7480 [02:20<30:12,  3.90it/s]

  5%|▌         | 405/7480 [02:20<32:20,  3.65it/s]

  5%|▌         | 404/7480 [02:20<30:12,  3.90it/s]
  5%|▌         | 405/7480 [02:20<32:20,  3.65it/s]

  5%|▌         | 407/7480 [02:21<34:28,  3.42it/s]

  5%|▌         | 406/7480 [02:21<32:20,  3.65it/s]
  5%|▌         | 407/7480 [02:21<34:28,  3.42it/s]
  5%|▌         | 408/7480 [02:21<34:28,  3.42it/s]
  5%|▌         | 409/7480 [02:21<34:27,  3.42it/s]
  5%|▌         | 410/7480 [02:21<34:27,  3.42it/s]

  5%|▌         | 411/7480 [02:22<29:10,  4.04it/s]

  5%|▌         | 411/7480 [02:22<29:10,  4.04it/s]
  6%|▌         | 412/7480 [02:22<29:10,  4.04it/s]

  6%|▌         | 413/7480 [02:22<31:20,  3.76it/s]

  6%|▌         | 413/7480 [02:22<31:20,  3.76it/s]
  6%|▌         | 414/7480 [02:22<31:20,  3.76it/s]

  6%|▌         | 415/7480 [02:23<33:32,  3.51it/s]

  6%|▌         | 415/7480 [02:23<33:32,  3.51it/s]
  6%|▌         | 416/7480 [02:23<33:32,  3.51it/s]

  6%|▌         | 417/7480 [02:24<35:06,  3.35it/s]

  6%|▌         | 417/7480 [02:24<35:06,  3.35it/s]
  6%|▌         | 418/7480 [02:24<35:05,  3.35it/s]
  6%|▌         | 419/7480 [02:24<35:05,  3.35it/s]

  6%|▌         | 420/7480 [02:24<32:22,  3.64it/s]

  6%|▌         | 420/7480 [02:24<32:22,  3.64it/s]
  6%|▌         | 421/7480 [02:24<32:21,  3.64it/s]
  6%|▌         | 422/7480 [02:24<32:21,  3.64it/s]

  6%|▌         | 423/7480 [02:25<30:55,  3.80it/s]

  6%|▌         | 423/7480 [02:25<30:55,  3.80it/s]
  6%|▌         | 424/7480 [02:25<30:55,  3.80it/s]
  6%|▌         | 425/7480 [02:25<30:55,  3.80it/s]

  6%|▌         | 426/7480 [02:26<29:40,  3.96it/s]

  6%|▌         | 426/7480 [02:26<29:40,  3.96it/s]
  6%|▌         | 427/7480 [02:26<29:39,  3.96it/s]
  6%|▌         | 428/7480 [02:26<29:39,  3.96it/s]
  6%|▌         | 429/7480 [02:26<29:39,  3.96it/s]

  6%|▌         | 430/7480 [02:27<26:10,  4.49it/s]

  6%|▌         | 430/7480 [02:27<26:10,  4.49it/s]
  6%|▌         | 431/7480 [02:27<26:10,  4.49it/s]

  6%|▌         | 432/7480 [02:27<29:36,  3.97it/s]

  6%|▌         | 432/7480 [02:27<29:36,  3.97it/s]
  6%|▌         | 433/7480 [02:27<29:36,  3.97it/s]

  6%|▌         | 434/7480 [02:28<32:21,  3.63it/s]

  6%|▌         | 434/7480 [02:28<32:21,  3.63it/s]
  6%|▌         | 435/7480 [02:28<32:21,  3.63it/s]

  6%|▌         | 436/7480 [02:30<1:00:30,  1.94it/s]

  6%|▌         | 436/7480 [02:30<1:00:30,  1.94it/s]
  6%|▌         | 437/7480 [02:30<1:00:30,  1.94it/s]

  6%|▌         | 438/7480 [02:32<1:02:14,  1.89it/s]

  6%|▌         | 438/7480 [02:32<1:02:14,  1.89it/s]
  6%|▌         | 439/7480 [02:32<1:02:13,  1.89it/s]

  6%|▌         | 440/7480 [02:32<56:24,  2.08it/s]

  6%|▌         | 440/7480 [02:32<56:24,  2.08it/s]
  6%|▌         | 441/7480 [02:32<56:23,  2.08it/s]
  6%|▌         | 442/7480 [02:32<56:23,  2.08it/s]
  6%|▌         | 443/7480 [02:32<56:22,  2.08it/s]

  6%|▌         | 444/7480 [02:33<40:09,  2.92it/s]

  6%|▌         | 444/7480 [02:33<40:09,  2.92it/s]
  6%|▌         | 445/7480 [02:33<40:08,  2.92it/s]

  6%|▌         | 446/7480 [02:34<40:35,  2.89it/s]

  6%|▌         | 446/7480 [02:34<40:35,  2.89it/s]
  6%|▌         | 447/7480 [02:34<40:34,  2.89it/s]
  6%|▌         | 448/7480 [02:34<40:34,  2.89it/s]

  6%|▌         | 449/7480 [02:34<36:22,  3.22it/s]

  6%|▌         | 449/7480 [02:34<36:22,  3.22it/s]
  6%|▌         | 450/7480 [02:34<36:21,  3.22it/s]
  6%|▌         | 451/7480 [02:34<36:21,  3.22it/s]

  6%|▌         | 452/7480 [02:35<33:06,  3.54it/s]

  6%|▌         | 452/7480 [02:35<33:06,  3.54it/s]
  6%|▌         | 453/7480 [02:35<33:05,  3.54it/s]

  6%|▌         | 454/7480 [02:36<34:42,  3.37it/s]

  6%|▌         | 454/7480 [02:36<34:42,  3.37it/s]
  6%|▌         | 455/7480 [02:36<34:41,  3.37it/s]

  6%|▌         | 456/7480 [02:36<36:09,  3.24it/s]

  6%|▌         | 456/7480 [02:36<36:09,  3.24it/s]
  6%|▌         | 457/7480 [02:36<36:09,  3.24it/s]

  6%|▌         | 458/7480 [02:37<36:33,  3.20it/s]

  6%|▌         | 458/7480 [02:37<36:33,  3.20it/s]
  6%|▌         | 459/7480 [02:37<36:33,  3.20it/s]

  6%|▌         | 460/7480 [02:38<37:41,  3.10it/s]
  6%|▌         | 465/7480 [02:38<20:25,  5.73it/s]

  6%|▌         | 460/7480 [02:38<37:41,  3.10it/s]
  6%|▌         | 461/7480 [02:38<37:41,  3.10it/s]
  6%|▌         | 462/7480 [02:38<37:40,  3.10it/s]
  6%|▌         | 463/7480 [02:38<37:40,  3.10it/s]
  6%|▌         | 464/7480 [02:38<37:40,  3.10it/s]
  6%|▌         | 465/7480 [02:38<20:25,  5.73it/s]
  6%|▌         | 466/7480 [02:38<20:24,  5.73it/s]
  6%|▌         | 467/7480 [02:38<20:24,  5.73it/s]
  6%|▋         | 468/7480 [02:38<20:24,  5.73it/s]
  6%|▋         | 469/7480 [02:38<20:24,  5.73it/s]

  6%|▋         | 470/7480 [02:39<19:07,  6.11it/s]

  6%|▋         | 470/7480 [02:39<19:07,  6.11it/s]
  6%|▋         | 471/7480 [02:39<19:06,  6.11it/s]

  6%|▋         | 472/7480 [02:39<22:45,  5.13it/s]

  6%|▋         | 472/7480 [02:39<22:45,  5.13it/s]
  6%|▋         | 473/7480 [02:39<22:45,  5.13it/s]

  6%|▋         | 474/7480 [02:40<26:22,  4.43it/s]

  6%|▋         | 474/7480 [02:40<26:22,  4.43it/s]
  6%|▋         | 475/7480 [02:40<26:22,  4.43it/s]

  6%|▋         | 476/7480 [02:41<29:43,  3.93it/s]

  6%|▋         | 476/7480 [02:41<29:43,  3.93it/s]
  6%|▋         | 477/7480 [02:41<29:43,  3.93it/s]

  6%|▋         | 478/7480 [02:41<32:48,  3.56it/s]

  6%|▋         | 478/7480 [02:41<32:48,  3.56it/s]
  6%|▋         | 479/7480 [02:41<32:48,  3.56it/s]

  6%|▋         | 480/7480 [02:44<1:08:03,  1.71it/s]

  6%|▋         | 480/7480 [02:44<1:08:03,  1.71it/s]
  6%|▋         | 481/7480 [02:44<1:08:02,  1.71it/s]

  6%|▋         | 482/7480 [02:45<1:01:54,  1.88it/s]

  6%|▋         | 482/7480 [02:45<1:01:54,  1.88it/s]
  6%|▋         | 483/7480 [02:45<1:01:54,  1.88it/s]

  6%|▋         | 484/7480 [02:46<55:34,  2.10it/s]

  6%|▋         | 484/7480 [02:46<55:34,  2.10it/s]
  6%|▋         | 485/7480 [02:46<55:33,  2.10it/s]

  6%|▋         | 486/7480 [02:46<51:35,  2.26it/s]

  6%|▋         | 486/7480 [02:46<51:35,  2.26it/s]
  7%|▋         | 487/7480 [02:46<51:35,  2.26it/s]

  7%|▋         | 488/7480 [02:47<48:47,  2.39it/s]

  7%|▋         | 488/7480 [02:47<48:47,  2.39it/s]
  7%|▋         | 489/7480 [02:47<48:47,  2.39it/s]
  7%|▋         | 490/7480 [02:47<48:47,  2.39it/s]
  7%|▋         | 491/7480 [02:47<48:46,  2.39it/s]

  7%|▋         | 492/7480 [02:48<35:27,  3.28it/s]

  7%|▋         | 492/7480 [02:48<35:27,  3.28it/s]
  7%|▋         | 493/7480 [02:48<35:27,  3.28it/s]

  7%|▋         | 494/7480 [02:48<36:34,  3.18it/s]

  7%|▋         | 494/7480 [02:48<36:34,  3.18it/s]
  7%|▋         | 495/7480 [02:48<36:34,  3.18it/s]
  7%|▋         | 496/7480 [02:48<36:33,  3.18it/s]

  7%|▋         | 497/7480 [02:49<33:22,  3.49it/s]

  7%|▋         | 497/7480 [02:49<33:22,  3.49it/s]
  7%|▋         | 498/7480 [02:49<33:21,  3.49it/s]

  7%|▋         | 499/7480 [02:50<34:35,  3.36it/s]

  7%|▋         | 499/7480 [02:50<34:35,  3.36it/s]
  7%|▋         | 500/7480 [02:50<34:35,  3.36it/s]
  7%|▋         | 501/7480 [02:50<34:34,  3.36it/s]

  7%|▋         | 502/7480 [02:51<32:12,  3.61it/s]

  7%|▋         | 502/7480 [02:51<32:12,  3.61it/s]
  7%|▋         | 503/7480 [02:51<32:12,  3.61it/s]

  7%|▋         | 504/7480 [02:51<34:41,  3.35it/s]

  7%|▋         | 504/7480 [02:51<34:41,  3.35it/s]
  7%|▋         | 505/7480 [02:51<34:41,  3.35it/s]

  7%|▋         | 506/7480 [02:52<35:39,  3.26it/s]

  7%|▋         | 506/7480 [02:52<35:39,  3.26it/s]
  7%|▋         | 507/7480 [02:52<35:38,  3.26it/s]
  7%|▋         | 508/7480 [02:52<35:38,  3.26it/s]
  7%|▋         | 509/7480 [02:52<35:38,  3.26it/s]
  7%|▋         | 510/7480 [02:52<35:37,  3.26it/s]
  7%|▋         | 511/7480 [02:52<35:37,  3.26it/s]
  7%|▋         | 512/7480 [02:52<35:37,  3.26it/s]
  7%|▋         | 513/7480 [02:52<35:37,  3.26it/s]
  7%|▋         | 514/7480 [02:52<35:36,  3.26it/s]
  7%|▋         | 515/7480 [02:52<35:36,  3.26it/s]
  7%|▋         | 516/7480 [02:52<35:36,  3.26it/s]
  7%|▋         | 517/7480 [02:52<35:35,  3.26it/s]

  7%|▋         | 518/7480 [02:53<15:44,  7.37it/s]

  7%|▋         | 518/7480 [02:53<15:44,  7.37it/s]
  7%|▋         | 519/7480 [02:53<15:44,  7.37it/s]

  7%|▋         | 520/7480 [02:53<19:05,  6.08it/s]

  7%|▋         | 520/7480 [02:53<19:05,  6.08it/s]
  7%|▋         | 521/7480 [02:53<19:05,  6.08it/s]
  7%|▋         | 522/7480 [02:53<19:05,  6.08it/s]
  7%|▋         | 523/7480 [02:53<19:05,  6.08it/s]
  7%|▋         | 524/7480 [02:53<19:04,  6.08it/s]
  7%|▋         | 525/7480 [02:53<19:04,  6.08it/s]

  7%|▋         | 526/7480 [02:54<17:23,  6.66it/s]

  7%|▋         | 526/7480 [02:54<17:23,  6.66it/s]
  7%|▋         | 527/7480 [02:54<17:23,  6.66it/s]

  7%|▋         | 528/7480 [02:57<40:10,  2.88it/s]

  7%|▋         | 528/7480 [02:57<40:10,  2.88it/s]
  7%|▋         | 529/7480 [02:57<40:09,  2.88it/s]

  7%|▋         | 530/7480 [02:58<40:07,  2.89it/s]

  7%|▋         | 530/7480 [02:58<40:07,  2.89it/s]
  7%|▋         | 531/7480 [02:58<40:06,  2.89it/s]

  7%|▋         | 532/7480 [02:58<39:42,  2.92it/s]

  7%|▋         | 532/7480 [02:58<39:42,  2.92it/s]
  7%|▋         | 533/7480 [02:58<39:42,  2.92it/s]

  7%|▋         | 534/7480 [02:59<39:48,  2.91it/s]

  7%|▋         | 534/7480 [02:59<39:48,  2.91it/s]
  7%|▋         | 535/7480 [02:59<39:47,  2.91it/s]

  7%|▋         | 536/7480 [03:00<39:57,  2.90it/s]

  7%|▋         | 536/7480 [03:00<39:57,  2.90it/s]
  7%|▋         | 537/7480 [03:00<39:57,  2.90it/s]

  7%|▋         | 538/7480 [03:00<39:47,  2.91it/s]

  7%|▋         | 538/7480 [03:00<39:47,  2.91it/s]
  7%|▋         | 539/7480 [03:00<39:46,  2.91it/s]

  7%|▋         | 540/7480 [03:01<40:23,  2.86it/s]

  7%|▋         | 540/7480 [03:01<40:23,  2.86it/s]
  7%|▋         | 541/7480 [03:01<40:23,  2.86it/s]

  7%|▋         | 542/7480 [03:02<40:40,  2.84it/s]

  7%|▋         | 542/7480 [03:02<40:40,  2.84it/s]
  7%|▋         | 543/7480 [03:02<40:40,  2.84it/s]

  7%|▋         | 544/7480 [03:02<40:14,  2.87it/s]

  7%|▋         | 544/7480 [03:02<40:14,  2.87it/s]
  7%|▋         | 545/7480 [03:02<40:13,  2.87it/s]

  7%|▋         | 546/7480 [03:03<40:28,  2.86it/s]

  7%|▋         | 546/7480 [03:03<40:28,  2.86it/s]
  7%|▋         | 547/7480 [03:03<40:27,  2.86it/s]

  7%|▋         | 548/7480 [03:04<41:35,  2.78it/s]

  7%|▋         | 548/7480 [03:04<41:35,  2.78it/s]
  7%|▋         | 549/7480 [03:04<41:35,  2.78it/s]

  7%|▋         | 550/7480 [03:05<41:14,  2.80it/s]

  7%|▋         | 550/7480 [03:05<41:14,  2.80it/s]
  7%|▋         | 551/7480 [03:05<41:14,  2.80it/s]

  7%|▋         | 552/7480 [03:05<41:11,  2.80it/s]

  7%|▋         | 552/7480 [03:05<41:11,  2.80it/s]
  7%|▋         | 553/7480 [03:05<41:11,  2.80it/s]

  7%|▋         | 554/7480 [03:06<40:41,  2.84it/s]

  7%|▋         | 554/7480 [03:06<40:41,  2.84it/s]
  7%|▋         | 555/7480 [03:06<40:40,  2.84it/s]

  7%|▋         | 556/7480 [03:07<43:37,  2.64it/s]
  8%|▊         | 561/7480 [03:07<22:35,  5.10it/s]

  7%|▋         | 556/7480 [03:07<43:37,  2.64it/s]
  7%|▋         | 557/7480 [03:07<43:37,  2.64it/s]
  7%|▋         | 558/7480 [03:07<43:37,  2.64it/s]
  7%|▋         | 559/7480 [03:07<43:36,  2.64it/s]
  7%|▋         | 560/7480 [03:07<43:36,  2.64it/s]
  8%|▊         | 561/7480 [03:07<22:35,  5.10it/s]

  8%|▊         | 563/7480 [03:10<53:59,  2.14it/s]

  8%|▊         | 562/7480 [03:10<22:35,  5.10it/s]
  8%|▊         | 563/7480 [03:10<53:59,  2.14it/s]

  8%|▊         | 565/7480 [03:11<50:42,  2.27it/s]

  8%|▊         | 564/7480 [03:11<53:58,  2.14it/s]
  8%|▊         | 565/7480 [03:11<50:42,  2.27it/s]

  8%|▊         | 566/7480 [03:11<55:29,  2.08it/s]

  8%|▊         | 566/7480 [03:11<55:29,  2.08it/s]
  8%|▊         | 567/7480 [03:11<55:28,  2.08it/s]
  8%|▊         | 568/7480 [03:11<55:28,  2.08it/s]
  8%|▊         | 569/7480 [03:11<55:27,  2.08it/s]

  8%|▊         | 570/7480 [03:12<38:49,  2.97it/s]

  8%|▊         | 570/7480 [03:12<38:49,  2.97it/s]
  8%|▊         | 571/7480 [03:12<38:49,  2.97it/s]

  8%|▊         | 572/7480 [03:13<39:26,  2.92it/s]

  8%|▊         | 572/7480 [03:13<39:26,  2.92it/s]
  8%|▊         | 573/7480 [03:13<39:25,  2.92it/s]

  8%|▊         | 574/7480 [03:13<39:44,  2.90it/s]

  8%|▊         | 574/7480 [03:13<39:44,  2.90it/s]
  8%|▊         | 575/7480 [03:13<39:44,  2.90it/s]
  8%|▊         | 576/7480 [03:13<39:43,  2.90it/s]

  8%|▊         | 577/7480 [03:14<34:56,  3.29it/s]

  8%|▊         | 577/7480 [03:14<34:56,  3.29it/s]
  8%|▊         | 578/7480 [03:14<34:56,  3.29it/s]
  8%|▊         | 579/7480 [03:14<34:55,  3.29it/s]
  8%|▊         | 580/7480 [03:14<34:55,  3.29it/s]
  8%|▊         | 581/7480 [03:14<34:55,  3.29it/s]

  8%|▊         | 582/7480 [03:15<26:40,  4.31it/s]

  8%|▊         | 582/7480 [03:15<26:40,  4.31it/s]
  8%|▊         | 583/7480 [03:15<26:40,  4.31it/s]

  8%|▊         | 584/7480 [03:16<29:50,  3.85it/s]

  8%|▊         | 584/7480 [03:16<29:50,  3.85it/s]
  8%|▊         | 585/7480 [03:16<29:49,  3.85it/s]

  8%|▊         | 586/7480 [03:16<32:20,  3.55it/s]

  8%|▊         | 586/7480 [03:16<32:20,  3.55it/s]
  8%|▊         | 587/7480 [03:16<32:20,  3.55it/s]

  8%|▊         | 588/7480 [03:17<34:26,  3.34it/s]

  8%|▊         | 588/7480 [03:17<34:26,  3.34it/s]
  8%|▊         | 589/7480 [03:17<34:25,  3.34it/s]
  8%|▊         | 590/7480 [03:17<34:25,  3.34it/s]

  8%|▊         | 591/7480 [03:18<32:13,  3.56it/s]

  8%|▊         | 591/7480 [03:18<32:13,  3.56it/s]
  8%|▊         | 592/7480 [03:18<32:13,  3.56it/s]

  8%|▊         | 593/7480 [03:18<34:00,  3.38it/s]

  8%|▊         | 593/7480 [03:18<34:00,  3.38it/s]
  8%|▊         | 594/7480 [03:18<34:00,  3.38it/s]

  8%|▊         | 595/7480 [03:19<35:58,  3.19it/s]

  8%|▊         | 595/7480 [03:19<35:58,  3.19it/s]
  8%|▊         | 596/7480 [03:19<35:58,  3.19it/s]
  8%|▊         | 597/7480 [03:19<35:58,  3.19it/s]
  8%|▊         | 598/7480 [03:19<35:57,  3.19it/s]

  8%|▊         | 599/7480 [03:22<54:28,  2.11it/s]

  8%|▊         | 599/7480 [03:22<54:28,  2.11it/s]
  8%|▊         | 600/7480 [03:22<54:28,  2.11it/s]

  8%|▊         | 601/7480 [03:23<54:26,  2.11it/s]

  8%|▊         | 601/7480 [03:23<54:26,  2.11it/s]
  8%|▊         | 602/7480 [03:23<54:25,  2.11it/s]

  8%|▊         | 603/7480 [03:23<50:38,  2.26it/s]

  8%|▊         | 603/7480 [03:23<50:38,  2.26it/s]
  8%|▊         | 604/7480 [03:23<50:37,  2.26it/s]

  8%|▊         | 605/7480 [03:24<48:30,  2.36it/s]

  8%|▊         | 605/7480 [03:24<48:30,  2.36it/s]
  8%|▊         | 606/7480 [03:24<48:30,  2.36it/s]

  8%|▊         | 607/7480 [03:25<46:53,  2.44it/s]

  8%|▊         | 607/7480 [03:25<46:53,  2.44it/s]
  8%|▊         | 608/7480 [03:25<46:52,  2.44it/s]

  8%|▊         | 609/7480 [03:26<45:05,  2.54it/s]

  8%|▊         | 609/7480 [03:26<45:05,  2.54it/s]
  8%|▊         | 610/7480 [03:26<45:05,  2.54it/s]

  8%|▊         | 611/7480 [03:26<44:34,  2.57it/s]

  8%|▊         | 611/7480 [03:26<44:34,  2.57it/s]
  8%|▊         | 612/7480 [03:26<44:34,  2.57it/s]

  8%|▊         | 613/7480 [03:27<44:23,  2.58it/s]
  8%|▊         | 617/7480 [03:27<25:44,  4.44it/s]

  8%|▊         | 613/7480 [03:27<44:23,  2.58it/s]
  8%|▊         | 614/7480 [03:27<44:23,  2.58it/s]
  8%|▊         | 615/7480 [03:27<44:22,  2.58it/s]
  8%|▊         | 616/7480 [03:27<44:22,  2.58it/s]
  8%|▊         | 617/7480 [03:27<25:44,  4.44it/s]
  8%|▊         | 618/7480 [03:27<25:44,  4.44it/s]
  8%|▊         | 619/7480 [03:27<25:43,  4.44it/s]

  8%|▊         | 620/7480 [03:28<26:39,  4.29it/s]

  8%|▊         | 620/7480 [03:28<26:39,  4.29it/s]
  8%|▊         | 621/7480 [03:28<26:39,  4.29it/s]

  8%|▊         | 622/7480 [03:29<29:45,  3.84it/s]

  8%|▊         | 622/7480 [03:29<29:45,  3.84it/s]
  8%|▊         | 623/7480 [03:29<29:45,  3.84it/s]
  8%|▊         | 624/7480 [03:29<29:45,  3.84it/s]

  8%|▊         | 625/7480 [03:30<29:30,  3.87it/s]

  8%|▊         | 625/7480 [03:30<29:30,  3.87it/s]
  8%|▊         | 626/7480 [03:30<29:30,  3.87it/s]
  8%|▊         | 627/7480 [03:30<29:30,  3.87it/s]
  8%|▊         | 628/7480 [03:30<29:29,  3.87it/s]
  8%|▊         | 629/7480 [03:30<29:29,  3.87it/s]
  8%|▊         | 630/7480 [03:30<29:29,  3.87it/s]
  8%|▊         | 631/7480 [03:30<29:29,  3.87it/s]

  8%|▊         | 632/7480 [03:30<20:04,  5.68it/s]
  9%|▊         | 637/7480 [03:30<13:53,  8.21it/s]

  8%|▊         | 632/7480 [03:30<20:04,  5.68it/s]
  8%|▊         | 633/7480 [03:30<20:04,  5.68it/s]
  8%|▊         | 634/7480 [03:30<20:04,  5.68it/s]
  8%|▊         | 635/7480 [03:30<20:04,  5.68it/s]
  9%|▊         | 636/7480 [03:30<20:04,  5.68it/s]
  9%|▊         | 637/7480 [03:30<13:53,  8.21it/s]
  9%|▊         | 638/7480 [03:30<13:53,  8.21it/s]

  9%|▊         | 639/7480 [03:31<17:57,  6.35it/s]

  9%|▊         | 639/7480 [03:31<17:57,  6.35it/s]
  9%|▊         | 640/7480 [03:31<17:56,  6.35it/s]
  9%|▊         | 641/7480 [03:31<17:56,  6.35it/s]
  9%|▊         | 642/7480 [03:31<17:56,  6.35it/s]
  9%|▊         | 643/7480 [03:31<17:56,  6.35it/s]

  9%|▊         | 644/7480 [03:32<17:34,  6.48it/s]

  9%|▊         | 644/7480 [03:32<17:34,  6.48it/s]
  9%|▊         | 645/7480 [03:32<17:34,  6.48it/s]
  9%|▊         | 646/7480 [03:32<17:34,  6.48it/s]

  9%|▊         | 647/7480 [03:33<27:55,  4.08it/s]

  9%|▊         | 647/7480 [03:33<27:55,  4.08it/s]
  9%|▊         | 648/7480 [03:33<27:55,  4.08it/s]
  9%|▊         | 649/7480 [03:33<27:55,  4.08it/s]

  9%|▊         | 650/7480 [03:36<42:07,  2.70it/s]

  9%|▊         | 650/7480 [03:36<42:07,  2.70it/s]
  9%|▊         | 651/7480 [03:36<42:07,  2.70it/s]

  9%|▊         | 652/7480 [03:36<41:33,  2.74it/s]

  9%|▊         | 652/7480 [03:36<41:33,  2.74it/s]
  9%|▊         | 653/7480 [03:36<41:32,  2.74it/s]

  9%|▊         | 654/7480 [03:37<41:26,  2.74it/s]

  9%|▊         | 654/7480 [03:37<41:26,  2.74it/s]
  9%|▉         | 655/7480 [03:37<41:26,  2.74it/s]
  9%|▉         | 656/7480 [03:37<41:26,  2.74it/s]
  9%|▉         | 657/7480 [03:37<41:25,  2.74it/s]
  9%|▉         | 658/7480 [03:37<41:25,  2.74it/s]
  9%|▉         | 659/7480 [03:37<41:25,  2.74it/s]
  9%|▉         | 660/7480 [03:37<41:24,  2.74it/s]
  9%|▉         | 661/7480 [03:37<41:24,  2.74it/s]
  9%|▉         | 662/7480 [03:37<41:23,  2.74it/s]

  9%|▉         | 663/7480 [03:38<22:41,  5.01it/s]

  9%|▉         | 663/7480 [03:38<22:41,  5.01it/s]
  9%|▉         | 664/7480 [03:38<22:41,  5.01it/s]

  9%|▉         | 665/7480 [03:38<25:21,  4.48it/s]

  9%|▉         | 665/7480 [03:38<25:21,  4.48it/s]
  9%|▉         | 666/7480 [03:38<25:21,  4.48it/s]

  9%|▉         | 667/7480 [03:39<28:23,  4.00it/s]

  9%|▉         | 667/7480 [03:39<28:23,  4.00it/s]
  9%|▉         | 668/7480 [03:39<28:23,  4.00it/s]

  9%|▉         | 669/7480 [03:40<31:08,  3.65it/s]

  9%|▉         | 669/7480 [03:40<31:08,  3.65it/s]
  9%|▉         | 670/7480 [03:40<31:07,  3.65it/s]

  9%|▉         | 671/7480 [03:41<33:44,  3.36it/s]

  9%|▉         | 671/7480 [03:41<33:44,  3.36it/s]
  9%|▉         | 672/7480 [03:41<33:43,  3.36it/s]

  9%|▉         | 673/7480 [03:41<35:21,  3.21it/s]

  9%|▉         | 673/7480 [03:41<35:21,  3.21it/s]
  9%|▉         | 674/7480 [03:41<35:20,  3.21it/s]

  9%|▉         | 675/7480 [03:42<37:23,  3.03it/s]

  9%|▉         | 675/7480 [03:42<37:23,  3.03it/s]
  9%|▉         | 676/7480 [03:42<37:23,  3.03it/s]

  9%|▉         | 677/7480 [03:43<38:35,  2.94it/s]

  9%|▉         | 677/7480 [03:43<38:35,  2.94it/s]
  9%|▉         | 678/7480 [03:43<38:35,  2.94it/s]

  9%|▉         | 679/7480 [03:44<39:10,  2.89it/s]

  9%|▉         | 679/7480 [03:44<39:10,  2.89it/s]
  9%|▉         | 680/7480 [03:44<39:10,  2.89it/s]

  9%|▉         | 681/7480 [03:44<39:42,  2.85it/s]

  9%|▉         | 681/7480 [03:44<39:42,  2.85it/s]
  9%|▉         | 682/7480 [03:44<39:42,  2.85it/s]
  9%|▉         | 683/7480 [03:44<39:41,  2.85it/s]

  9%|▉         | 684/7480 [03:45<35:29,  3.19it/s]

  9%|▉         | 684/7480 [03:45<35:29,  3.19it/s]
  9%|▉         | 685/7480 [03:45<35:29,  3.19it/s]

  9%|▉         | 686/7480 [03:48<1:11:39,  1.58it/s]

  9%|▉         | 686/7480 [03:48<1:11:39,  1.58it/s]
  9%|▉         | 687/7480 [03:48<1:11:38,  1.58it/s]

  9%|▉         | 688/7480 [03:49<1:02:42,  1.81it/s]
  9%|▉         | 693/7480 [03:49<32:54,  3.44it/s]

  9%|▉         | 688/7480 [03:49<1:02:42,  1.81it/s]
  9%|▉         | 689/7480 [03:49<1:02:42,  1.81it/s]
  9%|▉         | 690/7480 [03:49<1:02:41,  1.81it/s]
  9%|▉         | 691/7480 [03:49<1:02:41,  1.81it/s]
  9%|▉         | 692/7480 [03:49<1:02:40,  1.81it/s]
  9%|▉         | 693/7480 [03:49<32:54,  3.44it/s]

  9%|▉         | 695/7480 [03:50<34:51,  3.24it/s]

  9%|▉         | 694/7480 [03:50<32:54,  3.44it/s]
  9%|▉         | 695/7480 [03:50<34:51,  3.24it/s]

  9%|▉         | 697/7480 [03:50<36:22,  3.11it/s]

  9%|▉         | 696/7480 [03:50<34:50,  3.24it/s]
  9%|▉         | 697/7480 [03:50<36:22,  3.11it/s]

  9%|▉         | 698/7480 [03:51<42:41,  2.65it/s]

  9%|▉         | 698/7480 [03:51<42:41,  2.65it/s]
  9%|▉         | 699/7480 [03:51<42:41,  2.65it/s]

  9%|▉         | 700/7480 [03:52<42:26,  2.66it/s]

  9%|▉         | 700/7480 [03:52<42:26,  2.66it/s]
  9%|▉         | 701/7480 [03:52<42:25,  2.66it/s]

  9%|▉         | 702/7480 [03:53<41:40,  2.71it/s]

  9%|▉         | 702/7480 [03:53<41:40,  2.71it/s]
  9%|▉         | 703/7480 [03:53<41:39,  2.71it/s]

  9%|▉         | 704/7480 [03:53<40:51,  2.76it/s]

  9%|▉         | 704/7480 [03:53<40:51,  2.76it/s]
  9%|▉         | 705/7480 [03:53<40:51,  2.76it/s]

  9%|▉         | 706/7480 [03:54<40:40,  2.78it/s]

  9%|▉         | 706/7480 [03:54<40:40,  2.78it/s]
  9%|▉         | 707/7480 [03:54<40:39,  2.78it/s]

  9%|▉         | 708/7480 [03:55<40:47,  2.77it/s]

  9%|▉         | 708/7480 [03:55<40:47,  2.77it/s]
  9%|▉         | 709/7480 [03:55<40:47,  2.77it/s]

  9%|▉         | 710/7480 [03:55<40:11,  2.81it/s]

  9%|▉         | 710/7480 [03:55<40:11,  2.81it/s]
 10%|▉         | 711/7480 [03:55<40:10,  2.81it/s]

 10%|▉         | 712/7480 [03:56<40:00,  2.82it/s]

 10%|▉         | 712/7480 [03:56<40:00,  2.82it/s]
 10%|▉         | 713/7480 [03:56<40:00,  2.82it/s]
 10%|▉         | 714/7480 [03:56<40:00,  2.82it/s]

 10%|▉         | 715/7480 [03:57<35:03,  3.22it/s]

 10%|▉         | 715/7480 [03:57<35:03,  3.22it/s]
 10%|▉         | 716/7480 [03:57<35:03,  3.22it/s]

 10%|▉         | 717/7480 [03:57<36:26,  3.09it/s]

 10%|▉         | 717/7480 [03:57<36:26,  3.09it/s]
 10%|▉         | 718/7480 [03:57<36:25,  3.09it/s]

 10%|▉         | 719/7480 [04:01<1:15:21,  1.50it/s]

 10%|▉         | 719/7480 [04:01<1:15:21,  1.50it/s]
 10%|▉         | 720/7480 [04:01<1:15:20,  1.50it/s]

 10%|▉         | 721/7480 [04:01<1:05:44,  1.71it/s]

 10%|▉         | 721/7480 [04:01<1:05:44,  1.71it/s]
 10%|▉         | 722/7480 [04:01<1:05:43,  1.71it/s]

 10%|▉         | 723/7480 [04:02<58:31,  1.92it/s]

 10%|▉         | 723/7480 [04:02<58:31,  1.92it/s]
 10%|▉         | 724/7480 [04:02<58:30,  1.92it/s]

 10%|▉         | 725/7480 [04:03<52:57,  2.13it/s]
 10%|▉         | 731/7480 [04:03<24:31,  4.59it/s]

 10%|▉         | 725/7480 [04:03<52:57,  2.13it/s]
 10%|▉         | 726/7480 [04:03<52:57,  2.13it/s]
 10%|▉         | 727/7480 [04:03<52:56,  2.13it/s]
 10%|▉         | 728/7480 [04:03<52:56,  2.13it/s]
 10%|▉         | 729/7480 [04:03<52:55,  2.13it/s]
 10%|▉         | 730/7480 [04:03<52:55,  2.13it/s]
 10%|▉         | 731/7480 [04:03<24:31,  4.59it/s]
 10%|▉         | 732/7480 [04:03<24:31,  4.59it/s]
 10%|▉         | 733/7480 [04:03<24:30,  4.59it/s]
 10%|▉         | 734/7480 [04:03<24:30,  4.59it/s]
 10%|▉         | 735/7480 [04:03<24:30,  4.59it/s]
 10%|▉         | 736/7480 [04:03<24:30,  4.59it/s]
 10%|▉         | 737/7480 [04:03<24:30,  4.59it/s]

 10%|▉         | 738/7480 [04:04<18:42,  6.01it/s]

 10%|▉         | 738/7480 [04:04<18:42,  6.01it/s]
 10%|▉         | 739/7480 [04:04<18:42,  6.01it/s]

 10%|▉         | 740/7480 [04:04<23:04,  4.87it/s]

 10%|▉         | 740/7480 [04:04<23:04,  4.87it/s]
 10%|▉         | 741/7480 [04:04<23:04,  4.87it/s]

 10%|▉         | 742/7480 [04:05<26:44,  4.20it/s]

 10%|▉         | 742/7480 [04:05<26:44,  4.20it/s]
 10%|▉         | 743/7480 [04:05<26:43,  4.20it/s]

 10%|▉         | 744/7480 [04:06<29:40,  3.78it/s]

 10%|▉         | 744/7480 [04:06<29:40,  3.78it/s]
 10%|▉         | 745/7480 [04:06<29:39,  3.78it/s]
 10%|▉         | 746/7480 [04:06<29:39,  3.78it/s]

 10%|▉         | 747/7480 [04:07<29:15,  3.84it/s]

 10%|▉         | 747/7480 [04:07<29:15,  3.84it/s]
 10%|█         | 748/7480 [04:07<29:15,  3.84it/s]
 10%|█         | 749/7480 [04:07<29:14,  3.84it/s]

 10%|█         | 750/7480 [04:07<29:15,  3.83it/s]

 10%|█         | 750/7480 [04:07<29:15,  3.83it/s]
 10%|█         | 751/7480 [04:07<29:14,  3.83it/s]
 10%|█         | 752/7480 [04:08<29:14,  3.83it/s]

 10%|█         | 753/7480 [04:08<29:04,  3.86it/s]

 10%|█         | 753/7480 [04:08<29:04,  3.86it/s]
 10%|█         | 754/7480 [04:08<29:03,  3.86it/s]

 10%|█         | 755/7480 [04:09<31:58,  3.51it/s]

 10%|█         | 755/7480 [04:09<31:58,  3.51it/s]
 10%|█         | 756/7480 [04:09<31:57,  3.51it/s]
 10%|█         | 757/7480 [04:09<31:57,  3.51it/s]

 10%|█         | 758/7480 [04:10<30:39,  3.66it/s]

 10%|█         | 758/7480 [04:10<30:39,  3.66it/s]
 10%|█         | 759/7480 [04:10<30:38,  3.66it/s]

 10%|█         | 760/7480 [04:11<33:48,  3.31it/s]

 10%|█         | 760/7480 [04:11<33:48,  3.31it/s]
 10%|█         | 761/7480 [04:11<33:48,  3.31it/s]
 10%|█         | 762/7480 [04:11<33:48,  3.31it/s]

 10%|█         | 763/7480 [04:13<59:33,  1.88it/s]

 10%|█         | 763/7480 [04:13<59:33,  1.88it/s]
 10%|█         | 764/7480 [04:13<59:32,  1.88it/s]

 10%|█         | 765/7480 [04:14<54:59,  2.04it/s]

 10%|█         | 765/7480 [04:14<54:59,  2.04it/s]
 10%|█         | 766/7480 [04:14<54:58,  2.04it/s]

 10%|█         | 767/7480 [04:15<51:48,  2.16it/s]

 10%|█         | 767/7480 [04:15<51:48,  2.16it/s]
 10%|█         | 768/7480 [04:15<51:48,  2.16it/s]

 10%|█         | 769/7480 [04:16<49:10,  2.27it/s]

 10%|█         | 769/7480 [04:16<49:10,  2.27it/s]
 10%|█         | 770/7480 [04:16<49:09,  2.27it/s]
 10%|█         | 771/7480 [04:16<49:09,  2.27it/s]

 10%|█         | 772/7480 [04:16<41:15,  2.71it/s]

 10%|█         | 772/7480 [04:16<41:15,  2.71it/s]
 10%|█         | 773/7480 [04:16<41:15,  2.71it/s]

 10%|█         | 774/7480 [04:17<41:08,  2.72it/s]

 10%|█         | 774/7480 [04:17<41:08,  2.72it/s]
 10%|█         | 775/7480 [04:17<41:08,  2.72it/s]

 10%|█         | 776/7480 [04:18<41:34,  2.69it/s]

 10%|█         | 776/7480 [04:18<41:34,  2.69it/s]
 10%|█         | 777/7480 [04:18<41:34,  2.69it/s]
 10%|█         | 778/7480 [04:18<41:33,  2.69it/s]

 10%|█         | 779/7480 [04:19<36:51,  3.03it/s]

 10%|█         | 779/7480 [04:19<36:51,  3.03it/s]
 10%|█         | 780/7480 [04:19<36:50,  3.03it/s]

 10%|█         | 781/7480 [04:19<38:27,  2.90it/s]

 10%|█         | 781/7480 [04:19<38:27,  2.90it/s]
 10%|█         | 782/7480 [04:20<38:27,  2.90it/s]
 10%|█         | 783/7480 [04:20<38:26,  2.90it/s]
 10%|█         | 784/7480 [04:20<38:26,  2.90it/s]

 10%|█         | 785/7480 [04:20<31:23,  3.55it/s]

 10%|█         | 785/7480 [04:20<31:23,  3.55it/s]
 11%|█         | 786/7480 [04:20<31:23,  3.55it/s]

 11%|█         | 787/7480 [04:21<34:27,  3.24it/s]

 11%|█         | 787/7480 [04:21<34:27,  3.24it/s]
 11%|█         | 788/7480 [04:21<34:27,  3.24it/s]

 11%|█         | 789/7480 [04:22<37:05,  3.01it/s]

 11%|█         | 789/7480 [04:22<37:05,  3.01it/s]
 11%|█         | 790/7480 [04:22<37:05,  3.01it/s]

 11%|█         | 791/7480 [04:23<38:51,  2.87it/s]

 11%|█         | 791/7480 [04:23<38:51,  2.87it/s]
 11%|█         | 792/7480 [04:23<38:50,  2.87it/s]

 11%|█         | 793/7480 [04:26<1:16:15,  1.46it/s]

 11%|█         | 793/7480 [04:26<1:16:15,  1.46it/s]
 11%|█         | 794/7480 [04:26<1:16:15,  1.46it/s]

 11%|█         | 795/7480 [04:27<1:07:01,  1.66it/s]

 11%|█         | 795/7480 [04:27<1:07:01,  1.66it/s]
 11%|█         | 796/7480 [04:27<1:07:00,  1.66it/s]

 11%|█         | 797/7480 [04:27<1:00:03,  1.85it/s]

 11%|█         | 797/7480 [04:27<1:00:03,  1.85it/s]
 11%|█         | 798/7480 [04:27<1:00:02,  1.85it/s]

 11%|█         | 799/7480 [04:28<54:45,  2.03it/s]

 11%|█         | 799/7480 [04:28<54:45,  2.03it/s]
 11%|█         | 800/7480 [04:28<54:44,  2.03it/s]

 11%|█         | 801/7480 [04:29<51:16,  2.17it/s]

 11%|█         | 801/7480 [04:29<51:16,  2.17it/s]
 11%|█         | 802/7480 [04:29<51:16,  2.17it/s]

 11%|█         | 803/7480 [04:30<48:51,  2.28it/s]

 11%|█         | 803/7480 [04:30<48:51,  2.28it/s]
 11%|█         | 804/7480 [04:30<48:51,  2.28it/s]
 11%|█         | 805/7480 [04:30<48:50,  2.28it/s]
 11%|█         | 806/7480 [04:30<48:50,  2.28it/s]
 11%|█         | 807/7480 [04:30<48:49,  2.28it/s]

 11%|█         | 808/7480 [04:30<32:41,  3.40it/s]

 11%|█         | 808/7480 [04:30<32:41,  3.40it/s]
 11%|█         | 809/7480 [04:30<32:41,  3.40it/s]

 11%|█         | 810/7480 [04:31<35:10,  3.16it/s]

 11%|█         | 810/7480 [04:31<35:10,  3.16it/s]
 11%|█         | 811/7480 [04:31<35:10,  3.16it/s]
 11%|█         | 812/7480 [04:31<35:10,  3.16it/s]

 11%|█         | 813/7480 [04:32<33:33,  3.31it/s]

 11%|█         | 813/7480 [04:32<33:33,  3.31it/s]
 11%|█         | 814/7480 [04:32<33:32,  3.31it/s]

 11%|█         | 815/7480 [04:33<36:13,  3.07it/s]

 11%|█         | 815/7480 [04:33<36:13,  3.07it/s]
 11%|█         | 816/7480 [04:33<36:12,  3.07it/s]

 11%|█         | 817/7480 [04:34<38:21,  2.89it/s]

 11%|█         | 817/7480 [04:34<38:21,  2.89it/s]
 11%|█         | 818/7480 [04:34<38:21,  2.89it/s]

 11%|█         | 819/7480 [04:35<40:39,  2.73it/s]

 11%|█         | 819/7480 [04:35<40:39,  2.73it/s]
 11%|█         | 820/7480 [04:35<40:38,  2.73it/s]
 11%|█         | 821/7480 [04:35<40:38,  2.73it/s]

 11%|█         | 822/7480 [04:35<36:42,  3.02it/s]

 11%|█         | 822/7480 [04:35<36:42,  3.02it/s]
 11%|█         | 823/7480 [04:35<36:41,  3.02it/s]
 11%|█         | 824/7480 [04:35<36:41,  3.02it/s]

 11%|█         | 825/7480 [04:38<54:51,  2.02it/s]

 11%|█         | 825/7480 [04:38<54:51,  2.02it/s]
 11%|█         | 826/7480 [04:38<54:50,  2.02it/s]

 11%|█         | 827/7480 [04:39<59:36,  1.86it/s]

 11%|█         | 827/7480 [04:39<59:36,  1.86it/s]
 11%|█         | 828/7480 [04:39<59:35,  1.86it/s]

 11%|█         | 829/7480 [04:40<55:20,  2.00it/s]

 11%|█         | 829/7480 [04:40<55:20,  2.00it/s]
 11%|█         | 830/7480 [04:40<55:19,  2.00it/s]

 11%|█         | 831/7480 [04:41<51:41,  2.14it/s]

 11%|█         | 831/7480 [04:41<51:41,  2.14it/s]
 11%|█         | 832/7480 [04:41<51:41,  2.14it/s]

 11%|█         | 833/7480 [04:41<48:54,  2.26it/s]

 11%|█         | 833/7480 [04:41<48:54,  2.26it/s]
 11%|█         | 834/7480 [04:41<48:54,  2.26it/s]

 11%|█         | 835/7480 [04:42<46:58,  2.36it/s]

 11%|█         | 835/7480 [04:42<46:58,  2.36it/s]
 11%|█         | 836/7480 [04:42<46:58,  2.36it/s]

 11%|█         | 837/7480 [04:43<44:55,  2.46it/s]

 11%|█         | 837/7480 [04:43<44:55,  2.46it/s]
 11%|█         | 838/7480 [04:43<44:54,  2.46it/s]

 11%|█         | 839/7480 [04:44<43:53,  2.52it/s]

 11%|█         | 839/7480 [04:44<43:53,  2.52it/s]
 11%|█         | 840/7480 [04:44<43:53,  2.52it/s]
 11%|█         | 841/7480 [04:44<43:52,  2.52it/s]

 11%|█▏        | 842/7480 [04:44<37:59,  2.91it/s]

 11%|█▏        | 842/7480 [04:44<37:59,  2.91it/s]
 11%|█▏        | 843/7480 [04:44<37:58,  2.91it/s]
 11%|█▏        | 844/7480 [04:44<37:58,  2.91it/s]

 11%|█▏        | 845/7480 [04:45<34:16,  3.23it/s]

 11%|█▏        | 845/7480 [04:45<34:16,  3.23it/s]
 11%|█▏        | 846/7480 [04:45<34:16,  3.23it/s]

 11%|█▏        | 847/7480 [04:46<35:54,  3.08it/s]

 11%|█▏        | 847/7480 [04:46<35:54,  3.08it/s]
 11%|█▏        | 848/7480 [04:46<35:54,  3.08it/s]

 11%|█▏        | 849/7480 [04:47<37:24,  2.95it/s]

 11%|█▏        | 849/7480 [04:47<37:24,  2.95it/s]
 11%|█▏        | 850/7480 [04:47<37:24,  2.95it/s]

 11%|█▏        | 851/7480 [04:47<38:19,  2.88it/s]

 11%|█▏        | 851/7480 [04:47<38:19,  2.88it/s]
 11%|█▏        | 852/7480 [04:47<38:19,  2.88it/s]

 11%|█▏        | 853/7480 [04:48<38:11,  2.89it/s]

 11%|█▏        | 853/7480 [04:48<38:11,  2.89it/s]
 11%|█▏        | 854/7480 [04:48<38:11,  2.89it/s]

 11%|█▏        | 855/7480 [04:49<47:22,  2.33it/s]

 11%|█▏        | 855/7480 [04:49<47:22,  2.33it/s]
 11%|█▏        | 856/7480 [04:49<47:22,  2.33it/s]

 11%|█▏        | 857/7480 [04:52<1:13:13,  1.51it/s]

 11%|█▏        | 857/7480 [04:52<1:13:13,  1.51it/s]
 11%|█▏        | 858/7480 [04:52<1:13:13,  1.51it/s]

 11%|█▏        | 859/7480 [04:52<1:02:59,  1.75it/s]

 11%|█▏        | 859/7480 [04:52<1:02:59,  1.75it/s]
 11%|█▏        | 860/7480 [04:52<1:02:58,  1.75it/s]

 12%|█▏        | 861/7480 [04:53<55:21,  1.99it/s]

 12%|█▏        | 861/7480 [04:53<55:21,  1.99it/s]
 12%|█▏        | 862/7480 [04:53<55:20,  1.99it/s]
 12%|█▏        | 863/7480 [04:53<55:20,  1.99it/s]

 12%|█▏        | 864/7480 [04:54<44:29,  2.48it/s]

 12%|█▏        | 864/7480 [04:54<44:29,  2.48it/s]
 12%|█▏        | 865/7480 [04:54<44:29,  2.48it/s]

 12%|█▏        | 866/7480 [04:55<43:22,  2.54it/s]

 12%|█▏        | 866/7480 [04:55<43:22,  2.54it/s]
 12%|█▏        | 867/7480 [04:55<43:22,  2.54it/s]

 12%|█▏        | 868/7480 [04:55<42:27,  2.60it/s]

 12%|█▏        | 868/7480 [04:55<42:27,  2.60it/s]
 12%|█▏        | 869/7480 [04:55<42:26,  2.60it/s]

 12%|█▏        | 870/7480 [04:56<41:53,  2.63it/s]

 12%|█▏        | 870/7480 [04:56<41:53,  2.63it/s]
 12%|█▏        | 871/7480 [04:56<41:52,  2.63it/s]

 12%|█▏        | 872/7480 [04:57<41:26,  2.66it/s]

 12%|█▏        | 872/7480 [04:57<41:26,  2.66it/s]
 12%|█▏        | 873/7480 [04:57<41:26,  2.66it/s]

 12%|█▏        | 874/7480 [04:58<40:34,  2.71it/s]

 12%|█▏        | 874/7480 [04:58<40:34,  2.71it/s]
 12%|█▏        | 875/7480 [04:58<40:34,  2.71it/s]

 12%|█▏        | 876/7480 [04:58<40:43,  2.70it/s]

 12%|█▏        | 876/7480 [04:58<40:43,  2.70it/s]
 12%|█▏        | 877/7480 [04:58<40:43,  2.70it/s]
 12%|█▏        | 878/7480 [04:58<40:43,  2.70it/s]

 12%|█▏        | 879/7480 [04:59<35:24,  3.11it/s]

 12%|█▏        | 879/7480 [04:59<35:24,  3.11it/s]
 12%|█▏        | 880/7480 [04:59<35:23,  3.11it/s]

 12%|█▏        | 881/7480 [05:00<36:16,  3.03it/s]

 12%|█▏        | 881/7480 [05:00<36:16,  3.03it/s]
 12%|█▏        | 882/7480 [05:00<36:16,  3.03it/s]

 12%|█▏        | 883/7480 [05:00<37:10,  2.96it/s]

 12%|█▏        | 883/7480 [05:00<37:10,  2.96it/s]
 12%|█▏        | 884/7480 [05:00<37:09,  2.96it/s]

 12%|█▏        | 885/7480 [05:01<38:14,  2.87it/s]

 12%|█▏        | 885/7480 [05:01<38:14,  2.87it/s]
 12%|█▏        | 886/7480 [05:01<38:14,  2.87it/s]

 12%|█▏        | 887/7480 [05:04<1:15:32,  1.45it/s]

 12%|█▏        | 887/7480 [05:04<1:15:32,  1.45it/s]
 12%|█▏        | 888/7480 [05:04<1:15:32,  1.45it/s]

 12%|█▏        | 889/7480 [05:05<1:04:18,  1.71it/s]

 12%|█▏        | 889/7480 [05:05<1:04:18,  1.71it/s]
 12%|█▏        | 890/7480 [05:05<1:04:18,  1.71it/s]

 12%|█▏        | 891/7480 [05:06<57:10,  1.92it/s]

 12%|█▏        | 891/7480 [05:06<57:10,  1.92it/s]
 12%|█▏        | 892/7480 [05:06<57:10,  1.92it/s]

 12%|█▏        | 893/7480 [05:06<51:38,  2.13it/s]

 12%|█▏        | 893/7480 [05:06<51:38,  2.13it/s]
 12%|█▏        | 894/7480 [05:06<51:38,  2.13it/s]

 12%|█▏        | 895/7480 [05:07<47:24,  2.32it/s]

 12%|█▏        | 895/7480 [05:07<47:24,  2.32it/s]
 12%|█▏        | 896/7480 [05:07<47:23,  2.32it/s]

 12%|█▏        | 897/7480 [05:08<45:24,  2.42it/s]

 12%|█▏        | 897/7480 [05:08<45:24,  2.42it/s]
 12%|█▏        | 898/7480 [05:08<45:23,  2.42it/s]

 12%|█▏        | 899/7480 [05:09<44:31,  2.46it/s]

 12%|█▏        | 899/7480 [05:09<44:31,  2.46it/s]
 12%|█▏        | 900/7480 [05:09<44:30,  2.46it/s]

 12%|█▏        | 901/7480 [05:09<42:52,  2.56it/s]

 12%|█▏        | 901/7480 [05:09<42:52,  2.56it/s]
 12%|█▏        | 902/7480 [05:09<42:52,  2.56it/s]

 12%|█▏        | 903/7480 [05:10<41:43,  2.63it/s]

 12%|█▏        | 903/7480 [05:10<41:43,  2.63it/s]
 12%|█▏        | 904/7480 [05:10<41:42,  2.63it/s]

 12%|█▏        | 905/7480 [05:11<41:36,  2.63it/s]

 12%|█▏        | 905/7480 [05:11<41:36,  2.63it/s]
 12%|█▏        | 906/7480 [05:11<41:35,  2.63it/s]
 12%|█▏        | 907/7480 [05:11<41:35,  2.63it/s]
 12%|█▏        | 908/7480 [05:11<41:35,  2.63it/s]

 12%|█▏        | 909/7480 [05:11<31:54,  3.43it/s]

 12%|█▏        | 909/7480 [05:11<31:54,  3.43it/s]
 12%|█▏        | 910/7480 [05:11<31:54,  3.43it/s]
 12%|█▏        | 911/7480 [05:11<31:54,  3.43it/s]

 12%|█▏        | 912/7480 [05:12<30:00,  3.65it/s]

 12%|█▏        | 912/7480 [05:12<30:00,  3.65it/s]
 12%|█▏        | 913/7480 [05:12<30:00,  3.65it/s]

 12%|█▏        | 914/7480 [05:13<32:36,  3.36it/s]

 12%|█▏        | 914/7480 [05:13<32:36,  3.36it/s]
 12%|█▏        | 915/7480 [05:13<32:35,  3.36it/s]

 12%|█▏        | 916/7480 [05:14<34:26,  3.18it/s]

 12%|█▏        | 916/7480 [05:14<34:26,  3.18it/s]
 12%|█▏        | 917/7480 [05:14<34:25,  3.18it/s]

 12%|█▏        | 918/7480 [05:17<1:08:48,  1.59it/s]

 12%|█▏        | 918/7480 [05:17<1:08:48,  1.59it/s]
 12%|█▏        | 919/7480 [05:17<1:08:47,  1.59it/s]
 12%|█▏        | 920/7480 [05:17<1:08:47,  1.59it/s]
 12%|█▏        | 921/7480 [05:17<1:08:46,  1.59it/s]
 12%|█▏        | 922/7480 [05:17<1:08:45,  1.59it/s]

 12%|█▏        | 923/7480 [05:17<43:08,  2.53it/s]

 12%|█▏        | 923/7480 [05:17<43:08,  2.53it/s]
 12%|█▏        | 924/7480 [05:17<43:07,  2.53it/s]

 12%|█▏        | 925/7480 [05:18<42:34,  2.57it/s]

 12%|█▏        | 925/7480 [05:18<42:34,  2.57it/s]
 12%|█▏        | 926/7480 [05:18<42:34,  2.57it/s]
 12%|█▏        | 927/7480 [05:18<42:33,  2.57it/s]

 12%|█▏        | 928/7480 [05:19<37:54,  2.88it/s]

 12%|█▏        | 928/7480 [05:19<37:54,  2.88it/s]
 12%|█▏        | 929/7480 [05:19<37:54,  2.88it/s]

 12%|█▏        | 930/7480 [05:20<38:16,  2.85it/s]

 12%|█▏        | 930/7480 [05:20<38:16,  2.85it/s]
 12%|█▏        | 931/7480 [05:20<38:15,  2.85it/s]

 12%|█▏        | 932/7480 [05:20<39:10,  2.79it/s]

 12%|█▏        | 932/7480 [05:20<39:10,  2.79it/s]
 12%|█▏        | 933/7480 [05:20<39:10,  2.79it/s]

 12%|█▏        | 934/7480 [05:21<39:59,  2.73it/s]

 12%|█▏        | 934/7480 [05:21<39:59,  2.73it/s]
 12%|█▎        | 935/7480 [05:21<39:59,  2.73it/s]
 13%|█▎        | 936/7480 [05:21<39:58,  2.73it/s]

 13%|█▎        | 937/7480 [05:22<35:28,  3.07it/s]

 13%|█▎        | 937/7480 [05:22<35:28,  3.07it/s]
 13%|█▎        | 938/7480 [05:22<35:28,  3.07it/s]

 13%|█▎        | 939/7480 [05:23<36:29,  2.99it/s]

 13%|█▎        | 939/7480 [05:23<36:29,  2.99it/s]
 13%|█▎        | 940/7480 [05:23<36:29,  2.99it/s]

 13%|█▎        | 941/7480 [05:23<37:43,  2.89it/s]

 13%|█▎        | 941/7480 [05:23<37:43,  2.89it/s]
 13%|█▎        | 942/7480 [05:23<37:42,  2.89it/s]
 13%|█▎        | 943/7480 [05:23<37:42,  2.89it/s]

 13%|█▎        | 944/7480 [05:24<33:51,  3.22it/s]

 13%|█▎        | 944/7480 [05:24<33:51,  3.22it/s]
 13%|█▎        | 945/7480 [05:24<33:51,  3.22it/s]
 13%|█▎        | 946/7480 [05:24<33:51,  3.22it/s]
 13%|█▎        | 947/7480 [05:24<33:50,  3.22it/s]

 13%|█▎        | 948/7480 [05:25<28:11,  3.86it/s]

 13%|█▎        | 948/7480 [05:25<28:11,  3.86it/s]
 13%|█▎        | 949/7480 [05:25<28:10,  3.86it/s]

 13%|█▎        | 950/7480 [05:26<30:57,  3.52it/s]

 13%|█▎        | 950/7480 [05:26<30:57,  3.52it/s]
 13%|█▎        | 951/7480 [05:26<30:57,  3.52it/s]

 13%|█▎        | 952/7480 [05:26<33:11,  3.28it/s]

 13%|█▎        | 952/7480 [05:26<33:11,  3.28it/s]
 13%|█▎        | 953/7480 [05:26<33:10,  3.28it/s]

 13%|█▎        | 954/7480 [05:29<1:07:53,  1.60it/s]

 13%|█▎        | 954/7480 [05:29<1:07:53,  1.60it/s]
 13%|█▎        | 955/7480 [05:29<1:07:52,  1.60it/s]

 13%|█▎        | 956/7480 [05:30<59:58,  1.81it/s]

 13%|█▎        | 956/7480 [05:30<59:58,  1.81it/s]
 13%|█▎        | 957/7480 [05:30<59:58,  1.81it/s]

 13%|█▎        | 958/7480 [05:31<54:53,  1.98it/s]
 13%|█▎        | 963/7480 [05:31<28:45,  3.78it/s]

 13%|█▎        | 958/7480 [05:31<54:53,  1.98it/s]
 13%|█▎        | 959/7480 [05:31<54:52,  1.98it/s]
 13%|█▎        | 960/7480 [05:31<54:52,  1.98it/s]
 13%|█▎        | 961/7480 [05:31<54:51,  1.98it/s]
 13%|█▎        | 962/7480 [05:31<54:51,  1.98it/s]
 13%|█▎        | 963/7480 [05:31<28:45,  3.78it/s]
 13%|█▎        | 964/7480 [05:31<28:45,  3.78it/s]
 13%|█▎        | 965/7480 [05:31<28:45,  3.78it/s]
 13%|█▎        | 966/7480 [05:31<28:44,  3.78it/s]
 13%|█▎        | 967/7480 [05:31<28:44,  3.78it/s]
 13%|█▎        | 968/7480 [05:31<28:44,  3.78it/s]
 13%|█▎        | 969/7480 [05:31<28:44,  3.78it/s]
 13%|█▎        | 970/7480 [05:31<28:43,  3.78it/s]
 13%|█▎        | 971/7480 [05:31<28:43,  3.78it/s]

 13%|█▎        | 972/7480 [05:32<17:47,  6.10it/s]

 13%|█▎        | 972/7480 [05:32<17:47,  6.10it/s]
 13%|█▎        | 973/7480 [05:32<17:47,  6.10it/s]

 13%|█▎        | 974/7480 [05:33<21:16,  5.10it/s]

 13%|█▎        | 974/7480 [05:33<21:16,  5.10it/s]
 13%|█▎        | 975/7480 [05:33<21:15,  5.10it/s]

 13%|█▎        | 976/7480 [05:33<24:15,  4.47it/s]

 13%|█▎        | 976/7480 [05:33<24:15,  4.47it/s]
 13%|█▎        | 977/7480 [05:33<24:15,  4.47it/s]

 13%|█▎        | 978/7480 [05:34<27:53,  3.88it/s]

 13%|█▎        | 978/7480 [05:34<27:53,  3.88it/s]
 13%|█▎        | 979/7480 [05:34<27:53,  3.88it/s]

 13%|█▎        | 980/7480 [05:35<31:23,  3.45it/s]

 13%|█▎        | 980/7480 [05:35<31:23,  3.45it/s]
 13%|█▎        | 981/7480 [05:35<31:23,  3.45it/s]

 13%|█▎        | 982/7480 [05:36<33:42,  3.21it/s]

 13%|█▎        | 982/7480 [05:36<33:42,  3.21it/s]
 13%|█▎        | 983/7480 [05:36<33:41,  3.21it/s]

 13%|█▎        | 984/7480 [05:36<35:28,  3.05it/s]

 13%|█▎        | 984/7480 [05:36<35:28,  3.05it/s]
 13%|█▎        | 985/7480 [05:36<35:28,  3.05it/s]

 13%|█▎        | 986/7480 [05:37<36:52,  2.94it/s]

 13%|█▎        | 986/7480 [05:37<36:52,  2.94it/s]
 13%|█▎        | 987/7480 [05:37<36:51,  2.94it/s]
 13%|█▎        | 988/7480 [05:37<36:51,  2.94it/s]

 13%|█▎        | 989/7480 [05:38<33:17,  3.25it/s]

 13%|█▎        | 989/7480 [05:38<33:17,  3.25it/s]
 13%|█▎        | 990/7480 [05:38<33:17,  3.25it/s]

 13%|█▎        | 991/7480 [05:39<34:33,  3.13it/s]
 13%|█▎        | 996/7480 [05:39<19:05,  5.66it/s]

 13%|█▎        | 991/7480 [05:39<34:33,  3.13it/s]
 13%|█▎        | 992/7480 [05:39<34:32,  3.13it/s]
 13%|█▎        | 993/7480 [05:39<34:32,  3.13it/s]
 13%|█▎        | 994/7480 [05:39<34:32,  3.13it/s]
 13%|█▎        | 995/7480 [05:39<34:31,  3.13it/s]
 13%|█▎        | 996/7480 [05:39<19:05,  5.66it/s]

 13%|█▎        | 998/7480 [05:42<50:29,  2.14it/s]

 13%|█▎        | 997/7480 [05:42<19:05,  5.66it/s]
 13%|█▎        | 998/7480 [05:42<50:29,  2.14it/s]

 13%|█▎        | 1000/7480 [05:42<37:02,  2.92it/s]
 89%|████████▉ | 8/9 [39:30<05:14, 314.81s/it]

 13%|█▎        | 999/7480 [05:42<50:29,  2.14it/s]
 13%|█▎        | 1000/7480 [05:42<48:03,  2.25it/s]
                     MLUT4_AT.232A  MLUT4_RQ.2BTLS  MLUT4_TE.252A  \
Time
2025-05-25 05:20:05       0.852984        0.855904       0.842414
2025-05-25 05:30:05       0.876511        0.874611       0.847393
2025-05-25 05:35:05       0.877479        0.885625       0.860507
2025-05-25 05:40:05       0.878625        0.849563       0.860377
2025-05-25 05:45:05       0.877141        0.871733       0.849503

                     MLUT4_SIV.B7921  MLUT4_AIA792101B  MLUT4_PDT.956  \
Time
2025-05-25 05:20:05         0.903258          0.872434       0.899219
2025-05-25 05:30:05         0.903158          0.872244       0.916372
2025-05-25 05:35:05         0.903349          0.872158       0.914016
2025-05-25 05:40:05         0.903300          0.872148       0.910043
2025-05-25 05:45:05         0.903219          0.872148       0.914286

                     MLUT4_TE.252F  MLUT4_PT.231  MLUT4_FIC.231C  \
Time
2025-05-25 05:20:05       0.887579      0.869354        0.857897
2025-05-25 05:30:05       0.879727      0.867235        0.857888
2025-05-25 05:35:05       0.893944      0.867041        0.857883
2025-05-25 05:40:05       0.872940      0.866275        0.857879
2025-05-25 05:45:05       0.876962      0.865383        0.857874

                     MLUT4_FIC.231A  ...  DeSOx_2nd  MLUT4_AIC.232B  \
Time                                 ...
2025-05-25 05:20:05        0.859975  ...   0.880695       85.012138
2025-05-25 05:30:05        0.856716  ...   0.881114       88.954571
2025-05-25 05:35:05        0.860662  ...   0.880696       93.745851
2025-05-25 05:40:05        0.859286  ...   0.881061       85.305571
2025-05-25 05:45:05        0.859582  ...   0.881237      101.874866

                     MLUT4_AT.240  prev_target  MLUT4_AT-240  prediction  \
Time
2025-05-25 05:20:05     14.151761     0.888806     10.142385    0.881324
2025-05-25 05:30:05      9.316637     0.890104     10.575424    0.880864
2025-05-25 05:35:05      6.155893     0.890862     11.184283    0.881132
2025-05-25 05:40:05     12.572007     0.891577     10.146143    0.881572
2025-05-25 05:45:05      5.497275     0.891864     12.098968    0.880669

                     abs_error  threshold  y3_prediction  y3_abs_error
Time
2025-05-25 05:20:05   0.000629   0.000629      10.088916      0.053469
2025-05-25 05:30:05   0.000251   0.000591      10.597727      0.022302
2025-05-25 05:35:05   0.000436   0.000590      11.143392      0.040890
2025-05-25 05:40:05   0.000511   0.000593      10.102573      0.043571
2025-05-25 05:45:05   0.000568   0.000604      12.156787      0.057820

[5 rows x 50 columns]

  0%|          | 0/7480 [00:00<?, ?it/s]

  0%|          | 0/7480 [00:00<?, ?it/s]

  0%|          | 1/7480 [00:00<1:24:49,  1.47it/s]
  0%|          | 5/7480 [00:00<15:22,  8.10it/s]

  0%|          | 1/7480 [00:00<1:24:49,  1.47it/s]
  0%|          | 2/7480 [00:00<1:24:48,  1.47it/s]
  0%|          | 3/7480 [00:00<1:24:48,  1.47it/s]
  0%|          | 4/7480 [00:00<1:24:47,  1.47it/s]
  0%|          | 5/7480 [00:00<15:22,  8.10it/s]
  0%|          | 6/7480 [00:00<15:22,  8.10it/s]

  0%|          | 8/7480 [00:01<21:34,  5.77it/s]

  0%|          | 7/7480 [00:01<15:22,  8.10it/s]
  0%|          | 8/7480 [00:01<21:34,  5.77it/s]

  0%|          | 10/7480 [00:02<27:12,  4.58it/s]

  0%|          | 9/7480 [00:02<21:33,  5.77it/s]
  0%|          | 10/7480 [00:02<27:12,  4.58it/s]

  0%|          | 12/7480 [00:02<31:05,  4.00it/s]

  0%|          | 11/7480 [00:02<27:12,  4.58it/s]
  0%|          | 12/7480 [00:02<31:05,  4.00it/s]

  0%|          | 13/7480 [00:03<40:15,  3.09it/s]

  0%|          | 13/7480 [00:03<40:15,  3.09it/s]
  0%|          | 14/7480 [00:03<40:15,  3.09it/s]

  0%|          | 15/7480 [00:04<40:01,  3.11it/s]

  0%|          | 15/7480 [00:04<40:01,  3.11it/s]
  0%|          | 16/7480 [00:04<40:01,  3.11it/s]

  0%|          | 17/7480 [00:04<40:42,  3.05it/s]

  0%|          | 17/7480 [00:04<40:42,  3.05it/s]
  0%|          | 18/7480 [00:04<40:42,  3.05it/s]

  0%|          | 19/7480 [00:07<1:25:33,  1.45it/s]

  0%|          | 19/7480 [00:07<1:25:33,  1.45it/s]
  0%|          | 20/7480 [00:07<1:25:33,  1.45it/s]

  0%|          | 21/7480 [00:08<1:10:54,  1.75it/s]

  0%|          | 21/7480 [00:08<1:10:54,  1.75it/s]
  0%|          | 22/7480 [00:08<1:10:53,  1.75it/s]

  0%|          | 23/7480 [00:08<1:01:53,  2.01it/s]

  0%|          | 23/7480 [00:08<1:01:53,  2.01it/s]
  0%|          | 24/7480 [00:08<1:01:52,  2.01it/s]

  0%|          | 25/7480 [00:09<55:14,  2.25it/s]

  0%|          | 25/7480 [00:09<55:14,  2.25it/s]
  0%|          | 26/7480 [00:09<55:13,  2.25it/s]

  0%|          | 27/7480 [00:10<51:44,  2.40it/s]

  0%|          | 27/7480 [00:10<51:44,  2.40it/s]
  0%|          | 28/7480 [00:10<51:44,  2.40it/s]

  0%|          | 29/7480 [00:10<49:18,  2.52it/s]

  0%|          | 29/7480 [00:10<49:18,  2.52it/s]
  0%|          | 30/7480 [00:11<49:18,  2.52it/s]

  0%|          | 31/7480 [00:11<46:59,  2.64it/s]

  0%|          | 31/7480 [00:11<46:59,  2.64it/s]
  0%|          | 32/7480 [00:11<46:59,  2.64it/s]

  0%|          | 33/7480 [00:12<45:44,  2.71it/s]

  0%|          | 33/7480 [00:12<45:44,  2.71it/s]
  0%|          | 34/7480 [00:12<45:43,  2.71it/s]
  0%|          | 35/7480 [00:12<45:43,  2.71it/s]
  0%|          | 36/7480 [00:12<45:43,  2.71it/s]
  0%|          | 37/7480 [00:12<45:42,  2.71it/s]
  1%|          | 38/7480 [00:12<45:42,  2.71it/s]
  1%|          | 39/7480 [00:12<45:42,  2.71it/s]
  1%|          | 40/7480 [00:12<45:41,  2.71it/s]
  1%|          | 41/7480 [00:12<45:41,  2.71it/s]

  1%|          | 42/7480 [00:13<21:48,  5.69it/s]

  1%|          | 42/7480 [00:13<21:48,  5.69it/s]
  1%|          | 43/7480 [00:13<21:48,  5.69it/s]
  1%|          | 44/7480 [00:13<21:47,  5.69it/s]

  1%|          | 45/7480 [00:13<23:05,  5.37it/s]

  1%|          | 45/7480 [00:13<23:05,  5.37it/s]
  1%|          | 46/7480 [00:13<23:05,  5.37it/s]

  1%|          | 47/7480 [00:14<26:18,  4.71it/s]

  1%|          | 47/7480 [00:14<26:18,  4.71it/s]
  1%|          | 48/7480 [00:14<26:18,  4.71it/s]
  1%|          | 49/7480 [00:14<26:18,  4.71it/s]
  1%|          | 50/7480 [00:14<26:18,  4.71it/s]

  1%|          | 51/7480 [00:15<24:44,  5.00it/s]

  1%|          | 51/7480 [00:15<24:44,  5.00it/s]
  1%|          | 52/7480 [00:15<24:44,  5.00it/s]

  1%|          | 53/7480 [00:15<27:43,  4.46it/s]

  1%|          | 53/7480 [00:15<27:43,  4.46it/s]
  1%|          | 54/7480 [00:15<27:43,  4.46it/s]

  1%|          | 55/7480 [00:16<30:38,  4.04it/s]

  1%|          | 55/7480 [00:16<30:38,  4.04it/s]
  1%|          | 56/7480 [00:16<30:38,  4.04it/s]

  1%|          | 57/7480 [00:16<32:30,  3.81it/s]

  1%|          | 57/7480 [00:16<32:30,  3.81it/s]
  1%|          | 58/7480 [00:16<32:30,  3.81it/s]

  1%|          | 59/7480 [00:19<1:06:03,  1.87it/s]

  1%|          | 59/7480 [00:19<1:06:03,  1.87it/s]
  1%|          | 60/7480 [00:19<1:06:02,  1.87it/s]

  1%|          | 61/7480 [00:20<1:03:42,  1.94it/s]

  1%|          | 61/7480 [00:20<1:03:42,  1.94it/s]
  1%|          | 62/7480 [00:20<1:03:42,  1.94it/s]

  1%|          | 63/7480 [00:21<56:16,  2.20it/s]

  1%|          | 63/7480 [00:21<56:16,  2.20it/s]
  1%|          | 64/7480 [00:21<56:15,  2.20it/s]
  1%|          | 65/7480 [00:21<56:15,  2.20it/s]
  1%|          | 66/7480 [00:21<56:14,  2.20it/s]
  1%|          | 67/7480 [00:21<56:14,  2.20it/s]
  1%|          | 68/7480 [00:21<56:13,  2.20it/s]

  1%|          | 69/7480 [00:21<32:57,  3.75it/s]

  1%|          | 69/7480 [00:21<32:57,  3.75it/s]
  1%|          | 70/7480 [00:21<32:57,  3.75it/s]
  1%|          | 71/7480 [00:21<32:56,  3.75it/s]

  1%|          | 72/7480 [00:22<31:12,  3.96it/s]

  1%|          | 72/7480 [00:22<31:12,  3.96it/s]
  1%|          | 73/7480 [00:22<31:12,  3.96it/s]

  1%|          | 74/7480 [00:23<32:31,  3.79it/s]

  1%|          | 74/7480 [00:23<32:31,  3.79it/s]
  1%|          | 75/7480 [00:23<32:31,  3.79it/s]

  1%|          | 76/7480 [00:23<34:33,  3.57it/s]

  1%|          | 76/7480 [00:23<34:33,  3.57it/s]
  1%|          | 77/7480 [00:23<34:33,  3.57it/s]

  1%|          | 78/7480 [00:24<35:47,  3.45it/s]

  1%|          | 78/7480 [00:24<35:47,  3.45it/s]
  1%|          | 79/7480 [00:24<35:47,  3.45it/s]

  1%|          | 80/7480 [00:25<37:11,  3.32it/s]

  1%|          | 80/7480 [00:25<37:11,  3.32it/s]
  1%|          | 81/7480 [00:25<37:10,  3.32it/s]

  1%|          | 82/7480 [00:25<38:32,  3.20it/s]

  1%|          | 82/7480 [00:25<38:32,  3.20it/s]
  1%|          | 83/7480 [00:25<38:32,  3.20it/s]

  1%|          | 84/7480 [00:26<39:30,  3.12it/s]

  1%|          | 84/7480 [00:26<39:30,  3.12it/s]
  1%|          | 85/7480 [00:26<39:30,  3.12it/s]

  1%|          | 86/7480 [00:27<41:20,  2.98it/s]

  1%|          | 86/7480 [00:27<41:20,  2.98it/s]
  1%|          | 87/7480 [00:27<41:19,  2.98it/s]
  1%|          | 88/7480 [00:27<41:19,  2.98it/s]

  1%|          | 89/7480 [00:27<37:34,  3.28it/s]

  1%|          | 89/7480 [00:27<37:34,  3.28it/s]
  1%|          | 90/7480 [00:27<37:34,  3.28it/s]

  1%|          | 91/7480 [00:28<39:09,  3.14it/s]

  1%|          | 91/7480 [00:28<39:09,  3.14it/s]
  1%|          | 92/7480 [00:28<39:09,  3.14it/s]
  1%|          | 93/7480 [00:28<39:08,  3.14it/s]
  1%|▏         | 94/7480 [00:28<39:08,  3.14it/s]

  1%|▏         | 95/7480 [00:29<32:01,  3.84it/s]

  1%|▏         | 95/7480 [00:29<32:01,  3.84it/s]
  1%|▏         | 96/7480 [00:29<32:01,  3.84it/s]

  1%|▏         | 97/7480 [00:30<35:21,  3.48it/s]

  1%|▏         | 97/7480 [00:30<35:21,  3.48it/s]
  1%|▏         | 98/7480 [00:30<35:20,  3.48it/s]
  1%|▏         | 99/7480 [00:30<35:20,  3.48it/s]

  1%|▏         | 100/7480 [00:33<1:05:03,  1.89it/s]

  1%|▏         | 100/7480 [00:33<1:05:03,  1.89it/s]
  1%|▏         | 101/7480 [00:33<1:05:02,  1.89it/s]

  1%|▏         | 102/7480 [00:33<59:58,  2.05it/s]

  1%|▏         | 102/7480 [00:33<59:58,  2.05it/s]
  1%|▏         | 103/7480 [00:33<59:57,  2.05it/s]

  1%|▏         | 104/7480 [00:34<56:14,  2.19it/s]

  1%|▏         | 104/7480 [00:34<56:14,  2.19it/s]
  1%|▏         | 105/7480 [00:34<56:14,  2.19it/s]

  1%|▏         | 106/7480 [00:35<53:43,  2.29it/s]

  1%|▏         | 106/7480 [00:35<53:43,  2.29it/s]
  1%|▏         | 107/7480 [00:35<53:43,  2.29it/s]

  1%|▏         | 108/7480 [00:36<51:40,  2.38it/s]

  1%|▏         | 108/7480 [00:36<51:40,  2.38it/s]
  1%|▏         | 109/7480 [00:36<51:40,  2.38it/s]

  1%|▏         | 110/7480 [00:36<49:27,  2.48it/s]

  1%|▏         | 110/7480 [00:36<49:27,  2.48it/s]
  1%|▏         | 111/7480 [00:36<49:27,  2.48it/s]

  1%|▏         | 112/7480 [00:37<48:33,  2.53it/s]

  1%|▏         | 112/7480 [00:37<48:33,  2.53it/s]
  2%|▏         | 113/7480 [00:37<48:32,  2.53it/s]

  2%|▏         | 114/7480 [00:38<47:40,  2.57it/s]

  2%|▏         | 114/7480 [00:38<47:40,  2.57it/s]
  2%|▏         | 115/7480 [00:38<47:40,  2.57it/s]

  2%|▏         | 116/7480 [00:39<46:16,  2.65it/s]

  2%|▏         | 116/7480 [00:39<46:16,  2.65it/s]
  2%|▏         | 117/7480 [00:39<46:15,  2.65it/s]

  2%|▏         | 118/7480 [00:39<46:10,  2.66it/s]

  2%|▏         | 118/7480 [00:39<46:10,  2.66it/s]
  2%|▏         | 119/7480 [00:39<46:10,  2.66it/s]

  2%|▏         | 120/7480 [00:40<45:29,  2.70it/s]

  2%|▏         | 120/7480 [00:40<45:29,  2.70it/s]
  2%|▏         | 121/7480 [00:40<45:29,  2.70it/s]

  2%|▏         | 122/7480 [00:41<44:54,  2.73it/s]

  2%|▏         | 122/7480 [00:41<44:54,  2.73it/s]
  2%|▏         | 123/7480 [00:41<44:54,  2.73it/s]
  2%|▏         | 124/7480 [00:41<44:54,  2.73it/s]

  2%|▏         | 125/7480 [00:41<39:21,  3.11it/s]

  2%|▏         | 125/7480 [00:41<39:21,  3.11it/s]
  2%|▏         | 126/7480 [00:41<39:21,  3.11it/s]

  2%|▏         | 127/7480 [00:42<40:37,  3.02it/s]

  2%|▏         | 127/7480 [00:42<40:37,  3.02it/s]
  2%|▏         | 128/7480 [00:42<40:36,  3.02it/s]

  2%|▏         | 129/7480 [00:45<1:20:05,  1.53it/s]
  2%|▏         | 134/7480 [00:45<41:35,  2.94it/s]

  2%|▏         | 129/7480 [00:45<1:20:05,  1.53it/s]
  2%|▏         | 130/7480 [00:45<1:20:04,  1.53it/s]
  2%|▏         | 131/7480 [00:45<1:20:03,  1.53it/s]
  2%|▏         | 132/7480 [00:45<1:20:03,  1.53it/s]
  2%|▏         | 133/7480 [00:45<1:20:02,  1.53it/s]
  2%|▏         | 134/7480 [00:45<41:35,  2.94it/s]
  2%|▏         | 135/7480 [00:45<41:35,  2.94it/s]
  2%|▏         | 136/7480 [00:45<41:35,  2.94it/s]
  2%|▏         | 137/7480 [00:45<41:34,  2.94it/s]

  2%|▏         | 139/7480 [00:45<25:17,  4.84it/s]

  2%|▏         | 138/7480 [00:45<41:34,  2.94it/s]
  2%|▏         | 139/7480 [00:45<25:17,  4.84it/s]
  2%|▏         | 140/7480 [00:45<25:17,  4.84it/s]
  2%|▏         | 141/7480 [00:45<25:17,  4.84it/s]

  2%|▏         | 142/7480 [00:46<26:49,  4.56it/s]

  2%|▏         | 142/7480 [00:46<26:49,  4.56it/s]
  2%|▏         | 143/7480 [00:46<26:48,  4.56it/s]

  2%|▏         | 144/7480 [00:47<29:34,  4.13it/s]
  2%|▏         | 148/7480 [00:47<20:01,  6.10it/s]

  2%|▏         | 144/7480 [00:47<29:34,  4.13it/s]
  2%|▏         | 145/7480 [00:47<29:33,  4.13it/s]
  2%|▏         | 146/7480 [00:47<29:33,  4.13it/s]
  2%|▏         | 147/7480 [00:47<29:33,  4.13it/s]
  2%|▏         | 148/7480 [00:47<20:01,  6.10it/s]
  2%|▏         | 149/7480 [00:47<20:01,  6.10it/s]

  2%|▏         | 151/7480 [00:48<22:46,  5.36it/s]

  2%|▏         | 150/7480 [00:48<20:01,  6.10it/s]
  2%|▏         | 151/7480 [00:48<22:46,  5.36it/s]

  2%|▏         | 153/7480 [00:48<27:09,  4.50it/s]

  2%|▏         | 152/7480 [00:48<22:46,  5.36it/s]
  2%|▏         | 153/7480 [00:48<27:09,  4.50it/s]

  2%|▏         | 155/7480 [00:49<30:21,  4.02it/s]

  2%|▏         | 154/7480 [00:49<27:09,  4.50it/s]
  2%|▏         | 155/7480 [00:49<30:21,  4.02it/s]
  2%|▏         | 156/7480 [00:49<30:21,  4.02it/s]

  2%|▏         | 157/7480 [00:50<33:30,  3.64it/s]

  2%|▏         | 157/7480 [00:50<33:30,  3.64it/s]
  2%|▏         | 158/7480 [00:50<33:30,  3.64it/s]

  2%|▏         | 159/7480 [00:50<36:35,  3.33it/s]

  2%|▏         | 159/7480 [00:50<36:35,  3.33it/s]
  2%|▏         | 160/7480 [00:50<36:34,  3.33it/s]

  2%|▏         | 161/7480 [00:51<37:55,  3.22it/s]

  2%|▏         | 161/7480 [00:51<37:55,  3.22it/s]
  2%|▏         | 162/7480 [00:51<37:55,  3.22it/s]

  2%|▏         | 163/7480 [00:52<40:03,  3.04it/s]

  2%|▏         | 163/7480 [00:52<40:03,  3.04it/s]
  2%|▏         | 164/7480 [00:52<40:03,  3.04it/s]

  2%|▏         | 165/7480 [00:53<41:01,  2.97it/s]

  2%|▏         | 165/7480 [00:53<41:01,  2.97it/s]
  2%|▏         | 166/7480 [00:53<41:01,  2.97it/s]
  2%|▏         | 167/7480 [00:53<41:01,  2.97it/s]

  2%|▏         | 168/7480 [00:53<36:27,  3.34it/s]

  2%|▏         | 168/7480 [00:53<36:27,  3.34it/s]
  2%|▏         | 169/7480 [00:53<36:26,  3.34it/s]

  2%|▏         | 170/7480 [00:54<38:29,  3.17it/s]
  2%|▏         | 175/7480 [00:54<21:06,  5.77it/s]

  2%|▏         | 170/7480 [00:54<38:29,  3.17it/s]
  2%|▏         | 171/7480 [00:54<38:28,  3.17it/s]
  2%|▏         | 172/7480 [00:54<38:28,  3.17it/s]
  2%|▏         | 173/7480 [00:54<38:28,  3.17it/s]
  2%|▏         | 174/7480 [00:54<38:27,  3.17it/s]
  2%|▏         | 175/7480 [00:54<21:06,  5.77it/s]
  2%|▏         | 176/7480 [00:54<21:06,  5.77it/s]
  2%|▏         | 177/7480 [00:54<21:06,  5.77it/s]
  2%|▏         | 178/7480 [00:54<21:06,  5.77it/s]
  2%|▏         | 179/7480 [00:54<21:06,  5.77it/s]
  2%|▏         | 180/7480 [00:54<21:05,  5.77it/s]
  2%|▏         | 181/7480 [00:54<21:05,  5.77it/s]
  2%|▏         | 182/7480 [00:54<21:05,  5.77it/s]

  2%|▏         | 183/7480 [00:54<10:47, 11.27it/s]
  3%|▎         | 190/7480 [00:54<07:18, 16.64it/s]

  2%|▏         | 183/7480 [00:54<10:47, 11.27it/s]
  2%|▏         | 184/7480 [00:54<10:47, 11.27it/s]
  2%|▏         | 185/7480 [00:54<10:47, 11.27it/s]
  2%|▏         | 186/7480 [00:54<10:47, 11.27it/s]
  2%|▎         | 187/7480 [00:54<10:46, 11.27it/s]
  3%|▎         | 188/7480 [00:54<10:46, 11.27it/s]
  3%|▎         | 189/7480 [00:54<10:46, 11.27it/s]
  3%|▎         | 190/7480 [00:54<07:18, 16.64it/s]
  3%|▎         | 191/7480 [00:54<07:18, 16.64it/s]
  3%|▎         | 192/7480 [00:54<07:18, 16.64it/s]
  3%|▎         | 193/7480 [00:54<07:18, 16.64it/s]

  3%|▎         | 195/7480 [00:55<06:03, 20.07it/s]
  3%|▎         | 207/7480 [00:55<03:36, 33.54it/s]

  3%|▎         | 194/7480 [00:54<07:17, 16.64it/s]
  3%|▎         | 195/7480 [00:55<06:03, 20.07it/s]
  3%|▎         | 196/7480 [00:55<06:02, 20.07it/s]
  3%|▎         | 197/7480 [00:55<06:02, 20.07it/s]
  3%|▎         | 198/7480 [00:55<06:02, 20.07it/s]
  3%|▎         | 199/7480 [00:55<06:02, 20.07it/s]
  3%|▎         | 200/7480 [00:55<06:02, 20.07it/s]
  3%|▎         | 201/7480 [00:55<06:02, 20.07it/s]
  3%|▎         | 202/7480 [00:55<06:02, 20.07it/s]
  3%|▎         | 203/7480 [00:55<06:02, 20.07it/s]
  3%|▎         | 204/7480 [00:55<06:02, 20.07it/s]
  3%|▎         | 205/7480 [00:55<06:02, 20.07it/s]
  3%|▎         | 206/7480 [00:55<06:02, 20.07it/s]
  3%|▎         | 207/7480 [00:55<03:36, 33.54it/s]
  3%|▎         | 208/7480 [00:55<03:36, 33.54it/s]
  3%|▎         | 209/7480 [00:55<03:36, 33.54it/s]

  3%|▎         | 214/7480 [00:55<03:21, 36.02it/s]

  3%|▎         | 210/7480 [00:55<03:36, 33.54it/s]
  3%|▎         | 211/7480 [00:55<03:36, 33.54it/s]
  3%|▎         | 212/7480 [00:55<03:36, 33.54it/s]
  3%|▎         | 213/7480 [00:55<03:36, 33.54it/s]
  3%|▎         | 214/7480 [00:55<03:21, 36.02it/s]
  3%|▎         | 215/7480 [00:58<03:21, 36.02it/s]
  3%|▎         | 216/7480 [00:58<03:21, 36.02it/s]
  3%|▎         | 217/7480 [00:59<03:21, 36.02it/s]
  3%|▎         | 218/7480 [00:59<03:21, 36.02it/s]

  3%|▎         | 220/7480 [00:59<26:21,  4.59it/s]

  3%|▎         | 219/7480 [00:59<03:21, 36.02it/s]
  3%|▎         | 220/7480 [00:59<26:21,  4.59it/s]
  3%|▎         | 221/7480 [01:00<26:21,  4.59it/s]
  3%|▎         | 222/7480 [01:00<26:21,  4.59it/s]

  3%|▎         | 224/7480 [01:01<29:42,  4.07it/s]

  3%|▎         | 223/7480 [01:01<26:21,  4.59it/s]
  3%|▎         | 224/7480 [01:01<29:42,  4.07it/s]

  3%|▎         | 227/7480 [01:02<30:14,  4.00it/s]
  3%|▎         | 232/7480 [01:02<22:06,  5.46it/s]

  3%|▎         | 225/7480 [01:02<29:41,  4.07it/s]
  3%|▎         | 226/7480 [01:02<29:41,  4.07it/s]
  3%|▎         | 227/7480 [01:02<30:14,  4.00it/s]
  3%|▎         | 228/7480 [01:02<30:14,  4.00it/s]
  3%|▎         | 229/7480 [01:02<30:13,  4.00it/s]
  3%|▎         | 230/7480 [01:02<30:13,  4.00it/s]
  3%|▎         | 231/7480 [01:02<30:13,  4.00it/s]
  3%|▎         | 232/7480 [01:02<22:06,  5.46it/s]
  3%|▎         | 233/7480 [01:02<22:06,  5.46it/s]
  3%|▎         | 234/7480 [01:02<22:06,  5.46it/s]
  3%|▎         | 235/7480 [01:02<22:06,  5.46it/s]

  3%|▎         | 236/7480 [01:02<22:22,  5.40it/s]

  3%|▎         | 236/7480 [01:02<22:22,  5.40it/s]
  3%|▎         | 237/7480 [01:02<22:22,  5.40it/s]

  3%|▎         | 239/7480 [01:03<24:32,  4.92it/s]

  3%|▎         | 238/7480 [01:03<22:21,  5.40it/s]
  3%|▎         | 239/7480 [01:03<24:32,  4.92it/s]

  3%|▎         | 241/7480 [01:04<28:22,  4.25it/s]

  3%|▎         | 240/7480 [01:04<24:32,  4.92it/s]
  3%|▎         | 241/7480 [01:04<28:22,  4.25it/s]

  3%|▎         | 243/7480 [01:05<31:39,  3.81it/s]

  3%|▎         | 242/7480 [01:05<28:22,  4.25it/s]
  3%|▎         | 243/7480 [01:05<31:39,  3.81it/s]
  3%|▎         | 244/7480 [01:05<31:39,  3.81it/s]
  3%|▎         | 245/7480 [01:05<31:39,  3.81it/s]

  3%|▎         | 246/7480 [01:06<31:26,  3.84it/s]

  3%|▎         | 246/7480 [01:06<31:26,  3.84it/s]
  3%|▎         | 247/7480 [01:06<31:25,  3.84it/s]
  3%|▎         | 248/7480 [01:06<31:25,  3.84it/s]
  3%|▎         | 249/7480 [01:06<31:25,  3.84it/s]
  3%|▎         | 250/7480 [01:06<31:25,  3.84it/s]

  3%|▎         | 251/7480 [01:06<25:54,  4.65it/s]

  3%|▎         | 251/7480 [01:06<25:54,  4.65it/s]
  3%|▎         | 252/7480 [01:06<25:54,  4.65it/s]
  3%|▎         | 253/7480 [01:06<25:54,  4.65it/s]

  3%|▎         | 254/7480 [01:07<26:55,  4.47it/s]

  3%|▎         | 254/7480 [01:07<26:55,  4.47it/s]
  3%|▎         | 255/7480 [01:07<26:55,  4.47it/s]
  3%|▎         | 256/7480 [01:07<26:54,  4.47it/s]

  3%|▎         | 257/7480 [01:08<30:02,  4.01it/s]

  3%|▎         | 257/7480 [01:08<30:02,  4.01it/s]
  3%|▎         | 258/7480 [01:08<30:02,  4.01it/s]

  3%|▎         | 259/7480 [01:11<58:26,  2.06it/s]

  3%|▎         | 259/7480 [01:11<58:26,  2.06it/s]
  3%|▎         | 260/7480 [01:11<58:25,  2.06it/s]

  3%|▎         | 261/7480 [01:11<54:58,  2.19it/s]

  3%|▎         | 261/7480 [01:11<54:58,  2.19it/s]
  4%|▎         | 262/7480 [01:11<54:57,  2.19it/s]

  4%|▎         | 263/7480 [01:12<52:05,  2.31it/s]

  4%|▎         | 263/7480 [01:12<52:05,  2.31it/s]
  4%|▎         | 264/7480 [01:12<52:05,  2.31it/s]

  4%|▎         | 265/7480 [01:13<50:06,  2.40it/s]

  4%|▎         | 265/7480 [01:13<50:06,  2.40it/s]
  4%|▎         | 266/7480 [01:13<50:05,  2.40it/s]

  4%|▎         | 267/7480 [01:14<48:52,  2.46it/s]

  4%|▎         | 267/7480 [01:14<48:52,  2.46it/s]
  4%|▎         | 268/7480 [01:14<48:52,  2.46it/s]
  4%|▎         | 269/7480 [01:14<48:52,  2.46it/s]
  4%|▎         | 270/7480 [01:14<48:51,  2.46it/s]

  4%|▎         | 271/7480 [01:14<37:14,  3.23it/s]

  4%|▎         | 271/7480 [01:14<37:14,  3.23it/s]
  4%|▎         | 272/7480 [01:14<37:14,  3.23it/s]

  4%|▎         | 273/7480 [01:15<39:16,  3.06it/s]

  4%|▎         | 273/7480 [01:15<39:16,  3.06it/s]
  4%|▎         | 274/7480 [01:15<39:16,  3.06it/s]

  4%|▎         | 275/7480 [01:16<40:53,  2.94it/s]

  4%|▎         | 275/7480 [01:16<40:53,  2.94it/s]
  4%|▎         | 276/7480 [01:16<40:53,  2.94it/s]

  4%|▎         | 277/7480 [01:17<42:38,  2.82it/s]

  4%|▎         | 277/7480 [01:17<42:38,  2.82it/s]
  4%|▎         | 278/7480 [01:17<42:38,  2.82it/s]

  4%|▎         | 279/7480 [01:18<44:07,  2.72it/s]

  4%|▎         | 279/7480 [01:18<44:07,  2.72it/s]
  4%|▎         | 280/7480 [01:18<44:07,  2.72it/s]

  4%|▍         | 281/7480 [01:18<44:42,  2.68it/s]

  4%|▍         | 281/7480 [01:18<44:42,  2.68it/s]
  4%|▍         | 282/7480 [01:18<44:42,  2.68it/s]

  4%|▍         | 283/7480 [01:19<45:06,  2.66it/s]

  4%|▍         | 283/7480 [01:19<45:06,  2.66it/s]
  4%|▍         | 284/7480 [01:19<45:06,  2.66it/s]
  4%|▍         | 285/7480 [01:19<45:06,  2.66it/s]

  4%|▍         | 286/7480 [01:20<39:33,  3.03it/s]
  4%|▍         | 291/7480 [01:20<21:57,  5.46it/s]

  4%|▍         | 286/7480 [01:20<39:33,  3.03it/s]
  4%|▍         | 287/7480 [01:20<39:32,  3.03it/s]
  4%|▍         | 288/7480 [01:20<39:32,  3.03it/s]
  4%|▍         | 289/7480 [01:20<39:32,  3.03it/s]
  4%|▍         | 290/7480 [01:20<39:31,  3.03it/s]
  4%|▍         | 291/7480 [01:20<21:57,  5.46it/s]
  4%|▍         | 292/7480 [01:20<21:57,  5.46it/s]
  4%|▍         | 293/7480 [01:20<21:57,  5.46it/s]

  4%|▍         | 294/7480 [01:22<42:58,  2.79it/s]

  4%|▍         | 294/7480 [01:22<42:58,  2.79it/s]
  4%|▍         | 295/7480 [01:22<42:57,  2.79it/s]
  4%|▍         | 296/7480 [01:22<42:57,  2.79it/s]
  4%|▍         | 297/7480 [01:22<42:57,  2.79it/s]

  4%|▍         | 298/7480 [01:24<41:55,  2.86it/s]

  4%|▍         | 298/7480 [01:24<41:55,  2.86it/s]
  4%|▍         | 299/7480 [01:24<41:55,  2.86it/s]

  4%|▍         | 300/7480 [01:24<42:37,  2.81it/s]

  4%|▍         | 300/7480 [01:24<42:37,  2.81it/s]
  4%|▍         | 301/7480 [01:24<42:36,  2.81it/s]
  4%|▍         | 302/7480 [01:24<42:36,  2.81it/s]

  4%|▍         | 303/7480 [01:25<38:45,  3.09it/s]

  4%|▍         | 303/7480 [01:25<38:45,  3.09it/s]
  4%|▍         | 304/7480 [01:25<38:44,  3.09it/s]

  4%|▍         | 305/7480 [01:26<39:59,  2.99it/s]

  4%|▍         | 305/7480 [01:26<39:59,  2.99it/s]
  4%|▍         | 306/7480 [01:26<39:58,  2.99it/s]

  4%|▍         | 307/7480 [01:27<41:07,  2.91it/s]

  4%|▍         | 307/7480 [01:27<41:07,  2.91it/s]
  4%|▍         | 308/7480 [01:27<41:06,  2.91it/s]
  4%|▍         | 309/7480 [01:27<41:06,  2.91it/s]
  4%|▍         | 310/7480 [01:27<41:06,  2.91it/s]
  4%|▍         | 311/7480 [01:27<41:05,  2.91it/s]
  4%|▍         | 312/7480 [01:27<41:05,  2.91it/s]
  4%|▍         | 313/7480 [01:27<41:04,  2.91it/s]
  4%|▍         | 314/7480 [01:27<41:04,  2.91it/s]
  4%|▍         | 315/7480 [01:27<41:04,  2.91it/s]

  4%|▍         | 316/7480 [01:27<22:04,  5.41it/s]

  4%|▍         | 316/7480 [01:27<22:04,  5.41it/s]
  4%|▍         | 317/7480 [01:27<22:04,  5.41it/s]

  4%|▍         | 318/7480 [01:28<25:18,  4.72it/s]

  4%|▍         | 318/7480 [01:28<25:18,  4.72it/s]
  4%|▍         | 319/7480 [01:28<25:17,  4.72it/s]

  4%|▍         | 320/7480 [01:29<29:27,  4.05it/s]

  4%|▍         | 320/7480 [01:29<29:27,  4.05it/s]
  4%|▍         | 321/7480 [01:29<29:27,  4.05it/s]

  4%|▍         | 322/7480 [01:30<32:37,  3.66it/s]

  4%|▍         | 322/7480 [01:30<32:37,  3.66it/s]
  4%|▍         | 323/7480 [01:30<32:37,  3.66it/s]
  4%|▍         | 324/7480 [01:30<32:36,  3.66it/s]

  4%|▍         | 325/7480 [01:30<31:28,  3.79it/s]
  4%|▍         | 329/7480 [01:30<20:52,  5.71it/s]

  4%|▍         | 325/7480 [01:30<31:28,  3.79it/s]
  4%|▍         | 326/7480 [01:30<31:28,  3.79it/s]
  4%|▍         | 327/7480 [01:30<31:27,  3.79it/s]
  4%|▍         | 328/7480 [01:30<31:27,  3.79it/s]
  4%|▍         | 329/7480 [01:30<20:52,  5.71it/s]
  4%|▍         | 330/7480 [01:30<20:52,  5.71it/s]
  4%|▍         | 331/7480 [01:31<20:51,  5.71it/s]
  4%|▍         | 332/7480 [01:31<20:51,  5.71it/s]
  4%|▍         | 333/7480 [01:31<20:51,  5.71it/s]
  4%|▍         | 334/7480 [01:31<20:51,  5.71it/s]

  4%|▍         | 335/7480 [01:31<12:34,  9.47it/s]

  4%|▍         | 335/7480 [01:31<12:34,  9.47it/s]
  4%|▍         | 336/7480 [01:31<12:34,  9.47it/s]
  5%|▍         | 337/7480 [01:31<12:33,  9.47it/s]
  5%|▍         | 338/7480 [01:31<12:33,  9.47it/s]
  5%|▍         | 339/7480 [01:31<12:33,  9.47it/s]
  5%|▍         | 340/7480 [01:31<12:33,  9.47it/s]
  5%|▍         | 341/7480 [01:31<12:33,  9.47it/s]

  5%|▍         | 342/7480 [01:31<13:27,  8.84it/s]

  5%|▍         | 342/7480 [01:31<13:27,  8.84it/s]
  5%|▍         | 343/7480 [01:31<13:27,  8.84it/s]

  5%|▍         | 345/7480 [01:32<16:44,  7.11it/s]

  5%|▍         | 344/7480 [01:32<13:27,  8.84it/s]
  5%|▍         | 345/7480 [01:32<16:44,  7.11it/s]

  5%|▍         | 347/7480 [01:33<21:34,  5.51it/s]

  5%|▍         | 346/7480 [01:33<16:43,  7.11it/s]
  5%|▍         | 347/7480 [01:33<21:34,  5.51it/s]

  5%|▍         | 349/7480 [01:36<51:47,  2.29it/s]

  5%|▍         | 348/7480 [01:36<21:34,  5.51it/s]
  5%|▍         | 349/7480 [01:36<51:47,  2.29it/s]
  5%|▍         | 350/7480 [01:36<51:47,  2.29it/s]
  5%|▍         | 351/7480 [01:36<51:46,  2.29it/s]

  5%|▍         | 352/7480 [01:37<45:56,  2.59it/s]

  5%|▍         | 352/7480 [01:37<45:56,  2.59it/s]
  5%|▍         | 353/7480 [01:37<45:56,  2.59it/s]
  5%|▍         | 354/7480 [01:37<45:55,  2.59it/s]
  5%|▍         | 355/7480 [01:37<45:55,  2.59it/s]

  5%|▍         | 356/7480 [01:38<37:48,  3.14it/s]

  5%|▍         | 356/7480 [01:38<37:48,  3.14it/s]
  5%|▍         | 357/7480 [01:38<37:47,  3.14it/s]

  5%|▍         | 358/7480 [01:38<39:13,  3.03it/s]

  5%|▍         | 358/7480 [01:38<39:13,  3.03it/s]
  5%|▍         | 359/7480 [01:38<39:13,  3.03it/s]
  5%|▍         | 360/7480 [01:38<39:13,  3.03it/s]
  5%|▍         | 361/7480 [01:38<39:12,  3.03it/s]
  5%|▍         | 362/7480 [01:38<39:12,  3.03it/s]
  5%|▍         | 363/7480 [01:38<39:12,  3.03it/s]

  5%|▍         | 364/7480 [01:39<27:58,  4.24it/s]
  5%|▍         | 369/7480 [01:39<18:51,  6.28it/s]

  5%|▍         | 364/7480 [01:39<27:58,  4.24it/s]
  5%|▍         | 365/7480 [01:39<27:58,  4.24it/s]
  5%|▍         | 366/7480 [01:39<27:58,  4.24it/s]
  5%|▍         | 367/7480 [01:39<27:58,  4.24it/s]
  5%|▍         | 368/7480 [01:39<27:57,  4.24it/s]
  5%|▍         | 369/7480 [01:39<18:51,  6.28it/s]
  5%|▍         | 370/7480 [01:39<18:51,  6.28it/s]

  5%|▍         | 371/7480 [01:40<23:29,  5.04it/s]

  5%|▍         | 371/7480 [01:40<23:29,  5.04it/s]
  5%|▍         | 372/7480 [01:40<23:29,  5.04it/s]

  5%|▍         | 373/7480 [01:41<27:16,  4.34it/s]

  5%|▍         | 373/7480 [01:41<27:16,  4.34it/s]
  5%|▌         | 374/7480 [01:41<27:16,  4.34it/s]

  5%|▌         | 375/7480 [01:41<31:00,  3.82it/s]

  5%|▌         | 375/7480 [01:41<31:00,  3.82it/s]
  5%|▌         | 376/7480 [01:41<31:00,  3.82it/s]
  5%|▌         | 377/7480 [01:41<30:59,  3.82it/s]

  5%|▌         | 378/7480 [01:42<30:32,  3.88it/s]

  5%|▌         | 378/7480 [01:42<30:32,  3.88it/s]
  5%|▌         | 379/7480 [01:42<30:32,  3.88it/s]

  5%|▌         | 380/7480 [01:43<32:39,  3.62it/s]

  5%|▌         | 380/7480 [01:43<32:39,  3.62it/s]
  5%|▌         | 381/7480 [01:43<32:39,  3.62it/s]

  5%|▌         | 382/7480 [01:44<35:07,  3.37it/s]

  5%|▌         | 382/7480 [01:44<35:07,  3.37it/s]
  5%|▌         | 383/7480 [01:44<35:06,  3.37it/s]

  5%|▌         | 384/7480 [01:44<37:14,  3.18it/s]

  5%|▌         | 384/7480 [01:44<37:14,  3.18it/s]
  5%|▌         | 385/7480 [01:44<37:14,  3.18it/s]
  5%|▌         | 386/7480 [01:44<37:14,  3.18it/s]
  5%|▌         | 387/7480 [01:44<37:13,  3.18it/s]
  5%|▌         | 388/7480 [01:44<37:13,  3.18it/s]
  5%|▌         | 389/7480 [01:44<37:13,  3.18it/s]
  5%|▌         | 390/7480 [01:44<37:12,  3.18it/s]

  5%|▌         | 391/7480 [01:45<23:09,  5.10it/s]

  5%|▌         | 391/7480 [01:45<23:09,  5.10it/s]
  5%|▌         | 392/7480 [01:45<23:08,  5.10it/s]
  5%|▌         | 393/7480 [01:45<23:08,  5.10it/s]
  5%|▌         | 394/7480 [01:45<23:08,  5.10it/s]
  5%|▌         | 395/7480 [01:45<23:08,  5.10it/s]
  5%|▌         | 396/7480 [01:45<23:08,  5.10it/s]
  5%|▌         | 397/7480 [01:45<23:07,  5.10it/s]

  5%|▌         | 398/7480 [01:46<17:49,  6.62it/s]
  5%|▌         | 404/7480 [01:46<12:12,  9.66it/s]

  5%|▌         | 398/7480 [01:46<17:49,  6.62it/s]
  5%|▌         | 399/7480 [01:46<17:49,  6.62it/s]
  5%|▌         | 400/7480 [01:46<17:49,  6.62it/s]
  5%|▌         | 401/7480 [01:46<17:49,  6.62it/s]
  5%|▌         | 402/7480 [01:46<17:49,  6.62it/s]
  5%|▌         | 403/7480 [01:46<17:48,  6.62it/s]
  5%|▌         | 404/7480 [01:46<12:12,  9.66it/s]
  5%|▌         | 405/7480 [01:46<12:12,  9.66it/s]

  5%|▌         | 407/7480 [01:49<33:56,  3.47it/s]

  5%|▌         | 406/7480 [01:49<12:12,  9.66it/s]
  5%|▌         | 407/7480 [01:49<33:56,  3.47it/s]
  5%|▌         | 408/7480 [01:49<33:56,  3.47it/s]
  5%|▌         | 409/7480 [01:49<33:56,  3.47it/s]
  5%|▌         | 410/7480 [01:49<33:55,  3.47it/s]

  5%|▌         | 411/7480 [01:50<29:55,  3.94it/s]

  5%|▌         | 411/7480 [01:50<29:55,  3.94it/s]
  6%|▌         | 412/7480 [01:50<29:55,  3.94it/s]

  6%|▌         | 413/7480 [01:50<31:19,  3.76it/s]
  6%|▌         | 418/7480 [01:50<20:43,  5.68it/s]

  6%|▌         | 413/7480 [01:50<31:19,  3.76it/s]
  6%|▌         | 414/7480 [01:50<31:19,  3.76it/s]
  6%|▌         | 415/7480 [01:50<31:19,  3.76it/s]
  6%|▌         | 416/7480 [01:50<31:18,  3.76it/s]
  6%|▌         | 417/7480 [01:50<31:18,  3.76it/s]
  6%|▌         | 418/7480 [01:50<20:43,  5.68it/s]
  6%|▌         | 419/7480 [01:50<20:43,  5.68it/s]
  6%|▌         | 420/7480 [01:50<20:43,  5.68it/s]

  6%|▌         | 421/7480 [01:51<22:14,  5.29it/s]

  6%|▌         | 421/7480 [01:51<22:14,  5.29it/s]
  6%|▌         | 422/7480 [01:51<22:14,  5.29it/s]

  6%|▌         | 423/7480 [01:52<25:17,  4.65it/s]

  6%|▌         | 423/7480 [01:52<25:17,  4.65it/s]
  6%|▌         | 424/7480 [01:52<25:17,  4.65it/s]

  6%|▌         | 425/7480 [01:52<28:03,  4.19it/s]

  6%|▌         | 425/7480 [01:52<28:03,  4.19it/s]
  6%|▌         | 426/7480 [01:52<28:03,  4.19it/s]
  6%|▌         | 427/7480 [01:52<28:03,  4.19it/s]

  6%|▌         | 428/7480 [01:53<27:49,  4.22it/s]

  6%|▌         | 428/7480 [01:53<27:49,  4.22it/s]
  6%|▌         | 429/7480 [01:53<27:49,  4.22it/s]

  6%|▌         | 430/7480 [01:54<30:56,  3.80it/s]

  6%|▌         | 430/7480 [01:54<30:56,  3.80it/s]
  6%|▌         | 431/7480 [01:54<30:56,  3.80it/s]

  6%|▌         | 432/7480 [01:54<33:16,  3.53it/s]

  6%|▌         | 432/7480 [01:54<33:16,  3.53it/s]
  6%|▌         | 433/7480 [01:54<33:16,  3.53it/s]

  6%|▌         | 434/7480 [01:55<35:18,  3.33it/s]

  6%|▌         | 434/7480 [01:55<35:18,  3.33it/s]
  6%|▌         | 435/7480 [01:55<35:17,  3.33it/s]

  6%|▌         | 436/7480 [01:56<36:54,  3.18it/s]

  6%|▌         | 436/7480 [01:56<36:54,  3.18it/s]
  6%|▌         | 437/7480 [01:56<36:54,  3.18it/s]

  6%|▌         | 438/7480 [01:56<37:06,  3.16it/s]
  6%|▌         | 443/7480 [01:57<20:02,  5.85it/s]

  6%|▌         | 438/7480 [01:56<37:06,  3.16it/s]
  6%|▌         | 439/7480 [01:56<37:05,  3.16it/s]
  6%|▌         | 440/7480 [01:57<37:05,  3.16it/s]
  6%|▌         | 441/7480 [01:57<37:05,  3.16it/s]
  6%|▌         | 442/7480 [01:57<37:04,  3.16it/s]
  6%|▌         | 443/7480 [01:57<20:02,  5.85it/s]
  6%|▌         | 444/7480 [01:57<20:02,  5.85it/s]

  6%|▌         | 445/7480 [01:57<24:16,  4.83it/s]

  6%|▌         | 445/7480 [01:57<24:16,  4.83it/s]
  6%|▌         | 446/7480 [01:57<24:15,  4.83it/s]

  6%|▌         | 447/7480 [01:58<28:10,  4.16it/s]

  6%|▌         | 447/7480 [01:58<28:10,  4.16it/s]
  6%|▌         | 448/7480 [01:58<28:10,  4.16it/s]

  6%|▌         | 449/7480 [01:59<32:52,  3.56it/s]

  6%|▌         | 449/7480 [01:59<32:52,  3.56it/s]
  6%|▌         | 450/7480 [01:59<32:52,  3.56it/s]

  6%|▌         | 451/7480 [02:02<1:08:05,  1.72it/s]

  6%|▌         | 451/7480 [02:02<1:08:05,  1.72it/s]
  6%|▌         | 452/7480 [02:02<1:08:05,  1.72it/s]

  6%|▌         | 453/7480 [02:02<1:00:41,  1.93it/s]

  6%|▌         | 453/7480 [02:02<1:00:41,  1.93it/s]
  6%|▌         | 454/7480 [02:02<1:00:40,  1.93it/s]
  6%|▌         | 455/7480 [02:02<1:00:40,  1.93it/s]

  6%|▌         | 456/7480 [02:03<47:39,  2.46it/s]

  6%|▌         | 456/7480 [02:03<47:39,  2.46it/s]
  6%|▌         | 457/7480 [02:03<47:38,  2.46it/s]

  6%|▌         | 458/7480 [02:04<46:13,  2.53it/s]
  6%|▌         | 465/7480 [02:04<21:06,  5.54it/s]

  6%|▌         | 458/7480 [02:04<46:13,  2.53it/s]
  6%|▌         | 459/7480 [02:04<46:13,  2.53it/s]
  6%|▌         | 460/7480 [02:04<46:12,  2.53it/s]
  6%|▌         | 461/7480 [02:04<46:12,  2.53it/s]
  6%|▌         | 462/7480 [02:04<46:11,  2.53it/s]
  6%|▌         | 463/7480 [02:04<46:11,  2.53it/s]
  6%|▌         | 464/7480 [02:04<46:11,  2.53it/s]
  6%|▌         | 465/7480 [02:04<21:06,  5.54it/s]
  6%|▌         | 466/7480 [02:04<21:05,  5.54it/s]

  6%|▋         | 468/7480 [02:04<22:35,  5.17it/s]

  6%|▌         | 467/7480 [02:04<21:05,  5.54it/s]
  6%|▋         | 468/7480 [02:04<22:35,  5.17it/s]

  6%|▋         | 470/7480 [02:05<25:46,  4.53it/s]

  6%|▋         | 469/7480 [02:05<22:35,  5.17it/s]
  6%|▋         | 470/7480 [02:05<25:46,  4.53it/s]

  6%|▋         | 472/7480 [02:06<28:44,  4.06it/s]

  6%|▋         | 471/7480 [02:06<25:46,  4.53it/s]
  6%|▋         | 472/7480 [02:06<28:44,  4.06it/s]

  6%|▋         | 473/7480 [02:06<35:44,  3.27it/s]

  6%|▋         | 473/7480 [02:06<35:44,  3.27it/s]
  6%|▋         | 474/7480 [02:07<35:44,  3.27it/s]

  6%|▋         | 475/7480 [02:07<36:33,  3.19it/s]

  6%|▋         | 475/7480 [02:07<36:33,  3.19it/s]
  6%|▋         | 476/7480 [02:07<36:33,  3.19it/s]

  6%|▋         | 477/7480 [02:08<37:27,  3.12it/s]

  6%|▋         | 477/7480 [02:08<37:27,  3.12it/s]
  6%|▋         | 478/7480 [02:08<37:27,  3.12it/s]

  6%|▋         | 479/7480 [02:09<38:35,  3.02it/s]

  6%|▋         | 479/7480 [02:09<38:35,  3.02it/s]
  6%|▋         | 480/7480 [02:09<38:35,  3.02it/s]

  6%|▋         | 481/7480 [02:09<38:59,  2.99it/s]

  6%|▋         | 481/7480 [02:09<38:59,  2.99it/s]
  6%|▋         | 482/7480 [02:09<38:58,  2.99it/s]

  6%|▋         | 483/7480 [02:10<40:07,  2.91it/s]

  6%|▋         | 483/7480 [02:10<40:07,  2.91it/s]
  6%|▋         | 484/7480 [02:10<40:07,  2.91it/s]

  6%|▋         | 485/7480 [02:11<40:09,  2.90it/s]

  6%|▋         | 485/7480 [02:11<40:09,  2.90it/s]
  6%|▋         | 486/7480 [02:11<40:08,  2.90it/s]

  7%|▋         | 487/7480 [02:11<40:53,  2.85it/s]

  7%|▋         | 487/7480 [02:11<40:53,  2.85it/s]
  7%|▋         | 488/7480 [02:11<40:53,  2.85it/s]

  7%|▋         | 489/7480 [02:14<1:18:05,  1.49it/s]

  7%|▋         | 489/7480 [02:14<1:18:05,  1.49it/s]
  7%|▋         | 490/7480 [02:14<1:18:04,  1.49it/s]

  7%|▋         | 491/7480 [02:15<1:06:55,  1.74it/s]

  7%|▋         | 491/7480 [02:15<1:06:55,  1.74it/s]
  7%|▋         | 492/7480 [02:15<1:06:54,  1.74it/s]

  7%|▋         | 493/7480 [02:16<58:34,  1.99it/s]

  7%|▋         | 493/7480 [02:16<58:34,  1.99it/s]
  7%|▋         | 494/7480 [02:16<58:34,  1.99it/s]

  7%|▋         | 495/7480 [02:16<53:07,  2.19it/s]

  7%|▋         | 495/7480 [02:16<53:07,  2.19it/s]
  7%|▋         | 496/7480 [02:16<53:06,  2.19it/s]

  7%|▋         | 497/7480 [02:17<49:08,  2.37it/s]

  7%|▋         | 497/7480 [02:17<49:08,  2.37it/s]
  7%|▋         | 498/7480 [02:17<49:08,  2.37it/s]

  7%|▋         | 499/7480 [02:18<47:06,  2.47it/s]

  7%|▋         | 499/7480 [02:18<47:06,  2.47it/s]
  7%|▋         | 500/7480 [02:18<47:06,  2.47it/s]
  7%|▋         | 501/7480 [02:18<47:06,  2.47it/s]

  7%|▋         | 502/7480 [02:18<39:01,  2.98it/s]

  7%|▋         | 502/7480 [02:18<39:01,  2.98it/s]
  7%|▋         | 503/7480 [02:18<39:01,  2.98it/s]

  7%|▋         | 504/7480 [02:19<39:21,  2.95it/s]

  7%|▋         | 504/7480 [02:19<39:21,  2.95it/s]
  7%|▋         | 505/7480 [02:19<39:21,  2.95it/s]

  7%|▋         | 506/7480 [02:20<39:02,  2.98it/s]
  7%|▋         | 514/7480 [02:20<16:00,  7.26it/s]

  7%|▋         | 506/7480 [02:20<39:02,  2.98it/s]
  7%|▋         | 507/7480 [02:20<39:02,  2.98it/s]
  7%|▋         | 508/7480 [02:20<39:01,  2.98it/s]
  7%|▋         | 509/7480 [02:20<39:01,  2.98it/s]
  7%|▋         | 510/7480 [02:20<39:01,  2.98it/s]
  7%|▋         | 511/7480 [02:20<39:00,  2.98it/s]
  7%|▋         | 512/7480 [02:20<39:00,  2.98it/s]
  7%|▋         | 513/7480 [02:20<39:00,  2.98it/s]
  7%|▋         | 514/7480 [02:20<16:00,  7.26it/s]
  7%|▋         | 515/7480 [02:20<15:59,  7.26it/s]
  7%|▋         | 516/7480 [02:20<15:59,  7.26it/s]
  7%|▋         | 517/7480 [02:20<15:59,  7.26it/s]

  7%|▋         | 518/7480 [02:21<17:20,  6.69it/s]

  7%|▋         | 518/7480 [02:21<17:20,  6.69it/s]
  7%|▋         | 519/7480 [02:21<17:20,  6.69it/s]

  7%|▋         | 520/7480 [02:21<21:10,  5.48it/s]

  7%|▋         | 520/7480 [02:21<21:10,  5.48it/s]
  7%|▋         | 521/7480 [02:21<21:09,  5.48it/s]

  7%|▋         | 522/7480 [02:22<24:27,  4.74it/s]

  7%|▋         | 522/7480 [02:22<24:27,  4.74it/s]
  7%|▋         | 523/7480 [02:22<24:27,  4.74it/s]

  7%|▋         | 524/7480 [02:23<27:38,  4.20it/s]

  7%|▋         | 524/7480 [02:23<27:38,  4.20it/s]
  7%|▋         | 525/7480 [02:23<27:37,  4.20it/s]

  7%|▋         | 526/7480 [02:23<30:12,  3.84it/s]

  7%|▋         | 526/7480 [02:23<30:12,  3.84it/s]
  7%|▋         | 527/7480 [02:23<30:12,  3.84it/s]

  7%|▋         | 528/7480 [02:24<32:46,  3.54it/s]

  7%|▋         | 528/7480 [02:24<32:46,  3.54it/s]
  7%|▋         | 529/7480 [02:24<32:46,  3.54it/s]

  7%|▋         | 530/7480 [02:27<1:09:58,  1.66it/s]

  7%|▋         | 530/7480 [02:27<1:09:58,  1.66it/s]
  7%|▋         | 531/7480 [02:27<1:09:57,  1.66it/s]

  7%|▋         | 532/7480 [02:28<1:02:21,  1.86it/s]

  7%|▋         | 532/7480 [02:28<1:02:21,  1.86it/s]
  7%|▋         | 533/7480 [02:28<1:02:21,  1.86it/s]

  7%|▋         | 534/7480 [02:28<56:16,  2.06it/s]

  7%|▋         | 534/7480 [02:28<56:16,  2.06it/s]
  7%|▋         | 535/7480 [02:28<56:15,  2.06it/s]

  7%|▋         | 536/7480 [02:29<52:03,  2.22it/s]

  7%|▋         | 536/7480 [02:29<52:03,  2.22it/s]
  7%|▋         | 537/7480 [02:29<52:02,  2.22it/s]

  7%|▋         | 538/7480 [02:30<49:22,  2.34it/s]

  7%|▋         | 538/7480 [02:30<49:22,  2.34it/s]
  7%|▋         | 539/7480 [02:30<49:21,  2.34it/s]

  7%|▋         | 540/7480 [02:30<46:54,  2.47it/s]

  7%|▋         | 540/7480 [02:30<46:54,  2.47it/s]
  7%|▋         | 541/7480 [02:30<46:54,  2.47it/s]

  7%|▋         | 542/7480 [02:31<45:08,  2.56it/s]

  7%|▋         | 542/7480 [02:31<45:08,  2.56it/s]
  7%|▋         | 543/7480 [02:31<45:07,  2.56it/s]

  7%|▋         | 544/7480 [02:32<44:12,  2.61it/s]

  7%|▋         | 544/7480 [02:32<44:12,  2.61it/s]
  7%|▋         | 545/7480 [02:32<44:12,  2.61it/s]

  7%|▋         | 546/7480 [02:33<42:57,  2.69it/s]

  7%|▋         | 546/7480 [02:33<42:57,  2.69it/s]
  7%|▋         | 547/7480 [02:33<42:56,  2.69it/s]

  7%|▋         | 548/7480 [02:33<42:22,  2.73it/s]

  7%|▋         | 548/7480 [02:33<42:22,  2.73it/s]
  7%|▋         | 549/7480 [02:33<42:22,  2.73it/s]

  7%|▋         | 550/7480 [02:34<41:46,  2.77it/s]

  7%|▋         | 550/7480 [02:34<41:46,  2.77it/s]
  7%|▋         | 551/7480 [02:34<41:45,  2.77it/s]

  7%|▋         | 552/7480 [02:35<40:39,  2.84it/s]

  7%|▋         | 552/7480 [02:35<40:39,  2.84it/s]
  7%|▋         | 553/7480 [02:35<40:39,  2.84it/s]
  7%|▋         | 554/7480 [02:35<40:38,  2.84it/s]

  7%|▋         | 555/7480 [02:35<35:39,  3.24it/s]

  7%|▋         | 555/7480 [02:35<35:39,  3.24it/s]
  7%|▋         | 556/7480 [02:35<35:39,  3.24it/s]

  7%|▋         | 557/7480 [02:36<36:50,  3.13it/s]

  7%|▋         | 557/7480 [02:36<36:50,  3.13it/s]
  7%|▋         | 558/7480 [02:36<36:49,  3.13it/s]

  7%|▋         | 559/7480 [02:37<39:16,  2.94it/s]

  7%|▋         | 559/7480 [02:37<39:16,  2.94it/s]
  7%|▋         | 560/7480 [02:37<39:16,  2.94it/s]

  8%|▊         | 561/7480 [02:40<1:14:18,  1.55it/s]

  8%|▊         | 561/7480 [02:40<1:14:18,  1.55it/s]
  8%|▊         | 562/7480 [02:40<1:14:17,  1.55it/s]
  8%|▊         | 563/7480 [02:40<1:14:17,  1.55it/s]
  8%|▊         | 564/7480 [02:40<1:14:16,  1.55it/s]

  8%|▊         | 565/7480 [02:40<50:22,  2.29it/s]

  8%|▊         | 565/7480 [02:40<50:22,  2.29it/s]
  8%|▊         | 566/7480 [02:40<50:21,  2.29it/s]

  8%|▊         | 567/7480 [02:41<48:12,  2.39it/s]

  8%|▊         | 567/7480 [02:41<48:12,  2.39it/s]
  8%|▊         | 568/7480 [02:41<48:12,  2.39it/s]
  8%|▊         | 569/7480 [02:41<48:11,  2.39it/s]
  8%|▊         | 570/7480 [02:41<48:11,  2.39it/s]

  8%|▊         | 571/7480 [02:42<37:06,  3.10it/s]

  8%|▊         | 571/7480 [02:42<37:06,  3.10it/s]
  8%|▊         | 572/7480 [02:42<37:06,  3.10it/s]

  8%|▊         | 573/7480 [02:43<38:16,  3.01it/s]

  8%|▊         | 573/7480 [02:43<38:16,  3.01it/s]
  8%|▊         | 574/7480 [02:43<38:15,  3.01it/s]
  8%|▊         | 575/7480 [02:43<38:15,  3.01it/s]
  8%|▊         | 576/7480 [02:43<38:15,  3.01it/s]
  8%|▊         | 577/7480 [02:43<38:14,  3.01it/s]
  8%|▊         | 578/7480 [02:43<38:14,  3.01it/s]
  8%|▊         | 579/7480 [02:43<38:14,  3.01it/s]
  8%|▊         | 580/7480 [02:43<38:13,  3.01it/s]

  8%|▊         | 581/7480 [02:43<22:20,  5.15it/s]

  8%|▊         | 581/7480 [02:43<22:20,  5.15it/s]
  8%|▊         | 582/7480 [02:43<22:20,  5.15it/s]

  8%|▊         | 583/7480 [02:44<25:25,  4.52it/s]

  8%|▊         | 583/7480 [02:44<25:25,  4.52it/s]
  8%|▊         | 584/7480 [02:44<25:24,  4.52it/s]

  8%|▊         | 585/7480 [02:45<28:41,  4.01it/s]

  8%|▊         | 585/7480 [02:45<28:41,  4.01it/s]
  8%|▊         | 586/7480 [02:45<28:40,  4.01it/s]

  8%|▊         | 587/7480 [02:45<31:34,  3.64it/s]

  8%|▊         | 587/7480 [02:45<31:34,  3.64it/s]
  8%|▊         | 588/7480 [02:45<31:34,  3.64it/s]

  8%|▊         | 589/7480 [02:46<33:40,  3.41it/s]

  8%|▊         | 589/7480 [02:46<33:40,  3.41it/s]
  8%|▊         | 590/7480 [02:46<33:39,  3.41it/s]

  8%|▊         | 591/7480 [02:47<36:02,  3.19it/s]

  8%|▊         | 591/7480 [02:47<36:02,  3.19it/s]
  8%|▊         | 592/7480 [02:47<36:02,  3.19it/s]

  8%|▊         | 593/7480 [02:48<38:18,  3.00it/s]

  8%|▊         | 593/7480 [02:48<38:18,  3.00it/s]
  8%|▊         | 594/7480 [02:48<38:17,  3.00it/s]

  8%|▊         | 595/7480 [02:48<38:53,  2.95it/s]

  8%|▊         | 595/7480 [02:48<38:53,  2.95it/s]
  8%|▊         | 596/7480 [02:48<38:53,  2.95it/s]
  8%|▊         | 597/7480 [02:48<38:53,  2.95it/s]
  8%|▊         | 598/7480 [02:48<38:52,  2.95it/s]

  8%|▊         | 599/7480 [02:49<31:02,  3.69it/s]

  8%|▊         | 599/7480 [02:49<31:02,  3.69it/s]
  8%|▊         | 600/7480 [02:49<31:02,  3.69it/s]

  8%|▊         | 601/7480 [02:52<1:05:04,  1.76it/s]

  8%|▊         | 601/7480 [02:52<1:05:04,  1.76it/s]
  8%|▊         | 602/7480 [02:52<1:05:03,  1.76it/s]

  8%|▊         | 603/7480 [02:53<58:56,  1.94it/s]

  8%|▊         | 603/7480 [02:53<58:56,  1.94it/s]
  8%|▊         | 604/7480 [02:53<58:55,  1.94it/s]

  8%|▊         | 605/7480 [02:54<54:33,  2.10it/s]

  8%|▊         | 605/7480 [02:54<54:33,  2.10it/s]
  8%|▊         | 606/7480 [02:54<54:33,  2.10it/s]

  8%|▊         | 607/7480 [02:54<51:17,  2.23it/s]

  8%|▊         | 607/7480 [02:54<51:17,  2.23it/s]
  8%|▊         | 608/7480 [02:54<51:16,  2.23it/s]

  8%|▊         | 609/7480 [02:55<48:48,  2.35it/s]

  8%|▊         | 609/7480 [02:55<48:48,  2.35it/s]
  8%|▊         | 610/7480 [02:55<48:47,  2.35it/s]
  8%|▊         | 611/7480 [02:55<48:47,  2.35it/s]

  8%|▊         | 612/7480 [02:56<40:33,  2.82it/s]

  8%|▊         | 612/7480 [02:56<40:33,  2.82it/s]
  8%|▊         | 613/7480 [02:56<40:33,  2.82it/s]

  8%|▊         | 614/7480 [02:57<41:38,  2.75it/s]
  8%|▊         | 618/7480 [02:57<25:01,  4.57it/s]

  8%|▊         | 614/7480 [02:57<41:38,  2.75it/s]
  8%|▊         | 615/7480 [02:57<41:38,  2.75it/s]
  8%|▊         | 616/7480 [02:57<41:37,  2.75it/s]
  8%|▊         | 617/7480 [02:57<41:37,  2.75it/s]
  8%|▊         | 618/7480 [02:57<25:01,  4.57it/s]
  8%|▊         | 619/7480 [02:57<25:01,  4.57it/s]

  8%|▊         | 620/7480 [02:57<29:22,  3.89it/s]

  8%|▊         | 620/7480 [02:57<29:22,  3.89it/s]
  8%|▊         | 621/7480 [02:57<29:21,  3.89it/s]

  8%|▊         | 622/7480 [02:58<32:34,  3.51it/s]

  8%|▊         | 622/7480 [02:58<32:34,  3.51it/s]
  8%|▊         | 623/7480 [02:58<32:34,  3.51it/s]
  8%|▊         | 624/7480 [02:58<32:34,  3.51it/s]

  8%|▊         | 625/7480 [02:59<30:28,  3.75it/s]

  8%|▊         | 625/7480 [02:59<30:28,  3.75it/s]
  8%|▊         | 626/7480 [02:59<30:28,  3.75it/s]
  8%|▊         | 627/7480 [02:59<30:28,  3.75it/s]
  8%|▊         | 628/7480 [02:59<30:27,  3.75it/s]
  8%|▊         | 629/7480 [02:59<30:27,  3.75it/s]
  8%|▊         | 630/7480 [02:59<30:27,  3.75it/s]

  8%|▊         | 631/7480 [03:00<22:04,  5.17it/s]

  8%|▊         | 631/7480 [03:00<22:04,  5.17it/s]
  8%|▊         | 632/7480 [03:00<22:03,  5.17it/s]

  8%|▊         | 633/7480 [03:00<25:44,  4.43it/s]

  8%|▊         | 633/7480 [03:00<25:44,  4.43it/s]
  8%|▊         | 634/7480 [03:00<25:44,  4.43it/s]
  8%|▊         | 635/7480 [03:00<25:43,  4.43it/s]
  9%|▊         | 636/7480 [03:00<25:43,  4.43it/s]

  9%|▊         | 637/7480 [03:01<23:32,  4.84it/s]

  9%|▊         | 637/7480 [03:01<23:32,  4.84it/s]
  9%|▊         | 638/7480 [03:01<23:32,  4.84it/s]

  9%|▊         | 639/7480 [03:02<27:06,  4.21it/s]

  9%|▊         | 639/7480 [03:02<27:06,  4.21it/s]
  9%|▊         | 640/7480 [03:02<27:06,  4.21it/s]
  9%|▊         | 641/7480 [03:02<27:06,  4.21it/s]
  9%|▊         | 642/7480 [03:02<27:05,  4.21it/s]
  9%|▊         | 643/7480 [03:02<27:05,  4.21it/s]

  9%|▊         | 644/7480 [03:05<45:03,  2.53it/s]

  9%|▊         | 644/7480 [03:05<45:03,  2.53it/s]
  9%|▊         | 645/7480 [03:05<45:03,  2.53it/s]
  9%|▊         | 646/7480 [03:05<45:02,  2.53it/s]

  9%|▊         | 647/7480 [03:06<40:38,  2.80it/s]

  9%|▊         | 647/7480 [03:06<40:38,  2.80it/s]
  9%|▊         | 648/7480 [03:06<40:37,  2.80it/s]
  9%|▊         | 649/7480 [03:06<40:37,  2.80it/s]

  9%|▊         | 650/7480 [03:06<36:50,  3.09it/s]

  9%|▊         | 650/7480 [03:06<36:50,  3.09it/s]
  9%|▊         | 651/7480 [03:06<36:50,  3.09it/s]

  9%|▊         | 652/7480 [03:07<38:29,  2.96it/s]

  9%|▊         | 652/7480 [03:07<38:29,  2.96it/s]
  9%|▊         | 653/7480 [03:07<38:29,  2.96it/s]

  9%|▊         | 654/7480 [03:08<39:20,  2.89it/s]

  9%|▊         | 654/7480 [03:08<39:20,  2.89it/s]
  9%|▉         | 655/7480 [03:08<39:19,  2.89it/s]
  9%|▉         | 656/7480 [03:08<39:19,  2.89it/s]
  9%|▉         | 657/7480 [03:08<39:19,  2.89it/s]
  9%|▉         | 658/7480 [03:08<39:18,  2.89it/s]
  9%|▉         | 659/7480 [03:08<39:18,  2.89it/s]

  9%|▉         | 660/7480 [03:09<26:56,  4.22it/s]

  9%|▉         | 660/7480 [03:09<26:56,  4.22it/s]
  9%|▉         | 661/7480 [03:09<26:56,  4.22it/s]

  9%|▉         | 662/7480 [03:09<29:56,  3.80it/s]

  9%|▉         | 662/7480 [03:09<29:56,  3.80it/s]
  9%|▉         | 663/7480 [03:09<29:56,  3.80it/s]

  9%|▉         | 664/7480 [03:10<33:02,  3.44it/s]

  9%|▉         | 664/7480 [03:10<33:02,  3.44it/s]
  9%|▉         | 665/7480 [03:10<33:02,  3.44it/s]

  9%|▉         | 666/7480 [03:11<35:18,  3.22it/s]

  9%|▉         | 666/7480 [03:11<35:18,  3.22it/s]
  9%|▉         | 667/7480 [03:11<35:18,  3.22it/s]

  9%|▉         | 668/7480 [03:12<36:22,  3.12it/s]

  9%|▉         | 668/7480 [03:12<36:22,  3.12it/s]
  9%|▉         | 669/7480 [03:12<36:22,  3.12it/s]

  9%|▉         | 670/7480 [03:12<38:14,  2.97it/s]

  9%|▉         | 670/7480 [03:12<38:14,  2.97it/s]
  9%|▉         | 671/7480 [03:12<38:14,  2.97it/s]

  9%|▉         | 672/7480 [03:13<39:19,  2.89it/s]

  9%|▉         | 672/7480 [03:13<39:19,  2.89it/s]
  9%|▉         | 673/7480 [03:13<39:19,  2.89it/s]

  9%|▉         | 674/7480 [03:14<40:24,  2.81it/s]

  9%|▉         | 674/7480 [03:14<40:24,  2.81it/s]
  9%|▉         | 675/7480 [03:14<40:23,  2.81it/s]
  9%|▉         | 676/7480 [03:14<40:23,  2.81it/s]

  9%|▉         | 677/7480 [03:15<35:35,  3.18it/s]

  9%|▉         | 677/7480 [03:15<35:35,  3.18it/s]
  9%|▉         | 678/7480 [03:15<35:35,  3.18it/s]

  9%|▉         | 679/7480 [03:18<1:10:47,  1.60it/s]

  9%|▉         | 679/7480 [03:18<1:10:47,  1.60it/s]
  9%|▉         | 680/7480 [03:18<1:10:46,  1.60it/s]

  9%|▉         | 681/7480 [03:18<1:02:59,  1.80it/s]

  9%|▉         | 681/7480 [03:18<1:02:59,  1.80it/s]
  9%|▉         | 682/7480 [03:18<1:02:58,  1.80it/s]
  9%|▉         | 683/7480 [03:18<1:02:58,  1.80it/s]

  9%|▉         | 684/7480 [03:19<48:58,  2.31it/s]

  9%|▉         | 684/7480 [03:19<48:58,  2.31it/s]
  9%|▉         | 685/7480 [03:19<48:57,  2.31it/s]

  9%|▉         | 686/7480 [03:20<46:25,  2.44it/s]

  9%|▉         | 686/7480 [03:20<46:25,  2.44it/s]
  9%|▉         | 687/7480 [03:20<46:25,  2.44it/s]
  9%|▉         | 688/7480 [03:20<46:24,  2.44it/s]

  9%|▉         | 689/7480 [03:20<39:18,  2.88it/s]

  9%|▉         | 689/7480 [03:20<39:18,  2.88it/s]
  9%|▉         | 690/7480 [03:20<39:18,  2.88it/s]

  9%|▉         | 691/7480 [03:21<39:08,  2.89it/s]

  9%|▉         | 691/7480 [03:21<39:08,  2.89it/s]
  9%|▉         | 692/7480 [03:21<39:08,  2.89it/s]

  9%|▉         | 693/7480 [03:22<39:18,  2.88it/s]

  9%|▉         | 693/7480 [03:22<39:18,  2.88it/s]
  9%|▉         | 694/7480 [03:22<39:18,  2.88it/s]

  9%|▉         | 695/7480 [03:22<39:30,  2.86it/s]

  9%|▉         | 695/7480 [03:22<39:30,  2.86it/s]
  9%|▉         | 696/7480 [03:22<39:30,  2.86it/s]

  9%|▉         | 697/7480 [03:23<39:36,  2.85it/s]

  9%|▉         | 697/7480 [03:23<39:36,  2.85it/s]
  9%|▉         | 698/7480 [03:23<39:35,  2.85it/s]

  9%|▉         | 699/7480 [03:24<39:33,  2.86it/s]

  9%|▉         | 699/7480 [03:24<39:33,  2.86it/s]
  9%|▉         | 700/7480 [03:24<39:32,  2.86it/s]
  9%|▉         | 701/7480 [03:24<39:32,  2.86it/s]

  9%|▉         | 702/7480 [03:25<34:18,  3.29it/s]

  9%|▉         | 702/7480 [03:25<34:18,  3.29it/s]
  9%|▉         | 703/7480 [03:25<34:17,  3.29it/s]

  9%|▉         | 704/7480 [03:25<34:58,  3.23it/s]

  9%|▉         | 704/7480 [03:25<34:58,  3.23it/s]
  9%|▉         | 705/7480 [03:25<34:57,  3.23it/s]

  9%|▉         | 706/7480 [03:26<36:20,  3.11it/s]

  9%|▉         | 706/7480 [03:26<36:20,  3.11it/s]
  9%|▉         | 707/7480 [03:26<36:20,  3.11it/s]

  9%|▉         | 708/7480 [03:27<36:48,  3.07it/s]

  9%|▉         | 708/7480 [03:27<36:48,  3.07it/s]
  9%|▉         | 709/7480 [03:27<36:48,  3.07it/s]

  9%|▉         | 710/7480 [03:27<37:09,  3.04it/s]

  9%|▉         | 710/7480 [03:27<37:09,  3.04it/s]
 10%|▉         | 711/7480 [03:27<37:09,  3.04it/s]

 10%|▉         | 712/7480 [03:30<1:14:31,  1.51it/s]

 10%|▉         | 712/7480 [03:30<1:14:31,  1.51it/s]
 10%|▉         | 713/7480 [03:30<1:14:31,  1.51it/s]

 10%|▉         | 714/7480 [03:31<1:04:28,  1.75it/s]

 10%|▉         | 714/7480 [03:31<1:04:28,  1.75it/s]
 10%|▉         | 715/7480 [03:31<1:04:28,  1.75it/s]

 10%|▉         | 716/7480 [03:32<57:16,  1.97it/s]

 10%|▉         | 716/7480 [03:32<57:16,  1.97it/s]
 10%|▉         | 717/7480 [03:32<57:16,  1.97it/s]

 10%|▉         | 718/7480 [03:32<52:35,  2.14it/s]

 10%|▉         | 718/7480 [03:32<52:35,  2.14it/s]
 10%|▉         | 719/7480 [03:32<52:35,  2.14it/s]

 10%|▉         | 720/7480 [03:33<49:33,  2.27it/s]

 10%|▉         | 720/7480 [03:33<49:33,  2.27it/s]
 10%|▉         | 721/7480 [03:33<49:32,  2.27it/s]

 10%|▉         | 722/7480 [03:34<46:17,  2.43it/s]

 10%|▉         | 722/7480 [03:34<46:17,  2.43it/s]
 10%|▉         | 723/7480 [03:34<46:17,  2.43it/s]

 10%|▉         | 724/7480 [03:35<44:31,  2.53it/s]

 10%|▉         | 724/7480 [03:35<44:31,  2.53it/s]
 10%|▉         | 725/7480 [03:35<44:31,  2.53it/s]

 10%|▉         | 726/7480 [03:35<43:09,  2.61it/s]

 10%|▉         | 726/7480 [03:35<43:09,  2.61it/s]
 10%|▉         | 727/7480 [03:35<43:09,  2.61it/s]

 10%|▉         | 728/7480 [03:36<41:54,  2.69it/s]

 10%|▉         | 728/7480 [03:36<41:54,  2.69it/s]
 10%|▉         | 729/7480 [03:36<41:54,  2.69it/s]

 10%|▉         | 730/7480 [03:37<41:37,  2.70it/s]

 10%|▉         | 730/7480 [03:37<41:37,  2.70it/s]
 10%|▉         | 731/7480 [03:37<41:37,  2.70it/s]

 10%|▉         | 732/7480 [03:37<42:59,  2.62it/s]

 10%|▉         | 732/7480 [03:37<42:59,  2.62it/s]
 10%|▉         | 733/7480 [03:37<42:59,  2.62it/s]
 10%|▉         | 734/7480 [03:38<42:59,  2.62it/s]
 10%|▉         | 735/7480 [03:38<42:58,  2.62it/s]

 10%|▉         | 736/7480 [03:38<32:41,  3.44it/s]

 10%|▉         | 736/7480 [03:38<32:41,  3.44it/s]
 10%|▉         | 737/7480 [03:38<32:41,  3.44it/s]
 10%|▉         | 738/7480 [03:38<32:40,  3.44it/s]

 10%|▉         | 739/7480 [03:39<30:20,  3.70it/s]

 10%|▉         | 739/7480 [03:39<30:20,  3.70it/s]
 10%|▉         | 740/7480 [03:39<30:20,  3.70it/s]
 10%|▉         | 741/7480 [03:39<30:19,  3.70it/s]

 10%|▉         | 742/7480 [03:40<29:44,  3.78it/s]

 10%|▉         | 742/7480 [03:40<29:44,  3.78it/s]
 10%|▉         | 743/7480 [03:40<29:43,  3.78it/s]

 10%|▉         | 744/7480 [03:43<1:02:50,  1.79it/s]

 10%|▉         | 744/7480 [03:43<1:02:50,  1.79it/s]
 10%|▉         | 745/7480 [03:43<1:02:49,  1.79it/s]
 10%|▉         | 746/7480 [03:43<1:02:49,  1.79it/s]

 10%|▉         | 747/7480 [03:43<50:49,  2.21it/s]

 10%|▉         | 747/7480 [03:43<50:49,  2.21it/s]
 10%|█         | 748/7480 [03:43<50:48,  2.21it/s]

 10%|█         | 749/7480 [03:44<48:40,  2.30it/s]

 10%|█         | 749/7480 [03:44<48:40,  2.30it/s]
 10%|█         | 750/7480 [03:44<48:39,  2.30it/s]

 10%|█         | 751/7480 [03:45<46:33,  2.41it/s]

 10%|█         | 751/7480 [03:45<46:33,  2.41it/s]
 10%|█         | 752/7480 [03:45<46:33,  2.41it/s]

 10%|█         | 753/7480 [03:46<44:53,  2.50it/s]

 10%|█         | 753/7480 [03:46<44:53,  2.50it/s]
 10%|█         | 754/7480 [03:46<44:52,  2.50it/s]

 10%|█         | 755/7480 [03:46<43:26,  2.58it/s]

 10%|█         | 755/7480 [03:46<43:26,  2.58it/s]
 10%|█         | 756/7480 [03:46<43:26,  2.58it/s]

 10%|█         | 757/7480 [03:47<43:15,  2.59it/s]

 10%|█         | 757/7480 [03:47<43:15,  2.59it/s]
 10%|█         | 758/7480 [03:47<43:15,  2.59it/s]

 10%|█         | 759/7480 [03:48<42:59,  2.61it/s]
 10%|█         | 764/7480 [03:48<22:29,  4.98it/s]

 10%|█         | 759/7480 [03:48<42:59,  2.61it/s]
 10%|█         | 760/7480 [03:48<42:58,  2.61it/s]
 10%|█         | 761/7480 [03:48<42:58,  2.61it/s]
 10%|█         | 762/7480 [03:48<42:57,  2.61it/s]
 10%|█         | 763/7480 [03:48<42:57,  2.61it/s]
 10%|█         | 764/7480 [03:48<22:29,  4.98it/s]
 10%|█         | 765/7480 [03:48<22:29,  4.98it/s]

 10%|█         | 766/7480 [03:49<26:57,  4.15it/s]

 10%|█         | 766/7480 [03:49<26:57,  4.15it/s]
 10%|█         | 767/7480 [03:49<26:56,  4.15it/s]
 10%|█         | 768/7480 [03:49<26:56,  4.15it/s]
 10%|█         | 769/7480 [03:49<26:56,  4.15it/s]

 10%|█         | 770/7480 [03:49<24:32,  4.56it/s]

 10%|█         | 770/7480 [03:49<24:32,  4.56it/s]
 10%|█         | 771/7480 [03:49<24:32,  4.56it/s]

 10%|█         | 772/7480 [03:50<28:28,  3.93it/s]

 10%|█         | 772/7480 [03:50<28:28,  3.93it/s]
 10%|█         | 773/7480 [03:50<28:28,  3.93it/s]

 10%|█         | 774/7480 [03:51<32:14,  3.47it/s]

 10%|█         | 774/7480 [03:51<32:14,  3.47it/s]
 10%|█         | 775/7480 [03:51<32:14,  3.47it/s]

 10%|█         | 776/7480 [03:52<34:16,  3.26it/s]

 10%|█         | 776/7480 [03:52<34:16,  3.26it/s]
 10%|█         | 777/7480 [03:52<34:16,  3.26it/s]
 10%|█         | 778/7480 [03:52<34:15,  3.26it/s]

 10%|█         | 779/7480 [03:52<32:23,  3.45it/s]

 10%|█         | 779/7480 [03:53<32:23,  3.45it/s]
 10%|█         | 780/7480 [03:53<32:23,  3.45it/s]

 10%|█         | 781/7480 [03:56<1:06:46,  1.67it/s]

 10%|█         | 781/7480 [03:56<1:06:46,  1.67it/s]
 10%|█         | 782/7480 [03:56<1:06:45,  1.67it/s]
 10%|█         | 783/7480 [03:56<1:06:45,  1.67it/s]

 10%|█         | 784/7480 [03:56<53:24,  2.09it/s]

 10%|█         | 784/7480 [03:56<53:24,  2.09it/s]
 10%|█         | 785/7480 [03:56<53:23,  2.09it/s]

 11%|█         | 786/7480 [03:57<50:22,  2.21it/s]

 11%|█         | 786/7480 [03:57<50:22,  2.21it/s]
 11%|█         | 787/7480 [03:57<50:22,  2.21it/s]

 11%|█         | 788/7480 [03:58<48:17,  2.31it/s]

 11%|█         | 788/7480 [03:58<48:17,  2.31it/s]
 11%|█         | 789/7480 [03:58<48:17,  2.31it/s]

 11%|█         | 790/7480 [03:59<46:58,  2.37it/s]

 11%|█         | 790/7480 [03:59<46:58,  2.37it/s]
 11%|█         | 791/7480 [03:59<46:58,  2.37it/s]

 11%|█         | 792/7480 [03:59<46:23,  2.40it/s]

 11%|█         | 792/7480 [03:59<46:23,  2.40it/s]
 11%|█         | 793/7480 [03:59<46:22,  2.40it/s]
 11%|█         | 794/7480 [03:59<46:22,  2.40it/s]
 11%|█         | 795/7480 [03:59<46:21,  2.40it/s]

 11%|█         | 796/7480 [04:00<35:04,  3.18it/s]

 11%|█         | 796/7480 [04:00<35:04,  3.18it/s]
 11%|█         | 797/7480 [04:00<35:04,  3.18it/s]

 11%|█         | 798/7480 [04:01<36:59,  3.01it/s]

 11%|█         | 798/7480 [04:01<36:59,  3.01it/s]
 11%|█         | 799/7480 [04:01<36:59,  3.01it/s]
 11%|█         | 800/7480 [04:01<36:59,  3.01it/s]
 11%|█         | 801/7480 [04:01<36:58,  3.01it/s]
 11%|█         | 802/7480 [04:01<36:58,  3.01it/s]
 11%|█         | 803/7480 [04:01<36:58,  3.01it/s]

 11%|█         | 804/7480 [04:02<25:45,  4.32it/s]

 11%|█         | 804/7480 [04:02<25:45,  4.32it/s]
 11%|█         | 805/7480 [04:02<25:45,  4.32it/s]
 11%|█         | 806/7480 [04:02<25:45,  4.32it/s]

 11%|█         | 807/7480 [04:03<27:14,  4.08it/s]

 11%|█         | 807/7480 [04:03<27:14,  4.08it/s]
 11%|█         | 808/7480 [04:03<27:14,  4.08it/s]

 11%|█         | 809/7480 [04:03<30:46,  3.61it/s]

 11%|█         | 809/7480 [04:03<30:46,  3.61it/s]
 11%|█         | 810/7480 [04:03<30:46,  3.61it/s]

 11%|█         | 811/7480 [04:04<34:05,  3.26it/s]

 11%|█         | 811/7480 [04:04<34:05,  3.26it/s]
 11%|█         | 812/7480 [04:04<34:04,  3.26it/s]

 11%|█         | 813/7480 [04:05<36:32,  3.04it/s]

 11%|█         | 813/7480 [04:05<36:32,  3.04it/s]
 11%|█         | 814/7480 [04:05<36:32,  3.04it/s]

 11%|█         | 815/7480 [04:08<1:11:28,  1.55it/s]

 11%|█         | 815/7480 [04:08<1:11:28,  1.55it/s]
 11%|█         | 816/7480 [04:08<1:11:28,  1.55it/s]

 11%|█         | 817/7480 [04:09<1:04:24,  1.72it/s]

 11%|█         | 817/7480 [04:09<1:04:24,  1.72it/s]
 11%|█         | 818/7480 [04:09<1:04:23,  1.72it/s]

 11%|█         | 819/7480 [04:10<58:11,  1.91it/s]

 11%|█         | 819/7480 [04:10<58:11,  1.91it/s]
 11%|█         | 820/7480 [04:10<58:10,  1.91it/s]

 11%|█         | 821/7480 [04:10<54:32,  2.03it/s]

 11%|█         | 821/7480 [04:10<54:32,  2.03it/s]
 11%|█         | 822/7480 [04:10<54:31,  2.03it/s]

 11%|█         | 823/7480 [04:11<51:50,  2.14it/s]

 11%|█         | 823/7480 [04:11<51:50,  2.14it/s]
 11%|█         | 824/7480 [04:11<51:50,  2.14it/s]

 11%|█         | 825/7480 [04:12<49:29,  2.24it/s]

 11%|█         | 825/7480 [04:12<49:29,  2.24it/s]
 11%|█         | 826/7480 [04:12<49:29,  2.24it/s]
 11%|█         | 827/7480 [04:12<49:28,  2.24it/s]

 11%|█         | 828/7480 [04:13<41:14,  2.69it/s]

 11%|█         | 828/7480 [04:13<41:14,  2.69it/s]
 11%|█         | 829/7480 [04:13<41:14,  2.69it/s]

 11%|█         | 830/7480 [04:14<42:10,  2.63it/s]

 11%|█         | 830/7480 [04:14<42:10,  2.63it/s]
 11%|█         | 831/7480 [04:14<42:10,  2.63it/s]

 11%|█         | 832/7480 [04:14<43:02,  2.57it/s]

 11%|█         | 832/7480 [04:14<43:02,  2.57it/s]
 11%|█         | 833/7480 [04:15<43:02,  2.57it/s]

 11%|█         | 834/7480 [04:15<42:52,  2.58it/s]

 11%|█         | 834/7480 [04:15<42:52,  2.58it/s]
 11%|█         | 835/7480 [04:15<42:52,  2.58it/s]

 11%|█         | 836/7480 [04:16<42:31,  2.60it/s]

 11%|█         | 836/7480 [04:16<42:31,  2.60it/s]
 11%|█         | 837/7480 [04:16<42:31,  2.60it/s]

 11%|█         | 838/7480 [04:17<42:33,  2.60it/s]

 11%|█         | 838/7480 [04:17<42:33,  2.60it/s]
 11%|█         | 839/7480 [04:17<42:33,  2.60it/s]

 11%|█         | 840/7480 [04:18<42:48,  2.59it/s]

 11%|█         | 840/7480 [04:18<42:48,  2.59it/s]
 11%|█         | 841/7480 [04:18<42:48,  2.59it/s]

 11%|█▏        | 842/7480 [04:21<1:20:10,  1.38it/s]

 11%|█▏        | 842/7480 [04:21<1:20:10,  1.38it/s]
 11%|█▏        | 843/7480 [04:21<1:20:09,  1.38it/s]

 11%|█▏        | 844/7480 [04:21<1:07:46,  1.63it/s]

 11%|█▏        | 844/7480 [04:21<1:07:46,  1.63it/s]
 11%|█▏        | 845/7480 [04:21<1:07:45,  1.63it/s]

 11%|█▏        | 846/7480 [04:22<59:30,  1.86it/s]

 11%|█▏        | 846/7480 [04:22<59:30,  1.86it/s]
 11%|█▏        | 847/7480 [04:22<59:29,  1.86it/s]
 11%|█▏        | 848/7480 [04:22<59:29,  1.86it/s]

 11%|█▏        | 849/7480 [04:23<46:50,  2.36it/s]

 11%|█▏        | 849/7480 [04:23<46:50,  2.36it/s]
 11%|█▏        | 850/7480 [04:23<46:50,  2.36it/s]
 11%|█▏        | 851/7480 [04:23<46:49,  2.36it/s]

 11%|█▏        | 852/7480 [04:23<39:22,  2.81it/s]

 11%|█▏        | 852/7480 [04:23<39:22,  2.81it/s]
 11%|█▏        | 853/7480 [04:23<39:21,  2.81it/s]

 11%|█▏        | 854/7480 [04:24<39:45,  2.78it/s]

 11%|█▏        | 854/7480 [04:24<39:45,  2.78it/s]
 11%|█▏        | 855/7480 [04:24<39:45,  2.78it/s]

 11%|█▏        | 856/7480 [04:25<39:57,  2.76it/s]

 11%|█▏        | 856/7480 [04:25<39:57,  2.76it/s]
 11%|█▏        | 857/7480 [04:25<39:56,  2.76it/s]

 11%|█▏        | 858/7480 [04:26<39:05,  2.82it/s]

 11%|█▏        | 858/7480 [04:26<39:05,  2.82it/s]
 11%|█▏        | 859/7480 [04:26<39:05,  2.82it/s]
 11%|█▏        | 860/7480 [04:26<39:04,  2.82it/s]

 12%|█▏        | 861/7480 [04:26<33:59,  3.25it/s]

 12%|█▏        | 861/7480 [04:26<33:59,  3.25it/s]
 12%|█▏        | 862/7480 [04:26<33:59,  3.25it/s]

 12%|█▏        | 863/7480 [04:27<35:06,  3.14it/s]

 12%|█▏        | 863/7480 [04:27<35:06,  3.14it/s]
 12%|█▏        | 864/7480 [04:27<35:06,  3.14it/s]

 12%|█▏        | 865/7480 [04:28<35:47,  3.08it/s]

 12%|█▏        | 865/7480 [04:28<35:47,  3.08it/s]
 12%|█▏        | 866/7480 [04:28<35:46,  3.08it/s]

 12%|█▏        | 867/7480 [04:28<36:30,  3.02it/s]

 12%|█▏        | 867/7480 [04:28<36:30,  3.02it/s]
 12%|█▏        | 868/7480 [04:28<36:30,  3.02it/s]

 12%|█▏        | 869/7480 [04:29<37:28,  2.94it/s]

 12%|█▏        | 869/7480 [04:29<37:28,  2.94it/s]
 12%|█▏        | 870/7480 [04:29<37:27,  2.94it/s]

 12%|█▏        | 871/7480 [04:30<37:36,  2.93it/s]

 12%|█▏        | 871/7480 [04:30<37:36,  2.93it/s]
 12%|█▏        | 872/7480 [04:30<37:36,  2.93it/s]

 12%|█▏        | 873/7480 [04:31<37:58,  2.90it/s]

 12%|█▏        | 873/7480 [04:31<37:58,  2.90it/s]
 12%|█▏        | 874/7480 [04:31<37:58,  2.90it/s]

 12%|█▏        | 875/7480 [04:33<1:14:24,  1.48it/s]

 12%|█▏        | 875/7480 [04:33<1:14:24,  1.48it/s]
 12%|█▏        | 876/7480 [04:33<1:14:23,  1.48it/s]

 12%|█▏        | 877/7480 [04:34<1:04:11,  1.71it/s]

 12%|█▏        | 877/7480 [04:34<1:04:11,  1.71it/s]
 12%|█▏        | 878/7480 [04:34<1:04:11,  1.71it/s]

 12%|█▏        | 879/7480 [04:35<55:56,  1.97it/s]

 12%|█▏        | 879/7480 [04:35<55:56,  1.97it/s]
 12%|█▏        | 880/7480 [04:35<55:55,  1.97it/s]

 12%|█▏        | 881/7480 [04:36<51:04,  2.15it/s]

 12%|█▏        | 881/7480 [04:36<51:04,  2.15it/s]
 12%|█▏        | 882/7480 [04:36<51:03,  2.15it/s]

 12%|█▏        | 883/7480 [04:36<47:01,  2.34it/s]

 12%|█▏        | 883/7480 [04:36<47:01,  2.34it/s]
 12%|█▏        | 884/7480 [04:36<47:01,  2.34it/s]

 12%|█▏        | 885/7480 [04:37<44:22,  2.48it/s]

 12%|█▏        | 885/7480 [04:37<44:22,  2.48it/s]
 12%|█▏        | 886/7480 [04:37<44:22,  2.48it/s]

 12%|█▏        | 887/7480 [04:38<43:12,  2.54it/s]

 12%|█▏        | 887/7480 [04:38<43:12,  2.54it/s]
 12%|█▏        | 888/7480 [04:38<43:12,  2.54it/s]

 12%|█▏        | 889/7480 [04:38<42:00,  2.61it/s]

 12%|█▏        | 889/7480 [04:38<42:00,  2.61it/s]
 12%|█▏        | 890/7480 [04:38<42:00,  2.61it/s]

 12%|█▏        | 891/7480 [04:39<41:02,  2.68it/s]

 12%|█▏        | 891/7480 [04:39<41:02,  2.68it/s]
 12%|█▏        | 892/7480 [04:39<41:02,  2.68it/s]
 12%|█▏        | 893/7480 [04:39<41:01,  2.68it/s]
 12%|█▏        | 894/7480 [04:39<41:01,  2.68it/s]
 12%|█▏        | 895/7480 [04:39<41:01,  2.68it/s]
 12%|█▏        | 896/7480 [04:39<41:00,  2.68it/s]

 12%|█▏        | 897/7480 [04:40<25:34,  4.29it/s]

 12%|█▏        | 897/7480 [04:40<25:34,  4.29it/s]
 12%|█▏        | 898/7480 [04:40<25:33,  4.29it/s]

 12%|█▏        | 899/7480 [04:41<28:54,  3.79it/s]

 12%|█▏        | 899/7480 [04:41<28:54,  3.79it/s]
 12%|█▏        | 900/7480 [04:41<28:54,  3.79it/s]

 12%|█▏        | 901/7480 [04:41<30:55,  3.55it/s]

 12%|█▏        | 901/7480 [04:41<30:55,  3.55it/s]
 12%|█▏        | 902/7480 [04:41<30:54,  3.55it/s]
 12%|█▏        | 903/7480 [04:41<30:54,  3.55it/s]

 12%|█▏        | 904/7480 [04:42<29:19,  3.74it/s]

 12%|█▏        | 904/7480 [04:42<29:19,  3.74it/s]
 12%|█▏        | 905/7480 [04:42<29:18,  3.74it/s]

 12%|█▏        | 906/7480 [04:43<32:12,  3.40it/s]

 12%|█▏        | 906/7480 [04:43<32:12,  3.40it/s]
 12%|█▏        | 907/7480 [04:43<32:12,  3.40it/s]

 12%|█▏        | 908/7480 [04:44<40:30,  2.70it/s]

 12%|█▏        | 908/7480 [04:44<40:30,  2.70it/s]
 12%|█▏        | 909/7480 [04:44<40:30,  2.70it/s]

 12%|█▏        | 910/7480 [04:46<1:06:52,  1.64it/s]

 12%|█▏        | 910/7480 [04:46<1:06:52,  1.64it/s]
 12%|█▏        | 911/7480 [04:46<1:06:51,  1.64it/s]

 12%|█▏        | 912/7480 [04:47<59:30,  1.84it/s]

 12%|█▏        | 912/7480 [04:47<59:30,  1.84it/s]
 12%|█▏        | 913/7480 [04:47<59:29,  1.84it/s]
 12%|█▏        | 914/7480 [04:47<59:29,  1.84it/s]
 12%|█▏        | 915/7480 [04:47<59:28,  1.84it/s]

 12%|█▏        | 916/7480 [04:48<41:52,  2.61it/s]

 12%|█▏        | 916/7480 [04:48<41:52,  2.61it/s]
 12%|█▏        | 917/7480 [04:48<41:51,  2.61it/s]
 12%|█▏        | 918/7480 [04:48<41:51,  2.61it/s]

 12%|█▏        | 919/7480 [04:49<36:28,  3.00it/s]

 12%|█▏        | 919/7480 [04:49<36:28,  3.00it/s]
 12%|█▏        | 920/7480 [04:49<36:28,  3.00it/s]

 12%|█▏        | 921/7480 [04:49<37:07,  2.94it/s]

 12%|█▏        | 921/7480 [04:49<37:07,  2.94it/s]
 12%|█▏        | 922/7480 [04:49<37:07,  2.94it/s]

 12%|█▏        | 923/7480 [04:50<37:58,  2.88it/s]

 12%|█▏        | 923/7480 [04:50<37:58,  2.88it/s]
 12%|█▏        | 924/7480 [04:50<37:58,  2.88it/s]

 12%|█▏        | 925/7480 [04:51<37:55,  2.88it/s]

 12%|█▏        | 925/7480 [04:51<37:55,  2.88it/s]
 12%|█▏        | 926/7480 [04:51<37:54,  2.88it/s]
 12%|█▏        | 927/7480 [04:51<37:54,  2.88it/s]

 12%|█▏        | 928/7480 [04:51<34:03,  3.21it/s]

 12%|█▏        | 928/7480 [04:52<34:03,  3.21it/s]
 12%|█▏        | 929/7480 [04:52<34:02,  3.21it/s]

 12%|█▏        | 930/7480 [04:52<35:46,  3.05it/s]

 12%|█▏        | 930/7480 [04:52<35:46,  3.05it/s]
 12%|█▏        | 931/7480 [04:52<35:46,  3.05it/s]

 12%|█▏        | 932/7480 [04:53<36:40,  2.98it/s]

 12%|█▏        | 932/7480 [04:53<36:40,  2.98it/s]
 12%|█▏        | 933/7480 [04:53<36:40,  2.98it/s]

 12%|█▏        | 934/7480 [04:54<37:18,  2.92it/s]

 12%|█▏        | 934/7480 [04:54<37:18,  2.92it/s]
 12%|█▎        | 935/7480 [04:54<37:18,  2.92it/s]

 13%|█▎        | 936/7480 [04:54<37:54,  2.88it/s]

 13%|█▎        | 936/7480 [04:54<37:54,  2.88it/s]
 13%|█▎        | 937/7480 [04:54<37:53,  2.88it/s]

 13%|█▎        | 938/7480 [04:55<39:10,  2.78it/s]

 13%|█▎        | 938/7480 [04:55<39:10,  2.78it/s]
 13%|█▎        | 939/7480 [04:55<39:10,  2.78it/s]

 13%|█▎        | 940/7480 [04:56<38:37,  2.82it/s]

 13%|█▎        | 940/7480 [04:56<38:37,  2.82it/s]
 13%|█▎        | 941/7480 [04:56<38:37,  2.82it/s]
 13%|█▎        | 942/7480 [04:56<38:37,  2.82it/s]
 13%|█▎        | 943/7480 [04:56<38:36,  2.82it/s]

 13%|█▎        | 944/7480 [04:59<58:54,  1.85it/s]

 13%|█▎        | 944/7480 [04:59<58:54,  1.85it/s]
 13%|█▎        | 945/7480 [04:59<58:53,  1.85it/s]

 13%|█▎        | 946/7480 [05:00<54:16,  2.01it/s]

 13%|█▎        | 946/7480 [05:00<54:16,  2.01it/s]
 13%|█▎        | 947/7480 [05:00<54:16,  2.01it/s]

 13%|█▎        | 948/7480 [05:00<50:11,  2.17it/s]

 13%|█▎        | 948/7480 [05:00<50:11,  2.17it/s]
 13%|█▎        | 949/7480 [05:00<50:11,  2.17it/s]

 13%|█▎        | 950/7480 [05:01<47:24,  2.30it/s]

 13%|█▎        | 950/7480 [05:01<47:24,  2.30it/s]
 13%|█▎        | 951/7480 [05:01<47:23,  2.30it/s]

 13%|█▎        | 952/7480 [05:02<45:19,  2.40it/s]

 13%|█▎        | 952/7480 [05:02<45:19,  2.40it/s]
 13%|█▎        | 953/7480 [05:02<45:19,  2.40it/s]

 13%|█▎        | 954/7480 [05:03<43:57,  2.47it/s]
 13%|█▎        | 960/7480 [05:03<20:47,  5.23it/s]

 13%|█▎        | 954/7480 [05:03<43:57,  2.47it/s]
 13%|█▎        | 955/7480 [05:03<43:57,  2.47it/s]
 13%|█▎        | 956/7480 [05:03<43:56,  2.47it/s]
 13%|█▎        | 957/7480 [05:03<43:56,  2.47it/s]
 13%|█▎        | 958/7480 [05:03<43:55,  2.47it/s]
 13%|█▎        | 959/7480 [05:03<43:55,  2.47it/s]
 13%|█▎        | 960/7480 [05:03<20:47,  5.23it/s]
 13%|█▎        | 961/7480 [05:03<20:47,  5.23it/s]

 13%|█▎        | 962/7480 [05:03<25:14,  4.30it/s]

 13%|█▎        | 962/7480 [05:03<25:14,  4.30it/s]
 13%|█▎        | 963/7480 [05:03<25:14,  4.30it/s]

 13%|█▎        | 964/7480 [05:04<29:05,  3.73it/s]

 13%|█▎        | 964/7480 [05:04<29:05,  3.73it/s]
 13%|█▎        | 965/7480 [05:04<29:05,  3.73it/s]

 13%|█▎        | 966/7480 [05:05<31:59,  3.39it/s]

 13%|█▎        | 966/7480 [05:05<31:59,  3.39it/s]
 13%|█▎        | 967/7480 [05:05<31:59,  3.39it/s]

 13%|█▎        | 968/7480 [05:06<34:11,  3.17it/s]

 13%|█▎        | 968/7480 [05:06<34:11,  3.17it/s]
 13%|█▎        | 969/7480 [05:06<34:10,  3.17it/s]

 13%|█▎        | 970/7480 [05:06<35:21,  3.07it/s]

 13%|█▎        | 970/7480 [05:06<35:21,  3.07it/s]
 13%|█▎        | 971/7480 [05:06<35:20,  3.07it/s]

 13%|█▎        | 972/7480 [05:07<36:43,  2.95it/s]

 13%|█▎        | 972/7480 [05:07<36:43,  2.95it/s]
 13%|█▎        | 973/7480 [05:07<36:43,  2.95it/s]
 13%|█▎        | 974/7480 [05:07<36:43,  2.95it/s]
 13%|█▎        | 975/7480 [05:07<36:42,  2.95it/s]

 13%|█▎        | 976/7480 [05:08<29:15,  3.71it/s]

 13%|█▎        | 976/7480 [05:08<29:15,  3.71it/s]
 13%|█▎        | 977/7480 [05:08<29:14,  3.71it/s]

 13%|█▎        | 978/7480 [05:09<31:48,  3.41it/s]

 13%|█▎        | 978/7480 [05:09<31:48,  3.41it/s]
 13%|█▎        | 979/7480 [05:09<31:48,  3.41it/s]

 13%|█▎        | 980/7480 [05:12<1:05:18,  1.66it/s]

 13%|█▎        | 980/7480 [05:12<1:05:18,  1.66it/s]
 13%|█▎        | 981/7480 [05:12<1:05:17,  1.66it/s]

 13%|█▎        | 982/7480 [05:12<58:42,  1.84it/s]

 13%|█▎        | 982/7480 [05:12<58:42,  1.84it/s]
 13%|█▎        | 983/7480 [05:12<58:42,  1.84it/s]

 13%|█▎        | 984/7480 [05:13<53:17,  2.03it/s]

 13%|█▎        | 984/7480 [05:13<53:17,  2.03it/s]
 13%|█▎        | 985/7480 [05:13<53:17,  2.03it/s]

 13%|█▎        | 986/7480 [05:14<48:56,  2.21it/s]

 13%|█▎        | 986/7480 [05:14<48:56,  2.21it/s]
 13%|█▎        | 987/7480 [05:14<48:56,  2.21it/s]
 13%|█▎        | 988/7480 [05:14<48:55,  2.21it/s]

 13%|█▎        | 989/7480 [05:15<40:17,  2.69it/s]

 13%|█▎        | 989/7480 [05:15<40:17,  2.69it/s]
 13%|█▎        | 990/7480 [05:15<40:16,  2.69it/s]
 13%|█▎        | 991/7480 [05:15<40:16,  2.69it/s]

 13%|█▎        | 992/7480 [05:15<35:24,  3.05it/s]
 13%|█▎        | 996/7480 [05:15<22:18,  4.84it/s]

 13%|█▎        | 992/7480 [05:15<35:24,  3.05it/s]
 13%|█▎        | 993/7480 [05:15<35:24,  3.05it/s]
 13%|█▎        | 994/7480 [05:15<35:23,  3.05it/s]
 13%|█▎        | 995/7480 [05:15<35:23,  3.05it/s]
 13%|█▎        | 996/7480 [05:15<22:18,  4.84it/s]
 13%|█▎        | 997/7480 [05:15<22:18,  4.84it/s]

 13%|█▎        | 998/7480 [05:16<26:23,  4.09it/s]

 13%|█▎        | 998/7480 [05:16<26:23,  4.09it/s]
 13%|█▎        | 999/7480 [05:16<26:23,  4.09it/s]

 13%|█▎        | 1000/7480 [05:17<34:16,  3.15it/s]
100%|██████████| 9/9 [44:52<00:00, 299.12s/it]

 13%|█▎        | 1000/7480 [05:17<29:04,  3.71it/s]
                     MLUT4_AT.232A  MLUT4_RQ.2BTLS  MLUT4_TE.252A  \
Time
2025-05-25 05:20:05       0.852984        0.855904       0.842414
2025-05-25 05:30:05       0.876511        0.874611       0.847393
2025-05-25 05:35:05       0.877479        0.885625       0.860507
2025-05-25 05:40:05       0.878625        0.849563       0.860377
2025-05-25 05:45:05       0.877141        0.871733       0.849503

                     MLUT4_SIV.B7921  MLUT4_AIA792101B  MLUT4_PDT.956  \
Time
2025-05-25 05:20:05         0.903258          0.872434       0.899219
2025-05-25 05:30:05         0.903158          0.872244       0.916372
2025-05-25 05:35:05         0.903349          0.872158       0.914016
2025-05-25 05:40:05         0.903300          0.872148       0.910043
2025-05-25 05:45:05         0.903219          0.872148       0.914286

                     MLUT4_TE.252F  MLUT4_PT.231  MLUT4_FIC.231C  \
Time
2025-05-25 05:20:05       0.887579      0.869354        0.857897
2025-05-25 05:30:05       0.879727      0.867235        0.857888
2025-05-25 05:35:05       0.893944      0.867041        0.857883
2025-05-25 05:40:05       0.872940      0.866275        0.857879
2025-05-25 05:45:05       0.876962      0.865383        0.857874

                     MLUT4_FIC.231A  ...  DeSOx_2nd  MLUT4_AIC.232B  \
Time                                 ...
2025-05-25 05:20:05        0.859975  ...   0.881549       85.012138
2025-05-25 05:30:05        0.856716  ...   0.881163       88.954571
2025-05-25 05:35:05        0.860662  ...   0.881567       93.745851
2025-05-25 05:40:05        0.859286  ...   0.881785       85.305571
2025-05-25 05:45:05        0.859582  ...   0.881516      101.874866

                     MLUT4_AT.240  prev_target  MLUT4_AT-240  prediction  \
Time
2025-05-25 05:20:05     14.151761     0.888806     10.069804    0.882158
2025-05-25 05:30:05      9.316637     0.890104     10.571075    0.881741
2025-05-25 05:35:05      6.155893     0.890862     11.102642    0.881659
2025-05-25 05:40:05     12.572007     0.891577     10.084373    0.881888
2025-05-25 05:45:05      5.497275     0.891864     12.070540    0.881939

                     abs_error  threshold  y3_prediction  y3_abs_error
Time
2025-05-25 05:20:05   0.000609   0.000609      10.018037      0.051767
2025-05-25 05:30:05   0.000578   0.000606      10.519674      0.051401
2025-05-25 05:35:05   0.000092   0.000603      11.093997      0.008645
2025-05-25 05:40:05   0.000103   0.000600      10.075609      0.008764
2025-05-25 05:45:05   0.000423   0.000596      12.027431      0.043109

[5 rows x 50 columns]

In [25]:
import pandas as pd

combined_df = pd.DataFrame()

for idx, item in enumerate(df_metrics_list):
    # 假設每個 item 都有一欄叫 'Metric'，並在轉置後只取一列數據
    row = item.set_index('Metric').T.iloc[0]
    combined_df = pd.concat([combined_df, row], axis=1)

# 命名欄位
combined_df.columns = [f't+{i}' for i in range(1, len(df_metrics_list)+1)]

combined_df

,t+1,t+2,t+3,t+4,t+5,t+6,t+7,t+8,t+9
R-squared,0.968732,0.968565,0.955121,0.9557,0.958101,0.956785,0.951925,0.959627,0.955592
RMSE,0.006194,0.006378,0.007443,0.007514,0.007461,0.00742,0.007882,0.007364,0.007907
MAPE,0.541583,0.572122,0.643207,0.661034,0.670432,0.675741,0.720029,0.655624,0.702849

In [26]:
import pandas as pd

combined_df = pd.DataFrame()

for idx, item in enumerate(df_metrics_list_y3):
    # 假設每個 item 都有一欄叫 'Metric'，並在轉置後只取一列數據
    row = item.set_index('Metric').T.iloc[0]
    combined_df = pd.concat([combined_df, row], axis=1)

# 命名欄位
combined_df.columns = [f't+{i}' for i in range(1, len(df_metrics_list_y3)+1)]

combined_df

,t+1,t+2,t+3,t+4,t+5,t+6,t+7,t+8,t+9
R-squared,0.936964,0.932952,0.912495,0.918836,0.918303,0.917389,0.903859,0.916303,0.906048
RMSE,0.407693,0.417363,0.48892,0.476159,0.474826,0.468252,0.512908,0.47179,0.514294
MAPE,3.061258,3.245775,3.707015,3.68289,3.790514,3.732289,4.04246,3.675736,3.968032