<a href="https://colab.research.google.com/github/skywalker0803r/CFB/blob/main/%E6%BB%BE%E5%8B%95%E5%BC%8F%E9%A0%90%E6%B8%ACy2_300%E9%96%93%E9%9A%94_95%25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:


# Colab 進行matplotlib繪圖時顯示繁體中文
# 下載台北思源黑體並命名taipei_sans_tc_beta.ttf，移至指定路徑
!wget -O TaipeiSansTCBeta-Regular.ttf https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download

import matplotlib
import numpy as np

# 改style要在改font之前
# plt.style.use('seaborn')

matplotlib.font_manager.fontManager.addfont('TaipeiSansTCBeta-Regular.ttf')
matplotlib.rc('font', family='Taipei Sans TC Beta')

--2025-06-28 01:57:21--  https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_
Resolving drive.google.com (drive.google.com)... 172.217.12.14, 2607:f8b0:4025:810::200e
Connecting to drive.google.com (drive.google.com)|172.217.12.14|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_ [following]
--2025-06-28 01:57:21--  https://drive.usercontent.google.com/download?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 172.217.12.1, 2607:f8b0:4025:810::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|172.217.12.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20659344 (20M) [application/octet-stream]
Saving to: ‘TaipeiSansTCBeta-Regular.ttf’

TaipeiSansTCBeta-Re 100%[===================>]  19.70M  52.2MB/s    in 0.4s

2025-06-28 01:57:27 (52.2 MB/s) - ‘TaipeiSansTCBeta-Regular.ttf’ saved [20659344/20659344]

In [2]:

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/脫硫劑優化改善/20240916-CFB2脫硫劑優化改善.xlsx')
col = df.columns
df = df.iloc[1:,:]
df.columns = col
df = df.set_index('Unnamed: 0')
df.index.name = 'datetime'
df

Mounted at /content/drive

/usr/local/lib/python3.11/dist-packages/pandas/core/indexes/base.py:7588: FutureWarning: Dtype inference on a pandas object (Series, Index, ExtensionArray) is deprecated. The Index constructor will keep the original dtype in the future. Call `infer_objects` on the result to get the old behavior.
  return Index(sequences[0], name=names)

,MLUT4_AIA792101A,MLUT4_AIA792101B,MLUT4_AIC-232B,MLUT4_AT-232A,MLUT4_AT-237,MLUT4_AT-240,MLUT4_AT-240A,MLUT4_FIC-231A,MLUT4_FIC-231B,MLUT4_FIC-231C,...,MLUT4_TE-252F,MLUT4_TE-252G,MLUT4_TE-252H,MLUT4_TE-252I,MLUT4_ZT-231,MLUT4_ZT-232,DeSOx_1st,DeSOx_2nd,前爐SOx濃度,鈣硫比
datetime,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00,5.540932,6.8,67.034424,151.208024,9.623605,8.619934,8.619934,20.605973,0,17.456094,...,876.984866,845.297084,845.703201,876.997523,59.200001,15,0.969941,0.871410,2230.093232,2.223152
2024-01-01 00:05:00,5.533478,6.8,66.662524,150.811453,9.616252,8.147002,8.147002,20.18102,0,17.449118,...,875.326466,846.587071,844.10285,877.38106,59.200001,15,0.969979,0.877787,2220.527929,2.220789
2024-01-01 00:10:00,5.526025,6.8,64.320729,151.708113,9.608899,8.247992,8.247992,20.200619,0,17.442142,...,875.675699,845.374599,843.500123,877.8976,59.200001,15,0.971249,0.871768,2237.129686,2.217612
2024-01-01 00:15:00,5.518571,6.801543,64.840762,151.283528,9.600898,7.60582,7.60582,20.220218,0,17.571883,...,875.435828,845.10045,842.910508,874.888616,59.200001,15,0.970896,0.882700,2227.895501,2.214444
2024-01-01 00:20:00,5.511117,6.819977,64.390831,150.994896,9.581994,6.110485,6.110485,20.549012,0,17.339679,...,875.2454,846.058978,844.200021,878.41671,59.200001,15,0.970878,0.905103,2211.052236,2.211285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-15 23:35:00,6.258452,5.140339,114.166438,209.520746,9.360355,13.105704,13.105704,12.795748,11.854892,12.8422,...,916.635699,889.885541,906.016252,870.865216,100,26.103367,0.945172,0.885205,2082.274527,3.928554
2024-09-15 23:40:00,6.284992,5.166336,106.669841,208.177318,9.280099,9.903673,9.903673,12.797045,11.862273,12.823741,...,914.06561,889.042164,904.255862,869.007829,100,26.093265,0.948517,0.907156,2071.948976,3.927730
2024-09-15 23:45:00,6.232171,5.225976,104.663595,211.564232,9.359701,9.345572,9.345572,12.798342,11.880556,12.842696,...,913.978871,890.439554,903.442876,867.71297,100,26.1,0.949882,0.910708,2088.339754,3.928170
2024-09-15 23:50:00,6.20333,5.14117,103.246788,206.570014,9.211132,8.303164,8.303164,12.799638,11.926489,12.825216,...,913.419379,887.270132,903.808073,867.684024,100,26.078118,0.949256,0.919579,2034.665472,3.927928
2024-09-15 23:55:00,6.007071,4.972081,110.111657,209.432213,9.231066,8.933592,8.933592,12.800935,11.864035,12.803276,...,914.723621,889.081017,905.085873,868.045556,100,26.066269,0.946246,0.918868,2048.422596,3.928171

In [3]:
for i in df.columns:
  df[i] = pd.to_numeric(df[i], errors='coerce')
df

,MLUT4_AIA792101A,MLUT4_AIA792101B,MLUT4_AIC-232B,MLUT4_AT-232A,MLUT4_AT-237,MLUT4_AT-240,MLUT4_AT-240A,MLUT4_FIC-231A,MLUT4_FIC-231B,MLUT4_FIC-231C,...,MLUT4_TE-252F,MLUT4_TE-252G,MLUT4_TE-252H,MLUT4_TE-252I,MLUT4_ZT-231,MLUT4_ZT-232,DeSOx_1st,DeSOx_2nd,前爐SOx濃度,鈣硫比
datetime,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00,5.540932,6.800000,67.034424,151.208024,9.623605,8.619934,8.619934,20.605973,0.000000,17.456094,...,876.984866,845.297084,845.703201,876.997523,59.200001,15.000000,0.969941,0.871410,2230.093232,2.223152
2024-01-01 00:05:00,5.533478,6.800000,66.662524,150.811453,9.616252,8.147002,8.147002,20.181020,0.000000,17.449118,...,875.326466,846.587071,844.102850,877.381060,59.200001,15.000000,0.969979,0.877787,2220.527929,2.220789
2024-01-01 00:10:00,5.526025,6.800000,64.320729,151.708113,9.608899,8.247992,8.247992,20.200619,0.000000,17.442142,...,875.675699,845.374599,843.500123,877.897600,59.200001,15.000000,0.971249,0.871768,2237.129686,2.217612
2024-01-01 00:15:00,5.518571,6.801543,64.840762,151.283528,9.600898,7.605820,7.605820,20.220218,0.000000,17.571883,...,875.435828,845.100450,842.910508,874.888616,59.200001,15.000000,0.970896,0.882700,2227.895501,2.214444
2024-01-01 00:20:00,5.511117,6.819977,64.390831,150.994896,9.581994,6.110485,6.110485,20.549012,0.000000,17.339679,...,875.245400,846.058978,844.200021,878.416710,59.200001,15.000000,0.970878,0.905103,2211.052236,2.211285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-15 23:35:00,6.258452,5.140339,114.166438,209.520746,9.360355,13.105704,13.105704,12.795748,11.854892,12.842200,...,916.635699,889.885541,906.016252,870.865216,100.000000,26.103367,0.945172,0.885205,2082.274527,3.928554
2024-09-15 23:40:00,6.284992,5.166336,106.669841,208.177318,9.280099,9.903673,9.903673,12.797045,11.862273,12.823741,...,914.065610,889.042164,904.255862,869.007829,100.000000,26.093265,0.948517,0.907156,2071.948976,3.927730
2024-09-15 23:45:00,6.232171,5.225976,104.663595,211.564232,9.359701,9.345572,9.345572,12.798342,11.880556,12.842696,...,913.978871,890.439554,903.442876,867.712970,100.000000,26.100000,0.949882,0.910708,2088.339754,3.928170
2024-09-15 23:50:00,6.203330,5.141170,103.246788,206.570014,9.211132,8.303164,8.303164,12.799638,11.926489,12.825216,...,913.419379,887.270132,903.808073,867.684024,100.000000,26.078118,0.949256,0.919579,2034.665472,3.927928
2024-09-15 23:55:00,6.007071,4.972081,110.111657,209.432213,9.231066,8.933592,8.933592,12.800935,11.864035,12.803276,...,914.723621,889.081017,905.085873,868.045556,100.000000,26.066269,0.946246,0.918868,2048.422596,3.928171

# 篩選資料

In [4]:
coal_low = df[df["MLUT4_FIQ-2BTCF"] < 20]
sox = df["MLUT4_AT-240"]
constant_sox_indices = sox[sox.shift(1) == sox][(sox.shift(2) == sox) & (sox.shift(-1) == sox)].index
constant_sox = df.loc[constant_sox_indices]
common_index = coal_low.index.union(constant_sox.index)
select_df = df.loc[~df.index.isin(common_index), :]
select_df[["MLUT4_FIQ-2BTCF","MLUT4_AT-240"]]

                     MLUT4_FIQ-2BTCF  MLUT4_AT-240
datetime
2024-01-01 00:00:00        37.784191      8.619934
2024-01-01 00:05:00        37.824395      8.147002
2024-01-01 00:10:00        37.878584      8.247992
2024-01-01 00:15:00        37.932773      7.605820
2024-01-01 00:20:00        37.986962      6.110485
...                              ...           ...
2024-09-15 23:35:00        35.636522     13.105704
2024-09-15 23:40:00        35.644001      9.903673
2024-09-15 23:45:00        35.640006      9.345572
2024-09-15 23:50:00        35.642203      8.303164
2024-09-15 23:55:00        35.639999      8.933592

[53717 rows x 2 columns]

# 檢查篩選結果

In [5]:
import plotly.express as px

# 假設 df 是你的 DataFrame
fig = px.scatter(
    select_df[["MLUT4_FIQ-2BTCF","MLUT4_AT-240"]],
    x="MLUT4_FIQ-2BTCF",
    y="MLUT4_AT-240",
    title="MLUT4_FIQ-2BTCF vs MLUT4_AT-240 散點圖",
    labels={
        "MLUT4_FIQ-2BTCF": "FIQ-2BTCF",
        "MLUT4_AT-240": "AT-240"
    }
)

fig.show()

# columns select

In [7]:
import pickle

with open("/content/features2.pkl", "rb") as f:
    features = pickle.load(f)
features

['MLUT4_FT-956',
 'MLUT4_FT-957',
 'MLUT4_FIC-231C',
 'MLUT4_FIC-231B',
 'MLUT4_PDT-232',
 'MLUT4_PIC-233',
 'MLUT4_FIC-231A',
 'MLUT4_TE-252D',
 'MLUT4_FQ-239',
 'MLUT4_IT-E7925B',
 'MLUT4_RT-091',
 'MLUT4_AIA792101B',
 'MLUT4_FT-792020',
 'MLUT4_TE-251H',
 'MLUT4_AT-232A',
 'MLUT4_TE-252I',
 'MLUT4_IT-E7925A',
 'MLUT4_FQ-205',
 'MLUT4_FIC-233',
 'MLUT4_ZT-232',
 'MLUT4_FT-V004',
 'MLUT4_PT-231',
 'MLUT4_FT-232',
 'MLUT4_AT-237',
 'MLUT4_FT-951AB']

In [8]:
df.columns

Index(['MLUT4_AIA792101A', 'MLUT4_AIA792101B', 'MLUT4_AIC-232B',
       'MLUT4_AT-232A', 'MLUT4_AT-237', 'MLUT4_AT-240', 'MLUT4_AT-240A',
       'MLUT4_FIC-231A', 'MLUT4_FIC-231B', 'MLUT4_FIC-231C', 'MLUT4_FIC-233',
       'MLUT4_FIQ-2BTCF', 'MLUT4_FQ-205', 'MLUT4_FQ-239', 'MLUT4_FT-232',
       'MLUT4_FT-792003', 'MLUT4_FT-792020', 'MLUT4_FT-951AA',
       'MLUT4_FT-951AB', 'MLUT4_FT-956', 'MLUT4_FT-957', 'MLUT4_FT-V004',
       'MLUT4_IT-E7925A', 'MLUT4_IT-E7925B', 'MLUT4_PDIC-233', 'MLUT4_PDT-231',
       'MLUT4_PDT-232', 'MLUT4_PIC-233', 'MLUT4_PT-231', 'MLUT4_RQ-2BTLS',
       'MLUT4_RT-031', 'MLUT4_RT-041', 'MLUT4_RT-051', 'MLUT4_RT-081',
       'MLUT4_RT-091', 'MLUT4_SIV-B7921', 'MLUT4_TE-251A', 'MLUT4_TE-251B',
       'MLUT4_TE-251C', 'MLUT4_TE-251D', 'MLUT4_TE-251E', 'MLUT4_TE-251F',
       'MLUT4_TE-251G', 'MLUT4_TE-251H', 'MLUT4_TE-251I', 'MLUT4_TE-252A',
       'MLUT4_TE-252B', 'MLUT4_TE-252C', 'MLUT4_TE-252D', 'MLUT4_TE-252E',
       'MLUT4_TE-252F', 'MLUT4_TE-252G', 'MLUT4_TE-252H', 'MLUT4_TE-252I',
       'MLUT4_ZT-231', 'MLUT4_ZT-232', 'DeSOx_1st', 'DeSOx_2nd', '前爐SOx濃度',
       '鈣硫比'],
      dtype='object')

In [9]:
y_col = 'DeSOx_2nd'

In [10]:
select_df = select_df[features+[y_col]]
select_df = select_df[
    (~np.isinf(select_df[y_col])) &
    (~np.isnan(select_df[y_col]))
]
select_df

,MLUT4_FT-956,MLUT4_FT-957,MLUT4_FIC-231C,MLUT4_FIC-231B,MLUT4_PDT-232,MLUT4_PIC-233,MLUT4_FIC-231A,MLUT4_TE-252D,MLUT4_FQ-239,MLUT4_IT-E7925B,...,MLUT4_IT-E7925A,MLUT4_FQ-205,MLUT4_FIC-233,MLUT4_ZT-232,MLUT4_FT-V004,MLUT4_PT-231,MLUT4_FT-232,MLUT4_AT-237,MLUT4_FT-951AB,DeSOx_2nd
datetime,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00,3992.840799,3917.594740,17.456094,0.000000,78.370626,971.286903,20.605973,861.535652,354.292802,17.254982,...,13.302897,357.373726,179.388400,15.000000,0.00,1393.855901,359.664266,9.623605,99.231466,0.871410
2024-01-01 00:05:00,3988.473250,3917.320459,17.449118,0.000000,79.258313,969.395192,20.181020,860.299612,356.197588,17.324028,...,13.276501,356.975651,179.313536,15.000000,0.00,1393.743589,359.556551,9.616252,100.033768,0.877787
2024-01-01 00:10:00,3984.113830,3913.623750,17.442142,0.000000,77.719304,969.959118,20.200619,858.073290,354.060762,17.168178,...,13.300000,355.650485,179.519411,15.000000,0.00,1393.414400,355.172410,9.608899,99.932670,0.871768
2024-01-01 00:15:00,3984.936436,3929.257511,17.571883,0.000000,78.297800,971.875751,20.220218,858.422111,356.036892,17.308134,...,13.300000,356.219519,179.465741,15.000000,0.00,1393.990782,355.875036,9.600898,99.831572,0.882700
2024-01-01 00:20:00,3985.762194,3914.198450,17.339679,0.000000,78.501901,971.082502,20.549012,859.316649,359.261589,17.241191,...,13.275966,357.409226,179.344261,15.000000,0.00,1394.205901,356.333792,9.581994,100.181768,0.905103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-15 23:35:00,2630.971265,2639.985169,12.842200,11.854892,55.084016,954.066222,12.795748,928.560012,357.875976,15.681699,...,12.774718,307.745677,227.094066,26.103367,1.87,1361.905776,243.293496,9.360355,97.405392,0.885205
2024-09-15 23:40:00,2637.921800,2644.140047,12.823741,11.862273,54.970461,956.169561,12.797045,926.909370,359.734934,15.637485,...,12.769719,308.234169,226.873818,26.093265,1.87,1364.378553,241.649951,9.280099,97.528753,0.907156
2024-09-15 23:45:00,2635.895821,2636.322947,12.842696,11.880556,54.838819,958.502714,12.798342,926.152206,356.871482,15.715107,...,12.744950,304.988863,227.212922,26.100000,1.87,1368.033108,244.585288,9.359701,98.286113,0.910708
2024-09-15 23:50:00,2632.967159,2642.628602,12.825216,11.926489,54.834999,958.410063,12.799638,926.129445,366.308293,15.626760,...,12.776424,303.951692,227.050551,26.078118,1.87,1366.118718,245.330280,9.211132,99.519681,0.919579
2024-09-15 23:55:00,2636.355238,2636.768716,12.803276,11.864035,55.918399,955.994182,12.800935,926.943748,363.825685,15.657431,...,12.774641,306.157085,227.420687,26.066269,1.87,1362.451729,249.288039,9.231066,98.966342,0.918868

預測目標:DeSOx_1st 其餘為特徵

1. 先將數據select_df依據時間排序。

2. 自第1001筆開始，取用前1000筆數據建立rf模型，評估建模數據的"預測誤差絕對值"，計算前述數值的第80百分位數當成"門檻值"。

3. 運用2.的模型執行第1001筆的預測。

4. 比對3.的結果之"預測誤差絕對值"。若此數值超過"門檻值"，則第1002筆預測重複2.＆3.步驟；若此數值不超過"門檻值"，直接運用2.的模型執行第1002筆的預測。

5. 之後以此類推....

In [11]:
select_df.columns

Index(['MLUT4_FT-956', 'MLUT4_FT-957', 'MLUT4_FIC-231C', 'MLUT4_FIC-231B',
       'MLUT4_PDT-232', 'MLUT4_PIC-233', 'MLUT4_FIC-231A', 'MLUT4_TE-252D',
       'MLUT4_FQ-239', 'MLUT4_IT-E7925B', 'MLUT4_RT-091', 'MLUT4_AIA792101B',
       'MLUT4_FT-792020', 'MLUT4_TE-251H', 'MLUT4_AT-232A', 'MLUT4_TE-252I',
       'MLUT4_IT-E7925A', 'MLUT4_FQ-205', 'MLUT4_FIC-233', 'MLUT4_ZT-232',
       'MLUT4_FT-V004', 'MLUT4_PT-231', 'MLUT4_FT-232', 'MLUT4_AT-237',
       'MLUT4_FT-951AB', 'DeSOx_2nd'],
      dtype='object')

In [12]:
select_df.isnull().sum().sum()

np.int64(0)

In [13]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from tqdm import tqdm
import warnings
warnings.filterwarnings("ignore")

# ======================== 使用者自定義超參數 ==========================
PERCENTILE_THRESHOLD = 95     # 門檻百分位
PREDICTION_INTERVAL = 300     # 每次預測區間 (筆數)
MAX_STEPS = 1000              # 最多預測幾次（非總筆數）
WINDOW_SIZE = 1000            # 每次用多少資料訓練
# =====================================================================

# 1. 資料排序
select_df = select_df.sort_index().reset_index(drop=True)

# 2. 設定欄位
target_col = y_col
feature_cols = [col for col in select_df.columns if col not in ['timestamp', target_col]]
start_idx = WINDOW_SIZE

# 3. 儲存預測結果
predictions = []
abs_errors = []
thresholds = []
indices = []

# 4. 初始化進度條
pbar = tqdm(total=MAX_STEPS)

# 5. 初始模型與門檻
model = None
cached_threshold = None

# 6. 開始迴圈
i = start_idx
while i + PREDICTION_INTERVAL <= len(select_df):
    if pbar.n >= MAX_STEPS:
        print(f"已達 {MAX_STEPS} 步，提前結束迴圈")
        break

    retrain_model = False

    # 如果還沒模型，或是前次預測誤差超門檻 → 重訓
    if model is None:
        retrain_model = True
    else:
        # 快速預測一整段並計算誤差
        test_df = select_df.iloc[i:i+PREDICTION_INTERVAL]
        test_X = test_df[feature_cols]
        true_y = test_df[target_col].values
        preds = model.predict(test_X)
        errors = np.abs(preds - true_y)

        # 如果任一筆超門檻 → 重訓
        if cached_threshold is not None and np.any(errors > cached_threshold):
            retrain_model = True

    if retrain_model:
        train_df = select_df.iloc[i - WINDOW_SIZE:i]
        train_X = train_df[feature_cols]
        train_y = train_df[target_col]

        model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
        model.fit(train_X, train_y)

        train_preds = model.predict(train_X)
        train_errors = np.abs(train_preds - train_y)
        cached_threshold = np.percentile(train_errors, PERCENTILE_THRESHOLD)

        # 預測下一段（剛好可以重用 test_df）
        test_df = select_df.iloc[i:i+PREDICTION_INTERVAL]
        test_X = test_df[feature_cols]
        true_y = test_df[target_col].values
        preds = model.predict(test_X)
        errors = np.abs(preds - true_y)

    # 紀錄整段結果
    idx_range = list(range(i, i + PREDICTION_INTERVAL))
    predictions.extend(preds.tolist())
    abs_errors.extend(errors.tolist())
    thresholds.extend([cached_threshold] * len(preds))
    indices.extend(idx_range)

    pbar.update(1)
    i += PREDICTION_INTERVAL

pbar.close()

# 7. 輸出結果表
result_df = select_df.loc[indices].copy()
result_df['prediction'] = predictions
result_df['abs_error'] = abs_errors
result_df['threshold'] = thresholds

result_df.head()

 17%|█▋        | 172/1000 [07:02<33:55,  2.46s/it]

,MLUT4_FT-956,MLUT4_FT-957,MLUT4_FIC-231C,MLUT4_FIC-231B,MLUT4_PDT-232,MLUT4_PIC-233,MLUT4_FIC-231A,MLUT4_TE-252D,MLUT4_FQ-239,MLUT4_IT-E7925B,...,MLUT4_ZT-232,MLUT4_FT-V004,MLUT4_PT-231,MLUT4_FT-232,MLUT4_AT-237,MLUT4_FT-951AB,DeSOx_2nd,prediction,abs_error,threshold
1000,3982.933325,3936.791882,20.747748,0.0,108.214745,1102.994320,22.632297,894.113646,439.918414,17.033064,...,14.9,0.0,1406.945243,330.686470,6.675483,95.036593,0.912031,0.907622,0.004409,0.022871
1001,3983.544241,3929.114039,20.960797,0.0,107.243364,1103.196519,22.628941,895.076073,439.210893,16.983876,...,14.9,0.0,1408.903645,333.591439,6.661739,95.353668,0.902823,0.905920,0.003096,0.022871
1002,3985.621893,3932.630585,21.395041,0.0,107.787313,1102.844015,22.625585,895.779150,438.327778,17.100930,...,14.9,0.0,1405.631145,337.282611,6.647995,95.629688,0.887299,0.906567,0.019268,0.022871
1003,3982.279510,3933.459131,21.195365,0.0,107.991793,1102.583847,22.622228,896.204024,440.688510,17.007116,...,14.9,0.0,1407.407529,340.031637,6.634251,95.528780,0.883433,0.907920,0.024487,0.022871
1004,3979.527359,3935.727198,20.726037,0.0,107.857274,1101.892047,22.618872,896.507485,439.515343,17.061303,...,14.9,0.0,1405.892220,331.664549,6.620507,95.852248,0.883650,0.904438,0.020788,0.022871

In [14]:
result_df[[y_col,'prediction','abs_error','threshold']]

       DeSOx_2nd  prediction  abs_error  threshold
1000    0.912031    0.907622   0.004409   0.022871
1001    0.902823    0.905920   0.003096   0.022871
1002    0.887299    0.906567   0.019268   0.022871
1003    0.883433    0.907920   0.024487   0.022871
1004    0.883650    0.904438   0.020788   0.022871
...          ...         ...        ...        ...
52595   0.905129    0.875714   0.029414   0.010847
52596   0.918045    0.876285   0.041760   0.010847
52597   0.906779    0.873891   0.032888   0.010847
52598   0.911114    0.871978   0.039136   0.010847
52599   0.907466    0.873497   0.033968   0.010847

[51600 rows x 4 columns]

In [15]:
result_df.loc['AVG',:] = result_df[[y_col,'prediction','abs_error','threshold']].mean(axis=0)
result_df[[y_col,'prediction','abs_error','threshold']]

       DeSOx_2nd  prediction  abs_error  threshold
1000    0.912031    0.907622   0.004409   0.022871
1001    0.902823    0.905920   0.003096   0.022871
1002    0.887299    0.906567   0.019268   0.022871
1003    0.883433    0.907920   0.024487   0.022871
1004    0.883650    0.904438   0.020788   0.022871
...          ...         ...        ...        ...
52596   0.918045    0.876285   0.041760   0.010847
52597   0.906779    0.873891   0.032888   0.010847
52598   0.911114    0.871978   0.039136   0.010847
52599   0.907466    0.873497   0.033968   0.010847
AVG     0.740797    0.338905   0.618532   0.048936

[51601 rows x 4 columns]

In [16]:
import plotly.express as px

fig = px.line(result_df, y='abs_error', title='Absolute Error over Samples')
fig.show()